import type { AssessmentDef, AssessmentQuestionDef } from '../types'

const mc = (q: string, opts: string[], ans: string, exp: string, pts: number, ord: number): AssessmentQuestionDef =>
  ({ question: q, type: 'MULTIPLE_CHOICE', options: opts, correctAnswer: ans, explanation: exp, points: pts, order: ord })

const oe = (q: string, ans: string, exp: string, pts: number, ord: number): AssessmentQuestionDef =>
  ({ question: q, type: 'OPEN_ENDED', correctAnswer: ans, explanation: exp, points: pts, order: ord })

export const artsAssessments: Record<string, AssessmentDef> = {
  'visual-art-fundamentals': {
    title: 'Visual Art Fundamentals Assessment',
    passingScore: 75,
    timeLimitMin: 30,
    questions: [
      mc('What are the primary colors in traditional (subtractive) color theory?', ['Red, green, blue', 'Red, yellow, blue', 'Cyan, magenta, yellow', 'Orange, green, purple'], 'Red, yellow, blue', 'Traditional art uses red, yellow, and blue as primaries — they cannot be made by mixing other colors. Mixing them produces secondary colors (orange, green, purple).', 1, 1),
      mc('What is the rule of thirds in composition?', ['Dividing a canvas into thirds for color mixing', 'A guideline placing subjects at intersections of lines that divide the image into a 3×3 grid', 'Limiting a composition to three main elements', 'Painting in three layers'], 'A guideline placing subjects at intersections of lines that divide the image into a 3×3 grid', 'The rule of thirds suggests placing key subjects at the intersections of imaginary grid lines — creating more dynamic, balanced compositions than centering everything.', 1, 2),
      mc('What is value in visual art?', ['The monetary worth of a work', 'The lightness or darkness of a color or tone', 'The texture of a surface', 'The size of a composition'], 'The lightness or darkness of a color or tone', 'Value is one of the elements of art — the range from light (highlight) to dark (shadow). Controlling value creates depth, form, and contrast.', 1, 3),
      mc('What is negative space?', ['Empty or wasted areas in a composition', 'The space around and between subjects in a composition', 'Dark areas in a painting', 'Background elements'], 'The space around and between subjects in a composition', 'Negative space is as much a design element as positive space (the subject). Skillful use of negative space creates balance, rhythm, and visual interest.', 1, 4),
      mc('What does "contour line" mean in drawing?', ['A line following the outline or edge of a form', 'Vertical lines creating texture', 'The horizon line in a landscape', 'Crosshatching for shading'], 'A line following the outline or edge of a form', 'Contour drawing follows the edges and surface ridges of a subject. Blind contour drawing (without looking at the paper) trains hand-eye coordination.', 1, 5),
      mc('What is complementary colors?', ['Colors that match or are similar', 'Colors opposite each other on the color wheel — they create maximum contrast when placed together', 'Colors used together frequently in art history', 'Colors that can be mixed to create neutral tones'], 'Colors opposite each other on the color wheel — they create maximum contrast when placed together', 'Complementary pairs: red/green, blue/orange, yellow/purple. Placed together, they vibrate visually; mixed together, they neutralize to gray/brown.', 1, 6),
      mc('What is proportion in art?', ['The size of the canvas', 'The size relationship between different parts of a composition or figure', 'The weight of paint applied', 'The number of figures in a scene'], 'The size relationship between different parts of a composition or figure', 'Proportion describes how parts relate to each other and to the whole. Accurate proportion creates believable figures and spatial relationships; distorted proportion can be used expressively.', 1, 7),
      mc('What is a focal point in a composition?', ['The center of the canvas', 'The area that draws the viewer\'s eye first through contrast, detail, or placement', 'The largest element in the work', 'The title or signature of the artwork'], 'The area that draws the viewer\'s eye first through contrast, detail, or placement', 'Focal points guide the viewer\'s attention. Artists create them using contrast (light vs. dark), detail (highly rendered area), color (warm amid cool), or placement (intersections of thirds).', 1, 8),
      oe('Explain how an artist uses value (light and dark) to create the illusion of three-dimensional form on a flat surface.', 'Light falls on a 3D object and creates a gradient from highlight (lightest point facing the light source) through midtones to core shadow (the darkest area on the form itself), cast shadow (on the surface behind the object), and reflected light (bounced back into the shadow side). By replicating this pattern of values, a painter makes a flat circle look like a sphere. This is the fundamental technique of representational shading.', 'A strong answer names the specific value zones (highlight, midtone, core shadow, cast shadow, reflected light) and explains the mechanism of creating the illusion.', 2, 9),
      oe('What is the difference between representational, abstract, and non-objective art? Give an example of each.', 'Representational: depicts recognizable subjects from the real world — Leonardo\'s Mona Lisa. Abstract: based on real-world subjects but simplified, distorted, or fragmented — Picasso\'s Cubist portraits. Non-objective: no reference to the physical world, only form, color, line, and texture — Kandinsky\'s geometric compositions or Pollock\'s drip paintings. The spectrum moves from depicting reality to pure formal expression.', 'A strong answer correctly defines all three with examples, and notes the spectrum from realism to complete abstraction.', 2, 10),
    ],
  },

  'drawing': {
    title: 'Drawing Assessment',
    passingScore: 75,
    timeLimitMin: 30,
    questions: [
      mc('What is gesture drawing?', ['Drawing with your non-dominant hand', 'Quick, loose drawings that capture movement, energy, and pose rather than detail', 'Drawing without lifting the pencil', 'Drawing from memory only'], 'Quick, loose drawings that capture movement, energy, and pose rather than detail', 'Gesture drawing captures the essential action and weight of a figure or object in seconds or minutes — the foundation before adding structure and detail.', 1, 1),
      mc('What is one-point perspective?', ['Using one reference point to scale objects', 'A system where parallel lines converge to a single vanishing point on the horizon', 'Drawing with one light source', 'A method of proportional measurement'], 'A system where parallel lines converge to a single vanishing point on the horizon', 'One-point perspective creates depth for views straight-on or down a corridor — all horizontal lines converge at one point on the eye-level horizon line.', 1, 2),
      mc('What is cross-contour drawing?', ['Lines crossing the outline of a form', 'Lines drawn across the surface of a form to describe its three-dimensional shape', 'Overlapping contour outlines', 'Drawing both sides of a subject simultaneously'], 'Lines drawn across the surface of a form to describe its three-dimensional shape', 'Cross-contour lines follow the surface curvature of an object — like latitude/longitude lines on a globe — making flat drawings appear three-dimensional.', 1, 3),
      mc('What does "foreshortening" mean?', ['Making objects appear smaller in the distance', 'Drawing a form as it appears when facing toward or away from the viewer — compressed in one direction', 'Shortening lines for proportion', 'A technique for drawing fast sketches'], 'Drawing a form as it appears when facing toward or away from the viewer — compressed in one direction', 'When a limb or object points directly toward you, it appears much shorter than its actual length. Foreshortening depicts this visual distortion accurately.', 1, 4),
      mc('What is the purpose of a "sight-size" or comparative measurement technique?', ['Drawing objects at life size', 'Using your pencil at arm\'s length to measure and compare proportions in your subject', 'Drawing only what you can see clearly', 'A technique for scaling up sketches'], 'Using your pencil at arm\'s length to measure and compare proportions in your subject', 'Holding a pencil at arm\'s length, closing one eye, and comparing measurements lets you accurately gauge how tall vs. wide something is and how parts relate to each other.', 1, 5),
      mc('What is the difference between hard and soft edges in drawing?', ['Hard edges use pencil; soft use charcoal', 'Hard edges show a distinct boundary between areas; soft edges blur or gradually transition', 'Hard edges are outlines; soft edges are only for painting', 'There is no meaningful difference'], 'Hard edges show a distinct boundary between areas; soft edges blur or gradually transition', 'Edge quality communicates distance, material, and focus. Hard edges bring things forward or show sharp transitions; soft edges recede or suggest atmospheric distance.', 1, 6),
      mc('What does "construction" mean in figure drawing?', ['Building physical reference structures', 'Building the figure from basic geometric shapes (boxes, cylinders, spheres) before adding detail', 'The structural integrity of a drawing', 'The order in which body parts are drawn'], 'Building the figure from basic geometric shapes (boxes, cylinders, spheres) before adding detail', 'Constructive drawing starts with simple 3D forms to establish proportion, perspective, and volume — then refines toward the final image. It prevents flat, symbol-based drawing.', 1, 7),
      mc('What is "massing" in value drawing?', ['Adding heavy shading', 'Grouping all lights and darks into large, simple shapes before adding detail', 'Using black only for shadows', 'A technique for drawing crowds'], 'Grouping all lights and darks into large, simple shapes before adding detail', 'Massing simplifies complex value patterns into two or three big shapes (light mass, shadow mass). This creates strong, readable compositions before small details are added.', 1, 8),
      oe('Explain the concept of "drawing what you see, not what you know." Why is this difficult for beginners?', 'Beginners draw symbols — their mental image of "eye," "hand," "car" — instead of the actual shapes, proportions, and values in front of them. Our brains categorize objects so efficiently that we substitute conceptual symbols for visual observation. Drawing what you see means setting aside what you know and recording exactly what\'s there: the actual angle, the actual proportion, the actual shape of the shadow. Learning to draw is largely learning to override this symbolic thinking.', 'A strong answer explains the symbol-vs-observation distinction and names the cognitive mechanism (symbol substitution), not just "beginners don\'t look carefully."', 2, 9),
      oe('Why is regular observational drawing (from life, not from photos) recommended for developing drawing skills?', 'Drawing from life provides a 3D subject with real lighting, real perspective, and the full range of edges and values. Photos flatten space, lose detail in shadows and highlights, and have already made compositional choices. Drawing from life also requires active decision-making (what to emphasize, how to simplify) that builds artistic judgment. Photos can teach you to copy; life drawing teaches you to see.', 'A strong answer names specific limitations of photo reference (flattened, compressed range, already cropped) vs. the active engagement of life drawing.', 2, 10),
    ],
  },

  'graphic-design': {
    title: 'Graphic Design Assessment',
    passingScore: 75,
    timeLimitMin: 30,
    questions: [
      mc('What is hierarchy in graphic design?', ['The ranking of design software by popularity', 'The visual organization of elements by importance — guiding the viewer\'s eye through the content', 'The order in which layers appear', 'The history of design movements'], 'The visual organization of elements by importance — guiding the viewer\'s eye through the content', 'Visual hierarchy uses size, weight, color, and placement to tell viewers what to look at first, second, and third — making complex information navigable at a glance.', 1, 1),
      mc('What is whitespace (negative space) in graphic design?', ['White-colored areas only', 'The empty space around and between elements — essential for readability and visual breathing room', 'Unused parts of a template', 'A design mistake to be filled'], 'The empty space around and between elements — essential for readability and visual breathing room', 'Whitespace isn\'t wasted space — it improves legibility, creates focus, signals premium quality, and gives designs visual rest. Cramped designs overwhelm; generous whitespace communicates confidence.', 1, 2),
      mc('What is a typeface vs. a font?', ['They are identical terms', 'A typeface is a type family (Helvetica); a font is a specific variation (Helvetica Bold 12pt)', 'A font is the broader family; typeface is the specific style', 'Fonts are digital; typefaces are physical'], 'A typeface is a type family (Helvetica); a font is a specific variation (Helvetica Bold 12pt)', 'Typeface = the design family. Font = a specific weight, style, and size within that family. Common though technically imprecise to use them interchangeably.', 1, 3),
      mc('What is CMYK color mode used for?', ['Screen and digital design', 'Print design — representing colors as percentages of Cyan, Magenta, Yellow, and Key (black)', 'Photography editing', 'Web and app development'], 'Print design — representing colors as percentages of Cyan, Magenta, Yellow, and Key (black)', 'CMYK is the color model for print. RGB is for screens. Designing in RGB and printing can produce color shifts — always design in CMYK for print projects.', 1, 4),
      mc('What is the difference between raster and vector graphics?', ['Raster is black and white; vector is color', 'Raster images are pixel-based (lose quality when scaled); vector graphics are math-based (scale infinitely without quality loss)', 'Vector images are photos; raster images are illustrations', 'They are interchangeable'], 'Raster images are pixel-based (lose quality when scaled); vector graphics are math-based (scale infinitely without quality loss)', 'Raster (JPEG, PNG) — pixels. Scaling up blurs them. Vector (SVG, AI) — mathematical paths. Infinitely scalable. Logos and icons should be vector; photos are raster.', 1, 5),
      mc('What does "alignment" mean as a design principle?', ['Making all text the same size', 'Placing elements along a common edge or axis to create order and visual connection', 'Centering everything on the page', 'Matching colors between elements'], 'Placing elements along a common edge or axis to create order and visual connection', 'Alignment creates invisible lines that organize a layout. Strong alignment creates professionalism; weak alignment creates clutter. Even small misalignments feel sloppy.', 1, 6),
      mc('What is a grid system in layout design?', ['Decorative grid overlays', 'A framework of columns, rows, and margins that organizes content consistently across pages', 'A technique for pixel-perfect layouts only', 'The coordinate system in design software'], 'A framework of columns, rows, and margins that organizes content consistently across pages', 'Grids provide structural consistency, make complex layouts manageable, and guide alignment decisions. Most professional print and web design uses grid systems.', 1, 7),
      mc('What is kerning?', ['The space between lines of text', 'The adjustment of space between specific pairs of characters', 'The height of capital letters', 'The thickness of a typeface stroke'], 'The adjustment of space between specific pairs of characters', 'Kerning fixes uneven-looking character spacing in type — some letter combinations (AV, WA, To) have natural gaps that optical kerning corrects for professional-quality typography.', 1, 8),
      oe('A client wants a logo that works on a business card, a billboard, and a website. What file formats and specifications would you recommend and why?', 'Deliver vector formats: SVG (web), AI or EPS (print, scalable infinitely). Also provide raster versions: PNG with transparent background for web/presentations, high-res TIFF or PDF for print. The vector master lets the client resize to any scale without quality loss. Provide both color versions (CMYK for print, RGB/hex for digital) and a black-and-white version for single-color applications. A logo package should anticipate every use case.', 'A strong answer recommends vector as the master format, explains why it scales, and includes multiple format/color variants for different use cases.', 2, 9),
      oe('Explain the concept of "contrast" in design and describe three different ways a designer can create contrast.', 'Contrast is the difference between elements that makes the design visually interesting and readable. Methods: (1) Size contrast — large headline vs. small body text creates hierarchy. (2) Color contrast — dark text on light background or complementary colors. (3) Weight contrast — bold vs. light type. (4) Shape contrast — organic curves against geometric rectangles. (5) Value contrast — light vs. dark areas. Contrast is how you prevent designs from feeling flat and uniform.', 'A strong answer defines contrast as creating visual difference/interest, names at least three methods with examples for each.', 2, 10),
    ],
  },

  'photography': {
    title: 'Photography Assessment',
    passingScore: 75,
    timeLimitMin: 30,
    questions: [
      mc('What is aperture?', ['The camera\'s shutter speed setting', 'The opening in the lens that controls how much light reaches the sensor, expressed as f-stop', 'The ISO sensitivity setting', 'The focal length of the lens'], 'The opening in the lens that controls how much light reaches the sensor, expressed as f-stop', 'Aperture (f/2.8, f/8, f/16) controls light and depth of field. Wide aperture (low f-number, like f/1.8) = more light, shallow depth of field. Narrow aperture (high f-number, like f/16) = less light, deep focus.', 1, 1),
      mc('What does ISO measure?', ['The lens focal length', 'The image sensor\'s sensitivity to light', 'The shutter speed duration', 'The white balance setting'], 'The image sensor\'s sensitivity to light', 'Higher ISO (1600, 3200) brightens images in low light but introduces grain (noise). Lower ISO (100, 200) produces cleaner images but requires more light.', 1, 2),
      mc('What is shutter speed?', ['How quickly the autofocus locks', 'The duration the camera\'s shutter remains open, controlling motion blur', 'The number of photos per second in burst mode', 'The speed at which images process'], 'The duration the camera\'s shutter remains open, controlling motion blur', 'Fast shutter speeds (1/1000s) freeze motion. Slow shutter speeds (1/30s, 1s) blur motion — useful for light trails or waterfalls, but requires a tripod.', 1, 3),
      mc('What is depth of field?', ['The distance from camera to subject', 'The range of distance within a photo that appears acceptably sharp', 'The zoom level of a lens', 'The number of layers in an edited image'], 'The range of distance within a photo that appears acceptably sharp', 'Shallow depth of field (wide aperture, close focus, long lens) keeps only the subject sharp — background blurs (bokeh). Deep depth of field (narrow aperture, wide lens) keeps everything in focus.', 1, 4),
      mc('What is white balance?', ['The brightness level of highlights', 'The camera\'s calibration to make white objects appear white under different lighting conditions', 'The contrast between light and dark areas', 'The color saturation setting'], 'The camera\'s calibration to make white objects appear white under different lighting conditions', 'Different light sources have different color temperatures. Auto white balance corrects for this automatically; manual settings (daylight, tungsten, fluorescent) give more control.', 1, 5),
      mc('What is the exposure triangle?', ['The three corners of lighting a portrait', 'The relationship between aperture, shutter speed, and ISO — all three control exposure', 'A composition technique using three subjects', 'The three zones of a histogram'], 'The relationship between aperture, shutter speed, and ISO — all three control exposure', 'The exposure triangle: aperture controls light and depth of field, shutter controls time and motion, ISO controls sensor sensitivity. Changing one requires adjusting others to maintain correct exposure.', 1, 6),
      mc('What is the "golden hour" in photography?', ['The best time to edit photos', 'The hour after sunrise and before sunset — producing warm, soft, directional light', 'The optimal exposure time', 'A ratio used in composition'], 'The hour after sunrise and before sunset — producing warm, soft, directional light', 'Golden hour light is warm (orange/gold), comes from a low angle (creating long shadows and dimension), and is naturally diffused — producing flattering, dramatic results photographers prize.', 1, 7),
      mc('What is RAW format vs. JPEG?', ['RAW is compressed; JPEG is uncompressed', 'RAW captures all sensor data with no in-camera processing; JPEG is compressed and processed in-camera', 'JPEG has more data than RAW', 'They are functionally identical'], 'RAW captures all sensor data with no in-camera processing; JPEG is compressed and processed in-camera', 'RAW gives maximum editing latitude — you can recover highlights, adjust white balance, control sharpening. JPEG discards data, bakes in processing, and can\'t be recovered the same way.', 1, 8),
      oe('Explain how aperture, shutter speed, and ISO interact. Give an example of how you would adjust all three for a sports action shot.', 'All three affect exposure — changing one requires compensating with another. For sports: use fast shutter speed (1/1000s or faster) to freeze motion. This lets in less light, so open the aperture wide (f/2.8) to compensate. If still underexposed, raise ISO (800–1600). The trade-off: wide aperture gives shallow depth of field (can miss moving subjects), high ISO adds grain. Auto ISO with shutter priority mode is a practical approach for sports.', 'A strong answer explains the light tradeoffs, gives specific values, and acknowledges the resulting trade-offs (shallow DOF, grain).', 2, 9),
      oe('Beyond technical settings, what compositional choices can a photographer make to create a more compelling image?', 'Compositional choices: (1) Rule of thirds — place subjects off-center at grid intersections. (2) Leading lines — roads, fences, rivers that guide the eye toward the subject. (3) Framing — use foreground elements (doorways, branches) to frame the subject. (4) Perspective/angle — shoot from high, low, or unusual angles for fresh views. (5) Foreground interest — add depth by including interesting foreground elements. (6) Simplicity — eliminate distracting backgrounds by repositioning. (7) Moment — for people, wait for the decisive moment of expression or action.', 'A strong answer lists at least four compositional techniques with brief explanations of why each works.', 2, 10),
    ],
  },

  'music-fundamentals': {
    title: 'Music Fundamentals Assessment',
    passingScore: 75,
    timeLimitMin: 30,
    questions: [
      mc('What is pitch?', ['The volume of a sound', 'The perceived highness or lowness of a sound, determined by its frequency', 'The duration of a note', 'The quality of a sound\'s tone'], 'The perceived highness or lowness of a sound, determined by its frequency', 'Pitch is how high or low a note sounds. Higher frequency = higher pitch. Musical pitches are organized into named notes (A through G) and octaves.', 1, 1),
      mc('What is rhythm?', ['The speed of a piece of music', 'The pattern of long and short sounds and silences in music', 'The pitch pattern of a melody', 'The volume changes in music'], 'The pattern of long and short sounds and silences in music', 'Rhythm is the temporal organization of music — the pattern of beats and rests that gives music its feel and groove. It exists independently of pitch.', 1, 2),
      mc('What is a time signature?', ['How fast a piece should be played', 'A symbol at the beginning of a staff indicating how many beats per measure and what note value gets one beat', 'The key a piece is written in', 'The range of notes in a melody'], 'A symbol at the beginning of a staff indicating how many beats per measure and what note value gets one beat', 'In 4/4 time: 4 beats per measure, quarter note gets one beat. In 3/4: 3 beats per measure (waltz feel). The top number counts beats; the bottom shows which note equals one beat.', 1, 3),
      mc('What is a musical scale?', ['A device for measuring tempo', 'A sequence of notes in ascending or descending order following a specific pattern of intervals', 'The range of an instrument', 'The key signature of a piece'], 'A sequence of notes in ascending or descending order following a specific pattern of intervals', 'Scales define the tonal palette of a piece. The major scale sounds bright and happy; minor scales sound darker. They provide the building blocks for melodies and chords.', 1, 4),
      mc('What is harmony?', ['Singing or playing in perfect unison', 'The combination of simultaneous pitches that create chords and support the melody', 'The speed of a piece of music', 'The loudness of the music'], 'The combination of simultaneous pitches that create chords and support the melody', 'Harmony is vertical — what happens when multiple notes sound together. Consonant harmonies sound stable and pleasant; dissonant harmonies create tension seeking resolution.', 1, 5),
      mc('What is dynamics in music?', ['The speed of performance', 'How loud or soft music is played — ranging from piano (soft) to forte (loud)', 'The emotional content of the piece', 'The number of instruments performing'], 'How loud or soft music is played — ranging from piano (soft) to forte (loud)', 'Dynamic markings guide performers: piano (p) = soft, forte (f) = loud, mezzo-forte (mf) = medium loud, crescendo = gradually louder, decrescendo = gradually softer.', 1, 6),
      mc('What is melody?', ['A sequence of chords', 'A sequence of single notes organized rhythmically into a recognizable musical phrase', 'The background accompaniment', 'The harmony below the main line'], 'A sequence of single notes organized rhythmically into a recognizable musical phrase', 'Melody is the horizontal element of music — the "tune" you sing or hum. It\'s a succession of pitches in a specific rhythm that creates a memorable musical idea.', 1, 7),
      mc('What is tempo?', ['The pitch range of an instrument', 'The speed of the music, measured in beats per minute (BPM)', 'The time signature', 'The rhythmic pattern'], 'The speed of the music, measured in beats per minute (BPM)', 'Tempo determines how fast or slow music feels. Italian terms: Largo (very slow), Andante (walking pace), Moderato (moderate), Allegro (fast), Presto (very fast). Digital music uses BPM.', 1, 8),
      oe('Explain the difference between major and minor scales and describe the emotional qualities typically associated with each.', 'The major scale follows the pattern: W-W-H-W-W-W-H (whole and half steps). The natural minor scale: W-H-W-W-H-W-W. The third, sixth, and seventh degrees are lowered in minor. Emotionally: major scales tend to sound bright, happy, confident, triumphant (think "Happy Birthday"). Minor scales tend to sound darker, sadder, more dramatic or melancholic (think "Greensleeves"). These associations are cultural and contextual, not universal laws.', 'A strong answer gives the interval patterns or describes the structural difference, and acknowledges the emotional associations while noting they\'re culturally influenced.', 2, 9),
      oe('Why is active listening — not just hearing — important for understanding and appreciating music?', 'Active listening means tracking specific elements: rhythm patterns, how the melody moves, changes in harmony, dynamic shifts, instrumentation choices, and formal structure. Without it, music blurs into undifferentiated sound. Active listening reveals the composer\'s decisions, the interplay between instruments, and how musical tension and release create emotional effect. Like reading — you can decode words passively, but comprehension requires engagement.', 'A strong answer defines what active listening means in music, names specific elements to track, and explains why passive hearing fails to access music\'s structure.', 2, 10),
    ],
  },

  'creative-process': {
    title: 'Creative Process Assessment',
    passingScore: 75,
    timeLimitMin: 30,
    questions: [
      mc('What is the creative process?', ['Inspiration that strikes suddenly and completely', 'A series of stages — preparation, incubation, illumination, and verification — through which ideas develop', 'Random experimentation without planning', 'The steps to technically execute a finished artwork'], 'A series of stages — preparation, incubation, illumination, and verification — through which ideas develop', 'Graham Wallas\'s model identifies four stages: preparation (gathering knowledge), incubation (unconscious processing), illumination (the "aha" moment), and verification (testing and refining the idea).', 1, 1),
      mc('What is creative constraints?', ['Rules that prevent creative work', 'Limitations that paradoxically can stimulate creativity by forcing novel solutions within boundaries', 'The rules of a specific art form', 'Deadlines and budgets'], 'Limitations that paradoxically can stimulate creativity by forcing novel solutions within boundaries', 'Unlimited freedom can paralyze. Constraints — write a story in 100 words, design with two colors only — force creative problem-solving and often produce more interesting results than unlimited options.', 1, 2),
      mc('What is a creative brief?', ['A short creative work', 'A document outlining the goals, audience, constraints, and deliverables for a creative project', 'A daily journaling practice', 'A critique of a creative work'], 'A document outlining the goals, audience, constraints, and deliverables for a creative project', 'Creative briefs align client and creator expectations before work begins. They define the problem, target audience, tone, deliverables, and success criteria — preventing expensive misunderstandings.', 1, 3),
      mc('What is iteration in creative work?', ['Creating one perfect version', 'Making multiple versions or refinements — improving through successive rounds of feedback and revision', 'Copying a reference exactly', 'Brainstorming without committing to an idea'], 'Making multiple versions or refinements — improving through successive rounds of feedback and revision', 'Iteration is how professionals work. First versions are rarely the best — each cycle of make, evaluate, and refine moves the work toward a better solution. "Perfect" is the enemy of done.', 1, 4),
      mc('What is the difference between brainstorming and idea evaluation?', ['They are the same process', 'Brainstorming generates ideas without judgment; evaluation critically assesses which ideas are worth pursuing', 'Evaluation comes before brainstorming', 'Brainstorming is only for groups'], 'Brainstorming generates ideas without judgment; evaluation critically assesses which ideas are worth pursuing', 'Mixing generation and evaluation is a creativity killer — premature criticism stops the flow of ideas. Effective creative process separates divergent thinking (generating) from convergent thinking (selecting).', 1, 5),
      mc('What is creative block?', ['Lack of artistic talent', 'A state where generating or executing creative work feels impossible — often from fear, perfectionism, or exhaustion', 'Running out of art supplies', 'The technical difficulty of a medium'], 'A state where generating or executing creative work feels impossible — often from fear, perfectionism, or exhaustion', 'Creative blocks are psychological, not talent-based. Common causes: fear of judgment, perfectionism preventing starting, over-reliance on inspiration, and burnout. They affect everyone at all skill levels.', 1, 6),
      mc('What is creative research?', ['Only looking at other artists\' work', 'The process of gathering material — images, data, experiences, interviews — that informs and feeds creative work', 'Academic study of art history', 'Finding a creative mentor'], 'The process of gathering material — images, data, experiences, interviews — that informs and feeds creative work', 'Creative research feeds the creative mind. Art, literature, music, travel, conversations, observation — input determines output. The best creative work draws from rich, varied research.', 1, 7),
      mc('What does "kill your darlings" mean in the creative process?', ['Destroy old sketchbooks', 'Be willing to remove work you love if it doesn\'t serve the larger piece', 'Stop working on a failing project', 'Reject all criticism of your work'], 'Be willing to remove work you love if it doesn\'t serve the larger piece', 'Attachment to our own creations is natural but can prevent good decisions. The ability to remove beautiful but non-functional work in service of the whole is a mark of mature creative practice.', 1, 8),
      oe('Describe your personal creative process for a project you\'ve worked on. What stages did you go through?', 'A strong personal answer traces the process from initial research/inspiration through planning, first attempts, revision or problem-solving, feedback, and final refinement. The best answers acknowledge difficulty and iteration — not a smooth path from idea to execution, but a messy, looping process with dead ends and breakthroughs.', 'A strong answer is personal and specific, showing genuine reflection on what actually happened (including struggles), not an idealized description of a smooth process.', 2, 9),
      oe('Why is receiving and giving constructive criticism essential to developing as a creative?', 'Receiving feedback: our own perspective is limited — we see what we intended, not what\'s actually there. External eyes reveal blind spots. Without feedback, bad habits calcify. Giving feedback: articulating what works and what doesn\'t sharpens critical thinking and improves your own work by training you to see your own pieces more objectively. Creating in isolation produces growth; creating in community with honest feedback produces faster, deeper growth.', 'A strong answer addresses both receiving and giving feedback, and explains the mechanism (limited self-perspective, critical thinking development) not just that feedback is valuable.', 2, 10),
    ],
  },
}
