import type { ExerciseDef } from '../types'

function mc(
  question: string,
  options: string[],
  correctAnswer: string,
  explanation: string,
  order: number,
): ExerciseDef {
  return { question, type: 'MULTIPLE_CHOICE', options, correctAnswer, explanation, order }
}

export const artsExercises5: Record<string, ExerciseDef[]> = {
  'sound-and-pitch': [
    mc(
      'The A above middle C vibrates at 440 Hz. The A one octave higher vibrates at:',
      ['880 Hz — exactly double the frequency', '660 Hz — one and a half times the frequency', '480 Hz — 40 Hz more than the original', '220 Hz — exactly half the frequency'],
      '880 Hz — exactly double the frequency',
      'Doubling the frequency produces a note one octave higher — the same note name but higher in pitch. Halving the frequency produces a note one octave lower. This doubling relationship is the most fundamental mathematical relationship in music, appearing in all musical traditions.',
      1,
    ),
    mc(
      'There is no sharp or flat note between which two pairs of natural notes?',
      ['A and B, and C and D', 'E and F, and B and C', 'C and D, and F and G', 'D and E, and G and A'],
      'E and F, and B and C',
      'The 12-note chromatic scale has sharps/flats between most natural notes — except between E and F, and between B and C. These pairs are naturally a half step apart, so there is no note in between. This is why the piano keyboard has no black key between E and F, or between B and C.',
      2,
    ),
    mc(
      'Timbre (pronounced TAM-ber) refers to:',
      ['The volume or amplitude of a sound', 'The characteristic quality that distinguishes a piano from a guitar playing the same note at the same volume', 'The speed at which sound waves travel through air', 'The pitch or frequency of a musical note'],
      'The characteristic quality that distinguishes a piano from a guitar playing the same note at the same volume',
      'Timbre is the "color" of a sound — what makes a piano sound different from a violin playing the same pitch at the same volume. It results from the mixture of the fundamental frequency and its overtones (harmonics) in different proportions. Each instrument has a characteristic overtone mix that gives it its distinctive sound.',
      3,
    ),
    mc(
      'A tritone interval spans:',
      ['5 half steps (a perfect fourth)', '7 half steps (a perfect fifth)', '6 half steps — exactly halfway through the octave', '4 half steps (a major third)'],
      '6 half steps — exactly halfway through the octave',
      'The tritone (6 half steps) divides the octave exactly in half. It is the most dissonant interval in Western music — tense and unstable, always seeming to want to resolve. It appears prominently in dominant seventh chords (as the interval between the third and seventh), creating the chord\'s strong pull toward the tonic.',
      4,
    ),
    mc(
      'Enharmonic equivalents are notes that:',
      ['Sound identical but are spelled differently — such as F# and G♭', 'Are in the same octave but one is sharp and one is natural', 'Have the same name but are in different octaves', 'Are both natural notes with no sharps or flats'],
      'Sound identical but are spelled differently — such as F# and G♭',
      'Enharmonic equivalents produce the same pitch — on a piano, you play the same key. However, they are spelled differently because their theoretical role differs depending on the key. In D major, you write F#; in D♭ major, you write G♭. Same sound, different harmonic function.',
      5,
    ),
  ],

  'rhythm-and-meter': [
    mc(
      'Tempo in music is measured in:',
      ['Hertz — the number of sound wave cycles per second', 'BPM (beats per minute) — how many beats occur in one minute', 'Measures per minute — how many bars occur in one minute', 'Decibels — the intensity of the rhythmic pulse'],
      'BPM (beats per minute) — how many beats occur in one minute',
      'BPM is the universal tempo measurement. A metronome at 60 BPM produces one beat per second — a moderate, comfortable pace. At 120 BPM, two beats per second — Allegro territory. Italian tempo terms (Andante, Allegro, Presto) describe ranges of BPM.',
      1,
    ),
    mc(
      'The "backbeat" in popular music refers to:',
      ['The first beat of every measure, which carries the most weight', 'An accent on beats 2 and 4 in 4/4 time, typically marked by the snare drum in rock and pop', 'The bass drum pattern that establishes the rhythm', 'The final beat of a phrase before a new section begins'],
      'An accent on beats 2 and 4 in 4/4 time, typically marked by the snare drum in rock and pop',
      'The backbeat is the characteristic rhythmic feel of most contemporary popular music — rock, pop, blues. While classical music accents beat 1 most strongly, popular music accents beats 2 and 4, typically with the snare drum. This creates a "push" sensation rather than the "weight" of a downbeat accent.',
      2,
    ),
    mc(
      'A dotted quarter note has a duration equal to:',
      ['One quarter note plus one eighth note (1.5 beats)', 'Two quarter notes (2 beats)', 'One quarter note plus one sixteenth note (1.25 beats)', 'Three eighth notes (1.5 beats, but counted differently)'],
      'One quarter note plus one eighth note (1.5 beats)',
      'A dot adds half the note\'s value. A quarter note = 1 beat; half of that = 0.5 beats (an eighth note). Dotted quarter = 1 + 0.5 = 1.5 beats. Dotted rhythms create a characteristic lilt or bounce and are extremely common in music of all genres.',
      3,
    ),
    mc(
      'Syncopation creates rhythmic interest by:',
      ['Playing all notes exactly on the beat with maximum precision', 'Accenting off-beats and weak beats that aren\'t normally emphasized', 'Using triplets instead of straight eighth notes throughout', 'Playing at a tempo that is slightly faster than the indicated BPM'],
      'Accenting off-beats and weak beats that aren\'t normally emphasized',
      'In 4/4, the beats fall on 1, 2, 3, 4. Syncopation accents the "ands" (eighth-note off-beats) or anticipates beat 1 by landing on the "and" of beat 4. Most popular music — R&B, funk, jazz, hip-hop — relies heavily on syncopation to create groove and forward momentum.',
      4,
    ),
    mc(
      'The time signature 6/8 is felt differently from 3/4 because:',
      ['6/8 has six beats per measure while 3/4 has only three, making 6/8 twice as fast', '6/8 is felt as two beats that each divide into three eighth notes; 3/4 is felt as three beats that each divide into two eighth notes', '6/8 uses dotted quarter notes while 3/4 uses regular quarter notes as the beat unit', '6/8 is compound meter used only in fast music; 3/4 is simple meter used only in slow music'],
      '6/8 is felt as two beats that each divide into three eighth notes; 3/4 is felt as three beats that each divide into two eighth notes',
      'Both 6/8 and 3/4 contain six eighth-note equivalents per measure, but the grouping differs entirely. In 3/4, you tap three times (1-2-3); in 6/8, you tap twice, each beat subdividing into three (1-and-a, 2-and-a). This grouping difference is the test: how many times do you tap per measure?',
      5,
    ),
  ],

  'scales-and-keys': [
    mc(
      'The major scale follows the pattern of whole and half steps:',
      ['W-H-W-W-H-W-W (natural minor pattern)', 'W-W-H-W-W-W-H', 'H-W-W-H-W-W-W', 'W-W-W-H-W-W-H'],
      'W-W-H-W-W-W-H',
      'The major scale pattern — whole, whole, half, whole, whole, whole, half — is the same in every key. Starting from C: C-D (W), D-E (W), E-F (H), F-G (W), G-A (W), A-B (W), B-C (H). This produces C major using only the white keys on a piano. Any starting pitch with this pattern gives you the major scale in that key.',
      1,
    ),
    mc(
      'The "relative minor" of a major key uses the same notes as the major scale but:',
      ['Raises the third degree by a half step', 'Starts on the sixth degree of the major scale, making that note the new tonal center', 'Adds a flat to every note in the scale', 'Lowers the seventh degree by a half step'],
      'Starts on the sixth degree of the major scale, making that note the new tonal center',
      'A minor and C major use identical notes (all white keys on the piano), but A minor starts on A (the 6th degree of C major) and makes A the tonal center. The same notes rearranged with a different home base produce a completely different sound — darker and more serious than C major.',
      2,
    ),
    mc(
      'Moving clockwise around the Circle of Fifths:',
      ['Removes one sharp (or adds one flat) per step', 'Adds one sharp per step, moving to keys progressively further from C major', 'Changes the scale from major to minor at each step', 'Increases the number of flats by two per step'],
      'Adds one sharp per step, moving to keys progressively further from C major',
      'The Circle of Fifths arranges all 12 major keys so each adjacent key is a perfect fifth higher. Moving clockwise: C (0 sharps) → G (1 sharp) → D (2 sharps) → A (3 sharps)... Moving counterclockwise adds flats. Adjacent keys share all but one note, making them harmonically closely related.',
      3,
    ),
    mc(
      'The minor pentatonic scale is widely used in blues and rock improvisation because:',
      ['It contains all seven notes of the natural minor scale', 'It avoids the 2nd and 6th degrees, making it sound good over many different chord types without clashing', 'It is the easiest scale to play on guitar due to its open string compatibility', 'It is identical to the major scale in every key'],
      'It avoids the 2nd and 6th degrees, making it sound good over many different chord types without clashing',
      'The minor pentatonic (five-note) scale omits scale degrees 2 and 6 from the natural minor. These omitted degrees are the ones most likely to clash with chord tones. The resulting five-note set works safely over many different chord types — major, minor, and dominant seventh — making it a versatile "safe" scale for improvisation.',
      4,
    ),
    mc(
      'The Mixolydian mode differs from the major scale in that it:',
      ['Has a lowered third, giving it a minor character', 'Has a raised fourth, creating a dreamy, floating quality', 'Has a lowered seventh, giving it a blues-rock feel', 'Has a lowered second, creating a dark, Spanish character'],
      'Has a lowered seventh, giving it a blues-rock feel',
      'Mixolydian is the major scale with one change: the seventh degree is lowered by a half step. Starting on G in the C major scale gives G Mixolydian: G-A-B-C-D-E-F-G (F instead of F#). The lowered seventh gives it a slightly rough, bluesy quality — it is the mode of countless rock riffs.',
      5,
    ),
  ],

  'chords-and-harmony': [
    mc(
      'The difference between a major triad and a minor triad is:',
      ['The major triad has five notes; the minor triad has three notes', 'The major triad has a major third (4 half steps) above the root; the minor triad has a minor third (3 half steps)', 'The major triad includes the seventh; the minor triad does not', 'Major triads are only used in the top three strings of a guitar; minor triads use all six strings'],
      'The major triad has a major third (4 half steps) above the root; the minor triad has a minor third (3 half steps)',
      'Both triads are built root-third-fifth. The critical difference is the third: major third (4 half steps) = bright, stable, "happy"; minor third (3 half steps) = darker, more serious. Both have a perfect fifth above the root. For C major: C-E-G. For C minor: C-E♭-G.',
      1,
    ),
    mc(
      'In the diatonic chords of a major key, which chord built on the seventh scale degree is naturally diminished?',
      ['The I chord (tonic)', 'The V chord (dominant)', 'The vii° chord (leading tone)', 'The IV chord (subdominant)'],
      'The vii° chord (leading tone)',
      'When you build triads on each degree of a major scale using only notes in that key, the chord on the seventh degree (the leading tone) comes out diminished — a minor third plus a diminished fifth. In C major: B-D-F is a diminished triad. This chord is extremely tense and almost always resolves to the tonic (I).',
      2,
    ),
    mc(
      'The dominant seventh chord (V7) creates the strongest pull to the tonic primarily because:',
      ['It is the loudest chord in the key due to its four notes', 'It contains a tritone between the third and seventh that resolves by half-step motion to the tonic chord', 'It is always played loudly (forte) before the final tonic chord', 'It uses notes from outside the key, creating chromatic tension'],
      'It contains a tritone between the third and seventh that resolves by half-step motion to the tonic chord',
      'In G7 (the V7 in C major), the tritone between B and F desperately wants to resolve: B moves up a half step to C, and F moves down a half step to E — landing on the notes of the C major chord. This half-step resolution in both directions gives the V7-I progression its powerful, inevitable feeling.',
      3,
    ),
    mc(
      'A "deceptive cadence" is a progression where:',
      ['The V chord resolves to vi instead of the expected I chord', 'The IV chord resolves to I, creating a softer resolution than V to I', 'The I chord moves to V, leaving tension unresolved', 'The melody note of the tonic chord is in the bass instead of the root'],
      'The V chord resolves to vi instead of the expected I chord',
      'The deceptive cadence creates surprise: the V chord has built up tension and the listener expects resolution to I — but vi (the relative minor) appears instead. The vi shares two notes with I, so it is not jarring, but the resolution feels incomplete and suspended. Composers use it to extend phrases.',
      4,
    ),
    mc(
      'Inversions of a chord (first inversion, second inversion) are used primarily to:',
      ['Increase the chord\'s dissonance for greater harmonic tension', 'Create smoother voice leading — individual notes move by small intervals rather than jumping to new positions', 'Indicate that the chord should be played softly (piano)', 'Change the chord from major to minor quality'],
      'Create smoother voice leading — individual notes move by small intervals rather than jumping to new positions',
      'When a chord changes, individual voices (notes) move to the next chord. When all chords are in root position, the bass often jumps large intervals. Inversions allow the bass to move by step and notes to move by the smallest possible interval — producing smooth, flowing voice leading rather than jumpy chord changes.',
      5,
    ),
  ],

  'reading-notation': [
    mc(
      'In the treble clef, the notes on the five lines from bottom to top are:',
      ['F, A, C, E, G', 'E, G, B, D, F', 'G, B, D, F, A', 'A, C, E, G, B'],
      'E, G, B, D, F',
      'The treble clef lines from bottom to top are E-G-B-D-F, memorized as "Every Good Boy Does Fine." The spaces from bottom to top spell FACE. The treble clef curls around line 2, indicating that line 2 is G4 (the G above middle C). Middle C sits one ledger line below the treble clef staff.',
      1,
    ),
    mc(
      'An accidental (a sharp, flat, or natural sign) placed before a note applies:',
      ['Only to that specific note instance and is immediately forgotten', 'To all subsequent notes on the same line or space within the same measure, until cancelled or the measure ends', 'To every note in the piece from that point forward', 'Only to notes in the same octave as the written accidental'],
      'To all subsequent notes on the same line or space within the same measure, until cancelled or the measure ends',
      'Accidentals apply to subsequent notes on the same pitch within the same measure — you do not need to re-mark every instance. At the bar line, the accidental expires and the key signature resumes. A natural sign cancels a key signature sharp or flat for the remainder of that measure.',
      2,
    ),
    mc(
      'A fermata symbol (𝄐) above a note indicates:',
      ['Play the note staccato — short and detached', 'Gradually slow down (ritardando)', 'Hold the note longer than its written value; the performer or conductor decides how long', 'Return to the beginning of the piece'],
      'Hold the note longer than its written value; the performer or conductor decides how long',
      'A fermata pauses the regular pulse and extends the note or rest under it for an indeterminate length decided by the performer or conductor. It is commonly used at the end of phrases, at climactic moments, or at endings to create a sense of suspension or finality.',
      3,
    ),
    mc(
      'The dynamic marking "mf" (mezzo forte) means:',
      ['Play as softly as possible', 'Play very loudly (fortissimo)', 'Play moderately loud', 'Return gradually to the original volume'],
      'Play moderately loud',
      'The dynamic scale runs from ppp (pianississimo — as quiet as possible) through pp, p, mp, mf, f, ff, to fff. "Mezzo" means moderate or medium in Italian. Mezzo forte (mf) sits between mezzo piano (mp — moderately quiet) and forte (f — loud). It is a comfortable, present volume used for most normal passages.',
      4,
    ),
    mc(
      'The recommended approach when reading a new piece of music for the first time is to:',
      ['Play at full tempo immediately to get a feel for the piece', 'Start from the most interesting section to build motivation before learning the whole piece', 'Check key signature, time signature, and tempo marking; scan the structure; then play slowly and accurately', 'Skip any section that seems too difficult and only practice the easy parts'],
      'Check key signature, time signature, and tempo marking; scan the structure; then play slowly and accurately',
      'A systematic first-reading approach prevents learning mistakes that have to be unlearned: know what\'s sharp or flat (key signature), know the meter (time signature), know the character (tempo marking), understand the structure (repeats, D.C., endings), then play slowly enough that every note is correct. Wrong repetitions teach wrong patterns.',
      5,
    ),
  ],

  'time-signatures': [
    mc(
      'In compound meter (such as 6/8), the beat unit is a dotted note because:',
      ['Dotted notes are always longer than undotted notes', 'The beat in compound meter naturally divides into three equal parts, and a dotted note has exactly three subdivisions', 'Compound meter is only used in slow tempos where dotted notes sound natural', 'The bottom number "8" in 6/8 requires a dotted note for correct duration'],
      'The beat in compound meter naturally divides into three equal parts, and a dotted note has exactly three subdivisions',
      'In compound meter, each beat divides into three equal parts (triplet subdivision). A dotted quarter note = quarter + eighth = 3 eighth notes, so it naturally divides into three. This is why 6/8 is felt as two dotted-quarter beats (each dividing into three eighth notes), not as six independent eighth-note beats.',
      1,
    ),
    mc(
      'The critical difference between 3/4 and 6/8 time is:',
      ['3/4 is faster than 6/8', '3/4 has three beats each dividing into two; 6/8 has two beats each dividing into three — both have 6 eighth notes per measure but different felt groupings', '3/4 uses quarter notes; 6/8 uses eighth notes exclusively', '6/8 requires a compound time signature; 3/4 uses a simple time signature'],
      '3/4 has three beats each dividing into two; 6/8 has two beats each dividing into three — both have 6 eighth notes per measure but different felt groupings',
      'The test is how many times you tap per measure. In 3/4, you tap three times (1-2-3, 1-2-3). In 6/8, you tap twice (ONE-two-three, TWO-two-three). Both contain six eighth-note equivalents, but the grouping — two groups of three versus three groups of two — creates entirely different rhythmic feels.',
      2,
    ),
    mc(
      'An eighth note triplet in simple meter means:',
      ['Three quarter notes played in the space of two quarter notes', 'Three eighth notes played evenly in the space of two eighth notes (one quarter note)', 'Three sixteenth notes played in the space of two eighth notes', 'A group of three eighth notes with the middle note tied'],
      'Three eighth notes played evenly in the space of two eighth notes (one quarter note)',
      'Triplets temporarily borrow the compound subdivision within simple meter — forcing three notes into the space that normally holds two. An eighth note triplet fits three eighth notes into one beat (one quarter note\'s worth). In jazz and blues, the "swing" feel is a triplet-influenced long-short pair of eighth notes.',
      3,
    ),
    mc(
      'The time signature 5/4 is described as "asymmetric" because:',
      ['It uses five beats which cannot be evenly divided into equal groups of two or three', 'It is only used in 20th-century classical music, not in popular styles', 'The bottom number (4) does not match the top number (5)', 'Five-beat measures require an odd number of bars per phrase'],
      'It uses five beats which cannot be evenly divided into equal groups of two or three',
      'Regular meters group beats evenly: 2/4 (2 beats), 3/4 (3 beats), 4/4 (4 beats = 2×2), 6/8 (2 groups of 3). Five cannot be divided into equal groups — it must be felt as 3+2 or 2+3. This asymmetry creates a perpetual forward pull because the ear cannot settle into a predictable, resolving pattern.',
      4,
    ),
    mc(
      'Hemiola is the rhythmic technique of:',
      ['Gradually slowing the tempo over the course of a phrase', 'Playing a melody in one octave while accompanying it in another', 'Temporarily implying a different meter through accent patterns — such as implying 2/4 within 3/4', 'Adding extra beats to a measure to create rhythmic surprise'],
      'Temporarily implying a different meter through accent patterns — such as implying 2/4 within 3/4',
      'Hemiola creates the effect of a meter change without actually changing the time signature. In 3/4, accenting every other beat across two measures (instead of every three) creates the feeling of 2/4 — the listener briefly loses track of where beat 1 is. This technique appears in Baroque music, Brahms, and Latin music.',
      5,
    ),
  ],

  'ear-training': [
    mc(
      'The fundamental distinction between relative pitch and absolute (perfect) pitch is:',
      ['Relative pitch is innate; perfect pitch must be learned through training', 'Relative pitch hears intervals and relationships between notes; absolute pitch identifies note names upon hearing without any reference', 'Relative pitch applies only to melodic intervals; absolute pitch applies to harmonic intervals', 'Perfect pitch makes relative pitch unnecessary for professional musicians'],
      'Relative pitch hears intervals and relationships between notes; absolute pitch identifies note names upon hearing without any reference',
      'Relative pitch — hearing how notes relate to each other and to a tonal center — is learnable through practice and is the ear training skill that matters. Absolute (perfect) pitch — knowing the name of any note without a reference pitch — appears partially innate and is much harder to develop in adulthood. Most professional musicians have strong relative pitch, not absolute pitch.',
      1,
    ),
    mc(
      'Learning interval recognition using "reference songs" works by:',
      ['Memorizing the frequency difference between each interval in Hertz', 'Associating each interval with a familiar song where that interval appears at the beginning, so the sound becomes automatic', 'Practicing singing scales until each scale degree is recognized by its position', 'Listening to isolated tones without any musical context for pure frequency training'],
      'Associating each interval with a familiar song where that interval appears at the beginning, so the sound becomes automatic',
      'A perfect fifth at the start of "Twinkle Twinkle Little Star," a perfect fourth at the start of "Here Comes the Bride," a tritone opening "The Simpsons" theme — these associations make interval sounds immediately recognizable because you already know the songs cold. The interval sound becomes automatic through the association.',
      2,
    ),
    mc(
      'The primary distinction that makes major chords sound "bright" and minor chords sound "darker" is:',
      ['Major chords are played in higher registers; minor chords in lower registers', 'The third of the chord — major chords have a major third (4 half steps); minor chords have a minor third (3 half steps)', 'Major chords use more notes than minor chords', 'Minor chords are played more quietly than major chords'],
      'The third of the chord — major chords have a major third (4 half steps); minor chords have a minor third (3 half steps)',
      'The third degree is the defining characteristic. A major third creates an open, bright sound. A minor third creates a more closed, inward sound. Both major and minor triads share the root and perfect fifth — it is only the third that differs. Singing the third of any chord you hear helps you identify major vs. minor.',
      3,
    ),
    mc(
      'Transcription (writing down music by ear) is considered the highest ear training skill because:',
      ['It is the only way to practice ear training without a teacher', 'It simultaneously develops pitch recognition, rhythm notation, harmonic understanding, and melodic accuracy all at once', 'Transcription software makes it faster and therefore more productive', 'It allows musicians to learn songs without purchasing sheet music'],
      'It simultaneously develops pitch recognition, rhythm notation, harmonic understanding, and melodic accuracy all at once',
      'To transcribe music, you must identify the key, meter, individual pitches, rhythmic durations, chord changes, and melodic contours — all at once. This integration of every ear training skill makes it the most comprehensive practice. Start with simple folk melodies and work up gradually.',
      4,
    ),
    mc(
      'The recommended minimum daily ear training practice to build skill effectively is:',
      ['At least four hours per day of intensive interval drilling', '10-15 minutes of focused practice — daily repetition builds neural pathways more reliably than occasional long sessions', 'One session per week of at least 2 hours to maintain skills', 'Only when preparing for a specific performance or exam'],
      '10-15 minutes of focused practice — daily repetition builds neural pathways more reliably than occasional long sessions',
      'Short, consistent daily practice builds ear training skills more effectively than cramming. Neural pathways for pitch and interval recognition form through repeated exposure over time. Ten to fifteen minutes every day produces better results than one session per week even if the weekly session is much longer.',
      5,
    ),
  ],

  'what-is-creativity': [
    mc(
      'According to the lesson, creativity is most accurately defined as:',
      ['A special innate ability some people are born with that enables original self-expression', 'Making entirely new things from nothing — ideas that have no prior influence', 'Making new connections between existing things — combining prior inputs in unexpected ways', 'A talent that can be identified early in childhood through standardized testing'],
      'Making new connections between existing things — combining prior inputs in unexpected ways',
      'James Webb Young\'s definition — "the combination of existing elements in new and useful ways" — captures the reality of creativity. Nothing comes from nothing. Every creative work emerges from accumulated inputs: ideas absorbed, experiences processed, techniques learned. The creative act is finding unexpected connections among existing material.',
      1,
    ),
    mc(
      'The skill-taste gap described in the lesson refers to:',
      ['The difference between technical skill and business acumen in creative careers', 'The gap between a creator\'s taste (which develops quickly) and their technical ability (which requires more time to catch up)', 'The difference between what critics value and what audiences enjoy', 'The gap between amateur and professional levels of technical execution'],
      'The gap between a creator\'s taste (which develops quickly) and their technical ability (which requires more time to catch up)',
      'Ira Glass observed that people drawn to creative work have good taste — that\'s what got them into it. But early work doesn\'t match that taste yet, and the gap is discouraging. This is normal. The only closure is volume: making a lot of work over time. The taste that got you started eventually aligns with the ability you build through practice.',
      2,
    ),
    mc(
      'Divergent thinking differs from convergent thinking in that divergent thinking:',
      ['Evaluates ideas to select the best one while convergent thinking generates options', 'Applies logical rules to arrive at the single correct answer', 'Generates many possible ideas without evaluation, opening up possibilities', 'Is less useful in creative work than convergent thinking'],
      'Generates many possible ideas without evaluation, opening up possibilities',
      'Divergent thinking generates options — brainstorming, exploring, not judging. Convergent thinking evaluates and selects. Both are necessary for creative work. The common problem is applying convergent thinking too early — judging while generating — which stops divergent exploration before it can produce surprising ideas.',
      3,
    ),
    mc(
      'Research on creativity consistently finds that intrinsic motivation (doing something because you find it interesting) compared to extrinsic motivation (doing it for reward) tends to produce:',
      ['Similar quality work, but intrinsically motivated work is completed faster', 'More and higher-quality creative work — more adventurous and distinctive output', 'Work that is more commercially successful even if slightly less artistic', 'Work that is technically stronger but emotionally less resonant'],
      'More and higher-quality creative work — more adventurous and distinctive output',
      'Making work primarily to get likes, impress people, or earn approval tends to produce safer, more derivative work calculated to please. Making work because you are genuinely interested in the problem produces more adventurous, distinctive output. The most useful question is not "will people like this?" but "does this interest me?"',
      4,
    ),
    mc(
      'Constraints (like writing in a specific form, working with limited colors, or using only one tool) tend to:',
      ['Suppress creativity by limiting available options', 'Enhance creativity by focusing energy and forcing solutions that wouldn\'t emerge in unlimited space', 'Only benefit advanced practitioners; beginners need maximum freedom', 'Produce more technically correct but less emotionally expressive work'],
      'Enhance creativity by focusing energy and forcing solutions that wouldn\'t emerge in unlimited space',
      'When everything is possible, making a decision requires justifying it against infinite alternatives. Constraints narrow the space, making decisions easier and directing creative energy into working within the limits. A sonnet\'s 14-line structure, a photographer\'s one-lens commitment, a composer writing for a specific ensemble — constraints generate solutions that unlimited freedom never reaches.',
      5,
    ),
  ],

  'idea-generation': [
    mc(
      'The most important rule of effective brainstorming is:',
      ['Generating ideas in a group rather than alone, to benefit from diverse perspectives', 'Evaluating ideas critically as they are generated to focus on the most promising options immediately', 'Completely separating the generation phase (quantity, no judgment) from the evaluation phase (selection)', 'Starting with the most obvious ideas to clear them out before reaching creative ones'],
      'Completely separating the generation phase (quantity, no judgment) from the evaluation phase (selection)',
      'Mixing generation and evaluation is where brainstorming fails. When you judge ideas while generating them, you stop exploring before you find the unexpected ones. The good ideas are often not the first ideas — they come after the obvious options are exhausted. Suspend judgment entirely during generation; evaluate after.',
      1,
    ),
    mc(
      'The SCAMPER technique is most useful for:',
      ['Generating completely original ideas with no starting point', 'Systematically exploring variations on an existing idea, product, or creative work', 'Managing the evaluation and selection phase of idea generation', 'Organizing ideas generated in brainstorming into categories'],
      'Systematically exploring variations on an existing idea, product, or creative work',
      'SCAMPER (Substitute, Combine, Adapt, Modify/Magnify/Minimize, Put to other uses, Eliminate, Reverse) provides a structured checklist for exploring a design space around an existing starting point. It forces systematic exploration of variations you might leave undiscovered through free association alone.',
      2,
    ),
    mc(
      'The "forced connections" technique (random input) generates ideas by:',
      ['Combining two existing ideas that are obviously related and natural partners', 'Forcing a connection between a random, unrelated element and the creative problem, breaking habitual associative patterns', 'Randomly selecting from a list of pre-approved creative strategies', 'Using random time limits to force faster ideation'],
      'Forcing a connection between a random, unrelated element and the creative problem, breaking habitual associative patterns',
      'Your brain is very good at finding connections even when none are obvious. A random word (from a dictionary, a room object, a magazine) breaks you out of the associative ruts you\'d fall into without it. The connections that feel most forced are sometimes the most generative — they lead to territory you wouldn\'t reach through rational exploration.',
      3,
    ),
    mc(
      'Sleep and incubation are legitimate parts of the creative process because:',
      ['Sleeping on a problem is a superstition without scientific basis', 'The subconscious continues processing problems during rest and unrelated activities, with solutions emerging that focused effort cannot access', 'Creative ideas only come during sleep, not during waking work sessions', 'Sleep resets the brain\'s divergent thinking capacity to zero, enabling a fresh start'],
      'The subconscious continues processing problems during rest and unrelated activities, with solutions emerging that focused effort cannot access',
      'Memory consolidation and associative processing happen outside conscious awareness. The practical implication: load up on the problem thoroughly, work on it, then let it rest. Some of the most useful ideas surface while walking, showering, or washing dishes — during activities that occupy the body but free the mind.',
      4,
    ),
    mc(
      'When brainstorming produces ideas but everything is immediately dismissed, the likely cause is:',
      ['Input poverty — not enough raw material to generate from', 'Perfectionism — applying convergent (evaluative) thinking too early during the generation phase', 'Working alone rather than in a group setting', 'Insufficient time pressure to force commitment to ideas'],
      'Perfectionism — applying convergent (evaluative) thinking too early during the generation phase',
      'If you generate ideas but dismiss all of them immediately, convergent thinking is running during the generative phase. The fix: force yourself to fill an entire page before evaluating anything. Lower the criterion from "good enough" to "anything at all." Perfectionism during generation produces nothing worth evaluating.',
      5,
    ),
  ],

  'creative-blocks': [
    mc(
      'The most common and damaging creative block is:',
      ['Input depletion — running out of ideas due to insufficient external stimulus', 'Perfectionism — the belief that your worth depends on output quality, making failure feel dangerous to your identity', 'Impostor syndrome — not believing you deserve to call yourself a creative person', 'Technical skill gaps that prevent executing the ideas you can imagine'],
      'Perfectionism — the belief that your worth depends on output quality, making failure feel dangerous to your identity',
      'Perfectionism is not high standards — it is linking identity to work quality. If making bad work feels dangerous to your sense of self, not making anything becomes the "safe" choice. The solution is separating identity from work quality: the work can be bad; you are not bad. A bad first draft means you\'re a writer who wrote a first draft.',
      1,
    ),
    mc(
      'The "two-minute start" technique overcomes initiation blocks by:',
      ['Committing to only two minutes of work — low enough that even maximum resistance can overcome it — after which you usually continue', 'Timing yourself to measure how quickly you can start working', 'Working for exactly two minutes, then taking a break before the next two-minute session', 'Setting a timer so you stop exactly at two minutes and avoid over-committing'],
      'Committing to only two minutes of work — low enough that even maximum resistance can overcome it — after which you usually continue',
      'The resistance to starting is often resistance to the entire project\'s duration. "I have to spend two minutes on this" is survivable regardless of mood. Once inside the work for two minutes, you usually continue — because the resistance was to starting, not to the work itself.',
      2,
    ),
    mc(
      'Empty tank (input depletion) as a creative block is best addressed by:',
      ['Forcing more output even when nothing comes — the work will get better with persistence', 'Deliberately refilling through reading, visiting new places, diverse experiences, and consuming work outside your field', 'Switching to a completely different creative discipline permanently', 'Taking a multi-week complete rest from all creative activity'],
      'Deliberately refilling through reading, visiting new places, diverse experiences, and consuming work outside your field',
      'Creative output draws on accumulated input. When the tank is empty — when everything you make feels derivative, when you\'re recycling the same ideas — the solution is not more output but deliberate input: read something unrelated to your field, visit somewhere new, talk to someone whose life differs from yours. The brain generates novel combinations from diverse material.',
      3,
    ),
    mc(
      'When a project hits the "long middle" and seems like a mistake around one-third to halfway through, the recommended response is:',
      ['Abandon the project immediately since feeling stuck is a sign the idea was flawed from the start', 'Continue — the problems visible in the middle are usually problems with the draft, not with the idea, and more progress reveals the solutions', 'Start completely over with a different approach from the beginning', 'Show the unfinished work publicly to get feedback on whether to continue'],
      'Continue — the problems visible in the middle are usually problems with the draft, not with the idea, and more progress reveals the solutions',
      'Almost every creative person who has finished long-form work has felt around the midpoint that the project was a mistake. Almost all of them were wrong. The problems you see in the middle are often draft problems, not idea problems. More progress reveals solutions you can\'t see yet. Finishing a flawed project teaches vastly more than abandoning it.',
      4,
    ),
    mc(
      'Impostor syndrome in creative work is best addressed by:',
      ['Achieving sufficient external success to verify you deserve the creative title', 'Getting a formal degree or credential in your creative field', 'Doing the work regardless — the work doesn\'t require your identity to be resolved first', 'Avoiding public sharing until you feel fully confident in your abilities'],
      'Doing the work regardless — the work doesn\'t require your identity to be resolved first',
      'Virtually every creative person experiences impostor syndrome — even very successful ones. The creative people who keep making things despite it are not different in kind from those who stop; they have developed the habit of making despite the feeling. The identity question can remain open indefinitely while you work.',
      5,
    ),
  ],

  'habit-and-routine': [
    mc(
      'Paradoxically, creative routines (fixed schedules and habits) tend to enhance rather than suppress creativity because:',
      ['Creativity only emerges when the mind is fully relaxed and unstructured', 'When the time to work is not in question, creative energy is available for the actual work rather than for deciding whether and when to work', 'Fixed routines prevent creative people from experiencing the diverse inputs that fuel new ideas', 'Structured schedules force creative work to happen even when inspiration is absent, making inspiration unnecessary'],
      'When the time to work is not in question, creative energy is available for the actual work rather than for deciding whether and when to work',
      'When 7am means "this is creative work time" — no decision required — the limited willpower and decision-making energy available each day goes entirely into the work itself. The paradox: freedom of imagination is enhanced by temporal structure. Prolific creators from Beethoven to Toni Morrison maintained fixed daily work routines.',
      1,
    ),
    mc(
      'The "minimum viable habit" approach recommends starting a new creative habit by:',
      ['Committing to a rigorous schedule immediately to build discipline from the start', 'Setting an impossibly small commitment — like opening the document and writing one sentence — smaller than any plausible resistance', 'Setting multiple daily goals to maximize accountability', 'Starting with long sessions to build the habit of extended focused work quickly'],
      'Setting an impossibly small commitment — like opening the document and writing one sentence — smaller than any plausible resistance',
      'The goal of the minimum viable habit is to make the commitment smaller than any excuse. You can always do one sentence. The tiny commitment almost never produces only that — once started, most people continue — but the small threshold protects the habit on the hardest days, when a larger commitment would be skipped entirely.',
      2,
    ),
    mc(
      '"Habit stacking" involves:',
      ['Combining multiple creative practices into a single session', 'Attaching a new creative habit to an existing anchor habit — "after I do X, I do Y"', 'Gradually increasing the duration of creative sessions over several weeks', 'Tracking multiple habit metrics simultaneously in a single journal'],
      'Attaching a new creative habit to an existing anchor habit — "after I do X, I do Y"',
      '"After I pour my coffee, I sit down and write." "After I eat dinner, I sketch for 20 minutes." The existing anchor habit (coffee, dinner) triggers the new creative habit automatically, reducing the active decision-making required. Habits that are triggered by context rather than willpower are more reliable.',
      3,
    ),
    mc(
      'When a streak (consecutive days of creative work) breaks due to illness or life events, the recommended response is:',
      ['Treat the week as lost and begin a fresh streak the following Monday', 'Abandon the streak system entirely and switch to a different accountability approach', 'Return immediately — miss one day is an interruption; missing two begins to re-establish the "not doing" habit', 'Extend the next session to compensate for the missed day'],
      'Return immediately — miss one day is an interruption; missing two begins to re-establish the "not doing" habit',
      'Every streak eventually breaks — illness, travel, emergencies are inevitable. The "two-day rule" prevents one missed day from becoming a week, then a month. Miss one day without drama; return the next day without narrative. "I missed Monday, so this week is ruined" is a story, not a fact.',
      4,
    ),
    mc(
      'Regular daily creative practice, in addition to producing output, develops:',
      ['The ability to work without any external feedback or validation', 'An accelerated closing of the skill-taste gap, and the discovery of your actual creative interests and point of view through what recurs in your work', 'Complete freedom from creative blocks through habit and willpower', 'The ability to produce finished, polished work in every session without revision'],
      'An accelerated closing of the skill-taste gap, and the discovery of your actual creative interests and point of view through what recurs in your work',
      'Daily practice develops your eye faster — you make better judgments and decisions because you\'re doing it every day. More importantly, your creative identity emerges from looking at what you actually make: the subjects that recur, the problems you return to, the approaches you instinctively prefer. You don\'t discover this by thinking about it. You discover it by making things.',
      5,
    ),
  ],

  'feedback-and-critique': [
    mc(
      'The most useful type of feedback for work in progress is generally:',
      ['Evaluative feedback — direct judgments ("this is good/bad") that tell you whether to continue', 'Prescriptive feedback — specific solutions that tell you exactly what changes to make', 'Diagnostic feedback — descriptions of what is or isn\'t working from the audience\'s perspective', 'Comparative feedback — how the work compares to professional examples in the field'],
      'Diagnostic feedback — descriptions of what is or isn\'t working from the audience\'s perspective',
      'Diagnostic feedback tells you what the audience experienced: "I lost track of the story here," "my eye keeps going to this corner and I don\'t know why." It identifies problems without prescribing specific solutions, leaving the creative decisions to the maker. Prescription can close off options; diagnosis opens them.',
      1,
    ),
    mc(
      'When receiving critique, the temptation to explain what you were trying to do is a "trap" because:',
      ['It reveals your intentions to competitors who might steal your ideas', 'If someone didn\'t understand something in your work, explaining it confirms the work failed to communicate — the explanation should be in the work, not in your defense of it', 'Explaining your intent makes the critic feel bad for misunderstanding', 'It wastes time that could be spent listening to more feedback'],
      'If someone didn\'t understand something in your work, explaining it confirms the work failed to communicate — the explanation should be in the work, not in your defense of it',
      '"What I was going for was..." is almost always followed by information that should be in the work itself. If the work communicated what you intended, no explanation is needed. If it didn\'t, the explanation confirms the gap between intention and effect — which is exactly the information you needed, not something to defend against.',
      2,
    ),
    mc(
      'The filtering process for feedback recommends weighting most heavily:',
      ['Feedback from people who are more technically skilled than the maker', 'Notes that multiple independent reviewers identify independently — frequency-weighted feedback as signal', 'The first feedback received, since initial impressions are most accurate', 'Feedback that feels least threatening, since comfort allows genuine consideration'],
      'Notes that multiple independent reviewers identify independently — frequency-weighted feedback as signal',
      'If three different readers independently note the same problem — the ending feels abrupt, the background is distracting, the second verse is weak — that convergent feedback is strong signal. If only one person notes it, it might still be right, but the confidence is lower. Single-source feedback might reflect the reviewer\'s preferences rather than the work\'s actual problems.',
      3,
    ),
    mc(
      'The Liz Lerman Critical Response Process gives the maker more control by:',
      ['Requiring all feedback to be positive before any negative notes are given', 'Structuring the session so the maker can ask specific questions and decide what opinions to hear', 'Limiting feedback sessions to fifteen minutes to reduce the emotional intensity', 'Having the maker grade all feedback as helpful or unhelpful immediately after receiving it'],
      'Structuring the session so the maker can ask specific questions and decide what opinions to hear',
      'The four-step process begins with statements of meaning (no evaluation), then the maker asks specific questions, then responders ask neutral questions, and finally responders ask permission before giving opinions. This gives the maker significant control over what feedback they receive, producing more targeted, useful information.',
      4,
    ),
    mc(
      'When giving critique, "describe your experience, not your prescription" means:',
      ['Share your emotional response to the work rather than any analytical observation', 'Tell the maker what happened for you as an audience member rather than telling them what to do to fix it', 'Avoid giving any specific feedback that might be taken as prescriptive', 'Only comment on parts of the work that affected you personally'],
      'Tell the maker what happened for you as an audience member rather than telling them what to do to fix it',
      '"I felt confused about who was speaking in this section" is more useful than "you should clarify who\'s speaking." The first tells the maker what happened; the second tells them one possible solution — which might not be right for the work. Describing the experience leaves the creative problem and its solution in the maker\'s hands.',
      5,
    ),
  ],

  'sharing-your-work': [
    mc(
      'One practical argument for sharing creative work (beyond connection and feedback) is that:',
      ['Social media metrics provide objective measures of work quality', 'Sharing forces completion — work that stays private can remain permanently unfinished; committing to sharing creates the deadline that produces a done thing', 'Public sharing protects work from being copied by establishing a timestamp', 'Audience feedback always improves the work before it is finalized'],
      'Sharing forces completion — work that stays private can remain permanently unfinished; committing to sharing creates the deadline that produces a done thing',
      'Work in private can remain "not quite ready" forever. The commitment to share — to a deadline, to a format, to an audience — converts an indefinitely evolving process into something finished. This is one of the most practical arguments for sharing: it produces done work, which private perfectionism never does.',
      1,
    ),
    mc(
      'When starting to share creative work, the recommended approach is:',
      ['Launch everywhere simultaneously to maximize initial reach', 'Share first with one trusted person or a small specific community — a level that is slightly outside the comfort zone but survivable', 'Wait until the work is as close to perfect as possible before any sharing', 'Share immediately and publicly to build accountability and discipline'],
      'Share first with one trusted person or a small specific community — a level that is slightly outside the comfort zone but survivable',
      'Sharing exists on a spectrum. Starting at the lower-stakes end — one person, a writing group, a photography forum — builds the sharing muscle for higher-stakes contexts later. The goal is a level that stretches but does not overwhelm. One person\'s response is survivable regardless of outcome.',
      2,
    ),
    mc(
      'An email newsletter (like on Substack) is valuable for sharing creative work because:',
      ['It automatically reaches more people than social media platforms', 'It provides direct access to opt-in subscribers with no algorithm filtering — a list of 500 engaged subscribers can be worth more than 50,000 social media followers', 'It is the easiest platform to set up and maintain', 'It generates more revenue than other sharing platforms for most creators'],
      'It provides direct access to opt-in subscribers with no algorithm filtering — a list of 500 engaged subscribers can be worth more than 50,000 social media followers',
      'An email list is owned media — no platform can change the algorithm to reduce your reach, no platform can disappear taking your audience with it. People who subscribe opted in deliberately, making them more engaged than passive social media followers. Direct access without algorithmic filtering is uniquely valuable.',
      3,
    ),
    mc(
      'Metrics (follower counts, view counts, likes) should be treated with caution as measures of creative quality because:',
      ['Metrics are never useful and should be ignored entirely', 'They measure virality, platform fit, timing, and network effects as much as quality — a work reaching 12 people and mattering to three of them is not less valuable than a viral post forgotten the same day', 'Metrics only apply to commercial creative work, not personal projects', 'High metrics always indicate quality work that deserves to be replicated'],
      'They measure virality, platform fit, timing, and network effects as much as quality — a work reaching 12 people and mattering to three of them is not less valuable than a viral post forgotten the same day',
      'Metrics feel like objective quality measures, but they are not. They measure reach, timing, platform algorithm favorability, and network size. Some excellent work reaches very few people; some mediocre work goes viral. Using metrics to determine creative direction produces work optimized for virality, not for quality or meaning.',
      4,
    ),
    mc(
      'The question to ask when deciding whether to share work that you\'re keeping private is:',
      ['"Am I keeping this private because it is genuinely private and made for myself, or because I am afraid of sharing it?"', '"Will this work be universally understood and appreciated by any audience?"', '"Has this work been reviewed by at least three other people whose opinions I trust?"', '"Is this work technically perfect enough to represent my capabilities accurately?"'],
      '"Am I keeping this private because it is genuinely private and made for myself, or because I am afraid of sharing it?"',
      'Some creative work is genuinely private — journaling, therapeutic writing, personal processing. This doesn\'t need to be shared. But if the honest answer is fear — fear of judgment, misunderstanding, or criticism — then the work probably deserves to be shared. The goal is not to share everything; the goal is to not let fear be the reason you don\'t.',
      5,
    ),
  ],
}
