import type { AssessmentDef, AssessmentQuestionDef } from '../types'

const mc = (q: string, opts: string[], ans: string, exp: string, pts: number, ord: number): AssessmentQuestionDef =>
  ({ question: q, type: 'MULTIPLE_CHOICE', options: opts, correctAnswer: ans, explanation: exp, points: pts, order: ord })
const oe = (q: string, ans: string, exp: string, pts: number, ord: number): AssessmentQuestionDef =>
  ({ question: q, type: 'OPEN_ENDED', correctAnswer: ans, explanation: exp, points: pts, order: ord })

export const businessAssessments: Record<string, AssessmentDef> = {
  'business-foundations': {
    title: 'Business Foundations Assessment', passingScore: 75, timeLimitMin: 30,
    questions: [
      mc('What is the primary legal advantage of an LLC over a sole proprietorship?', ['Lower tax rates', 'Personal liability protection', 'Easier bank account setup', 'No paperwork required'], 'Personal liability protection', 'An LLC separates personal and business assets — if the business is sued, your personal property is generally protected. Sole proprietors have no such separation.', 1, 1),
      mc('Which component is NOT typically found in a business plan?', ['Market analysis', 'Financial projections', 'Employee vacation schedules', 'Value proposition'], 'Employee vacation schedules', 'A business plan covers strategy, market, operations, and financials. Day-to-day HR schedules are operational details handled separately after launch.', 1, 2),
      mc('Why should business and personal finances be kept separate?', ['To avoid paying taxes', 'To protect liability status and accurately measure profitability', 'Because banks require it for all accounts', 'To qualify for government grants'], 'To protect liability status and accurately measure profitability', 'Commingling funds can pierce the corporate veil (voiding LLC protection), makes bookkeeping a nightmare, and obscures whether the business is actually profitable.', 1, 3),
      mc('A revenue model describes:', ['How a business recruits employees', 'How a business generates income from its customers', 'The organizational chart of a company', 'A business\'s marketing strategy'], 'How a business generates income from its customers', 'Revenue models define the mechanism of income — subscriptions, one-time sales, licensing, advertising, etc. — and are central to evaluating business viability.', 1, 4),
      mc('Which business structure passes profits directly to the owner\'s personal tax return with no separate corporate tax?', ['C-Corporation', 'Sole Proprietorship', 'Nonprofit', 'Public Company'], 'Sole Proprietorship', 'Sole proprietorships are pass-through entities — all profits and losses appear on Schedule C of the owner\'s personal 1040. LLCs taxed as sole proprietors work the same way.', 1, 5),
      mc('Defining your target customer is important primarily because:', ['It is required by law', 'It helps you focus marketing and product decisions on people most likely to buy', 'It eliminates the need for a business plan', 'It guarantees funding from investors'], 'It helps you focus marketing and product decisions on people most likely to buy', 'Without a defined customer, marketing becomes scattershot and expensive. Knowing who you serve lets you speak their language, go where they are, and solve their actual problems.', 1, 6),
      mc('What is opportunity cost?', ['The cost of a lost business opportunity', 'The value of the next best alternative you give up when making a choice', 'The price of raw materials used in production', 'The interest charged on a business loan'], 'The value of the next best alternative you give up when making a choice', 'Every decision has a trade-off. Choosing to spend time on one activity means forgoing another. Recognizing opportunity cost leads to better resource allocation.', 1, 7),
      mc('A partnership agreement is important because:', ['It registers the business with the government', 'It defines each partner\'s roles, ownership share, and what happens during disputes or exit', 'It eliminates personal liability for all partners', 'It is required to open a business bank account'], 'It defines each partner\'s roles, ownership share, and what happens during disputes or exit', 'Without a written agreement, disputes default to state law, which may not reflect the partners\' intent. A clear agreement prevents most partnership conflicts before they start.', 1, 8),
      oe('Explain the difference between a hobby and a business, and why the distinction matters legally and financially.', 'A business operates with consistent intent to profit from exchanging value. The IRS distinguishes hobbies from businesses using factors like profit motive, time invested, and history of income or losses. Hobby losses cannot be deducted; business losses can offset other income.', 'The IRS hobby-loss rules mean that if your activity is classified as a hobby, you can\'t deduct expenses beyond income from it. A real business can deduct losses, claim depreciation, and access lending that a hobby cannot.', 2, 9),
      oe('You are starting a lawn care business. Describe two decisions where understanding your revenue model would affect how you structure the business.', 'A per-lawn transactional model requires different pricing, scheduling, and cash flow management than a monthly subscription model. Subscriptions provide predictable income but require customer retention systems. The choice affects hiring (full-time vs. seasonal), equipment investment, and marketing approach.', 'Revenue model affects pricing strategy, customer relationship type, cash flow predictability, hiring needs, and even what software you use to manage the business. Thinking it through early prevents costly pivots later.', 2, 10),
    ],
  },
  'operations-and-finance': {
    title: 'Operations & Finance Assessment', passingScore: 75, timeLimitMin: 30,
    questions: [
      mc('Cash flow differs from profit because:', ['Cash flow accounts for taxes while profit does not', 'Cash flow tracks actual money in and out; profit is revenue minus expenses on paper', 'They are the same thing expressed differently', 'Profit includes depreciation while cash flow does not'], 'Cash flow tracks actual money in and out; profit is revenue minus expenses on paper', 'A business can be profitable on paper but cash-flow negative — for example if customers pay 60 days after the work is done but suppliers must be paid immediately.', 1, 1),
      mc('What does accounts receivable represent?', ['Money you owe to suppliers', 'Money owed to your business by customers for goods or services already delivered', 'The total value of your inventory', 'Cash in your business bank account'], 'Money owed to your business by customers for goods or services already delivered', 'Accounts receivable is an asset — you\'ve delivered the product or service but haven\'t collected yet. High receivables can cause cash flow problems even in a profitable business.', 1, 2),
      mc('Gross profit margin is calculated as:', ['(Revenue - Total Expenses) / Revenue', '(Revenue - Cost of Goods Sold) / Revenue', 'Net Income / Total Assets', 'Operating Expenses / Revenue'], '(Revenue - Cost of Goods Sold) / Revenue', 'Gross margin shows how efficiently a business produces its product or service before accounting for overhead. It\'s the foundation of pricing decisions.', 1, 3),
      mc('A break-even point is the sales level at which:', ['The business begins to make a profit above normal', 'Total revenue exactly equals total costs — no profit, no loss', 'Fixed costs are fully recovered', 'Variable costs become zero'], 'Total revenue exactly equals total costs — no profit, no loss', 'Knowing your break-even gives you a minimum sales target and helps evaluate whether a business model is viable given realistic sales expectations.', 1, 4),
      mc('Which of the following is a fixed cost?', ['Materials used to make each product', 'Monthly rent for a storefront', 'Commission paid per sale', 'Packaging costs'], 'Monthly rent for a storefront', 'Fixed costs don\'t change with production volume — rent is the same whether you sell 10 or 10,000 units. Variable costs scale with output.', 1, 5),
      mc('Double-entry bookkeeping means every transaction:', ['Is recorded twice for backup purposes', 'Affects at least two accounts — a debit in one and a credit in another', 'Must be approved by two people', 'Is entered in both cash and accrual systems'], 'Affects at least two accounts — a debit in one and a credit in another', 'Double-entry ensures the accounting equation (Assets = Liabilities + Equity) stays balanced and provides a built-in error check on every transaction.', 1, 6),
      mc('Pricing based on cost-plus means:', ['Charging whatever the market will bear', 'Adding a markup percentage to the cost of producing or delivering a product', 'Matching a competitor\'s price exactly', 'Setting prices based on perceived customer value'], 'Adding a markup percentage to the cost of producing or delivering a product', 'Cost-plus is simple but ignores market conditions and value perception. It ensures costs are covered but may leave money on the table or price you out of the market.', 1, 7),
      mc('An income statement (P&L) shows:', ['A company\'s assets and liabilities at a point in time', 'Revenue, expenses, and profit over a time period', 'All cash received and spent during a period', 'The equity value of the business'], 'Revenue, expenses, and profit over a time period', 'The income statement measures performance over a period (month, quarter, year). The balance sheet measures financial position at a single point in time.', 1, 8),
      oe('A client pays you $5,000 for a job you completed last month. Explain how this affects your cash flow and your income statement differently.', 'The income statement recorded $5,000 revenue last month when the work was delivered. This month, cash flow increases by $5,000 when payment is received, but the income statement is unaffected — the revenue was already recognized. This is the core difference between accrual and cash accounting.', 'Revenue recognition and cash receipt are often separated in time. Accrual accounting records revenue when earned; cash accounting records it when received. The difference is especially pronounced for businesses with net-30 or net-60 payment terms.', 2, 9),
      oe('Your business has $8,000 in monthly fixed costs and a 40% gross margin. What monthly revenue do you need to break even, and how did you calculate it?', 'Break-even revenue = Fixed Costs / Gross Margin = $8,000 / 0.40 = $20,000 per month. At $20,000 revenue with 40% gross margin, gross profit is $8,000 — exactly enough to cover fixed costs with zero net profit.', 'This formula shows why margin matters so much. A business with 20% gross margin needs $40,000 in revenue to cover the same $8,000 in fixed costs. Higher margins mean a lower break-even and faster path to profitability.', 2, 10),
    ],
  },
  'sales-and-marketing': {
    title: 'Sales & Marketing Assessment', passingScore: 75, timeLimitMin: 30,
    questions: [
      mc('A value proposition is:', ['The price you charge for your product', 'A clear statement of why a customer should choose you over alternatives', 'Your company\'s mission statement', 'A legal guarantee of product performance'], 'A clear statement of why a customer should choose you over alternatives', 'A strong value proposition communicates the specific benefit, who it\'s for, and why you\'re the best choice. Vague claims like "great service" are not value propositions.', 1, 1),
      mc('Which stage of a sales funnel involves a prospect who knows your product and is comparing you to competitors?', ['Awareness', 'Consideration', 'Loyalty', 'Referral'], 'Consideration', 'The funnel moves from Awareness (they know you exist) → Consideration (evaluating options) → Decision (purchase) → Retention → Advocacy. Each stage requires different messaging.', 1, 2),
      mc('Customer acquisition cost (CAC) is:', ['The total marketing budget divided by brand impressions', 'The total sales and marketing spend divided by the number of new customers acquired', 'The cost of one sales call', 'The average order value of a new customer'], 'The total sales and marketing spend divided by the number of new customers acquired', 'CAC tells you how much it costs to win each customer. Comparing CAC to customer lifetime value (LTV) reveals whether your acquisition strategy is sustainable.', 1, 3),
      mc('Social proof most effectively persuades prospects because:', ['It appears in search results', 'People trust the experiences of other customers more than brand claims', 'It is cheaper than paid advertising', 'It reaches more people than email'], 'People trust the experiences of other customers more than brand claims', 'Reviews, testimonials, and case studies reduce perceived risk. Buyers naturally look for evidence that others have succeeded with your product before committing.', 1, 4),
      mc('A lead is best defined as:', ['Someone who has purchased from you before', 'A potential customer who has shown some interest but not yet bought', 'A business contact in your phone', 'An email on a purchased list'], 'A potential customer who has shown some interest but not yet bought', 'Leads are at the top of the sales funnel. Not all leads are equal — a qualified lead has shown intent and matches your ideal customer profile.', 1, 5),
      mc('Retention marketing focuses on:', ['Acquiring new customers through advertising', 'Keeping existing customers engaged and buying again', 'Building brand awareness in new markets', 'Generating press coverage'], 'Keeping existing customers engaged and buying again', 'Retaining customers is almost always cheaper than acquiring new ones. Loyalty programs, check-in emails, and excellent service are core retention tools.', 1, 6),
      mc('A unique selling proposition (USP) differs from a value proposition in that it emphasizes:', ['Price above all other factors', 'What makes you specifically different from every competitor', 'The breadth of your product line', 'Your company\'s founding story'], 'What makes you specifically different from every competitor', 'Your USP is the one thing you do or offer that no competitor can fully replicate. It\'s the answer to "Why you specifically?"', 1, 7),
      mc('Conversion rate in digital marketing refers to:', ['The number of website visitors per month', 'The percentage of visitors who take a desired action (purchase, sign up, etc.)', 'The ratio of clicks to impressions on an ad', 'Monthly recurring revenue growth'], 'The percentage of visitors who take a desired action (purchase, sign up, etc.)', 'Conversion rate optimization (CRO) is often more cost-effective than driving more traffic — doubling your conversion rate doubles revenue without spending more on ads.', 1, 8),
      oe('Describe the difference between inbound and outbound marketing and give one example of each that would work for a local service business.', 'Inbound marketing attracts customers by creating valuable content or experiences that bring them to you (e.g., a plumber writing blog posts about "how to fix a slow drain" that rank in Google). Outbound pushes a message to potential customers (e.g., door-hanger flyers in target neighborhoods). Inbound builds long-term trust; outbound creates immediate reach.', 'Both have a role. Inbound is often lower cost per lead over time but requires patience. Outbound can generate quick results but must be targeted to avoid wasted spend. Local service businesses often combine both.', 2, 9),
      oe('A customer bought from you six months ago but hasn\'t returned. Write two sentences describing a re-engagement approach and explain why timing matters.', 'A check-in message at 3-6 months acknowledges the relationship without seeming desperate — something like "It\'s been a while since your last [service]. Wanted to make sure everything is still going well and let you know about our current pricing." Timing matters because waiting too long means the customer may have already found a replacement, while reaching out too soon feels pushy.', 'Re-engagement works best when tied to a natural reason to reach out — a seasonal reminder, a related service, or a genuine check-in. The goal is to be top-of-mind at the moment the customer has a new need.', 2, 10),
    ],
  },
  'legal-basics': {
    title: 'Legal Basics for Business Assessment', passingScore: 75, timeLimitMin: 30,
    questions: [
      mc('Which element is NOT required to form a valid contract?', ['Offer', 'Acceptance', 'Consideration', 'A written signature'], 'A written signature', 'Most contracts are valid whether oral or written. The core requirements are offer, acceptance, consideration (something of value exchanged), and capacity of both parties. Written contracts are simply easier to enforce.', 1, 1),
      mc('Intellectual property (IP) protection for a business name or logo is called:', ['A copyright', 'A trademark', 'A patent', 'A trade secret'], 'A trademark', 'Trademarks protect brand identifiers — names, logos, slogans. Copyrights protect original creative works. Patents protect inventions. Trade secrets protect confidential business information.', 1, 2),
      mc('Personal liability protection in an LLC can be "pierced" (lost) when:', ['The LLC files taxes late', 'The owner commingles personal and business funds or uses the business as an alter ego', 'The LLC has only one member', 'The business operates in multiple states'], 'The owner commingles personal and business funds or uses the business as an alter ego', 'Courts can disregard the LLC structure if the owner treats the business as their personal piggy bank or fails to maintain proper records and separation. This is called piercing the corporate veil.', 1, 3),
      mc('An independent contractor differs from an employee primarily because:', ['Contractors always earn more money', 'Contractors control how and when they work; employers control employees\' methods', 'Contractors can\'t be held to deadlines', 'Contractors don\'t pay income tax'], 'Contractors control how and when they work; employers control employees\' methods', 'The IRS uses the behavioral control test among others. Misclassifying employees as contractors exposes businesses to back taxes, penalties, and benefits liability.', 1, 4),
      mc('A non-disclosure agreement (NDA) is used to:', ['Register a business name', 'Legally obligate parties to keep shared information confidential', 'Transfer ownership of intellectual property', 'Limit liability in a service contract'], 'Legally obligate parties to keep shared information confidential', 'NDAs protect trade secrets, client lists, pricing strategies, and other confidential information shared with employees, contractors, or potential partners.', 1, 5),
      mc('If a contract dispute goes to small claims court, what is the typical maximum claim amount?', ['$500', '$5,000 to $10,000 (varies by state)', '$50,000', 'No limit'], '$5,000 to $10,000 (varies by state)', 'Small claims court is designed for straightforward disputes without attorneys. The limit varies by state but is typically $5,000-$10,000. It\'s a practical option for collecting on unpaid invoices.', 1, 6),
      mc('A limitation of liability clause in a contract:', ['Eliminates all legal risk for one party', 'Caps the amount one party can recover from the other in a dispute', 'Transfers all risk to the customer', 'Is unenforceable in most states'], 'Caps the amount one party can recover from the other in a dispute', 'Service contracts often include clauses limiting liability to the amount paid for the service. Courts generally enforce these unless they\'re unconscionable or violate public policy.', 1, 7),
      mc('When must you collect and remit sales tax?', ['Only on transactions over $1,000', 'When selling taxable goods or services in states where you have nexus', 'Only on online sales', 'Only if you have a physical storefront'], 'When selling taxable goods or services in states where you have nexus', 'Nexus is the legal connection that creates a tax obligation in a state — typically a physical presence or, after the Wayfair decision, sufficient economic activity.', 1, 8),
      oe('A customer refuses to pay your invoice after you completed the agreed-upon work. Describe two steps you could take before hiring a lawyer, and explain why documentation matters throughout.', 'First, send a formal demand letter specifying the amount owed, the work completed, and a payment deadline — this creates a paper trail and often prompts payment. Second, file in small claims court if the amount is within the limit. Documentation (signed contracts, written scope, emails confirming completion, photos of finished work) is essential because courts require evidence, not just testimony.', 'Most non-payment situations are resolved before court. A professional demand letter signals you\'re serious. If it goes to court, whoever has the best documentation usually wins. Good habits from the start (written agreements, written change orders, delivery confirmations) protect you before disputes arise.', 2, 9),
      oe('Explain why using a contract template from the internet without modification could be risky for a small service business.', 'Generic templates may not reflect your state\'s laws, your specific service type, or the protections you actually need. They may include clauses that don\'t apply or miss critical ones — like payment terms, scope limitations, dispute resolution, or liability caps specific to your trade. A lawyer reviewing or customizing a template is a one-time cost that can prevent much larger losses.', 'Templates are a starting point, not a final answer. The most important clauses — limitation of liability, payment terms, change order procedures, cancellation policies — must be tailored to your actual business model and state law. One poorly worded clause can be very expensive.', 2, 10),
    ],
  },
  'taxes-for-business': {
    title: 'Business Taxes Assessment', passingScore: 75, timeLimitMin: 30,
    questions: [
      mc('Self-employment tax covers:', ['Federal and state income tax', 'Social Security and Medicare contributions for self-employed individuals', 'Sales tax on business transactions', 'Property tax on business equipment'], 'Social Security and Medicare contributions for self-employed individuals', 'Employees split SS/Medicare with employers. Self-employed individuals pay both halves — 15.3% on net self-employment income. Half is deductible on the personal return.', 1, 1),
      mc('Quarterly estimated tax payments are due:', ['Monthly', 'Four times per year in April, June, September, and January', 'Once per year with the annual return', 'Whenever the business has a profitable month'], 'Four times per year in April, June, September, and January', 'Employees have taxes withheld automatically. Self-employed individuals must estimate and pay quarterly to avoid underpayment penalties at year-end.', 1, 2),
      mc('A business expense is deductible when it is:', ['Over $500 in value', 'Ordinary and necessary for the business', 'Paid by credit card', 'Approved by an accountant'], 'Ordinary and necessary for the business', 'The IRS standard: "ordinary" means common in your industry; "necessary" means helpful and appropriate. Personal expenses disguised as business deductions are the most common audit trigger.', 1, 3),
      mc('The home office deduction requires that the space be used:', ['Only occasionally for work', 'Regularly and exclusively for business', 'At least 8 hours per week', 'In a room with a separate entrance'], 'Regularly and exclusively for business', '"Exclusive use" is strict — a guest bedroom that doubles as an office doesn\'t qualify. A dedicated room used only for work does. The deduction can be calculated using actual expenses or the simplified method ($5/sq ft).', 1, 4),
      mc('Depreciation allows businesses to:', ['Deduct the full cost of equipment in the year it breaks down', 'Spread the cost of a long-lived asset as an expense over its useful life', 'Avoid paying tax on equipment purchases entirely', 'Write off the market value decline of inventory'], 'Spread the cost of a long-lived asset as an expense over its useful life', 'A truck bought for $30,000 might be depreciated over 5 years, reducing taxable income by $6,000/year. Section 179 and bonus depreciation allow immediate expensing of qualifying assets.', 1, 5),
      mc('Which form reports self-employment income on a personal tax return?', ['W-2', 'Schedule C', '1099-NEC', 'Form 1120'], 'Schedule C', 'Sole proprietors and single-member LLCs attach Schedule C to their 1040, reporting business revenue and expenses. The net profit is also subject to self-employment tax on Schedule SE.', 1, 6),
      mc('Cash basis accounting records income and expenses:', ['When they are earned and incurred, regardless of payment', 'When cash is actually received or paid', 'At the end of each fiscal quarter', 'Based on when invoices are issued'], 'When cash is actually received or paid', 'Most small businesses use cash basis — simpler and avoids paying tax on income not yet received. Accrual basis is required for businesses above certain revenue thresholds or with inventory.', 1, 7),
      mc('A 1099-NEC must be issued to a contractor when you pay them:', ['Any amount for services', '$500 or more', '$600 or more', '$1,000 or more'], '$600 or more', 'If you pay a non-employee (freelancer, contractor) $600 or more in a year for services, you must issue a 1099-NEC by January 31. Failure to do so can result in penalties.', 1, 8),
      oe('A sole proprietor earned $80,000 in revenue and had $30,000 in deductible business expenses. Explain how self-employment tax applies to this situation and roughly what it would be.', 'Net profit = $80,000 - $30,000 = $50,000. SE tax applies to 92.35% of net profit ($50,000 × 0.9235 = $46,175). SE tax rate is 15.3%, so SE tax ≈ $7,065. Then half of SE tax ($3,533) is deductible from gross income on the 1040. The remaining $46,467 is subject to ordinary income tax at the appropriate bracket.', 'SE tax is in addition to regular income tax. Many first-year sole proprietors are surprised by how much they owe. Quarterly estimated payments are how you pay it throughout the year rather than in one lump sum.', 2, 9),
      oe('Describe two legitimate tax strategies a small business owner could use to reduce taxable income, and why documentation of each is critical.', 'Contributing to a SEP-IRA or Solo 401(k) reduces taxable income dollar-for-dollar (up to annual limits). Keeping thorough records of business mileage (date, purpose, miles) allows deducting vehicle business use. Documentation is critical because the IRS can audit up to 3 years back, and without records, even legitimate deductions can be disallowed.', 'Tax strategy is legal and legitimate — it\'s different from tax evasion. The difference between good planning and a penalty is documentation. Receipts, mileage logs, and clear business-purpose notes on expenses protect every deduction.', 2, 10),
    ],
  },
  'hiring-and-people': {
    title: 'Hiring & People Management Assessment', passingScore: 75, timeLimitMin: 30,
    questions: [
      mc('The key IRS test for worker classification focuses on:', ['How much the worker is paid', 'Behavioral control, financial control, and the type of relationship', 'Whether the worker has other clients', 'The duration of the working relationship'], 'Behavioral control, financial control, and the type of relationship', 'The IRS three-part test looks at: does the company control how work is done (behavioral), financial aspects like equipment and opportunity for profit (financial), and written contracts/benefits/permanency (relationship type).', 1, 1),
      mc('When hiring a W-2 employee, the employer is responsible for:', ['Only paying gross wages — taxes are the employee\'s responsibility', 'Withholding federal/state income tax, FICA, and paying employer\'s share of FICA', 'Filing the employee\'s annual tax return', 'Providing all tools and transportation automatically'], 'Withholding federal/state income tax, FICA, and paying employer\'s share of FICA', 'Employers withhold employee taxes and match Social Security/Medicare (6.2%/1.45% each). They also pay federal unemployment tax (FUTA) and often state unemployment.', 1, 2),
      mc('An offer letter should always include:', ['A guarantee of lifetime employment', 'Role title, compensation, start date, and whether employment is at-will', 'The company\'s complete policy manual', 'Performance review schedule for the next five years'], 'Role title, compensation, start date, and whether employment is at-will', 'A clear offer letter sets expectations and protects both parties. Most states are at-will, meaning either party can end employment at any time without cause — stating this avoids implied contract claims.', 1, 3),
      mc('At-will employment means:', ['The employee can quit at any time', 'Either party can end employment at any time for any legal reason, with or without cause', 'The employer can change job duties without notice', 'The employee has no legal protections whatsoever'], 'Either party can end employment at any time for any legal reason, with or without cause', 'At-will protects employers\' flexibility but still prohibits termination for illegal reasons (discrimination, retaliation for protected activity). Exceptions include contracts and implied promises of job security.', 1, 4),
      mc('A job description is most useful for:', ['Advertising on job boards only', 'Setting clear expectations, guiding hiring decisions, and documenting role scope for performance reviews', 'Meeting a legal requirement for all businesses', 'Determining the exact salary range automatically'], 'Setting clear expectations, guiding hiring decisions, and documenting role scope for performance reviews', 'A good job description is a management tool, not just a recruiting ad. It aligns expectations from day one and gives you something concrete to reference during performance conversations.', 1, 5),
      mc('Progressive discipline means:', ['Promoting high performers faster', 'Addressing performance issues in escalating steps before termination', 'Disciplining new employees more strictly', 'Requiring management approval for all disciplinary actions'], 'Addressing performance issues in escalating steps before termination', 'A typical progression: verbal warning → written warning → final written warning → termination. Documentation at each step protects against wrongful termination claims and gives employees clear chances to improve.', 1, 6),
      mc('When terminating an employee, you should:', ['Never provide a reason to avoid legal exposure', 'Document the specific reason, be direct, and ensure their final pay complies with state law', 'Always do it on a Friday to minimize disruption', 'First confirm they won\'t sue, then proceed'], 'Document the specific reason, be direct, and ensure their final pay complies with state law', 'Vague terminations can actually create more legal risk. Clear documented reasons tied to policy violations or performance issues are defensible. Final paycheck timing rules vary by state and must be followed.', 1, 7),
      mc('A non-compete agreement in an employment context:', ['Is enforceable in all 50 states without limitation', 'Restricts a former employee from working for competitors for a defined period and geography', 'Prevents the employee from discussing their salary', 'Is now illegal at the federal level in all circumstances'], 'Restricts a former employee from working for competitors for a defined period and geography', 'Non-competes are heavily restricted or unenforceable in several states (California, Minnesota, others). Where allowed, they must be reasonable in scope, duration, and geography to be enforceable.', 1, 8),
      oe('You hired someone as an independent contractor for a year. They work exclusively for you, use your tools, follow your schedule, and you control how they do their work. What is the legal risk, and what should you do?', 'This situation meets virtually every criterion for employee classification under the IRS test. The risk is misclassification liability: back payroll taxes, penalties, interest, unemployment insurance, and potentially employee benefits owed. You should consult an employment attorney and consider reclassifying the worker as a W-2 employee with proper setup of payroll.', 'The IRS and Department of Labor both aggressively pursue misclassification. Calling someone a contractor doesn\'t make them one — the actual working relationship determines status. Correction is always less expensive than an audit or lawsuit.', 2, 9),
      oe('Describe what an effective onboarding process for a first hire should include and why the first 90 days matter.', 'Effective onboarding covers paperwork (I-9, W-4, direct deposit), role training, introduction to systems and tools, clear 30/60/90-day goals, and regular check-ins. The first 90 days set the tone for performance expectations, culture fit, and retention. Poor onboarding is one of the leading causes of early turnover — replacing a hire costs 50-200% of their annual salary.', 'Onboarding is an investment. Employees who feel set up for success from day one are more productive faster and more likely to stay. Clear goals and early feedback loops also let you identify fit issues before significant investment has been made.', 2, 10),
    ],
  },
}
