import type { ExerciseDef } from '../types'

function mc(
  question: string,
  options: string[],
  correctAnswer: string,
  explanation: string,
  order: number
): ExerciseDef {
  return { question, type: 'MULTIPLE_CHOICE', options, correctAnswer, explanation, order }
}

export const globalEconExercises: Record<string, ExerciseDef[]> = {
  'why-countries-trade': [
    mc('What is comparative advantage?', ['Being the best in the world at producing something', 'The ability to produce a good at a lower opportunity cost than another country', 'Having more natural resources than trading partners', 'Producing more total output than other countries'], 'The ability to produce a good at a lower opportunity cost than another country', 'Comparative advantage (David Ricardo) says trade is beneficial even if one country is better at everything — each specializes in what it gives up least to produce.', 1),
    mc('If the US has an absolute advantage in both wheat and software, should it trade with India?', ['No — why trade when you\'re better at everything?', 'Yes — both benefit if each focuses on their comparative advantage', 'Only if India has an absolute advantage in something', 'Only if the US gets a surplus'], 'Yes — both benefit if each focuses on their comparative advantage', 'Even with absolute advantage in both, the US benefits by specializing in the good where its advantage is greatest (software) and trading for wheat.', 2),
    mc('What is the main benefit of international trade for consumers?', ['Jobs are always protected', 'Access to more goods at lower prices — competition and specialization increase efficiency', 'Domestic industries are strengthened', 'Trade always reduces the trade deficit'], 'Access to more goods at lower prices — competition and specialization increase efficiency', 'Trade expands variety and reduces prices through competition and specialization. Consumers gain access to goods they couldn\'t produce cheaply domestically.', 3),
    mc('Who are the "winners" and "losers" from free trade?', ['Everyone wins equally', 'Consumers and export industries win; import-competing domestic industries lose — but total gains exceed total losses', 'Only exporting countries win', 'Countries with trade surpluses always win'], 'Consumers and export industries win; import-competing domestic industries lose — but total gains exceed total losses', 'Trade creates overall gains but distributional effects. Workers in competing industries lose jobs, even as the overall economy grows — a key political tension.', 4),
    mc('What is the World Trade Organization (WTO)?', ['A body that manages international monetary policy', 'An international organization that sets rules for global trade and resolves trade disputes', 'A global free trade agreement', 'A US government agency managing exports'], 'An international organization that sets rules for global trade and resolves trade disputes', 'The WTO administers trade agreements, provides a forum for negotiations, and has a dispute resolution mechanism used when countries violate trade rules.', 5),
  ],
  'tariffs-and-trade-barriers': [
    mc('What is a tariff?', ['A quota on imports', 'A tax on imported goods', 'A subsidy to domestic producers', 'A ban on imports from specific countries'], 'A tax on imported goods', 'Tariffs are import taxes — they raise the price of foreign goods, making domestic products more competitive but raising prices for consumers.', 1),
    mc('What is an import quota?', ['A tax on imports above a certain value', 'A limit on the quantity of a good that can be imported', 'A quality standard required for imports', 'A ban on all imports of a specific product'], 'A limit on the quantity of a good that can be imported', 'Quotas restrict import volume directly — unlike tariffs which work through price. Both protect domestic producers at consumer expense.', 2),
    mc('What is the "infant industry" argument for trade protection?', ['Children\'s industries need special rules', 'New industries may need temporary protection to develop economies of scale and become competitive globally', 'All new firms deserve subsidies', 'Protection should only apply to industries with young workers'], 'New industries may need temporary protection to develop economies of scale and become competitive globally', 'The infant industry argument: temporarily shield emerging industries from international competition until they reach efficient scale. Critics note "temporary" protection rarely ends.', 3),
    mc('What is a trade war?', ['Military conflict over trade routes', 'A cycle of retaliatory tariffs between countries escalating until both are harmed', 'A WTO arbitration process', 'Competition between exporters of the same product'], 'A cycle of retaliatory tariffs between countries escalating until both are harmed', 'When one country raises tariffs, the other retaliates, then the first responds — escalating until both economies suffer higher prices and reduced trade.', 4),
    mc('Free trade agreements (FTAs) like NAFTA/USMCA do what?', ['Impose equal tariffs on all trading partners', 'Reduce or eliminate tariffs and trade barriers among member countries', 'Standardize wages across member countries', 'Create a shared currency among members'], 'Reduce or eliminate tariffs and trade barriers among member countries', 'FTAs create preferential trading relationships — lower barriers among members but typically maintain barriers against non-members.', 5),
  ],
  'trade-deficits': [
    mc('What is a trade deficit?', ['A government budget shortfall', 'When a country imports more goods and services than it exports', 'When a country\'s currency loses value', 'When exports exceed imports'], 'When a country imports more goods and services than it exports', 'Trade deficit = imports > exports. The US has run a persistent trade deficit — Americans buy more foreign goods than foreigners buy American goods.', 1),
    mc('Does a trade deficit necessarily indicate economic weakness?', ['Yes — deficits always signal a weak economy', 'No — the US runs large deficits while being the world\'s largest economy, partly because of strong consumer spending and dollar reserve status', 'Yes — it means the country is losing jobs to foreign countries', 'No — trade deficits are always beneficial'], 'No — the US runs large deficits while being the world\'s largest economy, partly because of strong consumer spending and dollar reserve status', 'Deficits often reflect strong domestic demand and investment inflows. Countries invest in the US because it\'s stable and profitable — which finances the deficit.', 2),
    mc('What is the current account?', ['A bank account used for international transactions', 'A record of all trade in goods and services plus income flows and transfers between countries', 'The government\'s annual operating budget', 'Corporate international profit statements'], 'A record of all trade in goods and services plus income flows and transfers between countries', 'The current account includes: trade balance (goods + services) + net investment income + net transfers. It\'s the broadest measure of trade flows.', 3),
    mc('If a country runs a current account deficit, what must be true of its financial account?', ['It must also run a financial account deficit', 'It must run a financial account surplus — foreign capital is flowing in to finance the deficit', 'The financial account is unrelated to the current account', 'The country must borrow from the IMF'], 'It must run a financial account surplus — foreign capital is flowing in to finance the deficit', 'Balance of payments accounting: current account + financial account = 0 (approximately). A current account deficit is financed by foreign investment (capital inflows).', 4),
    mc('Which of the following can reduce a trade deficit?', ['Raising tariffs alone (without other changes)', 'Increasing domestic savings relative to investment, or improving export competitiveness', 'Printing more money', 'Raising interest rates'], 'Increasing domestic savings relative to investment, or improving export competitiveness', 'Trade deficits are fundamentally a macroeconomic phenomenon tied to savings and investment. Tariffs redirect where you buy, not whether you run a deficit overall.', 5),
  ],
  'exchange-rates': [
    mc('What is an exchange rate?', ['The fee banks charge for currency exchange', 'The price of one currency in terms of another', 'The interest rate on foreign loans', 'The tariff rate between two countries'], 'The price of one currency in terms of another', 'If 1 USD = 0.92 EUR, that\'s the exchange rate. It determines how much foreign goods cost and what your exports sell for abroad.', 1),
    mc('When a currency appreciates, what happens to exports?', ['Exports become cheaper for foreign buyers', 'Exports become more expensive for foreign buyers, potentially reducing export volume', 'Exports are unaffected by exchange rates', 'Exports automatically increase due to stronger currency signal'], 'Exports become more expensive for foreign buyers, potentially reducing export volume', 'A stronger dollar makes US goods pricier abroad — reducing competitiveness. Imports become cheaper for Americans. A weaker dollar has the opposite effects.', 2),
    mc('What causes a currency to appreciate in value?', ['Higher inflation than trading partners', 'Increased demand for the currency — due to higher interest rates, trade surpluses, or strong economic performance', 'Government printing more money', 'Higher trade deficits'], 'Increased demand for the currency — due to higher interest rates, trade surpluses, or strong economic performance', 'More people wanting your currency (to invest, buy goods) drives up its price. High interest rates attract capital inflows, appreciating the currency.', 3),
    mc('What is a floating exchange rate?', ['A rate set by the government', 'An exchange rate determined by market supply and demand', 'A rate that changes only once per year', 'A rate pegged to gold'], 'An exchange rate determined by market supply and demand', 'Most major currencies (USD, EUR, GBP) float — their value fluctuates with market forces. Some countries fix or manage their exchange rates.', 4),
    mc('What is currency intervention?', ['A country defaulting on its debts', 'A central bank buying or selling its own currency to influence its exchange rate', 'A tariff policy targeting a specific country', 'IMF lending to countries in currency crisis'], 'A central bank buying or selling its own currency to influence its exchange rate', 'Central banks sometimes intervene — buying their own currency to prevent depreciation or selling it to prevent appreciation — managing exchange rates.', 5),
  ],
  'imf-and-world-bank': [
    mc('What is the IMF\'s primary role?', ['Funding development projects in poor countries', 'Providing short-term financial assistance to countries with balance-of-payments crises and promoting global monetary stability', 'Managing international trade disputes', 'Setting exchange rates for member countries'], 'Providing short-term financial assistance to countries with balance-of-payments crises and promoting global monetary stability', 'The IMF (International Monetary Fund) lends to countries that can\'t pay their international debts, usually attaching policy conditions requiring economic reform.', 1),
    mc('What does the World Bank primarily do?', ['Provide short-term crisis loans', 'Fund long-term development projects in developing countries — infrastructure, health, education', 'Manage global exchange rates', 'Resolve international trade disputes'], 'Fund long-term development projects in developing countries — infrastructure, health, education', 'The World Bank group provides long-term loans and grants for development — roads, schools, health systems — aimed at reducing poverty in developing nations.', 2),
    mc('What is "structural adjustment" in IMF lending?', ['Physical infrastructure improvements required by the IMF', 'Policy conditions (budget cuts, privatization, market liberalization) attached to IMF loans', 'The process of restructuring a country\'s national debt', 'IMF oversight of a country\'s legal system'], 'Policy conditions (budget cuts, privatization, market liberalization) attached to IMF loans', 'IMF loans typically require austerity measures and economic reforms — controversial because these conditions can worsen inequality and social services.', 3),
    mc('What is development economics concerned with?', ['How developed countries maintain their advantage', 'Understanding why some countries are poor and what policies promote sustainable economic growth and poverty reduction', 'International trade theory only', 'How to measure GDP in developing countries'], 'Understanding why some countries are poor and what policies promote sustainable economic growth and poverty reduction', 'Development economics studies poverty traps, institutions, human capital, and the policies that help countries industrialize and grow sustainably.', 4),
    mc('What is the "Washington Consensus"?', ['A US policy for managing foreign aid', 'A set of free-market policy prescriptions (privatization, deregulation, fiscal austerity) promoted by the IMF and World Bank in the 1980s-90s', 'A global agreement on exchange rates', 'A trade agreement between North American countries'], 'A set of free-market policy prescriptions (privatization, deregulation, fiscal austerity) promoted by the IMF and World Bank in the 1980s-90s', 'The Washington Consensus pushed market liberalization on developing countries. Mixed results — criticized for ignoring institutions, inequality, and sequencing of reforms.', 5),
  ],
  'economic-development': [
    mc('What is economic development?', ['Simply growing GDP per capita', 'A broad improvement in living standards, health, education, and capabilities — not just income growth', 'Industrialization and manufacturing growth', 'Foreign investment in a country'], 'A broad improvement in living standards, health, education, and capabilities — not just income growth', 'Amartya Sen\'s "capabilities approach": development is expanding what people can do and be — not just raising income but improving health, education, and freedom.', 1),
    mc('What is the Human Development Index (HDI)?', ['A measure of a country\'s military power', 'A composite index of life expectancy, education, and income per capita', 'The World Bank\'s poverty headcount measure', 'An index of economic freedom and market openness'], 'A composite index of life expectancy, education, and income per capita', 'The UN\'s HDI goes beyond GDP to measure health (life expectancy), education (schooling years), and living standards (income) — giving a fuller picture of development.', 2),
    mc('What is the "poverty trap"?', ['A law that prevents the poor from accumulating wealth', 'A self-reinforcing cycle where poverty prevents investment in human and physical capital needed to escape poverty', 'Taxes that are higher for poor people', 'A region with permanent poverty due to geography'], 'A self-reinforcing cycle where poverty prevents investment in human and physical capital needed to escape poverty', 'Too poor to save → can\'t invest in education/health/capital → remain poor. Breaking the trap often requires external investment or public provision of essentials.', 3),
    mc('What role do institutions play in economic development?', ['Institutions don\'t affect economic outcomes significantly', 'Strong property rights, rule of law, and accountable government are among the strongest predictors of long-run development', 'Only natural resources determine development outcomes', 'Geographic factors dominate institutional factors'], 'Strong property rights, rule of law, and accountable government are among the strongest predictors of long-run development', 'Acemoglu and Robinson\'s "Why Nations Fail": inclusive institutions that protect property and allow broad participation drive prosperity; extractive institutions don\'t.', 4),
    mc('Income inequality across countries has:', ['Increased dramatically since 1980 for all measures', 'Decreased on average as poorer countries grew faster — though within-country inequality often rose', 'Stayed exactly the same', 'Been eliminated by globalization'], 'Decreased on average as poorer countries grew faster — though within-country inequality often rose', 'China, India, and other developing nations have grown rapidly, reducing global between-country inequality. But within many countries, the gains went mostly to the top.', 5),
  ],
  'globalization-tradeoffs': [
    mc('What is globalization?', ['The process of countries becoming more isolated', 'The increasing integration of economies through trade, investment, migration, and information flows', 'The spread of American culture worldwide', 'The growth of multinational corporations'], 'The increasing integration of economies through trade, investment, migration, and information flows', 'Globalization connects national economies through trade, capital flows, supply chains, immigration, and technology — creating interdependence.', 1),
    mc('Which is a major benefit of globalization?', ['Reduced income inequality within all countries', 'Lower prices for consumers, faster innovation spread, and lifting billions out of poverty in developing nations', 'More stable commodity prices', 'Reduced power of multinational corporations'], 'Lower prices for consumers, faster innovation spread, and lifting billions out of poverty in developing nations', 'Global trade and investment helped countries like China, India, South Korea, and others achieve dramatic poverty reduction through export-led growth.', 2),
    mc('Which is a well-documented downside of globalization for workers in wealthy nations?', ['Workers gain bargaining power as firms compete for labor', 'Manufacturing job losses as production moves to lower-wage countries, creating localized economic devastation', 'Wages rise for all workers as productivity improves', 'Technology reduces the need to offshore jobs'], 'Manufacturing job losses as production moves to lower-wage countries, creating localized economic devastation', 'The "China Shock" research showed significant, concentrated job losses in US manufacturing regions as imports rose — with lasting negative effects on affected communities.', 3),
    mc('What is a global supply chain?', ['A single country\'s entire production process', 'The network of international production where components are made in different countries and assembled elsewhere', 'A cartel controlling global commodity prices', 'International shipping routes'], 'The network of international production where components are made in different countries and assembled elsewhere', 'A smartphone contains components from dozens of countries — designed in the US, chips from Taiwan, assembled in China. This is the modern global supply chain.', 4),
    mc('What did the COVID-19 pandemic reveal about global supply chains?', ['Supply chains were too short and needed to be longer', 'Long, specialized supply chains create fragility — single disruptions can cascade into global shortages', 'Global supply chains are entirely resilient', 'Reshoring production always reduces costs'], 'Long, specialized supply chains create fragility — single disruptions can cascade into global shortages', 'Semiconductor shortages, PPE crises, and container shipping backlogs revealed how concentrated global supply chains create systemic fragility.', 5),
  ],
  'rationality-and-its-limits': [
    mc('What does standard economics assume about people?', ['People are irrational and need government guidance', 'People are rational actors who maximize utility based on stable, consistent preferences', 'People make decisions based primarily on emotions', 'People copy each other\'s behavior without thinking'], 'People are rational actors who maximize utility based on stable, consistent preferences', 'The "homo economicus" model assumes people process information perfectly, have consistent preferences, and always choose to maximize their well-being.', 1),
    mc('What does behavioral economics add to this picture?', ['People are always irrational', 'Systematic, predictable ways in which real human decisions deviate from the rational actor model', 'Markets are always efficient despite human irrationality', 'Governments should control all economic decisions'], 'Systematic, predictable ways in which real human decisions deviate from the rational actor model', 'Behavioral economics (Kahneman, Thaler) documents predictable patterns of "irrational" behavior — heuristics, biases, inconsistencies — with real economic consequences.', 2),
    mc('What is bounded rationality?', ['The idea that humans have no rationality at all', 'The recognition that human rationality is limited by cognitive capacity, time, and available information', 'The maximum level of rationality humans can achieve with training', 'A mathematical bound on rational decision-making'], 'The recognition that human rationality is limited by cognitive capacity, time, and available information', 'Herbert Simon coined bounded rationality: people try to be rational but are limited by their cognitive resources. They "satisfice" (find good enough) rather than optimize.', 3),
    mc('What is present bias?', ['Preferring things that happen now over the same thing in the future, even when it\'s self-defeating', 'Bias toward current news over historical events', 'Preference for present location over distant locations', 'Overweighting recent information in predictions'], 'Preferring things that happen now over the same thing in the future, even when it\'s self-defeating', 'Present bias explains procrastination, undersaving, and overeating — the immediate reward dominates even when we know the long-run cost exceeds the benefit.', 4),
    mc('How does behavioral economics challenge traditional welfare economics?', ['People can\'t be trusted to make any decisions for themselves', 'If people systematically make choices that don\'t serve their own long-run interests, standard welfare analysis (which assumes preference satisfaction = welfare) breaks down', 'Behavioral economics confirms that markets always maximize welfare', 'Only irrational people need government help'], 'If people systematically make choices that don\'t serve their own long-run interests, standard welfare analysis (which assumes preference satisfaction = welfare) breaks down', 'If choice ≠ welfare (due to bias), then policy that serves stated preferences might not maximize well-being — opening space for paternalistic interventions like nudges.', 5),
  ],
  'nudges': [
    mc('What is a nudge in behavioral economics?', ['A government mandate requiring specific behavior', 'A subtle design choice in the decision environment that steers people toward better choices without restricting options', 'A tax or subsidy that changes behavior', 'An educational campaign about good decisions'], 'A subtle design choice in the decision environment that steers people toward better choices without restricting options', 'Nudges (Thaler & Sunstein) exploit behavioral tendencies to promote better choices — without banning anything or changing financial incentives.', 1),
    mc('Which is an example of a successful nudge?', ['Banning sugary drinks in schools', 'Making retirement savings opt-out (default enrolled) instead of opt-in — dramatically increasing participation', 'Taxing cigarettes to reduce smoking', 'Requiring healthy food in cafeterias'], 'Making retirement savings opt-out (default enrolled) instead of opt-in — dramatically increasing participation', 'Default enrollment exploits status quo bias — people tend to stick with defaults. Opt-out 401(k) enrollment dramatically raised savings rates with no compulsion.', 2),
    mc('What is "libertarian paternalism"?', ['The government banning unhealthy choices', 'Preserving freedom of choice while using choice architecture to steer people toward better outcomes', 'Taxing harmful behaviors', 'Mandating government-approved choices'], 'Preserving freedom of choice while using choice architecture to steer people toward better outcomes', 'Thaler and Sunstein\'s framework: keep options open, but design the choice environment to make good choices easier — "nudging" without coercion.', 3),
    mc('What is a default bias, and why does it matter for nudges?', ['People prefer default settings in electronics', 'People tend to stick with whatever option is presented as the default — making defaults a powerful policy lever', 'People avoid all choices that require action', 'Defaults only matter for technology products'], 'People tend to stick with whatever option is presented as the default — making defaults a powerful policy lever', 'Default bias (status quo bias) means changing the default changes behavior dramatically — without changing choices or incentives. Organ donation opt-out systems double donation rates.', 4),
    mc('What is a criticism of nudge policy?', ['Nudges have never been shown to work', 'Nudging manipulates people without their awareness, raises questions about who decides what\'s "better," and may not work in high-stakes decisions', 'Nudges always require government mandates', 'Nudge effects are always permanent'], 'Nudging manipulates people without their awareness, raises questions about who decides what\'s "better," and may not work in high-stakes decisions', 'Critics: who decides the "right" choice? Nudges can be used to serve corporate or government interests. And they may fail for complex, high-stakes decisions where deliberation matters.', 5),
  ],
}
