import type { ExerciseDef } from '../types'

function mc(
  question: string,
  options: string[],
  correctAnswer: string,
  explanation: string,
  order: number
): ExerciseDef {
  return { question, type: 'MULTIPLE_CHOICE', options, correctAnswer, explanation, order }
}

export const businessEconExercises: Record<string, ExerciseDef[]> = {
  'types-of-costs': [
    mc('What is a fixed cost?', ['A cost that changes with output', 'A cost that remains the same regardless of how much is produced', 'A one-time startup cost', 'A cost set by the government'], 'A cost that remains the same regardless of how much is produced', 'Fixed costs (rent, insurance, salaries of permanent staff) don\'t change with output level — you pay them whether you produce 0 or 1,000 units.', 1),
    mc('What is a variable cost?', ['A cost that\'s hard to predict', 'A cost that changes directly with output level', 'A cost shared between multiple firms', 'A cost that only occurs occasionally'], 'A cost that changes directly with output level', 'Variable costs (materials, hourly labor, utilities tied to production) rise as output rises and fall as output falls.', 2),
    mc('Economic profit differs from accounting profit because it:', ['Is always higher', 'Subtracts implicit costs (opportunity costs) in addition to explicit costs', 'Ignores tax payments', 'Counts only fixed costs'], 'Subtracts implicit costs (opportunity costs) in addition to explicit costs', 'Accounting profit = revenue − explicit costs. Economic profit = revenue − explicit costs − implicit costs (like the owner\'s forgone salary).', 3),
    mc('What is marginal cost?', ['The average cost per unit produced', 'The cost of producing one additional unit', 'The difference between fixed and variable costs', 'The minimum cost to enter the market'], 'The cost of producing one additional unit', 'Marginal cost = change in total cost / change in quantity. Firms compare marginal cost to marginal revenue to maximize profit.', 4),
    mc('A firm should produce more output as long as:', ['Revenue exceeds fixed costs', 'Marginal revenue exceeds marginal cost', 'Average cost is falling', 'Profit is positive'], 'Marginal revenue exceeds marginal cost', 'The profit-maximizing rule: produce where MR = MC. Producing where MR > MC adds to profit; where MR < MC, additional output reduces profit.', 5),
  ],
  'economies-of-scale': [
    mc('What are economies of scale?', ['The disadvantages large firms face', 'Cost advantages gained as output increases — average costs fall with scale', 'Taxes that increase with firm size', 'Government subsidies for large producers'], 'Cost advantages gained as output increases — average costs fall with scale', 'As firms grow, they can spread fixed costs, negotiate better input prices, specialize labor, and use larger/more efficient equipment.', 1),
    mc('What causes economies of scale?', ['Higher wages for larger firms', 'Spreading fixed costs, specialization, bulk purchasing, and more efficient technology at scale', 'Charging higher prices to more customers', 'Government regulation that favors large firms'], 'Spreading fixed costs, specialization, bulk purchasing, and more efficient technology at scale', 'Scale allows fixed costs to be divided among more units, workers to specialize, inputs to be purchased in bulk, and better capital to be deployed.', 2),
    mc('What are diseconomies of scale?', ['Benefits that shrink as a firm grows', 'When average costs rise as output increases beyond an optimal size', 'Taxes imposed at large output levels', 'When fixed costs become variable'], 'When average costs rise as output increases beyond an optimal size', 'Beyond the optimal scale, firms become harder to manage — coordination problems, bureaucracy, and inefficiency drive average costs up.', 3),
    mc('What is the minimum efficient scale (MES)?', ['The minimum output required to avoid losses', 'The smallest output level at which long-run average cost is minimized', 'The scale below which a firm must exit the market', 'The output level where marginal cost equals zero'], 'The smallest output level at which long-run average cost is minimized', 'MES is where the long-run average cost curve bottoms out — the efficient production scale. Industries with high MES tend toward fewer, larger firms.', 4),
    mc('A natural monopoly arises when:', ['One firm has a patent on a product', 'Economies of scale are so strong that one firm can serve the market more cheaply than multiple firms', 'The government grants exclusive rights to one firm', 'The product can only be produced by one process'], 'Economies of scale are so strong that one firm can serve the market more cheaply than multiple firms', 'Utilities (water, electricity) have huge fixed costs and falling average costs — competition is inefficient, so one regulated firm is often preferable.', 5),
  ],
  'production-decisions': [
    mc('In the short run, a firm should continue operating if:', ['Its total revenue covers total costs including fixed costs', 'Its total revenue covers its variable costs (price ≥ average variable cost)', 'It is making an accounting profit', 'Its fixed costs are low'], 'Its total revenue covers its variable costs (price ≥ average variable cost)', 'In the short run, fixed costs are sunk. As long as revenue covers variable costs, operating is better than shutting down (which still incurs fixed costs).', 1),
    mc('The law of diminishing marginal returns states:', ['Additional inputs always produce more output', 'Adding more of one input (with others fixed) eventually yields smaller increases in output', 'Output always decreases when inputs are added', 'Firms always produce less over time'], 'Adding more of one input (with others fixed) eventually yields smaller increases in output', 'As you add workers to a fixed factory, each additional worker adds less to output than the last — the marginal product of labor falls.', 2),
    mc('What is the production function?', ['The equation showing a firm\'s profit at each output level', 'The relationship between inputs and the maximum output that can be produced', 'A graph of price vs quantity supplied', 'The firm\'s cost structure over time'], 'The relationship between inputs and the maximum output that can be produced', 'The production function describes how inputs (labor, capital, land) are transformed into outputs — it defines productive capacity.', 3),
    mc('What does the isoquant curve represent?', ['All price combinations that yield equal revenue', 'All input combinations that produce the same output level', 'The firm\'s total cost at each output level', 'Consumer indifference between products'], 'All input combinations that produce the same output level', 'An isoquant shows all combinations of inputs (e.g., labor and capital) that produce the same quantity of output — the production analog of an indifference curve.', 4),
    mc('A firm maximizes profit by choosing the output where:', ['Total revenue is maximized', 'Total cost is minimized', 'Marginal revenue equals marginal cost', 'Average cost equals price'], 'Marginal revenue equals marginal cost', 'MR = MC is the universal profit-maximization condition. Below this: produce more. Above this: produce less. At equality: profit is maximized.', 5),
  ],
  'perfect-competition': [
    mc('What characterizes a perfectly competitive market?', ['One dominant firm sets prices', 'Many firms, identical products, free entry/exit, and price-taking behavior', 'A few large firms with differentiated products', 'Government controls prices'], 'Many firms, identical products, free entry/exit, and price-taking behavior', 'Perfect competition has many small firms selling identical goods — no single firm can influence price. Each firm is a price taker.', 1),
    mc('In long-run equilibrium in perfect competition, firms earn:', ['Economic superprofits', 'Zero economic profit (normal profit)', 'Negative profit', 'The highest possible accounting profit'], 'Zero economic profit (normal profit)', 'Profits attract entry; losses cause exit. In the long run, competition drives economic profit to zero — firms earn just enough to stay in business.', 2),
    mc('Why is perfect competition considered economically efficient?', ['It produces the maximum output regardless of cost', 'Price equals marginal cost, so goods are produced at minimum cost and valued at their true social cost', 'All firms are equally profitable', 'It prevents all market failures'], 'Price equals marginal cost, so goods are produced at minimum cost and valued at their true social cost', 'P = MC means consumers pay exactly the social cost of the last unit produced — allocatively efficient. Long-run P = min AC is productively efficient.', 3),
    mc('How does a competitive firm respond to a price above its average total cost?', ['It reduces output to avoid oversupply', 'It earns economic profit, which attracts new entrants who eventually drive price back down', 'It raises its own price further', 'It lobbies the government for protection'], 'It earns economic profit, which attracts new entrants who eventually drive price back down', 'Above-normal profits are the signal that draws new firms in — increasing supply until price falls back to the break-even level.', 4),
    mc('The supply curve for a perfectly competitive firm is its:', ['Average total cost curve', 'Marginal cost curve above average variable cost', 'Average variable cost curve', 'Total cost curve'], 'Marginal cost curve above average variable cost', 'A competitive firm supplies the quantity where P = MC. It only produces if P ≥ AVC. The MC curve above the AVC minimum IS the supply curve.', 5),
  ],
  'monopoly': [
    mc('A monopoly exists when:', ['One firm controls a large share of the market', 'There is only one seller with no close substitutes and significant barriers to entry', 'Two firms dominate the market', 'The government owns the industry'], 'There is only one seller with no close substitutes and significant barriers to entry', 'A pure monopoly is the sole seller of a product with no close substitutes — barriers to entry prevent competition from eroding its position.', 1),
    mc('How does a monopolist set its price?', ['It takes the market price like a competitive firm', 'It chooses the price that maximizes profit, setting MR = MC and pricing above marginal cost', 'It sets price equal to marginal cost', 'It sets price equal to average cost'], 'It chooses the price that maximizes profit, setting MR = MC and pricing above marginal cost', 'A monopolist faces the whole market demand curve, so it can set price. It maximizes profit at MR = MC, then reads price off the demand curve — always above MC.', 2),
    mc('What is deadweight loss from monopoly?', ['The monopolist\'s profit', 'The value of mutually beneficial trades that don\'t occur because price exceeds marginal cost', 'The loss in monopolist profit from regulation', 'The cost of barriers to entry'], 'The value of mutually beneficial trades that don\'t occur because price exceeds marginal cost', 'Monopoly underproduces relative to the competitive level. Consumers who would have bought at the competitive price don\'t buy at the monopoly price — that\'s deadweight loss.', 3),
    mc('What is price discrimination in a monopoly?', ['Charging higher prices to competitors\' customers', 'Charging different prices to different consumers for the same good based on willingness to pay', 'Raising prices over time', 'Setting different prices in different stores'], 'Charging different prices to different consumers for the same good based on willingness to pay', 'A price-discriminating monopolist extracts more consumer surplus — airlines, movie theaters, and software companies all practice forms of price discrimination.', 4),
    mc('Which is a common source of monopoly power?', ['Having the best marketing', 'Government-granted patents, exclusive licenses, or control of a key resource', 'Making a high-quality product', 'Being located in a small town'], 'Government-granted patents, exclusive licenses, or control of a key resource', 'Monopolies arise from: patents (pharmaceutical), natural resource control (De Beers diamonds), network effects, or government license (utilities).', 5),
  ],
  'oligopoly-and-monopolistic': [
    mc('What defines an oligopoly?', ['One firm controls the market', 'A few large firms dominate, with high barriers to entry and strategic interdependence', 'Many firms with differentiated products', 'A market with no barriers to entry'], 'A few large firms dominate, with high barriers to entry and strategic interdependence', 'Oligopolies (auto, airlines, oil) have a small number of large firms — each firm\'s decisions significantly affect the others.', 1),
    mc('What is strategic interdependence in an oligopoly?', ['Firms cooperate to set prices together', 'Each firm considers how rivals will react when making decisions', 'Firms copy each other\'s products exactly', 'Firms share production facilities'], 'Each firm considers how rivals will react when making decisions', 'In an oligopoly, cutting your price will provoke a response from competitors. This interdependence is why game theory (like the Prisoner\'s Dilemma) applies.', 2),
    mc('What is monopolistic competition?', ['A market with one dominant firm and many weak competitors', 'Many firms selling differentiated products with low barriers to entry', 'A market regulated by the government to prevent monopoly', 'A market with two or three dominant firms'], 'Many firms selling differentiated products with low barriers to entry', 'Monopolistic competition (restaurants, clothing) has many firms like perfect competition, but each firm\'s product is somewhat different — giving each slight pricing power.', 3),
    mc('In monopolistic competition, firms advertise heavily because:', ['Advertising is required by law', 'Product differentiation is key — advertising creates perceived differences that justify price premiums', 'Advertising reduces costs', 'Competitors pay for shared advertising'], 'Product differentiation is key — advertising creates perceived differences that justify price premiums', 'Differentiation is the source of monopolistic competitors\' limited pricing power. Advertising builds brand loyalty and perceived uniqueness.', 4),
    mc('What is the Prisoner\'s Dilemma and how does it apply to oligopolies?', ['A game where both players always cooperate', 'A game showing why individually rational choices (defecting/competing) lead to worse outcomes than cooperation, even when cooperation would benefit both', 'A model where firms always collude to set prices', 'A theory that predicts firms always compete on price'], 'A game showing why individually rational choices (defecting/competing) lead to worse outcomes than cooperation, even when cooperation would benefit both', 'Oligopolists could earn more by colluding, but each has incentive to defect. The Nash equilibrium (both compete) is worse than cooperation — just like the Prisoner\'s Dilemma.', 5),
  ],
  'antitrust': [
    mc('What is the purpose of antitrust law?', ['To protect large firms from competition', 'To prevent monopolies, cartels, and anti-competitive practices that harm consumers', 'To regulate government-owned industries', 'To set minimum wages for all workers'], 'To prevent monopolies, cartels, and anti-competitive practices that harm consumers', 'Antitrust law (Sherman Act, Clayton Act in the US) aims to maintain competitive markets by preventing mergers, price-fixing, and other market abuses.', 1),
    mc('What is a cartel?', ['A group of firms that legally sets industry standards', 'A group of firms that collude to fix prices, restrict output, or divide markets', 'A government agency that regulates monopolies', 'A trade union for businesses'], 'A group of firms that collude to fix prices, restrict output, or divide markets', 'Cartels (like OPEC) behave like a collective monopoly — restricting supply to raise prices. Price-fixing cartels are illegal in most countries.', 2),
    mc('What does the FTC (Federal Trade Commission) do?', ['Set interest rates for businesses', 'Enforce antitrust law and protect consumers from anti-competitive business practices', 'Collect corporate taxes', 'Regulate international trade'], 'Enforce antitrust law and protect consumers from anti-competitive business practices', 'The FTC investigates mergers, price-fixing, deceptive advertising, and other practices that harm competition or consumers.', 3),
    mc('When is a merger likely to be challenged by antitrust regulators?', ['When it involves companies in different industries', 'When it would significantly increase market concentration and reduce competition', 'When the merged company would be profitable', 'When both companies are publicly traded'], 'When it would significantly increase market concentration and reduce competition', 'Regulators use concentration measures (Herfindahl-Hirschman Index) to assess whether a merger would create market power harmful to consumers.', 4),
    mc('What is a natural monopoly, and how is it typically handled?', ['A monopoly that arises naturally without any barriers — it should be broken up', 'A monopoly where one firm can serve the market at lower cost than multiple firms — usually regulated rather than broken up', 'A monopoly created by nature\'s scarcity of a resource', 'A monopoly that regulators allow to charge any price'], 'A monopoly where one firm can serve the market at lower cost than multiple firms — usually regulated rather than broken up', 'Natural monopolies (utilities, railroads) are left intact but regulated — price caps, rate-of-return regulation — to prevent exploitation.', 5),
  ],
}
