import type { ExerciseDef } from '../types'

function mc(
  question: string,
  options: string[],
  correctAnswer: string,
  explanation: string,
  order: number
): ExerciseDef {
  return { question, type: 'MULTIPLE_CHOICE', options, correctAnswer, explanation, order }
}

export const macroExercises: Record<string, ExerciseDef[]> = {
  'gdp': [
    mc('What does GDP measure?', ['The government\'s annual budget', 'The total market value of all final goods and services produced in a country in a given period', 'Total income of all citizens including those abroad', 'The value of all transactions including intermediate goods'], 'The total market value of all final goods and services produced in a country in a given period', 'GDP (Gross Domestic Product) is the broadest measure of economic output — it counts final goods and services to avoid double-counting intermediate goods.', 1),
    mc('What does GDP NOT capture well?', ['Total economic output', 'Government spending and exports', 'Income inequality, well-being, environmental degradation, and non-market activity', 'Business investment'], 'Income inequality, well-being, environmental degradation, and non-market activity', 'GDP measures size, not quality of life. A country can have high GDP with extreme inequality, pollution, and poor health outcomes — GDP misses all of this.', 2),
    mc('What is real GDP vs nominal GDP?', ['Real GDP includes government transfers; nominal does not', 'Real GDP adjusts for inflation, making comparisons over time meaningful; nominal does not', 'Nominal GDP is always higher than real GDP', 'Real GDP counts only manufacturing; nominal counts all sectors'], 'Real GDP adjusts for inflation, making comparisons over time meaningful; nominal does not', 'Nominal GDP uses current prices. Real GDP adjusts for price changes, so you can compare actual output growth across years.', 3),
    mc('GDP can be measured three ways. Which of the following is NOT one of them?', ['Expenditure approach (C + I + G + NX)', 'Income approach (wages + profits + rents + interest)', 'Productivity approach (output per worker)', 'Production approach (value added at each stage)'], 'Productivity approach (output per worker)', 'GDP = expenditure (spending on final goods) = income (all earnings from production) = value added. Productivity is a separate concept.', 4),
    mc('If GDP grows 5% but population grows 3%, what happened to GDP per capita?', ['It grew 8%', 'It grew roughly 2%', 'It fell by 2%', 'It stayed the same'], 'It grew roughly 2%', 'GDP per capita ≈ GDP growth − population growth = 5% − 3% = 2%. Per capita GDP measures living standards better than total GDP.', 5),
  ],
  'unemployment': [
    mc('How is the official unemployment rate calculated?', ['People without jobs divided by the total population', 'People actively seeking work but not employed, divided by the labor force', 'All people not working divided by working-age adults', 'The number of job openings divided by job seekers'], 'People actively seeking work but not employed, divided by the labor force', 'Unemployment rate = unemployed / labor force. The labor force is employed + actively seeking work. Discouraged workers who\'ve stopped looking aren\'t counted.', 1),
    mc('What is frictional unemployment?', ['Unemployment caused by economic downturns', 'Short-term unemployment as people transition between jobs or enter the labor market', 'Unemployment caused by structural changes in the economy', 'Permanent unemployment in depressed regions'], 'Short-term unemployment as people transition between jobs or enter the labor market', 'Frictional unemployment is normal — it takes time to match workers with jobs. Some frictional unemployment is inevitable and even healthy.', 2),
    mc('What is structural unemployment?', ['Unemployment during recessions', 'Unemployment caused by a mismatch between workers\' skills and the skills employers need', 'Workers between seasonal jobs', 'People voluntarily leaving jobs'], 'Unemployment caused by a mismatch between workers\' skills and the skills employers need', 'Structural unemployment is long-term — industries shrink, technology displaces workers, and retraining is needed. It\'s harder to solve than frictional unemployment.', 3),
    mc('What is the "natural rate of unemployment"?', ['Zero unemployment — the goal of economic policy', 'The unemployment rate that exists in a healthy economy (frictional + structural), with no cyclical unemployment', 'The rate set by the Federal Reserve', 'The unemployment rate that never changes'], 'The unemployment rate that exists in a healthy economy (frictional + structural), with no cyclical unemployment', 'The natural rate (NAIRU) is typically 4-5% in the US — the level consistent with stable inflation and a healthy labor market.', 4),
    mc('Why does official unemployment undercount the true joblessness problem?', ['It counts part-time workers as unemployed', 'It excludes discouraged workers and those involuntarily working part-time', 'It only counts workers in manufacturing', 'The government manipulates the data'], 'It excludes discouraged workers and those involuntarily working part-time', 'The broader U-6 measure includes discouraged workers (who gave up) and underemployed (part-time who want full-time work) — always higher than the official rate.', 5),
  ],
  'inflation': [
    mc('What is inflation?', ['A rise in one product\'s price', 'A sustained increase in the general price level across the economy', 'Printing more money', 'A rise in government spending'], 'A sustained increase in the general price level across the economy', 'Inflation is measured by price indices (CPI, PCE) tracking a basket of goods over time. Prices rise in general, eroding purchasing power.', 1),
    mc('What causes demand-pull inflation?', ['Supply chain disruptions', 'Too much money chasing too few goods — aggregate demand exceeds aggregate supply', 'Rising input costs like oil prices', 'Government budget cuts'], 'Too much money chasing too few goods — aggregate demand exceeds aggregate supply', 'Demand-pull: the economy is running "too hot" — high employment, strong spending, and insufficient supply to meet demand pushes prices up.', 2),
    mc('What causes cost-push inflation?', ['Excessive consumer spending', 'Rising production costs (oil, wages, materials) that push prices up from the supply side', 'Government printing too much money', 'High interest rates'], 'Rising production costs (oil, wages, materials) that push prices up from the supply side', 'Cost-push inflation: supply shocks (oil embargo, supply chain breakdown) raise production costs, which firms pass on as higher prices.', 3),
    mc('What is the Consumer Price Index (CPI)?', ['The index of stock prices for consumer goods companies', 'A measure of the average price change of a fixed basket of goods and services bought by typical households', 'The price level set by the government', 'A measure of industrial production costs'], 'A measure of the average price change of a fixed basket of goods and services bought by typical households', 'CPI tracks prices of a representative basket — food, housing, transportation, healthcare — comparing them to a base year to measure inflation.', 4),
    mc('Hyperinflation refers to:', ['Inflation above 5% annually', 'Extremely rapid price increases (often 50%+ per month) causing a currency to lose most of its value rapidly', 'Inflation in only one sector of the economy', 'Inflation caused by government policy'], 'Extremely rapid price increases (often 50%+ per month) causing a currency to lose most of its value rapidly', 'Hyperinflation (Zimbabwe 2008, Weimar Germany 1923) destroys savings and economic stability — usually caused by excessive money printing.', 5),
  ],
  'business-cycles': [
    mc('What is a business cycle?', ['The process of starting and closing a business', 'The recurring pattern of economic expansion and contraction in GDP', 'The annual cycle of business profits and losses', 'The lifecycle of a product from launch to obsolescence'], 'The recurring pattern of economic expansion and contraction in GDP', 'Business cycles are fluctuations in economic activity — expansion (growth), peak, recession (contraction), trough, then recovery — repeating over time.', 1),
    mc('How is a recession formally defined?', ['Any slowdown in economic growth', 'Two consecutive quarters of negative real GDP growth', 'Unemployment above 10%', 'A stock market decline of more than 20%'], 'Two consecutive quarters of negative real GDP growth', 'The conventional definition is two consecutive quarters of negative real GDP growth. The NBER uses broader criteria including employment and income data.', 2),
    mc('What is a depression?', ['A severe recession lasting many years with widespread unemployment and economic hardship', 'A mild economic slowdown', 'A recession in only one region', 'Any recession with unemployment above 5%'], 'A severe recession lasting many years with widespread unemployment and economic hardship', 'A depression is a prolonged, severe recession. The Great Depression (1929-1939) saw 25% unemployment and GDP falling ~30%.', 3),
    mc('What happens to employment and output during an expansion?', ['Both fall', 'Both rise — more workers are employed and more goods are produced', 'Employment rises but output falls', 'Output rises but employment falls'], 'Both rise — more workers are employed and more goods are produced', 'During expansion, firms hire more workers, produce more output, and profits rise. Consumer confidence and spending also increase.', 4),
    mc('What is a leading economic indicator?', ['A statistic that follows the economy (like unemployment rate)', 'A statistic that tends to change before the economy changes, used to predict turning points', 'A measure of past economic performance', 'An indicator that moves with GDP simultaneously'], 'A statistic that tends to change before the economy changes, used to predict turning points', 'Leading indicators (stock prices, building permits, new orders) shift before the broader economy — useful for forecasting recessions or recoveries.', 5),
  ],
  'fiscal-policy': [
    mc('What is fiscal policy?', ['Central bank management of money supply and interest rates', 'Government use of spending and taxation to influence the economy', 'Exchange rate management', 'Regulation of financial institutions'], 'Government use of spending and taxation to influence the economy', 'Fiscal policy is Congress and the President\'s tool — spending more or cutting taxes to stimulate; spending less or raising taxes to cool the economy.', 1),
    mc('What is expansionary fiscal policy?', ['Raising taxes and cutting spending during a recession', 'Increasing government spending and/or cutting taxes to boost aggregate demand', 'The central bank lowering interest rates', 'Reducing the national debt'], 'Increasing government spending and/or cutting taxes to boost aggregate demand', 'Expansionary fiscal policy (stimulus) injects money into the economy during downturns — the 2009 ARRA and 2020 CARES Act are examples.', 2),
    mc('What is the fiscal multiplier?', ['The number of government programs funded by taxes', 'The ratio of change in GDP to the initial change in government spending', 'The tax rate applied to government contracts', 'The percentage of the budget funded by borrowing'], 'The ratio of change in GDP to the initial change in government spending', 'A multiplier > 1 means $1 of government spending generates more than $1 of GDP — because recipients spend their income, creating ripple effects.', 3),
    mc('What is automatic stabilization in fiscal policy?', ['The Federal Reserve automatically adjusting rates', 'Built-in policies that automatically stimulate during recessions and cool during booms (unemployment insurance, progressive taxes)', 'Government computers that adjust spending daily', 'Balanced budget requirements that automatically cut spending in recessions'], 'Built-in policies that automatically stimulate during recessions and cool during booms (unemployment insurance, progressive taxes)', 'Automatic stabilizers work without legislative action — unemployment benefits rise in recessions (stimulus) and tax receipts fall, cushioning the downturn.', 4),
    mc('What is a concern about fiscal policy lags?', ['Fiscal policy works too quickly', 'Recognition, legislative, and implementation lags mean stimulus may arrive after the recession is over', 'Fiscal policy can only be implemented once per year', 'Congress always passes fiscal policy immediately'], 'Recognition, legislative, and implementation lags mean stimulus may arrive after the recession is over', 'By the time a recession is recognized, debated in Congress, and infrastructure spending actually begins, the downturn may have reversed — making the stimulus pro-cyclical.', 5),
  ],
  'monetary-policy': [
    mc('Who conducts monetary policy in the United States?', ['Congress and the President', 'The Federal Reserve (the Fed)', 'The Treasury Department', 'The World Bank'], 'The Federal Reserve (the Fed)', 'The Fed is the US central bank, independent of political control. It manages money supply and interest rates to achieve its dual mandate: stable prices and maximum employment.', 1),
    mc('When the Fed raises interest rates, what is the expected effect?', ['More borrowing, higher investment, more spending', 'Less borrowing, less spending, reduced inflation', 'More inflation and faster GDP growth', 'Higher unemployment in the long run but no short-run effect'], 'Less borrowing, less spending, reduced inflation', 'Higher rates make borrowing costlier — mortgages, car loans, business investment decline. Reduced spending slows the economy and eases inflation.', 2),
    mc('What is quantitative easing (QE)?', ['The Fed printing money to fund the government directly', 'The Fed buying assets (bonds) to increase money supply and lower long-term rates when short-term rates can\'t go lower', 'Increasing bank reserve requirements', 'Government stimulus spending funded by borrowing'], 'The Fed buying assets (bonds) to increase money supply and lower long-term rates when short-term rates can\'t go lower', 'QE is used when interest rates hit zero (zero lower bound). The Fed buys government and mortgage bonds, pumping money into the economy and lowering long-term rates.', 3),
    mc('The Federal Reserve\'s dual mandate is:', ['Minimize inflation and maximize the stock market', 'Achieve maximum employment and stable prices (2% inflation target)', 'Fund the federal government and regulate banks', 'Set exchange rates and manage the national debt'], 'Achieve maximum employment and stable prices (2% inflation target)', 'Congress gave the Fed two goals: full employment and stable prices (targeting ~2% inflation). These sometimes conflict — hence the Fed\'s constant balancing act.', 4),
    mc('What is the federal funds rate?', ['The rate the government charges citizens for loans', 'The interest rate at which banks lend reserves to each other overnight — the Fed\'s primary policy tool', 'The rate on 10-year Treasury bonds', 'The rate on consumer mortgages'], 'The interest rate at which banks lend reserves to each other overnight — the Fed\'s primary policy tool', 'The Fed targets the federal funds rate to influence all other interest rates. Raising it tightens credit conditions throughout the economy.', 5),
  ],
  'national-debt': [
    mc('What is the national debt?', ['The annual deficit', 'The total accumulated borrowing by the federal government outstanding at a given time', 'Money owed by US citizens to foreign governments', 'The sum of all state debts'], 'The total accumulated borrowing by the federal government outstanding at a given time', 'The national debt is the cumulative total of all past annual deficits (and any surpluses). The US national debt exceeds $30 trillion.', 1),
    mc('What is the difference between the deficit and the national debt?', ['They are the same thing', 'The deficit is the annual shortfall (spending exceeds revenue); the debt is the accumulated total of all past deficits', 'The debt is annual; the deficit is the total owed', 'The deficit includes state debts; the national debt does not'], 'The deficit is the annual shortfall (spending exceeds revenue); the debt is the accumulated total of all past deficits', 'The deficit is the annual gap (spending − revenue). Each year\'s deficit adds to the national debt. A surplus would reduce it.', 2),
    mc('Who owns most of the US national debt?', ['Foreign countries like China', 'US government agencies (Social Security Trust Fund, Fed) and domestic investors — not primarily foreign countries', 'The Federal Reserve exclusively', 'Wealthy American individuals'], 'US government agencies (Social Security Trust Fund, Fed) and domestic investors — not primarily foreign countries', 'About 40% is held by US government accounts and the Fed. Most of the rest is domestic — pension funds, mutual funds. China holds ~3-4%.', 3),
    mc('Why might government debt be less harmful than private debt during a recession?', ['Government debt never needs to be repaid', 'Governments can grow GDP to service debt, borrow long-term in their own currency, and fiscal stimulus may generate more growth than the debt costs', 'Government interest rates are zero', 'Deficits automatically reduce over time'], 'Governments can grow GDP to service debt, borrow long-term in their own currency, and fiscal stimulus may generate more growth than the debt costs', 'The relevant metric is debt/GDP ratio. If borrowing funds productive investment that grows GDP faster than debt grows, the ratio stays manageable.', 4),
    mc('What is "crowding out" in the context of government debt?', ['Government spending replacing private spending one-for-one with no net effect', 'Government borrowing competing for limited capital, driving up interest rates and reducing private investment', 'Foreign countries reducing investment in the US', 'The government buying out private firms'], 'Government borrowing competing for limited capital, driving up interest rates and reducing private investment', 'When government borrows heavily, it competes with private borrowers — potentially raising interest rates and reducing business investment (crowding it out).', 5),
  ],
  'economic-schools': [
    mc('What is the core belief of Keynesian economics?', ['Markets always self-correct quickly', 'Government intervention through fiscal policy can stabilize the economy, especially during recessions', 'Tax cuts always pay for themselves through growth', 'The money supply should grow at a fixed rate'], 'Government intervention through fiscal policy can stabilize the economy, especially during recessions', 'Keynes argued that demand deficiency causes recessions and government spending can fill the gap — born from the Great Depression experience.', 1),
    mc('What does supply-side economics emphasize?', ['Increasing government spending to boost demand', 'Cutting taxes on producers and investors to stimulate supply, growth, and investment', 'Regulating markets to prevent monopoly', 'Maintaining high interest rates to control inflation'], 'Cutting taxes on producers and investors to stimulate supply, growth, and investment', 'Supply-siders ("Reaganomics") argue lower taxes on businesses and high earners generate investment, jobs, and growth that benefits everyone ("trickle-down").', 2),
    mc('What is the "crowding out" argument used by critics of Keynesian stimulus?', ['Government spending is inefficient by nature', 'Government borrowing raises interest rates, reducing private investment and negating stimulus effects', 'Government spending causes inflation immediately', 'Workers prefer government jobs to private jobs'], 'Government borrowing raises interest rates, reducing private investment and negating stimulus effects', 'If government borrowing "crowds out" equivalent private investment, the net effect on the economy may be zero or negative.', 3),
    mc('What is monetarism?', ['The view that only monetary policy matters and fiscal policy is ineffective', 'The view that the money supply is the primary driver of economic output and inflation, and should grow at a stable rate', 'The belief that markets need government direction', 'A theory that interest rates should never change'], 'The view that the money supply is the primary driver of economic output and inflation, and should grow at a stable rate', 'Milton Friedman\'s monetarism: control the money supply, not interest rates. Steady money growth prevents both inflation and recession.', 4),
    mc('What do most economists today believe about macro policy?', ['Either Keynesian or supply-side is completely right', 'A synthesis: both demand management and supply-side factors matter; the right mix depends on the situation', 'Neither fiscal nor monetary policy works', 'Only monetary policy is effective; fiscal policy never works'], 'A synthesis: both demand management and supply-side factors matter; the right mix depends on the situation', 'Modern macroeconomics is eclectic — fiscal policy matters in deep recessions, monetary policy for normal stabilization, and supply-side factors drive long-run growth.', 5),
  ],
}
