import type { AssessmentDef, AssessmentQuestionDef } from '../types'

const mc = (q: string, opts: string[], ans: string, exp: string, pts: number, ord: number): AssessmentQuestionDef =>
  ({ question: q, type: 'MULTIPLE_CHOICE', options: opts, correctAnswer: ans, explanation: exp, points: pts, order: ord })

const oe = (q: string, ans: string, exp: string, pts: number, ord: number): AssessmentQuestionDef =>
  ({ question: q, type: 'OPEN_ENDED', correctAnswer: ans, explanation: exp, points: pts, order: ord })

export const economicsAssessments: Record<string, AssessmentDef> = {
  'economic-thinking': {
    title: 'Economic Thinking Assessment',
    passingScore: 75,
    timeLimitMin: 30,
    questions: [
      mc('What does scarcity mean in economics?', ['Goods are rare and expensive', 'Resources are limited relative to wants', 'Only wealthy people can afford things', 'Markets have few sellers'], 'Resources are limited relative to wants', 'Scarcity means that resources — time, money, materials — are always limited compared to the unlimited wants people have.', 1, 1),
      mc('What is an opportunity cost?', ['The price of a product', 'The cost of producing one more unit', 'The value of the next best alternative you give up', 'A hidden tax on transactions'], 'The value of the next best alternative you give up', 'Opportunity cost is what you sacrifice when you make a choice — the benefit of the option you did not choose.', 1, 2),
      mc('Which of the following best describes a trade-off?', ['Buying goods from another country', 'Exchanging currency', 'Giving up one thing to get another', 'Reducing production costs'], 'Giving up one thing to get another', 'Every decision involves trade-offs — you can\'t have everything, so choosing one option means forgoing others.', 1, 3),
      mc('What does it mean to "think at the margin"?', ['Consider extreme scenarios', 'Evaluate the cost and benefit of one more unit', 'Only think about small purchases', 'Focus on the profit margin'], 'Evaluate the cost and benefit of one more unit', 'Marginal thinking means asking: what changes if I do one more (or one less) of this? It\'s a core economic reasoning tool.', 1, 4),
      mc('Which of these is an example of a positive incentive?', ['A fine for speeding', 'A discount for early payment', 'Higher taxes on cigarettes', 'Jail time for theft'], 'A discount for early payment', 'Positive incentives reward desired behavior. A discount encourages people to pay on time without punishment.', 1, 5),
      mc('What is the difference between a need and a want in economics?', ['Needs are cheap; wants are expensive', 'Needs are essential for survival; wants are not', 'Needs come from government; wants are personal', 'There is no difference'], 'Needs are essential for survival; wants are not', 'Economists distinguish needs (food, shelter, water) from wants (luxuries, preferences) to analyze decision-making and resource allocation.', 1, 6),
      mc('What is the purpose of a model in economics?', ['To predict stock prices exactly', 'To simplify reality and test ideas', 'To replace real-world data', 'To ensure everyone earns the same income'], 'To simplify reality and test ideas', 'Economic models are simplified representations of reality used to understand relationships and test theories without all the complexity of the real world.', 1, 7),
      mc('What does "rational behavior" assume in basic economic theory?', ['People always make perfect decisions', 'People choose the option that maximizes their benefit given their preferences', 'People never make mistakes', 'People always choose the cheapest option'], 'People choose the option that maximizes their benefit given their preferences', 'Rationality in economics means decision-makers weigh costs and benefits and choose what they believe is best for them — not that they\'re infallible.', 1, 8),
      oe('Explain a real-life example of opportunity cost from your own life.', 'Opportunity cost is the next best alternative given up when making a choice. For example, spending Saturday working means giving up leisure time — the opportunity cost is that free time.', 'A strong answer identifies a specific choice and names what was sacrificed — not just that "something was given up" but what specifically.', 2, 9),
      oe('Why do economists say "there\'s no such thing as a free lunch"? What does this phrase mean?', 'Even if something has no direct price, there is always an opportunity cost — someone paid for it, or something else was given up. Resources used for one thing can\'t be used for another.', 'The answer should connect the phrase to scarcity and opportunity cost, not just define "free lunch" literally.', 2, 10),
    ],
  },

  'business-economics': {
    title: 'Business Economics Assessment',
    passingScore: 75,
    timeLimitMin: 30,
    questions: [
      mc('What is supply in economics?', ['The desire consumers have to buy goods', 'The amount of a good producers are willing to sell at various prices', 'The total money in an economy', 'The government\'s stock of goods'], 'The amount of a good producers are willing to sell at various prices', 'Supply refers to how much of a good or service producers offer for sale at different price levels.', 1, 1),
      mc('When demand increases and supply stays the same, what typically happens to price?', ['Price falls', 'Price stays the same', 'Price rises', 'Supply also increases'], 'Price rises', 'With higher demand and unchanged supply, competition among buyers pushes prices upward until a new equilibrium is reached.', 1, 2),
      mc('What is a market equilibrium?', ['When the government sets a fixed price', 'When quantity supplied equals quantity demanded', 'When all businesses make a profit', 'When prices are at their lowest'], 'When quantity supplied equals quantity demanded', 'Equilibrium is the price at which the market clears — no surplus (unsold goods) and no shortage (unmet demand).', 1, 3),
      mc('What does "price elasticity of demand" measure?', ['How quickly prices change', 'How responsive quantity demanded is to a price change', 'The percentage profit margin', 'How many sellers are in a market'], 'How responsive quantity demanded is to a price change', 'Elasticity measures the sensitivity of demand to price. High elasticity means consumers buy much less when prices rise; low elasticity means demand barely changes.', 1, 4),
      mc('Which market structure has one dominant seller with no close substitutes?', ['Perfect competition', 'Oligopoly', 'Monopoly', 'Duopoly'], 'Monopoly', 'A monopoly exists when a single firm controls the entire market for a product or service with no close competition.', 1, 5),
      mc('What is a variable cost?', ['A cost that doesn\'t change with output', 'A cost that changes based on how much is produced', 'A one-time startup expense', 'A cost set by the government'], 'A cost that changes based on how much is produced', 'Variable costs (like materials and hourly labor) rise as production increases, unlike fixed costs (like rent) that stay the same regardless of output.', 1, 6),
      mc('What happens to a firm\'s profit when revenue exceeds total costs?', ['The firm operates at a loss', 'The firm breaks even', 'The firm earns a profit', 'The firm must lower prices'], 'The firm earns a profit', 'Profit = Revenue − Total Costs. When revenue is higher than all costs combined, the firm is profitable.', 1, 7),
      mc('What is a competitive advantage?', ['Selling at the lowest possible price', 'A factor that allows a firm to outperform rivals', 'Having the most employees', 'Operating without any competition'], 'A factor that allows a firm to outperform rivals', 'Competitive advantage is what distinguishes a firm — unique products, lower costs, better service — that lets it attract and retain customers better than competitors.', 1, 8),
      oe('Describe how supply and demand interact to set the price of a product you buy regularly.', 'Supply and demand interact at a market equilibrium. If more buyers want the product (demand up), sellers can raise prices. If supply increases (e.g., more producers), prices tend to fall. The market settles at the price where supply equals demand.', 'A strong answer applies the concept to a specific real product and explains the direction of price movement based on shifts.', 2, 9),
      oe('Why might a business choose to raise prices even if it risks losing some customers?', 'If demand is inelastic — meaning customers don\'t change their buying habits much when prices rise — a business can earn more revenue with fewer sales. Also, higher prices can signal quality or help cover rising costs.', 'The answer should mention elasticity or cost reasoning, not just vague profit motives.', 2, 10),
    ],
  },

  'macroeconomics': {
    title: 'Macroeconomics Assessment',
    passingScore: 75,
    timeLimitMin: 30,
    questions: [
      mc('What does GDP measure?', ['Total government spending', 'The total value of all goods and services produced in a country over a period', 'The number of people employed', 'The value of exports minus imports'], 'The total value of all goods and services produced in a country over a period', 'Gross Domestic Product is the broadest measure of a nation\'s economic output — all goods and services produced within its borders.', 1, 1),
      mc('What is inflation?', ['A rise in unemployment', 'A general increase in the price level over time', 'When the economy shrinks', 'When the government prints less money'], 'A general increase in the price level over time', 'Inflation means the purchasing power of money falls — the same amount of money buys less than it did before.', 1, 2),
      mc('What is the unemployment rate?', ['The percentage of all adults who are not working', 'The percentage of the labor force actively seeking work but not employed', 'The number of jobs available', 'The number of people who quit their jobs'], 'The percentage of the labor force actively seeking work but not employed', 'The unemployment rate counts people who are jobless, available to work, and actively looking — not everyone who isn\'t working.', 1, 3),
      mc('What is a recession?', ['When inflation rises above 5%', 'Two consecutive quarters of negative GDP growth', 'When the stock market falls 20%', 'When government debt increases'], 'Two consecutive quarters of negative GDP growth', 'A recession is technically defined as two or more consecutive quarters where real GDP declines.', 1, 4),
      mc('What tool does the Federal Reserve primarily use to control inflation?', ['Tax rates', 'Interest rates', 'Trade tariffs', 'Government spending'], 'Interest rates', 'The Fed\'s main lever is the federal funds rate. Raising interest rates makes borrowing more expensive, slowing spending and cooling inflation.', 1, 5),
      mc('What is fiscal policy?', ['The central bank\'s management of interest rates', 'Government decisions about spending and taxation', 'International trade agreements', 'Corporate pricing strategies'], 'Government decisions about spending and taxation', 'Fiscal policy is how governments use their budgets — spending more or taxing less to stimulate the economy, or the reverse to slow it down.', 1, 6),
      mc('What does the Consumer Price Index (CPI) track?', ['Corporate profits', 'The average change in prices paid by consumers for a basket of goods', 'Government bond prices', 'Export volumes'], 'The average change in prices paid by consumers for a basket of goods', 'The CPI measures inflation as experienced by typical households — tracking a standard basket of goods and services over time.', 1, 7),
      mc('What is the difference between a budget deficit and national debt?', ['They are the same thing', 'A deficit is annual shortfall; national debt is total accumulated deficits', 'National debt is annual; deficit is total', 'Neither involves government spending'], 'A deficit is annual shortfall; national debt is total accumulated deficits', 'A deficit occurs in a single year when spending exceeds revenue. National debt is the sum of all past deficits that haven\'t been paid off.', 1, 8),
      oe('Explain how raising interest rates is supposed to reduce inflation.', 'Higher interest rates make borrowing more expensive for businesses and consumers. People take out fewer loans, spend less, and businesses invest less. This reduces demand in the economy. With less money chasing goods, price pressures ease and inflation slows.', 'The answer should trace the chain: higher rates → less borrowing → less spending → lower demand → lower inflation.', 2, 9),
      oe('If the government wants to stimulate the economy during a recession, what fiscal policy tools might it use and why?', 'The government can increase spending (infrastructure, programs) to inject money into the economy and create jobs. It can also cut taxes to leave more money in households\' and businesses\' pockets, encouraging spending and investment. Both approaches aim to increase aggregate demand.', 'A strong answer names both tools (spending and taxes) and explains the mechanism — not just "the government helps people."', 2, 10),
    ],
  },

  'global-economics': {
    title: 'Global Economics Assessment',
    passingScore: 75,
    timeLimitMin: 30,
    questions: [
      mc('What is comparative advantage?', ['Having the best technology in a country', 'The ability to produce a good at a lower opportunity cost than another country', 'Being the largest exporter in a market', 'Having the lowest wages'], 'The ability to produce a good at a lower opportunity cost than another country', 'Comparative advantage means a country can produce something at relatively lower cost than others — this is the basis for trade even when one country is better at producing everything.', 1, 1),
      mc('What is a tariff?', ['A trade agreement between countries', 'A tax on imported goods', 'A subsidy for domestic producers', 'A shipping fee for exports'], 'A tax on imported goods', 'Tariffs are taxes placed on imports, making foreign goods more expensive to protect domestic industries or raise revenue.', 1, 2),
      mc('What does a trade deficit mean?', ['A country owes money to other governments', 'A country imports more than it exports', 'A country has a weak currency', 'A country is losing foreign investors'], 'A country imports more than it exports', 'A trade deficit occurs when the value of a country\'s imports exceeds its exports. It means the country is buying more from abroad than it is selling.', 1, 3),
      mc('What is a free trade agreement?', ['An agreement to eliminate all taxes', 'A pact between countries to reduce or eliminate trade barriers', 'A commitment to equal wages across countries', 'A deal to share natural resources'], 'A pact between countries to reduce or eliminate trade barriers', 'Free trade agreements lower or remove tariffs, quotas, and other restrictions so goods and services flow more freely between member countries.', 1, 4),
      mc('What causes currency exchange rates to change?', ['Only government decisions', 'Supply and demand for currencies in global markets', 'The number of tourists visiting a country', 'Annual GDP reports'], 'Supply and demand for currencies in global markets', 'Exchange rates fluctuate based on trade flows, investment, interest rates, and market speculation — currencies trade like other assets in global markets.', 1, 5),
      mc('What is globalization?', ['A policy of closing borders to trade', 'The increasing interconnection of world economies, cultures, and people', 'A single global government', 'The spread of the US dollar as global currency'], 'The increasing interconnection of world economies, cultures, and people', 'Globalization refers to the growing integration of economies through trade, investment, technology, and cultural exchange across borders.', 1, 6),
      mc('Which organization oversees international trade rules and disputes?', ['The United Nations', 'The International Monetary Fund', 'The World Trade Organization', 'The World Bank'], 'The World Trade Organization', 'The WTO sets and enforces the rules governing international trade and provides a forum for resolving trade disputes between countries.', 1, 7),
      mc('What is an import quota?', ['A minimum amount a country must import', 'A limit on how much of a good can be imported', 'A tax on imports', 'A subsidy for domestic exporters'], 'A limit on how much of a good can be imported', 'Quotas restrict the quantity of a specific good that can be imported, protecting domestic producers from foreign competition differently than tariffs.', 1, 8),
      oe('Explain why two countries might benefit from trading even if one is more efficient at producing everything.', 'Even if one country is better at producing all goods, it should specialize in what it produces at the lowest relative cost (comparative advantage) and trade for the rest. Both countries end up consuming more than they could alone. Trade gains come from specialization, not just absolute productivity.', 'The answer must reference comparative advantage, not just "they trade to get what they can\'t make."', 2, 9),
      oe('What are some arguments for and against tariffs? Give at least one of each.', 'For: Tariffs protect domestic industries and jobs from cheap foreign competition. Against: Tariffs raise prices for consumers, invite retaliation from trade partners, and reduce overall economic efficiency by distorting markets.', 'A strong answer presents a real argument on both sides — not just "some people like them, some don\'t."', 2, 10),
    ],
  },

  'behavioral-economics': {
    title: 'Behavioral Economics Assessment',
    passingScore: 75,
    timeLimitMin: 30,
    questions: [
      mc('What does behavioral economics study?', ['Corporate financial statements', 'How psychological factors affect real economic decisions', 'Government monetary policy', 'International trade patterns'], 'How psychological factors affect real economic decisions', 'Behavioral economics combines psychology and economics to understand why people make decisions that deviate from pure rationality.', 1, 1),
      mc('What is a cognitive bias?', ['A deliberate strategy to maximize profit', 'A systematic pattern of deviation from rational judgment', 'A preference for saving over spending', 'A type of market failure'], 'A systematic pattern of deviation from rational judgment', 'Cognitive biases are mental shortcuts or tendencies that cause people to think or decide in predictably irrational ways.', 1, 2),
      mc('What is loss aversion?', ['Avoiding investments entirely', 'Feeling losses more strongly than equivalent gains', 'Losing money on bad investments', 'Preferring guaranteed losses to uncertain ones'], 'Feeling losses more strongly than equivalent gains', 'Research shows losing $100 feels roughly twice as bad as gaining $100 feels good — people are more motivated to avoid losses than to acquire equivalent gains.', 1, 3),
      mc('What is the anchoring bias?', ['Relying too heavily on the first piece of information encountered', 'Trusting anchor stores more than smaller shops', 'Preferring familiar brands', 'Always choosing the median option'], 'Relying too heavily on the first piece of information encountered', 'Anchoring means the first number or piece of information you see disproportionately influences subsequent judgments, even when irrelevant.', 1, 4),
      mc('What is a nudge in behavioral economics?', ['A fine for bad behavior', 'A subtle change in choice design that influences decisions without restricting options', 'A marketing campaign', 'A government mandate'], 'A subtle change in choice design that influences decisions without restricting options', 'Nudges are design choices — like making healthy food the default — that steer people toward better decisions while leaving them free to choose otherwise.', 1, 5),
      mc('What is present bias?', ['Preferring to pay bills early', 'Overvaluing immediate rewards relative to future rewards', 'Being unable to plan for the future', 'Believing today\'s prices are always fair'], 'Overvaluing immediate rewards relative to future rewards', 'Present bias explains why people prefer $50 now over $60 next month even though they\'d choose $60 a month from now over $50 two months from now — the immediate feels more real.', 1, 6),
      mc('What does "default effect" mean?', ['The best available option', 'People tend to stick with whatever option is pre-selected', 'The standard market price', 'Choosing the cheapest item'], 'People tend to stick with whatever option is pre-selected', 'Defaults are powerful nudges — most people accept whatever is set as the default (like organ donation or retirement savings enrollment) rather than actively switching.', 1, 7),
      mc('What is the framing effect?', ['How marketing changes product perception', 'How the way information is presented affects decisions', 'A tax framework for businesses', 'A method for displaying prices'], 'How the way information is presented affects decisions', 'The same information presented differently leads to different choices. "90% survival rate" vs. "10% mortality rate" describe identical risks but produce different reactions.', 1, 8),
      oe('Describe a real situation where you or someone you know made an irrational economic decision because of a bias. Which bias was it?', 'Example: Staying in a bad investment because you\'ve already put money in (sunk cost fallacy). Or choosing the medium coffee because it seems like a deal next to the large (anchoring). The key is identifying the specific bias and explaining how it distorted the decision.', 'A strong answer names the bias correctly and connects it to a real behavior — not just a vague story about a bad decision.', 2, 9),
      oe('How could a business or government use behavioral economics to encourage better financial decisions without removing any choices?', 'They could use defaults (auto-enroll employees in retirement savings), simplify options to reduce decision fatigue, use loss framing ("you\'re leaving money on the table"), or make the desired behavior the path of least resistance. Nudges preserve freedom while improving outcomes.', 'The answer should name at least one specific technique and explain why it works psychologically.', 2, 10),
    ],
  },
}
