import type { ExerciseDef } from '../types'

function mc(
  question: string,
  options: string[],
  correctAnswer: string,
  explanation: string,
  order: number
): ExerciseDef {
  return { question, type: 'MULTIPLE_CHOICE', options, correctAnswer, explanation, order }
}

export const financeExercises8: Record<string, ExerciseDef[]> = {
  'tax-forms': [
    mc('What is the Form 1040?', ['A form for reporting business income', 'The main individual income tax return filed with the IRS', 'A W-2 supplement', 'A form for estate taxes'], 'The main individual income tax return filed with the IRS', 'Form 1040 is the standard U.S. individual tax return — it summarizes your income, deductions, credits, and final tax bill.', 1),
    mc('What is a 1099-DIV?', ['A form reporting dividend income from investments', 'A form for self-employment income', 'A contractor payment form', 'A bank interest statement'], 'A form reporting dividend income from investments', '1099-DIV reports dividends and capital gain distributions from stocks and mutual funds held in taxable accounts.', 2),
    mc('What is a 1098 form used for?', ['Reporting student loan interest paid', 'Reporting mortgage interest paid (used for itemizing)', 'Reporting unemployment benefits received', 'Reporting self-employment income'], 'Reporting mortgage interest paid (used for itemizing)', 'Form 1098 from your lender shows mortgage interest paid — deductible if you itemize. A 1098-E reports student loan interest.', 3),
    mc('What is Form 1099-INT?', ['Income from investments in international stocks', 'Interest income earned from bank accounts, CDs, and bonds', 'Interest paid on loans', 'Insurance premium statements'], 'Interest income earned from bank accounts, CDs, and bonds', 'Banks send 1099-INT when you earn $10+ in interest. This interest is taxable income reported on your 1040.', 4),
    mc('What does a Schedule K-1 report?', ['Your withholding from an employer', 'Your share of income/losses from a partnership, S-corp, trust, or estate', 'Rental income from a property you own', 'Investment dividends from index funds'], 'Your share of income/losses from a partnership, S-corp, trust, or estate', 'K-1 flows your share of business income, losses, credits, and deductions from pass-through entities to your personal return.', 5),
  ],
  'free-filing-options': [
    mc('What is the IRS Free File program?', ['A paid tax service subsidized by the government', 'Free federal tax filing software for taxpayers under certain income thresholds', 'A file storage service for tax documents', 'A form for requesting free tax advice'], 'Free federal tax filing software for taxpayers under certain income thresholds', 'IRS Free File offers free filing software from major companies for taxpayers with AGI at or below ~$79,000 (2024).', 1),
    mc('What is IRS Direct File?', ['The IRS\'s own free online filing tool for simple returns in participating states', 'A form mailed directly to the IRS', 'A free service offered by TurboTax', 'A service that files for you automatically'], 'The IRS\'s own free online filing tool for simple returns in participating states', 'Direct File is the IRS\'s own filing tool — free, no upsells, and available to those with straightforward tax situations.', 2),
    mc('What is the Volunteer Income Tax Assistance (VITA) program?', ['A paid service from the IRS', 'Free tax prep by IRS-certified volunteers for people earning generally under $67,000', 'A program to recruit IRS employees', 'Software for tax professionals'], 'Free tax prep by IRS-certified volunteers for people earning generally under $67,000', 'VITA sites are in libraries, community centers, and churches — IRS-certified volunteers prepare returns for free.', 3),
    mc('For a simple return (W-2 income, standard deduction), what is the cheapest filing option?', ['A CPA or tax attorney', 'IRS Free File, Direct File, or VITA', 'TurboTax Premium', 'H&R Block in-person service'], 'IRS Free File, Direct File, or VITA', 'Simple returns don\'t need paid services. Free options are just as accurate for straightforward situations.', 4),
    mc('When is it worth paying for tax preparation?', ['Never — always use free services', 'When you have complex situations: business income, multiple states, investments, rental property, or major life changes', 'When your refund is large', 'When you file late'], 'When you have complex situations: business income, multiple states, investments, rental property, or major life changes', 'Complexity justifies cost. Self-employment, rental income, or multiple states are where professional help pays for itself.', 5),
  ],
  'tax-deductions': [
    mc('What is a tax deduction?', ['A reduction in your tax bill dollar-for-dollar', 'A reduction in your taxable income, which reduces your tax bill proportionally', 'A refund from the IRS for overpayment', 'A penalty for underpayment'], 'A reduction in your taxable income, which reduces your tax bill proportionally', 'A $1,000 deduction at a 22% marginal rate saves $220 in taxes — not $1,000. Deductions reduce income; credits reduce tax directly.', 1),
    mc('Which of these is a common above-the-line deduction (available without itemizing)?', ['Charitable donations', 'Mortgage interest', 'Student loan interest paid', 'Medical expenses'], 'Student loan interest paid', 'Above-the-line deductions include: student loan interest, SE tax deduction, retirement contributions, and HSA contributions. No itemizing needed.', 2),
    mc('What is the home office deduction for?', ['Any room you use for personal projects', 'Space used regularly and exclusively for business, for self-employed workers', 'Any expenses related to your home', 'Remote employees working from home for an employer'], 'Space used regularly and exclusively for business, for self-employed workers', 'Self-employed with dedicated home office space can deduct a portion of rent/mortgage, utilities, and internet. W-2 employees cannot.', 3),
    mc('Which self-employed business expenses are generally deductible?', ['Groceries and clothing', 'Legitimate business expenses: equipment, software, professional development, business travel, health insurance premiums', 'Personal vehicle for all uses', 'Home entertainment costs'], 'Legitimate business expenses: equipment, software, professional development, business travel, health insurance premiums', 'Self-employed can deduct ordinary and necessary business expenses. The key test: was it for business?', 4),
    mc('What is the Child Tax Credit?', ['A deduction for claiming a child as a dependent', 'A tax credit reducing your tax bill by up to $2,000 per qualifying child under 17', 'Free childcare provided by the government', 'A credit only for single parents'], 'A tax credit reducing your tax bill by up to $2,000 per qualifying child under 17', 'The Child Tax Credit directly reduces taxes owed — up to $2,000 per child under 17. Credits are more valuable than deductions.', 5),
  ],
  'tax-advantaged-accounts': [
    mc('What makes an account "tax-advantaged"?', ['It earns higher interest rates', 'It receives special tax treatment — pre-tax contributions, tax-free growth, or tax-free withdrawals', 'It is insured by the government', 'It has no fees'], 'It receives special tax treatment — pre-tax contributions, tax-free growth, or tax-free withdrawals', 'Tax-advantaged accounts (401k, IRA, HSA, FSA) reduce your current or future tax burden — a legal, powerful wealth-building tool.', 1),
    mc('What is a Traditional IRA?', ['An account where you pay taxes now and withdraw tax-free later', 'An account with pre-tax contributions that grow tax-deferred; you pay taxes on withdrawal', 'A government retirement pension', 'An insurance product with a death benefit'], 'An account with pre-tax contributions that grow tax-deferred; you pay taxes on withdrawal', 'Traditional IRA: contribute pre-tax (if eligible) → grow tax-deferred → pay ordinary income tax at withdrawal in retirement.', 2),
    mc('What is a Roth IRA?', ['Pre-tax contributions, taxable withdrawals', 'After-tax contributions, tax-free growth and withdrawals in retirement', 'A government pension for low-income workers', 'An account only for self-employed people'], 'After-tax contributions, tax-free growth and withdrawals in retirement', 'Roth IRA: pay taxes now → invest after-tax dollars → all growth and withdrawals in retirement are completely tax-free.', 3),
    mc('What is an HSA (Health Savings Account)?', ['A checking account linked to your health insurance', 'A triple-tax-advantaged account for medical expenses: pre-tax in, tax-free growth, tax-free withdrawals for medical costs', 'A government health savings program for low-income families', 'A savings account that earns medical discounts'], 'A triple-tax-advantaged account for medical expenses: pre-tax in, tax-free growth, tax-free withdrawals for medical costs', 'HSAs are uniquely powerful: no tax going in, no tax growing, no tax coming out for medical expenses. After 65, withdraw for anything.', 4),
    mc('What is an FSA (Flexible Spending Account) and how does it differ from an HSA?', ['FSAs are for retirement; HSAs are for healthcare', 'FSAs are "use it or lose it" within the plan year; HSAs roll over indefinitely', 'FSAs earn more interest than HSAs', 'HSAs require a high-deductible plan; FSAs do not'], 'FSAs are "use it or lose it" within the plan year; HSAs roll over indefinitely', 'FSA: use pre-tax dollars for medical or dependent care, but forfeit unused balance at year-end. HSA: rolls over, grows, never expires.', 5),
  ],
  'when-to-get-help': [
    mc('When should you consult a CPA or tax professional?', ['For any tax return, regardless of complexity', 'When your situation is complex: business, rental property, divorce, major transactions, or multiple states', 'Only if you\'re audited', 'Never — software is always sufficient'], 'When your situation is complex: business, rental property, divorce, major transactions, or multiple states', 'Professional help is worth it when the tax savings or error prevention exceed the cost — typically with complex financial situations.', 1),
    mc('What is a fiduciary financial advisor?', ['An advisor who earns commission on products they sell', 'An advisor legally required to act in your best financial interest', 'A government-appointed financial counselor', 'An advisor who manages only retirement accounts'], 'An advisor legally required to act in your best financial interest', 'Fiduciary duty means they must recommend what\'s best for you, not what earns them the highest commission. Ask before hiring.', 2),
    mc('What is fee-only financial planning?', ['Planning where you pay per financial transaction', 'Advisors who charge only you — no commissions from products they recommend', 'Free financial advice from nonprofits', 'Planning that charges a percentage of your assets only'], 'Advisors who charge only you — no commissions from products they recommend', 'Fee-only removes conflicts of interest — the advisor earns only from you, not from selling you high-commission products.', 3),
    mc('When is nonprofit credit counseling useful?', ['When you want to build wealth through investments', 'When struggling with debt — they help negotiate repayment plans and provide free/low-cost guidance', 'When you need help with tax returns only', 'When you want a mortgage'], 'When struggling with debt — they help negotiate repayment plans and provide free/low-cost guidance', 'NFCC-member credit counseling agencies offer legitimate, low-cost debt management plans and financial counseling — not scams.', 4),
    mc('What should you always verify about a financial professional before hiring them?', ['That they went to a good college', 'Their credentials, fiduciary status, compensation structure, and any disciplinary history (BrokerCheck or CFP Board)', 'Their social media following', 'Their office location'], 'Their credentials, fiduciary status, compensation structure, and any disciplinary history (BrokerCheck or CFP Board)', 'Use FINRA BrokerCheck and CFP Board\'s website to verify credentials and check for complaints before trusting anyone with your money.', 5),
  ],
  'the-real-cost-of-homeownership': [
    mc('Beyond the mortgage payment, what ongoing costs do homeowners face?', ['None — the mortgage covers everything', 'Property taxes, homeowners insurance, HOA fees, maintenance, and repairs', 'Only utilities', 'Only HOA fees if applicable'], 'Property taxes, homeowners insurance, HOA fees, maintenance, and repairs', 'The "true cost" of owning includes all these beyond the mortgage — often 1-2% of home value per year in maintenance alone.', 1),
    mc('What is the general rule of thumb for annual home maintenance costs?', ['0.1% of home value', '0.5% of home value', '1-2% of home value per year', '5% of home value per year'], '1-2% of home value per year', 'A $300,000 home should budget $3,000-6,000/year for maintenance and repairs — HVAC, roof, appliances, plumbing, etc.', 2),
    mc('What are "closing costs" when buying a home?', ['The monthly payment at closing', 'Fees paid at closing — typically 2-5% of the purchase price', 'The down payment', 'The cost to close on a mortgage after paying it off'], 'Fees paid at closing — typically 2-5% of the purchase price', 'Closing costs include loan fees, title insurance, appraisal, attorney fees, and prepaid insurance/taxes — often $6,000-$15,000 on a $300K home.', 3),
    mc('What is equity?', ['The amount you still owe on your mortgage', 'Your ownership stake — the home\'s value minus what you owe', 'The interest portion of your mortgage payment', 'The property tax amount'], 'Your ownership stake — the home\'s value minus what you owe', 'Equity = market value − outstanding mortgage. As you pay down principal and home value rises, equity grows.', 4),
    mc('What is PMI and when is it required?', ['Private Mortgage Insurance — required when down payment is less than 20%', 'Property Management Insurance — required when renting out your home', 'Pre-Mortgage Insurance — required before applying for a loan', 'Public Mortgage Insurance — a government program'], 'Private Mortgage Insurance — required when down payment is less than 20%', 'PMI protects the lender if you default with low equity. It typically costs 0.5-1.5% of the loan annually, added to your payment.', 5),
  ],
  'when-renting-wins': [
    mc('Which factor most supports renting over buying?', ['You dislike your landlord', 'You plan to move within 2-3 years', 'Mortgage payments are slightly higher than rent', 'You don\'t own any furniture'], 'You plan to move within 2-3 years', 'Buying and selling has high transaction costs (5-10% of the price). You need several years to break even — short stays favor renting.', 1),
    mc('What is the price-to-rent ratio, and what does it tell you?', ['How much rent you can afford; higher is better', 'The ratio of home price to annual rent — high ratios favor renting; low ratios favor buying', 'The ratio of your rent to your income', 'A measure of rental inflation'], 'The ratio of home price to annual rent — high ratios favor renting; low ratios favor buying', 'P/R ratio = home price / annual rent. Above 20 generally favors renting (San Francisco, NYC). Below 15 may favor buying.', 2),
    mc('What is an opportunity cost argument for renting?', ['Renters have no financial discipline', 'The down payment money invested in index funds might outperform home appreciation', 'Rent payments go to waste', 'Renters don\'t pay property taxes, so they save more'], 'The down payment money invested in index funds might outperform home appreciation', 'A $60,000 down payment invested at 7% grows to $120,000 in 10 years. Home appreciation varies widely — renting and investing can win.', 3),
    mc('In hot housing markets, renting may be smarter because:', ['Renters always come out ahead financially', 'Home prices may be inflated and the buyer is taking on outsized risk for uncertain appreciation', 'Landlords pay all maintenance costs', 'Rent is always much less than mortgage payments'], 'Home prices may be inflated and the buyer is taking on outsized risk for uncertain appreciation', 'Buying at peak prices with high P/R ratios means you need significant appreciation just to break even after costs.', 4),
    mc('What lifestyle factors favor renting?', ['You want to build equity', 'You value flexibility, don\'t want maintenance responsibility, or are uncertain about the future', 'You have a large down payment', 'You have excellent credit'], 'You value flexibility, don\'t want maintenance responsibility, or are uncertain about the future', 'Renting offers mobility and zero maintenance hassle — valuable for career flexibility, uncertain situations, or a dislike of home upkeep.', 5),
  ],
}
