import type { ExerciseDef } from '../types'

function mc(
  question: string,
  options: string[],
  correctAnswer: string,
  explanation: string,
  order: number
): ExerciseDef {
  return { question, type: 'MULTIPLE_CHOICE', options, correctAnswer, explanation, order }
}

export const financeExercises3: Record<string, ExerciseDef[]> = {
  'good-debt-vs-bad-debt': [
    mc('What generally distinguishes "good" debt from "bad" debt?', ['Good debt has lower interest rates', 'Good debt builds long-term value or income; bad debt funds consumption with high interest', 'Good debt is tax deductible', 'Good debt has no interest'], 'Good debt builds long-term value or income; bad debt funds consumption with high interest', 'A mortgage (builds equity), student loan (builds earning power), or business loan can be "good." Credit card debt for spending is "bad."', 1),
    mc('Which is generally considered "good" debt?', ['A payday loan to cover rent', 'Credit card debt from a vacation', 'A mortgage for a home that appreciates in value', 'Buy-now-pay-later for electronics'], 'A mortgage for a home that appreciates in value', 'A mortgage finances an asset that may increase in value over time — the classic example of potentially good debt.', 2),
    mc('Why is credit card debt at 24% APR considered bad debt?', ['Credit cards are illegal in some states', 'The high interest rate costs far more than the original purchase over time', 'Credit cards reduce your credit score automatically', 'They can\'t be paid off early'], 'The high interest rate costs far more than the original purchase over time', '$1,000 at 24% APR, paying minimums, can take years to pay off and cost hundreds in interest beyond the purchase.', 3),
    mc('A student loan at 5% interest to earn a higher-paying degree is:', ['Always bad debt', 'Potentially good debt if the degree increases earnings enough to justify the cost', 'Always good debt regardless of outcome', 'Neither good nor bad'], 'Potentially good debt if the degree increases earnings enough to justify the cost', 'Student debt can be good or bad depending on the degree\'s ROI. A $150k loan for a $35k/year career is a poor trade.', 4),
    mc('Even "good" debt should be:', ['Maximized to build credit', 'Kept as long as possible for tax benefits', 'Minimized and managed carefully', 'Ignored once set up'], 'Minimized and managed carefully', 'No debt is risk-free. Even good debt should be the minimum necessary, managed responsibly, and paid off on schedule.', 5),
  ],
  'credit-cards': [
    mc('How do credit card companies make money from cardholders?', ['Annual fees only', 'Interest on carried balances, late fees, and annual fees', 'Renting your spending data', 'Taking a cut of every purchase'], 'Interest on carried balances, late fees, and annual fees', 'The biggest profits come from cardholders who carry balances and pay high interest. They also earn fees.', 1),
    mc('What is APR?', ['Annual Payment Required', 'Annual Percentage Rate — the yearly cost of carrying a balance', 'The fee charged annually for having the card', 'The minimum payment percentage'], 'Annual Percentage Rate — the yearly cost of carrying a balance', 'APR is the interest rate charged on carried balances. 24% APR on a $1,000 balance costs $240/year in interest.', 2),
    mc('What happens if you only pay the credit card minimum each month?', ['You pay off the debt in a reasonable time', 'You pay mostly interest — the debt shrinks very slowly and costs far more', 'Your credit score improves fastest', 'You avoid all interest charges'], 'You pay mostly interest — the debt shrinks very slowly and costs far more', 'Minimums are designed to maximize interest profits. Paying minimums on a large balance can take decades and double the cost.', 3),
    mc('What is a grace period on a credit card?', ['The time before your first payment is due', 'The window (typically 21-25 days) where no interest accrues if you pay in full', 'A period where fees are waived', 'The maximum time before your card is closed for non-use'], 'The window (typically 21-25 days) where no interest accrues if you pay in full', 'Pay your full balance before the grace period ends and you pay zero interest — the card is essentially a free short-term loan.', 4),
    mc('What is the safest way to use a credit card?', ['Carry a small balance to build credit', 'Pay the minimum every month', 'Pay the full statement balance by the due date every month', 'Use it for large purchases only'], 'Pay the full statement balance by the due date every month', 'Full payment by the due date = no interest + builds credit + earns rewards. This is the only way to win the credit card game.', 5),
  ],
  'student-loans': [
    mc('What is the difference between subsidized and unsubsidized federal student loans?', ['Subsidized have lower principal; unsubsidized are larger', 'Subsidized: government pays interest while in school; unsubsidized: interest accrues immediately', 'Subsidized are for graduate school; unsubsidized for undergrad', 'Subsidized are private loans; unsubsidized are federal'], 'Subsidized: government pays interest while in school; unsubsidized: interest accrues immediately', 'Subsidized loans are better — interest doesn\'t build while you\'re in school. Unsubsidized start accruing interest immediately.', 1),
    mc('What is income-driven repayment (IDR) for federal student loans?', ['Repaying only when income exceeds a threshold', 'A plan capping monthly payments at a percentage of discretionary income', 'A fixed low payment regardless of income', 'A loan forgiveness program'], 'A plan capping monthly payments at a percentage of discretionary income', 'IDR plans (IBR, PAYE, SAVE) set payments based on income — if income is low, payments can be $0. Forgiveness after 20-25 years.', 2),
    mc('What is Public Service Loan Forgiveness (PSLF)?', ['Forgiveness for any student loan after 10 years', 'Forgiveness after 10 years of payments while working full-time for a qualifying employer', 'A program for private school graduates', 'An automatic forgiveness program for low-income borrowers'], 'Forgiveness after 10 years of payments while working full-time for a qualifying employer', 'PSLF forgives remaining federal student debt after 10 years (120 payments) working for government or nonprofit employers.', 3),
    mc('Private student loans differ from federal loans in that they:', ['Have lower interest rates always', 'Lack income-driven repayment, forgiveness, and federal protections', 'Are smaller amounts', 'Are subsidized by the government'], 'Lack income-driven repayment, forgiveness, and federal protections', 'Private loans are from banks, not the government. They offer no IDR, no PSLF, and fewer hardship protections.', 4),
    mc('What is the smartest approach to student borrowing?', ['Borrow as much as you can at low rates', 'Borrow only what you need, maximize federal loans first, and research career earnings before committing', 'Use private loans to avoid federal bureaucracy', 'Take out loans for living expenses freely since rates are low'], 'Borrow only what you need, maximize federal loans first, and research career earnings before committing', 'The best student loan is the smallest one. Research expected salaries vs. total loan cost before signing anything.', 5),
  ],
  'predatory-lending': [
    mc('What is a payday loan?', ['A low-interest personal loan from a bank', 'A short-term, extremely high-interest loan due on your next payday', 'An advance on your salary from your employer', 'A government loan for emergencies'], 'A short-term, extremely high-interest loan due on your next payday', 'Payday loans are typically $200-$500 due in 2 weeks at APRs of 300-400%. They trap borrowers in debt cycles.', 1),
    mc('A payday loan with a $15 fee per $100 borrowed for 2 weeks is equivalent to what APR?', ['15%', '30%', '391%', '100%'], '391%', '$15 per $100 for 2 weeks = 15% per 2 weeks. Annualized: 15% × 26 = 390%. Payday loans are legally usurious.', 2),
    mc('What is rent-to-own?', ['Renting with an option to buy at fair market value', 'A scheme where you pay much more than retail for an item through small weekly payments', 'A homebuyer assistance program', 'A government housing voucher'], 'A scheme where you pay much more than retail for an item through small weekly payments', 'Rent-to-own stores charge 2-4x retail price through installments. A $400 TV might cost $1,200 total under rent-to-own.', 3),
    mc('Which of these is a sign of predatory lending?', ['Fixed interest rate disclosed upfront', 'No prepayment penalties', 'Triple-digit APR and automatic rollovers', 'A clear amortization schedule'], 'Triple-digit APR and automatic rollovers', 'Predatory loans obscure true costs, rollover debt for fees, and target people in financial distress.', 4),
    mc('What is the better alternative to a payday loan when you need emergency cash?', ['Another payday loan to cover the first', 'A credit union payday alternative loan (PAL), negotiating with creditors, or community assistance', 'A store credit card', 'A personal line of credit from a payday lender'], 'A credit union payday alternative loan (PAL), negotiating with creditors, or community assistance', 'Credit union PALs cap interest at 28% APR. Calling creditors, employers, or community organizations often beats any loan.', 5),
  ],
  'debt-avalanche-vs-snowball': [
    mc('What is the debt avalanche method?', ['Pay all debts equally each month', 'Pay minimums on all debts; put extra money toward the highest-interest debt first', 'Pay the largest balance first', 'Pay the newest debt first'], 'Pay minimums on all debts; put extra money toward the highest-interest debt first', 'The avalanche minimizes total interest paid — mathematically optimal. Tackle the most expensive debt first.', 1),
    mc('What is the debt snowball method?', ['Pay all debts simultaneously with equal amounts', 'Pay minimums on all; put extra money toward the smallest balance first regardless of interest', 'Pay the oldest debt first', 'Pay down debt only when you have a surplus'], 'Pay minimums on all; put extra money toward the smallest balance first regardless of interest', 'Snowball gives quick wins by eliminating small debts first — boosting motivation even if it costs more in interest.', 2),
    mc('Which method is mathematically optimal for minimizing total interest paid?', ['Debt snowball', 'Debt avalanche', 'Debt consolidation', 'Minimum payments'], 'Debt avalanche', 'Paying high-interest debt first always results in less total interest paid compared to snowball or minimum payments.', 3),
    mc('Which method works better for people who struggle with motivation to stay on a debt payoff plan?', ['Debt avalanche', 'Minimum payments', 'Debt snowball', 'Debt consolidation'], 'Debt snowball', 'Quick wins from eliminating small debts build momentum and motivation — the psychological benefit can outweigh the math cost.', 4),
    mc('The "extra money" in either method refers to:', ['Money borrowed for investing', 'Money you save by cutting expenses, applied on top of minimums', 'The minimum payment amount', 'Interest savings from the previous month'], 'Money you save by cutting expenses, applied on top of minimums', 'Find money by cutting spending or earning more, then throw that extra at your target debt each month.', 5),
  ],
  'negotiating-with-creditors': [
    mc('When can you negotiate with creditors?', ['Only if you\'re completely broke', 'When you\'re struggling to pay, have missed payments, or a debt is in collections', 'Only through a lawyer', 'Never — debt amounts are fixed by law'], 'When you\'re struggling to pay, have missed payments, or a debt is in collections', 'Creditors prefer getting something over nothing. If you\'re in hardship, call and ask for options — they often help.', 1),
    mc('What is a hardship program?', ['A government debt relief program', 'A creditor\'s program that temporarily reduces interest rates or payments for struggling customers', 'A bankruptcy filing', 'A payment plan set by a court'], 'A creditor\'s program that temporarily reduces interest rates or payments for struggling customers', 'Many credit card companies have undisclosed hardship programs — lower rates, waived fees, or reduced minimums for those who ask.', 2),
    mc('What is a debt settlement?', ['Paying off the full debt early for a discount', 'A creditor agreeing to accept less than the full balance owed', 'A bankruptcy chapter', 'A formal repayment agreement with the court'], 'A creditor agreeing to accept less than the full balance owed', 'Settlement means paying a portion of what you owe, in exchange for the debt being considered resolved. It hurts your credit.', 3),
    mc('What are the downsides of debt settlement?', ['There are no downsides', 'Credit damage, potential tax liability on forgiven debt, and fees if using a settlement company', 'It is illegal in most states', 'You must go to court'], 'Credit damage, potential tax liability on forgiven debt, and fees if using a settlement company', 'The IRS treats forgiven debt as income. Your credit takes a hit. Settlement companies often charge 15-25% of enrolled debt.', 4),
    mc('Before hiring a debt settlement company, you should:', ['Sign up immediately to start the process', 'Research alternatives: negotiate yourself, credit counseling (nonprofit), or bankruptcy as last resort', 'Contact your creditors to confirm they won\'t negotiate', 'Get a second credit card to balance transfer'], 'Research alternatives: negotiate yourself, credit counseling (nonprofit), or bankruptcy as last resort', 'You can often negotiate yourself for free. Nonprofit credit counseling is low-cost. Avoid for-profit debt relief firms.', 5),
  ],
  'debt-consolidation': [
    mc('What is debt consolidation?', ['Paying off all debt at once', 'Combining multiple debts into a single loan, ideally with lower interest', 'Filing for bankruptcy', 'Transferring debt between credit cards repeatedly'], 'Combining multiple debts into a single loan, ideally with lower interest', 'Consolidation simplifies multiple payments into one and can reduce the interest rate if you qualify for a lower rate.', 1),
    mc('A balance transfer credit card makes sense when:', ['You\'re struggling to pay minimums on current debt', 'You can pay off the transferred balance before the 0% intro period ends', 'The new card has a higher credit limit', 'You want to earn rewards on transferred debt'], 'You can pay off the transferred balance before the 0% intro period ends', 'Balance transfers offer 0% intro APR for 12-21 months. If you pay it off in that window, you save all the interest.', 2),
    mc('What is the risk of debt consolidation if spending habits don\'t change?', ['The new loan has higher interest always', 'You end up with the consolidated loan PLUS new credit card debt', 'Consolidation hurts your credit permanently', 'You lose access to the original credit accounts'], 'You end up with the consolidated loan PLUS new credit card debt', 'If you consolidate but continue spending on credit cards, you\'ll have the consolidation payment AND new card balances — worse than before.', 3),
    mc('Which type of consolidation loan typically offers the lowest interest rate?', ['Unsecured personal loan', 'Payday consolidation loan', 'Home equity loan (using your home as collateral)', 'Credit card balance transfer'], 'Home equity loan (using your home as collateral)', 'Secured debt costs less because the lender has collateral. But: if you default, you lose your home.', 4),
    mc('What is the difference between debt consolidation and debt settlement?', ['They are the same', 'Consolidation combines debts at new terms; settlement asks creditors to accept less than owed', 'Settlement is legal; consolidation is not', 'Consolidation requires bankruptcy; settlement doesn\'t'], 'Consolidation combines debts at new terms; settlement asks creditors to accept less than owed', 'Consolidation pays debts in full through new financing. Settlement reduces what you owe but damages your credit.', 5),
  ],
}
