import type { ExerciseDef } from '../types'

function mc(
  question: string,
  options: string[],
  correctAnswer: string,
  explanation: string,
  order: number
): ExerciseDef {
  return { question, type: 'MULTIPLE_CHOICE', options, correctAnswer, explanation, order }
}

export const financeExercises1: Record<string, ExerciseDef[]> = {
  'where-does-money-come-from': [
    mc('What is the difference between gross income and net income?', ['Gross is after taxes; net is before taxes', 'Gross is before taxes and deductions; net is what you actually take home', 'They are the same thing', 'Net income includes bonuses; gross does not'], 'Gross is before taxes and deductions; net is what you actually take home', 'Gross income is total earnings. Net income ("take-home pay") is what\'s left after taxes and deductions.', 1),
    mc('Which is an example of passive income?', ['Your hourly wages at work', 'Rental income from a property you own', 'A year-end bonus from your employer', 'Overtime pay'], 'Rental income from a property you own', 'Passive income comes in without active hourly work — rental income, dividends, and royalties are examples.', 2),
    mc('What is a W-2 form?', ['A tax return filing', 'An employer\'s report of wages paid and taxes withheld for an employee', 'A form for self-employment income', 'A bank statement showing deposits'], 'An employer\'s report of wages paid and taxes withheld for an employee', 'Employers send W-2s by January 31 showing total wages paid and taxes withheld — you use it to file your taxes.', 3),
    mc('Why is it important to understand all your income sources?', ['To maximize overtime pay', 'To accurately budget, plan, and file taxes', 'To negotiate a higher salary', 'To qualify for more credit cards'], 'To accurately budget, plan, and file taxes', 'Knowing all income — wages, side work, benefits — gives you an accurate picture for budgeting and ensures correct tax filing.', 4),
    mc('Which of these is NOT typically a source of earned income?', ['Hourly wages', 'Salary from a job', 'Stock dividends', 'Freelance payment for a project'], 'Stock dividends', 'Earned income comes from work. Dividends are investment (unearned) income — you don\'t work for them.', 5),
  ],
  'tracking-spending': [
    mc('What is the best first step to understanding your spending?', ['Cancel all subscriptions', 'Review your bank and credit card statements for 1-3 months', 'Guess based on memory', 'Only track cash purchases'], 'Review your bank and credit card statements for 1-3 months', 'Looking at actual transaction history shows where money really goes, not where you think it goes.', 1),
    mc('Why do most people underestimate their spending?', ['They don\'t have credit cards', 'Small purchases add up invisibly, and memory is inaccurate', 'They earn too much to notice', 'Their bank doesn\'t categorize transactions'], 'Small purchases add up invisibly, and memory is inaccurate', 'Coffee, subscriptions, and small daily purchases seem trivial but accumulate. Most people are surprised when they add them up.', 2),
    mc('Which is the most reliable method for tracking expenses?', ['Mental accounting', 'Automatic categorization through a budgeting app or bank', 'Estimating monthly totals', 'Only tracking expenses over $50'], 'Automatic categorization through a budgeting app or bank', 'Automation captures everything. Mental tracking and selective tracking miss too much.', 3),
    mc('What is a spending audit?', ['An IRS review of your finances', 'A review of where your money has gone over a set period', 'A credit report check', 'A meeting with a financial advisor'], 'A review of where your money has gone over a set period', 'A spending audit categorizes past transactions to reveal patterns, waste, and opportunities to save.', 4),
    mc('What should you do with the information from tracking your spending?', ['Nothing — it\'s just for awareness', 'Compare it to your income and identify areas to cut or redirect', 'Delete it after 30 days', 'Share it with your bank'], 'Compare it to your income and identify areas to cut or redirect', 'Tracking is only useful if you act on it — compare spending to income and make intentional changes.', 5),
  ],
  'fixed-vs-variable-expenses': [
    mc('What is a fixed expense?', ['An expense that changes month to month', 'An expense that stays the same each month', 'A one-time purchase', 'A voluntary expense like entertainment'], 'An expense that stays the same each month', 'Fixed expenses (rent, loan payments, insurance) are predictable — the same amount due each month.', 1),
    mc('Which of the following is a variable expense?', ['Monthly rent', 'Car loan payment', 'Grocery spending', 'Internet subscription'], 'Grocery spending', 'Variable expenses fluctuate — groceries, utilities, gas, and entertainment change month to month.', 2),
    mc('Why is it easier to cut variable expenses than fixed ones?', ['Variable expenses are always optional', 'Fixed expenses require contracts; variable expenses can be reduced immediately', 'Variable expenses are always smaller', 'Fixed expenses don\'t affect your budget'], 'Fixed expenses require contracts; variable expenses can be reduced immediately', 'Fixed expenses often require breaking leases or contracts. Variable expenses can be reduced next time you spend.', 3),
    mc('Discretionary expenses are:', ['Necessary for survival', 'Expenses you choose — wants, not needs', 'Fixed amounts deducted from your paycheck', 'Tax deductions'], 'Expenses you choose — wants, not needs', 'Discretionary spending is optional — dining out, subscriptions, hobbies. Non-discretionary is necessary: rent, food, utilities.', 4),
    mc('Which expense is both periodic AND fixed?', ['Groceries', 'Electricity bill', 'Annual car registration fee', 'Clothing'], 'Annual car registration fee', 'Periodic fixed expenses happen regularly but not monthly — car registration, insurance renewals, annual subscriptions.', 5),
  ],
  'budgeting-methods': [
    mc('What is the purpose of a budget?', ['To restrict spending and make life miserable', 'To give every dollar a purpose and align spending with goals', 'To track spending after the fact', 'To prepare for tax time'], 'To give every dollar a purpose and align spending with goals', 'A budget is a spending plan — it tells your money where to go so you can meet goals instead of wondering where it went.', 1),
    mc('Which budgeting method works by giving every dollar a specific category?', ['Pay-yourself-first', 'Zero-based budgeting', 'Cash envelope system', 'The 50/30/20 rule'], 'Zero-based budgeting', 'Zero-based budgeting allocates every dollar so income minus expenses equals zero. Nothing is "unaccounted for."', 2),
    mc('The envelope method works by:', ['Saving cash in envelopes for emergencies', 'Putting cash in labeled envelopes for each spending category', 'Mailing checks instead of using cards', 'Putting all savings in one envelope'], 'Putting cash in labeled envelopes for each spending category', 'Cash envelopes make spending tangible — when the envelope is empty, you stop spending in that category.', 3),
    mc('What is "pay yourself first"?', ['Spend freely and save whatever is left', 'Automatically transfer savings before paying bills', 'Negotiate better rates with creditors', 'Pay down debt before anything else'], 'Automatically transfer savings before paying bills', 'Pay yourself first moves money to savings the moment you\'re paid — before you can spend it on other things.', 4),
    mc('Which budgeting approach requires the least ongoing effort?', ['Zero-based budgeting', 'Cash envelope system', 'Automated savings with a few tracked categories', 'Detailed daily transaction logging'], 'Automated savings with a few tracked categories', 'Automation does the work — set up auto-transfers and track a few key areas rather than logging every purchase.', 5),
  ],
  'zero-based-budgeting': [
    mc('In zero-based budgeting, "zero" means:', ['You spend all your money', 'Every dollar is assigned a job so income minus outflows equals zero', 'You start with no savings', 'Your checking account hits zero each month'], 'Every dollar is assigned a job so income minus outflows equals zero', 'The goal is zero unallocated dollars — not zero dollars in your account. Savings are an "outflow" category.', 1),
    mc('What should be the first item assigned in a zero-based budget?', ['Entertainment and subscriptions', 'Savings and investment goals', 'Discretionary spending', 'Credit card minimums'], 'Savings and investment goals', 'Treating savings as a fixed expense first ensures you fund your future before spending on wants.', 2),
    mc('What do you do if income minus expenses is positive (surplus) in ZBB?', ['Spend the surplus freely', 'Allocate the surplus to savings, debt, or a goal', 'Stop the budget', 'Give it away'], 'Allocate the surplus to savings, debt, or a goal', 'Every leftover dollar needs a category — push it toward savings, extra debt payments, or a specific goal.', 3),
    mc('What do you do if income minus expenses is negative (deficit) in ZBB?', ['Ignore it', 'Cut expenses in discretionary categories until the budget balances', 'Borrow to cover it', 'Add more income estimates'], 'Cut expenses in discretionary categories until the budget balances', 'If spending exceeds income, reduce spending — especially discretionary items — until the budget balances.', 4),
    mc('How often should you redo a zero-based budget?', ['Once and forget it', 'Monthly or whenever income changes significantly', 'Annually', 'Only when you go into debt'], 'Monthly or whenever income changes significantly', 'ZBB works best when redone monthly — income, bills, and life change, and the budget should reflect reality.', 5),
  ],
  'the-fifty-thirty-twenty-rule': [
    mc('What does the 50/30/20 rule allocate to needs?', ['20%', '30%', '50%', '70%'], '50%', '50% for needs (rent, utilities, food, transport), 30% for wants, 20% for savings/debt.', 1),
    mc('Which category does dining out at restaurants fall under in the 50/30/20 rule?', ['Needs', 'Savings', 'Wants', 'Debt repayment'], 'Wants', 'Dining out is a want — you need food but not restaurant meals. Basic groceries are a need.', 2),
    mc('What does the 20% category cover?', ['Entertainment and hobbies', 'Savings, investments, and extra debt payments', 'Housing and utilities', 'Taxes and withholding'], 'Savings, investments, and extra debt payments', 'The 20% bucket is for building wealth and financial security — emergency fund, retirement, debt payoff.', 3),
    mc('The 50/30/20 rule works best as:', ['An exact rule everyone must follow precisely', 'A flexible starting framework, adjustable to your situation', 'A tax strategy', 'A retirement savings formula'], 'A flexible starting framework, adjustable to your situation', 'It\'s a guideline, not a law. High rent cities may need 60% for needs. Adjust based on your actual circumstances.', 4),
    mc('If you earn $3,000/month net, how much goes to savings/debt under 50/30/20?', ['$500', '$1,000', '$600', '$900'], '$600', '20% of $3,000 = $600 toward savings and debt repayment.', 5),
  ],
  'budgeting-tools': [
    mc('What is the main advantage of budgeting apps over spreadsheets?', ['They are always free', 'They automatically import and categorize transactions', 'They file your taxes automatically', 'They prevent overspending by blocking cards'], 'They automatically import and categorize transactions', 'Apps like YNAB, Mint, or Copilot connect to accounts and categorize spending — eliminating manual entry.', 1),
    mc('What is the primary risk of storing your financial data in a budgeting app?', ['It costs too much', 'Data breaches could expose your financial accounts', 'The app might change categories', 'It takes too long to set up'], 'Data breaches could expose your financial accounts', 'Apps linked to bank accounts hold sensitive data. Use strong passwords, 2FA, and reputable apps.', 2),
    mc('What is a simple, free budgeting tool anyone can use?', ['A dedicated financial advisor', 'A spreadsheet (Excel or Google Sheets)', 'Premium accounting software', 'A tax preparation service'], 'A spreadsheet (Excel or Google Sheets)', 'A spreadsheet costs nothing and gives complete control. Many free templates are available online.', 3),
    mc('Which budgeting app is well-known for the "give every dollar a job" philosophy?', ['Quicken', 'Mint', 'YNAB (You Need A Budget)', 'TurboTax'], 'YNAB (You Need A Budget)', 'YNAB is built around zero-based budgeting — allocating every dollar to a category before spending.', 4),
    mc('What should you do if a budgeting app\'s categories don\'t match your life?', ['Use the app as-is and adapt your spending', 'Customize categories to match your actual spending patterns', 'Abandon the app', 'Round all amounts to even numbers'], 'Customize categories to match your actual spending patterns', 'Good budgeting tools let you create custom categories. Personalized categories make the budget feel real and usable.', 5),
  ],
}
