import type { ExerciseDef } from '../types'

function mc(
  question: string,
  options: string[],
  correctAnswer: string,
  explanation: string,
  order: number
): ExerciseDef {
  return { question, type: 'MULTIPLE_CHOICE', options, correctAnswer, explanation, order }
}

export const financeExercises7: Record<string, ExerciseDef[]> = {
  'renters-and-homeowners': [
    mc('What does renters insurance cover?', ['The physical building you live in', 'Your personal belongings, liability if someone is injured in your unit, and temporary housing if displaced', 'Your landlord\'s property', 'Structural damage to the apartment'], 'Your personal belongings, liability if someone is injured in your unit, and temporary housing if displaced', 'Renters insurance protects tenants — your landlord\'s policy only covers the building, not your stuff.', 1),
    mc('Why is renters insurance one of the best values in insurance?', ['It\'s required by law', 'It typically costs $15-30/month and covers $20,000-$50,000 in belongings and $100,000+ liability', 'It covers everything with no deductible', 'It guarantees replacement at new-item prices'], 'It typically costs $15-30/month and covers $20,000-$50,000 in belongings and $100,000+ liability', 'For roughly the cost of a pizza, renters insurance protects against theft, fire, water damage, and lawsuits.', 2),
    mc('What does homeowners insurance NOT typically cover?', ['Fire damage', 'Theft', 'Flood damage (requires separate flood insurance)', 'Windstorm damage'], 'Flood damage (requires separate flood insurance)', 'Standard homeowners policies exclude floods. Flood insurance is purchased separately through FEMA\'s National Flood Insurance Program.', 3),
    mc('What is "actual cash value" vs "replacement cost value" in insurance?', ['ACV pays more; RCV pays less', 'ACV pays the depreciated value; RCV pays what it costs to replace the item new', 'They are the same for homeowners', 'ACV applies only to homes; RCV applies to renters'], 'ACV pays the depreciated value; RCV pays what it costs to replace the item new', 'ACV: your 5-year-old $1,200 TV might be worth $300 after depreciation. RCV: the insurer pays for a similar new TV.', 4),
    mc('When should you update your homeowners or renters insurance policy?', ['Never — set it and forget it', 'After major purchases, renovations, or life changes that affect the value of covered property', 'Only when premiums increase', 'Every 10 years'], 'After major purchases, renovations, or life changes that affect the value of covered property', 'If you buy jewelry, electronics, or remodel — update your policy. Being underinsured means you absorb the difference in a claim.', 5),
  ],
  'life-insurance': [
    mc('What is the primary purpose of life insurance?', ['To build wealth', 'To replace the financial support you provide if you die — protecting dependents', 'To pay for your funeral only', 'To earn tax-free returns on investments'], 'To replace the financial support you provide if you die — protecting dependents', 'Life insurance protects people who depend on your income — a spouse, children, or anyone who would be financially harmed by your death.', 1),
    mc('What is term life insurance?', ['Coverage for your entire life with a savings component', 'Pure death benefit coverage for a specific term (10, 20, 30 years)', 'Insurance that expires when you retire', 'A government life insurance program'], 'Pure death benefit coverage for a specific term (10, 20, 30 years)', 'Term insurance covers a specific period. It\'s pure insurance with no investment component — simple, affordable, and straightforward.', 2),
    mc('What is whole life insurance?', ['Insurance that covers any cause of death', 'Permanent coverage combining a death benefit with a cash value savings component', 'Life insurance that never requires medical exam', 'The cheapest form of life insurance'], 'Permanent coverage combining a death benefit with a cash value savings component', 'Whole life never expires and builds cash value, but premiums are 5-15x higher than term for the same death benefit.', 3),
    mc('For most families, which life insurance is recommended?', ['Whole life for its investment component', 'Variable universal life', 'Term life — it\'s affordable and covers when protection is most needed', 'No insurance if you\'re healthy'], 'Term life — it\'s affordable and covers when protection is most needed', 'Most financial advisors recommend "buy term and invest the difference." Term is much cheaper; invest savings in index funds.', 4),
    mc('Who most needs life insurance?', ['Young single people with no dependents', 'Retirees with significant savings', 'People with dependents (children, a spouse who relies on their income)', 'Everyone equally regardless of situation'], 'People with dependents (children, a spouse who relies on their income)', 'If no one depends on your income, life insurance is less critical. It\'s essential when others would suffer financially from your death.', 5),
  ],
  'disability-insurance': [
    mc('What does disability insurance replace?', ['Your car if totaled in an accident', 'A portion of your income if you become unable to work due to illness or injury', 'Medical bills during a disability', 'Your life insurance if you become disabled'], 'A portion of your income if you become unable to work due to illness or injury', 'Disability insurance pays 50-70% of your income if you can\'t work — protecting your ability to pay bills without income.', 1),
    mc('Why is disability insurance often overlooked but critically important?', ['It\'s very expensive and unnecessary', 'The odds of disability during working years far exceed death — yet most people lack coverage', 'Social Security covers all disabilities adequately', 'Employer health insurance covers lost wages'], 'The odds of disability during working years far exceed death — yet most people lack coverage', 'You\'re 3-5x more likely to be disabled than to die during your working years. Yet life insurance is prioritized over disability coverage.', 2),
    mc('What is the difference between short-term and long-term disability insurance?', ['Short-term is for injuries; long-term is for illness only', 'Short-term covers weeks to months; long-term covers years or until retirement', 'Short-term pays more; long-term pays less', 'There is no meaningful difference'], 'Short-term covers weeks to months; long-term covers years or until retirement', 'Short-term disability fills the gap before long-term kicks in. Long-term disability coverage is the critical protection.', 3),
    mc('What is an elimination period in disability insurance?', ['The time after which coverage expires', 'The waiting period before benefits start (e.g., 90 days after disability)', 'A period where the insurer can cancel your policy', 'The maximum benefit period'], 'The waiting period before benefits start (e.g., 90 days after disability)', 'Similar to a deductible in time. Longer elimination periods = lower premiums. Your emergency fund covers you during this wait.', 4),
    mc('Does Social Security Disability Insurance (SSDI) fully replace your income?', ['Yes — it replaces 100% of your income', 'No — SSDI is modest, hard to qualify for, and takes months to years to approve', 'Yes, but only for the first year', 'No — SSDI is only for people over 60'], 'No — SSDI is modest, hard to qualify for, and takes months to years to approve', 'SSDI average is ~$1,200-1,500/month and takes 3-5 months to 2+ years to approve. Private disability insurance is essential.', 5),
  ],
  'tax-brackets': [
    mc('The U.S. income tax system is progressive. What does that mean?', ['Everyone pays the same tax rate', 'Higher income is taxed at higher rates', 'Higher income means fewer deductions', 'The government sets progressively lower rates each year'], 'Higher income is taxed at higher rates', 'Progressive taxation applies higher rates to higher income — the more you earn, the higher the rate on amounts above each threshold.', 1),
    mc('If you move into a higher tax bracket, is ALL your income taxed at the new rate?', ['Yes — moving into a higher bracket means all income is taxed at that rate', 'No — only income above the bracket threshold is taxed at the higher rate', 'Yes, but you get a credit for the difference', 'No — tax brackets are irrelevant for most people'], 'No — only income above the bracket threshold is taxed at the higher rate', 'This is the biggest tax misconception. Each bracket applies only to income in that range. Earning $1 more won\'t dramatically raise your tax bill.', 2),
    mc('What is your marginal tax rate?', ['The average rate on all your income', 'The rate you pay on your last dollar of income', 'The rate before deductions', 'The rate set by your state'], 'The rate you pay on your last dollar of income', 'Marginal rate is the rate on the next dollar earned — useful for evaluating whether to earn more or make deductions.', 3),
    mc('What is your effective tax rate?', ['The highest bracket rate you hit', 'Your total tax paid divided by your total income', 'Your marginal rate minus deductions', 'The rate on your salary only'], 'Your total tax paid divided by your total income', 'Effective rate = total tax / total income. It\'s always lower than marginal rate because lower income is taxed at lower rates.', 4),
    mc('In 2024, what is the 0% federal capital gains rate threshold (approximately) for single filers?', ['$10,000', '$47,000', '$100,000', '$200,000'], '$47,000', 'For 2024, single filers with taxable income under ~$47,025 pay 0% on long-term capital gains — a powerful planning tool.', 5),
  ],
  'w2-vs-1099': [
    mc('What is the key difference between a W-2 employee and a 1099 contractor?', ['W-2 employees earn more', 'W-2 employees have taxes withheld and get benefits; 1099 contractors pay their own taxes and typically get no benefits', '1099 contractors get more legal protections', 'W-2 employees can deduct more expenses'], 'W-2 employees have taxes withheld and get benefits; 1099 contractors pay their own taxes and typically get no benefits', 'W-2: employer withholds taxes, pays half of Social Security/Medicare. 1099: you pay all self-employment tax (15.3%) yourself.', 1),
    mc('Self-employment tax (SE tax) for 1099 workers covers:', ['Federal income tax only', 'Social Security and Medicare taxes — the employee AND employer portions', 'State income taxes', 'Business licensing fees'], 'Social Security and Medicare taxes — the employee AND employer portions', 'Employees pay 7.65% SE tax (employer matches). Self-employed pay 15.3% — both halves — on net self-employment income.', 2),
    mc('What is quarterly estimated tax payment?', ['A monthly bank fee', 'Self-employed people\'s required tax deposits to avoid underpayment penalties', 'A refund preview', 'Tax paid only in Q4'], 'Self-employed people\'s required tax deposits to avoid underpayment penalties', 'Since no employer withholds from 1099 income, self-employed must pay estimated taxes quarterly (April, June, September, January).', 3),
    mc('What is a Schedule C?', ['The form for reporting stock gains', 'The IRS form self-employed people use to report business income and deductible expenses', 'A tax filing extension form', 'A W-2 equivalent for contractors'], 'The IRS form self-employed people use to report business income and deductible expenses', 'Schedule C attaches to your 1040 and shows business income minus legitimate business expenses = net profit subject to SE tax.', 4),
    mc('What deduction can self-employed workers take for their SE tax?', ['Deduct 100% of SE tax from income', 'Deduct 50% of SE tax paid from their income (above-the-line)', 'Deduct SE tax only if they itemize', 'There is no SE tax deduction'], 'Deduct 50% of SE tax paid from their income (above-the-line)', 'Self-employed people can deduct half of their SE tax from income — the "employer half" that W-2 employees don\'t have to pay.', 5),
  ],
  'withholding': [
    mc('What is tax withholding?', ['A penalty for underpaying taxes', 'Money deducted from each paycheck and sent to the IRS on your behalf', 'The amount you owe at tax time', 'A savings account at the IRS'], 'Money deducted from each paycheck and sent to the IRS on your behalf', 'Withholding is a pay-as-you-go system — you pre-pay taxes throughout the year based on your W-4 form.', 1),
    mc('Why do many people get a tax refund?', ['The IRS sends bonus payments', 'They had more withheld than they owed — the refund is their own money returned', 'They made too much money', 'Tax refunds are government subsidies'], 'They had more withheld than they owed — the refund is their own money returned', 'A refund means you overpaid during the year — you gave the government an interest-free loan of your own money.', 2),
    mc('Is a large tax refund actually a financial win?', ['Yes — free money from the government', 'No — it means you over-withheld and lost use of your money all year; better to get it in each paycheck', 'Yes — it shows you paid a lot of taxes', 'No — it triggers an audit'], 'No — it means you over-withheld and lost use of your money all year; better to get it in each paycheck', 'A $3,000 refund means you overpaid $250/month. You could have had that $250 each month to invest or use.', 3),
    mc('What form do you use to adjust your withholding at work?', ['Form 1040', 'Schedule C', 'W-4', 'W-2'], 'W-4', 'The W-4 (Employee\'s Withholding Certificate) tells your employer how much to withhold. Update it after major life changes.', 4),
    mc('When might you OWE taxes instead of getting a refund?', ['Never — everyone gets a refund', 'If you had too little withheld — new job, side income, changed withholding, or stopped withholding', 'If you earn too much money', 'If you file late'], 'If you had too little withheld — new job, side income, changed withholding, or stopped withholding', 'Owing taxes at filing means your withholding didn\'t cover what you owed. Adjust your W-4 to avoid a surprise bill next year.', 5),
  ],
  'standard-vs-itemized': [
    mc('What is the standard deduction?', ['A fixed dollar amount that reduces taxable income, requiring no itemization', 'The minimum tax you must pay', 'A deduction only for homeowners', 'A business expense deduction'], 'A fixed dollar amount that reduces taxable income, requiring no itemization', 'For 2024, the standard deduction is $14,600 (single) or $29,200 (married filing jointly) — deducted automatically without itemizing.', 1),
    mc('When should you itemize deductions instead of taking the standard deduction?', ['Always — itemizing gets you more money back', 'When your qualifying itemized deductions exceed the standard deduction amount', 'When you own a business', 'Only when the IRS asks you to'], 'When your qualifying itemized deductions exceed the standard deduction amount', 'Itemize only if your total deductible items (mortgage interest, state taxes, charitable gifts, etc.) exceed the standard deduction.', 2),
    mc('Which expenses can be itemized on Schedule A?', ['Grocery bills and transportation to work', 'Mortgage interest, state/local taxes (up to $10K), charitable contributions, medical expenses exceeding 7.5% of AGI', 'All business expenses', 'Student loan payments'], 'Mortgage interest, state/local taxes (up to $10K), charitable contributions, medical expenses exceeding 7.5% of AGI', 'Schedule A captures specific allowed deductions. Most people can\'t exceed the standard deduction after the 2017 tax law changes.', 3),
    mc('Since 2018, what percentage of taxpayers take the standard deduction?', ['30%', '50%', 'About 90%', '100%'], 'About 90%', 'The 2017 Tax Cuts and Jobs Act nearly doubled the standard deduction — most people now take it rather than itemizing.', 4),
    mc('What is AGI (Adjusted Gross Income)?', ['Your total gross income', 'Gross income minus above-the-line deductions (student loan interest, SE tax, retirement contributions)', 'Your net income after taxes', 'Income reported on your W-2 only'], 'Gross income minus above-the-line deductions (student loan interest, SE tax, retirement contributions)', 'AGI is your total income minus specific "above-the-line" deductions. It determines eligibility for many credits and deductions.', 5),
  ],
}
