import type { ExerciseDef } from '../types'

function mc(
  question: string,
  options: string[],
  correctAnswer: string,
  explanation: string,
  order: number
): ExerciseDef {
  return { question, type: 'MULTIPLE_CHOICE', options, correctAnswer, explanation, order }
}

export const financeExercises9: Record<string, ExerciseDef[]> = {
  'are-you-ready-to-buy': [
    mc('What financial conditions indicate readiness to buy a home?', ['You\'re tired of renting', 'Stable income, good credit score, enough for down payment AND closing costs AND reserves, and a plan to stay 5+ years', 'You have $10,000 saved', 'Your rent equals or exceeds a mortgage payment'], 'Stable income, good credit score, enough for down payment AND closing costs AND reserves, and a plan to stay 5+ years', 'Readiness means: good credit (680+), 5-20% down, 2-5% closing costs, 3-6 month emergency fund remaining AFTER closing, and job stability.', 1),
    mc('What debt-to-income (DTI) ratio do most lenders require?', ['Under 70%', 'Under 20%', 'Under 43-50% (front-end + back-end debt)', 'Under 80%'], 'Under 43-50% (front-end + back-end debt)', 'Most lenders want total monthly debt payments (including the new mortgage) at 43% or less of gross monthly income.', 2),
    mc('Why is having 3-6 months of expenses AFTER the down payment important?', ['Lenders require it', 'To cover unexpected home repairs without going into debt right after buying', 'To make extra mortgage payments', 'To impress the seller'], 'To cover unexpected home repairs without going into debt right after buying', 'New homeowners often face immediate repairs. Draining savings for the down payment and having nothing left is a recipe for debt.', 3),
    mc('What credit score range do most conventional mortgage lenders prefer?', ['500+', '580-619', '620-639', '740+ for best rates; 620 minimum for most loans'], '740+ for best rates; 620 minimum for most loans', 'Conventional loans typically require 620+. FHA loans accept as low as 580 with 3.5% down. Best rates go to 740+.', 4),
    mc('Which is true about buying vs renting financially?', ['Buying is always the better financial decision', 'Buying is better ONLY when done right — wrong timing or overextending can be financially devastating', 'Renting is always better', 'They are exactly equal financially'], 'Buying is better ONLY when done right — wrong timing or overextending can be financially devastating', 'Homeownership builds wealth for prepared buyers with long time horizons. Buying unprepared or in a bad market can destroy wealth.', 5),
  ],
  'how-mortgages-work': [
    mc('What is a mortgage?', ['A home insurance policy', 'A loan secured by real property — the home serves as collateral', 'A rental agreement with purchase option', 'A government housing grant'], 'A loan secured by real property — the home serves as collateral', 'A mortgage is a loan where the lender can foreclose and take the home if you stop making payments.', 1),
    mc('What happens in the first years of a mortgage payment?', ['Most of the payment goes to principal', 'Most of the payment goes to interest — principal paydown is minimal early on', 'Payments are split equally between principal and interest', 'Only interest is paid until year 5'], 'Most of the payment goes to interest — principal paydown is minimal early on', 'Amortization front-loads interest. In year 1 of a 30-year mortgage, 80-90% of each payment may be interest.', 2),
    mc('What is amortization?', ['The process of the home increasing in value', 'The schedule by which loan payments reduce the principal over time', 'The annual property tax calculation', 'A penalty for paying off a mortgage early'], 'The schedule by which loan payments reduce the principal over time', 'Amortization spreads payments over the loan term. Early payments are mostly interest; later payments are mostly principal.', 3),
    mc('What is the principal of a mortgage?', ['The monthly payment amount', 'The original amount borrowed (or remaining balance)', 'The interest charged each month', 'The down payment'], 'The original amount borrowed (or remaining balance)', 'Principal is the loan balance — what you actually owe. Interest is the cost for borrowing. Together they make up your payment (plus escrow).', 4),
    mc('What does making extra principal payments do?', ['Lowers your monthly payment immediately', 'Reduces the loan balance, shortening the loan term and saving interest', 'Increases your equity immediately and lowers interest charged but doesn\'t change monthly payment (typically)', 'Has no effect unless you refinance'], 'Reduces the loan balance, shortening the loan term and saving interest', 'Extra principal payments reduce the balance, so less interest accrues — you pay off faster and save thousands. No monthly payment change.', 5),
  ],
  'mortgage-types': [
    mc('What is a fixed-rate mortgage?', ['A mortgage where the rate changes with the market', 'A mortgage where the interest rate stays the same for the entire loan term', 'A short-term mortgage of 5 years or less', 'A government loan with a capped rate'], 'A mortgage where the interest rate stays the same for the entire loan term', 'Fixed-rate gives certainty — the same payment for 15 or 30 years, regardless of interest rate movements.', 1),
    mc('What is an ARM (adjustable-rate mortgage)?', ['A 15-year fixed mortgage', 'A mortgage with an initial fixed period, then a rate that adjusts periodically with the market', 'A mortgage with no down payment', 'A government-backed refinance program'], 'A mortgage with an initial fixed period, then a rate that adjusts periodically with the market', 'A 5/1 ARM: fixed for 5 years, then adjusts annually. Lower initial rates but unpredictable after the fixed period.', 2),
    mc('When might an ARM make sense?', ['When you plan to stay in the home for 30 years', 'When you plan to sell or refinance before the fixed period ends', 'When interest rates are expected to rise', 'Never — fixed rates are always better'], 'When you plan to sell or refinance before the fixed period ends', 'If you know you\'ll move in 5 years, a 5/1 ARM gives lower initial rates. The risk only materializes if you stay through rate adjustments.', 3),
    mc('What is the difference between a 15-year and 30-year mortgage?', ['15-year mortgages have higher monthly payments but cost much less in total interest', 'They are identical except in name', '30-year mortgages build equity faster', '15-year mortgages are only for people with perfect credit'], '15-year mortgages have higher monthly payments but cost much less in total interest', 'A $300K at 7%: 30-year = ~$2,000/month, $416K total interest. 15-year = ~$2,700/month, $186K total interest. Huge difference.', 4),
    mc('What is a jumbo loan?', ['A loan for mobile homes', 'A loan above conforming limits (~$766,550 in 2024) not eligible for Fannie/Freddie backing', 'Any mortgage over $500,000', 'A government-backed loan for large families'], 'A loan above conforming limits (~$766,550 in 2024) not eligible for Fannie/Freddie backing', 'Jumbo loans exceed conforming limits and can\'t be sold to Fannie Mae or Freddie Mac — they have stricter requirements and often higher rates.', 5),
  ],
  'down-payments-and-pmi': [
    mc('What is the traditional down payment percentage for a conventional mortgage?', ['5%', '10%', '20%', '30%'], '20%', 'The traditional standard is 20% down, which avoids PMI and gets better rates. But many loans accept 3-5%.', 1),
    mc('What is PMI and why do lenders require it?', ['Property Management Insurance — lenders require it for all loans', 'Private Mortgage Insurance — lenders require it when down payment is below 20% to protect against default', 'Pre-Market Insurance — required before listing a home for sale', 'Price Matching Insurance — protects buyers from price increases'], 'Private Mortgage Insurance — lenders require it when down payment is below 20% to protect against default', 'PMI protects the lender (not you) if you default with low equity. Typical cost: 0.5-1.5% of loan/year added to payment.', 2),
    mc('When can you cancel PMI?', ['Never — it\'s permanent', 'When equity reaches 20% of the original purchase price', 'After 5 years regardless of equity', 'After one year of payments'], 'When equity reaches 20% of the original purchase price', 'Under the Homeowners Protection Act, you can request PMI cancellation when equity hits 20%. Lenders must auto-cancel at 22%.', 3),
    mc('What is an FHA loan, and what down payment does it require?', ['A loan from the Federal Housing Authority — 0% down', 'A government-backed loan — down payment as low as 3.5% for 580+ credit scores', 'A loan for federally owned housing — 10% down minimum', 'A grant program requiring no repayment'], 'A government-backed loan — down payment as low as 3.5% for 580+ credit scores', 'FHA loans are backed by the Federal Housing Administration, allowing lower down payments and credit scores — with ongoing MIP (mortgage insurance).', 4),
    mc('A larger down payment provides which advantage?', ['Lower property taxes', 'Lower principal, lower monthly payment, possibly no PMI, and immediate equity', 'Guaranteed appreciation of the home', 'Lower homeowners insurance costs'], 'Lower principal, lower monthly payment, possibly no PMI, and immediate equity', 'More down = smaller loan = lower payments + possibly avoiding PMI + starting with equity. The math always favors more down (when you can).', 5),
  ],
  'getting-approved': [
    mc('What is pre-approval for a mortgage?', ['A guarantee that you will get a mortgage', 'A lender\'s conditional commitment based on income, credit, and asset verification', 'A free service that estimates your mortgage payment', 'The first step of the home search process'], 'A lender\'s conditional commitment based on income, credit, and asset verification', 'Pre-approval requires submitting financial documents. It tells you how much you can borrow and signals seriousness to sellers.', 1),
    mc('What documents do mortgage lenders typically require?', ['Just your ID and pay stub', 'W-2s, tax returns (2 years), pay stubs, bank statements, and employment verification', 'Only your credit report', 'Your lease agreement and utility bills'], 'W-2s, tax returns (2 years), pay stubs, bank statements, and employment verification', 'Lenders verify income stability, assets, and creditworthiness thoroughly — expect to provide 2+ years of financial documentation.', 2),
    mc('What is a debt-to-income ratio (DTI) and what does it measure?', ['Your credit score relative to debt', 'Monthly debt payments divided by gross monthly income — lenders use this to assess affordability', 'The ratio of your home price to your income', 'Total debt divided by total assets'], 'Monthly debt payments divided by gross monthly income — lenders use this to assess affordability', 'DTI = total monthly debt payments / gross monthly income. 43% is typically the max for most mortgages.', 3),
    mc('Why should you avoid major financial changes between pre-approval and closing?', ['Lenders re-verify finances at closing — job changes, new debt, or large purchases can jeopardize approval', 'The IRS monitors mortgage applicants', 'Property values could change', 'Your real estate agent requires stability'], 'Lenders re-verify finances at closing — job changes, new debt, or large purchases can jeopardize approval', 'Lenders pull credit and verify employment again at closing. New car loans, job changes, or large purchases can kill a deal.', 4),
    mc('What is an appraisal in the mortgage process?', ['A home inspection for safety issues', 'An independent estimate of a home\'s market value, required by lenders to confirm the loan amount', 'A review of neighborhood crime statistics', 'A title search to confirm ownership'], 'An independent estimate of a home\'s market value, required by lenders to confirm the loan amount', 'Lenders won\'t loan more than a home is worth. An appraiser independently confirms value to protect the lender\'s collateral.', 5),
  ],
  'finding-a-home': [
    mc('What is a buyer\'s agent?', ['An agent who represents the seller\'s interests', 'A real estate agent who represents and advocates for the buyer', 'A loan officer at your bank', 'An independent home inspector'], 'A real estate agent who represents and advocates for the buyer', 'A buyer\'s agent represents your interests — helping find homes, negotiating price, and guiding through the process. Usually paid by seller.', 1),
    mc('What should you prioritize during home showings?', ['Furniture and decor — they indicate quality', 'Location, structure, layout, size, and major systems — cosmetics can be changed', 'The seller\'s personal belongings', 'The neighborhood\'s social media reviews'], 'Location, structure, layout, size, and major systems — cosmetics can be changed', 'Paint colors change cheaply. Location, lot, foundation, and floorplan cannot. Evaluate what\'s hard to change.', 2),
    mc('What is a comparable sale (comp) in real estate?', ['A similar home listed in another city', 'A recently sold property similar in size, condition, and location, used to estimate fair market value', 'A competing offer on the same property', 'A home for sale at the same price'], 'A recently sold property similar in size, condition, and location, used to estimate fair market value', 'Comps determine what a home is actually worth. Sellers use them to price; buyers use them to make offers; appraisers use them officially.', 3),
    mc('What does "location, location, location" mean in real estate?', ['Buy the most expensive home in the neighborhood', 'Location is the dominant factor in property value — neighborhood, school district, walkability, and proximity matter most', 'Only buy homes near the city center', 'Location matters more than the home condition'], 'Location is the dominant factor in property value — neighborhood, school district, walkability, and proximity matter most', 'You can renovate a house but can\'t change where it is. School districts, safety, and neighborhood trajectory drive long-term value.', 4),
    mc('What is a home inspection and why is it critical?', ['A government certification that the home meets code', 'An independent expert examination of the home\'s structure and systems to identify defects', 'A visual tour conducted by the buyer\'s agent', 'An appraisal of the home\'s market value'], 'An independent expert examination of the home\'s structure and systems to identify defects', 'A home inspection ($300-500) can reveal foundation issues, roof problems, or faulty wiring — potentially saving tens of thousands.', 5),
  ],
  'making-an-offer': [
    mc('What is earnest money?', ['The down payment', 'A good-faith deposit showing you\'re serious about buying — held in escrow until closing', 'The first mortgage payment', 'Money paid to the real estate agent upfront'], 'A good-faith deposit showing you\'re serious about buying — held in escrow until closing', 'Earnest money (typically 1-3% of purchase price) is deposited when your offer is accepted. Applied toward down payment at closing.', 1),
    mc('What is a contingency in a real estate offer?', ['A higher offer price', 'A condition that must be met for the sale to proceed — financing, inspection, or appraisal contingencies', 'A legal penalty for backing out', 'The closing date'], 'A condition that must be met for the sale to proceed — financing, inspection, or appraisal contingencies', 'Contingencies protect the buyer: financing contingency lets you back out if loan falls through; inspection lets you renegotiate if issues found.', 2),
    mc('In a competitive market, what might buyers do to win a bidding war?', ['Offer below asking price', 'Offer over asking price, escalation clauses, shorter inspection periods, or waiving contingencies (risky)', 'Always match the asking price exactly', 'Wait for the market to cool down'], 'Offer over asking price, escalation clauses, shorter inspection periods, or waiving contingencies (risky)', 'Competitive markets may require above-ask offers. Waiving contingencies is risky — weigh the competitiveness against protection lost.', 3),
    mc('What is an escalation clause?', ['A clause allowing the seller to raise the price after acceptance', 'A clause in your offer that automatically increases your bid by a set amount above competing offers, up to a maximum', 'A penalty for backing out of the contract', 'A clause requiring the seller to make repairs'], 'A clause in your offer that automatically increases your bid by a set amount above competing offers, up to a maximum', 'An escalation clause says "I\'ll pay $X above any other offer, up to $Y max" — useful in bidding wars without overpaying blindly.', 4),
    mc('After your offer is accepted, what is the next major step?', ['Move in immediately', 'Open escrow, get the home inspected, and begin the formal loan underwriting process', 'Pay off the full purchase price', 'Notify your current landlord immediately'], 'Open escrow, get the home inspected, and begin the formal loan underwriting process', 'Acceptance opens a contract period where the buyer completes due diligence (inspection, appraisal) and finalizes mortgage approval.', 5),
  ],
}
