import type { ExerciseDef } from '../types'

function mc(
  question: string,
  options: string[],
  correctAnswer: string,
  explanation: string,
  order: number
): ExerciseDef {
  return { question, type: 'MULTIPLE_CHOICE', options, correctAnswer, explanation, order }
}

export const financeExercises6: Record<string, ExerciseDef[]> = {
  'asset-allocation': [
    mc('What is asset allocation?', ['Choosing individual stocks', 'Deciding how to divide your portfolio among different asset classes', 'Picking the best mutual fund', 'Timing the market'], 'Deciding how to divide your portfolio among different asset classes', 'Asset allocation determines what percentage goes to stocks, bonds, real estate, and cash — your biggest long-term decision.', 1),
    mc('The classic rule "110 minus your age in stocks" suggests a 30-year-old should hold:', ['30% stocks', '80% stocks', '110% stocks (impossible)', '30% bonds'], '80% stocks', '110 − 30 = 80% stocks. The rest in bonds. This is a rough guideline that shifts toward safety as you age.', 2),
    mc('Why do bonds become a larger part of a portfolio as you approach retirement?', ['Bonds earn higher returns than stocks', 'Bonds provide stability — you can\'t afford a major market crash near retirement', 'Bonds are tax-free', 'The IRS requires bond-heavy portfolios in retirement accounts'], 'Bonds provide stability — you can\'t afford a major market crash near retirement', 'Near retirement, preserving what you\'ve accumulated matters more than growth. A 50% crash with 2 years to retire is devastating.', 3),
    mc('What is rebalancing?', ['Selling all stocks when the market is high', 'Periodically buying/selling to restore your target asset allocation', 'Adding money to whichever investment is performing best', 'Switching to all bonds annually'], 'Periodically buying/selling to restore your target asset allocation', 'If stocks outperform and grow to 80% when your target is 70%, rebalancing sells some stocks and buys bonds to restore balance.', 4),
    mc('What is the main purpose of asset allocation?', ['To maximize returns at all times', 'To match your portfolio risk to your goals, timeline, and risk tolerance', 'To pick winning investments', 'To pay fewer taxes'], 'To match your portfolio risk to your goals, timeline, and risk tolerance', 'Allocation is personal — your portfolio should reflect when you need the money and how much volatility you can handle.', 5),
  ],
  'starting-with-little': [
    mc('What is the minimum amount needed to start investing?', ['$1,000', '$500', '$5,000', 'As little as $1 with some brokerages and apps'], 'As little as $1 with some brokerages and apps', 'Many modern brokerages (Fidelity, Schwab, M1 Finance) have $0 minimums. Some apps allow fractional shares starting at $1.', 1),
    mc('What is a fractional share?', ['A partial ownership of one share of stock', 'A type of bond that pays partial dividends', 'A discount on stock purchases for small investors', 'A mutual fund for people with little money'], 'A partial ownership of one share of stock', 'Fractional shares let you own a portion of expensive stocks. If Google costs $180/share, you can buy $10 worth.', 2),
    mc('Which account type should most people prioritize first for small investment amounts?', ['A regular taxable brokerage account', 'An employer\'s 401(k), especially if there\'s an employer match', 'A savings account', 'A foreign currency account'], 'An employer\'s 401(k), especially if there\'s an employer match', 'Employer match is free money — 100% return immediately. Always contribute enough to get the full match first.', 3),
    mc('What is dollar-cost averaging?', ['Buying investments when they are cheap', 'Investing a fixed amount at regular intervals regardless of price', 'Converting all money to dollars before investing', 'Timing the market around dollar strength'], 'Investing a fixed amount at regular intervals regardless of price', 'DCA buys more shares when prices are low and fewer when high — smoothing out the impact of market timing over time.', 4),
    mc('If you can only invest $50/month, what should you do?', ['Wait until you can invest $500/month', 'Invest the $50 consistently — time in the market beats timing the market', 'Put it all in one high-risk stock', 'Hold it in cash until you have more'], 'Invest the $50 consistently — time in the market beats timing the market', 'Starting small and consistent beats waiting to invest larger amounts. Compound interest rewards early starters more than large starters.', 5),
  ],
  'what-to-avoid': [
    mc('Why is day trading risky for most investors?', ['Day trading is illegal for individuals', 'Research shows most day traders lose money — they can\'t consistently beat the market', 'Day trading requires $100,000 minimum', 'Day trading returns are taxed at 100%'], 'Research shows most day traders lose money — they can\'t consistently beat the market', 'Studies find 70-80% of day traders lose money. Transaction costs, taxes, and competing with algorithms make it very hard to win.', 1),
    mc('What is a "hot tip" about a stock, and why is it dangerous?', ['Expert analysis from a licensed advisor — always reliable', 'Rumor or speculation about a stock\'s future — usually already priced in or false', 'Government alerts about fraudulent companies', 'Earnings reports from the company itself'], 'Rumor or speculation about a stock\'s future — usually already priced in or false', 'By the time a tip reaches you, insiders have already acted. Acting on tips is often illegal (insider trading) or simply a losing strategy.', 2),
    mc('What is a pump-and-dump scheme?', ['A legitimate market strategy for large investors', 'Fraudsters artificially inflate an asset\'s price then sell, leaving buyers with losses', 'A government program to stabilize asset prices', 'A way to quickly pay off debt'], 'Fraudsters artificially inflate an asset\'s price then sell, leaving buyers with losses', 'Promoters hype a cheap stock (or crypto), the price rises, they sell at the peak, and everyone who bought in loses.', 3),
    mc('What makes cryptocurrency particularly high-risk compared to stocks?', ['Crypto is always going to zero', 'Extreme volatility, no regulatory protection, no underlying earnings, and susceptibility to fraud', 'Crypto charges high transaction fees only', 'Stocks are also very risky — no difference'], 'Extreme volatility, no regulatory protection, no underlying earnings, and susceptibility to fraud', 'Crypto can drop 80% in months. There\'s no regulatory protection, no bankruptcy priority, and it\'s heavily used in scams.', 4),
    mc('What is the most evidence-backed long-term wealth-building investment strategy?', ['Active trading and market timing', 'Consistent, low-cost index fund investing across a diversified portfolio', 'Concentrating in one sector you know well', 'Investing only in bonds for safety'], 'Consistent, low-cost index fund investing across a diversified portfolio', 'Decades of research support: low-cost index funds, diversification, and consistent long-term investing beat almost all alternatives.', 5),
  ],
  'insurance-basics': [
    mc('What is a premium?', ['The maximum amount insurance will pay', 'The regular payment you make to keep your insurance active', 'The amount you pay out-of-pocket before insurance kicks in', 'A bonus payment if you don\'t file claims'], 'The regular payment you make to keep your insurance active', 'The premium is your monthly or annual payment to the insurance company. Miss it and your coverage lapses.', 1),
    mc('What is a deductible?', ['The total maximum your insurance will pay', 'The regular monthly payment for coverage', 'The amount you pay out-of-pocket before insurance starts covering costs', 'A penalty for filing too many claims'], 'The amount you pay out-of-pocket before insurance starts covering costs', 'On a $500 deductible policy: if you have a $1,200 claim, you pay $500, insurance pays $700.', 2),
    mc('What is the relationship between premium and deductible?', ['Higher deductible = higher premium', 'Higher deductible = lower premium (you take on more risk, so insurance costs less)', 'They are unrelated', 'Lower deductible = lower premium'], 'Higher deductible = lower premium (you take on more risk, so insurance costs less)', 'Choosing a higher deductible lowers your monthly premium because you\'re agreeing to absorb more cost before insurance pays.', 3),
    mc('What is an insurance copay?', ['The total cost of an insurance plan', 'A fixed amount you pay each time you use a service (e.g., $30 per doctor visit)', 'Your annual deductible', 'A discount for having multiple policies with one company'], 'A fixed amount you pay each time you use a service (e.g., $30 per doctor visit)', 'Copays are flat fees per service visit — a $30 copay for a primary care visit is separate from your deductible.', 4),
    mc('What is the purpose of insurance?', ['To make money from claims', 'To transfer the financial risk of catastrophic loss to a pool of policyholders', 'To pay for routine expected expenses', 'To replace the need for savings'], 'To transfer the financial risk of catastrophic loss to a pool of policyholders', 'Insurance protects against low-probability, high-cost events — a house fire, major illness, or car accident — by spreading risk.', 5),
  ],
  'why-insurance-matters': [
    mc('What financial event does insurance primarily protect against?', ['Regular monthly expenses', 'Catastrophic, unexpected losses that could wipe out savings', 'Small purchases you\'d rather finance', 'Normal wear and tear on belongings'], 'Catastrophic, unexpected losses that could wipe out savings', 'Insurance is for events that would be financially devastating — a totaled car, major surgery, or a house fire. Not for routine costs.', 1),
    mc('Why is going without health insurance especially risky?', ['Insurance companies will charge you more later', 'A single hospitalization can cost $50,000-$100,000+, destroying savings', 'The IRS requires health insurance', 'Health insurance is always free through employers'], 'A single hospitalization can cost $50,000-$100,000+, destroying savings', 'Medical bills are the leading cause of personal bankruptcy. Even a short hospital stay can cost tens of thousands without insurance.', 2),
    mc('At what life stage is insurance most valuable to obtain?', ['After a major illness or accident (when you need it)', 'Before you need it — when you\'re young and healthy, when premiums are lowest', 'Only in retirement', 'Only when you have dependents'], 'Before you need it — when you\'re young and healthy, when premiums are lowest', 'Insurance companies price based on risk. Young, healthy people pay the least. Getting coverage before health issues is crucial.', 3),
    mc('What is an out-of-pocket maximum?', ['The maximum your monthly premium can reach', 'The ceiling on what you pay in a year — after hitting it, insurance covers 100%', 'The maximum claim you can file', 'The maximum number of claims per year'], 'The ceiling on what you pay in a year — after hitting it, insurance covers 100%', 'After paying your deductible + copays + coinsurance up to the out-of-pocket max, insurance covers 100% of remaining costs.', 4),
    mc('Should you use insurance for every small claim you can file?', ['Yes — that\'s what you\'re paying for', 'No — frequent small claims can raise your premiums and potentially cause cancellation', 'Yes — it reduces your premium', 'No — there\'s a legal limit on claims'], 'No — frequent small claims can raise your premiums and potentially cause cancellation', 'Reserve insurance for significant losses. Small claims can trigger premium increases that cost more over time than just paying out-of-pocket.', 5),
  ],
  'health-insurance': [
    mc('What is a health insurance network?', ['The companies that own a health insurer', 'The group of doctors, hospitals, and providers that contracted with your insurer at negotiated rates', 'The geographic area your insurance covers', 'A list of conditions your insurance will cover'], 'The group of doctors, hospitals, and providers that contracted with your insurer at negotiated rates', 'Staying in-network means using providers who have agreed to rates with your insurer — keeping your costs much lower.', 1),
    mc('What is the difference between an HMO and a PPO?', ['HMOs have lower deductibles; PPOs have lower premiums', 'HMOs require a primary care physician and referrals; PPOs offer more flexibility to see specialists directly', 'HMOs are for families; PPOs are for individuals', 'HMOs cover more procedures than PPOs'], 'HMOs require a primary care physician and referrals; PPOs offer more flexibility to see specialists directly', 'HMOs are typically cheaper but more restrictive. PPOs cost more but allow seeing specialists and out-of-network providers more freely.', 2),
    mc('What is coinsurance?', ['A second insurance policy', 'The percentage of costs you pay after meeting your deductible (e.g., 80/20 means insurer pays 80%, you pay 20%)', 'A copay for prescriptions', 'Monthly premium splits between you and employer'], 'The percentage of costs you pay after meeting your deductible (e.g., 80/20 means insurer pays 80%, you pay 20%)', 'After hitting your deductible, coinsurance splits remaining costs: you pay 20%, insurer pays 80%, until you hit your out-of-pocket max.', 3),
    mc('What is an HSA (Health Savings Account)?', ['A hospital savings account opened at hospitals', 'A tax-advantaged savings account for medical expenses, available with high-deductible health plans', 'A government assistance program for low-income families', 'A savings account specifically for dental expenses'], 'A tax-advantaged savings account for medical expenses, available with high-deductible health plans', 'HSA contributions are pre-tax, grow tax-free, and are withdrawn tax-free for medical expenses. Triple tax advantage.', 4),
    mc('What happens if you receive care from an out-of-network provider?', ['Always the same cost as in-network', 'Your costs are typically much higher — the insurer pays less or nothing', 'Nothing — all providers are covered equally', 'You get a refund for the extra cost'], 'Your costs are typically much higher — the insurer pays less or nothing', 'Out-of-network providers haven\'t agreed to the insurer\'s rates. You could owe the full billed amount or a much higher share.', 5),
  ],
  'auto-insurance': [
    mc('What does liability insurance cover?', ['Damage to your own vehicle', 'Damage or injury you cause to other people or their property in an accident', 'Theft of your vehicle', 'Medical expenses for your own injuries'], 'Damage or injury you cause to other people or their property in an accident', 'Liability is required in most states — it pays for the other person\'s damages when you\'re at fault.', 1),
    mc('What does collision coverage pay for?', ['Damage caused by weather or animals', 'Damage to your car from a collision, regardless of fault', 'Theft of the vehicle', 'Medical bills for passengers'], 'Damage to your car from a collision, regardless of fault', 'Collision covers your car\'s damage in an accident. Comprehensive covers non-collision damage (weather, theft, animals).', 2),
    mc('What is uninsured motorist coverage?', ['Coverage for drivers who don\'t own a car', 'Coverage that pays your damages when hit by a driver with no insurance', 'Coverage for international driving', 'Coverage for commercial vehicles'], 'Coverage that pays your damages when hit by a driver with no insurance', 'About 12% of U.S. drivers are uninsured. This coverage protects you when the at-fault driver can\'t pay.', 3),
    mc('For an older car with low value, which coverage may not be worth the premium?', ['Liability insurance', 'Uninsured motorist coverage', 'Collision and comprehensive coverage', 'State-required minimum coverage'], 'Collision and comprehensive coverage', 'If your car is worth $2,000 and collision costs $400/year with a $500 deductible, the max payout is $1,500 — possibly not worth it.', 4),
    mc('What factors most affect your auto insurance premium?', ['The color of your car', 'Driving record, age, location, coverage level, and vehicle type', 'How often you wash your car', 'The number of cars on your block'], 'Driving record, age, location, coverage level, and vehicle type', 'Accidents and tickets raise rates dramatically. Young drivers pay more. Urban areas cost more. Coverage level is directly controllable.', 5),
  ],
}
