import type { ExerciseDef } from '../types'

function mc(
  question: string,
  options: string[],
  correctAnswer: string,
  explanation: string,
  order: number
): ExerciseDef {
  return { question, type: 'MULTIPLE_CHOICE', options, correctAnswer, explanation, order }
}

export const financeExercises4: Record<string, ExerciseDef[]> = {
  'checking-vs-savings': [
    mc('What is the primary purpose of a checking account?', ['Long-term saving', 'Daily transactions — paying bills, making purchases, receiving income', 'Earning high interest', 'Storing emergency funds'], 'Daily transactions — paying bills, making purchases, receiving income', 'Checking accounts are transactional — designed for frequent deposits and withdrawals, bill pay, and debit card use.', 1),
    mc('Which account typically earns higher interest?', ['Checking account', 'They earn the same', 'Savings account', 'Both earn no interest'], 'Savings account', 'Savings accounts are designed for storing money and earn more interest. Checking earns little or nothing.', 2),
    mc('What is the purpose of having both a checking AND savings account?', ['To confuse your bank', 'Checking handles daily spending; savings earns interest and protects money from impulse spending', 'Required by law', 'To maximize overdraft opportunities'], 'Checking handles daily spending; savings earns interest and protects money from impulse spending', 'The separation creates a functional and psychological divide — spending money stays accessible; savings stays protected.', 3),
    mc('What is a credit union?', ['A government-run bank', 'A for-profit lending company', 'A member-owned financial cooperative, often with better rates than banks', 'A type of credit card company'], 'A member-owned financial cooperative, often with better rates than banks', 'Credit unions are nonprofits owned by members. They typically offer higher savings rates, lower loan rates, and fewer fees.', 4),
    mc('What should you look for in a checking account to minimize costs?', ['The highest credit limit', 'No monthly maintenance fees, no minimum balance requirements, free ATM access', 'The most branches in your city', 'Highest overdraft limit'], 'No monthly maintenance fees, no minimum balance requirements, free ATM access', 'Many banks charge $10-15/month in fees. Online banks and credit unions often offer free checking with nationwide ATM access.', 5),
  ],
  'how-banks-make-money': [
    mc('What is the primary way banks make money?', ['ATM fees', 'The spread between what they pay depositors and what they charge borrowers', 'Credit card annual fees', 'Safe deposit box rentals'], 'The spread between what they pay depositors and what they charge borrowers', 'Banks pay 0.5% on savings deposits, then lend that money out at 6-7% for mortgages. The difference (net interest margin) is profit.', 1),
    mc('What is an overdraft fee?', ['A fee for making too many withdrawals', 'A penalty when your account goes negative from a purchase or withdrawal', 'A fee for having a savings account', 'A monthly maintenance charge'], 'A penalty when your account goes negative from a purchase or withdrawal', 'Overdraft fees are $25-35 per incident — banks make billions from them annually. Opt out of overdraft protection to avoid them.', 2),
    mc('How do banks earn money from credit cards?', ['From the interest they pay depositors', 'Interest on carried balances, late fees, interchange fees from merchants, and annual fees', 'From federal government subsidies', 'From the card\'s chip technology'], 'Interest on carried balances, late fees, interchange fees from merchants, and annual fees', 'Banks earn multiple revenue streams from cards — the highest is interest from cardholders who carry balances.', 3),
    mc('Why do online banks often offer better savings rates than traditional banks?', ['They take more risk', 'They have no physical branches, dramatically reducing overhead costs', 'They are less regulated', 'The government subsidizes them'], 'They have no physical branches, dramatically reducing overhead costs', 'No branch network means lower costs — online banks can pass savings to customers via higher deposit rates.', 4),
    mc('What is interchange?', ['The interest rate on loans', 'A fee merchants pay to accept card payments, shared between the card network and your bank', 'The fee for wire transfers', 'The annual fee for a card'], 'A fee merchants pay to accept card payments, shared between the card network and your bank', 'Every card swipe, the merchant pays ~1.5-2.5%. This funds cash back rewards and bank profits.', 5),
  ],
  'choosing-a-bank': [
    mc('What factor matters most when choosing where to bank?', ['The size of the bank', 'Fees, interest rates, ATM access, and customer service for your needs', 'Whether the bank has a sports sponsorship', 'How old the bank is'], 'Fees, interest rates, ATM access, and customer service for your needs', 'The best bank is the one that costs you least and serves your actual habits — branch access if you use branches; online if you\'re digital.', 1),
    mc('When is a credit union a better choice than a major bank?', ['When you want the most ATM locations', 'When you want lower loan rates, fewer fees, and better savings rates on smaller account balances', 'When you travel internationally frequently', 'When you need 24/7 phone support'], 'When you want lower loan rates, fewer fees, and better savings rates on smaller account balances', 'Credit unions return profits to members — typically better for everyday banking, auto loans, and personal loans.', 2),
    mc('What is a key advantage of an online bank over a traditional bank?', ['In-person teller assistance', 'Higher savings rates and lower or no monthly fees', 'More loan options', 'Guaranteed FDIC insurance only for online banks'], 'Higher savings rates and lower or no monthly fees', 'Online banks\' low overhead means better rates for savings accounts and fewer fees — typically 10-20x better savings rates.', 3),
    mc('What should you check before switching banks?', ['Whether the bank\'s CEO went to a good school', 'All automatic payments and deposits linked to the old account', 'The number of Instagram followers the bank has', 'Whether they have a physical location in another country'], 'All automatic payments and deposits linked to the old account', 'Before closing an old account, update all direct deposits and autopay connections — missing even one can cause missed payments.', 4),
    mc('Is FDIC insurance important when choosing a bank?', ['No — all financial institutions are safe', 'Yes — FDIC insures deposits up to $250,000 per ownership category if the bank fails', 'Only if you have over $1 million', 'Only for savings accounts, not checking'], 'Yes — FDIC insures deposits up to $250,000 per ownership category if the bank fails', 'FDIC insurance protects your deposits if the bank fails. Always verify your bank is FDIC-insured.', 5),
  ],
  'cds-and-money-market': [
    mc('What is a certificate of deposit (CD)?', ['A type of credit card', 'A savings account where you lock money for a fixed term in exchange for a higher rate', 'A government bond', 'A check from your employer'], 'A savings account where you lock money for a fixed term in exchange for a higher rate', 'CDs offer higher interest than regular savings in exchange for leaving the money untouched for a specified term (3 months to 5 years).', 1),
    mc('What happens if you withdraw money from a CD before it matures?', ['Nothing — withdrawal is always free', 'You pay an early withdrawal penalty, often 3-6 months of interest', 'The bank keeps all the money', 'Your credit score drops'], 'You pay an early withdrawal penalty, often 3-6 months of interest', 'CDs penalize early withdrawal — make sure you won\'t need the money during the term before opening one.', 2),
    mc('What is a money market account?', ['An account for investing in the stock market', 'A high-yield savings account with check-writing privileges and higher minimum balances', 'A short-term government bond fund', 'A retirement savings vehicle'], 'A high-yield savings account with check-writing privileges and higher minimum balances', 'Money market accounts earn more than regular savings and often allow limited check-writing. They typically require higher minimums.', 3),
    mc('When is a CD ladder a useful strategy?', ['When you want to maximize stock market returns', 'When you want steady access to maturing funds while still earning higher CD rates', 'When you have no savings', 'When you expect interest rates to fall'], 'When you want steady access to maturing funds while still earning higher CD rates', 'A CD ladder staggers maturity dates (e.g., 1-, 2-, 3-year CDs) so you always have a CD maturing soon without locking everything up.', 4),
    mc('When interest rates are rising, which CD strategy is best?', ['Open one long-term CD immediately to lock in the current rate', 'Use shorter terms or a CD ladder so you can reinvest at higher rates as they mature', 'Avoid CDs entirely', 'Open money market accounts instead'], 'Use shorter terms or a CD ladder so you can reinvest at higher rates as they mature', 'In a rising rate environment, locking into a long-term CD at today\'s rate means missing higher rates later. Short terms or ladders adapt.', 5),
  ],
  'interest-rates': [
    mc('What is an interest rate?', ['The penalty for late payment', 'The percentage of a principal that is charged or earned over a period', 'The fee for having a bank account', 'A tax on savings'], 'The percentage of a principal that is charged or earned over a period', 'Interest rates determine how much extra you pay on debt or earn on savings — expressed as a percentage per year (APR or APY).', 1),
    mc('What is the difference between APR and APY?', ['APR is for savings; APY is for loans', 'APR is the rate before compounding; APY reflects the effect of compounding (actual return/cost)', 'They are the same thing', 'APY is always lower than APR'], 'APR is the rate before compounding; APY reflects the effect of compounding (actual return/cost)', 'APY (annual percentage yield) accounts for compounding frequency. For savings, compare APY. For loans, compare APR.', 2),
    mc('How does the Federal Reserve\'s interest rate affect consumer borrowing?', ['No effect — consumer rates are set independently', 'When the Fed raises rates, borrowing costs for mortgages, auto loans, and credit cards typically rise', 'Higher Fed rates always lower mortgage rates', 'Only affects government bonds'], 'When the Fed raises rates, borrowing costs for mortgages, auto loans, and credit cards typically rise', 'The Fed funds rate is a benchmark. When it rises, banks raise their lending rates — making borrowing more expensive for consumers.', 3),
    mc('What is compound interest?', ['Interest calculated only on the original principal', 'Interest earned on both the principal and previously accumulated interest', 'A flat fee charged monthly', 'Interest charged only once per year'], 'Interest earned on both the principal and previously accumulated interest', 'Compounding makes interest grow exponentially. Einstein allegedly called it the eighth wonder of the world.', 4),
    mc('If you invest $1,000 at 5% annual interest compounded yearly, how much do you have after 2 years?', ['$1,100', '$1,050', '$1,102.50', '$1,010'], '$1,102.50', 'Year 1: $1,000 × 1.05 = $1,050. Year 2: $1,050 × 1.05 = $1,102.50.', 5),
  ],
  'fdic-insurance': [
    mc('What does FDIC insurance protect?', ['Your investments in stocks and mutual funds', 'Your deposits at FDIC-insured banks up to $250,000 per ownership category', 'Your money if you\'re robbed', 'Your retirement account from market losses'], 'Your deposits at FDIC-insured banks up to $250,000 per ownership category', 'FDIC insures checking, savings, CDs, and money market accounts — not investments — if the bank fails.', 1),
    mc('What is the FDIC insurance limit per depositor, per institution?', ['$100,000', '$500,000', '$250,000', 'Unlimited'], '$250,000', 'FDIC insures up to $250,000 per depositor, per bank, per ownership category. Multiple account types can expand coverage.', 2),
    mc('Are investments held at a bank (stocks, bonds, mutual funds) FDIC insured?', ['Yes — the bank covers all financial products', 'No — FDIC only covers deposit accounts, not investments', 'Yes, up to $100,000', 'Only if the bank also fails'], 'No — FDIC only covers deposit accounts, not investments', 'FDIC covers deposit accounts only. Investment products (even sold through a bank) can lose value and are NOT FDIC insured.', 3),
    mc('If a bank fails while your account is insured, what happens to your money?', ['You lose up to 10%', 'The FDIC ensures you get your money back up to the insured limit, usually within a few days', 'You must file a claim that takes years', 'You automatically get transferred to another bank with no loss'], 'The FDIC ensures you get your money back up to the insured limit, usually within a few days', 'FDIC bank failures are handled quickly — insured deposits are returned within days, often the next business day.', 4),
    mc('What is NCUA insurance?', ['Insurance for money market funds', 'The equivalent of FDIC for federally insured credit unions', 'A type of CD insurance', 'Coverage for online-only banks'], 'The equivalent of FDIC for federally insured credit unions', 'NCUA (National Credit Union Administration) provides the same protection as FDIC but for credit union deposits.', 5),
  ],
  'inflation-and-purchasing-power': [
    mc('What is inflation?', ['A rise in investment returns', 'The general increase in prices over time, reducing what money can buy', 'The process of printing money', 'A temporary price spike in one product'], 'The general increase in prices over time, reducing what money can buy', 'Inflation erodes purchasing power — $100 today buys less than $100 did 10 years ago.', 1),
    mc('At 3% annual inflation, how many years does it take for prices to roughly double?', ['10 years', '24 years', '50 years', '33 years'], '24 years', 'Use the Rule of 72: 72 / 3 = 24 years. Prices double every 24 years at 3% inflation.', 2),
    mc('Why is leaving all money in a savings account at 0.5% a risk when inflation is 3%?', ['Banks charge fees on savings accounts', 'Your money loses real purchasing power — it grows slower than prices rise', 'Savings accounts close after a period of inactivity', 'The government taxes savings interest at 100%'], 'Your money loses real purchasing power — it grows slower than prices rise', 'Real return = interest rate − inflation. 0.5% − 3% = −2.5%. You lose purchasing power even if the dollar balance grows.', 3),
    mc('What is the "real" interest rate?', ['The rate printed on a savings account', 'The nominal interest rate minus the inflation rate', 'The rate after taxes', 'The highest interest rate available'], 'The nominal interest rate minus the inflation rate', 'Real interest rate = nominal rate − inflation. It measures actual purchasing power growth.', 4),
    mc('What is the primary reason to invest rather than just save?', ['Investing is risk-free', 'Investments historically outpace inflation, growing real purchasing power over time', 'Banks charge fees on savings', 'You can\'t access savings in emergencies'], 'Investments historically outpace inflation, growing real purchasing power over time', 'Savings accounts lag inflation. The stock market has historically returned ~7% real (after inflation) annually over the long term.', 5),
  ],
}
