import type { ExerciseDef } from '../types'

function mc(
  question: string,
  options: string[],
  correctAnswer: string,
  explanation: string,
  order: number
): ExerciseDef {
  return { question, type: 'MULTIPLE_CHOICE', options, correctAnswer, explanation, order }
}

export const financeExercises2: Record<string, ExerciseDef[]> = {
  'why-emergency-funds-matter': [
    mc('What is an emergency fund?', ['Money saved for vacations', 'Liquid savings set aside for unexpected expenses', 'A low-interest credit card', 'An insurance policy'], 'Liquid savings set aside for unexpected expenses', 'An emergency fund is readily accessible cash for genuine emergencies — job loss, medical bills, car repairs.', 1),
    mc('Why is an emergency fund critical before paying off debt?', ['It isn\'t — pay debt first', 'A small emergency fund prevents you from adding new debt when something unexpected happens', 'Emergency funds earn more interest than debt costs', 'Lenders require them'], 'A small emergency fund prevents you from adding new debt when something unexpected happens', 'Without a cushion, any emergency forces you back onto credit cards. Even $1,000 stops the debt cycle.', 2),
    mc('Where should an emergency fund be kept?', ['Invested in stocks for growth', 'In a high-yield savings account — accessible but separate from checking', 'In a retirement account', 'Under your mattress'], 'In a high-yield savings account — accessible but separate from checking', 'The fund needs to be safe, liquid (quickly accessible), and separate enough that you won\'t accidentally spend it.', 3),
    mc('What qualifies as a true emergency?', ['Concert tickets you forgot to budget for', 'Car breakdown that stops you from getting to work', 'A holiday you want to take', 'A sale on clothes'], 'Car breakdown that stops you from getting to work', 'True emergencies are unexpected, necessary, and urgent. Planned events and wants are not emergencies.', 4),
    mc('What is the psychological benefit of having an emergency fund?', ['It makes you feel richer', 'It eliminates financial stress by providing security against the unexpected', 'It improves your credit score', 'It earns high interest'], 'It eliminates financial stress by providing security against the unexpected', 'Knowing you can handle a $1,000 surprise dramatically reduces anxiety. Financial stress is a major quality-of-life drain.', 5),
  ],
  'how-much-to-save': [
    mc('The general recommendation for a fully funded emergency fund is:', ['1 week of expenses', '1 month of expenses', '3-6 months of living expenses', '1 year of income'], '3-6 months of living expenses', 'Most experts recommend 3-6 months of essential expenses. Higher if income is variable or job is unstable.', 1),
    mc('Who needs a larger emergency fund — more than 6 months?', ['Salaried employees with stable jobs', 'People with variable income, single-income households, or health issues', 'People with no debt', 'People who own their cars outright'], 'People with variable income, single-income households, or health issues', 'The more uncertain your income or greater your risk of large unexpected expenses, the larger the fund should be.', 2),
    mc('To calculate your emergency fund target, you should add up:', ['Your monthly income', 'Your monthly essential expenses (rent, food, utilities, transport, minimum payments)', 'Your annual salary divided by 12', 'Your net worth'], 'Your monthly essential expenses (rent, food, utilities, transport, minimum payments)', 'Emergency fund targets are based on what you NEED to survive, not your full lifestyle spending.', 3),
    mc('Is a $500 emergency fund better than nothing?', ['No — save more or don\'t bother', 'Yes — even a small fund handles many common emergencies', 'Only if invested', 'No — you need at least $2,000 first'], 'Yes — even a small fund handles many common emergencies', 'Start where you are. $500-$1,000 handles the majority of real emergencies. Build from there.', 4),
    mc('Why do some people suggest starting with a $1,000 emergency fund before aggressively paying debt?', ['$1,000 earns enough interest to make debt worth keeping', 'A $1,000 buffer stops most small emergencies from becoming new credit card debt', 'Lenders require $1,000 in savings', 'It matches the standard insurance deductible'], 'A $1,000 buffer stops most small emergencies from becoming new credit card debt', 'Dave Ramsey popularized this: $1,000 catches most car and household emergencies, breaking the debt cycle.', 5),
  ],
  'building-the-fund': [
    mc('What is the most effective way to build an emergency fund quickly?', ['Wait for a raise', 'Automate a transfer from each paycheck to a separate savings account', 'Only save when you have leftover money', 'Use a credit card and pay it off each month'], 'Automate a transfer from each paycheck to a separate savings account', 'Automation removes the decision — money moves before you spend it. Consistency builds the fund faster than willpower.', 1),
    mc('If money is extremely tight, which approach helps most?', ['Give up — you can\'t save when broke', 'Find small amounts to cut (subscriptions, eating out) and redirect even $20-$50/month', 'Take out a personal loan to fund the emergency fund', 'Use a side hustle to fund it entirely before budgeting'], 'Find small amounts to cut (subscriptions, eating out) and redirect even $20-$50/month', 'Small consistent amounts compound over time. Canceling one unused subscription might fund $15/month toward safety.', 2),
    mc('Once your emergency fund is fully funded, what should you do with the monthly contribution you were making?', ['Stop saving and spend more', 'Redirect it to investing, debt payoff, or another financial goal', 'Keep adding to emergency fund indefinitely', 'Put it in a checking account'], 'Redirect it to investing, debt payoff, or another financial goal', 'Once funded, redirect that savings habit toward the next goal — debt elimination or investing for the future.', 3),
    mc('Which type of savings account is best for an emergency fund?', ['Checking account (for easy access)', 'A high-yield savings account at an online bank', 'A stock investment account', 'A CD (certificate of deposit)'], 'A high-yield savings account at an online bank', 'Online HYSAs earn much more than traditional banks and are still liquid. CDs have withdrawal penalties; stocks can crash.', 4),
    mc('Why is keeping the emergency fund separate from your checking account important?', ['Banks charge fees if they\'re in the same account', 'It prevents accidentally spending emergency savings on everyday purchases', 'The IRS requires separate accounts', 'Interest rates are higher in separate accounts'], 'It prevents accidentally spending emergency savings on everyday purchases', 'Out of sight, out of mind. Keeping it separate creates a mental barrier that protects the fund.', 5),
  ],
  'what-is-credit': [
    mc('What is credit?', ['Free money from a bank', 'The ability to borrow money with a promise to repay it later', 'Money you\'ve already earned', 'A government benefit program'], 'The ability to borrow money with a promise to repay it later', 'Credit lets you use money now and repay it over time — typically with interest.', 1),
    mc('Why does credit matter even if you avoid debt?', ['It doesn\'t matter', 'Good credit is required to rent apartments, get jobs, and qualify for insurance', 'Credit scores only matter for mortgages', 'Only businesses need credit'], 'Good credit is required to rent apartments, get jobs, and qualify for insurance', 'Landlords, employers, and insurance companies check credit. Poor credit can block housing, work, and raise costs.', 2),
    mc('What organization collects and maintains credit data?', ['The IRS', 'Your bank', 'Credit bureaus (Equifax, Experian, TransUnion)', 'The Federal Reserve'], 'Credit bureaus (Equifax, Experian, TransUnion)', 'The three major bureaus collect data from lenders and compile credit reports used to calculate your score.', 3),
    mc('What is the difference between a credit report and a credit score?', ['They are the same thing', 'A credit report is detailed account history; a score is a number derived from it', 'A score is your payment history; a report is your income', 'Reports are free; scores cost money'], 'A credit report is detailed account history; a score is a number derived from it', 'Your report is the raw data (accounts, payments, balances). Your score (FICO, VantageScore) is a number calculated from it.', 4),
    mc('How often can you get a free credit report from each bureau?', ['Once every 5 years', 'Once a year (weekly during some periods)', 'Monthly for a fee', 'Only when applying for credit'], 'Once a year (weekly during some periods)', 'AnnualCreditReport.com provides free reports from all three bureaus. During COVID, weekly access was added and extended.', 5),
  ],
  'how-credit-scores-work': [
    mc('What is the FICO score range?', ['0-100', '300-850', '1-1000', '500-900'], '300-850', 'FICO scores range from 300 (very poor) to 850 (exceptional). Above 700 is generally good.', 1),
    mc('What is the largest factor in calculating a FICO score?', ['Amount of debt owed', 'Length of credit history', 'Payment history', 'Types of credit used'], 'Payment history', 'Payment history is 35% of your FICO score — the biggest factor. Paying on time consistently is the single most important thing.', 2),
    mc('What is credit utilization, and how does it affect your score?', ['How often you apply for credit; high utilization lowers score', 'The percentage of available credit you\'re using; high utilization lowers score', 'Your total credit limit; more limits help your score', 'The types of credit accounts you have'], 'The percentage of available credit you\'re using; high utilization lowers score', 'Utilization = balances / credit limits. Keep it under 30% — ideally under 10%. It\'s 30% of your FICO score.', 3),
    mc('How does applying for several new credit cards quickly affect your score?', ['It helps by increasing available credit', 'It temporarily lowers it due to multiple hard inquiries', 'It has no effect', 'It improves payment history'], 'It temporarily lowers it due to multiple hard inquiries', 'Each application triggers a hard inquiry. Multiple hard inquiries in a short window signal financial stress to lenders.', 4),
    mc('What score is generally considered "good" for loan approvals at competitive rates?', ['Below 580', '580-620', '670 and above', '500-550'], '670 and above', 'Most lenders consider 670+ good. 740+ is very good and typically unlocks the best interest rates.', 5),
  ],
  'credit-reports': [
    mc('What information appears on a credit report?', ['Your bank account balances', 'Your income and assets', 'Account history, payment records, balances, and public records', 'Your employment history'], 'Account history, payment records, balances, and public records', 'Credit reports show: open/closed accounts, payment history, balances, hard inquiries, and public records (bankruptcies, judgments).', 1),
    mc('How long do most negative items stay on your credit report?', ['1 year', '3 years', '7 years', '10 years'], '7 years', 'Most negative items (late payments, collections, charge-offs) remain 7 years. Bankruptcies stay up to 10 years.', 2),
    mc('What should you do if you find an error on your credit report?', ['Ignore it — bureaus fix errors automatically', 'Dispute it in writing with the credit bureau', 'Pay it off even if it\'s wrong', 'Contact the IRS'], 'Dispute it in writing with the credit bureau', 'You have the right to dispute inaccurate information. The bureau must investigate and correct errors within 30 days.', 3),
    mc('What is a charge-off on a credit report?', ['An account you closed yourself', 'When a creditor writes off your debt as a loss after you stop paying', 'A zero-balance paid account', 'A credit limit increase'], 'When a creditor writes off your debt as a loss after you stop paying', 'A charge-off means the creditor gave up expecting payment — it\'s very negative on your report. The debt still exists.', 4),
    mc('Where can you get free access to all three credit reports annually?', ['Your bank\'s website', 'The credit bureau websites directly (for a fee)', 'AnnualCreditReport.com', 'The IRS website'], 'AnnualCreditReport.com', 'This is the official, federally mandated free credit report site — the only truly free source for all three bureaus.', 5),
  ],
  'building-credit-from-zero': [
    mc('What is the best first step to build credit with no history?', ['Apply for a regular unsecured credit card', 'Open a secured credit card and pay it in full monthly', 'Take out a personal loan', 'Ask someone to add you as an authorized user on their account (if trustworthy)'], 'Open a secured credit card and pay it in full monthly', 'A secured card requires a deposit as collateral — it\'s designed for building credit. Pay the full balance monthly to avoid interest.', 1),
    mc('What is a credit-builder loan?', ['A loan to pay off other debts', 'A loan where payments are reported to bureaus, building credit history as you save', 'A payday loan with lower interest', 'A loan from a friend or family member'], 'A loan where payments are reported to bureaus, building credit history as you save', 'Credit-builder loans (often from credit unions) hold the money in escrow — you make payments, build history, then get the funds.', 2),
    mc('How does being an authorized user on someone else\'s account build your credit?', ['It doesn\'t — only your own accounts count', 'The account\'s history appears on your report, even though you\'re not the primary cardholder', 'You get a separate card in your name', 'You inherit their credit score directly'], 'The account\'s history appears on your report, even though you\'re not the primary cardholder', 'If the primary cardholder has good history, being added as an authorized user can boost your thin credit file.', 3),
    mc('How long does it generally take to see a significant credit score after starting from no history?', ['1-2 weeks', '6-12 months', '5 years', 'Immediately'], '6-12 months', 'FICO requires at least 6 months of history. Building a good score typically takes 6-12 months of consistent responsible use.', 4),
    mc('What is the most important thing to do once you have a credit card to build credit?', ['Carry a balance to show you use it', 'Pay the statement balance in full every month, on time', 'Use it as little as possible', 'Only use it for emergencies'], 'Pay the statement balance in full every month, on time', 'On-time payment is the biggest credit factor. Paying in full avoids interest. Carrying a balance does NOT help your score.', 5),
  ],
}
