import type { ExerciseDef } from '../types'

function mc(
  question: string,
  options: string[],
  correctAnswer: string,
  explanation: string,
  order: number
): ExerciseDef {
  return { question, type: 'MULTIPLE_CHOICE', options, correctAnswer, explanation, order }
}

export const financeExercises10: Record<string, ExerciseDef[]> = {
  'closing-costs': [
    mc('What are closing costs?', ['The final mortgage payment', 'Fees and expenses paid at closing — typically 2-5% of the purchase price', 'The cost to list a home for sale', 'Prepaid property taxes only'], 'Fees and expenses paid at closing — typically 2-5% of the purchase price', 'Closing costs include loan origination, title insurance, appraisal, prepaid taxes/insurance, and attorney fees — typically $6,000-15,000.', 1),
    mc('What is title insurance and why is it required?', ['Insurance against the home\'s price declining', 'Insurance protecting against prior claims, liens, or title defects that could affect ownership', 'Insurance for the home\'s contents', 'A type of homeowners insurance'], 'Insurance protecting against prior claims, liens, or title defects that could affect ownership', 'Title insurance is a one-time fee protecting against ownership disputes — someone claiming a prior lien or fraud in the chain of title.', 2),
    mc('Can closing costs be negotiated or reduced?', ['No — they are fixed by law', 'Yes — you can shop lenders for lower fees, ask the seller to pay some costs, or roll some into the loan', 'Only if you use a specific lender', 'Only on new construction'], 'Yes — you can shop lenders for lower fees, ask the seller to pay some costs, or roll some into the loan', 'Seller concessions can cover buyer closing costs. Shopping multiple lenders can reduce origination fees. Compare Loan Estimates carefully.', 3),
    mc('What is an escrow account for a mortgage?', ['A savings account for your down payment', 'An account managed by the lender to pay property taxes and insurance from your monthly payment', 'A retirement savings account', 'Money held by your real estate agent'], 'An account managed by the lender to pay property taxes and insurance from your monthly payment', 'Lenders collect 1/12 of annual property taxes and insurance each month. Escrow ensures these are paid, protecting their collateral.', 4),
    mc('What is a Loan Estimate?', ['A pre-approval letter from a lender', 'A standardized 3-page form lenders must provide within 3 days of application, showing loan costs', 'An estimate of your home\'s value', 'A document listing comparable home sales'], 'A standardized 3-page form lenders must provide within 3 days of application, showing loan costs', 'The Loan Estimate (LE) shows interest rate, monthly payment, and all closing costs — use it to compare multiple lenders side by side.', 5),
  ],
  'the-time-value-of-starting-early': [
    mc('Why does starting retirement savings at 25 vs 35 make such a dramatic difference?', ['Younger investors get special government benefits', 'Compound interest has 10 more years to multiply — early money grows exponentially', 'Tax rates are lower for younger workers', 'Employer matches are larger for younger employees'], 'Compound interest has 10 more years to multiply — early money grows exponentially', '$5,000 invested at 25 at 7% grows to ~$75,000 by 65. The same $5,000 invested at 35 grows to ~$38,000. Ten years doubles the outcome.', 1),
    mc('If you invest $200/month starting at age 25 at 7% return, how does this compare to $400/month starting at 45?', ['$400/month wins since the amount is double', '$200/month wins since compound interest on early money dominates', 'They end up about equal', 'It depends entirely on market performance'], '$200/month wins since compound interest on early money dominates', 'Time beats amount. $200/month for 40 years at 7% ≈ $525,000. $400/month for 20 years ≈ $208,000. Starting early wins decisively.', 2),
    mc('What is the "latte factor" concept in personal finance?', ['Coffee is the most important budget item', 'Small daily expenses (like a $5 coffee) compound into significant missed investment growth over decades', 'Lifestyle spending has no real impact on retirement', 'You should never enjoy small luxuries'], 'Small daily expenses (like a $5 coffee) compound into significant missed investment growth over decades', '$5/day = $1,825/year. Invested at 7% for 30 years = ~$174,000. Small daily habits have enormous long-term opportunity costs.', 3),
    mc('What is the concept of "time in the market beats timing the market"?', ['You should invest when prices are lowest only', 'Consistently investing for a long time outperforms trying to predict price movements', 'Market timing is illegal', 'Time of day matters for stock purchases'], 'Consistently investing for a long time outperforms trying to predict price movements', 'Missing just the 10 best days in the market over 20 years dramatically cuts returns. Staying invested consistently outperforms timing.', 4),
    mc('What is the "catch-up contribution" rule for retirement accounts?', ['The ability to make up missed contributions from previous years', 'People over 50 can contribute extra to 401(k)s and IRAs each year', 'Making a larger first contribution to make up for starting late', 'Borrowing from your 401(k) to fund earlier years'], 'People over 50 can contribute extra to 401(k)s and IRAs each year', 'The IRS allows "catch-up" contributions for those 50+ to save more in 401(k)s ($7,500 extra) and IRAs ($1,000 extra) annually.', 5),
  ],
  'how-much-do-you-need': [
    mc('What is the 4% rule in retirement planning?', ['Save 4% of income each year for retirement', 'You can withdraw 4% of your portfolio annually and it should last 30 years', 'Invest only in 4% interest accounts', 'Your portfolio must earn 4% or more annually'], 'You can withdraw 4% of your portfolio annually and it should last 30 years', 'The 4% rule (from the Trinity Study) suggests a 4% annual withdrawal from a balanced portfolio has a high probability of lasting 30 years.', 1),
    mc('Using the 4% rule, if you need $50,000/year in retirement, how much do you need saved?', ['$500,000', '$1,000,000', '$1,250,000', '$2,000,000'], '$1,250,000', '$50,000 / 0.04 = $1,250,000. To generate $50K/year at 4% withdrawal, you need $1.25M.', 2),
    mc('What factor most affects how much you need to retire?', ['Your age when you retire', 'Your expected spending in retirement', 'The state you retire in', 'Whether you own your home'], 'Your expected spending in retirement', 'The more you plan to spend, the more you need. Reducing retirement spending needs cuts the required portfolio significantly.', 3),
    mc('How does Social Security factor into retirement income planning?', ['Ignore it — it won\'t exist by the time you retire', 'It provides a base income but typically replaces only 30-40% of pre-retirement income for average earners', 'It fully replaces all retirement income needs', 'It only applies to people who worked for government'], 'It provides a base income but typically replaces only 30-40% of pre-retirement income for average earners', 'Social Security supplements retirement but rarely covers everything. Plan for the gap between SS income and your spending needs.', 4),
    mc('Why does healthcare cost more heavily in retirement planning calculations?', ['Medicare covers everything after 65', 'Healthcare costs are the largest and most unpredictable retirement expense, averaging $315,000+ for a couple', 'Retirees are healthier than workers on average', 'Health insurance is free after retirement'], 'Healthcare costs are the largest and most unpredictable retirement expense, averaging $315,000+ for a couple', 'Fidelity estimates a 65-year-old couple needs $315,000+ for healthcare in retirement — a major budget item not covered by Medicare alone.', 5),
  ],
  'social-security-reality': [
    mc('What is Social Security?', ['A private retirement account', 'A government program providing retirement, disability, and survivor benefits funded by payroll taxes', 'A guaranteed investment return program', 'A savings account the government holds for you'], 'A government program providing retirement, disability, and survivor benefits funded by payroll taxes', 'Social Security is a pay-as-you-go program — current workers pay taxes that fund benefits for current retirees.', 1),
    mc('At what age can you begin collecting Social Security retirement benefits?', ['55', '60', '62 (early, reduced benefits)', '70 (you must wait until 70)'], '62 (early, reduced benefits)', 'You can begin at 62 but receive permanently reduced benefits. Full retirement age is 66-67. Waiting until 70 maximizes your monthly benefit.', 2),
    mc('What is the benefit of delaying Social Security until age 70?', ['No benefit — start as early as possible', 'Your monthly benefit increases by ~8% per year delayed past full retirement age, up to age 70', 'You receive a lump-sum payment instead', 'Medicare starts automatically'], 'Your monthly benefit increases by ~8% per year delayed past full retirement age, up to age 70', 'Delaying from 67 to 70 = 24% more monthly income for life. If you live long, waiting significantly increases lifetime benefits.', 3),
    mc('Should you rely on Social Security as your primary retirement income source?', ['Yes — it\'s designed to fully replace your income', 'No — it typically replaces 30-40% of average earner income; personal savings are essential', 'Yes, especially if you start collecting early', 'No — Social Security will be eliminated by the time most people retire'], 'No — it typically replaces 30-40% of average earner income; personal savings are essential', 'Social Security was designed as a supplement, not a complete solution. Plan for personal savings to cover the rest.', 4),
    mc('What happens to Social Security benefits for spouses?', ['Spouses get nothing from Social Security', 'A spouse can claim up to 50% of the other\'s benefit, whichever is higher than their own', 'Both spouses receive separate full benefits regardless of work history', 'Spouses must both reach 70 to collect'], 'A spouse can claim up to 50% of the other\'s benefit, whichever is higher than their own', 'A spouse with limited work history can claim a spousal benefit (up to 50% of their partner\'s full benefit) — giving them meaningful income.', 5),
  ],
  '401k-basics': [
    mc('What is a 401(k)?', ['A government pension plan', 'An employer-sponsored retirement savings plan funded with pre-tax or after-tax (Roth) contributions', 'A type of IRA for high earners', 'A savings account with a 401% bonus from the employer'], 'An employer-sponsored retirement savings plan funded with pre-tax or after-tax (Roth) contributions', '401(k) plans are offered by employers. Traditional contributions reduce taxable income now; Roth 401(k) is after-tax with tax-free withdrawals.', 1),
    mc('What is an employer match in a 401(k)?', ['The employer managing your investments', 'Free money — the employer contributes a percentage matching your contributions, up to a limit', 'The maximum you can contribute annually', 'The investment options your employer selects'], 'Free money — the employer contributes a percentage matching your contributions, up to a limit', 'A 3% match on a $60,000 salary = $1,800/year free. Not contributing enough to get the full match means leaving free money on the table.', 2),
    mc('What is the 2024 401(k) contribution limit (employee contribution)?', ['$7,000', '$13,500', '$23,000', '$66,000'], '$23,000', 'The 2024 employee 401(k) contribution limit is $23,000 ($30,500 for those 50+ with catch-up contributions).', 3),
    mc('What happens if you withdraw from a 401(k) before age 59½?', ['Nothing — withdrawals are always allowed', 'You pay income tax plus a 10% early withdrawal penalty', 'You lose only the employer match', 'Withdrawals are penalty-free if for education'], 'You pay income tax plus a 10% early withdrawal penalty', 'Early 401(k) withdrawals are costly: income taxes plus 10% penalty. Exception: Roth contributions (not earnings) can be taken out of Roth 401(k).', 4),
    mc('What is vesting in employer 401(k) matching?', ['The time before you can contribute to a 401(k)', 'The schedule by which employer match contributions become fully yours — you may have to stay X years to keep the match', 'The investment choices available in your plan', 'The annual review of your contribution percentage'], 'The schedule by which employer match contributions become fully yours — you may have to stay X years to keep the match', 'Employer matches may vest over 3-6 years. Leaving before full vesting means losing some or all of the employer\'s contributions.', 5),
  ],
  'ira-basics': [
    mc('What is an IRA?', ['An employer-sponsored retirement account', 'An Individual Retirement Account — a personal retirement savings account with tax advantages', 'A government pension supplement', 'A savings account with no contribution limits'], 'An Individual Retirement Account — a personal retirement savings account with tax advantages', 'IRAs are opened by individuals (not through employers). Traditional IRAs offer pre-tax growth; Roth IRAs offer tax-free growth.', 1),
    mc('What is the 2024 IRA contribution limit?', ['$7,000 ($8,000 if 50+)', '$14,000 per spouse', '$23,000', '$6,500'], '$7,000 ($8,000 if 50+)', 'The 2024 IRA limit is $7,000/year ($8,000 if age 50+). This applies across all your IRAs combined.', 2),
    mc('When is a Roth IRA typically better than a Traditional IRA?', ['When you\'re in a high tax bracket now', 'When you expect to be in a higher tax bracket in retirement — pay taxes now, withdraw tax-free later', 'When you want to reduce taxes today', 'When you earn too much for a Roth'], 'When you expect to be in a higher tax bracket in retirement — pay taxes now, withdraw tax-free later', 'Roth is ideal for young/low-income earners who expect higher future income. You pay a low rate now to get tax-free growth.', 3),
    mc('What is the Roth IRA income limit (for 2024, single filers)?', ['There is no income limit', 'Phase out begins at $146,000; ineligible above $161,000', 'Phase out at $200,000', 'Only available below $75,000 income'], 'Phase out begins at $146,000; ineligible above $161,000', 'High earners lose Roth IRA eligibility. A backdoor Roth IRA is a legal workaround for those above the income limit.', 4),
    mc('What is a rollover in retirement accounts?', ['Moving money between banks for better rates', 'Transferring funds from one retirement account to another without tax penalties', 'Withdrawing money and re-depositing it', 'The automatic reinvestment of dividends'], 'Transferring funds from one retirement account to another without tax penalties', 'When changing jobs, rolling a 401(k) into an IRA preserves tax-deferred status. Done correctly, there\'s no tax or penalty.', 5),
  ],
  'self-employed-retirement': [
    mc('What is a SEP-IRA?', ['A retirement account only for seniors', 'A Simplified Employee Pension IRA — a generous retirement account for self-employed people', 'A type of Roth IRA for freelancers', 'A small employer pension program requiring employees'], 'A Simplified Employee Pension IRA — a generous retirement account for self-employed people', 'SEP-IRAs allow contributions up to 25% of net self-employment income or $69,000 (2024) — far more than a regular IRA.', 1),
    mc('What is a Solo 401(k) (also called individual 401k)?', ['A 401(k) plan for companies with fewer than 50 employees', 'A retirement plan for self-employed with no employees — allowing both employee and employer contributions', 'A government plan for sole proprietors', 'An IRA with a higher contribution limit for freelancers'], 'A retirement plan for self-employed with no employees — allowing both employee and employer contributions', 'Solo 401(k) allows self-employed to contribute as both "employee" ($23,000) AND "employer" (25% of income) — potentially $69,000 total in 2024.', 2),
    mc('What is a SIMPLE IRA?', ['A basic IRA with lower contribution limits', 'A retirement plan for small businesses with up to 100 employees, with mandatory employer contributions', 'An IRA with no investment options', 'A government-managed retirement fund'], 'A retirement plan for small businesses with up to 100 employees, with mandatory employer contributions', 'SIMPLE IRAs require employers to either match employee contributions (up to 3%) or make a fixed 2% contribution for all eligible employees.', 3),
    mc('Why do self-employed people especially need to prioritize retirement savings?', ['They are legally required to', 'They have no employer pension or automatic payroll deductions — they must create their own retirement system', 'Self-employment income is taxed less, allowing more savings', 'Banks offer better rates for self-employed retirement accounts'], 'They have no employer pension or automatic payroll deductions — they must create their own retirement system', 'No employer match, no automatic withholding, no pension. Self-employed must be intentional and disciplined to build retirement security.', 4),
    mc('Which self-employed retirement account allows the highest contributions?', ['Traditional IRA', 'SEP-IRA or Solo 401(k) — both can approach $69,000 in 2024', 'SIMPLE IRA', 'Roth IRA only'], 'SEP-IRA or Solo 401(k) — both can approach $69,000 in 2024', 'Both SEP-IRA and Solo 401(k) allow dramatically more than a regular IRA ($7,000). Solo 401(k) also allows Roth contributions.', 5),
  ],
  'withdrawal-rules': [
    mc('At what age can you begin withdrawing from Traditional IRAs and 401(k)s penalty-free?', ['55', '62', '59½', '65'], '59½', 'Before 59½, withdrawals trigger a 10% early withdrawal penalty plus income taxes. After 59½, only taxes apply.', 1),
    mc('What is a Required Minimum Distribution (RMD)?', ['The minimum you must contribute annually', 'The government-required annual withdrawal from traditional retirement accounts starting at age 73', 'A mandatory distribution to beneficiaries', 'The minimum balance required to avoid fees'], 'The government-required annual withdrawal from traditional retirement accounts starting at age 73', 'The IRS requires RMDs from Traditional IRAs and 401(k)s starting at 73 (as of 2023 SECURE 2.0 Act) to collect taxes on deferred income.', 2),
    mc('Do Roth IRAs have Required Minimum Distributions?', ['Yes — starting at age 73 like traditional accounts', 'No — Roth IRAs have no RMDs during the owner\'s lifetime', 'Yes, but only for large balances', 'Only if the account is over 30 years old'], 'No — Roth IRAs have no RMDs during the owner\'s lifetime', 'Roth IRAs don\'t require withdrawals during your lifetime — a key estate planning advantage. The money keeps growing tax-free.', 3),
    mc('What is a 72(t) distribution?', ['An automatic distribution at age 72', 'Substantially equal periodic payments that allow early withdrawal without the 10% penalty', 'The RMD calculation formula', 'A distribution type only for Roth accounts'], 'Substantially equal periodic payments that allow early withdrawal without the 10% penalty', '72(t) allows early retirement account access without the 10% penalty, by taking "substantially equal periodic payments" for at least 5 years.', 4),
    mc('What happens to a retirement account when the owner dies?', ['The account is seized by the government', 'It passes to named beneficiaries, who have their own distribution rules (typically 10-year rule for non-spouses)', 'It must be immediately distributed and taxed', 'It transfers to the next of kin without taxes'], 'It passes to named beneficiaries, who have their own distribution rules (typically 10-year rule for non-spouses)', 'Beneficiaries inherit retirement accounts. Non-spouse beneficiaries generally must withdraw all funds within 10 years (SECURE Act 2019).', 5),
  ],
}
