import type { ExerciseDef } from '../types'

function mc(
  question: string,
  options: string[],
  correctAnswer: string,
  explanation: string,
  order: number
): ExerciseDef {
  return { question, type: 'MULTIPLE_CHOICE', options, correctAnswer, explanation, order }
}

export const financeExercises5: Record<string, ExerciseDef[]> = {
  'compound-interest': [
    mc('What makes compound interest different from simple interest?', ['Compound interest uses lower rates', 'Compound interest earns interest on accumulated interest, not just principal', 'Simple interest is for investments; compound is for loans', 'They are the same'], 'Compound interest earns interest on accumulated interest, not just principal', 'Simple interest: principal × rate × time. Compound: interest snowballs because each period\'s interest becomes part of the next period\'s principal.', 1),
    mc('If $1,000 earns 10% simple interest for 3 years, the total is:', ['$1,300', '$1,331', '$1,100', '$1,000'], '$1,300', 'Simple interest: $1,000 × 10% × 3 = $300 interest. Total = $1,300.', 2),
    mc('If $1,000 earns 10% compound interest annually for 3 years, the total is:', ['$1,300', '$1,100', '$1,331', '$1,000'], '$1,331', 'Year 1: $1,100. Year 2: $1,210. Year 3: $1,331. Compound earns $31 more than simple.', 3),
    mc('What does the Rule of 72 tell you?', ['How much to save for retirement', 'How many years to double money: 72 / interest rate', 'The maximum interest rate on a credit card', 'When to start investing'], 'How many years to double money: 72 / interest rate', '72 / interest rate ≈ years to double. At 8%: 72/8 = 9 years. A quick mental math rule.', 4),
    mc('Why does starting to invest at 25 vs 35 make such a large difference?', ['Younger investors get better rates', 'Compound interest has 10 more years to snowball — earlier money has exponentially more time to grow', 'Tax laws favor younger investors', 'Market returns are higher for young investors'], 'Compound interest has 10 more years to snowball — earlier money has exponentially more time to grow', 'Money invested at 25 might grow 8x by retirement; the same money invested at 35 might grow only 4x. Time is the key variable.', 5),
  ],
  'risk-and-return': [
    mc('What is the general relationship between risk and return in investing?', ['Higher risk, lower return', 'Higher risk, higher potential return', 'Risk and return are unrelated', 'All investments have the same risk'], 'Higher risk, higher potential return', 'Investors demand higher potential returns to compensate for taking on greater risk. No risk, no reward — but also no loss.', 1),
    mc('Which investment typically has the highest long-term return potential AND the highest risk?', ['U.S. Treasury bonds', 'Savings accounts', 'Stocks', 'CDs'], 'Stocks', 'Stocks offer the highest historical long-term returns (~10% nominal annually) but can lose 30-50% in a crash.', 2),
    mc('What is volatility in investing?', ['The amount of money you invest', 'The tendency for prices to fluctuate up and down', 'A measure of how long an investment lasts', 'The annual fee on an investment account'], 'The tendency for prices to fluctuate up and down', 'Volatility measures price swings. High-volatility investments (stocks) move dramatically; low-volatility (bonds) are more stable.', 3),
    mc('Why is time horizon important in risk tolerance?', ['Older investors pay fewer taxes', 'Longer time horizons allow more risk-taking because there\'s time to recover from losses', 'Shorter time horizons mean higher returns', 'Time horizons don\'t affect investment choices'], 'Longer time horizons allow more risk-taking because there\'s time to recover from losses', 'If retirement is 30 years away, short-term market crashes matter less — you have time to recover. Near retirement: preservation matters.', 4),
    mc('What does it mean to "lose money" in stocks?', ['Your dividends decrease', 'The market value of your shares falls below what you paid for them', 'You must pay a penalty for holding shares too long', 'Your brokerage charges extra fees'], 'The market value of your shares falls below what you paid for them', 'Stocks fluctuate. If you buy at $50 and the price drops to $30, you\'ve lost $20/share in market value — though it\'s unrealized until you sell.', 5),
  ],
  'stocks-basics': [
    mc('What is a stock?', ['A guaranteed investment return from a company', 'A unit of ownership in a company', 'A type of savings account', 'A government-issued bond'], 'A unit of ownership in a company', 'A share of stock represents partial ownership. If a company has 1 million shares and you own 1,000, you own 0.1% of the company.', 1),
    mc('How do investors make money from stocks?', ['The company pays them a guaranteed salary', 'Through price appreciation and/or dividends', 'Through interest paid by the company monthly', 'Through insurance payouts if the stock falls'], 'Through price appreciation and/or dividends', 'Stocks earn returns two ways: the price rising (capital gains) and dividends (periodic cash distributions from company profits).', 2),
    mc('What is a dividend?', ['The fee to buy a stock', 'A periodic payment companies make to shareholders from profits', 'The difference between buying and selling price', 'A type of stock option'], 'A periodic payment companies make to shareholders from profits', 'Dividends are cash payments from company profits to shareholders — not all stocks pay them, but income-focused stocks often do.', 3),
    mc('What is market capitalization?', ['The maximum amount you can invest in a company', 'The total value of a company\'s outstanding shares (share price × total shares)', 'The company\'s annual revenue', 'The stock exchange where a company trades'], 'The total value of a company\'s outstanding shares (share price × total shares)', 'Market cap = price × shares outstanding. Apple at $3T market cap means all its shares are worth $3 trillion total.', 4),
    mc('Where are stocks bought and sold?', ['Only through the company directly', 'At stock exchanges like NYSE or NASDAQ, via brokers', 'At banks during business hours only', 'Through the government'], 'At stock exchanges like NYSE or NASDAQ, via brokers', 'Stock exchanges are marketplaces where buyers and sellers transact. You access them through a brokerage account.', 5),
  ],
  'bonds-basics': [
    mc('What is a bond?', ['A type of stock with fixed dividends', 'A loan made to a government or corporation that pays regular interest', 'A savings account with a guaranteed return', 'A mutual fund that only holds stocks'], 'A loan made to a government or corporation that pays regular interest', 'When you buy a bond, you lend money to the issuer. They promise to pay you interest (coupon) and return the principal at maturity.', 1),
    mc('Which is generally safer: stocks or bonds?', ['Stocks — higher return means safer', 'Bonds — they offer predictable income and priority in bankruptcy', 'They are equally risky', 'Neither is safe — avoid both'], 'Bonds — they offer predictable income and priority in bankruptcy', 'Bonds are senior to stocks in bankruptcy and pay fixed income. Less upside, but more stability — especially government bonds.', 2),
    mc('What happens to bond prices when interest rates rise?', ['Bond prices rise', 'Bond prices fall', 'Bond prices are unaffected', 'Bond yields fall'], 'Bond prices fall', 'Bond prices and interest rates move inversely. New bonds at higher rates make existing lower-rate bonds less valuable.', 3),
    mc('What is a government bond?', ['A bond issued by corporations', 'A debt security issued by a government — considered among the safest investments', 'A guaranteed return of 10% annually', 'A bond backed by property'], 'A debt security issued by a government — considered among the safest investments', 'U.S. Treasury bonds are considered risk-free (for credit risk). They pay lower rates but have virtually no default risk.', 4),
    mc('What is credit risk in bonds?', ['The risk that interest rates change', 'The risk that the bond issuer defaults (fails to pay interest or principal)', 'The risk of inflation eroding returns', 'The risk of losing principal in a stock market crash'], 'The risk that the bond issuer defaults (fails to pay interest or principal)', 'Credit risk: will the borrower pay you back? Government bonds have near-zero credit risk; junk bonds have high default risk.', 5),
  ],
  'index-funds-and-etfs': [
    mc('What is an index fund?', ['A fund managed by expert stock pickers', 'A fund that tracks a market index like the S&P 500, holding all its stocks', 'A fund investing only in government bonds', 'A savings account linked to stock performance'], 'A fund that tracks a market index like the S&P 500, holding all its stocks', 'Index funds passively hold all (or representative) stocks in an index — like owning all 500 S&P 500 companies at once.', 1),
    mc('What is the main advantage of index funds over actively managed funds?', ['Index funds beat the market every year', 'Index funds have dramatically lower fees, and most active managers underperform indexes long-term', 'Index funds are FDIC insured', 'Index funds never lose money'], 'Index funds have dramatically lower fees, and most active managers underperform indexes long-term', 'Active fund expense ratios average ~0.5-1%; index funds average 0.03-0.1%. Over 20 years, this fee difference is enormous.', 2),
    mc('What is an ETF (exchange-traded fund)?', ['A savings account that trades like a stock', 'A fund that trades on an exchange throughout the day, like a stock', 'A certificate of deposit held at a bank', 'A type of bond fund'], 'A fund that trades on an exchange throughout the day, like a stock', 'ETFs are similar to index funds but trade on exchanges throughout the day at market prices, rather than end-of-day like mutual funds.', 3),
    mc('The S&P 500 index fund invests in:', ['The 500 safest bonds in America', 'The 500 largest U.S. publicly traded companies', 'International stocks only', '500 randomly selected small companies'], 'The 500 largest U.S. publicly traded companies', 'The S&P 500 represents the 500 largest U.S. companies by market cap — about 80% of U.S. stock market value.', 4),
    mc('What is an expense ratio?', ['The return an index fund generates', 'The annual fee charged as a percentage of assets under management', 'The brokerage commission on trades', 'The tax rate on fund distributions'], 'The annual fee charged as a percentage of assets under management', 'Expense ratio = annual fee as % of your investment. 0.03% on $10,000 = $3/year. 1% = $100/year. Compound this over decades.', 5),
  ],
  'mutual-funds': [
    mc('What is a mutual fund?', ['A type of savings account', 'A pooled investment vehicle where many investors combine money managed by a professional', 'A government retirement account', 'A bond issued by a municipality'], 'A pooled investment vehicle where many investors combine money managed by a professional', 'Mutual funds pool money from thousands of investors, managed by a fund manager who buys a portfolio of stocks, bonds, or both.', 1),
    mc('What is the key difference between a mutual fund and an ETF?', ['Mutual funds invest in stocks; ETFs invest in bonds', 'Mutual funds are priced once daily at NAV; ETFs trade throughout the day like stocks', 'ETFs require more capital to start', 'Mutual funds are always actively managed'], 'Mutual funds are priced once daily at NAV; ETFs trade throughout the day like stocks', 'Mutual funds settle at the day\'s net asset value (NAV). ETFs trade in real time on exchanges — more flexible but can create temptation to trade.', 2),
    mc('What does "load" mean in mutual funds?', ['The total assets in the fund', 'A sales commission — either upfront (front load) or at sale (back load)', 'The minimum investment required', 'The fund\'s annual operating expenses'], 'A sales commission — either upfront (front load) or at sale (back load)', 'Load funds charge a sales commission (1-5%) that goes to the broker. No-load funds have no commission — generally preferable.', 3),
    mc('What is a target-date fund?', ['A fund with a guaranteed return by the target year', 'An all-in-one fund that automatically becomes more conservative as the target retirement year approaches', 'A fund only for people within 5 years of retirement', 'A fund that sells all holdings on a specific date'], 'An all-in-one fund that automatically becomes more conservative as the target retirement year approaches', 'Target-date funds hold a mix of stocks and bonds that shifts toward bonds as you age — "set it and forget it" investing.', 4),
    mc('When do actively managed mutual funds beat index funds?', ['Consistently over the long term', 'Only in specific years — most underperform indexes after fees over 15+ years', 'Always in international markets', 'During all bear markets'], 'Only in specific years — most underperform indexes after fees over 15+ years', 'S&P SPIVA reports consistently show 80-90%+ of actively managed funds underperform their benchmarks over 15 years.', 5),
  ],
  'diversification': [
    mc('What is diversification?', ['Putting all money in one great investment', 'Spreading investments across different assets to reduce risk', 'Owning only international stocks', 'Keeping all money in cash'], 'Spreading investments across different assets to reduce risk', 'Diversification means not putting all eggs in one basket — spreading across stocks, bonds, sectors, and geographies.', 1),
    mc('Why doesn\'t diversification eliminate all investment risk?', ['Because diversification is a myth', 'Because some risks (market crashes) affect all investments — this is systematic risk', 'Because only 10 stocks can\'t be diversified', 'Because fees absorb all gains'], 'Because some risks (market crashes) affect all investments — this is systematic risk', 'Diversification eliminates company-specific risk but not market-wide risk. When the whole market crashes, diversified portfolios still fall.', 2),
    mc('Which is more diversified: owning 20 tech stocks or owning one S&P 500 index fund?', ['20 tech stocks — more companies', 'One S&P 500 fund — 500 companies across all sectors', 'They are equally diversified', 'Neither is diversified enough'], 'One S&P 500 fund — 500 companies across all sectors', '500 companies across all sectors is far more diversified than 20 companies in one sector with correlated risks.', 3),
    mc('What is correlation in investing?', ['The return on an investment', 'How similarly two assets tend to move — low correlation means they offset each other', 'The interest rate on bonds', 'The fee structure of a fund'], 'How similarly two assets tend to move — low correlation means they offset each other', 'Diversification works best when assets are uncorrelated — when stocks fall, bonds often rise, smoothing returns.', 4),
    mc('Which portfolio is best diversified?', ['100% US large-cap stocks', '100% bonds', 'Mix of US stocks, international stocks, bonds, and real estate', '50% cash, 50% gold'], 'Mix of US stocks, international stocks, bonds, and real estate', 'True diversification spans asset classes (stocks/bonds), geographies (US/international), and sectors — not just many stocks.', 5),
  ],
}
