import type { ExerciseDef } from '../types'

function mc(
  question: string,
  options: string[],
  correctAnswer: string,
  explanation: string,
  order: number,
): ExerciseDef {
  return { question, type: 'MULTIPLE_CHOICE', options, correctAnswer, explanation, order }
}

export const healthExercises7: Record<string, ExerciseDef[]> = {
  'anxiety-and-depression': [
    mc('Generalized Anxiety Disorder (GAD) is characterized by:', ['Intense fear of a specific object or situation', 'Sudden unexpected surges of intense fear with physical symptoms', 'Persistent, excessive worry about multiple life areas present most days', 'Anxiety that arises only in social situations'], 'Persistent, excessive worry about multiple life areas present most days', 'GAD involves chronic, difficult-to-control worry across many domains — work, health, money, family — accompanied by physical symptoms like muscle tension, restlessness, and sleep problems. This is a near-constant anxious state, not occasional worry.', 1),
    mc('Depression is most accurately described as:', ['Feeling sad in response to a difficult life event', 'Choosing not to engage with life out of weakness', 'A pervasive condition causing persistent low mood or loss of pleasure affecting thinking, physical function, and behavior', 'A temporary mood state that resolves on its own within days'], 'A pervasive condition causing persistent low mood or loss of pleasure affecting thinking, physical function, and behavior', 'Depression is far more than sadness. People often describe it as numbness or inability to feel pleasure (anhedonia). It affects cognition, energy, sleep, appetite, and the ability to perform basic functions. It is a biological condition, not a choice.', 2),
    mc('SSRIs are first-line medications for:', ['Psychotic disorders only', 'Both anxiety disorders and depression', 'Bipolar disorder and schizophrenia', 'Insomnia and chronic pain'], 'Both anxiety disorders and depression', 'SSRIs are the most commonly prescribed medications for both anxiety disorders and depression. They increase serotonin availability in synapses and typically take 4–6 weeks to show full effect. They are often combined with psychotherapy for better outcomes.', 3),
    mc('CBT is considered the most evidence-based psychotherapy for anxiety and depression because it:', ['Focuses exclusively on childhood experiences', 'Provides medication as part of an integrated package', 'Identifies and changes unhelpful thought patterns and behaviors that maintain symptoms', 'Relies solely on relaxation techniques'], 'Identifies and changes unhelpful thought patterns and behaviors that maintain symptoms', 'CBT is present-focused and skills-based. It works by identifying distorted thinking (catastrophizing, negative self-talk) and maladaptive behaviors (avoidance) that perpetuate anxiety and depression, then teaching skills to change them. It has strong evidence across many conditions.', 4),
    mc('Which statement about panic attacks is accurate?', ['They are caused by actual cardiac events requiring emergency evaluation', 'They involve sudden intense fear with physical symptoms often mistaken for a heart attack', 'They only occur in people who have experienced significant trauma', 'They last several hours and are proportional to real danger'], 'They involve sudden intense fear with physical symptoms often mistaken for a heart attack', 'Panic attacks are sudden surges of intense fear with physical symptoms — racing heart, chest pain, sweating, shortness of breath — that can convincingly resemble a heart attack. They peak within minutes and are not medically dangerous.', 5),
  ],

  'trauma-and-stress': [
    mc('Which system does stress primarily activate?', ['The parasympathetic nervous system and digestive system', 'The hypothalamic-pituitary-adrenal (HPA) axis and sympathetic nervous system', 'The endocrine system and reproductive hormones exclusively', 'The immune system, causing immediate inflammation'], 'The hypothalamic-pituitary-adrenal (HPA) axis and sympathetic nervous system', 'Stress activates the HPA axis (releasing cortisol) and the sympathetic nervous system (releasing adrenaline). Together these increase heart rate and blood pressure, raise blood glucose, slow digestion, and sharpen attention — a response evolved for short-term threats.', 1),
    mc('PTSD can develop after exposure to:', ['Any highly emotional experience, including positive events', 'Actual or threatened death, serious injury, or sexual violence — experienced, witnessed, or repeatedly exposed to details of', 'Work stress exceeding coping capacity over time', 'Any childhood experience'], 'Actual or threatened death, serious injury, or sexual violence — experienced, witnessed, or repeatedly exposed to details of', 'PTSD requires exposure to traumatic events involving actual or threatened death, serious injury, or sexual violence — through direct experience, witnessing, learning it happened to someone close, or repeated exposure to traumatic details (as with first responders).', 2),
    mc('Avoidance in PTSD is problematic because:', ['It exposes the person to too many trauma reminders', 'It prevents the nervous system from processing and updating its threat learning', 'It relieves symptoms permanently by reducing exposure to triggers', 'It causes trauma memories to become more vivid over time'], 'It prevents the nervous system from processing and updating its threat learning', 'Avoidance feels relieving short-term but maintains PTSD long-term. The brain never learns that the threat has passed and updates its fear response. Effective PTSD treatments — like Prolonged Exposure — specifically break this avoidance cycle.', 3),
    mc('Which PTSD therapy uses bilateral stimulation while processing traumatic memories?', ['Cognitive Processing Therapy (CPT)', 'Dialectical Behavior Therapy (DBT)', 'EMDR (Eye Movement Desensitization and Reprocessing)', 'Prolonged Exposure (PE)'], 'EMDR (Eye Movement Desensitization and Reprocessing)', 'EMDR involves processing traumatic memories while engaging in bilateral stimulation — eye movements, taps, or sounds. It has a strong evidence base for PTSD. The exact mechanism is debated but therapeutic outcomes are well-established.', 4),
    mc('Chronic stress is associated with which health effects?', ['Improved immune function from repeated activation', 'Reduced cardiovascular risk due to heart rate conditioning', 'Elevated cortisol, disrupted sleep, suppressed immunity, and increased cardiovascular risk', 'Accelerated digestion and improved gut microbiome'], 'Elevated cortisol, disrupted sleep, suppressed immunity, and increased cardiovascular risk', 'Chronic stress keeps cortisol chronically elevated — disrupting sleep, suppressing immune function, raising blood pressure, impairing memory and cognition, and contributing to anxiety, depression, and metabolic dysfunction. The stress response evolved for short-term use, not chronic activation.', 5),
  ],

  'mental-health-stigma': [
    mc('Self-stigma in mental health refers to:', ['Other people discriminating against someone with a mental health condition', 'Institutional policies that underfund mental health treatment', 'Internalizing society\'s negative attitudes and applying them to oneself', 'Media portraying mental illness negatively'], 'Internalizing society\'s negative attitudes and applying them to oneself', 'Self-stigma is when people with mental health conditions adopt the negative stereotypes society holds and apply them to themselves — believing they are weak, flawed, or deserving of shame. It is a major reason people avoid seeking help.', 1),
    mc('Research shows what most effectively reduces mental health stigma?', ['Stricter legal consequences for discriminatory behavior', 'Government campaigns emphasizing dangers of untreated mental illness', 'Personal contact with people who have mental health conditions and accurate education', 'Limiting media coverage of mental health topics'], 'Personal contact with people who have mental health conditions and accurate education', 'Two interventions have the strongest evidence for reducing stigma: personal contact with people with lived experience (which humanizes the issue) and accurate education about the biological, common, and treatable nature of mental health conditions.', 2),
    mc('The claim that people with mental illness are dangerous or violent is:', ['True — mental illness significantly increases violent crime risk', 'A stereotype contradicted by evidence: people with mental illness are far more likely to be victims of violence than perpetrators', 'True only for specific conditions like schizophrenia', 'Accurate for untreated conditions but not for those in treatment'], 'A stereotype contradicted by evidence: people with mental illness are far more likely to be victims of violence than perpetrators', 'The association between mental illness and violence is a persistent and damaging stigma with little basis in evidence. People with mental health conditions are statistically more likely to be victims of violence than perpetrators.', 3),
    mc('Structural stigma in mental health refers to:', ['An individual\'s personal prejudice against people with mental illness', 'Discrimination built into institutions — lower insurance coverage, less research funding, inadequate resources', 'The stigma experienced by mental health professionals', 'Stigma from structural differences in brain anatomy'], 'Discrimination built into institutions — lower insurance coverage, less research funding, inadequate resources', 'Structural stigma is discrimination embedded in institutions and systems — mental health conditions covered at lower rates by insurance, less funding for mental health research, inadequate mental health services in schools and workplaces.', 4),
    mc('Person-first language in mental health means saying:', ['"A schizophrenic patient" to clearly identify the condition', '"A person with schizophrenia" rather than "a schizophrenic"', '"Mentally ill people" as a general term for clarity', '"Special needs individuals" to avoid stigmatizing labels'], '"A person with schizophrenia" rather than "a schizophrenic"', 'Person-first language places the person before their diagnosis. This linguistic choice reflects that a person is not defined by their condition, countering the stigma of treating diagnosis as identity.', 5),
  ],
}
