import type { ExerciseDef } from '../types'

function mc(
  question: string,
  options: string[],
  correctAnswer: string,
  explanation: string,
  order: number,
): ExerciseDef {
  return { question, type: 'MULTIPLE_CHOICE', options, correctAnswer, explanation, order }
}

export const healthExercises12: Record<string, ExerciseDef[]> = {
  'why-exercise-matters': [
    mc('Why do fit people have lower resting heart rates than sedentary people?', ['Their nervous systems naturally calm down from routine exercise', 'Their hearts pump more blood per beat (higher stroke volume), so fewer beats are needed', 'Cardio training slows the electrical signals that pace the heart', 'Fit people produce less adrenaline at rest'], 'Their hearts pump more blood per beat (higher stroke volume), so fewer beats are needed', 'Exercise strengthens the heart as a muscle. A stronger heart has a larger stroke volume — more blood moved per contraction — so it needs to beat less often to meet the body\'s resting needs. This is cardiac efficiency, not just calmness.', 1),
    mc('BDNF, released during exercise, supports the brain by:', ['Blocking stress hormones from crossing the blood-brain barrier', 'Supporting neuron growth and connection', 'Directly increasing serotonin in the synapse', 'Reducing inflammation in the prefrontal cortex only'], 'Supporting neuron growth and connection', 'Brain-derived neurotrophic factor (BDNF) is sometimes called "Miracle-Gro for the brain." It supports the growth of new neurons and strengthens connections between existing ones. Exercise is one of the most reliable ways to increase BDNF, which helps explain long-term brain health benefits.', 2),
    mc('How does exercise reduce type 2 diabetes risk?', ['It increases insulin production in the pancreas', 'Muscle contractions use glucose directly and increase insulin sensitivity in cells', 'Exercise reduces appetite, leading to lower carbohydrate intake', 'It reduces blood glucose by increasing kidney filtration'], 'Muscle contractions use glucose directly and increase insulin sensitivity in cells', 'Working muscles take up glucose independent of insulin during exercise. Over time, regular exercise also increases insulin sensitivity — cells respond more readily to insulin signals. Both effects improve blood glucose regulation and reduce diabetes risk.', 3),
    mc('Weight-bearing exercise protects bone health by:', ['Increasing calcium absorption in the small intestine', 'Raising parathyroid hormone levels that stimulate bone growth', 'Stressing bones and stimulating bone-building cells (osteoblasts)', 'Reducing the osteoclast activity that breaks down bone tissue'], 'Stressing bones and stimulating bone-building cells (osteoblasts)', 'Bone responds to mechanical stress by becoming denser. Weight-bearing activities (walking, running, lifting) apply forces that stimulate osteoblasts — the cells that build new bone — helping build bone density in youth and preserve it with aging. This is why exercise protects against osteoporosis.', 4),
    mc('Current physical activity guidelines recommend at minimum:', ['60 minutes of vigorous activity daily', '150–300 minutes per week of moderate aerobic activity plus 2 days of muscle-strengthening', '30 minutes of cardio 3 days per week only', 'Daily stretching plus one strength session per week'], '150–300 minutes per week of moderate aerobic activity plus 2 days of muscle-strengthening', 'The American Heart Association and CDC recommend 150–300 minutes per week of moderate-intensity aerobic activity (or 75–150 minutes vigorous), plus muscle-strengthening at least 2 days per week. Reducing sedentary time is also emphasized independently.', 5),
  ],

  'cardio-vs-strength': [
    mc('VO2 max measures:', ['Maximum heart rate achievable during peak exercise', 'Maximal oxygen uptake — a key indicator of aerobic fitness', 'The volume of air the lungs can hold', 'How efficiently muscles convert oxygen to ATP'], 'Maximal oxygen uptake — a key indicator of aerobic fitness', 'VO2 max is the maximum rate at which the body can consume oxygen during intense exercise. It reflects cardiovascular and aerobic fitness and is improved through consistent cardio training. Higher VO2 max is associated with better health outcomes and longevity.', 1),
    mc('In the early weeks of a strength training program, most strength gains are due to:', ['Rapid muscle fiber enlargement from protein synthesis', 'Neural adaptations — the nervous system learns to recruit muscle fibers more efficiently', 'Increased testosterone from exercise', 'Connective tissue strengthening that allows greater force production'], 'Neural adaptations — the nervous system learns to recruit muscle fibers more efficiently', 'Novice strength gains happen faster than muscle can grow. The first weeks of strength training primarily improve how the nervous system coordinates and recruits muscle fibers — not how big the muscles are. True muscular hypertrophy takes longer to develop.', 2),
    mc('Zone 2 cardio (60–70% max heart rate) is important because:', ['It burns the most calories per minute', 'It is only effective for beginners', 'It builds aerobic base and mitochondrial density despite feeling easy', 'It is the only zone that burns fat as fuel'], 'It builds aerobic base and mitochondrial density despite feeling easy', 'Zone 2 training at a comfortable, conversational pace drives mitochondrial adaptations and aerobic base development. It is foundational for endurance athletes and general aerobic health. Many people skip it because it feels too easy, but it produces meaningful adaptations.', 3),
    mc('Resistance training increases resting metabolic rate because:', ['Exercise raises body temperature permanently', 'Muscle tissue burns more calories at rest than fat tissue — more muscle means higher basal burn', 'Strength training releases hormones that increase metabolism for 48 hours', 'The repair process after training consumes significant long-term energy'], 'Muscle tissue burns more calories at rest than fat tissue — more muscle means higher basal burn', 'Skeletal muscle is metabolically active tissue. Increasing muscle mass through resistance training raises the amount of energy the body expends even at rest, contributing to better body composition and metabolic health over time.', 4),
    mc('For someone doing both cardio and strength training, which sequencing is least problematic?', ['High-intensity cardio immediately before heavy leg training', 'Strength training followed by low-intensity cardio in the same session', 'Low-intensity cardio (walking) on strength training days', 'Running followed immediately by heavy squats'], 'Low-intensity cardio (walking) on strength training days', 'Low-intensity cardio does not meaningfully impair strength training performance. High-intensity cardio before or immediately after heavy lower-body strength work is more problematic due to overlapping fatigue and competing adaptations. Separating sessions or doing lighter cardio is the pragmatic solution.', 5),
  ],

  'progressive-overload': [
    mc('What happens during the supercompensation phase of the adaptation cycle?', ['The body returns to exactly its pre-exercise baseline', 'The body rebuilds to a capacity slightly above the previous baseline', 'The training stimulus is removed, causing detraining', 'Inflammation peaks and begins to resolve'], 'The body rebuilds to a capacity slightly above the previous baseline', 'After exercise stress and recovery, the body overshoots its previous baseline in anticipation of future demands — building slightly more capacity than existed before. This is supercompensation. Progressive overload provides the next stimulus before this extra capacity is lost.', 1),
    mc('The 10% rule for cardio progression recommends:', ['Increasing intensity by no more than 10% per week', 'Increasing weekly volume (distance, time) by no more than 10% per week to avoid overuse injuries', 'Adding one additional workout every 10 days', 'Running 10% faster each month'], 'Increasing weekly volume (distance, time) by no more than 10% per week to avoid overuse injuries', 'Connective tissue adapts more slowly than cardiovascular fitness. Increasing running mileage or cycling volume too quickly overloads tendons and ligaments before they\'ve adapted. The 10% per week guideline limits overuse injury risk while still allowing consistent progress.', 2),
    mc('Overtraining syndrome differs from normal post-workout fatigue because:', ['It resolves with 48 hours of rest', 'It is prolonged — involving weeks of reduced performance, persistent fatigue, and psychological burnout', 'It only affects cardiovascular performance, not strength', 'It is caused by doing too many different exercises rather than too much volume'], 'It is prolonged — involving weeks of reduced performance, persistent fatigue, and psychological burnout', 'Overtraining syndrome results from accumulated training stress without adequate recovery over an extended period. Unlike normal fatigue that resolves with a rest day, overtraining syndrome requires weeks to months of reduced training to recover from. It is characterized by declining performance, mood changes, and persistent exhaustion.', 3),
    mc('Linear progression (adding weight every session) is primarily effective for:', ['Advanced athletes with years of training', 'Intermediate lifters needing weekly progress targets', 'Beginners, whose rapid neural and muscular adaptations allow frequent improvements', 'Any lifter regardless of experience level'], 'Beginners, whose rapid neural and muscular adaptations allow frequent improvements', 'Novice lifters can add weight to the bar every session because their nervous systems and muscles are adapting rapidly from a low baseline. As training advances, the body adapts more slowly and needs more sophisticated periodization — weekly or monthly progress becomes the goal.', 4),
    mc('A planned deload week reduces training volume by 30–50% to:', ['Allow the body to fully stop exercising and reset', 'Let accumulated fatigue dissipate, often resulting in improved performance afterward', 'Switch entirely to cardio from strength training', 'Reduce calorie needs during a dieting phase'], 'Let accumulated fatigue dissipate, often resulting in improved performance afterward', 'Deload weeks are planned periods of reduced training intensity and volume every 4–8 weeks. They allow accumulated fatigue — from multiple weeks of hard training — to clear, revealing the fitness that was built but masked by tiredness. Performance often noticeably improves after a deload.', 5),
  ],
}
