import type { ExerciseDef } from '../types'

function mc(
  question: string,
  options: string[],
  correctAnswer: string,
  explanation: string,
  order: number,
): ExerciseDef {
  return { question, type: 'MULTIPLE_CHOICE', options, correctAnswer, explanation, order }
}

export const healthExercises2: Record<string, ExerciseDef[]> = {
  'cardiovascular-system': [
    mc('What is the function of capillaries in the cardiovascular system?', ['Carry oxygen-depleted blood back to the heart', 'Carry blood away from the heart at high pressure', 'Allow exchange of oxygen, nutrients, and waste between blood and tissues', 'Regulate blood pressure through muscular contraction'], 'Allow exchange of oxygen, nutrients, and waste between blood and tissues', 'Capillaries are microscopic vessels with walls only one cell thick. This thin barrier allows oxygen, nutrients, and waste products to pass between blood and surrounding tissues — the actual purpose of the whole circulatory system.', 1),
    mc('A blood pressure reading of 120/80 mmHg means:', ['120 is diastolic pressure, 80 is systolic', 'Both numbers represent the same measurement at different times', '120 is systolic (during contraction), 80 is diastolic (between beats)', 'The heart beats 120 times per minute and 80 during sleep'], '120 is systolic (during contraction), 80 is diastolic (between beats)', 'Systolic pressure is the force during ventricular contraction; diastolic is the pressure when the heart relaxes between beats. Normal is below 120/80 mmHg. Hypertension causes ongoing vessel damage.', 2),
    mc('Why do fit people typically have lower resting heart rates?', ['Fit people have smaller hearts that cycle faster', 'Their hearts pump more blood per beat (higher stroke volume), requiring fewer beats', 'Exercise permanently slows the electrical signals in the heart', 'Fit people have lower blood pressure, which reduces heart rate automatically'], 'Their hearts pump more blood per beat (higher stroke volume), requiring fewer beats', 'Cardiac fitness increases stroke volume — the amount of blood pumped per contraction. A more efficient heart meets the body\'s oxygen demands with fewer beats per minute. Elite athletes often have resting heart rates in the 40s–50s.', 3),
    mc('The acronym FAST is used to recognize stroke. What does the A stand for?', ['Airway blockage', 'Arm weakness', 'Atrial fibrillation', 'Abdominal pain'], 'Arm weakness', 'FAST stands for Face drooping, Arm weakness, Speech difficulty, Time to call 911. These are the hallmark sudden symptoms of stroke. Every minute without treatment, brain cells die — making rapid recognition critical.', 4),
    mc('Atherosclerosis, which causes coronary artery disease, involves:', ['The heart muscle thickening over time', 'Plaque building up inside artery walls, narrowing blood flow', 'Electrical conduction problems in the heart', 'Heart valves failing to close properly'], 'Plaque building up inside artery walls, narrowing blood flow', 'Atherosclerosis is cholesterol-containing plaque buildup inside arterial walls. In coronary arteries (which supply the heart muscle), this narrows blood flow, causing angina. A plaque rupture with clot formation causes a heart attack.', 5),
  ],

  'respiratory-system': [
    mc('Where does gas exchange occur in the lungs?', ['The trachea', 'The bronchi', 'The alveoli', 'The diaphragm'], 'The alveoli', 'Alveoli are tiny air sacs at the tips of the bronchiole tree. Surrounded by capillaries and with walls one cell thick, they are where oxygen crosses into the blood and carbon dioxide crosses out to be exhaled.', 1),
    mc('What primarily controls breathing rate?', ['Blood oxygen levels', 'Blood carbon dioxide levels', 'Lung volume', 'Heart rate'], 'Blood carbon dioxide levels', 'Breathing rate is primarily regulated by CO2 levels, not oxygen. When CO2 rises, the brainstem signals faster breathing. This is why hyperventilating (exhaling too much CO2) causes lightheadedness and involuntary breath-holding.', 2),
    mc('The epiglottis serves what function?', ['Filters particles from inhaled air', 'Covers the trachea during swallowing to prevent food from entering the airway', 'Regulates how much air enters each lung', 'Warms and humidifies air before it reaches the lungs'], 'Covers the trachea during swallowing to prevent food from entering the airway', 'The epiglottis is a flap of cartilage at the entrance to the larynx. When you swallow, it reflexively closes over the trachea, directing food and liquid into the esophagus rather than the airway.', 3),
    mc('Normal blood oxygen saturation (SpO2) is:', ['80–85%', '85–90%', '90–94%', '95–100%'], '95–100%', 'Normal oxygen saturation is 95–100%. Below 90%, cells are not receiving adequate oxygen — a medically significant finding. Pulse oximeters measure this non-invasively using light wavelengths through a finger.', 4),
    mc('COPD is most commonly caused by:', ['Untreated asthma', 'Recurring pneumonia', 'Smoking', 'High-altitude living'], 'Smoking', 'Smoking is the primary cause of COPD, which includes emphysema (destruction of alveolar walls) and chronic bronchitis (chronic airway inflammation). The damage is irreversible, but smoking cessation is the most important intervention to slow progression.', 5),
  ],

  'digestive-system': [
    mc('Where does most digestion and nutrient absorption occur?', ['Stomach', 'Large intestine', 'Small intestine', 'Liver'], 'Small intestine', 'The small intestine, about 20 feet long, is where most digestion is completed and nutrients are absorbed. Its inner surface is covered with villi and microvilli creating a total absorptive area roughly the size of a tennis court.', 1),
    mc('What role does the liver play in digestion?', ['Mechanically churns food with acid', 'Stores feces until elimination', 'Produces bile to emulsify fats and processes absorbed nutrients', 'Absorbs water from undigested material'], 'Produces bile to emulsify fats and processes absorbed nutrients', 'The liver produces bile (stored in the gallbladder) that emulsifies fats for digestion. It also receives nutrient-rich blood from the small intestine and processes nutrients, removes toxins, and regulates blood glucose.', 2),
    mc('What protects the stomach from its own acid?', ['Peristalsis pushing contents downward', 'A thick mucus lining protecting the stomach wall', 'The pyloric sphincter preventing backflow', 'Stomach acid that only activates after food contact'], 'A thick mucus lining protecting the stomach wall', 'The stomach secretes strong hydrochloric acid to digest food and kill pathogens. To protect itself, it secretes a thick mucus layer. When this protection breaks down — from H. pylori or NSAID use — stomach ulcers develop.', 3),
    mc('Which best describes the gut microbiome?', ['Harmful bacteria that cause most digestive diseases', 'Viruses that live in the digestive tract', 'Trillions of bacteria in the colon that aid digestion, train immunity, and influence health', 'Digestive enzymes produced by the pancreas'], 'Trillions of bacteria in the colon that aid digestion, train immunity, and influence health', 'The gut microbiome consists of roughly 100 trillion bacteria of hundreds of species living primarily in the colon. They help digest fiber, produce vitamins, regulate the immune system, and communicate with the brain through the gut-brain axis.', 4),
    mc('Celiac disease is an autoimmune reaction triggered by:', ['Lactose in dairy', 'Gluten — a protein in wheat, barley, and rye', 'Fructose in fruit', 'Casein in milk'], 'Gluten — a protein in wheat, barley, and rye', 'In celiac disease, consuming gluten triggers an immune attack on the small intestine lining, damaging villi and impairing nutrient absorption. The only treatment is strict, lifelong gluten avoidance.', 5),
  ],
}
