import type { ExerciseDef } from '../types'

function mc(
  question: string,
  options: string[],
  correctAnswer: string,
  explanation: string,
  order: number,
): ExerciseDef {
  return { question, type: 'MULTIPLE_CHOICE', options, correctAnswer, explanation, order }
}

export const healthExercises11: Record<string, ExerciseDef[]> = {
  'bleeding-and-wounds': [
    mc('Which type of bleeding is most immediately life-threatening?', ['Venous bleeding — dark blood flowing steadily', 'Capillary bleeding — slow oozing from a surface wound', 'Arterial bleeding — bright red blood spurting in pulses', 'Internal bleeding with no external blood visible'], 'Arterial bleeding — bright red blood spurting in pulses', 'Arterial bleeding — bright red, pulsating spurts — is the most immediately dangerous. Arteries carry oxygenated blood at high pressure; significant arterial hemorrhage can cause death within minutes. It requires immediate, aggressive direct pressure or tourniquet.', 1),
    mc('The most common mistake when applying direct pressure to a wound is:', ['Removing the cloth when it soaks through to check the wound', 'Not pressing hard enough to compress the bleeding vessel', 'Applying pressure for too long, preventing clotting', 'Using clean rather than sterile materials'], 'Not pressing hard enough to compress the bleeding vessel', 'The two most common direct pressure mistakes are: not pressing hard enough (you need to compress the vessel), and removing or lifting the cloth (which disturbs forming clots). Press firmly — harder than feels comfortable — for at least 10 uninterrupted minutes.', 2),
    mc('Current guidance on tourniquets for severe limb bleeding has:', ['Restricted their use to trained medical professionals only', 'Maintained the traditional advice to avoid them due to limb damage risk', 'Reversed previous restrictions — studies show tourniquets save lives when used appropriately', 'Limited tourniquet use to situations where direct pressure has failed for more than 30 minutes'], 'Reversed previous restrictions — studies show tourniquets save lives when used appropriately', 'Military trauma medicine research has definitively shown that tourniquets save lives in severe limb bleeding. Previous avoidance recommendations that cost lives have been reversed. Tourniquets are now standard in Stop the Bleed training.', 3),
    mc('A wound likely needs stitches if it:', ['Has bled for more than 5 minutes with pressure applied', 'Is longer than about 1/2 inch, gapes open, or is on the face or over a joint', 'Has any bruising around the wound edges', 'Requires more than one bandage to cover'], 'Is longer than about 1/2 inch, gapes open, or is on the face or over a joint', 'Wounds needing closure are those that gape open, are too wide to close naturally, are on high-tension areas (face, joints, hands, feet), involve deep structures, or are bite wounds. Closure should occur within 6–12 hours — after that, infection risk increases.', 4),
    mc('Signs of wound infection warranting medical care include:', ['Scabbing and light itching around the wound', 'Mild swelling and bruising in the first 24 hours', 'Increasing redness spreading from the wound, warmth, pus, or red streaks', 'Clear fluid seeping from the wound on day 2 or 3'], 'Increasing redness spreading from the wound, warmth, pus, or red streaks', 'Signs of infection include expanding redness (especially with warmth), pus or discharge, fever, and red streaks spreading from the wound — which indicate spreading infection (lymphangitis) that requires urgent medical treatment.', 5),
  ],

  'burns-and-injuries': [
    mc('For a burn, the correct immediate first aid is:', ['Ice or an ice pack applied directly', 'Butter, toothpaste, or oil to protect the skin', 'Cool (not cold) running water for 10–20 minutes', 'A sterile dry dressing applied immediately without cooling'], 'Cool (not cold) running water for 10–20 minutes', 'Cool running water (not ice — which causes additional tissue damage) applied for 10–20 minutes is the evidence-based treatment for burns within the first 30 minutes. Home remedies like butter or toothpaste trap heat and increase infection risk.', 1),
    mc('A full-thickness (third-degree) burn is characterized by:', ['Intense pain, redness, and blistering', 'Superficial redness without blistering that heals in days', 'Destruction of all skin layers; may appear white, brown, or black; may not be painful', 'Severe pain limited to the outer skin layer'], 'Destruction of all skin layers; may appear white, brown, or black; may not be painful', 'Full-thickness burns destroy all skin layers and may damage underlying tissue. They can appear white, brown, or black. Paradoxically, they may not be painful because nerve endings are destroyed. They always require medical care.', 2),
    mc('For a suspected fracture of the spine, pelvis, or femur, the correct first aid is:', ['Straighten and immobilize with a splint', 'Support the person to walk to reduce swelling', 'Keep the person still in the position found and wait for EMS', 'Apply ice and elevation and transport to urgent care'], 'Keep the person still in the position found and wait for EMS', 'Fractures of the spine, pelvis, or femur require professional handling — movement without proper technique can cause additional life-altering injury. Keep the person still, do not attempt to move them, and wait for trained EMS personnel.', 3),
    mc('The RICE protocol for sprains stands for:', ['Reduce, Immobilize, Cool, Elevate', 'Rest, Ice, Compression, Elevation', 'Restrict, Immobilize, Compress, Evaluate', 'Rest, Ibuprofen, Cold, Exercise'], 'Rest, Ice, Compression, Elevation', 'RICE is the standard initial treatment for sprains: Rest (avoid using the injured area), Ice (20 minutes every 2–3 hours for 48 hours), Compression (elastic bandage), and Elevation (raise above heart level to reduce swelling).', 4),
    mc('After a head injury, which symptom most clearly warrants calling 911?', ['Mild headache that resolves within an hour', 'Soreness at the point of impact', 'Loss of consciousness, repeated vomiting, or worsening headache', 'Feeling shaken and upset immediately after injury'], 'Loss of consciousness, repeated vomiting, or worsening headache', 'Red flags after head injury indicating serious brain injury include: loss of consciousness (even briefly), confusion, repeated vomiting, worsening headache, seizures, unequal pupils, slurred speech, clear fluid from nose or ears, and limb weakness.', 5),
  ],

  'overdose-and-poisoning': [
    mc('The U.S. Poison Control Center number, available 24/7, is:', ['911', '1-800-222-1222', '1-888-POISON-1', '211'], '1-800-222-1222', '1-800-222-1222 is the national Poison Control Center number in the U.S., available 24/7. Toxicologists can advise on whether emergency care is needed and what to do for exposures that don\'t appear immediately life-threatening.', 1),
    mc('Signs of opioid overdose include all of the following EXCEPT:', ['Pinpoint (very small) pupils', 'Slow, shallow, or stopped breathing', 'Gurgling or choking sounds', 'Wide, dilated pupils and agitation'], 'Wide, dilated pupils and agitation', 'Opioid overdose produces: unconsciousness, slow/shallow/stopped breathing, pinpoint pupils, blue/purple lips, pale clammy skin, and gurgling sounds. Dilated pupils and agitation are more consistent with stimulant overdose — the opposite presentation.', 2),
    mc('Naloxone (Narcan) is used to:', ['Prevent someone from becoming intoxicated on opioids', 'Rapidly reverse opioid overdose by blocking opioid receptors', 'Treat alcohol poisoning by accelerating metabolism', 'Prevent opioid withdrawal symptoms'], 'Rapidly reverse opioid overdose by blocking opioid receptors', 'Naloxone rapidly reverses opioid overdose by blocking and displacing opioids from their receptors. Critically, naloxone wears off in 30–90 minutes — shorter than many opioids — so the person can re-enter overdose. Emergency care is required even if naloxone works.', 3),
    mc('For someone unconscious from alcohol poisoning, the priority is:', ['Giving them coffee or water to help sober up', 'Having them shower in cold water', 'Calling 911 and placing them in the recovery position to prevent choking on vomit', 'Having them sleep it off flat on their back'], 'Calling 911 and placing them in the recovery position to prevent choking on vomit', 'Alcohol poisoning with unconsciousness is a medical emergency. Place them on their side (recovery position) to prevent choking if they vomit. Coffee, cold showers, and sleeping flat do not help — time is the only cure, and medical monitoring is needed.', 4),
    mc('If you suspect carbon monoxide poisoning inside a building, your first action should be:', ['Open windows to ventilate and then call 911', 'Call 911 from inside and wait for responders', 'Get out immediately and call 911 from outside — do not re-enter', 'Check the furnace before deciding to evacuate'], 'Get out immediately and call 911 from outside — do not re-enter', 'Carbon monoxide is colorless and odorless — undetectable without a CO detector. If poisoning is suspected, evacuate immediately, call 911 from outside, and do not re-enter. Even brief additional CO exposure causes harm. Everyone exposed needs medical evaluation.', 5),
  ],
}
