import type { AssessmentDef, AssessmentQuestionDef } from '../types'

const mc = (q: string, opts: string[], ans: string, exp: string, pts: number, ord: number): AssessmentQuestionDef =>
  ({ question: q, type: 'MULTIPLE_CHOICE', options: opts, correctAnswer: ans, explanation: exp, points: pts, order: ord })

const oe = (q: string, ans: string, exp: string, pts: number, ord: number): AssessmentQuestionDef =>
  ({ question: q, type: 'OPEN_ENDED', correctAnswer: ans, explanation: exp, points: pts, order: ord })

export const healthAssessments: Record<string, AssessmentDef> = {
  'human-body': {
    title: 'Human Body Assessment',
    passingScore: 75,
    timeLimitMin: 30,
    questions: [
      mc('What is the primary function of the cardiovascular system?', ['Filter waste from blood', 'Transport oxygen, nutrients, and waste throughout the body', 'Regulate hormone production', 'Coordinate muscle movement'], 'Transport oxygen, nutrients, and waste throughout the body', 'The cardiovascular system (heart, blood, vessels) acts as the body\'s delivery and waste removal network — circulating everything cells need and carrying away metabolic waste.', 1, 1),
      mc('What organ is primarily responsible for filtering blood and producing urine?', ['Liver', 'Spleen', 'Kidneys', 'Pancreas'], 'Kidneys', 'The kidneys filter about 200 liters of blood daily, removing waste products and excess water to produce urine — maintaining blood chemistry and fluid balance.', 1, 2),
      mc('What is the function of the autonomic nervous system?', ['Control voluntary muscle movements', 'Regulate unconscious body functions like heart rate, digestion, and breathing', 'Process sensory information', 'Coordinate reflexes only'], 'Regulate unconscious body functions like heart rate, digestion, and breathing', 'The autonomic nervous system runs involuntary processes — you don\'t consciously control your heart rate or digestive contractions. It has sympathetic (fight-or-flight) and parasympathetic (rest-and-digest) branches.', 1, 3),
      mc('What is homeostasis?', ['The process of cell division', 'The body\'s ability to maintain stable internal conditions despite external changes', 'Blood clotting after injury', 'Immune response to pathogens'], 'The body\'s ability to maintain stable internal conditions despite external changes', 'Homeostasis is the constant self-regulation maintaining temperature, pH, blood sugar, hydration — the narrow conditions all body systems require to function.', 1, 4),
      mc('What is the role of red blood cells?', ['Fight infection', 'Carry oxygen from the lungs to body tissues using hemoglobin', 'Produce antibodies', 'Form blood clots'], 'Carry oxygen from the lungs to body tissues using hemoglobin', 'Red blood cells are packed with hemoglobin — a protein that binds oxygen in the lungs and releases it to tissues, then picks up CO2 for the return trip.', 1, 5),
      mc('What does the lymphatic system do?', ['Pump blood through the body', 'Drain excess fluid from tissues and support the immune system', 'Digest food', 'Filter air entering the lungs'], 'Drain excess fluid from tissues and support the immune system', 'The lymphatic system collects interstitial fluid, returns it to circulation, and houses immune cells — lymph nodes filter pathogens and are where immune responses are coordinated.', 1, 6),
      mc('What is the function of the liver?', ['Produce insulin', 'Detoxify blood, produce bile, synthesize proteins, and regulate metabolism', 'Filter urine', 'Control breathing rate'], 'Detoxify blood, produce bile, synthesize proteins, and regulate metabolism', 'The liver is the body\'s chemical factory — it processes nutrients, produces bile for digestion, detoxifies alcohol and drugs, makes clotting proteins, and stores glycogen.', 1, 7),
      mc('What is the difference between arteries and veins?', ['Arteries carry deoxygenated blood; veins carry oxygenated blood', 'Arteries carry blood away from the heart; veins carry blood to the heart', 'They carry identical blood in opposite directions', 'Veins are larger than arteries'], 'Arteries carry blood away from the heart; veins carry blood to the heart', 'Arteries (usually carrying oxygenated blood) lead away from the heart under pressure. Veins return blood to the heart and use valves to prevent backflow.', 1, 8),
      oe('Explain how the body responds to an infection from a bacterial pathogen.', 'The immune response has multiple layers: physical barriers (skin, mucus) are the first defense. If breached, innate immunity responds first — inflammation, fever, phagocytes consuming bacteria. The adaptive immune system activates days later: B cells produce antibodies targeting the specific pathogen, T cells destroy infected cells. Memory cells remain so future exposure triggers a faster response (basis of immunity and vaccination).', 'A strong answer mentions both innate and adaptive immunity, not just "white blood cells fight it."', 2, 9),
      oe('Why does exercise have benefits for both the cardiovascular and musculoskeletal systems?', 'For the cardiovascular system: regular aerobic exercise strengthens the heart muscle, improves cardiac output, lowers resting heart rate, improves blood lipid profiles, and reduces blood pressure. For the musculoskeletal system: strength exercise increases muscle fiber size, bone density (load-bearing stress triggers bone remodeling), and tendon/ligament strength. The body adapts to the demands placed on it — use it or lose it.', 'A strong answer names specific adaptations for each system rather than just saying "exercise is healthy."', 2, 10),
    ],
  },

  'nutrition-and-diet': {
    title: 'Nutrition and Diet Assessment',
    passingScore: 75,
    timeLimitMin: 30,
    questions: [
      mc('What are macronutrients?', ['Vitamins and minerals needed in small amounts', 'Carbohydrates, proteins, and fats — the three main energy-providing nutrients', 'Antioxidants and phytonutrients', 'Fiber and water'], 'Carbohydrates, proteins, and fats — the three main energy-providing nutrients', 'Macronutrients provide energy (calories) and are needed in large quantities. Carbohydrates and proteins have 4 kcal/gram; fats have 9 kcal/gram.', 1, 1),
      mc('What is the primary role of protein in the diet?', ['Provide quick energy', 'Build and repair tissues, produce enzymes, hormones, and immune proteins', 'Insulate body fat', 'Carry fat-soluble vitamins'], 'Build and repair tissues, produce enzymes, hormones, and immune proteins', 'Proteins are the building blocks of nearly everything functional in the body — muscles, enzymes, hormones, antibodies, and structural components all require amino acids from dietary protein.', 1, 2),
      mc('What is a simple carbohydrate vs. a complex carbohydrate?', ['Simple carbs are healthier', 'Simple carbs are quickly digested sugars; complex carbs are longer chains that digest more slowly', 'Complex carbs come only from fruit', 'They have the same nutritional value'], 'Simple carbs are quickly digested sugars; complex carbs are longer chains that digest more slowly', 'Simple carbs (sugar, white bread) spike blood sugar rapidly. Complex carbs (whole grains, beans) digest slowly, providing more sustained energy and better blood sugar control.', 1, 3),
      mc('What is a caloric deficit?', ['Consuming more calories than you burn', 'When you burn more calories than you consume', 'An unhealthy restriction of food', 'Having too few nutrients despite enough calories'], 'When you burn more calories than you consume', 'A caloric deficit means energy out > energy in. The body draws on stored fat (and some muscle) to make up the difference — the mechanism behind fat loss.', 1, 4),
      mc('What are trans fats and why are they harmful?', ['Healthy fats found in fish', 'Industrially produced fats (partially hydrogenated oils) that raise LDL and lower HDL cholesterol, increasing heart disease risk', 'Natural fats in meat that are fine in moderation', 'Any fat found in fried food'], 'Industrially produced fats (partially hydrogenated oils) that raise LDL and lower HDL cholesterol, increasing heart disease risk', 'Trans fats are produced by hydrogenating vegetable oils to make them solid. They raise harmful LDL cholesterol, lower protective HDL, and significantly increase cardiovascular disease risk.', 1, 5),
      mc('What is dietary fiber?', ['A type of simple carbohydrate', 'Non-digestible plant carbohydrates that support digestion, blood sugar, and gut health', 'A supplement for weight loss', 'A protein found in whole grains'], 'Non-digestible plant carbohydrates that support digestion, blood sugar, and gut health', 'Fiber passes through the digestive system undigested, feeding gut bacteria, slowing sugar absorption, adding bulk to stool, and reducing cholesterol absorption.', 1, 6),
      mc('What does BMI measure?', ['Exact body fat percentage', 'A ratio of weight to height squared used as a population-level screening tool', 'Muscle mass relative to fat', 'Cardiovascular fitness level'], 'A ratio of weight to height squared used as a population-level screening tool', 'BMI is weight(kg)/height(m)². It\'s a crude screening tool — it doesn\'t distinguish muscle from fat and is least accurate for athletes and the elderly.', 1, 7),
      mc('Which vitamin deficiency causes scurvy?', ['Vitamin D', 'Vitamin B12', 'Vitamin C', 'Vitamin A'], 'Vitamin C', 'Vitamin C (ascorbic acid) is essential for collagen synthesis. Deficiency causes scurvy — bleeding gums, joint pain, poor wound healing. Historically devastated sailors without fresh produce.', 1, 8),
      oe('Why do nutrition experts generally recommend whole foods over processed foods, even when the calorie counts are similar?', 'Whole foods retain fiber, micronutrients, antioxidants, and phytonutrients lost in processing. Fiber slows digestion and feeds beneficial gut bacteria. Processed foods often contain added sugar, sodium, and industrial fats not present in whole versions. They also tend to be hyper-palatable, triggering overconsumption. Beyond calories, food quality affects inflammation, gut microbiome, hormonal responses, and long-term disease risk.', 'A strong answer goes beyond "whole foods have more nutrients" to explain fiber, palatability, and metabolic effects.', 2, 9),
      oe('Explain the difference between hunger and appetite. Why does this distinction matter for eating behavior?', 'Hunger is the physiological signal of caloric need — driven by hormones (ghrelin rises when the stomach is empty). Appetite is the psychological desire to eat, driven by sight, smell, emotion, habit, and food palatability. You can be full but still have appetite (seeing dessert after a big meal). Highly processed foods exploit appetite independent of hunger. Understanding this helps people recognize emotional eating and distinguish "I\'m hungry" from "I want to eat."', 'A strong answer defines both terms physiologically and explains the behavioral implication.', 2, 10),
    ],
  },

  'mental-health-fundamentals': {
    title: 'Mental Health Fundamentals Assessment',
    passingScore: 75,
    timeLimitMin: 30,
    questions: [
      mc('What is the biopsychosocial model of mental health?', ['A model focusing only on brain chemistry', 'A framework recognizing that mental health is influenced by biological, psychological, and social factors', 'A classification system for mental disorders', 'A treatment protocol for depression'], 'A framework recognizing that mental health is influenced by biological, psychological, and social factors', 'Mental health isn\'t just brain chemistry — genetics, trauma, thought patterns, relationships, stress, and social support all interact to affect mental wellbeing.', 1, 1),
      mc('What is the difference between anxiety and an anxiety disorder?', ['They are the same', 'Anxiety is normal and adaptive; an anxiety disorder is when anxiety is disproportionate and impairs functioning', 'Anxiety disorders are always more severe', 'Only anxiety disorders involve physical symptoms'], 'Anxiety is normal and adaptive; an anxiety disorder is when anxiety is disproportionate and impairs functioning', 'Feeling anxious before a job interview is normal and helpful. An anxiety disorder involves excessive, persistent anxiety that interferes with daily life and is disproportionate to actual threats.', 1, 2),
      mc('What is cognitive behavioral therapy (CBT)?', ['A medication for anxiety', 'A therapy focusing on identifying and changing unhelpful thought patterns and behaviors', 'A form of hypnosis', 'Group therapy for mental illness'], 'A therapy focusing on identifying and changing unhelpful thought patterns and behaviors', 'CBT is one of the most evidence-based psychotherapies — it works by identifying distorted thoughts (cognitive) and changing behaviors (behavioral) that maintain mental health problems.', 1, 3),
      mc('What are the warning signs of a mental health crisis?', ['Only visible symptoms like crying', 'Significant changes in behavior, expressing hopelessness, withdrawing, self-harm, or suicidal thoughts', 'Any period of sadness', 'Physical illness only'], 'Significant changes in behavior, expressing hopelessness, withdrawing, self-harm, or suicidal thoughts', 'Crisis warning signs include dramatic behavior change, giving away possessions, saying goodbye, talking about hopelessness or being a burden, and direct or indirect statements about suicide.', 1, 4),
      mc('What is stigma in the context of mental health?', ['A diagnosis label', 'Negative stereotypes and discrimination against people with mental health conditions', 'A side effect of psychiatric medication', 'A type of cognitive distortion'], 'Negative stereotypes and discrimination against people with mental health conditions', 'Mental health stigma causes people to avoid seeking help, hide struggles, and face unfair judgment. It\'s a major barrier to treatment and recovery.', 1, 5),
      mc('What is the role of sleep in mental health?', ['Sleep only affects physical health', 'Sleep deprivation worsens virtually all mental health conditions and adequate sleep supports emotional regulation', 'Mental health affects sleep but not vice versa', 'Sleep disorders are separate from mental health'], 'Sleep deprivation worsens virtually all mental health conditions and adequate sleep supports emotional regulation', 'Sleep is when the brain consolidates memories, regulates emotion, and clears waste products. Chronic sleep deprivation increases anxiety, depression, irritability, and cognitive impairment.', 1, 6),
      mc('What is a coping strategy?', ['Avoiding all stressors', 'A technique or behavior used to manage stress and difficult emotions', 'A psychiatric medication', 'A diagnosis of a mental health condition'], 'A technique or behavior used to manage stress and difficult emotions', 'Coping strategies can be adaptive (exercise, mindfulness, talking to someone, problem-solving) or maladaptive (substance use, avoidance, self-harm). Building healthy coping skills is central to mental health.', 1, 7),
      mc('What does "trauma-informed" mean?', ['Treating trauma patients only', 'An approach recognizing how trauma affects people and prioritizing safety, trust, and empowerment', 'A requirement to always ask about trauma history', 'A type of therapy for PTSD only'], 'An approach recognizing how trauma affects people and prioritizing safety, trust, and empowerment', 'Trauma-informed approaches acknowledge that many people have trauma histories that affect behavior. Rather than asking "what\'s wrong with you?" they ask "what happened to you?" — shifting blame to context.', 1, 8),
      oe('Why do so many people avoid seeking mental health treatment, and what would need to change for more people to get help?', 'Barriers: stigma (fear of being seen as weak or crazy), cost and lack of insurance coverage, shortage of providers (especially in rural areas), not knowing how to access help, cultural factors, and the illness itself making it hard to take action. Changes needed: reduce stigma through education and open conversation, expand affordable access, train more providers, integrate mental health into primary care, and normalize help-seeking the way we normalize treating physical illness.', 'A strong answer names multiple specific barriers and proposes systemic solutions, not just individual-level change.', 2, 9),
      oe('Describe what a healthy support system looks like and why social connection matters for mental health.', 'A healthy support system includes people you trust (friends, family, mentors), who offer different types of support: emotional (listening, validating), practical (help with tasks), informational (advice, resources), and social (belonging, fun). Social connection is a fundamental human need — isolation increases cortisol, risk of depression, and even mortality. Strong social ties are one of the most robust predictors of wellbeing across research.', 'A strong answer names types of support, explains the mechanism (not just "connection is good"), and acknowledges quality over quantity.', 2, 10),
    ],
  },

  'first-aid-and-emergency-response': {
    title: 'First Aid and Emergency Response Assessment',
    passingScore: 75,
    timeLimitMin: 30,
    questions: [
      mc('What is the first step in any emergency?', ['Begin CPR immediately', 'Assess scene safety before approaching', 'Call 911 right away', 'Move the victim to a safer location'], 'Assess scene safety before approaching', 'Scene safety comes first — an unsafe scene (active traffic, electrical hazards, unstable structures) can turn a rescuer into another victim. Assess before you act.', 1, 1),
      mc('What does CPR stand for and what does it do?', ['Cardiac Pressure Resuscitation — restarts the heart', 'Cardiopulmonary Resuscitation — artificially circulates blood and maintains oxygenation when the heart stops', 'Critical Patient Response — a hospital protocol', 'Continuous Pulse Restoration — a defibrillator procedure'], 'Cardiopulmonary Resuscitation — artificially circulates blood and maintains oxygenation when the heart stops', 'CPR manually compresses the heart to circulate blood and provides rescue breaths to maintain oxygenation — buying time until a defibrillator or advanced help arrives.', 1, 2),
      mc('At what rate should chest compressions be performed in CPR for adults?', ['60–80 per minute', '100–120 per minute', '40–60 per minute', 'As fast as possible'], '100–120 per minute', 'Current guidelines recommend 100–120 compressions per minute with full chest recoil between compressions and a depth of at least 2 inches for adults.', 1, 3),
      mc('What is an AED?', ['Automated Emergency Defibrillator — shocks all cardiac events', 'Automated External Defibrillator — delivers an electric shock to restore normal heart rhythm in ventricular fibrillation', 'Advanced Emergency Device — used only by paramedics', 'Airway Emergency Device — manages choking'], 'Automated External Defibrillator — delivers an electric shock to restore normal heart rhythm in ventricular fibrillation', 'AEDs are designed for public use — they analyze the heart rhythm and deliver a shock if appropriate (V-fib). They significantly improve cardiac arrest survival rates.', 1, 4),
      mc('What is the correct method to stop severe bleeding?', ['Apply ice to reduce blood flow', 'Apply direct pressure with a clean cloth and maintain it', 'Elevate only, without touching the wound', 'Use a tourniquet immediately for all wounds'], 'Apply direct pressure with a clean cloth and maintain it', 'Direct pressure is the primary method for controlling bleeding. Don\'t lift the cloth to check — add more on top. A tourniquet is used for life-threatening limb bleeding that can\'t be controlled by pressure alone.', 1, 5),
      mc('What is the recovery position used for?', ['Someone not breathing', 'An unconscious but breathing person — to keep the airway clear and prevent aspiration', 'A person in cardiac arrest', 'Someone with a suspected spinal injury'], 'An unconscious but breathing person — to keep the airway clear and prevent aspiration', 'The recovery position (on their side) uses gravity to keep the airway open and allows fluids to drain, preventing an unconscious person from choking if they vomit.', 1, 6),
      mc('What is the Heimlich maneuver used for?', ['Cardiac arrest', 'Severe choking where the airway is completely blocked', 'Diabetic emergencies', 'Drowning'], 'Severe choking where the airway is completely blocked', 'The Heimlich maneuver (abdominal thrusts) uses upward pressure to force air from the lungs and dislodge an airway obstruction in a conscious choking victim.', 1, 7),
      mc('What are signs of a stroke you should recognize?', ['Sudden hunger, thirst, and sweating', 'Sudden face drooping, arm weakness, speech difficulty — remember FAST (Face, Arms, Speech, Time)', 'Slow onset of headache and nausea', 'Chest pain and shortness of breath'], 'Sudden face drooping, arm weakness, speech difficulty — remember FAST (Face, Arms, Speech, Time)', 'FAST is the stroke recognition tool: Face drooping, Arm weakness, Speech difficulty — Time to call 911. Speed is critical because brain tissue dies rapidly without blood.', 1, 8),
      oe('Someone collapses in front of you. Walk through exactly what you would do in the first few minutes.', 'Check scene safety. Tap shoulders and shout to check responsiveness. If unresponsive: call 911 (or tell someone specific to call). Open airway, check breathing (10 seconds). If not breathing normally: begin CPR — 30 chest compressions (100–120/min, 2" depth), 2 rescue breaths. Send someone for AED. Apply AED as soon as it arrives and follow its prompts. Continue CPR until EMS arrives or person recovers.', 'A strong answer follows the correct sequence: scene safety → responsiveness → 911 → breathing check → CPR → AED. No critical steps skipped or out of order.', 2, 9),
      oe('Why is it important for non-medical people to learn basic first aid and CPR, even when 911 is available?', 'EMS response times average 7–14 minutes — brain death from cardiac arrest begins within 4–6 minutes. Bystander CPR doubles or triples survival rates. First aid for bleeding can prevent death from hemorrhage in minutes. Most emergencies happen in places with people who aren\'t medical professionals. The skills are simple, trainable, and may be the difference between life and death before professionals arrive.', 'A strong answer gives the specific time window, survival rate data, and explains bystander effectiveness.', 2, 10),
    ],
  },

  'fitness-and-exercise': {
    title: 'Fitness and Exercise Assessment',
    passingScore: 75,
    timeLimitMin: 30,
    questions: [
      mc('What are the main components of physical fitness?', ['Only strength and endurance', 'Cardiovascular endurance, muscular strength, muscular endurance, flexibility, and body composition', 'Speed, agility, and power', 'Aerobic capacity only'], 'Cardiovascular endurance, muscular strength, muscular endurance, flexibility, and body composition', 'The five health-related fitness components are cardiorespiratory endurance, muscular strength, muscular endurance, flexibility, and body composition. All contribute to overall health.', 1, 1),
      mc('What is progressive overload?', ['Never increasing workout intensity', 'Gradually increasing training stimulus (weight, volume, intensity) to continue adaptation', 'Doing the same workout daily', 'Adding variety to prevent boredom'], 'Gradually increasing training stimulus (weight, volume, intensity) to continue adaptation', 'The body adapts to the demands placed on it. To continue improving, you must progressively increase the challenge — more weight, more reps, less rest, or higher intensity over time.', 1, 2),
      mc('What happens during the EPOC (excess post-exercise oxygen consumption) period?', ['Nothing — the body returns to baseline immediately', 'The body consumes extra oxygen and burns additional calories while recovering', 'Muscle soreness peaks', 'Protein synthesis stops'], 'The body consumes extra oxygen and burns additional calories while recovering', 'EPOC (the "afterburn effect") is the elevated metabolism after intense exercise as the body restores oxygen levels, removes lactate, and repairs tissue — continuing to burn calories post-workout.', 1, 3),
      mc('What is the difference between aerobic and anaerobic exercise?', ['Aerobic is outdoors; anaerobic is indoors', 'Aerobic uses oxygen for sustained energy; anaerobic uses stored energy without oxygen for short intense efforts', 'Anaerobic is safer', 'They have the same effect on the body'], 'Aerobic uses oxygen for sustained energy; anaerobic uses stored energy without oxygen for short intense efforts', 'Aerobic exercise (jogging, cycling) runs on oxygen — sustainable for long periods. Anaerobic exercise (sprinting, heavy lifting) exceeds the oxygen supply capacity and uses ATP-PC and glycolytic pathways.', 1, 4),
      mc('What is delayed onset muscle soreness (DOMS)?', ['Injury from improper form', 'Soreness appearing 24–72 hours after exercise, caused by microscopic muscle damage', 'Lactic acid buildup during exercise', 'A sign of overtraining'], 'Soreness appearing 24–72 hours after exercise, caused by microscopic muscle damage', 'DOMS is normal after novel or intense exercise — especially eccentric movements. It\'s caused by micro-tears that trigger inflammation and repair, leading to adaptation (muscle growth).', 1, 5),
      mc('What is the recommended amount of moderate-intensity aerobic exercise per week for adults?', ['30 minutes once a week', 'At least 150 minutes per week', 'At least 500 minutes per week', '60 minutes every other day only'], 'At least 150 minutes per week', 'Current guidelines from the CDC and WHO recommend 150–300 minutes of moderate-intensity aerobic activity weekly (or 75–150 minutes vigorous), plus muscle-strengthening activities twice a week.', 1, 6),
      mc('What is the primary role of a warm-up before exercise?', ['To burn extra calories', 'To gradually increase heart rate, blood flow to muscles, and joint mobility — reducing injury risk', 'To stretch muscles to maximum length', 'To hydrate before activity'], 'To gradually increase heart rate, blood flow to muscles, and joint mobility — reducing injury risk', 'A proper warm-up raises body temperature, increases muscle pliability, primes the neuromuscular system, and mentally prepares you — reducing injury risk and improving performance.', 1, 7),
      mc('What does "resting heart rate" indicate about fitness?', ['Nothing — it varies too much', 'A lower resting heart rate generally indicates better cardiovascular fitness', 'Higher is always healthier', 'It only measures stress levels'], 'A lower resting heart rate generally indicates better cardiovascular fitness', 'Trained hearts pump more blood per beat (higher stroke volume), so they don\'t need to beat as often to deliver oxygen. Average resting HR is 60–100 BPM; well-trained athletes can have rates in the 40s.', 1, 8),
      oe('Explain how resistance training leads to muscle growth at the cellular level.', 'Resistance training creates mechanical stress and micro-damage in muscle fibers. This triggers an inflammatory response and activates satellite cells (muscle stem cells). During recovery, satellite cells repair and fuse with muscle fibers, and protein synthesis adds contractile proteins (actin and myosin), increasing fiber size (hypertrophy). Without adequate protein and recovery, the process is incomplete. This is why nutrition and rest are as important as the workout itself.', 'A strong answer mentions micro-damage, protein synthesis, recovery requirement, and the cellular mechanism — not just "muscles get bigger."', 2, 9),
      oe('Why is rest and recovery an essential part of a training program, not just an afterthought?', 'Adaptation happens during rest, not during the workout. The workout is the stimulus; recovery is when muscles repair, grow, and neural adaptations consolidate. Without adequate rest: overtraining syndrome (performance decreases, injury risk increases, immune suppression, mood disturbance). Sleep is when most recovery hormones (growth hormone) are released. Under-recovering is as harmful as under-training. The training cycle is stress → recovery → adaptation — all three are required.', 'A strong answer explains that adaptation happens during rest (not training), names overtraining consequences, and mentions sleep.', 2, 10),
    ],
  },

  'navigating-healthcare': {
    title: 'Navigating Healthcare Assessment',
    passingScore: 75,
    timeLimitMin: 30,
    questions: [
      mc('What is a primary care physician (PCP)?', ['A specialist in internal medicine only', 'A general doctor who provides comprehensive care and coordinates referrals to specialists', 'An emergency room doctor', 'A nurse practitioner only'], 'A general doctor who provides comprehensive care and coordinates referrals to specialists', 'PCPs (family medicine, internal medicine, general practitioners) are your main point of contact — they handle routine care, preventive medicine, chronic conditions, and refer to specialists as needed.', 1, 1),
      mc('What is the difference between urgent care and an emergency room?', ['Emergency rooms are faster', 'Urgent care handles non-life-threatening issues; ERs handle serious emergencies — ERs are more expensive', 'They provide identical services', 'Urgent care is for children only'], 'Urgent care handles non-life-threatening issues; ERs handle serious emergencies — ERs are more expensive', 'Use urgent care for injuries and illnesses that need attention today but aren\'t life-threatening (minor cuts, infections, sprained ankle). Use the ER for chest pain, difficulty breathing, severe bleeding, or stroke symptoms.', 1, 2),
      mc('What is preventive care?', ['Treatment after becoming ill', 'Healthcare focused on preventing disease through screenings, vaccinations, and healthy lifestyle support', 'Care only for elderly patients', 'Emergency medicine'], 'Healthcare focused on preventing disease through screenings, vaccinations, and healthy lifestyle support', 'Preventive care catches problems early or prevents them entirely — annual physicals, cancer screenings, blood pressure checks, and vaccines are all preventive and typically covered by insurance.', 1, 3),
      mc('What is informed consent?', ['A form you sign before any medical procedure automatically', 'Your right to understand a procedure\'s risks and benefits and agree to it before it\'s performed', 'Permission for doctors to share records', 'An insurance pre-authorization'], 'Your right to understand a procedure\'s risks and benefits and agree to it before it\'s performed', 'Informed consent means you have the right to know what a procedure involves, its risks and alternatives, and to agree or refuse before anything is done to you.', 1, 4),
      mc('What is HIPAA?', ['A health insurance program', 'A federal law protecting the privacy of your medical information', 'A patient bill of rights', 'A prescription drug coverage system'], 'A federal law protecting the privacy of your medical information', 'HIPAA (Health Insurance Portability and Accountability Act) restricts who can access or share your medical records — providers can only share information with your consent or for treatment purposes.', 1, 5),
      mc('What is a formulary in health insurance?', ['A list of covered doctors', 'A list of prescription drugs covered by an insurance plan, often with tiered cost-sharing', 'A medical diagnosis coding system', 'A list of covered procedures'], 'A list of prescription drugs covered by an insurance plan, often with tiered cost-sharing', 'Formularies categorize drugs by tier — generic drugs (tier 1) have lowest copays; brand-name and specialty drugs higher tiers. Always check if your medications are on your plan\'s formulary.', 1, 6),
      mc('What does it mean to get a "second opinion"?', ['Asking a friend what they think', 'Consulting another qualified physician to confirm or challenge a diagnosis or treatment plan', 'Researching your condition online', 'Asking a pharmacist about your prescription'], 'Consulting another qualified physician to confirm or confirm a diagnosis or treatment plan', 'Second opinions are appropriate for serious diagnoses, major surgeries, or when uncertain about a treatment. A reputable provider should support this — it\'s your right as a patient.', 1, 7),
      mc('What information should you bring to a new doctor\'s appointment?', ['Just your insurance card', 'Current medications list, medical history, family history, insurance info, and a list of questions', 'Only symptoms you are experiencing now', 'Previous diagnoses only'], 'Current medications list, medical history, family history, insurance info, and a list of questions', 'Being prepared maximizes a limited appointment. Medication lists prevent dangerous interactions. Family history helps identify risks. Questions ensure you leave with the information you need.', 1, 8),
      oe('What should you do if you receive a medical bill that seems higher than expected or contains charges for services you didn\'t receive?', 'Request an itemized bill — many bills are vague summaries. Compare it to your insurance Explanation of Benefits (EOB). If you see charges for services not received, contact the billing department immediately — billing errors are common. If charges are legitimate but high, ask about financial assistance programs, payment plans, or negotiate (especially if uninsured). File an insurance appeal if coverage was wrongly denied. Medical billing errors are extremely common and worth challenging.', 'A strong answer mentions requesting itemized bills, checking EOB, appealing denials, and financial assistance — not just "call and complain."', 2, 9),
      oe('Why is having a primary care doctor important even when you feel healthy?', 'PCPs provide continuity of care — they know your history and notice changes over time. Preventive screenings (colonoscopy, blood pressure, cholesterol, blood sugar) catch problems before symptoms appear, when they\'re most treatable. PCPs coordinate care when specialists are needed. Without one, people use the ER for non-emergencies (more expensive, no follow-up) or wait until conditions are advanced. Routine care is cheaper and more effective than treating advanced disease.', 'A strong answer makes the case with specific benefits: continuity, screening, coordination, cost.', 2, 10),
    ],
  },
}
