import type { ExerciseDef } from '../types'

function mc(
  question: string,
  options: string[],
  correctAnswer: string,
  explanation: string,
  order: number,
): ExerciseDef {
  return { question, type: 'MULTIPLE_CHOICE', options, correctAnswer, explanation, order }
}

export const healthExercises6: Record<string, ExerciseDef[]> = {
  'common-diet-myths': [
    mc('The myth that "carbs make you fat" is inaccurate because:', ['Carbohydrates have no calories', 'Excess calories — from any macronutrient — cause fat gain; carbs are not uniquely fattening', 'The body can only store carbs as glycogen, never as fat', 'Low-carb diets have been proven ineffective'], 'Excess calories — from any macronutrient — cause fat gain; carbs are not uniquely fattening', 'The body stores excess energy as fat regardless of the macronutrient source. The real problem with many carb-rich foods is that they are refined, easy to overconsume, and low in fiber — not that carbohydrates as a category cause fat gain.', 1),
    mc('What does research say about commercial "detox" or "cleanse" products?', ['They effectively remove toxins the liver cannot handle', 'They are beneficial for short-term use after unhealthy eating', 'There is no credible scientific evidence they remove toxins or provide health benefits', 'They are regulated by the FDA for efficacy'], 'There is no credible scientific evidence they remove toxins or provide health benefits', 'Your liver and kidneys continuously filter and remove waste products without outside help. "Detox" products never name the specific toxins they remove, never explain a plausible mechanism, and have no evidence base. The term is marketing, not biology.', 2),
    mc('The claim that "breakfast is the most important meal of the day" originated from:', ['A landmark medical journal study', 'A marketing campaign, not scientific evidence', 'USDA dietary guidelines from the 1970s', 'Research on children\'s academic performance'], 'A marketing campaign, not scientific evidence', 'The "breakfast is most important" claim has roots in advertising, not nutrition science. Research on breakfast is complex — people who skip breakfast without being hungry don\'t show worse health outcomes in controlled studies.', 3),
    mc('For people without celiac disease or gluten sensitivity, a gluten-free diet:', ['Improves gut health for everyone', 'Has no evidence of benefit and may be lower in fiber and nutrients than whole-grain alternatives', 'Is recommended by most gastroenterologists preventively', 'Reduces bloating in all people'], 'Has no evidence of benefit and may be lower in fiber and nutrients than whole-grain alternatives', 'For the estimated 99% of people without celiac disease, avoiding gluten provides no demonstrated health benefit. Gluten-free products are often more expensive, lower in fiber, and less nutritious than the whole-grain products they replace.', 4),
    mc('Eating 6 small meals versus 3 larger meals per day:', ['Significantly boosts metabolism through more frequent digestion', 'Has no metabolic advantage — total food intake determines total thermic effect', 'Prevents blood sugar crashes that increase fat storage', 'Is always better because it prevents overeating'], 'Has no metabolic advantage — total food intake determines total thermic effect', 'The thermic effect of food is determined by total caloric intake across the day, not by how many meals it is divided into. Six small meals and three larger meals with identical calories and macronutrients have the same total thermic effect.', 5),
  ],

  'special-dietary-needs': [
    mc('Which nutrient is non-negotiable as a supplement for vegans because deficiency causes irreversible nerve damage?', ['Iron', 'Vitamin D', 'Vitamin B12', 'Zinc'], 'Vitamin B12', 'Vitamin B12 is found almost exclusively in animal products. Vegans who don\'t supplement or consume B12-fortified foods will develop deficiency, which causes irreversible peripheral neuropathy and megaloblastic anemia. Supplementation is not optional.', 1),
    mc('During pregnancy, which nutrient is most critical before and in early pregnancy to prevent neural tube defects?', ['Iron', 'Calcium', 'Folate (folic acid)', 'DHA'], 'Folate (folic acid)', 'Folate is essential for DNA synthesis during the rapid cell division of fetal development. Deficiency in early pregnancy causes neural tube defects like spina bifida. 400–800 mcg/day starting before conception is recommended.', 2),
    mc('For infants under 6 months, what is the recommended exclusive feeding method?', ['Iron-fortified cereals starting at 4 months', 'Breast milk or formula only', 'Diluted fruit juice to supplement vitamins', 'A combination of breast milk and solid foods'], 'Breast milk or formula only', 'For the first 6 months, breast milk or formula exclusively is recommended. Breast milk is nutritionally optimal and provides immune benefits; formula is a safe alternative. Solid foods should not be introduced until around 6 months.', 3),
    mc('As people age, protein needs generally:', ['Decrease because muscle activity is reduced', 'Stay exactly the same throughout adult life', 'Increase because of accelerated muscle loss and reduced protein efficiency', 'Become irrelevant because calorie needs drop significantly'], 'Increase because of accelerated muscle loss and reduced protein efficiency', 'Sarcopenia — age-related muscle loss — accelerates with age. Older adults also process dietary protein less efficiently. Higher protein intake (1.0–1.2g/kg or more) combined with resistance exercise is the primary strategy for preserving muscle mass and function.', 4),
    mc('Food allergies differ from food intolerances primarily because:', ['Allergies only affect the digestive system', 'Allergies are immune-mediated and can be life-threatening; intolerances are non-immune and typically cause GI symptoms', 'Intolerances are more severe and require complete avoidance', 'Allergies are permanent; intolerances can be outgrown'], 'Allergies are immune-mediated and can be life-threatening; intolerances are non-immune and typically cause GI symptoms', 'Food allergies involve the immune system and can cause anaphylaxis — a life-threatening systemic reaction. Food intolerances (like lactose intolerance) are non-immune-mediated, causing uncomfortable but not dangerous GI symptoms. Management strategies differ significantly.', 5),
  ],

  'what-is-mental-health': [
    mc('Good mental health is best described as:', ['Being happy and positive at all times', 'The ability to cope with stress, work productively, and maintain relationships', 'The complete absence of any diagnosable mental disorder', 'Having no history of trauma or emotional difficulty'], 'The ability to cope with stress, work productively, and maintain relationships', 'Good mental health does not mean constant happiness. It means handling normal life stresses, functioning at work, maintaining meaningful relationships, and bouncing back from adversity. Everyone has mental health, and it exists on a spectrum that changes over time.', 1),
    mc('The statement that mental health conditions are biological, not moral failures, is supported by:', ['Cultural beliefs about mental strength', 'Brain scans showing structural differences, genetic studies, and neurochemical changes in people with these conditions', 'The fact that therapy and willpower can cure all conditions', 'Historical records of mental illness in all societies'], 'Brain scans showing structural differences, genetic studies, and neurochemical changes in people with these conditions', 'Mental health conditions involve measurable biological changes — structural and functional differences on brain imaging, genetic heritability, and disruptions in neurotransmitter systems. Physical conditions like thyroid disorders can also cause mental health symptoms. These are biological conditions, not character failures.', 2),
    mc('Approximately what fraction of U.S. adults will experience a diagnosable mental disorder in their lifetime?', ['1 in 10', '1 in 5', 'Nearly 1 in 2', '1 in 20'], 'Nearly 1 in 2', 'Mental health conditions are extremely common. About 1 in 5 adults experience one in any given year, and nearly 1 in 2 will have a diagnosable mental disorder at some point in their lifetime. Mental health conditions are a normal part of human experience.', 3),
    mc('The DSM-5 is:', ['A medication database listing approved psychiatric drugs', 'A diagnostic manual classifying mental disorders used by clinicians', 'A federal program funding mental health treatment', 'A standardized test measuring cognitive function'], 'A diagnostic manual classifying mental disorders used by clinicians', 'The DSM-5 (Diagnostic and Statistical Manual of Mental Disorders) is published by the American Psychiatric Association and provides the shared framework clinicians use to diagnose mental disorders. It is updated as knowledge evolves.', 4),
    mc('A normal emotional experience crosses into a mental disorder when it is:', ['Caused by a specific identifiable event', 'Persistent, disproportionate, and significantly impairs daily functioning', 'Experienced by fewer than 10% of people', 'Accompanied by physical symptoms'], 'Persistent, disproportionate, and significantly impairs daily functioning', 'Grief, anxiety before stressful events, and sadness are normal experiences. They become disorders when they persist beyond what circumstances warrant, are disproportionate, and significantly interfere with work, relationships, or daily function.', 5),
  ],
}
