import type { ExerciseDef } from '../types'

function mc(
  question: string,
  options: string[],
  correctAnswer: string,
  explanation: string,
  order: number,
): ExerciseDef {
  return { question, type: 'MULTIPLE_CHOICE', options, correctAnswer, explanation, order }
}

export const healthExercises3: Record<string, ExerciseDef[]> = {
  'nervous-system': [
    mc('The "fight or flight" response is controlled by which branch of the autonomic nervous system?', ['Somatic nervous system', 'Parasympathetic nervous system', 'Central nervous system', 'Sympathetic nervous system'], 'Sympathetic nervous system', 'The sympathetic nervous system activates fight-or-flight — increasing heart rate, dilating airways, redirecting blood to muscles, and suppressing digestion. The parasympathetic ("rest and digest") system is active during calm states.', 1),
    mc('Myelin sheaths around axons serve what purpose?', ['Supply nutrients to the neuron', 'Store neurotransmitters for release', 'Dramatically speed up electrical signal transmission', 'Connect neurons to muscle fibers'], 'Dramatically speed up electrical signal transmission', 'Myelin is a fatty coating that insulates axons and allows electrical signals to jump between nodes, dramatically increasing transmission speed. Multiple sclerosis destroys myelin, causing progressive loss of nervous system function.', 2),
    mc('The hippocampus is primarily associated with:', ['Voluntary muscle movement', 'Converting short-term memories to long-term storage', 'Regulating heart rate and breathing', 'Processing visual information'], 'Converting short-term memories to long-term storage', 'The hippocampus is critical for memory consolidation. Alzheimer\'s disease characteristically damages the hippocampus first, which is why memory loss is the earliest symptom.', 3),
    mc('Dopamine, serotonin, and GABA are examples of:', ['Hormones produced by endocrine glands', 'Neurotransmitters — chemical messengers that carry signals between neurons', 'Enzymes that break down neural tissue', 'Myelin proteins that protect axons'], 'Neurotransmitters — chemical messengers that carry signals between neurons', 'Neurotransmitters are chemicals released across synapses to transmit signals between neurons. Dopamine is associated with reward; serotonin with mood and sleep; GABA with inhibition and calming. Many psychiatric medications alter neurotransmitter levels.', 4),
    mc('Parkinson\'s disease involves the loss of neurons that produce:', ['Serotonin', 'Acetylcholine', 'Dopamine', 'Norepinephrine'], 'Dopamine', 'Parkinson\'s disease results from progressive loss of dopamine-producing neurons in the substantia nigra. The resulting dopamine deficit causes tremors, rigidity, and slowed movement. Dopamine replacement therapies help manage symptoms.', 5),
  ],

  'musculoskeletal-system': [
    mc('Beyond providing structure, bones also serve which function?', ['Producing digestive enzymes', 'Generating body heat', 'Producing red blood cells, white blood cells, and platelets in bone marrow', 'Regulating hormone production'], 'Producing red blood cells, white blood cells, and platelets in bone marrow', 'Red marrow in flat bones and the ends of long bones produces all blood cells — red blood cells, white blood cells, and platelets. Bones also store calcium and phosphorus and protect vital organs.', 1),
    mc('Bone remodeling involves:', ['Osteoblasts building new bone and osteoclasts breaking it down', 'Osteoclasts only, removing damaged bone permanently', 'Tendons and ligaments being replaced by bone', 'Calcium being removed from blood permanently'], 'Osteoblasts building new bone and osteoclasts breaking it down', 'Bone is living tissue constantly undergoing remodeling. Osteoclasts break down old bone; osteoblasts build new bone. Exercise creates mechanical stress that stimulates osteoblasts — which is why weight-bearing exercise prevents osteoporosis.', 2),
    mc('Tendons connect muscle to bone. What connects bone to bone?', ['Cartilage', 'Ligaments', 'Fascia', 'Synovial fluid'], 'Ligaments', 'Tendons connect muscle to bone. Ligaments connect bone to bone, stabilizing joints. A sprain is an injury to a ligament; a strain is an injury to a muscle or tendon.', 3),
    mc('Muscles grow larger through what mechanism?', ['New muscle cells created during exercise', 'Satellite cells repairing micro-tears and adding contractile protein during recovery', 'Increased blood flow enlarging existing fibers', 'Fat cells converting to muscle cells'], 'Satellite cells repairing micro-tears and adding contractile protein during recovery', 'Resistance training creates microscopic damage to muscle fibers. Satellite cells (muscle stem cells) repair this damage and add new contractile protein, making the fiber slightly larger and stronger. Recovery is essential — without it, no growth occurs.', 4),
    mc('Osteoporosis is characterized by:', ['Inflamed cartilage in joints', 'Loss of bone density making bones brittle and fracture-prone', 'Overactive osteoblasts producing too much bone', 'Muscle weakness from calcium deficiency'], 'Loss of bone density making bones brittle and fracture-prone', 'Osteoporosis involves reduced bone density, making bones fragile and prone to fractures. It is common in older women after menopause when estrogen (which protects bone) declines. Prevention includes calcium, vitamin D, and weight-bearing exercise.', 5),
  ],

  'immune-system': [
    mc('What is the difference between innate and adaptive immunity?', ['Innate is acquired through vaccines; adaptive is present from birth', 'Innate is fast and non-specific; adaptive is slower but precisely targeted and builds lasting memory', 'Innate uses B cells; adaptive uses neutrophils', 'Innate protects only the skin; adaptive protects internal organs'], 'Innate is fast and non-specific; adaptive is slower but precisely targeted and builds lasting memory', 'Innate immunity responds immediately to any threat using physical barriers and non-specific cells. Adaptive immunity takes days to activate but recognizes specific antigens, produces antibodies, and creates memory cells for faster future responses.', 1),
    mc('How do vaccines protect against disease?', ['They kill pathogens already in the bloodstream', 'They expose the immune system to a harmless form of a pathogen so it builds memory cells', 'They strengthen physical barriers like skin', 'They boost white blood cell counts permanently'], 'They expose the immune system to a harmless form of a pathogen so it builds memory cells', 'Vaccines present a safe form of a pathogen — weakened, killed, a fragment, or mRNA instructions. The immune system mounts a response and creates memory cells. When the real pathogen appears later, the rapid memory response eliminates it.', 2),
    mc('B cells in the adaptive immune system produce:', ['Cytotoxic T cells', 'Antibodies that bind to specific antigens', 'Natural killer cells for cancer surveillance', 'Macrophages that engulf pathogens'], 'Antibodies that bind to specific antigens', 'B cells are lymphocytes that produce antibodies — Y-shaped proteins that bind to specific antigens on pathogens. Antibodies neutralize pathogens, mark them for destruction, and activate other immune components.', 3),
    mc('In an allergic reaction, the immune system is responding to:', ['A genuine pathogen that needs to be eliminated', 'A harmless substance as if it were a dangerous pathogen', 'A failure of innate immunity to detect real threats', 'Self-tissue incorrectly identified as foreign'], 'A harmless substance as if it were a dangerous pathogen', 'Allergies are exaggerated immune responses to harmless substances like pollen or peanut proteins. The immune system mistakenly treats these as dangerous, triggering inflammation and in severe cases (anaphylaxis), a life-threatening whole-body reaction.', 4),
    mc('HIV/AIDS progressively weakens immunity by destroying:', ['Natural killer cells', 'Helper T cells (CD4+ cells)', 'B cells that produce antibodies', 'Bone marrow stem cells'], 'Helper T cells (CD4+ cells)', 'HIV specifically infects and destroys CD4+ helper T cells — the coordinators of the adaptive immune response. As helper T cell counts drop, the ability to fight infections and cancer collapses. AIDS is the advanced stage when immunity is severely compromised.', 5),
  ],
}
