import type { ExerciseDef } from '../types'

function mc(
  question: string,
  options: string[],
  correctAnswer: string,
  explanation: string,
  order: number,
): ExerciseDef {
  return { question, type: 'MULTIPLE_CHOICE', options, correctAnswer, explanation, order }
}

export const healthExercises13: Record<string, ExerciseDef[]> = {
  'designing-a-workout-plan': [
    mc('For a complete beginner to strength training, which program structure is most recommended?', ['Push/pull/legs 6 days per week for maximum volume', 'Full body 3 days per week for higher stimulus frequency', 'Upper/lower 4 days per week for balanced volume', 'Single muscle-group isolation sessions daily'], 'Full body 3 days per week for higher stimulus frequency', 'Beginners benefit most from training each muscle group frequently — 3 times per week. Full body sessions achieve this with only 3 training days. At the beginner stage, neural adaptations require frequent practice of movements, and the lower total volume per session is appropriate for recovery capacity.', 1),
    mc('In a strength training session, compound movements should be performed:', ['Last, after isolation work has pre-exhausted the muscles', 'First, when energy and focus are highest', 'In the middle, after a thorough warm-up but before fatigue sets in', 'At any order — exercise sequence does not matter'], 'First, when energy and focus are highest', 'Compound movements (squat, deadlift, bench press, row, overhead press) require the most energy, coordination, and focus. Performing them early in the session — when you\'re fresh — allows maximum effort and reduces injury risk from poor form due to fatigue.', 2),
    mc('A balanced strength program should include which movement patterns?', ['Primarily pushing movements, as these are most functional', 'Squat, hip hinge, horizontal push and pull, vertical push and pull, and core', 'Only compound movements — isolation exercises have no value', 'Pushing and pulling in equal proportion, with minimal leg work'], 'Squat, hip hinge, horizontal push and pull, vertical push and pull, and core', 'Covering all major movement patterns ensures balanced muscular development and reduces injury risk from asymmetries. Missing patterns (especially horizontal pulling or hip hinge) are common causes of imbalances and eventual injury.', 3),
    mc('Why is tracking workouts important for progressive overload?', ['It helps count calories burned during each session', 'It lets you know exactly what you did before so you can systematically beat it next time', 'It provides motivation through social sharing', 'It is required by most beginner programs'], 'It lets you know exactly what you did before so you can systematically beat it next time', 'Progressive overload requires increasing the challenge over time. Without a record of previous weights, sets, and reps, you\'re guessing. Tracking creates a feedback loop — you know your last performance and have a concrete target to beat.', 4),
    mc('Programs like StrongLifts 5×5 are effective for beginners primarily because:', ['They use very high volume to maximize muscle damage', 'They are simple, proven, and apply progressive overload systematically', 'They focus exclusively on isolation exercises for targeted muscle growth', 'They require minimal time — under 20 minutes per session'], 'They are simple, proven, and apply progressive overload systematically', 'Beginner programs like StrongLifts 5×5 succeed because they are simple enough to execute consistently, use compound movements that produce broad adaptations, and apply progressive overload automatically (add weight when you hit the target). Complexity is the enemy of adherence for beginners.', 5),
  ],

  'recovery-and-rest': [
    mc('Why is sleep the most important recovery tool for athletes and exercisers?', ['Sleep burns fat, helping maintain body composition during training', 'Growth hormone is primarily released during deep sleep, driving muscle repair and adaptation', 'Sleep prevents cortisol from being released after workouts', 'Sleep maximizes the anabolic window after resistance training'], 'Growth hormone is primarily released during deep sleep, driving muscle repair and adaptation', 'Most growth hormone secretion — which drives tissue repair, muscle protein synthesis, and other recovery processes — occurs during deep (slow-wave) sleep. Inadequate sleep disrupts this hormone release along with glycogen replenishment, increases cortisol, and impairs all aspects of recovery.', 1),
    mc('Active recovery (light movement on rest days) is beneficial because:', ['It burns calories without adding training stress', 'It promotes blood flow to healing muscles and helps clear metabolic waste', 'It maintains cardio fitness during strength-focused training blocks', 'It signals to the body to stay in an anabolic state'], 'It promotes blood flow to healing muscles and helps clear metabolic waste', 'Light movement — walking, easy cycling, gentle yoga — increases circulation to recovering muscles, helping deliver nutrients and clear waste products from exercise. This reduces soreness and stiffness without adding meaningful training stress.', 2),
    mc('The minimum recommended rest before training the same muscle group again at high intensity is:', ['12 hours', '48 hours', '72 hours', '24 hours'], '48 hours', 'Muscle protein synthesis and repair after intense resistance training takes 24–72 hours depending on the person and intensity. Working the same muscle again before sufficient recovery interrupts the repair process. 48 hours is the general minimum guideline; beginners and those doing very intense sessions may need the full 72.', 3),
    mc('An elevated resting heart rate 5+ beats above normal is a sign of:', ['Improved cardiovascular fitness from training', 'Inadequate recovery — the body is still stressed from previous training', 'Overhydration affecting blood volume', 'Normal day-to-day variation with no training implication'], 'Inadequate recovery — the body is still stressed from previous training', 'A consistently elevated resting heart rate (compared to your personal baseline) is a reliable signal of accumulated fatigue and inadequate recovery. The nervous system and cardiovascular system are still in a stress state. It is one of the most objective early signs that more rest is needed.', 4),
    mc('Post-workout protein consumption (20–40g) is most important for:', ['Immediately replacing glycogen stores depleted by exercise', 'Supporting muscle protein synthesis during the recovery window', 'Preventing muscle breakdown (catabolism) during the workout itself', 'Replacing electrolytes lost through sweating'], 'Supporting muscle protein synthesis during the recovery window', 'Resistance training signals the body to rebuild muscle fibers. Protein provides the amino acids needed for this synthesis. Consuming protein in the hours after training supports this process. However, total daily protein intake matters more than precise timing for most people.', 5),
  ],

  'exercise-without-a-gym': [
    mc('The primary advantage of exercising without a gym is:', ['Lower injury risk from bodyweight-only training', 'Removing friction — no commute, no schedule, no membership barrier', 'Better access to progressive overload tools', 'Greater social accountability from other exercisers'], 'Removing friction — no commute, no schedule, no membership barrier', 'The biggest barrier to exercise consistency for many people is friction — the effort of getting to the gym. Exercising at home or outdoors removes this friction entirely. Even a modest reduction in barriers can be the difference between exercising and not.', 1),
    mc('To apply progressive overload without a gym, bodyweight exercises can be progressed by:', ['Doing more reps indefinitely — there is no upper limit on bodyweight difficulty', 'Moving to harder exercise variations as easier ones become manageable', 'Reducing rest time only — the exercises themselves cannot be made harder', 'Switching between exercises each session to keep the body guessing'], 'Moving to harder exercise variations as easier ones become manageable', 'Bodyweight training has clear progressions: push-up → archer push-up → one-arm push-up; bodyweight squat → Bulgarian split squat → pistol squat. These progressions increase difficulty significantly without adding external weight, allowing genuine progressive overload.', 2),
    mc('A doorframe pull-up bar ($20–35) is particularly valuable for home training because:', ['It can be used for over 100 different exercises', 'It enables back and biceps training (rows, pull-ups) that is otherwise difficult without equipment', 'It is the most cost-effective piece of equipment for cardiovascular training', 'It replaces the need for resistance bands entirely'], 'It enables back and biceps training (rows, pull-ups) that is otherwise difficult without equipment', 'Back training is the hardest component to achieve with purely bodyweight exercises. A pull-up bar enables rows (horizontal pull), pull-ups (vertical pull), chin-ups, and hanging core work — covering the back and biceps movement patterns that are otherwise nearly impossible without equipment.', 3),
    mc('For cardiovascular training without equipment, which option is most accessible?', ['Swimming — a full-body low-impact workout', 'Brisk walking — free, low-injury-risk, and meets aerobic guidelines', 'Cycling — joint-friendly and highly effective', 'High-intensity interval training with jumping exercises'], 'Brisk walking — free, low-injury-risk, and meets aerobic guidelines', 'Brisk walking for 30–60 minutes meets aerobic activity guidelines and produces substantial health benefits. It requires no equipment, has very low injury risk, and is accessible to nearly all fitness levels. It is underrated as a primary exercise modality.', 4),
    mc('What is the primary disadvantage of home exercise compared to gym training?', ['Home exercise cannot achieve progressive overload', 'Lack of environmental cues and social context makes self-motivation harder', 'Bodyweight training is not effective for building real strength', 'Home workouts cannot target major muscle groups adequately'], 'Lack of environmental cues and social context makes self-motivation harder', 'The gym provides environmental cues — being there signals that exercise is what you do there — and social context of others training around you. Without these, home exercise requires more self-direction and deliberate habit-building. The fix is strategies like a set time, visible equipment, and structured programs.', 5),
  ],
}
