import type { ExerciseDef } from '../types'

function mc(
  question: string,
  options: string[],
  correctAnswer: string,
  explanation: string,
  order: number,
): ExerciseDef {
  return { question, type: 'MULTIPLE_CHOICE', options, correctAnswer, explanation, order }
}

export const healthExercises10: Record<string, ExerciseDef[]> = {
  'cpr-basics': [
    mc('CPR is started when a person is:', ['Conscious but complaining of chest pain', 'Unconscious with slow, shallow breathing', 'Unresponsive and not breathing or only gasping', 'Experiencing a seizure and temporarily unresponsive'], 'Unresponsive and not breathing or only gasping', 'CPR is indicated for cardiac arrest: unresponsiveness combined with absent or abnormal breathing. Occasional gasps (agonal breathing) are not normal breathing — they indicate cardiac arrest. If unsure whether someone is breathing normally, start CPR.', 1),
    mc('For adult CPR, the correct compression depth is:', ['At least 1 inch (2.5 cm)', 'At least 2 inches (5 cm)', 'No more than 1.5 inches to avoid rib fractures', 'As deep as physically possible'], 'At least 2 inches (5 cm)', 'Chest compressions must be at least 2 inches (5 cm) deep to be effective — they must compress the heart against the spine to circulate blood. The most common CPR mistake is not pressing hard enough. Allow full chest recoil between compressions.', 2),
    mc('The correct compression rate for CPR is:', ['60–80 compressions per minute', '100–120 compressions per minute', '80–100 compressions per minute', 'As fast as possible'], '100–120 compressions per minute', '100–120 compressions per minute is the target — fast but controlled. The tempo of "Stayin\' Alive" by the Bee Gees (~100 BPM) is a commonly used memory aid. Too slow fails to maintain circulation; too fast prevents full chest recoil.', 3),
    mc('For infants under 1 year, CPR compressions should be performed using:', ['The heel of one hand, same as for adults', 'Both thumbs with hands encircling the chest', 'Two fingers on the center of the chest just below the nipple line', 'A full hand compression at adult depth'], 'Two fingers on the center of the chest just below the nipple line', 'Infant CPR uses two fingers (index and middle) on the center of the chest just below the nipple line, compressing to 1.5 inches depth. This technique is appropriate for the infant\'s smaller, more fragile chest.', 4),
    mc('What can CPR alone do in cardiac arrest, and why does an AED matter?', ['CPR alone restarts the heart in most cases; AEDs are supplementary', 'CPR circulates blood temporarily but cannot fix the abnormal heart rhythm — only a defibrillator can restore normal rhythm', 'CPR alone is as effective as CPR plus AED for the first 10 minutes', 'AEDs are only useful when CPR has failed after 5 minutes'], 'CPR circulates blood temporarily but cannot fix the abnormal heart rhythm — only a defibrillator can restore normal rhythm', 'CPR maintains some blood circulation, preserving brain function while buying time. Most sudden cardiac arrests involve ventricular fibrillation — a chaotic rhythm only a defibrillator can correct. Getting an AED quickly is as important as starting CPR quickly.', 5),
  ],

  'aed-use': [
    mc('AEDs are designed to be used by:', ['Only trained paramedics and EMTs', 'Physicians and nurses in clinical settings', 'Anyone — the device analyzes the rhythm and only delivers a shock if needed', 'People who have completed an 8-hour first aid certification'], 'Anyone — the device analyzes the rhythm and only delivers a shock if needed', 'AEDs are specifically designed for bystander use with no medical training. The device detects the heart rhythm and will only advise a shock if a shockable rhythm is present. You cannot accidentally shock someone who doesn\'t need it.', 1),
    mc('The primary reason to use an AED as quickly as possible is:', ['CPR becomes ineffective after 5 minutes', 'Survival probability decreases approximately 10% for every minute without defibrillation', 'AEDs become ineffective if used more than 10 minutes after cardiac arrest', 'Brain death occurs within 3 minutes without defibrillation'], 'Survival probability decreases approximately 10% for every minute without defibrillation', 'Most sudden cardiac arrests involve ventricular fibrillation, which only a defibrillator can correct. Survival drops approximately 10% per minute without defibrillation. With CPR and early defibrillation, survival rates in some settings exceed 50%.', 2),
    mc('After delivering a shock with an AED, you should immediately:', ['Check for a pulse before anything else', 'Remove the pads in case another shock is needed', 'Resume CPR starting with compressions', 'Wait 2 minutes before taking any action'], 'Resume CPR starting with compressions', 'Immediately after the shock, resume CPR — even if the person appears to have recovered. The AED will guide you to analyze again after 2 minutes of CPR. Do not pause to check for a pulse, which is unreliable and wastes precious time.', 3),
    mc('If an AED\'s analysis indicates "No shock advised," you should:', ['Check if pads are attached and try again', 'Stop and wait for EMS', 'Continue CPR immediately — the AED will prompt when to analyze again', 'Assume the person has recovered'], 'Continue CPR immediately — the AED will prompt when to analyze again', '"No shock advised" means the heart is not in a shockable rhythm. Resume CPR immediately — the person still needs circulation maintained, and a shockable rhythm may develop. The AED will continue to analyze periodically.', 4),
    mc('AEDs are commonly found in:', ['Only hospitals and medical facilities', 'Primarily pharmacies and medical supply stores', 'Airports, gyms, shopping malls, schools, and office buildings', 'Police and fire stations only'], 'Airports, gyms, shopping malls, schools, and office buildings', 'AEDs are required or strongly recommended in many public places — airports, gyms, malls, schools, stadiums, hotels, and workplaces. They are typically in bright orange or green cases mounted on walls. When you call 911, dispatchers often know where the nearest AED is.', 5),
  ],

  'choking': [
    mc('The universal sign that someone is choking is:', ['Clutching the throat with one or both hands', 'Coughing loudly and forcefully', 'Pointing to their mouth and making sounds', 'Turning red in the face and gasping'], 'Clutching the throat with one or both hands', 'The universal choking sign is clutching the throat with both hands. Someone with a complete obstruction cannot speak, cough effectively, or make meaningful sounds. If they can answer "Are you choking?" verbally, the airway is not fully blocked.', 1),
    mc('For abdominal thrusts (Heimlich maneuver), where should the fist be positioned?', ['Just below the chin on the lower neck', 'Directly over the sternum at chest level', 'Above the navel and well below the breastbone', 'At the level of the lower ribs on both sides'], 'Above the navel and well below the breastbone', 'The fist should be thumb-side against the abdomen above the navel and well below the breastbone. Thrusts should be quick, firm, and inward-and-upward. Proper placement avoids injuring the ribs while maximizing the force to expel the obstruction.', 2),
    mc('If a choking victim becomes unconscious, the appropriate response is:', ['Continue abdominal thrusts in the same standing position', 'Lower them to the floor carefully and begin CPR', 'Roll them onto their side and wait for EMS', 'Attempt a blind finger sweep to remove the object'], 'Lower them to the floor carefully and begin CPR', 'If a choking victim loses consciousness, lower them to the floor, call 911, and begin CPR. Chest compressions may help dislodge the object. Before rescue breaths, look in the mouth — if you can see the object, remove it. Never do a blind finger sweep.', 3),
    mc('Why are abdominal thrusts never used on infants under 1 year?', ['Their diaphragms are too strong to respond to abdominal pressure', 'The technique would compress the stomach rather than the airway', 'Their abdomens are too small and the technique could cause serious internal injury', 'Infants cannot be positioned correctly for the maneuver'], 'Their abdomens are too small and the technique could cause serious internal injury', 'Abdominal thrusts on infants risk serious organ damage. Instead use back blows and chest thrusts: support the infant face-down on your forearm (head lower), give 5 firm back blows, turn face-up, give 5 chest thrusts, and alternate until the object is dislodged.', 4),
    mc('Chest thrusts replace abdominal thrusts for a choking adult when:', ['The person is sitting rather than standing', 'The victim is pregnant or obese and the abdomen cannot be effectively compressed', 'The choking has lasted more than 2 minutes', 'The person is elderly or has osteoporosis'], 'The victim is pregnant or obese and the abdomen cannot be effectively compressed', 'Chest thrusts (at the center of the sternum, same location as CPR compressions) are used when abdominal thrusts cannot be effectively delivered — primarily in pregnancy (where abdominal pressure could harm the fetus) or in severe obesity.', 5),
  ],
}
