import type { ExerciseDef } from '../types'

function mc(
  question: string,
  options: string[],
  correctAnswer: string,
  explanation: string,
  order: number,
): ExerciseDef {
  return { question, type: 'MULTIPLE_CHOICE', options, correctAnswer, explanation, order }
}

export const healthExercises14: Record<string, ExerciseDef[]> = {
  'primary-care-and-specialists': [
    mc('What distinguishes a primary care physician (PCP) from a specialist?', ['PCPs have more years of training than specialists', 'PCPs are generalists who manage broad health needs and coordinate specialist care', 'Specialists handle both routine and complex care; PCPs only do screenings', 'PCPs only treat children and young adults'], 'PCPs are generalists who manage broad health needs and coordinate specialist care', 'Primary care physicians are trained broadly to manage overall health across many conditions and age groups. They handle preventive care, common illnesses, chronic disease management, and act as the coordinator when specialist expertise is needed. Specialists have deeper but narrower training in a specific system or disease area.', 1),
    mc('Nurse practitioners (NPs) and physician assistants (PAs) in primary care:', ['Can only perform screenings, not diagnose or treat conditions', 'Are fully qualified to handle most routine primary care needs', 'Must be supervised by a physician for every patient encounter', 'Only see patients in hospital settings, not outpatient clinics'], 'Are fully qualified to handle most routine primary care needs', 'NPs and PAs are mid-level providers with graduate-level training. They diagnose and treat common conditions, prescribe medications, and handle most routine primary care needs. Supervision requirements vary by state. For routine care, seeing an NP or PA is appropriate and often more accessible.', 2),
    mc('Urgent care (rather than the emergency room) is appropriate for:', ['Chest pain or suspected heart attack', 'Difficulty breathing or signs of stroke', 'Minor infections, small lacerations, and sprains', 'Severe abdominal pain or loss of consciousness'], 'Minor infections, small lacerations, and sprains', 'Urgent care handles non-life-threatening conditions needing prompt attention — ear infections, UTIs, minor injuries, rashes. For these, urgent care is faster and far less expensive than an ER. Emergency rooms are for potentially life-threatening conditions: chest pain, stroke signs, severe trauma, major breathing difficulty.', 3),
    mc('Preventive colorectal cancer screening for average-risk adults should begin at:', ['50 for everyone', '45, per current guidelines', '60, when risk becomes significant', '35 for men, 45 for women'], '45, per current guidelines', 'Guidelines updated in recent years have lowered the recommended age for colorectal cancer screening from 50 to 45 for average-risk adults, due to increasing rates in younger people. People with family history or other risk factors may need to start earlier.', 4),
    mc('Why does having an ongoing primary care relationship improve healthcare outcomes?', ['PCPs have access to better diagnostic equipment than specialists', 'A doctor who knows your history can identify changes, connect symptoms, and advocate effectively', 'PCPs charge lower fees, reducing the cost of care', 'Primary care relationships are required to access insurance benefits'], 'A doctor who knows your history can identify changes, connect symptoms, and advocate effectively', 'Continuity of care means your provider has context — your baseline, your history, your risk factors. This allows them to notice when something changes, make connections between seemingly unrelated symptoms, and provide personalized rather than generic care. Fragmented care (urgent care for everything) loses this advantage.', 5),
  ],

  'understanding-your-insurance': [
    mc('The deductible in a health insurance plan is:', ['The monthly amount you pay regardless of whether you use care', 'The amount you pay out of pocket before insurance starts sharing costs', 'The maximum amount you will pay in a year for covered services', 'The fixed amount you pay per visit or prescription'], 'The amount you pay out of pocket before insurance starts sharing costs', 'The deductible is the annual threshold before your insurance begins covering costs. A $2,000 deductible means you pay the first $2,000 of covered services yourself. Most plans cover preventive care without requiring the deductible to be met first.', 1),
    mc('The out-of-pocket maximum in a health insurance plan is:', ['The amount you pay in premiums each year', 'The ceiling on what you will pay for covered services in a year — after which insurance covers 100%', 'The maximum amount insurance will pay for any single service', 'The co-pay cap for specialist visits'], 'The ceiling on what you will pay for covered services in a year — after which insurance covers 100%', 'The out-of-pocket maximum is your annual financial exposure cap for covered healthcare costs. Once you hit this amount (from deductibles, copays, and coinsurance combined), your insurance pays 100% for the rest of the year. It protects you from catastrophic medical bills.', 2),
    mc('A key risk with out-of-network providers is:', ['They provide lower-quality care than in-network providers', 'You may be billed at much higher rates with little or no insurance coverage', 'Your primary care physician cannot refer you to them', 'Out-of-network providers cannot file claims with your insurer'], 'You may be billed at much higher rates with little or no insurance coverage', 'Out-of-network providers haven\'t negotiated rates with your insurer. You may pay significantly more — sometimes the full chargemaster price — with little or no coverage from your plan. This can happen even at in-network facilities if individual providers (anesthesiologists, ER doctors) are out-of-network.', 3),
    mc('An HSA (Health Savings Account) is available only to people enrolled in:', ['Any health insurance plan', 'A qualifying High Deductible Health Plan (HDHP)', 'Medicaid or Medicare', 'An HMO plan'], 'A qualifying High Deductible Health Plan (HDHP)', 'HSAs are linked specifically to qualifying HDHPs. Contributions are pre-tax, funds roll over indefinitely (unlike FSAs), and invested funds grow tax-free. They can be used for qualified medical expenses now or saved for future healthcare costs — making them a powerful tax-advantaged healthcare savings vehicle.', 4),
    mc('Prior authorization from your insurance company is required:', ['Only for emergency procedures', 'For some procedures, medications, and specialist referrals — skipping it may result in a denied claim', 'Only when switching from one plan to another', 'For all prescription refills after 90 days'], 'For some procedures, medications, and specialist referrals — skipping it may result in a denied claim', 'Prior authorization is advance approval from your insurer that a service is medically necessary and covered. Without it, the claim may be denied after the fact — leaving you with the full bill. Your doctor\'s office typically handles this, but it\'s worth confirming for any significant planned procedure.', 5),
  ],

  'prescriptions-and-medications': [
    mc('Generic drugs are considered clinically equivalent to brand-name drugs because:', ['They are made in the same factories as brand-name drugs', 'The FDA requires them to be bioequivalent — same active ingredient, same absorption rate and extent', 'They contain identical inactive ingredients to the brand-name version', 'Generic manufacturers pay licensing fees to use the same formula'], 'The FDA requires them to be bioequivalent — same active ingredient, same absorption rate and extent', 'FDA bioequivalence means a generic must deliver the same active ingredient to the bloodstream at the same rate and to the same extent as the brand. Differences in inactive ingredients (fillers, dyes) don\'t affect clinical efficacy for most medications. Generics typically cost 80–90% less.', 1),
    mc('GoodRx is valuable because:', ['It provides free prescription drugs to qualifying low-income patients', 'It can sometimes offer lower prices than using insurance at the pharmacy', 'It is a government program that caps prescription costs at $35', 'It negotiates directly with drug manufacturers to lower list prices'], 'It can sometimes offer lower prices than using insurance at the pharmacy', 'GoodRx negotiates discounted prescription prices at participating pharmacies. For some medications, the GoodRx price is lower than your insurance copay. You can\'t use both simultaneously, but comparing both prices and choosing the lower one is a practical cost-saving strategy.', 2),
    mc('Grapefruit can be dangerous to consume with certain medications because:', ['Its acidity chemically degrades drug molecules in the stomach', 'It contains compounds that inhibit an enzyme that metabolizes many drugs, causing drug levels to rise unpredictably', 'It speeds up kidney excretion, reducing drug effectiveness', 'Its vitamin C content interacts with drug binding proteins'], 'It contains compounds that inhibit an enzyme that metabolizes many drugs, causing drug levels to rise unpredictably', 'Grapefruit contains furanocoumarins that inhibit CYP3A4, an enzyme that metabolizes many medications. When this enzyme is blocked, drug levels in the blood can rise significantly — sometimes to dangerous levels. Affected drugs include many statins, some blood pressure medications, and others. Check with your pharmacist.', 3),
    mc('The most important reason to tell all healthcare providers about every supplement and herbal remedy you take is:', ['Supplements are often contaminated and providers need to know about toxin exposure', 'Many supplements interact with prescription medications — "natural" does not mean safe to combine', 'Insurance may cover supplements if they are listed in your medical record', 'Providers need to adjust supplement dosing based on prescription drug use'], 'Many supplements interact with prescription medications — "natural" does not mean safe to combine', 'Herbal supplements are pharmacologically active. St. John\'s Wort, for example, significantly affects the metabolism of many drugs including birth control, HIV medications, and psychiatric drugs. "Natural" does not mean inert. Drug-supplement interactions can reduce drug effectiveness or cause dangerous drug levels.', 4),
    mc('Polypharmacy (taking many medications simultaneously) is a particular concern for older adults because:', ['Older adults are more likely to be prescribed unnecessary medications', 'Aging affects drug metabolism, and interactions multiply as the number of medications increases', 'Older adults are less likely to report side effects accurately', 'Insurance coverage decreases with age, making polypharmacy unaffordable'], 'Aging affects drug metabolism, and interactions multiply as the number of medications increases', 'Age-related changes reduce the kidney and liver function that metabolize and excrete medications, so drugs act longer and stronger in older adults. With five or more medications, interaction risks multiply exponentially. Periodic medication reviews to eliminate unnecessary drugs are a key safety practice for older adults.', 5),
  ],
}
