import type { ExerciseDef } from '../types'

function mc(
  question: string,
  options: string[],
  correctAnswer: string,
  explanation: string,
  order: number,
): ExerciseDef {
  return { question, type: 'MULTIPLE_CHOICE', options, correctAnswer, explanation, order }
}

export const healthExercises4: Record<string, ExerciseDef[]> = {
  'macronutrients': [
    mc('How many calories does fat provide per gram, compared to protein and carbohydrates?', ['Fat: 4 kcal/g, same as protein and carbs', 'Fat: 7 kcal/g, protein and carbs: 4 kcal/g', 'Fat: 9 kcal/g, protein and carbs: 4 kcal/g', 'Fat: 9 kcal/g, protein: 7 kcal/g, carbs: 4 kcal/g'], 'Fat: 9 kcal/g, protein and carbs: 4 kcal/g', 'Fat provides 9 kcal per gram — more than twice protein or carbohydrates (each 4 kcal/g). This is why fat-dense foods are calorie-dense. Fat is not inherently unhealthy — it is essential for many body functions.', 1),
    mc('Complete proteins contain:', ['Only saturated fatty acids', 'All 9 essential amino acids the body cannot make', 'All 20 amino acids including those the body produces', 'Only animal-derived sources'], 'All 9 essential amino acids the body cannot make', 'Of the 20 amino acids, 9 are "essential" — the body cannot synthesize them and must get them from food. Complete proteins (meat, fish, eggs, dairy, soy, quinoa) contain all 9.', 2),
    mc('The glycemic response of a food refers to:', ['How much protein the food contains per serving', 'How quickly the food raises blood glucose after eating', 'The total calorie content relative to volume', 'How long food takes to leave the stomach'], 'How quickly the food raises blood glucose after eating', 'Glycemic response describes how rapidly blood glucose rises after eating. Refined carbs cause rapid spikes requiring large insulin responses. Fiber and resistant starches slow glucose absorption. Repeated large spikes contribute to insulin resistance over time.', 3),
    mc('Trans fats are particularly harmful because:', ['They contain twice the calories of other fats', 'They are found naturally in all animal products', 'They are strongly associated with heart disease and have been largely banned', 'They block absorption of fat-soluble vitamins'], 'They are strongly associated with heart disease and have been largely banned', 'Trans fats are artificially produced by partial hydrogenation of vegetable oils. Research consistently linked them to increased LDL, reduced HDL, and cardiovascular disease. The FDA banned partially hydrogenated oils from the U.S. food supply.', 4),
    mc('Which fat type in fatty fish is associated with anti-inflammatory and cardiovascular benefits?', ['Saturated fat', 'Trans fat', 'Omega-3 fatty acids', 'Monounsaturated fat'], 'Omega-3 fatty acids', 'Omega-3 fatty acids (EPA and DHA) are polyunsaturated fats found in fatty fish, flaxseed, and walnuts. They have anti-inflammatory properties and are important for brain and cardiovascular health.', 5),
  ],

  'micronutrients': [
    mc('Which vitamins are fat-soluble, stored in tissues, and require dietary fat for absorption?', ['Vitamins C and B12', 'Vitamins B6, B9, and B12', 'Vitamins A, D, E, and K', 'Vitamins C, D, and E'], 'Vitamins A, D, E, and K', 'The four fat-soluble vitamins — A, D, E, and K — dissolve in fat, are stored in fatty tissues and the liver, and require dietary fat for absorption. Because they are stored, deficiency develops slowly but toxicity from supplements is possible.', 1),
    mc('Vitamin D deficiency is particularly common because:', ['Most people eat too few animal products', 'The vitamin is destroyed by cooking', 'Few foods contain it and many people have limited sun exposure, which is the main production source', 'The body excretes it rapidly in urine'], 'Few foods contain it and many people have limited sun exposure, which is the main production source', 'Vitamin D is produced in skin exposed to UVB sunlight. People in northern climates, those who spend little time outdoors, or who use sun protection consistently have limited production. Few foods naturally contain much vitamin D, making deficiency extremely common.', 2),
    mc('Iron deficiency anemia causes symptoms primarily because iron is essential for:', ['Bone density and calcium absorption', 'Hemoglobin, which carries oxygen in red blood cells', 'Immune cell production in bone marrow', 'Thyroid hormone synthesis'], 'Hemoglobin, which carries oxygen in red blood cells', 'Iron is a key component of hemoglobin, the protein in red blood cells that binds and transports oxygen. Without adequate iron, fewer red blood cells are produced and they carry less oxygen. Symptoms include fatigue, weakness, and shortness of breath.', 3),
    mc('Folate (vitamin B9) is especially critical during pregnancy because deficiency causes:', ['Rickets in the infant', 'Neural tube defects like spina bifida in the developing fetus', 'Anemia in the mother', 'Vitamin K deficiency bleeding in the newborn'], 'Neural tube defects like spina bifida in the developing fetus', 'Folate is essential for DNA synthesis and cell division. Deficiency during early fetal development — when the neural tube is forming — causes neural tube defects including spina bifida. 400–800 mcg/day starting before conception is recommended.', 4),
    mc('Which mineral is involved in over 300 enzymatic reactions and commonly underconsumed in Western diets?', ['Calcium', 'Iron', 'Zinc', 'Magnesium'], 'Magnesium', 'Magnesium participates in over 300 enzymatic reactions including energy production, protein synthesis, muscle and nerve function, and blood sugar regulation. Low vegetable and whole grain consumption makes it one of the most commonly underconsumed minerals.', 5),
  ],

  'reading-food-labels': [
    mc('On a Nutrition Facts panel, what should you check first?', ['The calorie count per serving', 'The serving size', 'The % Daily Value for fat', 'The ingredient list'], 'The serving size', 'The serving size is the foundation of everything else on the label. All calories, fat, sodium, and other figures are per serving. A package with 3 servings means all those numbers multiply by 3 if you eat the whole thing — which is often the actual amount consumed.', 1),
    mc('A % Daily Value of 20% or more for a nutrient indicates:', ['A low amount of that nutrient', 'The food provides exactly one-fifth of your needs', 'A high amount of that nutrient', 'The nutrient exceeds recommended limits'], 'A high amount of that nutrient', 'The FDA\'s quick interpretation: 5% DV or less is low; 20% DV or more is high. This shortcut helps quickly compare products and identify foods high or low in specific nutrients, based on a 2,000 calorie reference diet.', 2),
    mc('On an ingredient list, ingredients are ordered by:', ['Alphabetical order', 'Descending order by weight — most abundant ingredient listed first', 'Nutritional importance', 'Ascending order by weight'], 'Descending order by weight — most abundant ingredient listed first', 'Ingredients are listed by descending weight. The first ingredient is present in the greatest amount. If sugar (or one of its aliases) appears in the first few positions, the product is primarily sugar — regardless of front-of-package marketing.', 3),
    mc('The label claim "low fat" legally means:', ['The product has no fat', 'The product has 3g or less fat per serving', 'The product has less fat than the regular version', 'The product contains only unsaturated fats'], 'The product has 3g or less fat per serving', '"Low fat" is a regulated claim meaning 3g or less fat per serving. Critically, low-fat products often replace fat with sugar to maintain palatability. Always check the full nutrition facts and ingredient list — "low fat" does not mean low calorie or healthy.', 4),
    mc('Why is "natural" on food packaging largely meaningless?', ['It is a regulated term applying only to unprocessed foods', 'It is not regulated by the FDA and can appear on almost any product', 'It means the product has no additives or preservatives', 'It guarantees no artificial colors or flavors'], 'It is not regulated by the FDA and can appear on almost any product', '"Natural" is not meaningfully regulated by the FDA. Companies can apply it broadly. Unlike "organic" (which has specific USDA standards), "natural" is a marketing term that tells you almost nothing about the food\'s actual content or production methods.', 5),
  ],
}
