import type { ExerciseDef } from '../types'

function mc(
  question: string,
  options: string[],
  correctAnswer: string,
  explanation: string,
  order: number,
): ExerciseDef {
  return { question, type: 'MULTIPLE_CHOICE', options, correctAnswer, explanation, order }
}

export const healthExercises8: Record<string, ExerciseDef[]> = {
  'self-care-that-works': [
    mc('Which intervention has the strongest evidence for reducing depression symptoms as a standalone treatment?', ['Journaling and gratitude practices', 'Regular aerobic exercise', 'Aromatherapy and relaxation techniques', 'Omega-3 fatty acid supplements'], 'Regular aerobic exercise', 'Regular aerobic exercise has effect sizes for reducing depression symptoms comparable to antidepressants in some studies. It also reduces anxiety, improves sleep quality, reduces cortisol, and increases BDNF. A 30-minute walk most days produces measurable mental health benefits.', 1),
    mc('Avoidance is problematic as a coping strategy because:', ['It uses too much cognitive energy', 'It provides short-term relief while worsening the underlying problem long-term — it is the engine of anxiety disorders', 'It prevents learning new coping strategies', 'It reduces social connection, which drives mental health'], 'It provides short-term relief while worsening the underlying problem long-term — it is the engine of anxiety disorders', 'Avoidance feels like relief in the moment — anxiety drops when you avoid a feared situation. But this reinforces avoidance and prevents the nervous system from learning that the feared situation is manageable. Over time, avoidance often expands what triggers anxiety.', 2),
    mc('Slow, controlled breathing with longer exhalation helps manage stress because:', ['It reduces oxygen to the brain, slowing racing thoughts', 'It activates the parasympathetic nervous system, reducing physiological stress arousal', 'It provides a distraction from stressful thoughts', 'It raises CO2 levels, signaling the brain to slow down'], 'It activates the parasympathetic nervous system, reducing physiological stress arousal', 'The autonomic nervous system responds to breathing patterns. Slow breathing with longer exhalations (like 4-7-8 or box breathing) directly activates the parasympathetic "rest and digest" state — reducing heart rate, blood pressure, and physiological stress reactivity.', 3),
    mc('Rumination differs from productive problem-solving in that it involves:', ['Actively planning solutions to stressors', 'Repetitive, passive focus on negative thoughts without resolution or action', 'Discussing problems with trusted friends for perspective', 'Analyzing past mistakes to avoid repeating them'], 'Repetitive, passive focus on negative thoughts without resolution or action', 'Rumination is repetitive mental replay of distress — re-experiencing negative emotions without problem-solving. It is associated with depression and anxiety. Behavioral activation (taking any action, even small) is more effective at breaking the rumination cycle than more thinking.', 4),
    mc('Using alcohol to manage anxiety is counterproductive because:', ['Alcohol raises cortisol levels immediately upon consumption', 'Alcohol provides short-term relief but worsens anxiety over time and disrupts sleep', 'The calories in alcohol cause metabolic stress that worsens mood', 'Alcohol depletes serotonin permanently with regular use'], 'Alcohol provides short-term relief but worsens anxiety over time and disrupts sleep', 'Alcohol is a depressant that temporarily sedates, reducing anxiety short-term. But as it wears off, anxiety rebounds — sometimes worse. Alcohol also suppresses REM sleep and disrupts sleep architecture, worsening the mood and cognitive regulation that affect anxiety.', 5),
  ],

  'sleep-and-mental-health': [
    mc('REM sleep is particularly important for mental health because:', ['It is when growth hormone is released for physical recovery', 'It is when the body\'s immune system is most active', 'It is when emotional memories are processed and the emotional charge of difficult experiences is reduced', 'It is the deepest, most restorative stage of sleep'], 'It is when emotional memories are processed and the emotional charge of difficult experiences is reduced', 'During REM sleep, the brain processes emotional experiences from the day — sorting and reducing the intensity of difficult memories. REM deprivation impairs emotional regulation, making negative events feel more intense and harder to manage.', 1),
    mc('Sleep deprivation increases anxiety primarily by:', ['Reducing melatonin that normally calms the nervous system', 'Increasing amygdala activity and reducing the prefrontal cortex\'s ability to regulate emotional responses', 'Causing physical discomfort that amplifies psychological distress', 'Lowering serotonin to the same degree as clinical depression'], 'Increasing amygdala activity and reducing the prefrontal cortex\'s ability to regulate emotional responses', 'Even one night of significant sleep loss increases amygdala reactivity (threat detection) and impairs prefrontal cortex function (rational regulation). The result is stronger, less controlled emotional reactions — including anxiety — to situations that would otherwise feel manageable.', 2),
    mc('The single most important sleep hygiene factor is:', ['Using blackout curtains and white noise', 'Avoiding caffeine completely', 'Consistent bed and wake times every day, including weekends', 'Taking melatonin 30 minutes before bed'], 'Consistent bed and wake times every day, including weekends', 'The circadian rhythm is a biological clock regulating sleep-wake cycles. Consistency — going to bed and waking at the same time every day — keeps this clock calibrated. Sleeping in on weekends, even by an hour or two, disrupts this rhythm and impairs sleep quality.', 3),
    mc('CBT-I (cognitive behavioral therapy for insomnia) is first-line treatment because:', ['It works faster than medications with no side effects', 'It addresses behavioral and cognitive patterns maintaining insomnia and is more effective long-term than sleep medications', 'It is covered by all insurance plans', 'It combines medication and therapy for fastest resolution'], 'It addresses behavioral and cognitive patterns maintaining insomnia and is more effective long-term than sleep medications', 'CBT-I addresses behaviors (irregular schedule, using bed for waking activities) and thoughts (catastrophizing about poor sleep) that perpetuate insomnia. Research consistently shows better long-term outcomes than sleep medications, without dependency or rebound insomnia.', 4),
    mc('Caffeine\'s effect on sleep is prolonged because:', ['It permanently alters brain sleep receptors', 'It has a half-life of approximately 5–6 hours, so half remains active hours after consumption', 'It causes the body to produce excess cortisol into the evening', 'Its effects on sleep architecture last 24 hours regardless of timing'], 'It has a half-life of approximately 5–6 hours, so half remains active hours after consumption', 'A 3pm coffee still has half its caffeine active at 9pm. Caffeine works by blocking adenosine receptors — adenosine is the sleep pressure molecule that builds throughout the day. Many people are more sensitive to caffeine than they realize.', 5),
  ],

  'getting-professional-help': [
    mc('The key difference between a psychiatrist and a psychologist is:', ['Psychologists have more years of training', 'Psychiatrists are medical doctors who can prescribe medication; psychologists typically cannot', 'Psychologists focus on serious mental illness; psychiatrists treat mild anxiety', 'Psychiatrists only work in hospital settings'], 'Psychiatrists are medical doctors who can prescribe medication; psychologists typically cannot', 'Psychiatrists hold MD or DO degrees and can prescribe medication, often focusing on medication management. Psychologists hold doctoral degrees (PhD or PsyD) and specialize in psychological assessment and psychotherapy. In most states, psychologists cannot prescribe.', 1),
    mc('The strongest predictor of therapy outcomes is:', ['The specific therapy modality used', 'The number of sessions completed', 'The therapeutic alliance — the quality of the relationship between therapist and client', 'The therapist\'s years of experience'], 'The therapeutic alliance — the quality of the relationship between therapist and client', 'Research consistently shows therapeutic alliance — the bond, agreement on goals, and collaborative relationship — is one of the strongest predictors of therapy outcome, often more predictive than the specific modality used.', 2),
    mc('Dialectical Behavior Therapy (DBT) was originally developed for which condition?', ['PTSD', 'Borderline personality disorder — teaching mindfulness, distress tolerance, emotion regulation, and interpersonal effectiveness', 'Schizophrenia', 'Eating disorders'], 'Borderline personality disorder — teaching mindfulness, distress tolerance, emotion regulation, and interpersonal effectiveness', 'DBT was developed by Marsha Linehan for borderline personality disorder and has since been applied broadly to emotional dysregulation. It teaches four skill modules: mindfulness, distress tolerance, emotion regulation, and interpersonal effectiveness.', 3),
    mc('The 988 Suicide and Crisis Lifeline can be reached by:', ['Calling or texting 988 in the United States', 'Calling 911 and selecting the mental health option', 'Texting HELP to 741741 only', 'Visiting a hospital emergency department'], 'Calling or texting 988 in the United States', '988 is the three-digit code for the Suicide and Crisis Lifeline, available by call or text in the U.S. 24/7. Crisis Text Line (text HOME to 741741) is a separate service. 911 and emergency departments are for immediate physical safety.', 4),
    mc('When is it appropriate to try a different therapist?', ['Never — switching resets all progress', 'Only after completing at least 20 sessions', 'If you don\'t feel reasonably comfortable after 2–3 sessions — fit matters significantly', 'Only if your insurance changes'], 'If you don\'t feel reasonably comfortable after 2–3 sessions — fit matters significantly', 'Therapeutic alliance is critical to outcomes, and not every therapist-client match works. Mild discomfort from addressing difficult material is normal, but if you lack a basic sense of comfort and trust after 2–3 sessions, trying a different therapist is appropriate.', 5),
  ],
}
