import type { ExerciseDef } from '../types'

function mc(
  question: string,
  options: string[],
  correctAnswer: string,
  explanation: string,
  order: number,
): ExerciseDef {
  return { question, type: 'MULTIPLE_CHOICE', options, correctAnswer, explanation, order }
}

export const healthExercises15: Record<string, ExerciseDef[]> = {
  'medical-records': [
    mc('Under HIPAA, how long does a provider have to respond to your medical records request?', ['7 business days', '30 days (60 days with an extension)', '90 days for hospitals, 14 days for clinics', 'There is no required timeframe — providers set their own policies'], '30 days (60 days with an extension)', 'HIPAA requires healthcare providers to respond to access requests within 30 calendar days. A 30-day extension is allowed if the provider notifies you in writing. Providers cannot simply delay or ignore medical records requests.', 1),
    mc('Why should you maintain your own personal medical records rather than relying on providers to share them?', ['Providers are not required to keep records beyond 7 years', 'The healthcare system is fragmented — records often don\'t transfer between providers automatically', 'HIPAA prevents providers from sharing records without your physical presence', 'Maintaining your own records protects you from identity theft'], 'The healthcare system is fragmented — records often don\'t transfer between providers automatically', 'Different providers, hospitals, urgent cares, and specialists often operate on separate systems and don\'t automatically share records. Tests get repeated, relevant history goes unmentioned, and critical information is missing at key moments. Maintaining your own summary solves this gap.', 2),
    mc('The medical ID feature on smartphones is valuable because:', ['It allows emergency providers to bill you without your insurance card', 'First responders can access your critical health information from the lock screen without unlocking the phone', 'It automatically calls 911 when you fall unconscious', 'It stores prescription information that can be downloaded at any pharmacy'], 'First responders can access your critical health information from the lock screen without unlocking the phone', 'iPhone and some Android phones have a Medical ID accessible from the lock screen — no passcode required. First responders know to look for it and can immediately see your conditions, medications, allergies, blood type, and emergency contacts. This can affect treatment decisions when you cannot speak for yourself.', 3),
    mc('Psychotherapy notes receive special privacy protections because:', ['Mental health conditions are more sensitive and stigmatized than physical health conditions', 'They are considered the therapist\'s personal work product and are separately protected beyond standard HIPAA rules', 'Mental health providers are not required to follow HIPAA', 'Psychotherapy notes contain information about third parties who have not consented to disclosure'], 'They are considered the therapist\'s personal work product and are separately protected beyond standard HIPAA rules', 'Psychotherapy notes — the therapist\'s personal session notes — are separately protected under HIPAA and many state laws. Providers can withhold these even in response to a records request, though they must provide a summary. This protection recognizes the sensitive nature of therapy content.', 4),
    mc('Under the 21st Century Cures Act, providers are required to:', ['Share records with other providers automatically after any visit', 'Give patients free electronic access to their full health record through digital tools', 'Reduce medical record request fees to zero for all patients', 'Maintain records for a minimum of 25 years'], 'Give patients free electronic access to their full health record through digital tools', 'The 21st Century Cures Act requires providers to give patients free electronic access to their complete health information through standardized APIs and patient portals. This significantly expanded patient data access rights and enabled apps to connect to your health data with your permission.', 5),
  ],

  'second-opinions': [
    mc('When is seeking a second opinion most clearly warranted?', ['For any visit where you receive a prescription', 'After a serious diagnosis, before major surgery, or when a diagnosis remains unclear', 'Only when you feel the first doctor was rude or dismissive', 'After every specialist visit as standard practice'], 'After a serious diagnosis, before major surgery, or when a diagnosis remains unclear', 'Second opinions have the highest value for consequential decisions: serious diagnoses (cancer, neurological conditions), major surgery recommendations, unclear diagnoses after evaluation, or treatments that aren\'t working. For routine care, second opinions are less necessary.', 1),
    mc('Research on physicians\' reactions to second opinion requests shows:', ['Most physicians take it as a personal insult', 'Experienced physicians frequently recommend second opinions themselves and generally understand the request', 'Physicians are professionally required to accommodate second opinions', 'Physicians become less cooperative with care if you seek a second opinion'], 'Experienced physicians frequently recommend second opinions themselves and generally understand the request', 'Good physicians understand that patients need to be confident in major medical decisions. Many routinely recommend second opinions for serious diagnoses. A physician who reacts negatively to a second opinion request is demonstrating a concerning attitude toward patient autonomy — itself useful information.', 2),
    mc('For a cancer diagnosis, getting a second opinion on the pathology report is valuable because:', ['Oncologists may disagree on treatment but pathologists always agree', 'Pathology interpretation has meaningful variability — the diagnosis everything else builds on is worth verifying', 'Second pathology opinions are required by insurance before treatment can begin', 'Cancer pathology is a new field with limited standardization'], 'Pathology interpretation has meaningful variability — the diagnosis everything else builds on is worth verifying', 'The pathology report — analysis of tissue from biopsy — determines the cancer type, grade, and stage that drives all subsequent treatment decisions. Pathology interpretation involves expert judgment that varies between pathologists. Major cancer centers routinely find discrepancies when reviewing pathology. This is one of the highest-value second opinions in medicine.', 3),
    mc('When two providers give conflicting recommendations, the best next step is:', ['Automatically follow the second opinion since it was sought for a reason', 'Return to the first provider and dismiss the second opinion', 'Ask each to explain their reasoning, and consider a third opinion or research the evidence', 'Choose the recommendation from the provider with more experience'], 'Ask each to explain their reasoning, and consider a third opinion or research the evidence', 'Conflicting opinions often reflect genuine clinical uncertainty or different evidence interpretations — not that one provider is simply wrong. Understanding the reasoning behind each recommendation, doing your own research, or seeking a third opinion gives you the information to make a genuinely informed decision.', 4),
    mc('How should you frame a request for a second opinion to your current provider?', ['Explain all the reasons you doubt their diagnosis to justify the request', 'Bring a printed article showing why the diagnosis might be wrong', 'Simply say you\'d like another opinion before proceeding and ask them to share your records', 'Wait until after treatment has started to request the second opinion'], 'Simply say you\'d like another opinion before proceeding and ask them to share your records', '"I\'d like to get another opinion before we proceed. Can you share my records?" is complete and sufficient. You don\'t need to justify wanting a second opinion. Straightforward, non-confrontational phrasing is usually all that\'s needed, and providers are accustomed to the request.', 5),
  ],

  'medical-billing': [
    mc('The chargemaster price on a hospital bill is:', ['The final amount you owe after insurance adjustment', 'The deliberate "sticker price" that almost no one actually pays — insurance negotiates it down dramatically', 'The price set by Medicare for each procedure', 'The amount your insurer will reimburse the provider'], 'The deliberate "sticker price" that almost no one actually pays — insurance negotiates it down dramatically', 'The chargemaster is a hospital\'s internal price list, deliberately set high. Insurance companies negotiate contracted rates that are dramatically lower. Self-pay patients may be charged near chargemaster rates unless they negotiate — which is why asking for the "cash pay" or "insurance rate" matters when uninsured.', 1),
    mc('An Explanation of Benefits (EOB) from your insurer is:', ['A bill requiring payment by a specific due date', 'An explanation of how the insurer processed a claim — showing what was billed, paid, and what you owe', 'A denial of coverage for a specific service', 'Your annual summary of all services used and their costs'], 'An explanation of how the insurer processed a claim — showing what was billed, paid, and what you owe', 'The EOB is not a bill — it is a statement showing how your insurer processed a claim: what the provider charged, what the insurer paid, what was written off under the negotiated rate, and what remains your responsibility. Comparing your EOB to the provider\'s bill catches discrepancies.', 2),
    mc('The most reliable way to identify billing errors on a medical bill is:', ['Calling the billing department and asking if there are any errors', 'Requesting and reviewing an itemized bill — a line-by-line breakdown of every charge', 'Comparing the total to what you expected based on care received', 'Checking that the provider and date of service are correct'], 'Requesting and reviewing an itemized bill — a line-by-line breakdown of every charge', 'Summary bills only show totals. Itemized bills show every service, procedure, and supply charged with its billing code. Common errors — duplicate charges, services not received, wrong codes — only become visible at the line item level. Always request an itemized bill for any significant charge.', 3),
    mc('When a health insurance claim is denied, you should:', ['Accept the denial — appeals are rarely successful', 'File an appeal immediately — denials are frequently overturned through the appeals process', 'Switch insurance plans to one that covers the service', 'Pay the bill and deduct it from your taxes as a medical expense'], 'File an appeal immediately — denials are frequently overturned through the appeals process', 'Insurance claim denials are frequently incorrect or overturnable. The appeals process requires the insurer to reconsider. Appeals are often successful — insurers reconsider, or providers submit additional documentation proving medical necessity. If internal appeal fails, external review by an independent third party is required by law for most plans.', 4),
    mc('If you receive a large medical bill you cannot pay in full, which approach is most effective?', ['Pay the minimum possible each month to avoid collections', 'Ask about financial assistance programs, negotiate a lump-sum settlement, or set up a zero-interest payment plan', 'Transfer the balance to a credit card to consolidate the debt', 'Ignore the bill — medical debt rarely leads to collections'], 'Ask about financial assistance programs, negotiate a lump-sum settlement, or set up a zero-interest payment plan', 'Medical bills are often negotiable. Nonprofit hospitals have charity care programs offering income-based discounts. A lump-sum cash offer (40–60% of the balance) is often accepted, especially for older debt. Many providers offer zero-interest payment plans. Financial assistance exists and is underutilized — ask explicitly.', 5),
  ],
}
