import type { ExerciseDef } from '../types'

function mc(
  question: string,
  options: string[],
  correctAnswer: string,
  explanation: string,
  order: number,
): ExerciseDef {
  return { question, type: 'MULTIPLE_CHOICE', options, correctAnswer, explanation, order }
}

export const healthExercises5: Record<string, ExerciseDef[]> = {
  'calories-and-energy': [
    mc('Basal metabolic rate (BMR) accounts for approximately what percentage of total daily energy expenditure?', ['10–20%', '30–45%', '60–75%', '80–90%'], '60–75%', 'BMR — the energy the body uses at complete rest to maintain breathing, circulation, temperature, and cellular repair — accounts for roughly 60–75% of total daily energy expenditure. Physical activity is the most variable component but represents a smaller share for most people.', 1),
    mc('Which macronutrient has the highest thermic effect of food (calories used to digest it)?', ['Fat', 'Carbohydrates', 'Alcohol', 'Protein'], 'Protein', 'Protein has a thermic effect of 20–35% — meaning 20–35% of protein calories are used in the digestion process itself. Fat has the lowest thermic effect (0–3%). This is one reason protein is particularly satiating and metabolically active.', 2),
    mc('Metabolic adaptation in response to calorie restriction means:', ['The body converts muscle to fat to preserve energy', 'BMR can decrease, slowing weight loss over time', 'The digestive system absorbs more calories', 'Fat cells multiply to store extra energy'], 'BMR can decrease, slowing weight loss over time', 'When you eat less, the body adapts by reducing BMR — metabolic adaptation. Energy expenditure decreases over time, which is why weight loss plateaus and why people often regain weight after dieting.', 3),
    mc('Alcohol provides how many calories per gram?', ['4 kcal/g', '7 kcal/g', '9 kcal/g', '2 kcal/g'], '7 kcal/g', 'Alcohol provides 7 kcal per gram — more than protein and carbohydrates (4 kcal/g each) but less than fat (9 kcal/g). These calories provide no nutritional benefit and can significantly add to total intake.', 4),
    mc('Which factor most strongly determines basal metabolic rate?', ['Number of meals eaten per day', 'Lean muscle mass and body size', 'The specific foods eaten', 'Daily caffeine consumption'], 'Lean muscle mass and body size', 'BMR is primarily driven by body size and lean mass. Larger bodies burn more energy at rest. Muscle tissue burns roughly 13 kcal/kg/day versus about 4 kcal/kg/day for fat. Building muscle increases resting energy expenditure over time.', 5),
  ],

  'what-a-healthy-diet-looks-like': [
    mc('Which dietary pattern has the strongest consistent evidence for long-term health benefits?', ['A high-protein, low-carb diet', 'A diet emphasizing vegetables, whole grains, legumes, and limited processed foods', 'A low-fat diet with controlled calorie counting', 'An intermittent fasting protocol with no food restrictions'], 'A diet emphasizing vegetables, whole grains, legumes, and limited processed foods', 'Decades of research consistently links diets rich in vegetables, whole grains, legumes, nuts, and fish — and low in ultra-processed foods and added sugars — with lower rates of heart disease, cancer, diabetes, and mortality. This pattern appears across Mediterranean, DASH, and plant-forward diets.', 1),
    mc('What matters more than the specific macronutrient ratio of a diet?', ['Meal timing and frequency', 'The total number of calories consumed daily', 'The quality and source of those macronutrients', 'Taking a daily multivitamin'], 'The quality and source of those macronutrients', 'Whether carbohydrates are 30% or 40% of calories matters less than whether they come from vegetables and whole grains or refined flour and sugar. A higher-fat diet built on olive oil and avocados performs better in research than a low-fat diet full of refined carbs.', 2),
    mc('Processed meat (bacon, sausage, deli meats) is associated with increased risk of:', ['Osteoporosis', 'Kidney stones', 'Cancer', 'Type 1 diabetes'], 'Cancer', 'Processed meats are classified as Group 1 carcinogens by the WHO, associated with increased colorectal cancer risk. The evidence is stronger for processed meat than unprocessed red meat. Limiting processed meat is one of the most consistent dietary recommendations.', 3),
    mc('Why do experts recommend minimizing sugar-sweetened beverages specifically?', ['They contain caffeine that disrupts sleep', 'They add significant calories with minimal satiety or nutritional benefit', 'They damage tooth enamel more than solid sugars', 'They raise blood pressure through excess sodium'], 'They add significant calories with minimal satiety or nutritional benefit', 'Liquid calories — soda, juice, sweetened coffee, energy drinks — are rapidly absorbed and do not activate satiety signals the way solid food does. They add significant caloric and sugar load without reducing hunger, making them easy to overconsume alongside regular meals.', 4),
    mc('"Consistency beats perfection" in diet means:', ['It is acceptable to eat anything as long as you exercise', 'A sustainable dietary pattern maintained over time produces better outcomes than short-term perfect adherence', 'Counting calories precisely is more important than food quality', 'Supplements compensate for an inconsistent diet'], 'A sustainable dietary pattern maintained over time produces better outcomes than short-term perfect adherence', 'A very good diet maintained most of the time — with flexibility for occasions and preferences — is more beneficial than a "perfect" diet followed rigidly for weeks then abandoned. Long-term adherence is what produces health outcomes.', 5),
  ],

  'eating-on-a-budget': [
    mc('Which food is among the cheapest and most nutritious protein sources on earth?', ['Fresh salmon fillets', 'Organic chicken breast', 'Dry beans and lentils', 'Greek yogurt'], 'Dry beans and lentils', 'Dry lentils and beans cost roughly $1–2 per pound and make multiple servings. They are high in protein, fiber, iron, and folate. Combined with rice, they form a complete protein. They are among the most nutritionally dense and cost-effective foods available.', 1),
    mc('Why are frozen vegetables a smart budget choice nutritionally?', ['They are lower in sodium than fresh vegetables', 'They are nutritionally equivalent to fresh — often frozen at peak ripeness — and significantly cheaper with no waste', 'They are pre-cooked, reducing preparation time', 'They contain added vitamins not found in fresh produce'], 'They are nutritionally equivalent to fresh — often frozen at peak ripeness — and significantly cheaper with no waste', 'Frozen vegetables are typically frozen immediately after harvest at peak ripeness, preserving nutrients. They cost less than fresh, have no spoilage waste, and are available year-round. For most cooking purposes, they are nutritionally indistinguishable from fresh.', 2),
    mc('Beans and rice together form a nutritionally complete protein because:', ['Both contain all essential amino acids individually', 'Combined, they provide all essential amino acids that each lacks alone', 'Rice provides complete protein and beans add fiber', 'The cooking process creates new amino acids when both are prepared together'], 'Combined, they provide all essential amino acids that each lacks alone', 'Beans are low in methionine but high in lysine; rice is the opposite. Together, they supply all nine essential amino acids — a complete protein. This combination has sustained populations worldwide at minimal cost throughout history.', 3),
    mc('Which version of a food generally offers the best value for most groceries?', ['Organic, name-brand products for safety', 'Pre-cut and pre-washed for time savings', 'Generic or store-brand products with similar nutritional content', 'Fresh over frozen to maximize vitamins'], 'Generic or store-brand products with similar nutritional content', 'Store-brand and generic products typically have nutritional content identical to name brands. The price difference reflects marketing costs, not quality. For staples like canned goods, frozen vegetables, oats, and dry goods, generic is virtually always the better value.', 4),
    mc('SNAP (Supplemental Nutrition Assistance Program) is:', ['A voluntary discount card at grocery stores', 'A government food assistance program for income-qualifying individuals and families', 'A meal kit delivery service for low-income households', 'A nutrition counseling program run by hospitals'], 'A government food assistance program for income-qualifying individuals and families', 'SNAP provides food purchasing assistance to income-qualifying individuals and families through EBT cards accepted at most grocery stores. Many eligible people do not apply. Applications can be submitted through state SNAP offices or benefits.gov.', 5),
  ],
}
