import type { ExerciseDef } from '../types'

function mc(
  question: string,
  options: string[],
  correctAnswer: string,
  explanation: string,
  order: number,
): ExerciseDef {
  return { question, type: 'MULTIPLE_CHOICE', options, correctAnswer, explanation, order }
}

export const healthExercises9: Record<string, ExerciseDef[]> = {
  'helping-someone-else': [
    mc('When someone you care about is struggling mentally, the most valuable thing you can offer is:', ['Specific advice on what worked for you', 'Reassurance and silver linings to their situation', 'Presence and listening without rushing to fix, with validation of their experience', 'Encouragement to think more positively'], 'Presence and listening without rushing to fix, with validation of their experience', 'The most helpful response is genuine listening — letting the person feel heard without jumping to solutions. Validation ("that sounds really hard") communicates that their experience makes sense, which is often more healing than advice.', 1),
    mc('Research shows that asking someone directly "Are you thinking about suicide?" will:', ['Plant the idea and increase their risk', 'Not increase risk and opens a conversation that may be lifesaving', 'Only be helpful if asked by a licensed professional', 'Make the person feel accused and damage the relationship'], 'Not increase risk and opens a conversation that may be lifesaving', 'Multiple studies confirm that asking directly about suicide does not plant the idea or increase risk. Most people who are suicidal feel relief when someone finally asks directly. Avoiding the question does not protect anyone.', 2),
    mc('Offering "let me know if you need anything" is less helpful than:', ['Sending a card expressing support', 'Offering specific practical help like bringing a meal on a specific day', 'Calling to check in regularly', 'Recommending a therapist you\'ve heard about'], 'Offering specific practical help like bringing a meal on a specific day', '"Let me know if you need anything" shifts the burden to the struggling person — who is already struggling — to identify needs and ask. Specific offers ("I\'m bringing dinner Thursday") require nothing of the person and are far more likely to be accepted.', 3),
    mc('Warning signs of increased suicide risk include:', ['Suddenly becoming more social and reconnecting with friends', 'Expressing interest in the future and making plans', 'Giving away possessions, unusual goodbyes, or sudden calmness after depression', 'Seeking professional mental health treatment for the first time'], 'Giving away possessions, unusual goodbyes, or sudden calmness after depression', 'Warning signs include giving away valued possessions, unusual farewells, sudden calmness after a period of depression (sometimes indicating a decision has been made), increased substance use, and withdrawal. Sudden calmness can be particularly dangerous.', 4),
    mc('When supporting someone through a mental health crisis, setting limits on what you can provide is:', ['A sign that you don\'t truly care', 'Abandonment that worsens the person\'s condition', 'Necessary sustainability — you cannot support others from a depleted state', 'Appropriate only if you have your own diagnosed mental health condition'], 'Necessary sustainability — you cannot support others from a depleted state', 'Supporting someone through mental health struggles is emotionally demanding. Setting limits is not abandonment — it is sustainability. You are not responsible for fixing another person\'s mental health, and you cannot effectively help from a place of depletion.', 5),
  ],

  'assessing-an-emergency': [
    mc('What is the correct first priority when arriving at an emergency scene?', ['Immediately approach and begin caring for any injured person', 'Assess scene safety before approaching anyone', 'Call 911 while running toward the victim', 'Begin CPR on any unconscious person immediately'], 'Assess scene safety before approaching anyone', 'Scene safety comes first. Rushing to help without checking for ongoing hazards — traffic, downed power lines, fire, violence, chemical exposure — can turn one victim into two. Heroes who enter unsafe scenes without proper training frequently become casualties themselves.', 1),
    mc('To check for responsiveness in an unresponsive person, you should:', ['Look for visible breathing and check for a carotid pulse simultaneously', 'Tap the shoulders firmly and shout "Are you okay? Can you hear me?"', 'Open the airway first, then check responsiveness', 'Check for medical ID bracelet before any assessment'], 'Tap the shoulders firmly and shout "Are you okay? Can you hear me?"', 'The standard responsiveness check is tapping the shoulders firmly while loudly asking "Are you okay?" or "Can you hear me?" If there is no response, proceed to calling 911 and checking for breathing.', 2),
    mc('Why is it better to point at a specific individual in a crowd rather than calling for help generally?', ['Direct commands are more legally binding', 'General calls trigger the bystander effect — people assume others will act', 'Most bystanders are untrained and need direct instruction', 'It is faster to point than speak in a noisy environment'], 'General calls trigger the bystander effect — people assume others will act', 'The bystander effect means individuals in a crowd assume someone else will help. Calling out generally often results in nobody acting. Pointing specifically — "You in the red shirt, call 911 now" — assigns clear responsibility and gets action.', 3),
    mc('In the primary survey ABCs of emergency assessment, "C" stands for:', ['Consciousness — assessing responsiveness', 'Compression — beginning chest compressions', 'Circulation — checking for major bleeding', 'Communication — calling 911'], 'Circulation — checking for major bleeding', 'The primary survey covers Airway (is it open?), Breathing (is the person breathing?), and Circulation (is there major bleeding?). Controlling life-threatening bleeding is an immediate priority alongside airway and breathing.', 4),
    mc('When briefing arriving paramedics, you should provide:', ['Only your name and exact location', 'The victim\'s name, address, and insurance information', 'What happened, how long ago, what has changed, and what care you have provided', 'A full medical history from any ID found'], 'What happened, how long ago, what has changed, and what care you have provided', 'Paramedics need a rapid handoff: what happened (mechanism), when (timeline), how the victim\'s condition has changed, and what care you have provided. This information directly affects their immediate treatment decisions.', 5),
  ],

  'calling-for-help': [
    mc('When calling 911, what should you provide first?', ['Your name and relationship to the victim', 'The nature of the emergency in detail', 'Your location — address, cross streets, or landmarks', 'The victim\'s age and medical history'], 'Your location — address, cross streets, or landmarks', 'Location is the most critical piece of information — emergency responders cannot help if they cannot find you. Provide street address, cross streets, apartment or building number, or landmarks. Everything else can be gathered while responders are en route.', 1),
    mc('What should you do with your phone after calling 911 and beginning to provide care?', ['Hang up — the dispatcher has all the information needed', 'Call a second emergency number as backup', 'Leave it on, tell the dispatcher you are providing care, and stay on the line', 'Hand it to a bystander to keep the line open'], 'Leave it on, tell the dispatcher you are providing care, and stay on the line', 'Do not hang up. Dispatchers can guide you through CPR, bleeding control, or other interventions, and relay information to approaching responders. If you must put the phone down, tell the dispatcher and leave it on.', 2),
    mc('When should you call 911 for a seizure?', ['Any seizure in anyone', 'Only if the person has no prior epilepsy diagnosis', 'For a seizure in someone not known to have epilepsy, or any seizure lasting more than 5 minutes', 'Only if the person stops breathing during the seizure'], 'For a seizure in someone not known to have epilepsy, or any seizure lasting more than 5 minutes', 'Seizures in people with known epilepsy that are typical and resolve normally may not require 911. But a first seizure, a seizure lasting more than 5 minutes (status epilepticus), or a seizure with injury or non-recovery warrants emergency response.', 3),
    mc('If you are alone with an adult in cardiac arrest, you should:', ['Do CPR for 5 minutes before calling 911', 'Call 911 first or use a hands-free device while beginning CPR', 'Begin CPR immediately without calling 911 until someone arrives', 'Perform rescue breathing only until 911 is called'], 'Call 911 first or use a hands-free device while beginning CPR', 'For adults in cardiac arrest, call 911 first (unless another person can call while you start CPR). The exception is children who drowned or collapsed from respiratory causes — give 2 minutes of CPR first, then call. Early defibrillation depends on 911 response.', 4),
    mc('When uncertain whether a situation warrants calling 911, you should:', ['Wait to see if the situation worsens', 'Contact a physician for guidance', 'Call 911 — dispatchers help determine if emergency response is needed', 'Use urgent care or telehealth instead'], 'Call 911 — dispatchers help determine if emergency response is needed', 'Emergency dispatchers are trained to gather information and assess situations. It is not an abuse of the system to call when uncertain. Dispatchers can help decide whether emergency response is needed and can guide you through immediate care.', 5),
  ],
}
