import type { ExerciseDef } from '../types'

function mc(
  question: string,
  options: string[],
  correctAnswer: string,
  explanation: string,
  order: number
): ExerciseDef {
  return { question, type: 'MULTIPLE_CHOICE', options, correctAnswer, explanation, order }
}

export const historyExercises6: Record<string, ExerciseDef[]> = {
  'industrialization-and-imperialism': [
    mc('What was the Industrial Revolution?', ['A political revolution overthrowing monarchies', 'The transformation from agrarian, handcraft economies to manufacturing and machine production, beginning in Britain ~1760-1840', 'A revolution in agricultural techniques', 'A cultural shift valuing scientific knowledge'], 'The transformation from agrarian, handcraft economies to manufacturing and machine production, beginning in Britain ~1760-1840', 'The Industrial Revolution began in British textile mills, powered by coal and steam. It spread to Europe and North America, fundamentally changing work, cities, family life, and global economic power.', 1),
    mc('What was 19th-century imperialism?', ['Peaceful economic cooperation between nations', 'The expansion of European power over much of Asia, Africa, and the Pacific — through colonization, military force, and economic domination', 'A political philosophy favoring smaller government', 'Voluntary federation between European nations and colonies'], 'The expansion of European power over much of Asia, Africa, and the Pacific — through colonization, military force, and economic domination', 'By 1914, European powers controlled ~84% of the world\'s land. Britain, France, Germany, and others competed for colonies providing raw materials, markets, and prestige.', 2),
    mc('What was the Berlin Conference (1884-85)?', ['A peace conference ending a European war', 'A meeting of European powers that divided Africa among themselves without African participation — establishing the "Scramble for Africa"', 'A trade conference establishing global tariff rules', 'A conference creating the first international human rights standards'], 'A meeting of European powers that divided Africa among themselves without African participation — establishing the "Scramble for Africa"', 'Fourteen European nations drew borders across Africa with no regard for existing ethnic, linguistic, or political boundaries. This arbitrary division created conflicts that persist today.', 3),
    mc('How did industrialization change labor conditions in the 19th century?', ['It immediately improved wages and working conditions', 'Workers initially faced brutal conditions: child labor, 14-hour days, dangerous factories, and urban poverty — leading to labor movements demanding reform', 'It had minimal impact on ordinary workers\' lives', 'It eliminated the need for human labor quickly'], 'Workers initially faced brutal conditions: child labor, 14-hour days, dangerous factories, and urban poverty — leading to labor movements demanding reform', 'Early industrial capitalism created enormous wealth alongside misery. Reformers like Marx documented exploitation; labor unions organized strikes; laws gradually banned child labor and limited hours.', 4),
    mc('What was Social Darwinism?', ['Darwin\'s own theory applied to society', 'The misapplication of evolutionary ideas to justify social inequality, imperialism, and racial hierarchy as "natural" outcomes of competition', 'A scientific theory about human social evolution', 'A progressive theory arguing for social reform based on science'], 'The misapplication of evolutionary ideas to justify social inequality, imperialism, and racial hierarchy as "natural" outcomes of competition', 'Social Darwinism (Herbert Spencer) used "survival of the fittest" to justify exploiting workers and colonizing peoples as natural law. Darwin himself opposed this misuse of his theory.', 5),
  ],
  'world-wars': [
    mc('What underlying conditions made World War I so catastrophic?', ['Only the assassination of Franz Ferdinand', 'A web of alliances, military mobilization plans, imperial rivalries, and nationalism that turned a regional crisis into a global war', 'German aggression was the sole cause', 'A planned war by all major powers simultaneously'], 'A web of alliances, military mobilization plans, imperial rivalries, and nationalism that turned a regional crisis into a global war', 'The alliance system (Triple Alliance vs Triple Entente) meant one conflict pulled in all powers. Military planning (Schlieffen Plan) required rapid mobilization. Colonial rivalries and nationalism inflamed tensions.', 1),
    mc('What made World War I\'s warfare uniquely devastating?', ['The use of nuclear weapons for the first time', 'Industrial weapons (machine guns, artillery, poison gas) combined with 19th-century tactics, producing trench warfare and mass casualties with no territorial gain', 'A lack of military planning and strategy', 'Primarily naval combat that killed sailors but spared soldiers'], 'Industrial weapons (machine guns, artillery, poison gas) combined with 19th-century tactics, producing trench warfare and mass casualties with no territorial gain', 'Machine guns and artillery made frontal assaults suicidal — yet generals kept ordering them. The Battle of the Somme (1916): 60,000 British casualties on day one. 20 million died in the war overall.', 2),
    mc('What caused the rise of fascism in Europe between the wars?', ['Economic prosperity enabling radical politics', 'Economic devastation, humiliation from WWI, failed democracies, fear of communism, and demagogues exploiting nationalism and resentment', 'Deliberate choice by democratic majorities', 'Military coups planned years in advance'], 'Economic devastation, humiliation from WWI, failed democracies, fear of communism, and demagogues exploiting nationalism and resentment', 'Weimar Germany faced hyperinflation, Depression unemployment (33%), and Versailles humiliation. Hitler and Mussolini offered scapegoats and national greatness. Weak democracies couldn\'t resist.', 3),
    mc('What was appeasement and why did it fail?', ['A military strategy of attacking aggressors preemptively', 'The policy of making concessions to Hitler (e.g., Munich Agreement 1938) to avoid war — which only emboldened further aggression', 'A policy of isolationism from European affairs', 'Economic sanctions on Nazi Germany'], 'The policy of making concessions to Hitler (e.g., Munich Agreement 1938) to avoid war — which only emboldened further aggression', 'Chamberlain\'s "peace for our time" gave Hitler the Sudetenland. Six months later, Hitler took all of Czechoslovakia. Appeasement taught him that democracies wouldn\'t fight — a miscalculation about Poland proved fatal.', 4),
    mc('What was the United Nations\' key improvement over the League of Nations?', ['It excluded major powers to prevent deadlock', 'The US joined, and the Security Council gave major powers (including the US and USSR) formal roles — making it harder for great powers to simply ignore it', 'It had its own military force', 'It was purely an economic organization without political functions'], 'The US joined, and the Security Council gave major powers (including the US and USSR) formal roles — making it harder for great powers to simply ignore it', 'The League failed partly because the US Senate rejected membership. The UN included both superpowers from the start, giving it more legitimacy — though Security Council vetoes can still paralyze it.', 5),
  ],
  'decolonization': [
    mc('What drove decolonization after World War II?', ['European generosity and planned handover of power', 'WWII weakened colonial powers, nationalist movements strengthened, and the Cold War superpowers (both for different reasons) pressured European empires to dissolve', 'Military defeat of all colonial powers', 'UN resolutions forcing immediate independence'], 'WWII weakened colonial powers, nationalist movements strengthened, and the Cold War superpowers (both for different reasons) pressured European empires to dissolve', 'Britain and France were economically exhausted. US and USSR both opposed European empires (though for different reasons). Nationalist movements (India, Algeria, Vietnam, Kenya) pushed back with increasing force.', 1),
    mc('What was Gandhi\'s approach to independence from Britain?', ['Armed revolution', 'Nonviolent civil disobedience — refusing to cooperate with British rule through strikes, boycotts, and peaceful protest', 'Negotiation through the British Parliament', 'Military alliance with Japan during WWII'], 'Nonviolent civil disobedience — refusing to cooperate with British rule through strikes, boycotts, and peaceful protest', 'Gandhi\'s satyagraha (truth-force) mobilized millions. The Salt March (1930), economic boycotts, and mass civil disobedience made India ungovernable at an affordable cost — ultimately forcing British withdrawal.', 2),
    mc('What problems did many newly independent nations face?', ['Immediate prosperity and stable democracy', 'Artificial colonial borders dividing ethnic groups, lack of experienced governance institutions, economic dependency, and Cold War interference', 'Full preparedness from colonial-era training', 'No interference from former colonial powers after independence'], 'Artificial colonial borders dividing ethnic groups, lack of experienced governance institutions, economic dependency, and Cold War interference', 'Colonial borders were drawn for European convenience. Post-independence nations often had multiple competing ethnic groups, economies designed to export raw materials to Europe, and elites trained in European models.', 3),
    mc('What was the Non-Aligned Movement?', ['Countries allied with neither NATO nor the Warsaw Pact during the Cold War, seeking an independent foreign policy path', 'A military alliance of newly independent nations', 'Countries that refused to join the United Nations', 'A trade bloc of former colonies'], 'Countries allied with neither NATO nor the Warsaw Pact during the Cold War, seeking an independent foreign policy path', 'Founded at Bandung (1955), the Non-Aligned Movement included India, Egypt, Yugoslavia, and dozens of newly independent nations seeking to avoid being Cold War pawns of either superpower.', 4),
    mc('What was apartheid in South Africa?', ['A democratic system including all South Africans', 'A system of institutionalized racial segregation and white minority rule from 1948-1994, dismantled through Nelson Mandela\'s movement and international pressure', 'An anti-colonial liberation movement', 'A system of tribal governance in South Africa'], 'A system of institutionalized racial segregation and white minority rule from 1948-1994, dismantled through Nelson Mandela\'s movement and international pressure', 'Apartheid (Afrikaans: "separateness") enforced racial classification, segregated all public life, and denied Black South Africans political rights. Mandela was imprisoned 27 years. International sanctions and the ANC ultimately ended it.', 5),
  ],
  'globalization': [
    mc('What is globalization?', ['The spread of American culture worldwide', 'The increasing interconnection of economies, cultures, and peoples through trade, communication, migration, and international institutions', 'The creation of a world government', 'The standardization of all cultures to one global norm'], 'The increasing interconnection of economies, cultures, and peoples through trade, communication, migration, and international institutions', 'Globalization accelerated after WWII (Bretton Woods, GATT/WTO) and again after the Cold War. Trade, foreign investment, migration, and digital communication have made national economies increasingly interdependent.', 1),
    mc('What has been a key criticism of economic globalization?', ['It has made all countries equally wealthy', 'It has benefited some while harming others — raising living standards in some developing countries while displacing workers in developed countries and increasing inequality', 'It has been purely beneficial with no drawbacks', 'It has primarily helped wealthy countries while hurting all developing nations'], 'It has benefited some while harming others — raising living standards in some developing countries while displacing workers in developed countries and increasing inequality', 'Global poverty has fallen dramatically; China\'s middle class exploded. But manufacturing workers in the US, Europe face competition. Inequality within many countries has increased even as global inequality fell.', 2),
    mc('What role does the World Trade Organization (WTO) play?', ['Setting global tariff rates that all nations must follow', 'A forum for negotiating trade rules and resolving trade disputes between member nations', 'A global bank lending to developing countries', 'A political organization governing international affairs'], 'A forum for negotiating trade rules and resolving trade disputes between member nations', 'The WTO (successor to GATT, 1995) has 164 members. It negotiates trade agreements and provides a dispute settlement mechanism — allowing countries to challenge tariffs and trade barriers legally.', 3),
    mc('How has the internet changed globalization?', ['It has had minimal effect on economic globalization', 'It has dramatically accelerated globalization — enabling instant communication, remote work, global commerce, and the rapid spread of information and culture', 'It has reversed globalization by enabling local economies', 'It only affects cultural globalization, not economic'], 'It has dramatically accelerated globalization — enabling instant communication, remote work, global commerce, and the rapid spread of information and culture', 'The internet collapsed communication costs to near zero. Global supply chains are coordinated in real time. Digital services cross borders frictionlessly. Culture spreads instantly. This creates new interdependencies and vulnerabilities.', 4),
    mc('What are the environmental consequences of globalization?', ['Globalization has had no environmental impact', 'Increased production and consumption have accelerated resource depletion, pollution, and carbon emissions — while also enabling global cooperation on environmental problems', 'Globalization has purely improved environmental outcomes through technology', 'Only developing countries experience environmental degradation from globalization'], 'Increased production and consumption have accelerated resource depletion, pollution, and carbon emissions — while also enabling global cooperation on environmental problems', 'More people consuming more goods means more emissions, deforestation, and pollution. But global agreements (Paris Climate Accord) and technology transfer are also products of globalization. The relationship is complex.', 5),
  ],
  'how-media-works': [
    mc('How do most free news outlets make money?', ['Subscriptions and public funding equally', 'Primarily through advertising — selling audiences\' attention to advertisers, which creates incentives to maximize engagement rather than accuracy', 'Government subsidies', 'Direct donations from readers only'], 'Primarily through advertising — selling audiences\' attention to advertisers, which creates incentives to maximize engagement rather than accuracy', 'Advertising-supported media profits when more people watch/read longer. Outrage, fear, and novelty drive engagement. This business model creates incentives that can conflict with accurate, nuanced reporting.', 1),
    mc('What is the difference between news reporting and opinion/commentary?', ['There is no meaningful distinction in modern media', 'News reporting describes factual events; opinion/commentary interprets, analyzes, or argues about their meaning', 'Opinion is always biased; news is always objective', 'Opinion pieces must be labeled as fictional'], 'News reporting describes factual events; opinion/commentary interprets, analyzes, or argues about their meaning', 'The distinction matters: news should be verifiable facts; opinion reflects the writer\'s interpretation. Many outlets blur this line, and audiences often can\'t distinguish between them.', 2),
    mc('What is a news cycle?', ['The time it takes to print and distribute a newspaper', 'The rapid turnover of media attention from story to story — typically 24-48 hours before a story is replaced by new coverage', 'A news organization\'s production schedule', 'The pattern of which stories get covered in what order'], 'The rapid turnover of media attention from story to story — typically 24-48 hours before a story is replaced by new coverage', 'The 24-hour news cycle (and now social media\'s faster churn) means stories must compete for attention. Important stories can disappear quickly; the unusual and dramatic persist.', 3),
    mc('What is an algorithm\'s role in social media news consumption?', ['Algorithms ensure users see a balanced range of perspectives', 'Algorithms prioritize content that maximizes engagement — often showing people more of what they already agree with, creating filter bubbles', 'Algorithms only organize content chronologically', 'Algorithms are controlled by government regulators'], 'Algorithms prioritize content that maximizes engagement — often showing people more of what they already agree with, creating filter bubbles', 'Social media algorithms optimize for time-on-platform. Outrage and confirmation of existing beliefs drive engagement. This creates echo chambers where users see a distorted picture of reality that reinforces their existing views.', 4),
    mc('What is the difference between public broadcasting and commercial media?', ['Public broadcasting is government propaganda; commercial media is independent', 'Public broadcasting is funded by government/public support with a public service mandate; commercial media primarily serves advertisers\' interests', 'There is no meaningful difference in content or funding', 'Commercial media is always more accurate than public broadcasting'], 'Public broadcasting is funded by government/public support with a public service mandate; commercial media primarily serves advertisers\' interests', 'BBC, NPR, PBS have public service mandates — they must serve all audiences, not just profitable ones. They\'re more insulated from advertiser pressure but can face political pressure from funders.', 5),
  ],
  'identifying-bias': [
    mc('What is media bias?', ['Deliberate lies published by journalists', 'A systematic lean in how information is selected, framed, or presented that favors particular perspectives, groups, or conclusions', 'Any disagreement with one\'s own views', 'Only political bias in news coverage'], 'A systematic lean in how information is selected, framed, or presented that favors particular perspectives, groups, or conclusions', 'Bias can be explicit (opinion) or subtle (story selection, framing, word choice, whose voices are included). All media contains some bias — the question is how significant, in what direction, and whether it\'s acknowledged.', 1),
    mc('What is confirmation bias?', ['A journalist\'s bias toward confirming their editor\'s opinions', 'The tendency to search for, favor, and interpret information that confirms our existing beliefs while discounting contradicting information', 'A bias that only affects political conservatives', 'A statistical bias in polling methodology'], 'The tendency to search for, favor, and interpret information that confirms our existing beliefs while discounting contradicting information', 'Confirmation bias affects everyone regardless of politics. We notice evidence that supports our views and dismiss evidence that challenges them. It\'s a natural cognitive tendency that careful reasoning tries to counteract.', 2),
    mc('What questions should you ask to identify bias in a source?', ['Only "who wrote it?"', 'Who wrote it, who funds it, what perspective is centered/excluded, what words are chosen, and what context or counterevidence is omitted', '"Is this story interesting?" and "Do I agree with it?"', 'Only "Is this a reputable outlet?"'], 'Who wrote it, who funds it, what perspective is centered/excluded, what words are chosen, and what context or counterevidence is omitted', 'Bias detection requires lateral reading (check other sources about the source), looking at funding, noticing whose voices appear, and paying attention to framing — what\'s included AND excluded.', 3),
    mc('What is a false balance?', ['Presenting two viewpoints equally when evidence strongly supports one', 'Giving equal time to a scientific consensus and a fringe position — creating a misleading impression that there is genuine debate', 'An unfair attack on one political party', 'Reporting only one side of a story'], 'Giving equal time to a scientific consensus and a fringe position — creating a misleading impression that there is genuine debate', 'Presenting climate denial as equally valid to climate science, or anti-vaccine views as equally valid to medical consensus, creates false balance. Equal "both sides" treatment can mislead when evidence is not actually equal.', 4),
    mc('What does it mean to "read laterally"?', ['Reading from left to right', 'Opening multiple tabs to check what other sources say ABOUT your source — verifying its credibility before trusting its content', 'Reading the end of an article before the beginning', 'Only reading sources you already trust'], 'Opening multiple tabs to check what other sources say ABOUT your source — verifying its credibility before trusting its content', 'Lateral reading (Stanford researchers\' recommendation): don\'t read deeply into a source before verifying it. Fact-checkers immediately search what others say about the source — a more efficient credibility check.', 5),
  ],
  'spotting-misinformation': [
    mc('What is the difference between misinformation and disinformation?', ['They are the same thing', 'Misinformation is false information spread without intent to deceive; disinformation is deliberately false information spread to manipulate', 'Disinformation is slightly inaccurate; misinformation is entirely fabricated', 'Misinformation only spreads online; disinformation only in print'], 'Misinformation is false information spread without intent to deceive; disinformation is deliberately false information spread to manipulate', 'Someone sharing a false rumor believing it\'s true is spreading misinformation. A state actor creating fake stories to influence an election is spreading disinformation. Intent matters for the source — the harm is the same.', 1),
    mc('What is a deepfake?', ['A very convincing lie told in person', 'AI-generated or manipulated media — videos, images, or audio — that appears authentic but depicts events or statements that never happened', 'A type of online scam targeting elderly people', 'Exaggerated satire of real events'], 'AI-generated or manipulated media — videos, images, or audio — that appears authentic but depicts events or statements that never happened', 'Deepfakes use AI to put words in real people\'s mouths or create convincing fake images. They threaten to make visual "evidence" unreliable — raising the stakes for media literacy.', 2),
    mc('What are common warning signs that a story might be misinformation?', ['It disagrees with your political views', 'Emotional/outrage-triggering language, no named sources, unrecognizable outlet, no date, headline contradicts the article body, or it seems too perfectly confirming', 'It\'s only published on social media', 'It involves a public figure'], 'Emotional/outrage-triggering language, no named sources, unrecognizable outlet, no date, headline contradicts the article body, or it seems too perfectly confirming', 'Misinformation is often designed to provoke outrage or fear (you\'ll share angry content). Check: is this outlet real? Can I find this reported elsewhere? Are sources named? Does the article match the headline?', 3),
    mc('What is the "liar\'s dividend"?', ['The financial gain from selling fake news', 'The ability for people to dismiss authentic evidence as fake because of the existence of deepfakes and misinformation', 'The legal protection misinformation creators enjoy', 'The media profits from covering misinformation stories'], 'The ability for people to dismiss authentic evidence as fake because of the existence of deepfakes and misinformation', 'Deepfakes create a paradox: not only can fake evidence be created, but real evidence can be dismissed as potentially fake. Politicians and others can deny authentic recordings by claiming they\'re AI-generated.', 4),
    mc('What is the most reliable approach to fact-checking a claim?', ['Trust any source that quotes specific numbers', 'Check whether established fact-checking organizations (PolitiFact, FactCheck.org, Snopes) and multiple reliable news outlets have verified it', 'Trust social media posts with many likes and shares', 'Believe anything published by a major network'], 'Check whether established fact-checking organizations (PolitiFact, FactCheck.org, Snopes) and multiple reliable news outlets have verified it', 'No single source is infallible. Convergence across multiple independent, reputable sources increases confidence. Fact-checking organizations have transparent methodologies and track records you can evaluate.', 5),
  ],
}
