import type { ExerciseDef } from '../types'

function mc(
  question: string,
  options: string[],
  correctAnswer: string,
  explanation: string,
  order: number
): ExerciseDef {
  return { question, type: 'MULTIPLE_CHOICE', options, correctAnswer, explanation, order }
}

export const historyExercises7: Record<string, ExerciseDef[]> = {
  'logical-fallacies': [
    mc('What is an ad hominem fallacy?', ['Attacking an argument\'s weakest point', 'Attacking the person making an argument instead of the argument itself', 'Making an argument that appeals to emotion', 'Claiming something is true because many people believe it'], 'Attacking the person making an argument instead of the argument itself', '"You can\'t trust what she says about climate — she drives a big truck." The truck doesn\'t affect whether her argument about climate data is correct. Ad hominem attacks the speaker, not the substance.', 1),
    mc('What is a straw man fallacy?', ['Arguing against a position no one actually holds', 'Misrepresenting someone\'s argument to make it easier to attack — then refuting that distorted version', 'Using irrelevant facts to support a conclusion', 'Appealing to tradition to justify a practice'], 'Misrepresenting someone\'s argument to make it easier to attack — then refuting that distorted version', '"You want to reduce military spending." "So you want to leave the country defenseless!" The second statement exaggerates the first into an extreme no one actually argued.', 2),
    mc('What is a false dichotomy (either/or fallacy)?', ['Presenting more options than actually exist', 'Presenting only two options when more exist — "You\'re either with us or against us"', 'Claiming a cause produced an effect without evidence', 'Dismissing an argument because of where the speaker is from'], 'Presenting only two options when more exist — "You\'re either with us or against us"', 'Most complex issues have more than two positions. "Support this policy or you hate poor people" ignores the possibility of different approaches. False dichotomies force unnecessary either/or choices.', 3),
    mc('What is a slippery slope fallacy?', ['Arguing that a small action will inevitably lead to extreme consequences without demonstrating the causal chain', 'Gradually changing an argument during a debate', 'Using statistics to mislead', 'Appealing to a respected authority'], 'Arguing that a small action will inevitably lead to extreme consequences without demonstrating the causal chain', '"If we allow same-sex marriage, next people will want to marry their pets." This assumes a chain of consequences without evidence that each step actually leads to the next.', 4),
    mc('What is an appeal to authority fallacy?', ['Using any expert opinion to support a claim', 'Claiming something is true solely because an authority figure said so — especially when the authority is not an expert in the relevant field', 'Citing peer-reviewed research', 'Using historical examples to make an argument'], 'Claiming something is true solely because an authority figure said so — especially when the authority is not an expert in the relevant field', 'Expert consensus matters — but "a famous actor says this supplement works" is not medical evidence. Even real experts can be wrong, especially outside their field. Evidence, not authority, should settle factual claims.', 5),
  ],
  'evaluating-sources': [
    mc('What does it mean to evaluate a source\'s credibility?', ['Deciding if you agree with its conclusions', 'Assessing its accuracy, expertise, objectivity, currency, and purpose before deciding how much to trust it', 'Checking if it has a professional-looking website', 'Trusting any source cited by another source you trust'], 'Assessing its accuracy, expertise, objectivity, currency, and purpose before deciding how much to trust it', 'The CRAAP test: Currency (is it recent?), Relevance, Authority (who wrote it? what are their credentials?), Accuracy (is it verifiable? sourced?), Purpose (why was this written?).', 1),
    mc('What is the difference between primary and secondary sources?', ['Primary sources are more reliable; secondary sources are less reliable', 'Primary sources are original materials (documents, data, eyewitness accounts); secondary sources analyze or interpret primary sources', 'Primary sources are older; secondary sources are newer', 'Secondary sources are always biased; primary sources are neutral'], 'Primary sources are original materials (documents, data, eyewitness accounts); secondary sources analyze or interpret primary sources', 'A diary from 1865 is a primary source; a history book analyzing the Civil War is secondary. Primary sources offer raw evidence; secondary sources offer interpretation. Both have value.', 2),
    mc('Why is peer review important for scientific sources?', ['Peer review guarantees a study is correct', 'It means other experts in the field reviewed the methodology and findings before publication — a quality check that filters out obvious errors', 'Only peer-reviewed studies are ever worth reading', 'Peer review is performed by government agencies'], 'It means other experts in the field reviewed the methodology and findings before publication — a quality check that filters out obvious errors', 'Peer review is imperfect but essential. It catches methodological errors, unsupported conclusions, and ethical problems before publication. Non-peer-reviewed research (preprints, press releases) hasn\'t passed this check.', 3),
    mc('What should you consider about funding when evaluating a study?', ['Funded research is always biased and should be ignored', 'Funding source can create conflicts of interest — industry-funded research may have systematic biases favoring the funder\'s products or interests', 'Only government-funded research is trustworthy', 'Funding source is irrelevant to research quality'], 'Funding source can create conflicts of interest — industry-funded research may have systematic biases favoring the funder\'s products or interests', 'Tobacco industry-funded studies consistently found smoking less harmful. Pharmaceutical companies\' clinical trials show their drugs working more often than independent trials. Follow-the-money is a legitimate credibility question.', 4),
    mc('What does it mean for a claim to be "extraordinary"?', ['It is very important and interesting', 'It contradicts well-established evidence — such claims require stronger evidence than ordinary claims to be believed', 'It is supported by multiple sources', 'It comes from an expert outside the mainstream'], 'It contradicts well-established evidence — such claims require stronger evidence than ordinary claims to be believed', '"Extraordinary claims require extraordinary evidence" (Carl Sagan). A claim that a pill cures all cancers contradicts decades of cancer research — it needs much stronger evidence than a claim that aspirin relieves headaches.', 5),
  ],
  'forming-your-own-views': [
    mc('What distinguishes an opinion from a fact?', ['Opinions are wrong; facts are right', 'Facts are verifiable through evidence; opinions are judgments or beliefs that can\'t be true or false in the same way', 'Facts are stated by experts; opinions by ordinary people', 'There is no meaningful distinction in most contexts'], 'Facts are verifiable through evidence; opinions are judgments or beliefs that can\'t be true or false in the same way', '"The earth is 4.5 billion years old" is verifiable. "This policy is unfair" involves a value judgment. Many claims mix both — understanding the difference helps evaluate what evidence can and cannot resolve.', 1),
    mc('What is steelmanning?', ['Attacking the strongest version of your own argument', 'Articulating the strongest possible version of an opposing view before arguing against it', 'A debate technique for winning arguments', 'Agreeing with every point an opponent makes'], 'Articulating the strongest possible version of an opposing view before arguing against it', 'Steelmanning (opposite of strawmanning) means genuinely engaging with the best version of opposing arguments. It reduces tribalism, improves your own thinking, and produces more honest discourse.', 2),
    mc('What is the difference between changing your mind based on evidence vs. social pressure?', ['Both are equally valid reasons to update your beliefs', 'Updating beliefs based on new evidence is intellectually honest; changing views due to social pressure is not — it means conforming to avoid discomfort, not following truth', 'Social pressure is always a reliable guide to correct views', 'You should never change your initial view'], 'Updating beliefs based on new evidence is intellectually honest; changing views due to social pressure is not — it means conforming to avoid discomfort, not following truth', 'Intellectual integrity means following evidence wherever it leads, including to uncomfortable conclusions. Conforming to group pressure regardless of evidence is the foundation of groupthink and mob dynamics.', 3),
    mc('Why is intellectual humility important in forming views?', ['It means admitting you know nothing', 'Recognizing the limits of your knowledge and the possibility you\'re wrong makes you more open to evidence and less likely to hold bad views confidently', 'It means agreeing with experts on everything', 'It leads to never having strong opinions'], 'Recognizing the limits of your knowledge and the possibility you\'re wrong makes you more open to evidence and less likely to hold bad views confidently', 'Intellectual humility doesn\'t mean endless uncertainty — it means holding views in proportion to evidence and remaining genuinely open to revision. The most confident people are often most wrong.', 4),
    mc('What does it mean to think critically about your own beliefs?', ['Doubting everything until paralyzed by uncertainty', 'Subjecting your own views to the same scrutiny you apply to others\' — asking what evidence supports them, what could change your mind, and whether you\'re being consistent', 'Only accepting beliefs that can be proven mathematically', 'Constantly changing your views to appear open-minded'], 'Subjecting your own views to the same scrutiny you apply to others\' — asking what evidence supports them, what could change your mind, and whether you\'re being consistent', 'Critical thinking applies equally to your own beliefs. Ask: what evidence do I have? What would change my mind? Am I holding different standards for my side vs. the other side? Are my reasoning processes consistent?', 5),
  ],
}
