import type { AssessmentDef, AssessmentQuestionDef } from '../types'

const mc = (q: string, opts: string[], ans: string, exp: string, pts: number, ord: number): AssessmentQuestionDef =>
  ({ question: q, type: 'MULTIPLE_CHOICE', options: opts, correctAnswer: ans, explanation: exp, points: pts, order: ord })
const oe = (q: string, ans: string, exp: string, pts: number, ord: number): AssessmentQuestionDef =>
  ({ question: q, type: 'OPEN_ENDED', correctAnswer: ans, explanation: exp, points: pts, order: ord })

export const historyAssessments: Record<string, AssessmentDef> = {
  'how-government-works': {
    title: 'How Government Works Assessment', passingScore: 75, timeLimitMin: 25,
    questions: [
      mc('The principle of federalism divides power between:', ['The House and Senate', 'The federal government and state governments', 'The President and Congress', 'The courts and the executive branch'], 'The federal government and state governments', 'Federalism distributes sovereign power between the national government and states. States retain powers not granted to the federal government (10th Amendment). This structure creates multiple levels of governance and allows states to serve as "laboratories of democracy."', 1, 1),
      mc('Checks and balances prevent any one branch from becoming too powerful by:', ['Requiring all three branches to agree on every decision', 'Giving each branch specific powers to limit the other two', 'Rotating leadership among branches every four years', 'Allowing courts to overrule all legislation'], 'Giving each branch specific powers to limit the other two', 'Congress passes laws; the President can veto them; Congress can override the veto. The President nominates judges; the Senate confirms. Courts can strike down laws as unconstitutional. Each branch has leverage over the others.', 1, 2),
      mc('Judicial review — the power to strike down laws as unconstitutional — was established by:', ['The Constitution directly', 'The Bill of Rights', 'Marbury v. Madison (1803)', 'The Federalist Papers'], 'Marbury v. Madison (1803)', 'Chief Justice John Marshall\'s opinion in Marbury v. Madison established that the Supreme Court has the authority to review and invalidate laws that violate the Constitution — a power not explicitly stated in the document but now foundational to American law.', 1, 3),
      mc('The Electoral College system means a presidential candidate wins by:', ['Receiving more than 50% of the national popular vote', 'Winning 270 or more electoral votes', 'Winning the majority of U.S. states', 'Being selected by Congress'], 'Winning 270 or more electoral votes', 'Each state has electoral votes equal to its congressional delegation. The winner of each state (in most states, winner-take-all) receives all its electoral votes. 270 of 538 is the majority needed to win.', 1, 4),
      mc('A bill becomes a law when:', ['The President signs it or Congress overrides a veto with a two-thirds majority in both chambers', 'Either the House or Senate passes it', 'A committee approves it', 'The Supreme Court rules it constitutional'], 'The President signs it or Congress overrides a veto with a two-thirds majority in both chambers', 'A bill must pass both the House and Senate in identical form, then be signed by the President. If vetoed, Congress can override with a 2/3 majority in each chamber. A bill also becomes law if the President takes no action within 10 days while Congress is in session.', 1, 5),
      mc('The First Amendment protects:', ['The right to bear arms', 'Freedom of speech, religion, press, assembly, and petition', 'The right to a jury trial', 'Protection from unreasonable searches'], 'Freedom of speech, religion, press, assembly, and petition', 'The First Amendment\'s five freedoms are the cornerstone of American civil liberties. These protections are not absolute — speech that creates "clear and present danger" or constitutes defamation can be restricted.', 1, 6),
      mc('Congress\'s power of the purse means:', ['Congress controls all federal spending and taxation', 'The President can spend money without congressional approval', 'The Federal Reserve controls government spending', 'States fund most federal programs'], 'Congress controls all federal spending and taxation', 'Article I gives Congress exclusive authority to levy taxes and appropriate funds. The executive branch cannot spend money that Congress has not authorized — a critical check on presidential power.', 1, 7),
      mc('The 14th Amendment\'s Equal Protection Clause requires:', ['States to provide equal educational facilities to all students', 'That states treat all persons equally under the law', 'Federal elections to be conducted uniformly', 'Congress to treat all states identically in legislation'], 'That states treat all persons equally under the law', 'Ratified after the Civil War, the 14th Amendment has been used to challenge racial segregation (Brown v. Board), sex discrimination, and differential treatment of many groups. It extended constitutional protections against state (not just federal) action.', 1, 8),
      oe('Explain why the framers designed a system with separated powers and checks and balances, using the historical context of their experience with British rule.', 'The framers experienced British rule under a Parliament with near-unlimited power and a monarch who could abuse executive authority. They also worried about mob rule in a pure democracy. Separated powers ensure no single person or group controls all functions of government. Checks and balances (veto, override, judicial review, advice and consent) create friction that slows abusive action. They designed a system where ambition would counteract ambition — institutional competition as a safeguard against tyranny.', 'The framers were students of history and philosophy (Montesquieu, Locke) who saw concentrated power as the root of tyranny. Their design reflects a deep distrust of human nature in positions of authority. The resulting system is slow and often frustrating by design — that friction is a feature, not a bug.', 2, 9),
      oe('Describe how a citizen can participate in democracy beyond voting in presidential elections.', 'Civic participation includes: contacting elected representatives, attending town halls, running for local office (school board, city council), serving on juries, participating in ballot initiatives and referendums, joining advocacy organizations, supporting campaigns, attending public meetings, and engaging with local government which handles much of daily life (zoning, schools, roads). Presidential elections get the most attention, but local elections often have more immediate impact on everyday life with far fewer voters, meaning individual voices carry more weight.', 'Democracy requires participation beyond Election Day. Many consequential decisions are made at the local and state level. Voter turnout in local elections is often below 20%, meaning a small organized group can have enormous influence. Civic engagement is a skill and habit that compounds over time.', 2, 10),
    ],
  },
  'us-history-foundations': {
    title: 'US History: Foundations Assessment', passingScore: 75, timeLimitMin: 30,
    questions: [
      mc('The Declaration of Independence primarily argued that:', ['The colonies needed a stronger central government', 'King George III had violated colonists\' natural rights, justifying revolution', 'Trade restrictions were the sole cause of rebellion', 'The colonies sought limited home rule, not independence'], 'King George III had violated colonists\' natural rights, justifying revolution', 'Drawing on Locke\'s social contract theory, Jefferson argued that governments derive their just powers from the consent of the governed, and that when a government violates natural rights (life, liberty, pursuit of happiness), revolution is justified.', 1, 1),
      mc('The Constitutional Convention of 1787 was called primarily to:', ['Draft the Bill of Rights', 'Revise or replace the ineffective Articles of Confederation', 'Establish a standing army', 'Negotiate trade agreements with Britain'], 'Revise or replace the ineffective Articles of Confederation', 'The Articles of Confederation left Congress unable to tax, regulate commerce, or enforce laws. Shays\' Rebellion (1786) demonstrated the federal government\'s weakness. Delegates exceeded their mandate and wrote a new Constitution.', 1, 2),
      mc('The Missouri Compromise (1820) attempted to address slavery by:', ['Banning slavery in all U.S. territories', 'Admitting Missouri as a slave state and Maine as a free state, maintaining the Senate balance and prohibiting slavery north of 36°30\'', 'Granting slaveholders federal compensation for freed slaves', 'Extending the Northwest Ordinance to all territories'], 'Admitting Missouri as a slave state and Maine as a free state, maintaining the Senate balance and prohibiting slavery north of 36°30\'', 'The Missouri Compromise held the union together for three decades by balancing slave and free states in the Senate. It was effectively repealed by the Kansas-Nebraska Act (1854), which reopened the slavery question in territories.', 1, 3),
      mc('Manifest Destiny described the belief that:', ['The United States should remain geographically contained', 'Americans were divinely destined to expand across the continent', 'Native American tribes should be assimilated into American culture', 'Western territories should remain territories, not states'], 'Americans were divinely destined to expand across the continent', 'Manifest Destiny provided ideological justification for westward expansion, Mexican-American War, displacement of Native Americans, and acquisition of territory from the Pacific to the Rio Grande. It combined nationalism, racial ideology, and Protestant millennialism.', 1, 4),
      mc('The Dred Scott decision (1857) held that:', ['Congress could ban slavery in territories', 'Enslaved people had no legal standing to sue in federal courts and Congress could not ban slavery in territories', 'All people born in the United States were citizens', 'The Missouri Compromise was constitutional'], 'Enslaved people had no legal standing to sue in federal courts and Congress could not ban slavery in territories', 'Chief Justice Taney\'s decision outraged the North, effectively invalidating the Missouri Compromise and asserting that enslaved people were property with no rights. It accelerated the sectional crisis leading to the Civil War.', 1, 5),
      mc('Reconstruction (1865-1877) primarily aimed to:', ['Punish Southern leaders for treason', 'Rebuild the South physically, politically reintegrate Confederate states, and define the rights of formerly enslaved people', 'Expand the Union to Canada', 'Restore the pre-war plantation economy'], 'Rebuild the South physically, politically reintegrate Confederate states, and define the rights of formerly enslaved people', 'Reconstruction\'s goals were contested — Radical Republicans sought transformative change; Johnson and later Democrats sought restoration of the pre-war order. The 13th, 14th, and 15th Amendments were its most lasting achievements.', 1, 6),
      mc('The Three-Fifths Compromise in the Constitution counted enslaved people as:', ['Full citizens for all purposes', 'Three-fifths of a person for the purposes of congressional representation and taxation', 'One-half of a person for taxation only', 'Not counted for any constitutional purpose'], 'Three-fifths of a person for the purposes of congressional representation and taxation', 'This compromise gave Southern states more representation in Congress (and therefore more electoral votes) than they would have had if enslaved people were excluded entirely, embedding the political power of slaveholding states into the Constitution.', 1, 7),
      mc('The Federalist Papers were written primarily to:', ['Explain the failures of the Articles of Confederation', 'Persuade New York voters to ratify the Constitution', 'Outline the Bill of Rights', 'Justify the American Revolution to European powers'], 'Persuade New York voters to ratify the Constitution', 'Madison, Hamilton, and Jay wrote 85 essays under the pseudonym "Publius" to build support for ratification in the critical state of New York. They remain the most authoritative explanation of the framers\' intentions and constitutional theory.', 1, 8),
      oe('Explain how the Civil War fundamentally changed the relationship between the federal government and the states.', 'Before the Civil War, many Americans viewed their primary loyalty as belonging to their state. The Confederate argument for secession rested on states\' rights — the idea that states were sovereign and could leave the union. The Union\'s victory settled by force that the United States was a permanent, indivisible nation. The post-war amendments (13th, 14th, 15th) expanded federal power, making the federal government the guarantor of individual rights against state action — a fundamental shift from the original constitutional design.', 'The Civil War is often called the "Second Founding" because it resolved contradictions left by the framers. The 14th Amendment\'s citizenship and equal protection clauses created a new relationship between citizens and the federal government that would be the basis for civil rights litigation for the next 150 years.', 2, 9),
      oe('How did the institution of slavery shape American political, economic, and social development from the founding through the Civil War?', 'Economically, slavery powered the plantation system that produced tobacco, cotton, and other export crops funding American economic development. Politically, it distorted representation (Three-Fifths Compromise), drove westward expansion (the slavery question in new territories), and ultimately split the Democratic Party and prompted the formation of the Republican Party. Socially, it created a racial hierarchy that persisted long after emancipation, embedded in law and culture. Every major political crisis from 1787-1861 was fundamentally about slavery — compromises bought time but could not resolve the contradiction of a nation founded on liberty that institutionalized bondage.', 'Understanding slavery\'s centrality is essential to understanding American history. It was not a peripheral issue — it was embedded in the Constitution, the economy, westward expansion, and the social order. The Civil War, Reconstruction, and the Civil Rights Movement are all chapters in the unfinished story of reconciling American ideals with American reality.', 2, 10),
    ],
  },
  'us-history-modern': {
    title: 'US History: Modern Era Assessment', passingScore: 75, timeLimitMin: 30,
    questions: [
      mc('The Progressive Era (1890s-1920s) was characterized by:', ['Laissez-faire capitalism and minimal government regulation', 'Reform movements addressing corruption, labor conditions, monopolies, and political processes', 'Isolationism from world affairs', 'A return to agrarian values against industrialization'], 'Reform movements addressing corruption, labor conditions, monopolies, and political processes', 'Progressives championed antitrust legislation, food safety, women\'s suffrage, direct election of senators, and child labor laws. They believed government could and should address the inequities created by industrialization.', 1, 1),
      mc('The Great Depression was triggered primarily by:', ['World War I debt alone', 'A combination of stock market crash, bank failures, agricultural crisis, and deflationary policy responses', 'Excessive government spending in the 1920s', 'A drought that destroyed the agricultural economy'], 'A combination of stock market crash, bank failures, agricultural crisis, and deflationary policy responses', 'The 1929 crash exposed underlying weaknesses: overleveraged speculation, weak banks, agricultural distress, and international debt problems. The Fed\'s contractionary response deepened the depression, as did the Smoot-Hawley tariffs.', 1, 2),
      mc('The New Deal primarily aimed to:', ['Restore the 1920s level of economic inequality', 'Provide relief, recovery, and reform to address the Great Depression through expanded federal programs', 'Return to the gold standard and balanced budgets', 'Eliminate all private enterprise in favor of government control'], 'Provide relief, recovery, and reform to address the Great Depression through expanded federal programs', 'FDR\'s New Deal created Social Security, the FDIC, the SEC, rural electrification, and millions of jobs through the WPA and CCC. It permanently expanded the federal government\'s role in the economy and social welfare.', 1, 3),
      mc('The United States entered World War II directly because of:', ['German unrestricted submarine warfare alone', 'Japan\'s attack on Pearl Harbor on December 7, 1941', 'A formal alliance with Britain requiring entry upon their declaration of war', 'Congressional declaration of war in 1940'], 'Japan\'s attack on Pearl Harbor on December 7, 1941', 'While FDR wanted to aid Britain and faced rising tensions with Japan, the US remained officially neutral until Pearl Harbor. Germany then declared war on the US four days later, bringing America fully into both theaters.', 1, 4),
      mc('The Cold War was fundamentally a conflict between:', ['Nuclear-armed nations over specific territorial disputes', 'Competing ideological and economic systems — US-led capitalism versus Soviet-led communism', 'The US and China for dominance in Asia', 'European colonial powers and newly independent nations'], 'Competing ideological and economic systems — US-led capitalism versus Soviet-led communism', 'The Cold War was as much an ideological contest as a military one. Both superpowers sought to extend their economic and political systems globally, competing through proxy wars, economic aid, cultural diplomacy, and the arms race.', 1, 5),
      mc('Brown v. Board of Education (1954) was significant because it:', ['Granted voting rights to Black Americans', 'Unanimously struck down racial segregation in public schools as unconstitutional under the 14th Amendment', 'Integrated the U.S. military', 'Created affirmative action programs in universities'], 'Unanimously struck down racial segregation in public schools as unconstitutional under the 14th Amendment', 'Brown overturned the "separate but equal" doctrine of Plessy v. Ferguson (1896). Chief Justice Warren\'s unanimous opinion was a major victory for the NAACP\'s legal strategy and galvanized the Civil Rights Movement.', 1, 6),
      mc('The Civil Rights Act of 1964 prohibited:', ['Segregation in public schools specifically', 'Discrimination based on race, color, religion, sex, or national origin in employment and public accommodations', 'Poll taxes in federal elections', 'Gerrymandering of congressional districts'], 'Discrimination based on race, color, religion, sex, or national origin in employment and public accommodations', 'The Civil Rights Act outlawed discrimination in hotels, restaurants, theaters, and employment. Combined with the Voting Rights Act (1965), it dismantled the legal structure of Jim Crow — though enforcement remained a struggle.', 1, 7),
      mc('The Vietnam War\'s legacy in American political culture includes:', ['Renewed confidence in military intervention abroad', 'Deep skepticism about government credibility and overseas military commitments', 'Consensus that the war was necessary and well-executed', 'Permanent political dominance of the antiwar movement'], 'Deep skepticism about government credibility and overseas military commitments', 'Vietnam shattered Cold War consensus, revealed that the government had misled the public (Pentagon Papers), ended the military draft, introduced the War Powers Resolution (1973), and made future interventions politically costly. The "Vietnam syndrome" shaped foreign policy for decades.', 1, 8),
      oe('Explain how the Civil Rights Movement used non-violent direct action as a strategy and why it was effective in the American context.', 'Non-violent direct action (sit-ins, freedom rides, marches) forced confrontation with segregation while keeping the moral high ground. When authorities responded with violence — as in Birmingham with fire hoses and police dogs — it exposed the brutality of segregation to a national television audience. This moral clarity generated sympathy in the North and internationally, putting pressure on the federal government. Violence by protesters would have allowed authorities to frame the conflict as a public order problem rather than a civil rights crisis.', 'The strategy was designed for the specific context of American media, law, and politics. Martin Luther King Jr. understood that the movement needed federal intervention, and that federal action required public pressure, which required moral clarity. The combination of legal challenges (NAACP), legislative lobbying, and non-violent direct action was a sophisticated multi-front campaign.', 2, 9),
      oe('How did the September 11, 2001 attacks reshape American domestic policy and foreign policy in the decade that followed?', 'Domestically, 9/11 led to the creation of the Department of Homeland Security, the PATRIOT Act (expanded surveillance), and the transformation of airport security. The Authorization for Use of Military Force gave presidents broad war-making authority used for years afterward. Foreign policy shifted to the "War on Terror" — invasions of Afghanistan (2001) and Iraq (2003), drone programs, detention policies at Guantanamo, and a new doctrine of preemptive war. These choices had lasting consequences: the Iraq War destabilized the Middle East, contributed to the rise of ISIS, created trillions in debt, and cost thousands of American and hundreds of thousands of Iraqi lives.', 'The 9/11 response illustrates how a single event can reshape a nation\'s trajectory. Decisions made in the months after — many in an atmosphere of fear and incomplete information — had consequences playing out for decades. Understanding this period is essential for evaluating how democracies respond to security threats while preserving constitutional values.', 2, 10),
    ],
  },
  'world-history-ancient': {
    title: 'World History: Ancient to Medieval Assessment', passingScore: 75, timeLimitMin: 30,
    questions: [
      mc('The development of writing in Mesopotamia (cuneiform) was primarily driven by:', ['Religious purposes', 'The need to record agricultural surpluses, debts, and trade', 'Military strategy and battle planning', 'Astronomical observation'], 'The need to record agricultural surpluses, debts, and trade', 'The earliest cuneiform tablets (c. 3400 BCE) were administrative records — tracking grain, livestock, and labor. Writing emerged as a technology to manage the complexity of surplus-based urban economies, not as art or religion first.', 1, 1),
      mc('Athenian democracy differed from modern democracy in that:', ['It was a representative rather than direct system', 'Only adult male citizens participated — excluding women, slaves, and foreigners', 'All residents including foreigners voted', 'Decisions were made by an elected Senate'], 'Only adult male citizens participated — excluding women, slaves, and foreigners', 'Athenian democracy was direct (citizens voted on laws themselves) but radically exclusive by modern standards. Out of a population of perhaps 250,000-300,000, only ~30,000 adult male citizens could participate.', 1, 2),
      mc('The Pax Romana (Roman Peace) refers to:', ['A peace treaty between Rome and Carthage', 'A roughly 200-year period of relative stability and prosperity within the Roman Empire', 'The treaty ending the Punic Wars', 'Augustus\'s diplomatic policy toward neighboring kingdoms'], 'A roughly 200-year period of relative stability and prosperity within the Roman Empire', 'From Augustus (27 BCE) to Marcus Aurelius (180 CE), the Roman world experienced unprecedented stability, trade, and infrastructure development. Internal conflicts existed, but no major external invasions threatened the core empire.', 1, 3),
      mc('The Silk Road was significant because it:', ['Was a single road connecting China to Rome', 'Was a network of trade routes facilitating the exchange of goods, ideas, religions, and diseases across Eurasia', 'Was controlled exclusively by Chinese merchants', 'Primarily transported silk for European textile markets'], 'Was a network of trade routes facilitating the exchange of goods, ideas, religions, and diseases across Eurasia', 'The Silk Road transmitted not just silk but Buddhism, Islam, technologies (papermaking, printing), and eventually the Black Death. It was the primary engine of Eurasian cultural exchange for over a millennium.', 1, 4),
      mc('The fall of the Western Roman Empire in 476 CE was primarily caused by:', ['A single catastrophic battle with Germanic tribes', 'A combination of internal political instability, economic problems, military pressures, and administrative collapse', 'The rise of Christianity undermining Roman military values', 'A plague that killed the entire Roman army'], 'A combination of internal political instability, economic problems, military pressures, and administrative collapse', 'Rome\'s fall was a long process, not a sudden event. Historians debate the causes — political chaos (50+ emperors in 50 years), currency debasement, overextension, migration pressures, and administrative fragmentation all contributed. Many Romans barely noticed the "fall."', 1, 5),
      mc('The Islamic caliphates preserved and advanced which areas of knowledge during Europe\'s early medieval period?', ['Architecture and military technology only', 'Mathematics, astronomy, medicine, philosophy, and translations of Greek texts', 'Agricultural techniques and architecture', 'Legal systems and commercial law exclusively'], 'Mathematics, astronomy, medicine, philosophy, and translations of Greek texts', 'Islamic scholars translated, preserved, and advanced Greek philosophy and science during a period when much of it was lost in Western Europe. Algebra, algorithms, and advances in astronomy and medicine were developed in Baghdad, Cairo, and Cordoba.', 1, 6),
      mc('Feudalism in medieval Europe organized society around:', ['Merit-based advancement through the church hierarchy', 'Mutual obligations of land and service between lords and vassals', 'City-state governance with elected councils', 'Imperial centralized administration similar to Rome'], 'Mutual obligations of land and service between lords and vassals', 'Lords granted land (fiefs) to vassals in exchange for military service and loyalty. Serfs worked the land in exchange for protection. This hierarchical system of reciprocal obligations defined political, economic, and social relationships in medieval Europe.', 1, 7),
      mc('The Black Death (1347-1351) transformed European society primarily by:', ['Strengthening feudal institutions as lords took tighter control', 'Reducing the population by 30-60% and disrupting feudal labor relations, accelerating social change', 'Eliminating the Catholic Church\'s power', 'Causing the Hundred Years War'], 'Reducing the population by 30-60% and disrupting feudal labor relations, accelerating social change', 'With a third of the population dead, surviving peasants could demand better wages and conditions — feudal obligations weakened. The Church\'s inability to prevent the plague damaged its authority. The demographic shock accelerated the transition from medieval to early modern Europe.', 1, 8),
      oe('Compare and contrast how Alexander the Great\'s conquests and the spread of Islam (7th-8th centuries CE) each created cultural diffusion across a vast geographic area.', 'Alexander\'s conquests (334-323 BCE) spread Greek language, culture, and philosophy from Greece to Egypt and Persia to northwest India — the Hellenistic period. Greek became the lingua franca of educated elites; Greek architectural styles, philosophy, and religion blended with local traditions. Islamic expansion used both military conquest and trade to spread Arabic language, Islamic law, and a shared religious culture from the Arabian Peninsula to Spain and Central Asia. Both created large zones of cultural exchange — but Islam created a more durable and deeply rooted transformation because it was carried by a religious community, not just an empire, and continued spreading through trade long after political expansion slowed.', 'Cultural diffusion follows power but is not identical to it. Alexander\'s empire fragmented immediately after his death, but Hellenistic culture persisted for centuries. Islamic culture proved even more durable because religion, law, language, and commerce reinforced each other. Both illustrate how military and commercial networks transmit ideas across geographical boundaries.', 2, 9),
      oe('Explain how the Mongol Empire, despite its reputation for destruction, contributed to Eurasian connectivity and cultural exchange.', 'The Mongol Empire (13th-14th centuries) was the largest contiguous land empire in history. After conquest, the Mongols established the Pax Mongolica — a period of relative peace and safe trade across their territories. The Silk Road flourished; merchants, diplomats, and missionaries traveled from China to Persia to Europe. The Mongols were religiously tolerant and pragmatic administrators who employed conquered peoples\' skills. Technologies and ideas (printing, gunpowder, paper money) moved more freely across Eurasia than ever before. The unintended consequence was also the rapid spread of the Black Death along these same trade routes.', 'The Mongols challenge simple historical categories of "destructive" vs. "constructive." Their initial conquests were catastrophic, destroying cities and killing millions. But their administrative legacy created one of history\'s great moments of globalization. History\'s most transformative forces often carry both destruction and creation simultaneously.', 2, 10),
    ],
  },
  'world-history-modern': {
    title: 'World History: Modern Era Assessment', passingScore: 75, timeLimitMin: 30,
    questions: [
      mc('The Protestant Reformation fundamentally challenged:', ['The existence of God in European thought', 'The Catholic Church\'s authority as the sole interpreter of Christian doctrine', 'The political power of European monarchs', 'Scientific methods of inquiry'], 'The Catholic Church\'s authority as the sole interpreter of Christian doctrine', 'Luther\'s 95 Theses (1517) challenged indulgences but opened broader questions: Who interprets scripture? What is the source of religious authority? The Reformation fractured European Christianity and made religion a source of political conflict for over a century.', 1, 1),
      mc('The Columbian Exchange refers to:', ['Christopher Columbus\'s trade agreement with Spain', 'The transfer of plants, animals, diseases, and people between the Americas and Afro-Eurasia after 1492', 'European competition for Caribbean island colonies', 'Spanish silver from the Americas funding European wars'], 'The transfer of plants, animals, diseases, and people between the Americas and Afro-Eurasia after 1492', 'The Columbian Exchange transformed both hemispheres. Diseases (smallpox, measles) killed 50-90% of indigenous American populations. American crops (potatoes, maize, tomatoes) transformed Eurasian diets and enabled population growth. African slavery was established to replace collapsed indigenous labor.', 1, 2),
      mc('The Industrial Revolution\'s most significant long-term consequence was:', ['The immediate improvement of living standards for workers', 'Sustained economic growth through productivity increases that transformed global power and daily life', 'The decline of agricultural societies worldwide within a generation', 'The elimination of economic inequality through efficiency'], 'Sustained economic growth through productivity increases that transformed global power and daily life', 'Industrialization created modern capitalism, urbanization, the working class, and sustained growth. In the short term, conditions for factory workers were often brutal. Over generations, productivity gains created wealth that raised living standards — but unevenly.', 1, 3),
      mc('European imperialism in Africa in the 19th-20th centuries was driven by:', ['Humanitarian concern for African populations', 'Economic competition for raw materials and markets, combined with nationalism and racial ideology', 'African invitation for European development assistance', 'The need to settle growing European populations'], 'Economic competition for raw materials and markets, combined with nationalism and racial ideology', 'The Scramble for Africa (1880s-1914) was driven by industrialism\'s demand for raw materials, nationalist competition among European powers, and Social Darwinist ideology that justified conquest. The Berlin Conference (1884-85) divided Africa among European powers with no African participation.', 1, 4),
      mc('The assassination of Archduke Franz Ferdinand in 1914 triggered WWI primarily because:', ['He was the most popular leader in Europe', 'It activated a system of interlocking alliances between major European powers', 'Austria-Hungary had no army and needed German support', 'The assassination was ordered by the German government'], 'It activated a system of interlocking alliances between major European powers', 'Franz Ferdinand\'s assassination by a Serbian nationalist was the spark, but the underlying causes were the alliance system, militarism, imperial competition, and nationalism. The alliance network turned a regional dispute into a continental war within weeks.', 1, 5),
      mc('The Holocaust was the systematic murder of approximately:', ['500,000 Jewish people by Nazi Germany', '6 million Jewish people and millions of others by Nazi Germany and its collaborators', '1 million people in concentration camps', '2 million political prisoners by the Soviet Union'], '6 million Jewish people and millions of others by Nazi Germany and its collaborators', 'The Holocaust killed approximately 6 million Jews (two-thirds of European Jewry) plus millions more — Roma, disabled people, Soviet POWs, political prisoners, gay people, and others targeted by Nazi racial ideology. It was a systematic, state-organized genocide.', 1, 6),
      mc('The United Nations was established after WWII primarily to:', ['Create a world government with authority over national governments', 'Provide a forum for diplomacy and collective security to prevent future world wars', 'Enforce the peace terms imposed on Germany', 'Govern the decolonization of European empires'], 'Provide a forum for diplomacy and collective security to prevent future world wars', 'The UN (1945) was designed to address the failures of the League of Nations — including the United States\' refusal to join. Its Security Council structure (with five permanent veto-holding members) reflected the new post-war power balance.', 1, 7),
      mc('Decolonization after WWII was accelerated by:', ['European prosperity that allowed orderly transfer of power', 'The weakening of European powers by the war, rise of nationalist movements, and Cold War pressures', 'UN military enforcement of independence', 'American military intervention against European colonizers'], 'The weakening of European powers by the war, rise of nationalist movements, and Cold War pressures', 'WWII devastated European economies and exposed the contradictions of empires built on freedom fighting powers that denied freedom to colonized peoples. Both superpowers (for different reasons) pushed decolonization. Nationalist movements had been building for decades.', 1, 8),
      oe('Explain how the Enlightenment\'s ideas about reason, rights, and government contributed to the American and French Revolutions, and where the two revolutions diverged in outcomes.', 'Enlightenment thinkers (Locke, Montesquieu, Rousseau, Voltaire) argued that human reason, not divine authority, should govern society; that individuals have natural rights; and that government derives legitimacy from the consent of the governed. The American Revolution (1776) drew directly on Locke to justify independence and created a stable republic with protected rights. The French Revolution (1789) drew on Rousseau\'s popular sovereignty and went further — dismantling aristocracy, executing the king, and ultimately producing the Terror and Napoleon. The difference lies partly in context: America\'s revolution replaced a distant colonial government; France\'s revolution overthrew an entrenched domestic social order, creating much more violent conflict.', 'Both revolutions demonstrate how ideas reshape societies — but ideas don\'t determine outcomes alone. Social context, institutional capacity, and the nature of resistance shape whether revolutionary ideals produce stable democracy or violent radicalization. This lesson recurs throughout modern revolutionary history.', 2, 9),
      oe('How did the Cold War shape the global order between 1945 and 1991, and what were its consequences for countries in Asia, Africa, and Latin America?', 'The Cold War divided the world into competing blocs — US-aligned capitalist democracies and Soviet-aligned communist states — with a large non-aligned movement in between. For much of Asia, Africa, and Latin America, the Cold War meant superpower intervention in local conflicts to prevent the "other side" from gaining influence. The Korean War, Vietnam War, proxy conflicts in Angola, Congo, and Nicaragua, and US support for authoritarian regimes (if anti-communist) are examples. The Cold War often prolonged or intensified conflicts, supported dictators over democrats, and left destabilized states after superpower interest waned. Its end in 1991 brought both new freedoms (Eastern Europe) and new chaos (Yugoslavia, former Soviet states).', 'The Cold War\'s impact on the Global South is often underappreciated. For many countries, the superpower competition meant foreign intervention, weapons flows to both sides, and the subordination of local interests to geopolitical calculations made in Washington and Moscow. Understanding this history is essential for understanding the politics of many regions today.', 2, 10),
    ],
  },
  'media-literacy': {
    title: 'Media Literacy & Critical Thinking Assessment', passingScore: 75, timeLimitMin: 25,
    questions: [
      mc('Confirmation bias in media consumption means:', ['Believing everything the media reports', 'Preferentially seeking and accepting information that confirms existing beliefs while dismissing contradicting evidence', 'Being more likely to share stories from trusted news sources', 'Checking multiple sources before forming an opinion'], 'Preferentially seeking and accepting information that confirms existing beliefs while dismissing contradicting evidence', 'Confirmation bias is one of the most powerful cognitive distortions. It operates automatically — we find familiar ideas more credible and spend less cognitive effort evaluating claims we already agree with.', 1, 1),
      mc('A news outlet that consistently frames stories to favor one political perspective is demonstrating:', ['Bad reporting due to incompetence', 'Editorial bias, which can be present even in factually accurate reporting', 'Misinformation if any facts are wrong', 'Propaganda only if funded by a government'], 'Editorial bias, which can be present even in factually accurate reporting', 'Bias operates in story selection, framing, which voices are amplified, and what context is provided — even when individual facts are accurate. Identifying framing is as important as checking factual accuracy.', 1, 2),
      mc('The ad hominem fallacy attacks:', ['The logical structure of an argument', 'The character of the person making an argument instead of the argument itself', 'The evidence cited in an argument', 'A strawman version of the opposing view'], 'The character of the person making an argument instead of the argument itself', 'Ad hominem ("to the person") redirects from the argument\'s validity to the arguer\'s character, motives, or identity. Whether the speaker is likeable or not is irrelevant to whether their argument is sound.', 1, 3),
      mc('Which is the most reliable indicator of a credible news source?', ['It confirms your existing beliefs', 'It has a large social media following', 'It corrects errors transparently, names its reporters, and distinguishes news from opinion', 'It publishes stories that make you angry'], 'It corrects errors transparently, names its reporters, and distinguishes news from opinion', 'Credibility markers include: clear correction policy, named reporters with verifiable credentials, transparent funding, editorial independence from ownership, and clear separation of news and opinion sections.', 1, 4),
      mc('The difference between misinformation and disinformation is:', ['They are identical — both refer to false information', 'Misinformation is false information spread without intent to deceive; disinformation is deliberately crafted to mislead', 'Misinformation applies to social media only', 'Disinformation is technically true but misleading'], 'Misinformation is false information spread without intent to deceive; disinformation is deliberately crafted to mislead', 'Both spread false information, but intent differs. Your aunt sharing a debunked health claim is spreading misinformation. A government creating fake social media accounts to manipulate an election is disinformation. Both cause harm; the latter also involves deliberate deception.', 1, 5),
      mc('When evaluating a statistic in a news story, the most important question to ask is:', ['Who funded the research?', 'Is this statistic from a peer-reviewed source only?', 'What is the full context — sample size, methodology, comparison baseline, and what the statistic actually measures?', 'Does the statistic support my view?'], 'What is the full context — sample size, methodology, comparison baseline, and what the statistic actually measures?', 'Statistics can be technically accurate but deeply misleading without context. "Crime increased 100%" sounds dramatic but may mean 2 incidents became 4. "9 out of 10 dentists recommend" begs questions about which dentists, recommend for what, and who funded the survey.', 1, 6),
      mc('A false equivalence fallacy occurs when:', ['Two sides of a debate are accurately represented', 'Two things that are not actually similar in nature or evidence are presented as equivalent', 'An argument uses emotional language to persuade', 'A speaker quotes an expert out of context'], 'Two things that are not actually similar in nature or evidence are presented as equivalent', '"Some scientists believe in evolution; others don\'t — who\'s right?" This presents manufactured scientific dissent as equivalent to scientific consensus, implying equal weight where none exists. Media "bothsidesism" can create false equivalences between well-supported and fringe positions.', 1, 7),
      mc('The most effective way to verify a viral claim before sharing it is:', ['Check if people you trust have already shared it', 'Search specifically for debunking or fact-checks of the claim using a dedicated fact-checking site', 'Count how many people have shared it', 'See if a major TV network has covered it'], 'Search specifically for debunking or fact-checks of the claim using a dedicated fact-checking site', 'Snopes, PolitiFact, FactCheck.org, and AP Fact Check are designed to investigate viral claims. Searching the exact text of a claim with "fact check" added is often revealing. Social sharing velocity is not evidence of accuracy — false claims spread faster than true ones.', 1, 8),
      oe('Describe the difference between a logical argument\'s validity and its soundness, using an example.', 'A valid argument has a logical structure where the conclusion follows from the premises (if premises are true, the conclusion must be true). A sound argument is both valid AND has true premises. Example: "All mammals breathe air. Whales are mammals. Therefore whales breathe air." — this is valid and sound. "All cats can fly. My pet is a cat. Therefore my pet can fly." — this is valid (the logic holds) but unsound because the first premise is false. Evaluating arguments requires checking both the logical structure and the truth of the premises.', 'Validity is about form; soundness is about both form and truth. Many misleading arguments are logically valid — the trick is the false premise buried in them. Identifying premises and checking whether they\'re actually true is the core skill of critical thinking.', 2, 9),
      oe('You see a social media post claiming a well-known scientist said vaccines cause autism, accompanied by a short video clip. Describe your step-by-step process for evaluating this claim before deciding whether to share it.', 'Step 1: Identify the claim specifically. Step 2: Search for the full video/context — clips are often edited to change meaning. Step 3: Search the scientist\'s name and the claim on fact-checking sites. Step 4: Look for the original source (interview, paper, talk) to see the full quote in context. Step 5: Check scientific consensus on the claim itself using authoritative sources (CDC, peer-reviewed meta-analyses). Step 6: Consider the source of the post — who benefits from this spreading? The bar for sharing a dramatic claim should be much higher than for believing it privately.', 'Viral health misinformation is especially dangerous because it can affect life-or-death decisions. The asymmetry between spreading a false claim (seconds) and correcting it (never fully successful) means the responsible threshold for sharing is high. If you can\'t verify it, don\'t amplify it.', 2, 10),
    ],
  },
}
