import type { ExerciseDef } from '../types'

function mc(
  question: string,
  options: string[],
  correctAnswer: string,
  explanation: string,
  order: number
): ExerciseDef {
  return { question, type: 'MULTIPLE_CHOICE', options, correctAnswer, explanation, order }
}

export const historyExercises2: Record<string, ExerciseDef[]> = {
  'colonization': [
    mc('What was the first permanent English settlement in North America?', ['Plymouth, Massachusetts', 'Jamestown, Virginia (1607)', 'Roanoke, Virginia', 'Boston, Massachusetts'], 'Jamestown, Virginia (1607)', 'Jamestown (1607) was the first permanent English settlement. It nearly failed due to disease, starvation, and conflict — tobacco cultivation eventually made it profitable.', 1),
    mc('What was the primary motivation for most European colonization of North America?', ['Religious freedom for all settlers', 'Economic gain — trade, resources, and land — combined with national competition and religious motives', 'Escaping political persecution exclusively', 'Scientific exploration'], 'Economic gain — trade, resources, and land — combined with national competition and religious motives', 'Most colonization was driven by profit and empire-building. Spain sought silver and gold; England and France sought trade and land. Some settlers sought religious freedom (Pilgrims) but economics dominated.', 2),
    mc('What was the Columbian Exchange?', ['A treaty dividing the Americas between Spain and Portugal', 'The transfer of plants, animals, diseases, and people between the Americas and Europe/Africa/Asia after 1492', 'A trade agreement between colonies and England', 'The exchange of enslaved people between Africa and the Americas'], 'The transfer of plants, animals, diseases, and people between the Americas and Europe/Africa/Asia after 1492', 'The Columbian Exchange transformed global diets (potatoes, corn, tomatoes to Europe; wheat, horses to Americas) and devastated Indigenous populations through introduced diseases (smallpox).', 3),
    mc('What was the impact of colonization on Indigenous peoples?', ['Minimal — colonizers mostly avoided contact', 'Devastating — disease, warfare, displacement, and enslavement killed millions and destroyed cultures', 'Primarily beneficial — colonizers brought technology and improved living standards', 'Limited to coastal areas only'], 'Devastating — disease, warfare, displacement, and enslavement killed millions and destroyed cultures', 'Estimates suggest 50-90% of Indigenous populations died from European diseases alone. Survivors faced warfare, forced conversion, land seizure, and enslavement over the following centuries.', 4),
    mc('What was the "triangular trade"?', ['Trade between three American colonies', 'The Atlantic trade network linking Europe, Africa, and the Americas — exporting enslaved people from Africa, goods from colonies to Europe', 'Trade between three European empires', 'A trade agreement between North and South American colonies'], 'The Atlantic trade network linking Europe, Africa, and the Americas — exporting enslaved people from Africa, goods from colonies to Europe', 'The triangular trade: Europe sent manufactured goods to Africa, Africa sent enslaved people to the Americas, the Americas sent raw materials (tobacco, cotton, sugar) to Europe. It built European and colonial wealth on enslaved labor.', 5),
  ],
  'causes-of-revolution': [
    mc('What is "taxation without representation"?', ['Paying taxes to a foreign country', 'The colonial complaint that Britain taxed them without giving them representation in Parliament — a violation of English rights', 'The right of colonies to create their own tax laws', 'A protest against high tax rates specifically'], 'The colonial complaint that Britain taxed them without giving them representation in Parliament — a violation of English rights', 'After the French and Indian War, Britain taxed colonists (Stamp Act, Townshend Acts) to pay war debts. Colonists argued they couldn\'t be taxed without a voice in Parliament.', 1),
    mc('What sparked the Boston Massacre (1770)?', ['A colonial attack on British soldiers', 'A tense confrontation between colonists and British soldiers that ended with soldiers firing into the crowd, killing five', 'A British assault on a colonial meeting', 'A tax protest that turned violent'], 'A tense confrontation between colonists and British soldiers that ended with soldiers firing into the crowd, killing five', 'Tensions over the British military presence led to a confrontation. Soldiers fired into the crowd, killing five colonists. Patriots (especially Paul Revere\'s engraving) used it as propaganda to build anti-British sentiment.', 2),
    mc('What was the Boston Tea Party (1773)?', ['A meeting of colonial leaders to plan the Revolution', 'Colonial protestors dumped British tea into Boston Harbor to protest the Tea Act — taxation without representation', 'A British seizure of colonial tea ships', 'A trade dispute over tea tariffs'], 'Colonial protestors dumped British tea into Boston Harbor to protest the Tea Act — taxation without representation', 'The Sons of Liberty, disguised as Mohawk warriors, boarded East India Company ships and dumped 342 chests of tea. Britain responded with the Coercive (Intolerable) Acts, radicalizing more colonists.', 3),
    mc('What were the Intolerable Acts?', ['Colonial laws that angered British merchants', 'British laws punishing Massachusetts after the Boston Tea Party — closing Boston harbor, restricting colonial self-governance', 'Acts banning colonial manufacture of goods', 'Laws restricting religious practice in colonies'], 'British laws punishing Massachusetts after the Boston Tea Party — closing Boston harbor, restricting colonial self-governance', 'Britain\'s harsh response to the Tea Party unified other colonies in defense of Massachusetts, accelerating the path to revolution. The "punishment" backfired diplomatically.', 4),
    mc('What was the Enlightenment\'s influence on the American Revolution?', ['It provided military strategy for colonists', 'Enlightenment ideas about natural rights, social contract, and popular sovereignty justified revolution against an unjust government', 'It created anti-religious sentiment in the colonies', 'It had no significant influence on colonial thinking'], 'Enlightenment ideas about natural rights, social contract, and popular sovereignty justified revolution against an unjust government', 'Locke\'s natural rights (life, liberty, property), Montesquieu\'s separation of powers, and Rousseau\'s social contract directly influenced Jefferson, Madison, and the Declaration of Independence.', 5),
  ],
  'revolution-and-founding': [
    mc('What does the Declaration of Independence primarily argue?', ['A list of grievances against Britain only', 'That all men are created equal with unalienable rights, that government derives legitimacy from the consent of the governed, and that revolution is justified when government fails its purpose', 'A plan for the new American government', 'A request for peace negotiations with Britain'], 'That all men are created equal with unalienable rights, that government derives legitimacy from the consent of the governed, and that revolution is justified when government fails its purpose', 'Jefferson\'s Declaration (1776) articulates Enlightenment principles: natural rights, popular sovereignty, and the right to revolution — then lists 27 grievances against King George.', 1),
    mc('Why was the Battle of Saratoga (1777) significant?', ['It was the first major American victory', 'It convinced France to formally ally with the American colonies — turning the Revolution into a global conflict', 'It ended the Revolution', 'It was where Washington crossed the Delaware'], 'It convinced France to formally ally with the American colonies — turning the Revolution into a global conflict', 'France, eager to weaken Britain, had been secretly aiding the colonies. Saratoga\'s American victory proved the colonists could win, bringing French troops, ships, and funding openly.', 2),
    mc('What was the Articles of Confederation?', ['The first draft of the Declaration of Independence', 'The first governing document of the United States — creating a weak central government that proved ineffective', 'The British response to colonial demands', 'The treaty ending the Revolutionary War'], 'The first governing document of the United States — creating a weak central government that proved ineffective', 'The Articles (1781-1789) created a loose union where states had most power. The central government couldn\'t tax, regulate commerce, or enforce laws — leading to the Constitutional Convention.', 3),
    mc('The Constitutional Convention of 1787 produced what major compromise between large and small states?', ['The Missouri Compromise', 'The Great Compromise: a bicameral Congress with proportional representation in the House and equal representation in the Senate', 'The Three-Fifths Compromise', 'The Electoral College Compromise'], 'The Great Compromise: a bicameral Congress with proportional representation in the House and equal representation in the Senate', 'Large states wanted representation by population (Virginia Plan); small states wanted equal representation (New Jersey Plan). The Great Compromise created our bicameral Congress.', 4),
    mc('What was the Three-Fifths Compromise?', ['A deal giving free Black men partial voting rights', 'A compromise counting enslaved people as 3/5 of a person for apportioning House seats and taxes', 'A plan dividing states into thirds for electoral purposes', 'A tax agreement giving Southern states a discount'], 'A compromise counting enslaved people as 3/5 of a person for apportioning House seats and taxes', 'Southern states wanted to count enslaved people for representation but not for taxation. Northern states objected. The 3/5 compromise gave the South more House seats, amplifying slaveholder political power.', 5),
  ],
  'early-republic': [
    mc('What were the Federalist Papers?', ['Propaganda for British colonial rule', 'A series of essays by Hamilton, Madison, and Jay arguing for ratification of the Constitution', 'The first laws passed by Congress', 'Anti-federalist arguments against a strong central government'], 'A series of essays by Hamilton, Madison, and Jay arguing for ratification of the Constitution', '85 essays (1787-88) argued for the Constitution\'s ratification. Federalist No. 10 (factions/democracy), No. 51 (checks and balances), and No. 78 (judicial review) remain essential to constitutional interpretation.', 1),
    mc('What is the significance of Washington\'s Farewell Address (1796)?', ['It declared war on France', 'It warned against permanent foreign alliances and domestic political factions (parties)', 'It called for the abolition of slavery', 'It argued for a stronger federal government'], 'It warned against permanent foreign alliances and domestic political factions (parties)', 'Washington warned that excessive partisanship and foreign entanglements would destroy the republic. His warnings about factions proved prophetic as the two-party system immediately emerged.', 2),
    mc('What was the Louisiana Purchase (1803)?', ['A treaty with France granting trade rights on the Mississippi River', 'The US purchase of ~828,000 square miles from France for $15 million, doubling the country\'s size', 'A purchase of Florida from Spain', 'A land grant to settle the Ohio Valley'], 'The US purchase of ~828,000 square miles from France for $15 million, doubling the country\'s size', 'Napoleon needed money and feared British seizure. Jefferson, despite constitutional concerns about implied powers, bought the territory that stretched from the Mississippi to the Rockies.', 3),
    mc('What was the War of 1812 primarily about?', ['Conflict over the Louisiana Purchase', 'British interference with American shipping, impressment of sailors, and US desire to expand into British Canada', 'A dispute over the US-Canadian border', 'Conflict with Spain over Florida'], 'British interference with American shipping, impressment of sailors, and US desire to expand into British Canada', 'Britain, at war with Napoleon, violated American neutrality and forced American sailors into the Royal Navy. The inconclusive war ended with the status quo but boosted American nationalism.', 4),
    mc('What was Manifest Destiny as an ideology?', ['The belief that America should remain isolated from world affairs', 'The 19th-century belief that US expansion across the continent was inevitable, divinely ordained, and justified', 'A legal doctrine authorizing westward settlement', 'A diplomatic agreement with Mexico about borders'], 'The 19th-century belief that US expansion across the continent was inevitable, divinely ordained, and justified', 'Manifest Destiny (term coined 1845) provided ideological justification for westward expansion at the expense of Indigenous peoples and Mexico — framing conquest as Providence\'s will.', 5),
  ],
  'westward-expansion': [
    mc('What was the Indian Removal Act (1830)?', ['A law granting land rights to Native Americans', 'A law authorizing the forced relocation of Indigenous peoples east of the Mississippi to territory west of it', 'A Supreme Court ruling protecting Native land', 'A treaty guaranteeing Native sovereignty'], 'A law authorizing the forced relocation of Indigenous peoples east of the Mississippi to territory west of it', 'President Jackson\'s Indian Removal Act led to the forced removal of the Cherokee, Creek, Seminole, and other nations — killing thousands on the Trail of Tears.', 1),
    mc('What was the Mexican-American War (1846-48) and its outcome?', ['A border dispute resolved by negotiation', 'A US war with Mexico that resulted in Mexico ceding the Southwest (California, Texas, New Mexico) to the US', 'Mexico\'s war of independence from Spain', 'A conflict over trade along the Santa Fe Trail'], 'A US war with Mexico that resulted in Mexico ceding the Southwest (California, Texas, New Mexico) to the US', 'After Texas annexation, border disputes led to war. The Treaty of Guadalupe Hidalgo (1848) gave the US ~500,000 sq miles — including California (just before gold was discovered).', 2),
    mc('What triggered the California Gold Rush (1848-49)?', ['A government survey discovering gold deposits', 'The discovery of gold at Sutter\'s Mill in January 1848 — news spread, bringing 300,000 prospectors from around the world', 'Native American trade of gold with settlers', 'A mining company\'s discovery in the Sierra Nevada'], 'The discovery of gold at Sutter\'s Mill in January 1848 — news spread, bringing 300,000 prospectors from around the world', 'The Gold Rush transformed California from a sparsely settled Mexican province to a state in two years. It also devastated California Native peoples and contributed to sectional tensions over new states.', 3),
    mc('What was the Homestead Act (1862)?', ['A law granting freedom to enslaved people in Confederate states', 'A law offering 160 acres of federal land to settlers who farmed it for five years', 'A law establishing Native American reservations', 'A land sale program for veterans'], 'A law offering 160 acres of federal land to settlers who farmed it for five years', 'The Homestead Act drew millions of settlers to the Great Plains, transforming the region but also accelerating the destruction of Indigenous peoples\' ways of life and the buffalo population.', 4),
    mc('What was the transcontinental railroad and why did it matter?', ['A railroad connecting North and South', 'A rail line (completed 1869) linking the East Coast to California — transforming commerce, settlement, and communications', 'A proposed rail line that was never completed', 'A railroad connecting the US to Canada'], 'A rail line (completed 1869) linking the East Coast to California — transforming commerce, settlement, and communications', 'The Central Pacific and Union Pacific (with Chinese immigrant labor) met at Promontory Summit, Utah. The railroad made cross-country travel days instead of months, spurring Western settlement and national integration.', 5),
  ],
  'slavery-and-sectional-crisis': [
    mc('What was the Missouri Compromise (1820)?', ['A law ending slavery nationwide', 'An agreement admitting Missouri as a slave state, Maine as a free state, and banning slavery above 36°30\' in the Louisiana Purchase territory', 'A compromise on tariffs between North and South', 'A treaty ending Native American conflicts in Missouri'], 'An agreement admitting Missouri as a slave state, Maine as a free state, and banning slavery above 36°30\' in the Louisiana Purchase territory', 'The Missouri Compromise temporarily eased sectional tensions by maintaining the Senate balance between free and slave states while drawing a geographic line for slavery\'s expansion.', 1),
    mc('What was the Compromise of 1850?', ['An agreement ending the Mexican-American War', 'A series of laws admitting California as free, creating popular sovereignty in new territories, and strengthening the Fugitive Slave Act', 'A compromise giving slavery equal status with free labor', 'A plan to compensate slaveholders for emancipation'], 'A series of laws admitting California as free, creating popular sovereignty in new territories, and strengthening the Fugitive Slave Act', 'Henry Clay\'s compromise temporarily settled sectional disputes but the Fugitive Slave Act outraged Northerners by requiring them to return escaped people to slavery.', 2),
    mc('What was the Kansas-Nebraska Act (1854) and why was it significant?', ['A law organizing territories on the Great Plains', 'It repealed the Missouri Compromise, allowing popular sovereignty to decide slavery in Kansas and Nebraska — leading to violent conflict ("Bleeding Kansas")', 'A law restricting westward migration', 'A compromise that satisfied both North and South'], 'It repealed the Missouri Compromise, allowing popular sovereignty to decide slavery in Kansas and Nebraska — leading to violent conflict ("Bleeding Kansas")', 'The Act destroyed the Whig Party and gave birth to the Republican Party. Pro- and anti-slavery settlers flooded Kansas, creating two competing governments and guerrilla warfare.', 3),
    mc('What was the Dred Scott decision (1857)?', ['A ruling freeing enslaved people who had lived in free states', 'A Supreme Court ruling that enslaved people were property, not citizens, and Congress couldn\'t ban slavery in territories', 'A decision expanding voting rights for free Black men', 'A ruling protecting the rights of free Black citizens'], 'A Supreme Court ruling that enslaved people were property, not citizens, and Congress couldn\'t ban slavery in territories', 'Chief Justice Taney\'s Dred Scott decision inflamed Northern opinion, invalidated the Missouri Compromise line, and convinced many that slaveholders controlled the federal government.', 4),
    mc('What was the Underground Railroad?', ['A literal underground train system', 'A network of secret routes and safe houses helping enslaved people escape to free states or Canada', 'A system for transporting goods from South to North', 'A communication network between abolitionist groups'], 'A network of secret routes and safe houses helping enslaved people escape to free states or Canada', 'Conductors like Harriet Tubman helped hundreds escape. Safe houses stretched from the Deep South to Canada. Tubman made 13 missions, freeing roughly 70 people.', 5),
  ],
}
