import type { ExerciseDef } from '../types'

function mc(
  question: string,
  options: string[],
  correctAnswer: string,
  explanation: string,
  order: number
): ExerciseDef {
  return { question, type: 'MULTIPLE_CHOICE', options, correctAnswer, explanation, order }
}

export const historyExercises4: Record<string, ExerciseDef[]> = {
  'social-change-in-the-sixties': [
    mc('What was the counterculture movement of the 1960s?', ['A conservative reaction to civil rights', 'A youth-led cultural rebellion rejecting mainstream values, embracing peace, sexual freedom, and experimentation', 'A political movement to expand government programs', 'An artistic movement focused on abstract painting'], 'A youth-led cultural rebellion rejecting mainstream values, embracing peace, sexual freedom, and experimentation', 'The counterculture emerged from anti-war sentiment, civil rights inspiration, and postwar affluence. Rock music, communes, psychedelics, and anti-establishment politics defined a generational break.', 1),
    mc('What was the significance of the Voting Rights Act of 1965?', ['It gave women the right to vote', 'It banned discriminatory voting practices (literacy tests, poll taxes) that had disenfranchised Black voters throughout the South', 'It lowered the voting age to 18', 'It established federal oversight of all elections'], 'It banned discriminatory voting practices (literacy tests, poll taxes) that had disenfranchised Black voters throughout the South', 'The Voting Rights Act, signed by LBJ after the Bloody Sunday march in Selma, dramatically increased Black voter registration in Southern states — a key achievement of the Civil Rights Movement.', 2),
    mc('What sparked the feminist movement of the 1960s-70s?', ['Only the contraceptive pill', 'A combination of WWII workforce experience, civil rights inspiration, Betty Friedan\'s "The Feminine Mystique," and workplace discrimination', 'A political party created specifically for women\'s rights', 'The 19th Amendment\'s passage'], 'A combination of WWII workforce experience, civil rights inspiration, Betty Friedan\'s "The Feminine Mystique," and workplace discrimination', 'Second-wave feminism addressed workplace inequality, reproductive rights, domestic violence, and legal discrimination. NOW (1966), Ms. Magazine, Title IX (1972), and Roe v. Wade (1973) were major outcomes.', 3),
    mc('What was the War Powers Resolution (1973)?', ['A declaration of war against North Vietnam', 'A law requiring the President to notify Congress within 48 hours of deploying troops and limiting unauthorized military engagement to 60 days', 'A treaty ending the Vietnam War', 'A law giving the President unlimited authority in wartime'], 'A law requiring the President to notify Congress within 48 hours of deploying troops and limiting unauthorized military engagement to 60 days', 'Congress passed the War Powers Resolution over Nixon\'s veto after Vietnam — asserting legislative power over military commitments and responding to the undeclared Vietnam War.', 4),
    mc('What was Watergate?', ['A foreign policy scandal involving the CIA', 'The political scandal where Nixon\'s campaign operatives broke into Democratic headquarters; Nixon\'s cover-up led to his resignation in 1974', 'An environmental disaster in Washington DC', 'A Supreme Court case about presidential power'], 'The political scandal where Nixon\'s campaign operatives broke into Democratic headquarters; Nixon\'s cover-up led to his resignation in 1974', 'The Watergate break-in, cover-up, and obstruction of justice led to the first presidential resignation in US history. It severely damaged public trust in government.', 5),
  ],
  'america-in-the-21st-century': [
    mc('What were the September 11, 2001 attacks?', ['A domestic terror attack by a militia group', 'Coordinated al-Qaeda terrorist attacks using hijacked planes that destroyed the World Trade Center and damaged the Pentagon, killing nearly 3,000', 'A cyberattack on US government infrastructure', 'A failed foreign military attack on US soil'], 'Coordinated al-Qaeda terrorist attacks using hijacked planes that destroyed the World Trade Center and damaged the Pentagon, killing nearly 3,000', '9/11 was the deadliest terrorist attack in history. It led to the War in Afghanistan, the PATRIOT Act, the creation of DHS, and a dramatic reshaping of US foreign policy and domestic security.', 1),
    mc('What was the 2008 financial crisis?', ['A stock market crash caused by the dot-com bubble', 'A global financial collapse triggered by the collapse of the US housing bubble and risky mortgage-backed securities, causing the worst recession since the Great Depression', 'A banking crisis caused by foreign currency manipulation', 'A government default on national debt'], 'A global financial collapse triggered by the collapse of the US housing bubble and risky mortgage-backed securities, causing the worst recession since the Great Depression', 'Deregulated financial markets, predatory lending, and complex derivatives built on bad mortgages created a systemic crisis. Lehman Brothers failed; unemployment hit 10%; Congress passed a $700 billion bailout.', 2),
    mc('What was the Affordable Care Act (2010)?', ['A law that created Medicare and Medicaid', 'A law expanding health insurance coverage through insurance marketplaces, Medicaid expansion, and requiring coverage for pre-existing conditions', 'A law creating a single-payer healthcare system', 'A law reducing government involvement in healthcare'], 'A law expanding health insurance coverage through insurance marketplaces, Medicaid expansion, and requiring coverage for pre-existing conditions', 'The ACA ("Obamacare") reduced the uninsured rate significantly. Key provisions: insurance marketplaces, Medicaid expansion, coverage for pre-existing conditions, allowing children to stay on parents\' plans to 26.', 3),
    mc('What was the COVID-19 pandemic\'s impact on the US?', ['Minimal — it lasted only a few months', 'Over 1 million American deaths, economic disruption, accelerated remote work/learning, and deep political polarization around public health measures', 'Primarily an economic crisis with few health impacts', 'It primarily affected only elderly Americans'], 'Over 1 million American deaths, economic disruption, accelerated remote work/learning, and deep political polarization around public health measures', 'COVID-19 killed more Americans than any event since the Civil War. It triggered the fastest vaccine development in history, massive stimulus spending, and exposed deep divisions in American society.', 4),
    mc('What characterizes the political polarization of early 21st century America?', ['Increasing bipartisan cooperation on major issues', 'Deepening ideological sorting of the parties, decline of moderates, media fragmentation into partisan ecosystems, and declining trust in institutions', 'A shift toward a third-party system', 'Growing consensus on economic and social policy'], 'Deepening ideological sorting of the parties, decline of moderates, media fragmentation into partisan ecosystems, and declining trust in institutions', 'The parties have ideologically sorted — more liberal Democrats, more conservative Republicans — while cable news, social media, and gerrymandering reinforce divisions. Trust in government, media, and institutions has declined.', 5),
  ],
  'first-civilizations': [
    mc('What was Mesopotamia and why is it called the "cradle of civilization"?', ['A region in Egypt known for its pyramids', 'The river valley between the Tigris and Euphrates (modern Iraq) where some of the earliest cities, writing, and organized government emerged', 'A region in India where agriculture first developed', 'The area around the Nile where ancient Egypt arose'], 'The river valley between the Tigris and Euphrates (modern Iraq) where some of the earliest cities, writing, and organized government emerged', 'Sumer (c. 3500 BCE) produced the first cities (Ur, Uruk), cuneiform writing, the wheel, and formal law codes. The fertile floodplains enabled agricultural surplus that supported specialization.', 1),
    mc('What was the significance of cuneiform writing?', ['It was the first alphabetic writing system', 'The first writing system (Sumerian), used for record-keeping, law, and literature — enabling the accumulation and transmission of knowledge', 'A secret religious writing used by priests only', 'A pictographic system used only for art'], 'The first writing system (Sumerian), used for record-keeping, law, and literature — enabling the accumulation and transmission of knowledge', 'Cuneiform (c. 3200 BCE) began as accounting marks for grain and goods. It evolved to record laws (Hammurabi\'s Code), literature (Epic of Gilgamesh), and religious texts.', 2),
    mc('What was Hammurabi\'s Code?', ['The first Egyptian religious text', 'One of the earliest written legal codes — setting punishments for various offenses, establishing the principle that laws apply to everyone', 'A military treaty between Mesopotamian city-states', 'A system of taxation for the Babylonian empire'], 'One of the earliest written legal codes — setting punishments for various offenses, establishing the principle that laws apply to everyone', 'Hammurabi\'s Code (c. 1754 BCE) contained 282 laws inscribed on a stele. Its "eye for an eye" principle and written, public laws were revolutionary — though punishments varied by social class.', 3),
    mc('What was ancient Egypt\'s most distinctive contribution to civilization?', ['The first democracy', 'Monumental architecture (pyramids), hieroglyphic writing, agricultural mastery of the Nile, and a sophisticated religious and cultural system lasting 3,000 years', 'The first iron tools and weapons', 'The invention of the wheel'], 'Monumental architecture (pyramids), hieroglyphic writing, agricultural mastery of the Nile, and a sophisticated religious and cultural system lasting 3,000 years', 'Egypt\'s stability — protected by desert barriers and Nile floods — allowed extraordinary cultural continuity. The pyramids (built ~2600-2500 BCE) remain engineering marvels. Its art and religion influenced later civilizations.', 4),
    mc('What role did river valleys play in early civilization?', ['They were avoided due to flooding danger', 'They provided reliable water, fertile soil from annual flooding, transportation, and trade routes — enabling agricultural surplus and population growth', 'They only supported nomadic peoples', 'They were primarily defensive barriers against invaders'], 'They provided reliable water, fertile soil from annual flooding, transportation, and trade routes — enabling agricultural surplus and population growth', 'The great river civilizations — Mesopotamia (Tigris/Euphrates), Egypt (Nile), Indus (Indus), China (Yellow River) — all arose where rivers provided predictable floods, fertile silt, and transportation networks.', 5),
  ],
  'ancient-greece': [
    mc('What was democracy in ancient Athens?', ['A system where all people voted equally', 'A direct democracy where adult male citizens (excluding women, slaves, and foreigners) participated directly in governance', 'A representative system like modern democracy', 'A monarchy with an elected council'], 'A direct democracy where adult male citizens (excluding women, slaves, and foreigners) participated directly in governance', 'Athenian democracy (5th century BCE) was direct — citizens voted on laws and policies themselves. About 30,000-60,000 male citizens were eligible; women, enslaved people, and foreigners were excluded.', 1),
    mc('What was the significance of Greek philosophy?', ['It was primarily religious doctrine', 'Greek philosophers (Socrates, Plato, Aristotle) developed systematic methods of reasoning, ethics, and inquiry that laid foundations for Western thought', 'It was focused exclusively on mathematics', 'It was a political movement for democratic reform'], 'Greek philosophers (Socrates, Plato, Aristotle) developed systematic methods of reasoning, ethics, and inquiry that laid foundations for Western thought', 'Socrates\' questioning method, Plato\'s theory of forms and ideal government, Aristotle\'s logic and natural science — Greek philosophy shaped Western medicine, science, politics, and ethics for two millennia.', 2),
    mc('What were the Persian Wars and why did they matter?', ['A series of Greek conquests of Persia', 'Greek city-states\' defense against Persian invasion (490-479 BCE) — protecting Greek independence and democratic political culture', 'Trade conflicts between Greece and the Persian Empire', 'Wars over the Mediterranean trade routes'], 'Greek city-states\' defense against Persian invasion (490-479 BCE) — protecting Greek independence and democratic political culture', 'Marathon (490 BCE) and Thermopylae/Salamis (480 BCE) are the key battles. Greek victory allowed the flourishing of Athenian democracy and culture — shaping Western civilization.', 3),
    mc('What was the Peloponnesian War?', ['A war between Greece and Persia', 'A devastating conflict between Athens and Sparta (431-404 BCE) that weakened Greek city-states and ended Athenian dominance', 'A war that unified Greece under one government', 'A religious conflict between Greek city-states'], 'A devastating conflict between Athens and Sparta (431-404 BCE) that weakened Greek city-states and ended Athenian dominance', 'Athens and Sparta\'s 27-year war exhausted both sides. Sparta won but gained a ruined empire. The weakened city-states became vulnerable to Macedonian conquest under Philip II and Alexander.', 4),
    mc('What was Alexander the Great\'s legacy?', ['He preserved the isolation of Greek culture', 'He spread Greek (Hellenistic) culture across an empire from Greece to India, creating a fusion of Greek and Eastern cultures', 'He established a permanent Greek empire that lasted centuries', 'He conquered Rome and unified the Mediterranean'], 'He spread Greek (Hellenistic) culture across an empire from Greece to India, creating a fusion of Greek and Eastern cultures', 'Alexander conquered Persia, Egypt, and reached India by 323 BCE. The Hellenistic Age that followed blended Greek language and culture with Egyptian, Persian, and Indian traditions — creating a cosmopolitan world.', 5),
  ],
  'ancient-rome': [
    mc('What was the Roman Republic?', ['Rome before it had any democracy', 'The Roman government from 509-27 BCE — featuring elected consuls, a Senate, and checks on power before becoming an empire', 'A city-state ruled by kings', 'The name for Rome\'s colonial possessions'], 'The Roman government from 509-27 BCE — featuring elected consuls, a Senate, and checks on power before becoming an empire', 'The Republic\'s mixed constitution — consuls (executive), Senate (advisory/legislative), popular assemblies — influenced the US Founders. "SPQR" (Senate and People of Rome) embodied its dual sovereignty.', 1),
    mc('What caused the fall of the Roman Republic?', ['Foreign invasion by Germanic tribes', 'Internal power struggles, wealth inequality, breakdown of republican norms, and military commanders (Marius, Sulla, Caesar) using armies for personal power', 'Economic collapse from trade disruption', 'Plague wiping out the Roman elite'], 'Internal power struggles, wealth inequality, breakdown of republican norms, and military commanders (Marius, Sulla, Caesar) using armies for personal power', 'Century of civil wars (133-27 BCE): Gracchi reforms failed, Sulla marched on Rome, Caesar crossed the Rubicon. Augustus emerged from civil war as the first emperor, preserving republican forms while holding absolute power.', 2),
    mc('What was Pax Romana?', ['The Roman peace treaty with Persia', 'A roughly 200-year period (27 BCE-180 CE) of relative peace and stability across the Roman Empire at its height', 'Rome\'s policy toward conquered peoples', 'The name for Roman religious tolerance'], 'A roughly 200-year period (27 BCE-180 CE) of relative peace and stability across the Roman Empire at its height', 'The Pax Romana saw the Empire\'s greatest extent (~5 million km²), architectural achievements (Colosseum, aqueducts), trade networks, and legal development. Population reached ~70 million.', 3),
    mc('What were Rome\'s most lasting contributions to Western civilization?', ['Military tactics and gladiatorial combat', 'Roman law, Latin language (root of Romance languages), engineering (roads, aqueducts), and the spread of Christianity throughout the empire', 'Philosophy and democratic theory', 'Agricultural innovations'], 'Roman law, Latin language (root of Romance languages), engineering (roads, aqueducts), and the spread of Christianity throughout the empire', 'Roman law concepts (innocent until proven guilty, legal personhood) underlie Western legal systems. Latin evolved into French, Spanish, Italian, Portuguese, Romanian. Roman roads enabled trade and military control for centuries.', 4),
    mc('What caused Rome\'s decline and fall?', ['A single decisive military defeat', 'A combination of factors: political instability, economic problems, military pressure from Germanic peoples, and loss of civic identity — the Western Empire fell in 476 CE', 'The rise of Christianity weakening Rome militarily', 'Plague eliminating the entire population'], 'A combination of factors: political instability, economic problems, military pressure from Germanic peoples, and loss of civic identity — the Western Empire fell in 476 CE', 'Rome\'s "fall" was gradual. Causes debated: military overextension, currency debasement, political corruption, climate change, pandemic, and demographic pressure from migrating peoples all contributed.', 5),
  ],
  'ancient-asia': [
    mc('What was Confucianism\'s core teaching?', ['Achieving personal enlightenment through meditation', 'A system of ethics emphasizing social harmony through proper relationships, respect for hierarchy, education, and moral cultivation', 'Rejection of worldly concerns and focus on the afterlife', 'A monotheistic religion centered on one supreme deity'], 'A system of ethics emphasizing social harmony through proper relationships, respect for hierarchy, education, and moral cultivation', 'Confucius (551-479 BCE) taught that social order rested on proper relationships: ruler-subject, parent-child, husband-wife, elder-younger, friend-friend. Education and virtue were paths to good governance.', 1),
    mc('What was the Silk Road?', ['A road built of silk connecting Chinese cities', 'A network of trade routes connecting China, Central Asia, Persia, and the Mediterranean — carrying goods, ideas, and religions across Eurasia', 'A Chinese military strategy', 'The name for China\'s Great Wall trade zone'], 'A network of trade routes connecting China, Central Asia, Persia, and the Mediterranean — carrying goods, ideas, and religions across Eurasia', 'The Silk Road (active c. 130 BCE-1450 CE) carried silk, spices, porcelain, and paper westward; horses, glass, and gold eastward. Buddhism, Islam, and the plague also traveled these routes.', 2),
    mc('What was the significance of China\'s Great Wall?', ['It successfully prevented all northern invasions', 'A series of defensive walls built over centuries to protect Chinese states from northern nomadic peoples — a symbol of Chinese civilization\'s scale', 'A road network for internal trade', 'A religious monument'], 'A series of defensive walls built over centuries to protect Chinese states from northern nomadic peoples — a symbol of Chinese civilization\'s scale', 'The wall (multiple phases, largely built under the Ming Dynasty) stretched ~13,000 miles total. It required millions of forced laborers. It was partially effective but never a complete barrier.', 3),
    mc('What was the Maurya Empire in ancient India?', ['A small regional kingdom in southern India', 'The first empire to unify most of the Indian subcontinent, reaching its height under Emperor Ashoka who promoted Buddhism and ethical governance', 'A trading confederation in the Indus Valley', 'The empire that conquered Alexander the Great\'s forces'], 'The first empire to unify most of the Indian subcontinent, reaching its height under Emperor Ashoka who promoted Buddhism and ethical governance', 'Ashoka (304-232 BCE), after the bloody Kalinga War, converted to Buddhism and governed by dharma (ethical duty) — promoting religious tolerance, hospitals, and animal welfare across the empire.', 4),
    mc('What was Buddhism\'s core teaching?', ['God created the world and judges all people', 'The Four Noble Truths: suffering exists, it arises from craving, it can end, and the Eightfold Path leads to its end', 'All souls are reincarnated based on caste', 'Enlightenment comes through extreme asceticism only'], 'The Four Noble Truths: suffering exists, it arises from craving, it can end, and the Eightfold Path leads to its end', 'The Buddha (Siddhartha Gautama, c. 563-483 BCE) taught that suffering comes from attachment and desire. The Eightfold Path (right understanding, intention, speech, action, livelihood, effort, mindfulness, concentration) leads to nirvana.', 5),
  ],
  'fall-of-rome-and-middle-ages': [
    mc('What were the "Dark Ages" and is the term accurate?', ['A period of total civilizational collapse across all of Europe', 'A pejorative term for the early medieval period — while Roman urban civilization declined in the West, Byzantine civilization, Islamic scholars, and monasteries preserved learning', 'A period when Christianity was suppressed', 'The period between the fall of Rome and the Renaissance when nothing of note happened'], 'A pejorative term for the early medieval period — while Roman urban civilization declined in the West, Byzantine civilization, Islamic scholars, and monasteries preserved learning', 'The "Dark Ages" label is misleading. Byzantine Empire flourished; Islamic civilization was a golden age; Irish monasteries preserved classical texts; Charlemagne built an empire. The term reflects Western European perspective.', 1),
    mc('What was the Byzantine Empire?', ['A barbarian successor state to Rome', 'The continuation of the Eastern Roman Empire, centered in Constantinople, lasting nearly a thousand years after Rome\'s fall (until 1453)', 'A Greek colonial empire in the eastern Mediterranean', 'The name for the Holy Roman Empire'], 'The continuation of the Eastern Roman Empire, centered in Constantinople, lasting nearly a thousand years after Rome\'s fall (until 1453)', 'Constantinople (modern Istanbul) was founded by Emperor Constantine. Byzantium preserved Roman law (Justinian\'s Code), Greek learning, and Orthodox Christianity — falling to the Ottomans in 1453.', 2),
    mc('What was Charlemagne\'s significance?', ['He reunited the Eastern and Western Roman Empires', 'He unified much of Western Europe under Frankish rule, was crowned Holy Roman Emperor in 800 CE, and promoted learning and the Church', 'He conquered the Byzantine Empire', 'He led the First Crusade'], 'He unified much of Western Europe under Frankish rule, was crowned Holy Roman Emperor in 800 CE, and promoted learning and the Church', 'Charlemagne (742-814 CE) built the largest Western European empire since Rome, established schools and standardized writing, and created a model of Christian kingship that influenced medieval Europe.', 3),
    mc('What was feudalism?', ['A democratic system of local governance in medieval Europe', 'A hierarchical social-political system where lords granted land (fiefs) to vassals in exchange for military service and loyalty', 'A church-based system of government', 'An economic system based on trade rather than agriculture'], 'A hierarchical social-political system where lords granted land (fiefs) to vassals in exchange for military service and loyalty', 'Feudalism organized medieval European society: king → lords/nobles → knights → serfs. Land for service. Security in exchange for obligation. It fragmented political power across local lords.', 4),
    mc('What was the Black Death and its impact?', ['A war that killed millions across Europe', 'A bubonic plague pandemic (1347-1353) killing 30-60% of Europe\'s population — transforming society, labor relations, and undermining faith in the Church', 'A famine caused by crop failures across Europe', 'A smallpox epidemic that preceded the Renaissance'], 'A bubonic plague pandemic (1347-1353) killing 30-60% of Europe\'s population — transforming society, labor relations, and undermining faith in the Church', 'The Black Death killed 25-50 million Europeans. Labor scarcity empowered surviving peasants. Church\'s failure to explain or stop the plague eroded its authority. Social upheaval helped set the stage for the Renaissance.', 5),
  ],
}
