import type { ExerciseDef } from '../types'

function mc(
  question: string,
  options: string[],
  correctAnswer: string,
  explanation: string,
  order: number
): ExerciseDef {
  return { question, type: 'MULTIPLE_CHOICE', options, correctAnswer, explanation, order }
}

export const historyExercises1: Record<string, ExerciseDef[]> = {
  'three-branches': [
    mc('What are the three branches of the US federal government?', ['President, Congress, Courts', 'Legislative, Executive, Judicial', 'Senate, House, Supreme Court', 'Federal, State, Local'], 'Legislative, Executive, Judicial', 'The Constitution divides federal power into three branches: Legislative (Congress makes laws), Executive (President enforces laws), Judicial (Courts interpret laws).', 1),
    mc('Which branch of government makes federal laws?', ['The President', 'The Supreme Court', 'Congress (Senate + House of Representatives)', 'The Cabinet'], 'Congress (Senate + House of Representatives)', 'Article I of the Constitution grants all legislative power to Congress. A bill must pass both the Senate and House before the President can sign it into law.', 2),
    mc('How many US Senators does each state have?', ['Based on population', 'Two Senators per state, regardless of population', 'One Senator per state', 'Varies by state constitution'], 'Two Senators per state, regardless of population', 'The Senate has 100 members — 2 per state. This equal representation was the "Great Compromise" that balanced large-state and small-state interests at the Constitutional Convention.', 3),
    mc('What is the term length for a US House Representative?', ['6 years', '4 years', '2 years', 'Life tenure'], '2 years', 'House members serve 2-year terms — the shortest of any federal office. This makes them highly accountable to voters and requires frequent campaigning.', 4),
    mc('What is the primary role of the judicial branch?', ['Creating laws', 'Enforcing laws and managing the military', 'Interpreting laws and determining their constitutionality', 'Collecting taxes and managing the budget'], 'Interpreting laws and determining their constitutionality', 'Federal courts, headed by the Supreme Court, interpret what laws mean and whether they comply with the Constitution. This power of judicial review protects constitutional rights.', 5),
  ],
  'the-constitution': [
    mc('What is the US Constitution?', ['A declaration of independence from Britain', 'The supreme law of the land — the foundational framework of US government', 'A list of citizens\' rights only', 'A treaty between the states'], 'The supreme law of the land — the foundational framework of US government', 'The Constitution (1787, ratified 1788) establishes the structure of government, its powers, and its limits. All other laws must conform to it. The Supreme Court enforces this supremacy.', 1),
    mc('What are the first ten amendments to the Constitution called?', ['The Articles of Confederation', 'The Bill of Rights', 'The Federalist Papers', 'The Declaration of Rights'], 'The Bill of Rights', 'The Bill of Rights (ratified 1791) protects individual liberties: speech, religion, press, assembly, due process, right against unreasonable search, right to trial, and more.', 2),
    mc('What does the First Amendment protect?', ['The right to bear arms', 'Freedom of speech, religion, press, assembly, and petition', 'Protection from unreasonable searches', 'The right to a fair trial'], 'Freedom of speech, religion, press, assembly, and petition', 'The First Amendment prevents government from restricting speech, establishing a religion, abridging press freedom, or limiting peaceful assembly and petitioning government.', 3),
    mc('How is the Constitution amended?', ['The President signs an executive order', 'Congress proposes (2/3 of both chambers) and 3/4 of states ratify', 'The Supreme Court can amend it through rulings', 'A simple majority vote in Congress'], 'Congress proposes (2/3 of both chambers) and 3/4 of states ratify', 'The amendment process is deliberately difficult — it requires broad supermajority support. Only 27 amendments have been ratified in over 230 years.', 4),
    mc('What is the Supremacy Clause?', ['The President\'s power to override Congress', 'The clause establishing that the Constitution and federal law are the supreme law of the land, overriding state law', 'The Supreme Court\'s power of judicial review', 'The rule that the Senate confirms federal appointments'], 'The clause establishing that the Constitution and federal law are the supreme law of the land, overriding state law', 'Article VI\'s Supremacy Clause means states cannot pass laws that contradict federal law or the Constitution. Federal law wins conflicts.', 5),
  ],
  'federalism': [
    mc('What is federalism?', ['A system where the national government has all power', 'A system dividing governmental power between a national government and state governments', 'A system where states have all power', 'A form of direct democracy'], 'A system dividing governmental power between a national government and state governments', 'US federalism creates dual sovereignty — the national and state governments each have their own spheres of authority, protecting against concentration of power.', 1),
    mc('What are "enumerated powers"?', ['Powers reserved for the states', 'Powers specifically listed in the Constitution as belonging to the federal government', 'Powers shared by federal and state governments', 'Powers belonging to the President alone'], 'Powers specifically listed in the Constitution as belonging to the federal government', 'Article I, Section 8 lists federal enumerated powers: coin money, regulate commerce, declare war, raise armies, etc. Powers not listed are reserved to states or the people (10th Amendment).', 2),
    mc('What does the 10th Amendment say?', ['Citizens have free speech', 'Powers not delegated to the federal government are reserved to the states or the people', 'States cannot abridge federal rights', 'The federal government has unlimited power over states'], 'Powers not delegated to the federal government are reserved to the states or the people', 'The 10th Amendment is the foundation of states\' rights — if the Constitution doesn\'t give a power to the federal government, that power belongs to states or citizens.', 3),
    mc('What are concurrent powers?', ['Powers held only by the federal government', 'Powers shared by both federal and state governments (like taxing and law enforcement)', 'Powers reserved exclusively to states', 'Powers belonging to local governments'], 'Powers shared by both federal and state governments (like taxing and law enforcement)', 'Both levels of government can tax, borrow money, establish courts, and make and enforce laws. These shared powers are concurrent.', 4),
    mc('What is an advantage of federalism?', ['It makes national policy uniform everywhere', 'States can serve as "laboratories of democracy" — experimenting with policies before national adoption', 'It eliminates conflict between levels of government', 'It allows the President to govern states directly'], 'States can serve as "laboratories of democracy" — experimenting with policies before national adoption', 'Justice Brandeis coined this phrase. Massachusetts\' health care reform became the model for the ACA. State marijuana legalization preceded federal debate.', 5),
  ],
  'checks-and-balances': [
    mc('What is the purpose of checks and balances?', ['To slow government down so nothing gets done', 'To prevent any one branch from accumulating too much power by giving each branch ways to limit the others', 'To ensure the President controls Congress', 'To allow courts to make laws'], 'To prevent any one branch from accumulating too much power by giving each branch ways to limit the others', 'The Founders feared tyranny — checks and balances ensure no branch can dominate. Power is shared and contested, requiring cooperation to govern.', 1),
    mc('What is a presidential veto?', ['The President\'s power to fire members of Congress', 'The President\'s power to reject legislation passed by Congress', 'The Supreme Court striking down a law', 'Congress overriding a presidential action'], 'The President\'s power to reject legislation passed by Congress', 'If the President vetoes a bill, it returns to Congress. Congress can override the veto with a 2/3 majority in both chambers — a high bar that preserves significant executive power.', 2),
    mc('What is judicial review?', ['Congress reviewing court decisions', 'The power of federal courts to declare laws unconstitutional', 'The President reviewing Supreme Court nominees', 'Citizens reviewing government actions'], 'The power of federal courts to declare laws unconstitutional', 'Established in Marbury v. Madison (1803), judicial review gives courts the power to strike down acts of Congress or the President that violate the Constitution.', 3),
    mc('How does the Senate check the Executive Branch?', ['By vetoing presidential orders', 'Through the power to confirm presidential appointments and ratify treaties (with 2/3 majority)', 'By impeaching the President directly', 'Through the power of the purse'], 'Through the power to confirm presidential appointments and ratify treaties (with 2/3 majority)', 'The Senate confirms Cabinet members, federal judges (including Supreme Court justices), and ambassadors. It must ratify international treaties with a 2/3 supermajority.', 4),
    mc('What is impeachment?', ['Removing a president by popular vote', 'The process by which Congress can charge (House) and try (Senate) federal officials for high crimes and misdemeanors', 'The Supreme Court removing a president', 'A recall election for federal officials'], 'The process by which Congress can charge (House) and try (Senate) federal officials for high crimes and misdemeanors', 'The House impeaches (simple majority charge). The Senate holds a trial (2/3 needed to remove). Three presidents have been impeached (Johnson, Clinton, Trump twice); none removed.', 5),
  ],
  'congress-and-legislation': [
    mc('How does a bill become a law?', ['The President proposes it and Congress votes', 'A bill is introduced, passes committee, passes both chambers, and is signed by the President (or veto is overridden)', 'The Supreme Court approves proposed laws', 'States propose laws and Congress ratifies them'], 'A bill is introduced, passes committee, passes both chambers, and is signed by the President (or veto is overridden)', 'The legislative process: introduction → committee review → floor debate/vote → other chamber → conference committee (if different versions) → President signs or vetoes.', 1),
    mc('What is a filibuster?', ['A procedural vote to end debate', 'A Senate tactic where members extend debate indefinitely to delay or block a vote', 'A House rule limiting debate time', 'A Presidential veto of a spending bill'], 'A Senate tactic where members extend debate indefinitely to delay or block a vote', 'The Senate filibuster allows the minority to block legislation by prolonging debate. Ending a filibuster (cloture) requires 60 votes — giving the minority significant blocking power.', 2),
    mc('What is the "power of the purse"?', ['The President\'s ability to impose tariffs', 'Congress\'s constitutional authority to appropriate all federal spending and raise revenue through taxation', 'The Treasury\'s ability to print money', 'The Fed\'s control over interest rates'], 'Congress\'s constitutional authority to appropriate all federal spending and raise revenue through taxation', 'No money can be spent without Congressional appropriation. This gives Congress significant leverage over the Executive Branch\'s ability to carry out its agenda.', 3),
    mc('How many members are in the House of Representatives?', ['100', '435', '538', '535'], '435', 'The House has 435 voting members. Seats are apportioned by state population (reapportioned every 10 years after the census). California has the most; Wyoming the fewest.', 4),
    mc('What is a conference committee?', ['A meeting between the President and Congressional leaders', 'A joint committee that reconciles different versions of a bill passed by the House and Senate', 'A committee that handles classified legislation', 'A committee of all senators and representatives that votes on final bills'], 'A joint committee that reconciles different versions of a bill passed by the House and Senate', 'When the House and Senate pass different versions of the same bill, a conference committee of members from both chambers negotiates a single compromise version.', 5),
  ],
  'the-courts': [
    mc('What is the structure of the federal court system?', ['One Supreme Court only', 'District courts → Circuit courts of appeals → Supreme Court', 'State courts → Federal courts → Supreme Court', 'Trial courts → Federal courts → Congress'], 'District courts → Circuit courts of appeals → Supreme Court', 'The three-tier federal system: 94 district courts (trials), 13 circuit courts (appeals), Supreme Court (final). State court systems are separate but can be reviewed by SCOTUS on federal/constitutional questions.', 1),
    mc('How many justices are on the Supreme Court?', ['7', '12', '9', '15'], '9', 'The Supreme Court has 9 justices (1 Chief Justice + 8 Associates). The Constitution doesn\'t specify the number — Congress sets it by statute. It has been 9 since 1869.', 2),
    mc('What is the significance of Marbury v. Madison (1803)?', ['It established the two-party system', 'It established judicial review — the Supreme Court\'s power to strike down unconstitutional laws', 'It abolished slavery in the North', 'It created the Electoral College'], 'It established judicial review — the Supreme Court\'s power to strike down unconstitutional laws', 'Chief Justice Marshall\'s ruling established that the Supreme Court has the authority to invalidate laws that violate the Constitution — the foundation of the modern judiciary\'s power.', 3),
    mc('What does it mean for a court to have "jurisdiction"?', ['The power to enforce its rulings', 'The legal authority to hear and decide a particular case', 'The right to create new laws', 'The ability to review Congressional decisions'], 'The legal authority to hear and decide a particular case', 'Jurisdiction limits which courts can hear which cases. Federal courts have jurisdiction over constitutional questions, federal law, disputes between states. State courts handle most criminal and civil matters.', 4),
    mc('What is stare decisis?', ['A Supreme Court term for unanimous decisions', 'The legal principle of respecting precedent — courts should follow prior decisions on similar issues', 'The right to appeal any decision', 'A rule requiring written opinions for all decisions'], 'The legal principle of respecting precedent — courts should follow prior decisions on similar issues', 'Stare decisis (Latin: "to stand by decided matters") provides stability and predictability in law. Courts can overturn precedent (Roe v. Wade → Dobbs) but face a high bar.', 5),
  ],
  'voting-and-elections': [
    mc('What is the Electoral College?', ['A school that trains future politicians', 'The system by which the President is elected — each state has electors (= senators + representatives) who formally elect the President', 'A direct popular vote for the President', 'The committee that certifies election results'], 'The system by which the President is elected — each state has electors (= senators + representatives) who formally elect the President', 'Each state has electors = its congressional delegation (senators + representatives). 270 electoral votes needed to win. Most states are winner-take-all. A candidate can win Electoral College but lose popular vote.', 1),
    mc('What amendment gave 18-year-olds the right to vote?', ['15th Amendment', '19th Amendment', '26th Amendment', '24th Amendment'], '26th Amendment', 'The 26th Amendment (1971) lowered the voting age from 21 to 18 — largely in response to the argument that those old enough to be drafted and die in Vietnam should be able to vote.', 2),
    mc('What is a primary election?', ['The final election between Democratic and Republican candidates', 'An election within a party to select its candidate for the general election', 'A preliminary vote on ballot measures only', 'The first round of voting in the Electoral College'], 'An election within a party to select its candidate for the general election', 'Primary elections (or caucuses) determine who represents a party in the general election. They can be open (anyone votes), closed (only registered party members), or semi-open.', 3),
    mc('What is voter turnout?', ['The number of polling places in an election', 'The percentage of eligible voters who actually cast a ballot in an election', 'The speed at which votes are counted', 'The number of candidates on a ballot'], 'The percentage of eligible voters who actually cast a ballot in an election', 'US turnout is relatively low vs other democracies — roughly 55-65% in presidential elections, lower in midterms. Registration requirements, polling hours, and voter ID laws affect turnout.', 4),
    mc('What is gerrymandering?', ['Fraud committed during elections', 'Drawing electoral district boundaries to advantage a particular party or group', 'A system of proportional representation', 'The practice of campaigning in battleground states'], 'Drawing electoral district boundaries to advantage a particular party or group', 'State legislatures draw congressional district maps. Partisan gerrymandering packs opposition voters into a few districts and spreads majority voters across many — maximizing seats won per vote.', 5),
  ],
}
