import type { ExerciseDef } from '../types'

function mc(
  question: string,
  options: string[],
  correctAnswer: string,
  explanation: string,
  order: number
): ExerciseDef {
  return { question, type: 'MULTIPLE_CHOICE', options, correctAnswer, explanation, order }
}

export const historyExercises5: Record<string, ExerciseDef[]> = {
  'islam-and-the-caliphates': [
    mc('What are the Five Pillars of Islam?', ['Prayer, fasting, charity, pilgrimage, and jihad', 'Shahada (declaration of faith), Salat (prayer), Zakat (charity), Sawm (fasting), Hajj (pilgrimage)', 'Faith, hope, charity, prayer, and pilgrimage', 'Belief, prayer, fasting, almsgiving, and scripture'], 'Shahada (declaration of faith), Salat (prayer), Zakat (charity), Sawm (fasting), Hajj (pilgrimage)', 'The Five Pillars are the core practices of Islam: testifying that God is one and Muhammad is His prophet, praying five times daily, giving to the poor, fasting during Ramadan, and making pilgrimage to Mecca.', 1),
    mc('What was the Golden Age of Islam?', ['The period of early Islamic military expansion', 'A period (c. 8th-13th centuries) of remarkable intellectual achievement in mathematics, science, medicine, and philosophy centered in Baghdad and other cities', 'The founding of Islam by Muhammad', 'The period when Islam spread to Europe'], 'A period (c. 8th-13th centuries) of remarkable intellectual achievement in mathematics, science, medicine, and philosophy centered in Baghdad and other cities', 'Islamic scholars preserved and advanced Greek knowledge, invented algebra (al-Khwarizmi), developed optics (Ibn al-Haytham), advanced medicine (Avicenna), and translated ancient texts that later sparked the European Renaissance.', 2),
    mc('What was the caliphate?', ['A system of Islamic law', 'The political-religious leadership of the Muslim community following Muhammad\'s death — various dynasties (Umayyad, Abbasid) ruled vast empires', 'A type of Islamic mosque', 'A democratic council in early Islamic society'], 'The political-religious leadership of the Muslim community following Muhammad\'s death — various dynasties (Umayyad, Abbasid) ruled vast empires', 'The caliph (khalifa = successor) led the Muslim community. The Rashidun, Umayyad, and Abbasid caliphates successively ruled; the Abbasid Caliphate in Baghdad was the height of Islamic civilization.', 3),
    mc('How did Islam spread so rapidly after Muhammad\'s death?', ['Exclusively through military conquest', 'A combination of military expansion, trade networks, the appeal of its egalitarian message, and adoption by local rulers', 'Through forced conversion only', 'Primarily through missionaries sent to foreign lands'], 'A combination of military expansion, trade networks, the appeal of its egalitarian message, and adoption by local rulers', 'Early Islamic expansion was military but also ideological — Islam\'s message of equality before God appealed to those under Byzantine and Persian rule. Trade carried Islam to Southeast Asia, Africa, and Central Asia without armies.', 4),
    mc('What was the significance of the Battle of Tours/Poitiers (732 CE)?', ['Muslims conquered France and Spain', 'Frankish forces under Charles Martel halted Islamic expansion into Western Europe, marking the furthest extent of Muslim advance from the west', 'The Byzantine Empire defeated an Islamic invasion', 'Muslims and Christians agreed to share control of Spain'], 'Frankish forces under Charles Martel halted Islamic expansion into Western Europe, marking the furthest extent of Muslim advance from the west', 'Charles Martel\'s victory at Tours halted the Umayyad advance from Spain into France. Historians debate whether a Muslim victory would have changed European history, but the battle became a symbol of Christian resistance.', 5),
  ],
  'feudalism-and-crusades': [
    mc('What was a serf in medieval feudal society?', ['A free farmer who paid taxes', 'A peasant bound to the land — unable to leave without the lord\'s permission, obligated to work the lord\'s fields', 'A skilled craftsman in a medieval city', 'A knight of the lowest rank'], 'A peasant bound to the land — unable to leave without the lord\'s permission, obligated to work the lord\'s fields', 'Serfs were not slaves but were not free — tied to land that belonged to lords. They owed labor service and dues; in return received protection. The Black Death eventually empowered surviving serfs to demand better terms.', 1),
    mc('What was the role of the Catholic Church in medieval Europe?', ['Primarily a spiritual organization with no political power', 'The dominant institution of medieval life — providing education, charity, and moral authority while popes claimed authority over kings', 'A political institution with no religious function', 'A local institution with no influence beyond individual parishes'], 'The dominant institution of medieval life — providing education, charity, and moral authority while popes claimed authority over kings', 'The medieval Church controlled education (monasteries and universities), record-keeping, and social welfare. Popes clashed with kings over investiture (appointing bishops). Excommunication could delegitimize rulers.', 2),
    mc('What were the Crusades?', ['Islamic military campaigns into Europe', 'A series of military campaigns (1095-1291) initiated by the papacy to capture the Holy Land from Muslim control', 'Trade expeditions to the Middle East', 'Missionary efforts to convert northern Europeans to Christianity'], 'A series of military campaigns (1095-1291) initiated by the papacy to capture the Holy Land from Muslim control', 'Pope Urban II called the First Crusade in 1095. Eight major Crusades followed. The First took Jerusalem (1099); Saladin retook it (1187). The Crusades failed ultimately but transformed European-Islamic interaction.', 3),
    mc('What were the long-term effects of the Crusades?', ['They permanently established Christian control of Jerusalem', 'They increased trade and cultural exchange between Europe and the Islamic world, but also left a legacy of religious violence and mistrust', 'They had no lasting impact on either civilization', 'They unified Christian Europe under one ruler'], 'They increased trade and cultural exchange between Europe and the Islamic world, but also left a legacy of religious violence and mistrust', 'The Crusades facilitated exchange of goods, ideas (Arabic numerals, medicine, philosophy), and technologies. They also produced massacres of Jews and Muslims and planted seeds of religious hostility.', 4),
    mc('What was Magna Carta (1215)?', ['A medieval religious document', 'A charter signed by King John of England limiting royal power and establishing that even kings must obey the law — a foundation of constitutional government', 'The first democratic constitution in Europe', 'A peace treaty between England and France'], 'A charter signed by King John of England limiting royal power and establishing that even kings must obey the law — a foundation of constitutional government', 'Magna Carta established key principles: the king cannot imprison subjects without cause (habeas corpus), taxes require consent of the governed, and law constrains rulers. It influenced English common law and the US Constitution.', 5),
  ],
  'mongol-empire': [
    mc('How large was the Mongol Empire at its peak?', ['Roughly the size of Western Europe', 'The largest contiguous land empire in history — spanning from China to Eastern Europe and covering ~24 million km²', 'About the size of modern Russia', 'Primarily limited to Central Asia and China'], 'The largest contiguous land empire in history — spanning from China to Eastern Europe and covering ~24 million km²', 'Under Genghis Khan and his successors (c. 1206-1368), the Mongols conquered China, Persia, Russia, and reached Poland and Hungary — connecting Eurasia in an unprecedented way.', 1),
    mc('What was the Pax Mongolica?', ['A peace treaty ending Mongol conquests', 'A period of relative stability across the Mongol Empire enabling unprecedented trade, communication, and cultural exchange along the Silk Road', 'Mongol religious tolerance policies', 'The name for Genghis Khan\'s legal code'], 'A period of relative stability across the Mongol Empire enabling unprecedented trade, communication, and cultural exchange along the Silk Road', 'The Pax Mongolica (c. 1260-1350) allowed merchants, diplomats, and travelers (Marco Polo) to cross Eurasia safely. It also, unfortunately, provided highways for the Black Death.', 2),
    mc('What was the Mongol Empire\'s impact on civilizations it conquered?', ['It preserved all existing institutions', 'It was enormously destructive (millions killed, cities destroyed) but also connected Eurasia, spreading technologies and enabling cultural exchange', 'It created democratic governments in conquered lands', 'It spread Islam as the official religion everywhere'], 'It was enormously destructive (millions killed, cities destroyed) but also connected Eurasia, spreading technologies and enabling cultural exchange', 'The Mongols destroyed Baghdad (1258), ending the Abbasid Caliphate and killing hundreds of thousands. Yet Mongol rule also spread Chinese gunpowder, paper money, and printing; Mongol rulers often adopted local cultures.', 3),
    mc('How did the Mongol Empire ultimately decline?', ['Defeated by a unified European alliance', 'Through a combination of political fragmentation into rival khanates, inability to administer vast territories, the Black Death, and resistance from local populations', 'Conquered by China from the east', 'Through conversion to Christianity and peaceful dissolution'], 'Through a combination of political fragmentation into rival khanates, inability to administer vast territories, the Black Death, and resistance from local populations', 'After Kublai Khan, the empire fragmented into four khanates that often warred with each other. The Yuan Dynasty in China was overthrown in 1368; other khanates dissolved over the following century.', 4),
    mc('What was the significance of the Silk Road under Mongol control?', ['It declined as Mongols restricted trade', 'Mongol control of Central Asia made the entire Silk Road network safe, enabling direct European-Asian trade and the exchange of ideas, goods, and diseases', 'It became exclusively a military supply route', 'It shifted to sea routes, making the Silk Road irrelevant'], 'Mongol control of Central Asia made the entire Silk Road network safe, enabling direct European-Asian trade and the exchange of ideas, goods, and diseases', 'Marco Polo\'s journey to China (1271-1295) was enabled by Mongol peace. This era of Eurasian connection directly inspired the European Age of Exploration — seeking those Asian goods by sea.', 5),
  ],
  'renaissance-and-reformation': [
    mc('What was the Renaissance?', ['A political revolution establishing republics across Europe', 'A cultural and intellectual movement (14th-17th centuries) reviving classical Greek and Roman learning, emphasizing humanism and human potential', 'A religious reform movement within the Catholic Church', 'A period of scientific discovery unrelated to classical learning'], 'A cultural and intellectual movement (14th-17th centuries) reviving classical Greek and Roman learning, emphasizing humanism and human potential', 'Beginning in Italian city-states, the Renaissance celebrated human achievement, reason, and beauty — producing Leonardo da Vinci, Michelangelo, Machiavelli, and transforming art, literature, and philosophy.', 1),
    mc('What was humanism in the Renaissance context?', ['A rejection of religion', 'An intellectual movement emphasizing human dignity, individual potential, classical education, and the value of life on Earth — not only preparation for the afterlife', 'A philosophical school believing humans are naturally evil', 'A political movement for democratic government'], 'An intellectual movement emphasizing human dignity, individual potential, classical education, and the value of life on Earth — not only preparation for the afterlife', 'Renaissance humanism shifted focus from divine authority to human capacity. It valued classical texts, rhetoric, history, and moral philosophy — producing educated, well-rounded citizens rather than only religious scholars.', 2),
    mc('What did the Gutenberg printing press (c. 1440) change?', ['Only religious texts could be printed', 'It dramatically lowered the cost of books, enabling mass literacy, the spread of ideas, and directly enabling the Protestant Reformation', 'It had minimal impact — handwritten books remained dominant', 'It allowed only governments to control printed information'], 'It dramatically lowered the cost of books, enabling mass literacy, the spread of ideas, and directly enabling the Protestant Reformation', 'Before printing: a Bible cost years of a craftsman\'s salary. After: ideas spread rapidly and cheaply. Luther\'s 95 Theses spread across Germany in weeks. The printing press transformed politics, religion, and science.', 3),
    mc('What did Martin Luther\'s 95 Theses (1517) argue?', ['The Pope should be replaced by an elected council', 'That the Catholic Church\'s sale of indulgences (forgiveness) was corrupt and contrary to scripture — salvation comes through faith alone, not works or payments', 'That the Bible should be read only in Latin', 'That Christians should reject all church authority'], 'That the Catholic Church\'s sale of indulgences (forgiveness) was corrupt and contrary to scripture — salvation comes through faith alone, not works or payments', 'Luther challenged papal authority, condemned indulgences, and argued for "sola scriptura" (scripture alone) and "sola fide" (faith alone). The printing press spread his ideas rapidly, making his break from Rome irreversible.', 4),
    mc('What were the major consequences of the Protestant Reformation?', ['The Catholic Church peacefully reformed itself', 'The permanent split of Western Christianity, decades of religious wars, and the stimulation of literacy (reading the Bible) and political thought about religious freedom', 'The reformation had no lasting political effects', 'All of Europe became Protestant within a generation'], 'The permanent split of Western Christianity, decades of religious wars, and the stimulation of literacy (reading the Bible) and political thought about religious freedom', 'The Reformation created Lutheranism, Calvinism, Anglicanism, and dozens of other denominations. The Wars of Religion (French, Thirty Years\' War) killed millions. Religious pluralism eventually forced political tolerance.', 5),
  ],
  'age-of-exploration': [
    mc('What motivated European exploration in the 15th-16th centuries?', ['Pure scientific curiosity', 'A desire for direct trade routes to Asia (bypassing Islamic middlemen), wealth, national prestige, and spreading Christianity', 'Escaping religious persecution in Europe', 'A search for uninhabited land for settlement'], 'A desire for direct trade routes to Asia (bypassing Islamic middlemen), wealth, national prestige, and spreading Christianity', 'The Ottoman Empire\'s control of eastern trade routes made Asian spices expensive. Europeans sought sea routes. "God, Gold, and Glory" — religion, wealth, and national competition — drove exploration.', 1),
    mc('What was Columbus\'s actual achievement in 1492?', ['He proved the Earth was round', 'He established the first sustained contact between Europe and the Americas, beginning an era of colonization and exchange that transformed both worlds', 'He found a sea route to India', 'He discovered that the Atlantic Ocean could be crossed safely'], 'He established the first sustained contact between Europe and the Americas, beginning an era of colonization and exchange that transformed both worlds', 'Columbus didn\'t "discover" America (Indigenous people had lived there for 20,000+ years) or prove Earth was round (educated Europeans already knew). His voyages initiated the Columbian Exchange and European colonization.', 2),
    mc('What was the transatlantic slave trade?', ['A trade system moving African goods to the Americas', 'The forced transportation of approximately 12.5 million Africans to the Americas as enslaved laborers from the 16th to 19th centuries', 'The movement of European indentured servants to colonies', 'Trade of enslaved people within Africa only'], 'The forced transportation of approximately 12.5 million Africans to the Americas as enslaved laborers from the 16th to 19th centuries', 'The transatlantic slave trade was the largest forced migration in history. About 12.5 million Africans were transported; roughly 2 million died during the Middle Passage. It built colonial economies and shaped the modern world.', 3),
    mc('What was the encomienda system?', ['A Spanish land measurement system', 'A Spanish colonial labor system granting colonizers the right to demand labor and tribute from Indigenous peoples', 'A land ownership system for Spanish settlers', 'A tax system imposed on Spanish colonies'], 'A Spanish colonial labor system granting colonizers the right to demand labor and tribute from Indigenous peoples', 'Encomienda gave Spanish colonizers authority over Indigenous peoples in exchange for Christianizing them. In practice it was brutal forced labor. Bartolomé de las Casas documented and opposed its abuses.', 4),
    mc('What was the significance of Magellan\'s circumnavigation (1519-1522)?', ['It proved that sailing west eventually reaches Asia', 'The first expedition to sail around the entire world, proving Earth\'s spherical shape practically and revealing the Pacific Ocean\'s vast scale', 'It established the first colony in the Pacific', 'It mapped the coastline of South America for the first time'], 'The first expedition to sail around the entire world, proving Earth\'s spherical shape practically and revealing the Pacific Ocean\'s vast scale', 'Magellan was killed in the Philippines; Elcano completed the voyage with 18 survivors from 270. The circumnavigation revealed how large the Pacific was — far larger than any map had shown.', 5),
  ],
  'scientific-revolution': [
    mc('What was the Scientific Revolution?', ['A political movement replacing religious leaders with scientists', 'A fundamental transformation in how Europeans understood nature (16th-17th centuries) — replacing ancient authority with observation, experiment, and mathematical reasoning', 'A period when all scientific theories were disproven', 'A religious reform movement based on scientific evidence'], 'A fundamental transformation in how Europeans understood nature (16th-17th centuries) — replacing ancient authority with observation, experiment, and mathematical reasoning', 'The Scientific Revolution (Copernicus through Newton) replaced Aristotelian natural philosophy with empirical science — changing how humans understand their place in the universe and establishing the scientific method.', 1),
    mc('What was the Copernican Revolution?', ['Copernicus\'s discovery that Earth rotates on its axis', 'Copernicus\'s heliocentric model placing the Sun at the center of the solar system — challenging the Earth-centered model that the Church endorsed', 'A political revolution inspired by astronomy', 'The invention of the telescope'], 'Copernicus\'s heliocentric model placing the Sun at the center of the solar system — challenging the Earth-centered model that the Church endorsed', 'Copernicus\'s De Revolutionibus (1543) proposed heliocentrism. Galileo confirmed it telescopically; the Church forced his recantation. Newton\'s gravity explained why it worked — completing the revolution.', 2),
    mc('What was the Enlightenment?', ['A scientific movement focused on astronomy', 'An 18th-century intellectual movement applying reason, empiricism, and skepticism to all areas of human life — politics, religion, economics, and society', 'A religious revival movement in Europe', 'A movement promoting classical Greek and Roman values'], 'An 18th-century intellectual movement applying reason, empiricism, and skepticism to all areas of human life — politics, religion, economics, and society', 'Enlightenment thinkers (Locke, Voltaire, Rousseau, Montesquieu) questioned tradition and authority, championed reason and human rights, and directly inspired the American and French Revolutions.', 3),
    mc('What is the scientific method?', ['A set of ancient Greek philosophical techniques', 'A systematic process: observe, hypothesize, predict, test experimentally, analyze results, and refine — building knowledge through reproducible evidence', 'The opinions of credentialed experts', 'A mathematical approach to solving problems'], 'A systematic process: observe, hypothesize, predict, test experimentally, analyze results, and refine — building knowledge through reproducible evidence', 'Francis Bacon and René Descartes articulated empirical and rational methods. The scientific method replaced authority with evidence — any claim must be testable and reproducible.', 4),
    mc('What was the significance of Newton\'s Principia Mathematica (1687)?', ['It proved heliocentrism for the first time', 'It provided the mathematical laws of motion and universal gravitation — unifying terrestrial and celestial mechanics under one framework', 'It established calculus as a branch of mathematics', 'It refuted all previous scientific theories'], 'It provided the mathematical laws of motion and universal gravitation — unifying terrestrial and celestial mechanics under one framework', 'Newton\'s three laws of motion and law of universal gravitation explained why the Moon orbits Earth and why apples fall — the same force. It gave science a predictive mathematical framework that lasted until Einstein.', 5),
  ],
  'atlantic-revolutions': [
    mc('What was the primary philosophical basis for the American and French Revolutions?', ['Mercantilism and trade theory', 'Enlightenment ideas about natural rights, popular sovereignty, and social contract theory', 'Religious texts supporting democratic rule', 'Ancient Roman republican models exclusively'], 'Enlightenment ideas about natural rights, popular sovereignty, and social contract theory', 'Locke\'s natural rights (life, liberty, property), Rousseau\'s social contract, and Montesquieu\'s separation of powers directly shaped Jefferson\'s Declaration and the French Declaration of the Rights of Man.', 1),
    mc('What was the Haitian Revolution (1791-1804)?', ['A French colonial revolt against Spanish rule', 'The only successful large-scale slave revolt in history — enslaved people of Saint-Domingue overthrew French colonial rule and established Haiti as the first Black republic', 'A revolution led by free Black colonists against white planters only', 'A French military campaign against British Caribbean colonies'], 'The only successful large-scale slave revolt in history — enslaved people of Saint-Domingue overthrew French colonial rule and established Haiti as the first Black republic', 'Toussaint Louverture and Jean-Jacques Dessalines led the revolution. Haiti\'s independence (1804) terrified slaveholders across the Americas and proved enslaved people could win freedom by force.', 2),
    mc('What were the key differences between the American and French Revolutions?', ['Both were equally radical and violent', 'The American Revolution was more moderate, preserving existing social structures; the French Revolution was far more radical, executing the king and aristocracy and going through terror', 'The French Revolution was peaceful; the American involved significant violence', 'They were identical in ideology and outcome'], 'The American Revolution was more moderate, preserving existing social structures; the French Revolution was far more radical, executing the king and aristocracy and going through terror', 'The American Revolution largely preserved property rights and social hierarchy. The French Revolution went through radical phases: the Terror (40,000 executions), Napoleon\'s rise, and repeated regime changes.', 3),
    mc('What was the Latin American independence movement\'s significance?', ['Spain peacefully granted independence to its colonies', 'Between 1810-1826, most Spanish and Portuguese colonies in the Americas won independence — inspired by Enlightenment ideas and the American and French Revolutions', 'Only Mexico gained independence in this period', 'The US liberated Latin American countries by military force'], 'Between 1810-1826, most Spanish and Portuguese colonies in the Americas won independence — inspired by Enlightenment ideas and the American and French Revolutions', 'Simón Bolívar, José de San Martín, and Miguel Hidalgo led independence movements across South America, Central America, and Mexico. By 1826, nearly all of Latin America was independent from European rule.', 4),
    mc('What was Napoleon\'s lasting impact on Europe?', ['He restored European monarchies to their pre-revolutionary power', 'He spread Revolutionary ideals (legal equality, nationalism, Napoleonic Code) across Europe while also triggering nationalism that would reshape the continent', 'He established a permanent French empire across Europe', 'He had no lasting impact after his defeat'], 'He spread Revolutionary ideals (legal equality, nationalism, Napoleonic Code) across Europe while also triggering nationalism that would reshape the continent', 'The Napoleonic Code\'s legal equality spread across Europe. His conquests stirred nationalist resistance that eventually produced German and Italian unification. His career both spread and ultimately triggered reaction against revolutionary ideals.', 5),
  ],
}
