import type { ExerciseDef } from '../types'

function mc(
  question: string,
  options: string[],
  correctAnswer: string,
  explanation: string,
  order: number
): ExerciseDef {
  return { question, type: 'MULTIPLE_CHOICE', options, correctAnswer, explanation, order }
}

export const historyExercises3: Record<string, ExerciseDef[]> = {
  'civil-war': [
    mc('What was the primary cause of the Civil War?', ['Tariffs and economic differences alone', 'Slavery — specifically its expansion into new territories and the political crisis it created', 'States\' rights in general, unrelated to slavery', 'Southern desire for a parliamentary government'], 'Slavery — specifically its expansion into new territories and the political crisis it created', 'The Confederacy\'s founding documents explicitly cite slavery\'s preservation as their cause. The "states\' rights" they sought to protect were primarily the right to hold people in slavery.', 1),
    mc('What was the Emancipation Proclamation (1863)?', ['A law ending slavery in all US states', 'A presidential order freeing enslaved people in Confederate states — transforming the war into explicitly a fight against slavery', 'A treaty offering freedom to enslaved people who fought for the Union', 'A law passed by Congress banning slavery nationwide'], 'A presidential order freeing enslaved people in Confederate states — transforming the war into explicitly a fight against slavery', 'Lincoln\'s proclamation applied only to Confederate states, not border states. It reframed the war, made European intervention for the Confederacy politically impossible, and authorized Black military service.', 2),
    mc('What military advantage did the North have over the South?', ['Superior military leadership', 'Larger population, industrial capacity, railroad network, and naval superiority', 'Geographic advantages and defensive position', 'Support from foreign nations'], 'Larger population, industrial capacity, railroad network, and naval superiority', 'The North\'s industrial and demographic advantages were decisive: 22 million Northerners vs 9 million Southerners (3.5 million enslaved). Northern industry could produce war material the agrarian South could not.', 3),
    mc('What was the significance of the Battle of Gettysburg (1863)?', ['The first major Confederate victory', 'The turning point of the war — the Confederate invasion of the North was repelled, ending Southern hopes for a decisive victory', 'The final battle of the Civil War', 'The battle where Lincoln delivered the Gettysburg Address during combat'], 'The turning point of the war — the Confederate invasion of the North was repelled, ending Southern hopes for a decisive victory', 'Gettysburg (July 1-3, 1863) ended Lee\'s second invasion of the North. Combined with Vicksburg\'s fall the same day, it shifted momentum decisively toward the Union.', 4),
    mc('What did the 13th Amendment do?', ['Granted Black men the right to vote', 'Abolished slavery throughout the United States', 'Granted citizenship to all people born in the US', 'Guaranteed equal protection under the law'], 'Abolished slavery throughout the United States', 'The 13th Amendment (1865) formally abolished slavery everywhere in the US, ending the institution that had existed since colonial times and resolving the central contradiction of the Republic.', 5),
  ],
  'reconstruction': [
    mc('What was Reconstruction?', ['The literal rebuilding of Southern infrastructure after the Civil War', 'The period (1865-1877) of federal effort to reintegrate Southern states and define the rights of newly freed people', 'A series of punitive laws punishing Confederate leaders', 'A plan to redistribute Southern land to formerly enslaved people'], 'The period (1865-1877) of federal effort to reintegrate Southern states and define the rights of newly freed people', 'Reconstruction involved debating how to rebuild the South, what rights freedpeople would have, and on what terms Confederate states could rejoin the Union — ending when Northern political will collapsed.', 1),
    mc('What were the Reconstruction Amendments?', ['13th, 14th, and 15th Amendments — abolishing slavery, granting birthright citizenship and equal protection, and prohibiting denial of voting rights based on race', '1st, 2nd, and 3rd Amendments', '10th, 11th, and 12th Amendments', 'Amendments specifically granting land to freedpeople'], '13th, 14th, and 15th Amendments — abolishing slavery, granting birthright citizenship and equal protection, and prohibiting denial of voting rights based on race', 'These three amendments transformed the Constitution: abolishing slavery (13th), creating birthright citizenship and equal protection (14th), and banning racial voting restrictions (15th).', 2),
    mc('What were Black Codes?', ['Laws granting rights to freedpeople', 'Southern laws restricting the freedom and rights of Black Americans after the Civil War — effectively re-creating conditions of servitude', 'Federal laws protecting Black citizens\' rights', 'Codes of conduct in Black community organizations'], 'Southern laws restricting the freedom and rights of Black Americans after the Civil War — effectively re-creating conditions of servitude', 'Black Codes (1865-66) restricted movement, required labor contracts, allowed vagrancy laws to force people into convict labor, and limited economic opportunity — shocking Northern Republicans into Radical Reconstruction.', 3),
    mc('How did Reconstruction end?', ['Congress voted to end federal oversight', 'The Compromise of 1877 — Republicans accepted Hayes as president; Democrats got federal troops withdrawn from the South, ending federal protection of Black rights', 'The Supreme Court ruled Reconstruction unconstitutional', 'Southern states met all conditions for readmission'], 'The Compromise of 1877 — Republicans accepted Hayes as president; Democrats got federal troops withdrawn from the South, ending federal protection of Black rights', 'The disputed 1876 election was resolved by a deal: Hayes became president, Union troops left the South, and Reconstruction ended — beginning the era of Jim Crow segregation and Black disenfranchisement.', 4),
    mc('What was sharecropping?', ['A system of land grants to freedpeople', 'A labor system where formerly enslaved people farmed land in exchange for a share of the crop — often trapping families in debt to white landowners', 'A cooperative farming arrangement among freedpeople', 'Government-sponsored farming communities for freedpeople'], 'A labor system where formerly enslaved people farmed land in exchange for a share of the crop — often trapping families in debt to white landowners', 'Sharecropping replaced slavery economically — landowners advanced supplies and tools, then manipulated accounts to keep workers perpetually in debt, unable to leave. It lasted well into the 20th century.', 5),
  ],
  'gilded-age-and-progressive-era': [
    mc('What characterized the Gilded Age (1870s-1900)?', ['A period of equal economic opportunity and democratic reform', 'Rapid industrialization, extreme inequality, political corruption, and the rise of monopolistic corporations', 'Strong labor unions and worker protections', 'Minimal immigration and cultural stability'], 'Rapid industrialization, extreme inequality, political corruption, and the rise of monopolistic corporations', 'Mark Twain coined "Gilded Age" — glittering on the surface but corrupt beneath. Robber barons (Carnegie, Rockefeller, Vanderbilt) accumulated unprecedented wealth while workers labored in dangerous conditions.', 1),
    mc('What did Progressive Era reformers seek to accomplish?', ['A return to agrarian society', 'Regulation of big business, democratic reforms (direct election of senators, women\'s suffrage), consumer protections, and social welfare measures', 'Expansion of American empire overseas', 'Reduction of immigration to the US'], 'Regulation of big business, democratic reforms (direct election of senators, women\'s suffrage), consumer protections, and social welfare measures', 'Progressives (1900-1920) targeted corporate power (antitrust laws), political corruption (primary elections, 17th Amendment), and social problems (child labor, food safety, women\'s suffrage).', 2),
    mc('What was the significance of Upton Sinclair\'s "The Jungle" (1906)?', ['It exposed Southern racism', 'It exposed unsanitary conditions in Chicago meatpacking plants, leading to the Pure Food and Drug Act', 'It argued for stronger labor unions', 'It documented conditions for immigrant workers in sweatshops'], 'It exposed unsanitary conditions in Chicago meatpacking plants, leading to the Pure Food and Drug Act', 'Sinclair intended to expose worker exploitation but readers were more shocked by what was in their food. Public outrage directly led to the Pure Food and Drug Act (1906) and the creation of the FDA.', 3),
    mc('What was the 19th Amendment?', ['Prohibition of alcohol', 'Women\'s right to vote, ratified in 1920', 'Direct election of senators', 'The income tax amendment'], 'Women\'s right to vote, ratified in 1920', 'After 72 years of activism beginning with Seneca Falls (1848), women won the constitutional right to vote. Susan B. Anthony, Elizabeth Cady Stanton, and Sojourner Truth are among the movement\'s leaders.', 4),
    mc('What was the Sherman Antitrust Act (1890)?', ['A tariff protecting American manufacturers', 'The first federal law banning monopolistic combinations and conspiracies in restraint of trade', 'A law regulating railroad rates', 'A banking regulation act'], 'The first federal law banning monopolistic combinations and conspiracies in restraint of trade', 'The Sherman Act gave government the power to break up trusts. Theodore Roosevelt used it to dissolve Standard Oil (1911) and Northern Securities — earning him the "trust-buster" label.', 5),
  ],
  'world-war-one': [
    mc('What triggered World War I?', ['Germany\'s invasion of France', 'The assassination of Archduke Franz Ferdinand of Austria-Hungary in Sarajevo (June 1914), setting off a chain of alliances', 'The sinking of the Lusitania', 'Britain\'s declaration of war on Germany'], 'The assassination of Archduke Franz Ferdinand of Austria-Hungary in Sarajevo (June 1914), setting off a chain of alliances', 'Franz Ferdinand\'s assassination by Gavrilo Princip triggered Austria-Hungary\'s ultimatum to Serbia → Russia mobilized → Germany declared war on Russia → France → Germany invaded Belgium → Britain declared war on Germany.', 1),
    mc('Why did the US enter World War I in 1917?', ['The sinking of the Lusitania alone', 'German unrestricted submarine warfare attacking American ships and the Zimmermann Telegram offering Mexico US territory to attack America', 'To fulfill treaty obligations', 'After a direct German attack on US territory'], 'German unrestricted submarine warfare attacking American ships and the Zimmermann Telegram offering Mexico US territory to attack America', 'Wilson asked Congress for war after Germany resumed sinking American ships and the Zimmermann Telegram (Germany\'s secret offer to Mexico) was intercepted and published.', 2),
    mc('What were the major outcomes of World War I?', ['Germany became a major power; the Ottoman Empire survived', 'Germany was humiliated by the Treaty of Versailles, four empires collapsed, the League of Nations was created, and conditions for WWII were set', 'A stable peace was achieved in Europe for a generation', 'The US became the dominant world power immediately'], 'Germany was humiliated by the Treaty of Versailles, four empires collapsed, the League of Nations was created, and conditions for WWII were set', 'Versailles imposed crushing reparations, territorial losses, and war guilt on Germany — fueling resentment exploited by Hitler. Germany, Austria-Hungary, Ottoman, and Russian empires all collapsed.', 3),
    mc('What was the Great Migration (1910-1970)?', ['European immigration to the US during World War I', 'The mass movement of Black Americans from the South to Northern cities seeking industrial jobs and escape from Jim Crow', 'The migration of American families westward during the Dust Bowl', 'The movement of workers to wartime manufacturing centers'], 'The mass movement of Black Americans from the South to Northern cities seeking industrial jobs and escape from Jim Crow', 'About 6 million Black Americans migrated North, transforming Chicago, Detroit, New York, and other cities. The migration built the cultural foundations of the Harlem Renaissance and reshaped American politics.', 4),
    mc('What was the 18th Amendment (Prohibition)?', ['Women\'s right to vote', 'Constitutional ban on the manufacture, sale, and transportation of alcohol (1920-1933)', 'Federal income tax', 'Direct election of US senators'], 'Constitutional ban on the manufacture, sale, and transportation of alcohol (1920-1933)', 'Prohibition (18th Amendment, enforced by Volstead Act) banned alcohol nationally. It failed — bootlegging, speakeasies, and organized crime flourished. Repealed by the 21st Amendment (1933).', 5),
  ],
  'great-depression': [
    mc('What caused the Great Depression?', ['A single stock market crash', 'Multiple factors: stock market crash (1929), bank failures, falling agricultural prices, Smoot-Hawley tariff, and contractionary monetary policy', 'German war reparations disrupting global trade', 'Government overspending in the 1920s'], 'Multiple factors: stock market crash (1929), bank failures, falling agricultural prices, Smoot-Hawley tariff, and contractionary monetary policy', 'The Depression had many causes. The crash triggered a financial panic. Bank failures destroyed savings. The Fed tightened money supply. The Smoot-Hawley tariff crushed global trade. All feedback-looped into collapse.', 1),
    mc('What was the New Deal?', ['A Republican plan for economic recovery through tax cuts', 'FDR\'s programs to provide relief, recovery, and reform — including Social Security, banking regulation, and public works employment', 'A negotiated settlement with European creditors', 'A plan to return to the gold standard'], 'FDR\'s programs to provide relief, recovery, and reform — including Social Security, banking regulation, and public works employment', 'FDR\'s first 100 days transformed the role of federal government. New Deal agencies: FDIC (bank insurance), SEC (market regulation), Social Security, TVA (public power), and CCC/WPA (public employment).', 2),
    mc('What was the Dust Bowl?', ['A mining collapse in the West', 'A devastating ecological disaster in the Great Plains — years of drought and poor farming practices created massive dust storms, displacing hundreds of thousands', 'Flooding along the Mississippi River', 'A factory accident that spread industrial pollution'], 'A devastating ecological disaster in the Great Plains — years of drought and poor farming practices created massive dust storms, displacing hundreds of thousands', 'Over-plowing removed native grasses; drought turned topsoil to dust. "Black blizzards" buried farms. ~3.5 million people fled the Great Plains — Okies traveled Route 66 to California.', 3),
    mc('What long-term changes did the New Deal make to American government?', ['Minimal lasting changes — programs were temporary', 'It fundamentally expanded the federal government\'s role in the economy and created the social safety net (Social Security, unemployment insurance, banking regulation)', 'It reduced government involvement in markets', 'It transferred power from federal to state governments'], 'It fundamentally expanded the federal government\'s role in the economy and created the social safety net (Social Security, unemployment insurance, banking regulation)', 'The New Deal permanently changed Americans\' expectations of government — federal responsibility for economic stability and minimum security became embedded in policy. Social Security still exists today.', 4),
    mc('What ultimately ended the Great Depression?', ['The New Deal fully restored the economy by 1937', 'World War II spending — massive government investment in war production effectively ended unemployment', 'Tax cuts stimulating private investment', 'The gold standard being restored'], 'World War II spending — massive government investment in war production effectively ended unemployment', 'By 1940, unemployment was still 14%. War mobilization eliminated it: 16 million in military, millions more in war industries. The New Deal reformed capitalism but WWII spending finally ended the Depression.', 5),
  ],
  'world-war-two': [
    mc('What was the Holocaust?', ['Germany\'s military strategy in Eastern Europe', 'The Nazi genocide of six million Jews and millions of others (Roma, disabled people, political opponents, LGBTQ people) through systematic mass murder', 'Anti-Jewish laws restricting civil rights', 'World War II combat deaths on the Eastern Front'], 'The Nazi genocide of six million Jews and millions of others (Roma, disabled people, political opponents, LGBTQ people) through systematic mass murder', 'The Holocaust was industrialized genocide — concentration camps, death camps (Auschwitz, Treblinka), mass shootings by Einsatzgruppen. Six million Jews — two-thirds of European Jewry — were murdered.', 1),
    mc('What brought the US into World War II?', ['Germany\'s declaration of war on the US', 'Japan\'s surprise attack on Pearl Harbor, Hawaii (December 7, 1941)', 'The fall of France', 'German submarine attacks on US ships'], 'Japan\'s surprise attack on Pearl Harbor, Hawaii (December 7, 1941)', 'Japan attacked the US Pacific Fleet at Pearl Harbor, killing 2,403 Americans. FDR called it "a date which will live in infamy." Congress declared war on Japan; Germany and Italy then declared war on the US.', 2),
    mc('What was D-Day (June 6, 1944)?', ['Japan\'s surrender to Allied forces', 'The Allied invasion of Normandy, France — the largest seaborne invasion in history, opening the Western Front against Nazi Germany', 'The US invasion of North Africa', 'Germany\'s surrender to Allied forces'], 'The Allied invasion of Normandy, France — the largest seaborne invasion in history, opening the Western Front against Nazi Germany', 'Operation Overlord landed 156,000 Allied troops on five beaches. Despite massive casualties, the beachheads held — beginning the liberation of Western Europe and Germany\'s two-front collapse.', 3),
    mc('What was the Manhattan Project?', ['A US urban renewal program', 'The secret US program to develop atomic weapons, culminating in bombs dropped on Hiroshima and Nagasaki', 'A plan to rebuild Manhattan after wartime rationing', 'The Allied intelligence operation in Western Europe'], 'The secret US program to develop atomic weapons, culminating in bombs dropped on Hiroshima and Nagasaki', 'Led by J. Robert Oppenheimer, the Manhattan Project employed 130,000 people at secret sites. The bombs on Hiroshima (August 6) and Nagasaki (August 9, 1945) killed 100,000-200,000 and led to Japan\'s surrender.', 4),
    mc('What was the United Nations and why was it created?', ['A military alliance against the Soviet Union', 'An intergovernmental organization created after WWII to maintain peace, foster international cooperation, and prevent another world war', 'A trade agreement among Allied nations', 'A court to try Nazi war criminals'], 'An intergovernmental organization created after WWII to maintain peace, foster international cooperation, and prevent another world war', 'The UN (founded 1945, replacing the failed League of Nations) has 193 member states. Its Security Council (with five permanent veto-holding members) is the primary body for international peace and security.', 5),
  ],
  'cold-war': [
    mc('What was the Cold War?', ['A war fought in cold climates', 'A geopolitical rivalry between the US and USSR from 1947 to 1991, characterized by ideological competition, proxy wars, and nuclear threat but no direct military conflict', 'A trade war between the US and Soviet bloc', 'A diplomatic dispute about post-WWII borders'], 'A geopolitical rivalry between the US and USSR from 1947 to 1991, characterized by ideological competition, proxy wars, and nuclear threat but no direct military conflict', 'The Cold War pitted US-led capitalism/democracy against Soviet communism across the globe — through arms race, space race, propaganda, and proxy wars in Korea, Vietnam, and elsewhere.', 1),
    mc('What was the Marshall Plan?', ['A military alliance with Western European nations', 'The US program providing $13 billion in economic aid to rebuild Western Europe after WWII, preventing communist political gains', 'A treaty dividing Germany into East and West', 'A nuclear weapons sharing agreement with NATO allies'], 'The US program providing $13 billion in economic aid to rebuild Western Europe after WWII, preventing communist political gains', 'Secretary of State Marshall\'s plan (1948-1952) rebuilt European economies devastated by WWII. Prosperous democracies were less vulnerable to communist parties, which is precisely the strategic intent.', 2),
    mc('What was the doctrine of Mutually Assured Destruction (MAD)?', ['A military strategy for fighting nuclear war', 'The deterrence logic that both superpowers had enough nuclear weapons that any first strike would trigger devastating retaliation — making nuclear war suicidal', 'A UN policy on nuclear disarmament', 'A US pledge not to use nuclear weapons first'], 'The deterrence logic that both superpowers had enough nuclear weapons that any first strike would trigger devastating retaliation — making nuclear war suicidal', 'MAD created a stable (if terrifying) deterrence: both sides knew nuclear war meant their own destruction, creating incentive not to strike first. The balance of terror prevented direct conflict.', 3),
    mc('What was the Cuban Missile Crisis (1962)?', ['The US invasion of Cuba to remove Castro', 'A 13-day standoff when the US discovered Soviet nuclear missiles in Cuba — the closest the Cold War came to nuclear exchange', 'Cuba\'s attempt to acquire nuclear weapons independently', 'A trade embargo dispute with Cuba'], 'A 13-day standoff when the US discovered Soviet nuclear missiles in Cuba — the closest the Cold War came to nuclear exchange', 'Kennedy and Khrushchev negotiated: Soviets withdrew Cuban missiles; US pledged not to invade Cuba and secretly removed missiles from Turkey. The crisis led to the nuclear hotline and arms control talks.', 4),
    mc('How did the Cold War end?', ['The US defeated the Soviet Union militarily', 'The Soviet Union collapsed internally (1991) due to economic stagnation, nationalist movements, and Gorbachev\'s reforms — ending the Cold War', 'A negotiated peace treaty between superpowers', 'Nuclear disarmament treaties resolved the conflict'], 'The Soviet Union collapsed internally (1991) due to economic stagnation, nationalist movements, and Gorbachev\'s reforms — ending the Cold War', 'Gorbachev\'s glasnost (openness) and perestroika (restructuring) loosened Soviet control. Berlin Wall fell 1989. Baltic republics declared independence. Soviet Union formally dissolved December 25, 1991.', 5),
  ],
  'civil-rights-movement': [
    mc('What was the legal foundation of segregation challenged by the Civil Rights Movement?', ['Reconstruction laws requiring segregation', '"Separate but equal" — established by Plessy v. Ferguson (1896) — which segregated public facilities based on race', 'State constitutions requiring segregation', 'The 14th Amendment which permitted separate facilities'], '"Separate but equal" — established by Plessy v. Ferguson (1896) — which segregated public facilities based on race', 'Plessy held that racial segregation was constitutional as long as facilities were "equal." Brown v. Board (1954) overturned this — separate is inherently unequal.', 1),
    mc('What was the significance of Brown v. Board of Education (1954)?', ['It integrated the US military', 'The Supreme Court unanimously ruled racial segregation in public schools unconstitutional, overturning Plessy v. Ferguson', 'It gave Black Americans the right to vote', 'It outlawed literacy tests for voting'], 'The Supreme Court unanimously ruled racial segregation in public schools unconstitutional, overturning Plessy v. Ferguson', 'Chief Justice Warren\'s unanimous decision declared segregated schools inherently unequal — a landmark that opened the legal assault on Jim Crow and energized the Civil Rights Movement.', 2),
    mc('What was the Montgomery Bus Boycott (1955-56)?', ['A Supreme Court case about bus segregation', 'A 381-day boycott of Montgomery city buses by Black residents after Rosa Parks\' arrest — ending bus segregation and launching MLK\'s national prominence', 'A federal law desegregating public transportation', 'A protest march from Montgomery to Washington DC'], 'A 381-day boycott of Montgomery city buses by Black residents after Rosa Parks\' arrest — ending bus segregation and launching MLK\'s national prominence', 'Rosa Parks\'s arrest for refusing to give her seat to a white man sparked the boycott. With 40,000 Black riders refusing to ride, the bus company lost revenue. The Supreme Court ultimately ruled bus segregation unconstitutional.', 3),
    mc('What was the Civil Rights Act of 1964?', ['A law giving Black Americans the right to vote', 'A landmark law prohibiting discrimination based on race, color, religion, sex, or national origin in employment and public accommodations', 'A constitutional amendment banning segregation', 'A law creating the NAACP'], 'A landmark law prohibiting discrimination based on race, color, religion, sex, or national origin in employment and public accommodations', 'The Civil Rights Act banned discrimination in hotels, restaurants, theaters, and employment. Combined with the Voting Rights Act (1965), it legally dismantled Jim Crow — though enforcement and social change lagged.', 4),
    mc('What was the philosophy of nonviolent direct action in the Civil Rights Movement?', ['Avoiding all confrontation with authorities', 'Deliberately and peacefully breaking unjust laws to force moral confrontation, accepting the consequences to expose injustice', 'A legal strategy relying only on courts', 'A diplomatic approach negotiating with Southern governors'], 'Deliberately and peacefully breaking unjust laws to force moral confrontation, accepting the consequences to expose injustice', 'Inspired by Gandhi, MLK\'s strategy of nonviolence exposed the brutality of the system. Sit-ins, freedom rides, and marches — met with fire hoses and clubs — shifted national and international opinion.', 5),
  ],
}
