import type { ExerciseDef } from '../types'

function mc(
  question: string,
  options: string[],
  correctAnswer: string,
  explanation: string,
  order: number
): ExerciseDef {
  return { question, type: 'MULTIPLE_CHOICE', options, correctAnswer, explanation, order }
}

export const languageExercises1: Record<string, ExerciseDef[]> = {
  'before-you-read': [
    mc('What is the purpose of previewing a text before reading?', ['To avoid having to read the whole thing', 'To activate prior knowledge, set a purpose, and create a mental framework that helps you read more efficiently', 'To find out if the text is worth reading', 'To memorize the headings and subheadings'], 'To activate prior knowledge, set a purpose, and create a mental framework that helps you read more efficiently', 'Previewing — scanning titles, headings, visuals, and the introduction — primes your brain to connect new information to what you already know, making comprehension deeper and faster.', 1),
    mc('What is a useful strategy when previewing an unfamiliar text?', ['Skip to the conclusion immediately', 'Read the title, scan headings and visuals, read the first and last paragraphs, then predict what the text is about', 'Read every word at normal speed from the beginning', 'Look up the author\'s biography first'], 'Read the title, scan headings and visuals, read the first and last paragraphs, then predict what the text is about', 'This previewing sequence builds a mental map before deep reading. Predictions don\'t need to be correct — the act of predicting actively engages your mind with the content.', 2),
    mc('Why should you set a purpose before reading?', ['So you can stop reading when you\'ve achieved it', 'A clear purpose directs your attention — you know what to look for and can read more efficiently', 'So you can skip sections that don\'t match your purpose', 'It isn\'t particularly helpful — just read the text'], 'A clear purpose directs your attention — you know what to look for and can read more efficiently', 'Reading to find a specific answer is faster than reading everything with equal attention. Setting a purpose helps you skim irrelevant sections and slow down for important ones.', 3),
    mc('What does activating prior knowledge before reading help you do?', ['Confirm that you already know the topic', 'Connect new information to existing knowledge, which improves comprehension and retention', 'Avoid reading texts outside your expertise', 'Speed up your reading rate'], 'Connect new information to existing knowledge, which improves comprehension and retention', 'Memory works through connections. New information sticks better when attached to something you already know. Activating prior knowledge before reading creates hooks for the new content.', 4),
    mc('When is prediction a useful prereading strategy?', ['Never — you should read without expectations', 'Always — making predictions, even incorrect ones, actively engages you with the text and improves comprehension', 'Only when you know the topic well already', 'Only for fiction texts'], 'Always — making predictions, even incorrect ones, actively engages you with the text and improves comprehension', 'Prediction is generative — it forces your brain to engage actively with the material. When predictions are wrong, that contrast with reality is itself memorable and helps understanding.', 5),
  ],
  'reading-actively': [
    mc('What is annotation in reading?', ['Writing a summary of the entire text', 'Marking up the text — underlining, highlighting, writing notes in margins — to engage actively and track your thinking', 'Reading the text twice before taking notes', 'Translating difficult vocabulary into simpler words'], 'Marking up the text — underlining, highlighting, writing notes in margins — to engage actively and track your thinking', 'Annotation transforms passive reading into an active conversation with the text. Your marks and notes record your thinking process and make it easier to review key ideas later.', 1),
    mc('What makes a good reading question?', ['A question you already know the answer to', 'A question that requires engaging with the text\'s meaning — not just finding a fact, but making sense of why or how', 'Any question that occurs to you while reading', 'A question with a yes or no answer'], 'A question that requires engaging with the text\'s meaning — not just finding a fact, but making sense of why or how', '"What does the author mean by this?" or "Why does this matter?" push deeper than "What year did this happen?" Good questions drive active comprehension rather than surface scanning.', 2),
    mc('What is summarizing in the context of active reading?', ['Copying out the most important sentences', 'Restating the text\'s main ideas in your own words — a check that you actually understood it', 'Writing a shorter version of the text for someone else', 'Paraphrasing every sentence as you read'], 'Restating the text\'s main ideas in your own words — a check that you actually understood it', 'Summarizing in your own words forces you to process meaning, not just recognize words. If you can\'t summarize a section, you probably didn\'t fully understand it.', 3),
    mc('What does it mean to "chunk" a reading?', ['Skipping sections that seem difficult', 'Breaking a long text into manageable sections and pausing after each to check comprehension before continuing', 'Reading in timed intervals with breaks', 'Grouping related vocabulary words together'], 'Breaking a long text into manageable sections and pausing after each to check comprehension before continuing', 'Chunking prevents the experience of reading many pages and retaining nothing. Stopping to reflect after each section consolidates understanding before moving on.', 4),
    mc('Why is re-reading a strategy for difficult texts?', ['Because the first reading is never useful', 'Complex texts often reward re-reading — the second pass reveals connections and meaning invisible in the first read', 'Because you should always read everything twice', 'Re-reading is only useful for fiction'], 'Complex texts often reward re-reading — the second pass reveals connections and meaning invisible in the first read', 'First reading provides a rough map; second reading deepens understanding. Knowing how the text ends, for example, makes earlier parts more meaningful. Dense texts almost always require multiple reads.', 5),
  ],
  'main-idea-and-detail': [
    mc('What is the main idea of a text?', ['The first sentence of the text', 'The central point or argument the author wants you to take away from the entire text', 'A summary of all the facts presented', 'The most interesting part of the text'], 'The central point or argument the author wants you to take away from the entire text', 'The main idea is what the whole text is about — the "so what?" Everything else (examples, data, anecdotes) exists to support it. It\'s different from the topic, which is just the subject.', 1),
    mc('What is the difference between a topic and a main idea?', ['They are the same thing stated differently', 'The topic is the subject (what the text is about); the main idea is the argument about that topic (what the author claims about it)', 'The topic is more specific; the main idea is more general', 'The main idea appears in the first paragraph; the topic is stated elsewhere'], 'The topic is the subject (what the text is about); the main idea is the argument about that topic (what the author claims about it)', 'Topic: "climate change." Main idea: "Climate change poses an existential threat requiring immediate policy action." The topic is just a label; the main idea makes a claim about it.', 2),
    mc('What is a supporting detail?', ['Any sentence in the text that isn\'t the main idea', 'Specific evidence, examples, facts, or explanations that develop and support the main idea', 'A quotation from another source', 'A statistic mentioned in the text'], 'Specific evidence, examples, facts, or explanations that develop and support the main idea', 'Supporting details explain, prove, or illustrate the main idea. They answer "how do you know?" or "can you give an example?" Not every detail is equally important — you must distinguish major from minor support.', 3),
    mc('Where is the main idea most commonly stated in a paragraph?', ['Always in the middle', 'Most often in the topic sentence — typically the first or last sentence — though sometimes it must be inferred', 'Only in the last sentence', 'It is never explicitly stated — always implied'], 'Most often in the topic sentence — typically the first or last sentence — though sometimes it must be inferred', 'Academic writing typically states the topic sentence first. Literary and journalistic writing sometimes build to it or imply it. Recognizing these patterns helps you find main ideas efficiently.', 4),
    mc('How do you distinguish important details from minor ones?', ['All details mentioned in the text are equally important', 'Important details directly support the main idea; minor details add color but aren\'t essential to the argument', 'Only details with statistics are important', 'The author always signals which details matter'], 'Important details directly support the main idea; minor details add color but aren\'t essential to the argument', 'Ask: "If this detail were removed, would the main idea be unsupported?" Major details answer yes. Minor details (illustrative anecdotes, colorful examples) add interest without being structurally necessary.', 5),
  ],
  'inference-and-implication': [
    mc('What is an inference in reading?', ['A fact explicitly stated in the text', 'A conclusion drawn by combining textual evidence with prior knowledge — reading what is implied but not directly stated', 'An opinion stated by the author', 'A prediction about what will happen next in the text'], 'A conclusion drawn by combining textual evidence with prior knowledge — reading what is implied but not directly stated', 'Inference fills gaps between what\'s written and what\'s meant. "She slammed the door" implies anger without stating it. Good inference is based on textual evidence, not just imagination.', 1),
    mc('What is the difference between explicit and implicit information?', ['Explicit is true; implicit might not be', 'Explicit information is directly stated; implicit information is suggested or implied — you must infer it', 'Explicit is in the text; implicit is in the author\'s intention only', 'There is no meaningful difference'], 'Explicit information is directly stated; implicit information is suggested or implied — you must infer it', '"It was raining" is explicit. "She paused at the window before leaving" might implicitly suggest hesitation or sadness — the reader infers emotional meaning from physical description.', 2),
    mc('What makes an inference valid?', ['You feel confident about it', 'It is grounded in specific textual evidence AND is consistent with what you know — not just a guess', 'The author might have intended it', 'It makes the text more interesting'], 'It is grounded in specific textual evidence AND is consistent with what you know — not just a guess', 'Valid inferences point to evidence. "I think she\'s nervous because the text says her hands were shaking and she kept checking her phone" is supported. "I think she\'s nervous because I\'ve felt that way" is not.', 3),
    mc('What is subtext?', ['A secondary text referenced by the main text', 'The layer of meaning beneath the surface — what is implied, unsaid, or communicated indirectly in a text', 'A text that is less important than the main text', 'Footnotes and citations in academic writing'], 'The layer of meaning beneath the surface — what is implied, unsaid, or communicated indirectly in a text', 'Subtext is communication beneath the literal words. In dialogue, characters often say one thing but mean another. Authors use setting, word choice, and action to convey meaning beyond what\'s explicitly stated.', 4),
    mc('Why is making inferences important for reading comprehension?', ['Because authors always leave out important information deliberately', 'All meaningful texts leave gaps that readers must fill using inference — understanding requires going beyond the literal surface of the text', 'Because it helps you read faster', 'Inference is only needed for fiction'], 'All meaningful texts leave gaps that readers must fill using inference — understanding requires going beyond the literal surface of the text', 'No text states everything. Authors assume shared knowledge, use figurative language, and imply rather than state. Readers who only process explicit content miss much of the meaning. Inference is fundamental comprehension.', 5),
  ],
  'authors-purpose': [
    mc('What are the main purposes an author might have?', ['To confuse and challenge the reader', 'To inform, persuade, entertain, or some combination — and understanding the purpose helps you read critically', 'Only to provide information', 'To test the reader\'s knowledge'], 'To inform, persuade, entertain, or some combination — and understanding the purpose helps you read critically', 'Authors write to inform (news, textbooks), persuade (arguments, advertisements), entertain (fiction, humor), or inspire. Identifying purpose helps you read with appropriate skepticism and attention.', 1),
    mc('How does an author\'s purpose affect how you read a text?', ['It doesn\'t — you should read all texts the same way', 'It changes what you look for: informational texts → accuracy and completeness; persuasive texts → reasoning and evidence; entertainment → enjoyment and emotional response', 'It only affects how quickly you read', 'It tells you whether to trust the text at all'], 'It changes what you look for: informational texts → accuracy and completeness; persuasive texts → reasoning and evidence; entertainment → enjoyment and emotional response', 'Reading a scientific article requires checking methodology. Reading a political op-ed requires evaluating arguments. Reading a novel invites emotional engagement. Matching your reading approach to purpose improves comprehension.', 2),
    mc('What is point of view in a text?', ['The tense in which the story is told', 'The perspective from which a text is written — who is telling it and what they know, believe, and can observe', 'Whether the author uses first or third person pronouns', 'The author\'s emotional state while writing'], 'The perspective from which a text is written — who is telling it and what they know, believe, and can observe', 'Point of view shapes everything. First-person narration is intimate but limited to one perspective. Third-person omniscient knows all characters\' thoughts. News uses third-person limited. Each creates different relationships with the reader.', 3),
    mc('How does author\'s background affect their writing?', ['It never affects what they write', 'Authors write from their experiences, identities, and beliefs — which shape what they notice, how they frame things, and whose stories they tell', 'Only unprofessional authors let their background show', 'Background only matters in autobiographical writing'], 'Authors write from their experiences, identities, and beliefs — which shape what they notice, how they frame things, and whose stories they tell', 'All writing reflects a perspective shaped by the writer\'s life. This doesn\'t make writing invalid — but knowing who wrote a text (and their context) helps you read it more critically and completely.', 4),
    mc('How can you identify an author\'s purpose when it isn\'t explicitly stated?', ['You can\'t — assume all texts are purely informational', 'By examining the content selected, the tone, the evidence used, and what the text asks you to think or do differently', 'By checking the author\'s credentials', 'By the length of the text'], 'By examining the content selected, the tone, the evidence used, and what the text asks you to think or do differently', 'Ask: What information does the author include and exclude? Is the tone neutral or charged? Does it present multiple perspectives? Does it call you to action? These clues reveal purpose even when unstated.', 5),
  ],
  'tone-and-voice': [
    mc('What is tone in writing?', ['The volume at which the text should be read', 'The author\'s attitude toward the subject and audience — conveyed through word choice, sentence structure, and content selection', 'The main theme of the text', 'The genre the text belongs to'], 'The author\'s attitude toward the subject and audience — conveyed through word choice, sentence structure, and content selection', 'Tone can be formal or informal, sincere or ironic, urgent or contemplative, angry or compassionate. Like tone of voice in speech, it shapes how the message lands regardless of the literal content.', 1),
    mc('What is diction in writing?', ['Grammar rules governing word order', 'Word choice — the specific words an author selects, which carry connotations and create tone', 'The use of dialogue in fiction', 'Spelling and punctuation decisions'], 'Word choice — the specific words an author selects, which carry connotations and create tone', '"Passed away," "died," and "croaked" all mean the same thing but carry very different tones. Diction is one of the most powerful tools writers have — word choice shapes meaning, tone, and how readers feel.', 2),
    mc('What is the difference between denotation and connotation?', ['Denotation is for literary texts; connotation is for informational texts', 'Denotation is a word\'s literal dictionary meaning; connotation is the emotional associations and implications it carries', 'Connotation is more precise than denotation', 'There is no meaningful difference'], 'Denotation is a word\'s literal dictionary meaning; connotation is the emotional associations and implications it carries', '"Home" and "house" have similar denotations but different connotations — home implies warmth and belonging. Writers choose words for their connotations, not just their definitions.', 3),
    mc('What is voice in writing?', ['The author\'s speaking voice recorded as audio', 'The distinctive personality that comes through a writer\'s work — the combination of diction, rhythm, perspective, and attitude that makes one writer sound different from another', 'Whether a text is written in first or third person', 'The genre-specific style required by a publication'], 'The distinctive personality that comes through a writer\'s work — the combination of diction, rhythm, perspective, and attitude that makes one writer sound different from another', 'Voice is why you can often recognize a writer by a paragraph: Hemingway\'s terse directness, Didion\'s crystalline cool, Twain\'s vernacular warmth. Voice is what makes writing feel alive and individual.', 4),
    mc('How does figurative language affect tone?', ['It doesn\'t — tone is only created by explicit statements', 'Metaphors, similes, and imagery create emotional associations that shape how readers feel about the subject', 'It only matters in poetry', 'Figurative language always creates an informal tone'], 'Metaphors, similes, and imagery create emotional associations that shape how readers feel about the subject', '"The economy collapsed" is neutral. "The economy was gutted like a fish" is visceral and alarming. Figurative language recruits emotional and sensory associations that shape tone far beyond the literal meaning.', 5),
  ],
  'evaluating-arguments': [
    mc('What components make a strong argument?', ['Emotional appeals and confident delivery', 'A clear claim, relevant evidence that supports it, sound reasoning connecting evidence to the claim, and acknowledgment of counterarguments', 'Many examples and statistics', 'An authoritative tone and credentials'], 'A clear claim, relevant evidence that supports it, sound reasoning connecting evidence to the claim, and acknowledgment of counterarguments', 'Strong arguments are transparent about their logic. The claim is debatable; evidence is verifiable; reasoning is explicit and valid; counterarguments show the author has engaged honestly with complexity.', 1),
    mc('What is the difference between evidence and an assertion?', ['Assertions are more reliable than evidence', 'An assertion is an unsupported claim; evidence is verifiable data, examples, or expert consensus that supports a claim', 'They are different words for the same thing', 'Assertions are facts; evidence is interpretation'], 'An assertion is an unsupported claim; evidence is verifiable data, examples, or expert consensus that supports a claim', '"Vaccines cause harm" is an assertion. "Studies show vaccines prevent disease with very rare side effects" is an evidence-based claim. Demanding evidence separates persuasion from manipulation.', 2),
    mc('What does it mean for an argument to be internally consistent?', ['The argument is long enough to be credible', 'The premises actually lead to the conclusion, without contradictions or logical gaps', 'All examples used in the argument are from credible sources', 'The argument agrees with your prior beliefs'], 'The premises actually lead to the conclusion, without contradictions or logical gaps', 'Internal consistency means the argument\'s structure holds together. If you accept the premises, you should reach the conclusion. Contradicting yourself or drawing conclusions your evidence doesn\'t support are inconsistency failures.', 3),
    mc('Why is acknowledging counterarguments a sign of a strong argument?', ['It shows the author isn\'t confident in their position', 'It demonstrates intellectual honesty and strengthens the argument by showing the author has considered and addressed opposing views', 'It makes the argument longer and more impressive', 'It allows the author to avoid defending the main claim'], 'It demonstrates intellectual honesty and strengthens the argument by showing the author has considered and addressed opposing views', 'Arguments that ignore counterarguments are weaker because readers can easily think of objections the author didn\'t address. Acknowledging and refuting counterarguments demonstrates genuine engagement with the topic.', 4),
    mc('What is a rhetorical appeal?', ['A type of logical fallacy', 'A strategy for persuasion — logos (logic/evidence), ethos (credibility/character), pathos (emotion)', 'Only emotional manipulation in political speech', 'A technique used only in advertisements'], 'A strategy for persuasion — logos (logic/evidence), ethos (credibility/character), pathos (emotion)', 'Aristotle\'s three appeals: logos (reasoning and evidence), ethos (establishing the speaker\'s credibility), pathos (connecting emotionally with the audience). Strong arguments typically use all three appropriately.', 5),
  ],
}
