import type { ExerciseDef } from '../types'

function mc(
  question: string,
  options: string[],
  correctAnswer: string,
  explanation: string,
  order: number
): ExerciseDef {
  return { question, type: 'MULTIPLE_CHOICE', options, correctAnswer, explanation, order }
}

export const languageExercises3: Record<string, ExerciseDef[]> = {
  'capitalization': [
    mc('Which words are always capitalized in English?', ['All nouns and adjectives', 'The first word of a sentence, proper nouns, and the pronoun "I"', 'All important words regardless of type', 'Only names of people and places'], 'The first word of a sentence, proper nouns, and the pronoun "I"', 'Proper nouns (specific names: Sarah, Chicago, Monday, January, English) are capitalized. Common nouns (city, day, month, language) are not. "I" is always capitalized regardless of position.', 1),
    mc('Which sentence is correctly capitalized?', ['"I love the Fall season in new england."', '"I love the fall season in New England."', '"i love the Fall Season in New England."', '"I Love The Fall Season In New England."'], '"I love the fall season in New England."', '"Fall" is a common noun (season) — not capitalized. "New England" is a proper noun (specific region) — capitalized. "I" is always capitalized. Don\'t capitalize every word — only proper nouns and sentence beginnings.', 2),
    mc('When are titles capitalized?', ['Always capitalize all words in any title', 'Capitalize the first word, last word, and all major words — but not articles, short prepositions, or coordinating conjunctions (unless first or last)', 'Only capitalize the first word of a title', 'Capitalize every word except the last one'], 'Capitalize the first word, last word, and all major words — but not articles, short prepositions, or coordinating conjunctions (unless first or last)', '"The Catcher in the Rye" — "the," "in" are not capitalized (articles and prepositions). This is "title case." Some styles differ slightly, but the principle is consistent.', 3),
    mc('Should seasons (spring, summer, fall, winter) be capitalized?', ['Yes — always capitalize seasons', 'No — seasons are common nouns and are not capitalized', 'Only when used as adjectives', 'Only when referring to a specific year\'s season'], 'No — seasons are common nouns and are not capitalized', '"I love fall." "Summer is my favorite season." Seasons are common nouns — not capitalized. Compare: "Monday" (proper noun, capitalized) vs. "autumn" (common noun, not capitalized).', 4),
    mc('When should directions be capitalized?', ['Always capitalize North, South, East, and West', 'Capitalize when referring to a specific region (the South, the Pacific Northwest) but not when indicating direction (drive north, turn east)', 'Never capitalize directions', 'Only capitalize when used in a place name'], 'Capitalize when referring to a specific region (the South, the Pacific Northwest) but not when indicating direction (drive north, turn east)', '"She moved to the South." (proper noun — the region) vs. "Drive south on I-95." (direction, not capitalized). "The West" (region) vs. "the western wall" (adjective, direction).', 5),
  ],
  'brainstorming': [
    mc('What is brainstorming in the writing process?', ['Editing your first draft for errors', 'Generating as many ideas as possible without judging them — quantity over quality', 'Researching sources for your paper', 'Outlining your main points before writing'], 'Generating as many ideas as possible without judging them — quantity over quality', 'Effective brainstorming suspends judgment. No idea is too wild. The goal is volume — you\'ll evaluate, select, and refine later. Self-censoring too early kills creative possibilities.', 1),
    mc('What is freewriting?', ['Writing without any errors', 'Writing continuously for a set time without stopping or editing — letting ideas flow without self-censorship', 'Writing the final draft without an outline', 'Writing only the parts of an essay you know well'], 'Writing continuously for a set time without stopping or editing — letting ideas flow without self-censorship', 'Set a timer (5-10 minutes), write continuously, don\'t lift the pen or stop to edit. The goal is to bypass your inner critic and discover what you actually think. Most of it won\'t be usable — that\'s fine.', 2),
    mc('What is mind mapping?', ['Planning your essay structure', 'A visual brainstorming technique starting with a central idea and branching out to related concepts', 'Memorizing information using visual aids', 'Creating a diagram of a text\'s argument'], 'A visual brainstorming technique starting with a central idea and branching out to related concepts', 'Mind maps (also called clustering or webbing) let you see connections between ideas visually. Write the central topic in the center, branch out to subtopics, then branch those further — revealing unexpected connections.', 3),
    mc('Why is it important to brainstorm before outlining?', ['Outlining first is actually better', 'Brainstorming opens possibilities before you commit to a structure — outlining too early can shut down ideas before you\'ve found the best ones', 'Brainstorming and outlining should happen simultaneously', 'You only need to brainstorm if you have no ideas at all'], 'Brainstorming opens possibilities before you commit to a structure — outlining too early can shut down ideas before you\'ve found the best ones', 'Committing to structure too early narrows your thinking. Brainstorm first to explore the territory fully, then choose the best path and outline it. Structure imposes judgment — save it for after generating ideas.', 4),
    mc('What should you do with your brainstormed ideas before writing?', ['Use all of them in your draft', 'Review, evaluate, group related ideas, select the most promising ones, and decide on a focus or thesis', 'Delete the weakest ideas and use the rest in order', 'Share all your ideas with others before selecting any'], 'Review, evaluate, group related ideas, select the most promising ones, and decide on a focus or thesis', 'Brainstorming produces raw material, not a plan. The next step is evaluation: which ideas are strong? Which relate to each other? Which support a central argument? This selection process shapes your focus.', 5),
  ],
  'drafting': [
    mc('What is the purpose of a first draft?', ['To produce a polished, finished piece', 'To get your ideas down on paper — imperfectly — so you have something to work with and improve', 'To finalize your argument and structure', 'To impress your reader with your initial ideas'], 'To get your ideas down on paper — imperfectly — so you have something to work with and improve', 'First drafts are supposed to be rough. Hemingway called the first draft "the first act of creation." The blank page is the enemy; a rough draft is a starting point. All good writing is rewriting.', 1),
    mc('What is the main challenge most writers face when drafting?', ['Writing too much', 'The inner critic that censors ideas before they reach the page — perfectionism that prevents getting words down', 'Choosing the right font and formatting', 'Making the draft too long'], 'The inner critic that censors ideas before they reach the page — perfectionism that prevents getting words down', 'The most common drafting problem is stopping to perfect every sentence before moving forward. This kills momentum. Write forward; fix backward — get the full draft down before you edit.', 2),
    mc('What strategy helps overcome writer\'s block during drafting?', ['Wait until inspiration strikes', 'Lower the stakes — write badly on purpose, write notes to yourself, write the easiest section first, or just write anything to start moving', 'Research more before writing anything', 'Start with the introduction, which is the most important part'], 'Lower the stakes — write badly on purpose, write notes to yourself, write the easiest section first, or just write anything to start moving', 'Writer\'s block is often perfectionism blocking imperfect output. Permission to write badly dissolves the block. Start anywhere — the middle, the easiest section. Momentum builds as you write.', 3),
    mc('Should you edit while drafting?', ['Yes — fix each sentence before moving to the next', 'Mostly no — editing interrupts flow; complete the draft first, then edit systematically', 'Yes — editing while drafting produces better first drafts', 'You should only edit after someone else reads your draft'], 'Mostly no — editing interrupts flow; complete the draft first, then edit systematically', 'Switching between drafting brain (generative, forward-moving) and editing brain (critical, backward-looking) kills momentum. Turn off spellcheck if needed. Get the draft done, then edit with a separate pass.', 4),
    mc('What makes an effective opening paragraph in a draft?', ['Starting with a dictionary definition', 'Something that hooks the reader\'s attention, establishes the topic, and (in essays) moves toward the thesis', 'Stating all your main points immediately', 'A summary of everything the essay will cover'], 'Something that hooks the reader\'s attention, establishes the topic, and (in essays) moves toward the thesis', 'Hooks can be anecdotes, surprising facts, questions, or striking statements. Many writers draft the introduction last — once you know what you\'ve written, you can write an opening that accurately leads into it.', 5),
  ],
  'revising': [
    mc('What is the difference between revising and editing?', ['They are the same thing', 'Revising changes the content, structure, and argument; editing fixes surface-level errors in language and mechanics', 'Editing changes the meaning; revising fixes grammar', 'Revising is what others do to your work; editing is what you do'], 'Revising changes the content, structure, and argument; editing fixes surface-level errors in language and mechanics', 'Revision (re-seeing) may involve cutting paragraphs, reordering sections, strengthening arguments, or adding evidence. Editing polishes what remains. Don\'t edit before you\'ve revised — you may cut what you\'ve polished.', 1),
    mc('What is the most important question to ask when revising?', ['"Is my grammar correct?"', '"Does this fulfill the assignment requirements?"', '"Does this accomplish its purpose — is my main point clear and well-supported?"', '"Is this long enough?"'], '"Does this accomplish its purpose — is my main point clear and well-supported?"', 'Before fixing sentences, check if the whole piece works. Is the thesis clear? Is it supported throughout? Is the structure logical? Fixing grammar in a structurally broken essay is wasted effort.', 2),
    mc('What does it mean to revise for clarity?', ['Making every sentence short', 'Ensuring each sentence says exactly what you mean — removing ambiguity, unnecessary complexity, and obscured meaning', 'Using simpler vocabulary throughout', 'Reducing the word count by 20%'], 'Ensuring each sentence says exactly what you mean — removing ambiguity, unnecessary complexity, and obscured meaning', 'Clarity revision asks: could this be misunderstood? Is the relationship between ideas explicit? Are pronouns clear about what they refer to? Does jargon serve the reader or obscure meaning?', 3),
    mc('Why is reading your work aloud a useful revision strategy?', ['It helps you memorize your writing', 'Your ear catches rhythm problems, run-on sentences, repetition, and awkward phrasing that your eye skips over', 'It makes the editing process faster', 'It only works for fiction, not essays'], 'Your ear catches rhythm problems, run-on sentences, repetition, and awkward phrasing that your eye skips over', 'When you read silently, your brain fills in what should be there rather than what is. Reading aloud forces you to process every word — rhythm, sound, and meaning reveal problems invisible during silent reading.', 4),
    mc('What is cutting during revision?', ['Deleting your weakest arguments entirely', 'Removing words, sentences, and sections that don\'t serve the piece — that repeat, digress, or add length without adding value', 'Reducing your essay to a shorter format', 'Deleting the draft and starting over'], 'Removing words, sentences, and sections that don\'t serve the piece — that repeat, digress, or add length without adding value', '"Kill your darlings" (Faulkner): even your favorite sentences must go if they don\'t serve the writing. Strong revision is often more about removal than addition — concise writing is almost always clearer.', 5),
  ],
  'editing-and-proofreading': [
    mc('What is proofreading?', ['A comprehensive revision of content and structure', 'A final check for surface errors — typos, spelling, punctuation, and formatting — after all content revision is complete', 'Checking that your citations are correct', 'Reading your work for the first time after a break'], 'A final check for surface errors — typos, spelling, punctuation, and formatting — after all content revision is complete', 'Proofreading is the last step before submission. It catches errors that survived revision — typos, missed words, inconsistent formatting. It should happen AFTER all substantive revision is done.', 1),
    mc('Why shouldn\'t you rely solely on spellcheck?', ['Spellcheck is usually wrong', 'Spellcheck only catches misspellings, not wrong words used correctly — "their" for "there," "from" for "form," "public" for "pubic"', 'Spellcheck slows down the writing process', 'Spellcheck doesn\'t work for academic writing'], 'Spellcheck only catches misspellings, not wrong words used correctly — "their" for "there," "from" for "form," "public" for "pubic"', 'Spellcheck can\'t tell that "The affect was dramatic" should be "The effect was dramatic" — both words are spelled correctly. Human proofreading catches errors spellcheck misses.', 2),
    mc('What strategy improves proofreading effectiveness?', ['Reading the document as fast as possible', 'Reading slowly — backward sentence by sentence, using a ruler, or reading aloud — to force your brain to see what\'s actually on the page', 'Having your computer read it aloud', 'Proofreading immediately after finishing the draft'], 'Reading slowly — backward sentence by sentence, using a ruler, or reading aloud — to force your brain to see what\'s actually on the page', 'Your brain autocorrects errors when reading forward. Reading backward isolates each sentence from context. Using a ruler forces slow line-by-line attention. These techniques defeat your brain\'s error-correction instinct.', 3),
    mc('What should you check when editing for style?', ['Only grammar and spelling', 'Wordiness, repetition, passive vs. active voice, vague language, and whether the writing matches the appropriate register for the audience', 'Whether the writing sounds like your favorite author', 'Only sentence length and variety'], 'Wordiness, repetition, passive vs. active voice, vague language, and whether the writing matches the appropriate register for the audience', 'Style editing goes beyond grammar: are you using ten words where three will do? Are you using the passive voice when active would be stronger? Is your language concrete or vague? Is the tone appropriate?', 4),
    mc('Why is it helpful to take a break before proofreading?', ['So you forget what you wrote', 'Distance gives you fresh eyes — you see what\'s actually on the page rather than what you intended to write', 'It makes the process faster', 'It only helps for long documents'], 'Distance gives you fresh eyes — you see what\'s actually on the page rather than what you intended to write', 'When you\'ve just written something, your brain supplies missing words and corrects errors automatically. After a break (or sleeping on it), you read with more objectivity — catching errors that were invisible before.', 5),
  ],
  'the-paragraph': [
    mc('What is a topic sentence?', ['The first sentence of any paragraph', 'The sentence that states the main idea of a paragraph — what the entire paragraph is about and why it matters', 'A sentence that introduces a quotation', 'The concluding sentence of a paragraph'], 'The sentence that states the main idea of a paragraph — what the entire paragraph is about and why it matters', 'The topic sentence is the paragraph\'s thesis. Every other sentence supports, explains, or proves it. It doesn\'t have to be first, but placing it first gives readers immediate orientation.', 1),
    mc('What makes a paragraph unified?', ['Having exactly five sentences', 'Every sentence relates directly to and supports the topic sentence — no digression or off-topic material', 'Starting with a topic sentence and ending with a conclusion', 'Having an equal mix of details and analysis'], 'Every sentence relates directly to and supports the topic sentence — no digression or off-topic material', 'Unity means one paragraph = one idea. If a sentence doesn\'t support the topic sentence, it either belongs in another paragraph or should be cut. Digression breaks the reader\'s focus.', 2),
    mc('What is the difference between a major supporting detail and analysis?', ['Major details are more important than analysis', 'A major detail provides evidence; analysis explains what the evidence means and why it matters to the argument', 'Analysis is what you write first; details come later', 'They are the same thing stated differently'], 'A major detail provides evidence; analysis explains what the evidence means and why it matters to the argument', 'The common error is providing evidence without explanation — assuming the evidence speaks for itself. It doesn\'t. After every quote, statistic, or example, explain: what does this show? Why does it support your point?', 3),
    mc('What is the PIE paragraph structure?', ['Point, Introduce, Explore', 'Point (topic sentence), Illustrate (evidence/example), Explain (analysis of how the illustration proves the point)', 'Preview, Include, Evaluate', 'Position, Interpret, End'], 'Point (topic sentence), Illustrate (evidence/example), Explain (analysis of how the illustration proves the point)', 'PIE is a simple framework: make your point, give evidence to illustrate it, then explain how the evidence proves your point. The "Explain" step is where most student writers fall short.', 4),
    mc('How long should a paragraph be?', ['Always 5 sentences — no more, no less', 'Long enough to fully develop the topic sentence — typically 3-8 sentences, but determined by what the idea needs, not a fixed rule', 'As short as possible for reader convenience', 'As long as possible to demonstrate thoroughness'], 'Long enough to fully develop the topic sentence — typically 3-8 sentences, but determined by what the idea needs, not a fixed rule', 'Paragraph length should match the complexity of the idea. A one-sentence paragraph emphasizes a point. A ten-sentence paragraph may be exploring a complex idea. Arbitrary length rules ignore what the writing actually needs.', 5),
  ],
  'transitions': [
    mc('What is the purpose of transitions in writing?', ['To add length to your writing', 'To show relationships between ideas and guide readers smoothly from one thought to the next', 'To begin each new paragraph with something different', 'To replace topic sentences'], 'To show relationships between ideas and guide readers smoothly from one thought to the next', 'Transitions tell readers how ideas relate: addition (furthermore), contrast (however), causation (therefore), sequence (first, then), example (for instance). Without them, readers must infer connections themselves.', 1),
    mc('Which transition best shows contrast?', ['"Furthermore"', '"However"', '"Therefore"', '"For instance"'], '"However"', 'Contrast transitions (however, nevertheless, on the other hand, conversely, yet, although) signal that the following idea contradicts or qualifies what came before. "I wanted to go; however, the weather was terrible."', 2),
    mc('Which transition best shows causation?', ['"Additionally"', '"In contrast"', '"Therefore"', '"Meanwhile"'], '"Therefore"', 'Causal transitions (therefore, thus, consequently, as a result, because of this) signal that what follows results from what came before. "She studied for weeks; therefore, she felt confident."', 3),
    mc('What is a transition between paragraphs?', ['Repeating the same idea in two consecutive paragraphs', 'A phrase or sentence that connects the ending idea of one paragraph to the opening idea of the next, showing the relationship between them', 'Starting every paragraph with "Additionally" or "Furthermore"', 'A heading that introduces the next paragraph\'s topic'], 'A phrase or sentence that connects the ending idea of one paragraph to the opening idea of the next, showing the relationship between them', 'Inter-paragraph transitions prevent the "list of paragraphs" effect. They show how your argument develops by explicitly linking one idea to the next: "This pattern of X connects to the broader question of Y..."', 4),
    mc('When can a transition word make writing worse?', ['Transition words always improve writing', 'When they\'re used mechanically without reflecting the actual relationship between ideas — padding without meaning', 'When they appear at the beginning of sentences', 'When they make paragraphs too long'], 'When they\'re used mechanically without reflecting the actual relationship between ideas — padding without meaning', '"Furthermore" used without adding anything further, or "however" when there\'s no actual contrast, creates verbal clutter. Transitions should reveal real logical relationships, not simulate them.', 5),
  ],
}
