import type { ExerciseDef } from '../types'

function mc(
  question: string,
  options: string[],
  correctAnswer: string,
  explanation: string,
  order: number
): ExerciseDef {
  return { question, type: 'MULTIPLE_CHOICE', options, correctAnswer, explanation, order }
}

export const languageExercises4: Record<string, ExerciseDef[]> = {
  'introductions-and-conclusions': [
    mc('What are the main jobs of an introduction?', ['Summarize everything the essay will say', 'Hook the reader\'s attention, provide necessary context, and present the thesis — moving from broad to specific', 'Start with a dictionary definition and end with the thesis', 'State all supporting points in order'], 'Hook the reader\'s attention, provide necessary context, and present the thesis — moving from broad to specific', 'The inverted triangle structure: start broad (the hook establishes relevance), narrow through context, arrive at the specific thesis. Readers should know your argument and why it matters before the body begins.', 1),
    mc('What makes an effective hook?', ['Starting with "According to Merriam-Webster..."', 'Something that creates interest, raises a question, or creates tension — an anecdote, striking fact, provocative question, or compelling statement', 'Restating the essay prompt', 'Beginning with "In today\'s society..."'], 'Something that creates interest, raises a question, or creates tension — an anecdote, striking fact, provocative question, or compelling statement', 'Avoid clichés: dictionary definitions, "Since the dawn of time," "In today\'s society." Effective hooks create genuine curiosity or connection. The hook earns attention; the context keeps it; the thesis directs it.', 2),
    mc('What is the purpose of a conclusion?', ['To repeat the introduction with different words', 'To synthesize the essay\'s argument, show its significance, and provide a sense of closure — looking beyond the essay itself', 'To summarize each body paragraph in order', 'To apologize for any weaknesses in the argument'], 'To synthesize the essay\'s argument, show its significance, and provide a sense of closure — looking beyond the essay itself', 'A conclusion synthesizes (shows how pieces fit together) rather than summarizing (lists them again). The best conclusions answer "so what?" — why does this argument matter beyond the page?', 3),
    mc('What should a strong conclusion NOT do?', ['Reference the thesis', 'Introduce significant new evidence or arguments that should have been in the body', 'Broaden out to the topic\'s larger significance', 'Create a sense of closure'], 'Introduce significant new evidence or arguments that should have been in the body', 'Introducing a major new point in the conclusion confuses readers — it should have been developed in the body. Minor new ideas or a forward-looking statement are acceptable; major arguments are not.', 4),
    mc('What is the "bookending" technique in introductions and conclusions?', ['Using the same length for intro and conclusion', 'Returning to the hook\'s image, idea, or story in the conclusion — creating structural unity by closing the circle you opened', 'Starting and ending with quotations', 'Using the same transition words in both'], 'Returning to the hook\'s image, idea, or story in the conclusion — creating structural unity by closing the circle you opened', 'If your introduction opens with an anecdote, returning to it in the conclusion (with new understanding from the essay) creates elegant closure. Readers feel the essay\'s journey is complete.', 5),
  ],
  'expository-essays': [
    mc('What is the primary purpose of an expository essay?', ['To argue for a specific position', 'To explain, inform, or describe a topic clearly and objectively — not to argue or persuade', 'To tell a personal story', 'To describe a scene or experience vividly'], 'To explain, inform, or describe a topic clearly and objectively — not to argue or persuade', 'Expository writing informs the reader about a topic: compare/contrast, cause/effect, process analysis, classification. The goal is understanding, not agreement. Objectivity and clarity are primary virtues.', 1),
    mc('What is a compare/contrast essay?', ['An essay that only lists differences between two things', 'An essay analyzing the similarities and differences between two subjects to reveal something meaningful about both', 'An essay comparing your opinion to others\'', 'A type of argumentative essay'], 'An essay analyzing the similarities and differences between two subjects to reveal something meaningful about both', 'Compare/contrast essays don\'t just list differences — they analyze what those similarities and differences reveal. Two organizational patterns: block (all of A, then all of B) or point-by-point (alternate A and B on each point).', 2),
    mc('What is a cause/effect essay?', ['An essay proving something caused something else', 'An essay exploring why something happened (causes) and/or what resulted from it (effects)', 'An essay about historical events and their aftermath', 'An argument that one variable causes another'], 'An essay exploring why something happened (causes) and/or what resulted from it (effects)', 'Cause/effect essays can focus on causes, effects, or both. The challenge: avoiding oversimplification (most events have multiple causes) and avoiding confusing correlation with causation.', 3),
    mc('What is a process analysis essay?', ['An analysis of a business process', 'An essay explaining how something works or how to do something — in sequential steps the reader can follow', 'An essay critiquing a process for its flaws', 'A scientific paper documenting research methodology'], 'An essay explaining how something works or how to do something — in sequential steps the reader can follow', 'Process essays (how to bake bread, how photosynthesis works, how a bill becomes a law) require clear sequential organization, precise language, and appropriate level of detail for the intended audience.', 4),
    mc('What makes expository writing effective?', ['Strong emotional language and personal opinions', 'Clear organization, accurate information, precise language, and appropriate depth for the audience\'s knowledge level', 'Taking a strong position and defending it', 'Long paragraphs demonstrating thorough knowledge'], 'Clear organization, accurate information, precise language, and appropriate depth for the audience\'s knowledge level', 'Expository writing serves the reader\'s understanding. Clarity comes before elegance. Definitions of unfamiliar terms, logical sequencing, and examples appropriate to the reader\'s background are essential.', 5),
  ],
  'argumentative-essays': [
    mc('What is a thesis statement in an argumentative essay?', ['A statement of the topic you\'re writing about', 'A specific, debatable claim that your essay will prove through evidence and reasoning', 'The main question your essay is asking', 'A summary of the essay\'s main points'], 'A specific, debatable claim that your essay will prove through evidence and reasoning', 'A strong thesis is: specific (not vague), arguable (someone could reasonably disagree), and significant (worth arguing). "Social media has drawbacks" is weak — vague and obvious. "Social media\'s algorithmic design has measurably increased teen depression" is strong.', 1),
    mc('What is a counterargument in an argumentative essay?', ['An argument that disproves your thesis', 'An opposing view that you acknowledge and then refute — demonstrating you\'ve engaged seriously with the strongest objections', 'A concession that your argument is wrong', 'An argument that supports a different thesis than yours'], 'An opposing view that you acknowledge and then refute — demonstrating you\'ve engaged seriously with the strongest objections', 'Including counterarguments makes your argument stronger, not weaker. It shows you\'ve thought beyond your own position and can be trusted. The structure: acknowledge the opposing view, then explain why your position still holds.', 2),
    mc('What is a concession in argumentation?', ['Giving up your argument entirely', 'Acknowledging that an opposing point has merit or that your position has limits — before explaining why your overall argument still stands', 'Agreeing with the counterargument you\'ve presented', 'Admitting that you don\'t have enough evidence'], 'Acknowledging that an opposing point has merit or that your position has limits — before explaining why your overall argument still stands', '"While it\'s true that X presents a challenge to my argument, this is outweighed by Y because..." Conceding what\'s true in opposing views while maintaining your overall position demonstrates intellectual honesty.', 3),
    mc('What type of evidence is generally strongest in argumentative essays?', ['Personal anecdotes and emotional stories', 'Peer-reviewed research, verifiable data, and expert consensus in the relevant field', 'Quotations from famous people', 'Historical examples that are very old'], 'Peer-reviewed research, verifiable data, and expert consensus in the relevant field', 'Evidence hierarchy: empirical research > expert consensus > statistics (from credible sources) > expert opinion > anecdote. Emotional appeals can support logical evidence but shouldn\'t replace it in academic argument.', 4),
    mc('What does it mean to "warrant" your evidence?', ['Finding legitimate sources', 'Explicitly explaining the logical connection between your evidence and your claim — why this evidence proves your point', 'Having evidence from multiple sources', 'Citing your sources in proper format'], 'Explicitly explaining the logical connection between your evidence and your claim — why this evidence proves your point', 'The warrant is the unstated assumption connecting evidence to claim. Making it explicit strengthens the argument. "This statistic shows X; this matters because it demonstrates Y, which proves my claim that Z."', 5),
  ],
  'narrative-essays': [
    mc('What distinguishes a narrative essay from a memoir or autobiography?', ['Narrative essays are always fictional', 'A narrative essay uses personal story to illustrate a broader point or insight — it\'s not just "what happened" but "what it means"', 'Narrative essays must be short', 'There is no meaningful difference'], 'A narrative essay uses personal story to illustrate a broader point or insight — it\'s not just "what happened" but "what it means"', 'Narrative essays have a thesis — even if implicit. The story exists to demonstrate something. "Here\'s what happened" is diary writing. "Here\'s what happened, and here\'s what it reveals about X" is a narrative essay.', 1),
    mc('What is scene vs. summary in narrative writing?', ['Scene is longer; summary is shorter', 'Scene shows moments in detail with dialogue and action; summary compresses time and covers background or transitions quickly', 'Summary is for nonfiction; scene is for fiction', 'There is no useful distinction'], 'Scene shows moments in detail with dialogue and action; summary compresses time and covers background or transitions quickly', 'Master writers control the ratio: slow down (scene) for the most important moments; speed up (summary) through transitions and background. The pivotal moments of your story should be scenes, not summaries.', 2),
    mc('What is "showing vs. telling" in narrative writing?', ['A preference for using examples over statements', 'Showing depicts events through concrete detail, action, and dialogue; telling states conclusions directly — strong narrative writing prefers showing', 'Telling is acceptable; showing is never appropriate', 'They are equally valid choices with no preference'], 'Showing depicts events through concrete detail, action, and dialogue; telling states conclusions directly — strong narrative writing prefers showing', '"She was nervous" (telling). "Her hands wouldn\'t stop shaking and she kept re-reading the last line of the email" (showing). Showing invites readers to feel and conclude; telling reports and distances.', 3),
    mc('What is narrative tension?', ['Arguments between characters in the story', 'The uncertainty or conflict that makes readers want to know what happens next — created by unresolved questions, obstacles, or competing desires', 'The emotional intensity of the narration style', 'Conflict between the narrator and the reader'], 'The uncertainty or conflict that makes readers want to know what happens next — created by unresolved questions, obstacles, or competing desires', 'Tension = dramatic question + obstacles. Even personal essays need tension: will the narrator figure this out? Overcome this? Make the right choice? Without tension, there\'s nothing to pull readers forward.', 4),
    mc('What makes a narrative essay\'s ending effective?', ['Summarizing the main events of the story', 'Revealing a moment of insight or transformation — showing how the narrator or situation changed — that gives the story meaning', 'Ending at the story\'s most exciting moment', 'Ending exactly where the story began'], 'Revealing a moment of insight or transformation — showing how the narrator or situation changed — that gives the story meaning', 'Narrative endings should land on meaning, not just conclusion. The reader should feel that something has been understood or changed — that the journey of the essay was worth making.', 5),
  ],
  'descriptive-essays': [
    mc('What is the primary purpose of a descriptive essay?', ['To argue for a position using evidence', 'To evoke a vivid sensory experience in the reader\'s mind — to make them see, hear, feel, taste, or smell what you\'re describing', 'To explain how something works', 'To tell a story with a clear plot'], 'To evoke a vivid sensory experience in the reader\'s mind — to make them see, hear, feel, taste, or smell what you\'re describing', 'Descriptive writing aims for immersion. The reader should experience the subject through the writing. Success is measured by whether the description is so specific and sensory that readers feel they\'re there.', 1),
    mc('What is the role of sensory detail in descriptive writing?', ['Sensory details are only for creative fiction', 'Specific sensory details (sight, sound, smell, taste, touch) anchor description in physical reality and create vivid reader experience', 'Only visual details matter in descriptive writing', 'Sensory details are decorative additions to the main content'], 'Specific sensory details (sight, sound, smell, taste, touch) anchor description in physical reality and create vivid reader experience', '"A busy kitchen" is vague. "The sizzle of butter hitting the pan, the sharp smell of garlic, the metallic clatter of pans against the industrial stove" is sensory — it transports the reader.', 2),
    mc('What is a dominant impression in descriptive writing?', ['The most important detail in the description', 'The overall mood, feeling, or main quality that the entire description is designed to convey', 'The first thing described in the essay', 'The most surprising detail included'], 'The overall mood, feeling, or main quality that the entire description is designed to convey', 'Descriptive writing needs a controlling idea — not just a random collection of details. Every detail should contribute to the dominant impression: eerie, joyful, chaotic, peaceful. Details that contradict it should be cut.', 3),
    mc('What is figurative language and why is it used in descriptive writing?', ['Incorrect language used for artistic effect', 'Language that describes one thing in terms of another (metaphor, simile, personification) — making the unfamiliar vivid by comparison to the familiar', 'Exaggerated language to make things sound more impressive', 'Formal, technical language for precise description'], 'Language that describes one thing in terms of another (metaphor, simile, personification) — making the unfamiliar vivid by comparison to the familiar', '"The fog was thick" is literal. "The fog moved like a slow exhale" is figurative — it brings the reader\'s knowledge of breath to bear on understanding the fog. Figurative language creates meaning through connection.', 4),
    mc('What is the difference between objective and subjective description?', ['Objective description is always better', 'Objective describes observable facts; subjective includes feelings, interpretations, and personal responses to the subject', 'Subjective means fictional; objective means factual', 'They are the same thing stated from different angles'], 'Objective describes observable facts; subjective includes feelings, interpretations, and personal responses to the subject', '"The walls are blue and 10 feet high" is objective. "The walls felt like they were closing in" is subjective. Effective descriptive writing often blends both — grounding subjective impression in objective detail.', 5),
  ],
  'finding-sources': [
    mc('What makes a source credible?', ['It agrees with your thesis', 'It has a clear author with relevant expertise, transparent methodology, is published in a reputable venue, and can be verified', 'It appears on the first page of Google results', 'It is available for free online'], 'It has a clear author with relevant expertise, transparent methodology, is published in a reputable venue, and can be verified', 'Credibility indicators: named, qualified author; peer-reviewed or reputable publication; clear, verifiable evidence; recent publication (for rapidly changing topics); no significant conflicts of interest.', 1),
    mc('What is a peer-reviewed journal article?', ['Any academic article available online', 'Research reviewed and approved by other experts in the field before publication — the gold standard for academic evidence', 'A journal article that has been cited many times', 'An article written by multiple authors'], 'Research reviewed and approved by other experts in the field before publication — the gold standard for academic evidence', 'Peer review means independent experts in the field evaluated the methodology and conclusions before publication. It\'s imperfect but the best filter for academic quality. Databases like JSTOR, PubMed, and Google Scholar index peer-reviewed work.', 2),
    mc('What is the difference between a primary and secondary source in research?', ['Primary sources are always more reliable', 'Primary sources are original materials (data, documents, firsthand accounts); secondary sources analyze or interpret primary sources', 'Secondary sources are more useful for research', 'They differ only in age — primary sources are older'], 'Primary sources are original materials (data, documents, firsthand accounts); secondary sources analyze or interpret primary sources', 'The CDC\'s raw COVID data is a primary source; a news article analyzing it is secondary. A historical diary is primary; a history textbook is secondary. Both are valuable for different purposes.', 3),
    mc('What is the problem with using Wikipedia as a research source?', ['Wikipedia is always wrong', 'Wikipedia can be edited by anyone and may contain errors — it\'s a starting point for research, not a citable source; use its references to find primary sources', 'Wikipedia is too academic for most research', 'Wikipedia only covers popular topics'], 'Wikipedia can be edited by anyone and may contain errors — it\'s a starting point for research, not a citable source; use its references to find primary sources', 'Wikipedia\'s References section often contains excellent primary and secondary sources. Use Wikipedia to understand a topic and find those sources — then cite the original source, not Wikipedia.', 4),
    mc('What does "evaluating sources laterally" mean in research?', ['Reading a source from beginning to end before evaluating it', 'Checking what others say about a source before trusting its content — looking it up in other places rather than reading deeply into it first', 'Only using sources from your own field', 'Comparing two sources on the same topic'], 'Checking what others say about a source before trusting its content — looking it up in other places rather than reading deeply into it first', 'Before spending time reading a source deeply, check: who publishes this? What do other sources say about it? A quick lateral search can reveal that a source is unreliable before you waste time with its content.', 5),
  ],
  'using-evidence': [
    mc('What are the three main ways to incorporate source material?', ['Summarize, simplify, and quote', 'Direct quotation (exact words), paraphrase (your words, same idea), and summary (condensed version of larger section)', 'Copy, paste, and cite', 'Translate, interpret, and include'], 'Direct quotation (exact words), paraphrase (your words, same idea), and summary (condensed version of larger section)', 'Each serves different purposes: quote when the exact words matter; paraphrase when the idea matters more than phrasing; summarize when you need the gist of a longer source. All three require citation.', 1),
    mc('What is a direct quotation and when should you use it?', ['Using someone else\'s words without citation', 'Using a source\'s exact words in quotation marks — most appropriate when the precise wording is significant or uniquely well-expressed', 'Paraphrasing in your own words', 'Any reference to someone else\'s ideas'], 'Using a source\'s exact words in quotation marks — most appropriate when the precise wording is significant or uniquely well-expressed', 'Use direct quotes sparingly — when the exact words matter (legal documents, famous speeches, striking phrasing). Don\'t quote when a paraphrase would serve just as well; your voice should dominate the essay.', 2),
    mc('What is the difference between quoting and plagiarizing?', ['Plagiarizing means using bad sources', 'Quoting means using someone\'s words with proper attribution and quotation marks; plagiarizing means presenting someone\'s work as your own without attribution', 'Plagiarism only applies to copying entire essays', 'There is no difference — both use others\' words'], 'Quoting means using someone\'s words with proper attribution and quotation marks; plagiarizing means presenting someone\'s work as your own without attribution', 'Even paraphrasing without citation is plagiarism. You must attribute ideas, not just exact words. Citation is the mechanism that makes using sources ethical and academically honest.', 3),
    mc('What is a "dropped quote"?', ['A quotation that falls in the middle of a paragraph', 'A quotation inserted without introduction, context, or explanation — floating without connection to your argument', 'A quotation from an unreliable source', 'A very short quotation of one or two words'], 'A quotation inserted without introduction, context, or explanation — floating without connection to your argument', '"Studies show learning is important. \'The brain adapts to repeated stimuli\' (Smith, 2020). This affects education." The quote is dropped in without attribution or explanation. Introduce who said it and why it matters.', 4),
    mc('What does it mean to "sandwich" a quotation?', ['Putting quotes in the middle of paragraphs only', 'Introducing the source and context before the quote, then following with explanation of what it shows — intro, quote, analysis', 'Using short quotes between long paragraphs', 'Only quoting in the middle of sentences'], 'Introducing the source and context before the quote, then following with explanation of what it shows — intro, quote, analysis', 'The quote sandwich: "Smith argues that [CONTEXT]. As she explains, \'[QUOTATION]\' (Smith, p. 45). This demonstrates [ANALYSIS]." Never let a quote speak for itself — always explain what it proves.', 5),
  ],
}
