import type { AssessmentDef, AssessmentQuestionDef } from '../types'

const mc = (q: string, opts: string[], ans: string, exp: string, pts: number, ord: number): AssessmentQuestionDef =>
  ({ question: q, type: 'MULTIPLE_CHOICE', options: opts, correctAnswer: ans, explanation: exp, points: pts, order: ord })

const oe = (q: string, ans: string, exp: string, pts: number, ord: number): AssessmentQuestionDef =>
  ({ question: q, type: 'OPEN_ENDED', correctAnswer: ans, explanation: exp, points: pts, order: ord })

export const languageAssessments: Record<string, AssessmentDef> = {
  'reading-comprehension': {
    title: 'Reading Comprehension Assessment',
    passingScore: 75,
    timeLimitMin: 30,
    questions: [
      mc('What is the main idea of a passage?', ['The first sentence', 'The central point or argument the author is making throughout the text', 'A supporting detail that repeats', 'The conclusion paragraph only'], 'The central point or argument the author is making throughout the text', 'The main idea is the overarching message — what the text is fundamentally about. It\'s broader than any single detail and is supported throughout.', 1, 1),
      mc('What is an inference?', ['A direct quote from the text', 'A conclusion drawn using text evidence plus prior knowledge — reading between the lines', 'A summary of the passage', 'An opinion the author states directly'], 'A conclusion drawn using text evidence plus prior knowledge — reading between the lines', 'Inferences go beyond what is stated — you combine what the text says with what you know to reach a logical conclusion the author implies but doesn\'t state.', 1, 2),
      mc('What is the difference between a fact and an opinion in a text?', ['Facts are longer; opinions are shorter', 'Facts can be verified objectively; opinions express personal judgments or beliefs', 'Opinions use numbers; facts use adjectives', 'They are the same if the author states both confidently'], 'Facts can be verified objectively; opinions express personal judgments or beliefs', 'Facts are verifiable claims ("The bill passed 55-45"). Opinions are judgments ("The bill was the worst legislation in a decade"). Reading critically requires distinguishing these.', 1, 3),
      mc('What is the author\'s purpose?', ['The topic of the passage', 'The reason the author wrote the text — to inform, persuade, entertain, or describe', 'The thesis statement', 'The conclusion of the passage'], 'The reason the author wrote the text — to inform, persuade, entertain, or describe', 'Identifying purpose helps you interpret tone and evaluate the text critically. Persuasive texts require more skepticism than purely informational ones.', 1, 4),
      mc('What is context clues?', ['A dictionary definition in the text', 'Information in the surrounding text that helps figure out an unfamiliar word\'s meaning', 'Footnotes and glossaries', 'The title and headings'], 'Information in the surrounding text that helps figure out an unfamiliar word\'s meaning', 'Context clues include synonyms, antonyms, examples, and explanations near an unfamiliar word that let you infer its meaning without a dictionary.', 1, 5),
      mc('What does it mean to "read actively"?', ['Reading as fast as possible', 'Engaging with the text by questioning, annotating, predicting, and connecting', 'Reading out loud', 'Re-reading every paragraph twice'], 'Engaging with the text by questioning, annotating, predicting, and connecting', 'Active reading is purposeful engagement: asking questions, underlining key points, noting unfamiliar terms, connecting to what you know. Passive reading often leads to poor retention.', 1, 6),
      mc('What is a primary source?', ['The most reliable source on a topic', 'An original document, artifact, or firsthand account from the time period being studied', 'A textbook summary', 'A peer-reviewed journal article'], 'An original document, artifact, or firsthand account from the time period being studied', 'Primary sources are firsthand — diaries, speeches, photos, original research, eyewitness accounts. Secondary sources analyze or interpret primary sources.', 1, 7),
      mc('What is the difference between skimming and scanning?', ['They are the same technique', 'Skimming gets a general overview; scanning looks for specific information', 'Scanning reads everything; skimming skips paragraphs', 'Skimming is for fiction; scanning for non-fiction'], 'Skimming gets a general overview; scanning looks for specific information', 'Skim to get the gist of a passage (read opening, topic sentences, conclusion). Scan to find a specific fact, name, or date without reading everything.', 1, 8),
      oe('Describe a strategy you would use to identify the main idea of a complex multi-paragraph article.', 'Strategy: Read the title and any subheadings first. Read the first and last paragraph fully. Read the first sentence of each body paragraph (topic sentences state each paragraph\'s supporting point). Identify what thread runs through all the topic sentences — that\'s typically the main idea. Summarize the article in one sentence to test your understanding.', 'A strong answer gives specific, actionable steps — not just "read carefully and find the main point."', 2, 9),
      oe('Why is it important to consider an author\'s potential bias or purpose when reading persuasive text?', 'Every writer has a perspective, and persuasive text is designed to move you toward a conclusion. Without awareness of bias, you may accept one-sided evidence as complete truth, confuse emotional appeals with logical arguments, or miss alternative views entirely. Understanding who wrote something, for what audience, and for what purpose helps you evaluate claims critically rather than accepting them passively.', 'A strong answer explains that awareness of bias protects against manipulation and enables critical evaluation — not just "authors can be wrong."', 2, 10),
    ],
  },

  'grammar-and-mechanics': {
    title: 'Grammar and Mechanics Assessment',
    passingScore: 75,
    timeLimitMin: 30,
    questions: [
      mc('What is a clause?', ['Any group of words', 'A group of words containing a subject and a verb', 'A sentence ending with a period', 'A dependent phrase without a verb'], 'A group of words containing a subject and a verb', 'Clauses have both a subject and a predicate. Independent clauses can stand alone; dependent clauses cannot.', 1, 1),
      mc('What is a comma splice?', ['Using a comma after an introductory phrase', 'Joining two independent clauses with only a comma, creating a run-on sentence', 'Using too many commas in a list', 'A comma before the word "and"'], 'Joining two independent clauses with only a comma, creating a run-on sentence', 'Comma splices: "I went to the store, I bought milk." Fix with: a period, semicolon, or coordinating conjunction with the comma.', 1, 2),
      mc('Which sentence is grammatically correct?', ['Him and I went to the store.', 'She gave the award to John and I.', 'Between you and me, this is wrong.', 'Between you and I, this is right.'], 'Between you and me, this is wrong.', '"Between" is a preposition requiring object pronouns (me, him, her) not subject pronouns (I, he, she). "Between you and me" is always correct.', 1, 3),
      mc('What is the difference between active and passive voice?', ['Active uses "to be" verbs; passive does not', 'Active: subject performs the action; passive: subject receives the action', 'Passive voice is always incorrect', 'They are interchangeable with no difference in meaning'], 'Active: subject performs the action; passive: subject receives the action', 'Active: "The dog bit the man." Passive: "The man was bitten by the dog." Active is usually clearer and more direct; passive is useful when the doer is unknown or unimportant.', 1, 4),
      mc('When should you use "its" vs. "it\'s"?', ['"Its" is always possessive; "it\'s" is only formal', '"It\'s" is a contraction of "it is" or "it has"; "its" is possessive', 'They are interchangeable', '"Its" is plural; "it\'s" is singular'], '"It\'s" is a contraction of "it is" or "it has"; "its" is possessive', 'It\'s = It is (or It has). Its = belonging to it. Test: if you can replace it with "it is," use it\'s. "Its" needs no apostrophe because possessive pronouns never do.', 1, 5),
      mc('What is parallel structure?', ['Repeating the same word multiple times', 'Using the same grammatical form for elements in a list or comparison', 'Having equal-length sentences', 'Using symmetrical paragraphs'], 'Using the same grammatical form for elements in a list or comparison', 'Parallel structure: "She likes swimming, hiking, and to cook" is wrong. "She likes swimming, hiking, and cooking" is parallel — all gerunds.', 1, 6),
      mc('What is a dangling modifier?', ['An adjective placed after the noun', 'A modifying phrase that doesn\'t clearly attach to the word it\'s meant to modify', 'An adverb at the end of a sentence', 'A clause beginning with "which"'], 'A modifying phrase that doesn\'t clearly attach to the word it\'s meant to modify', 'Dangling modifier: "Running down the street, the dog bit my ankle." Who was running? Fix: "As I ran down the street, the dog bit my ankle."', 1, 7),
      mc('Where does the comma go in a compound sentence with a coordinating conjunction?', ['After the conjunction', 'Before the conjunction', 'No comma needed', 'After the second clause'], 'Before the conjunction', 'In compound sentences: "I went to the store, and I bought milk." The comma precedes the coordinating conjunction (FANBOYS: for, and, nor, but, or, yet, so) when joining two independent clauses.', 1, 8),
      oe('Correct and explain the errors in this sentence: "The committee gave the award to John and I, whom worked tirelessly on the project."', 'Two errors: (1) "John and I" should be "John and me" — it\'s the object of the preposition "to," requiring an object pronoun. (2) "whom" should be "who" — "who worked tirelessly" is a subject relative clause, requiring the subject pronoun "who." Corrected: "The committee gave the award to John and me, who worked tirelessly on the project."', 'A complete answer identifies both errors, names the grammatical rule for each, and provides the corrected sentence.', 2, 9),
      oe('Why does grammar matter in professional writing, and when is it acceptable to break the rules?', 'Grammar matters professionally because errors undermine credibility — readers judge competence by writing quality. In formal contexts (resumes, business emails, legal documents), errors signal carelessness. Rules can be broken intentionally for effect in creative writing or informal contexts: fragments for emphasis, starting sentences with "and" or "but" for rhythm, colloquial language to match audience tone. The key is intentionality — know the rules before breaking them.', 'A strong answer distinguishes formal vs. informal contexts and frames rule-breaking as intentional and purposeful — not just acceptable generally.', 2, 10),
    ],
  },

  'writing-fundamentals': {
    title: 'Writing Fundamentals Assessment',
    passingScore: 75,
    timeLimitMin: 30,
    questions: [
      mc('What is a thesis statement?', ['The first sentence of any paragraph', 'The central claim or argument of a piece of writing, usually in the introduction', 'A summary of all main points', 'A quote that introduces the topic'], 'The central claim or argument of a piece of writing, usually in the introduction', 'A strong thesis states your position and previews what you\'ll argue or explore. It\'s the commitment you make to the reader about what the essay will prove.', 1, 1),
      mc('What is the purpose of a topic sentence?', ['To transition between paragraphs', 'To state the main idea of a paragraph and connect it to the thesis', 'To provide evidence for a claim', 'To introduce a quotation'], 'To state the main idea of a paragraph and connect it to the thesis', 'Each body paragraph needs a topic sentence that announces its specific supporting point — guiding the reader and maintaining focus.', 1, 2),
      mc('What does "showing vs. telling" mean in writing?', ['Using more words vs. fewer', 'Providing specific sensory details that evoke an experience (showing) vs. stating it plainly (telling)', 'Writing in second person vs. third person', 'Using dialogue vs. narration'], 'Providing specific sensory details that evoke an experience (showing) vs. stating it plainly (telling)', '"He was angry" is telling. "His hands clenched the desk until his knuckles went white" is showing. Strong writing puts readers in the scene rather than summarizing what happened.', 1, 3),
      mc('What is voice in writing?', ['The grammatical person (first, second, third)', 'The distinctive personality, style, and tone that makes a writer\'s work recognizable', 'Whether the text uses active or passive voice', 'The narrator\'s perspective in fiction'], 'The distinctive personality, style, and tone that makes a writer\'s work recognizable', 'Voice is what makes one writer\'s work sound distinct from another\'s — their word choices, rhythm, humor, directness, and perspective. Developing voice takes practice.', 1, 4),
      mc('What is the purpose of a revision?', ['Fixing spelling and grammar errors only', 'Improving content, organization, clarity, and persuasiveness — often rethinking large sections', 'Formatting the document correctly', 'Adding more length to reach a word count'], 'Improving content, organization, clarity, and persuasiveness — often rethinking large sections', 'Revision means re-seeing the writing as a whole. Proofreading is surface-level; revision is structural — asking whether the argument is clear, evidence is sufficient, and organization serves the purpose.', 1, 5),
      mc('What is a writing prompt response\'s most important element?', ['Using the most sophisticated vocabulary', 'Directly addressing what the prompt asks with a clear, supported answer', 'Having the most paragraphs', 'Starting with a rhetorical question'], 'Directly addressing what the prompt asks with a clear, supported answer', 'Prompt response: answer what\'s asked. Many writing problems stem from addressing a related but different question — or burying the answer under too much introduction.', 1, 6),
      mc('What is the difference between paraphrasing and plagiarism?', ['Paraphrasing uses synonyms only', 'Paraphrasing restates another\'s idea in your own words with attribution; plagiarism presents another\'s work as your own', 'Plagiarism is only copying exact words', 'There is no difference if you cite the source'], 'Paraphrasing restates another\'s idea in your own words with attribution; plagiarism presents another\'s work as your own', 'Proper paraphrase involves genuine restatement (not just word substitution) plus a citation. Even paraphrase without credit is plagiarism.', 1, 7),
      mc('What makes a conclusion effective?', ['Simply restating the introduction word-for-word', 'Synthesizing key points, reinforcing the thesis, and leaving the reader with something to consider', 'Introducing new arguments', 'Ending with a question'], 'Synthesizing key points, reinforcing the thesis, and leaving the reader with something to consider', 'Strong conclusions do more than summarize — they show how the argument adds up, reinforce the "so what," and give the reader a sense of completion or a lasting idea.', 1, 8),
      oe('Write a strong thesis statement for an essay arguing that social media has had more negative than positive effects on teenagers.', 'Example: "While social media provides teenagers with unprecedented connectivity and access to information, its documented effects on mental health, sleep, and social comparison cause measurable harm that outweighs its benefits." A strong thesis takes a clear position, acknowledges complexity (the counterargument), and signals the essay\'s scope.', 'A strong answer takes a clear, arguable position (not just "social media has effects"), includes nuance, and previews the direction of the argument.', 2, 9),
      oe('Why do professional writers do multiple drafts instead of trying to get it right the first time?', 'First drafts are for getting ideas down — premature editing interrupts creative flow and produces nothing. Revision allows distance: coming back later, you see what\'s actually on the page instead of what you intended. Multiple passes let you address different concerns separately: structure first, then argument, then paragraphs, then sentences, then proofreading. The best writing almost always emerges through revision, not first attempts.', 'A strong answer explains the separation of generation and evaluation, the value of distance, and the layered revision approach.', 2, 10),
    ],
  },

  'essay-writing': {
    title: 'Essay Writing Assessment',
    passingScore: 75,
    timeLimitMin: 30,
    questions: [
      mc('What is the purpose of an argumentative essay?', ['To tell a story', 'To make a claim and support it with evidence to persuade the reader', 'To describe a process', 'To compare two subjects'], 'To make a claim and support it with evidence to persuade the reader', 'Argumentative essays stake out a position and marshal logic, evidence, and reasoning to convince readers — not just share information but advocate for a conclusion.', 1, 1),
      mc('What is a counterargument and why should you include one?', ['An argument from the opposing team', 'Acknowledging and responding to the strongest objection to your position — showing you\'ve considered multiple perspectives', 'An argument that contradicts itself', 'A paragraph summarizing what others have said'], 'Acknowledging and responding to the strongest objection to your position — showing you\'ve considered multiple perspectives', 'Including and rebutting counterarguments strengthens credibility — it shows intellectual honesty and makes your position more convincing than if you\'d ignored obvious objections.', 1, 2),
      mc('What is a rhetorical appeal?', ['A technique for grammar correction', 'One of three persuasive strategies: ethos (credibility), pathos (emotion), logos (logic)', 'A question posed to the reader', 'A type of transitional phrase'], 'One of three persuasive strategies: ethos (credibility), pathos (emotion), logos (logic)', 'Aristotle identified three appeals: ethos (establishing credibility), pathos (engaging emotions), logos (using reason and evidence). Effective persuasion uses all three.', 1, 3),
      mc('What is a compare-and-contrast essay?', ['An essay arguing one position over another', 'An essay that examines similarities and differences between two subjects', 'An essay explaining how something works', 'An essay about a personal experience'], 'An essay that examines similarities and differences between two subjects', 'Compare-contrast essays examine two subjects together to illuminate both more clearly. They can be organized point-by-point or subject-by-subject.', 1, 4),
      mc('What is the PIE paragraph structure?', ['Position, Illustration, Explanation', 'Point, Illustration, Explanation — state a point, provide evidence, explain the connection', 'Paragraph, Introduction, Essay', 'Premise, Inference, Evaluation'], 'Point, Illustration, Explanation — state a point, provide evidence, explain the connection', 'PIE is a body paragraph framework: Point (topic sentence), Illustration (evidence/quote), Explanation (how the evidence supports your point). The explanation is often the weakest part for novice writers.', 1, 5),
      mc('What is a transitional phrase used for?', ['To introduce new evidence', 'To connect ideas and show the logical relationship between sentences and paragraphs', 'To conclude the essay', 'To introduce the counterargument'], 'To connect ideas and show the logical relationship between sentences and paragraphs', 'Transitions (furthermore, however, consequently, in contrast) signal how ideas relate — adding, contrasting, giving examples, showing causation — and guide the reader through the argument.', 1, 6),
      mc('What is the correct citation format called in most academic writing?', ['Harvard format only', 'It varies — MLA, APA, Chicago, and others are used in different disciplines', 'APA is used universally', 'Citation format doesn\'t matter as long as you include sources'], 'It varies — MLA, APA, Chicago, and others are used in different disciplines', 'Citation style varies by discipline: MLA for humanities, APA for social sciences and science, Chicago for history. Always use the format your instructor or publication requires.', 1, 7),
      mc('What is a synthesis essay?', ['A summary of a single source', 'An essay that draws on multiple sources to develop an original argument or perspective', 'A personal narrative with cited sources', 'A scientific report'], 'An essay that draws on multiple sources to develop an original argument or perspective', 'Synthesis essays don\'t just summarize sources — they connect, compare, and integrate them to support an original argument, showing how sources relate to each other and the central claim.', 1, 8),
      oe('What makes the difference between a weak and a strong argumentative essay? List at least three factors.', 'Strong argumentative essays: (1) have a clear, specific, arguable thesis — not just a topic statement; (2) use credible, relevant evidence — not just opinions; (3) explain how evidence connects to the claim (analysis, not just quotations); (4) address and rebut counterarguments honestly; (5) use clear organization so the reader follows the logic; (6) conclude with synthesis that reinforces the argument\'s significance.', 'A strong answer names concrete elements — thesis specificity, evidence quality, analysis depth, counterargument handling — not vague advice like "be clear."', 2, 9),
      oe('Why is the "so what?" question so important in essay writing?', '"So what?" asks why your argument matters beyond the page — what\'s the broader significance, implication, or consequence. An essay that proves its point but never answers "so what?" feels hollow. The most memorable essays connect their specific argument to something larger: a broader principle, a real-world consequence, a shift in how we should think about something. "So what?" transforms a completed argument into a meaningful one.', 'A strong answer explains that "so what?" addresses significance and stakes, and shows that the essay matters beyond just being right.', 2, 10),
    ],
  },

  'practical-writing': {
    title: 'Practical Writing Assessment',
    passingScore: 75,
    timeLimitMin: 30,
    questions: [
      mc('What is the most important element of a professional email?', ['A formal greeting and closing', 'A clear subject line that tells the recipient exactly what the email is about', 'Formal language throughout', 'Attaching relevant documents'], 'A clear subject line that tells the recipient exactly what the email is about', 'Subject lines determine whether emails get opened and when. "Quick question" is useless; "Request for invoice #2847 approval by Friday" gives everything needed.', 1, 1),
      mc('What should a professional resume prioritize?', ['Listing every job you\'ve ever had', 'Relevant experience, specific accomplishments with measurable results, and tailoring to the specific job', 'An objective statement at the top', 'A photo and personal information'], 'Relevant experience, specific accomplishments with measurable results, and tailoring to the specific job', 'Strong resumes highlight what matters for the specific role, use numbers to quantify impact ("increased sales by 30%"), and are tailored rather than generic.', 1, 2),
      mc('What is the tone of a cover letter?', ['Desperate and enthusiastic', 'Confident and professional — showing specific knowledge of the company and why you\'re a fit', 'Casual and conversational', 'Identical to the resume in format'], 'Confident and professional — showing specific knowledge of the company and why you\'re a fit', 'Cover letters connect your experience to the specific role. Generic letters fail. The best letters reference specific company details and explain why you, why this role, why now.', 1, 3),
      mc('What makes business writing different from academic writing?', ['Business writing uses no evidence', 'Business writing prioritizes clarity, brevity, and action — what the reader needs to know and do, not comprehensive argument', 'Academic writing is always longer', 'There is no meaningful difference'], 'Business writing prioritizes clarity, brevity, and action — what the reader needs to know and do, not comprehensive argument', 'Business readers are busy. Get to the point, state the action needed, use bullet points for scannability. Academic writing is for depth and thoroughness; business writing is for decision-making and action.', 1, 4),
      mc('What is a memo used for?', ['A formal letter to outside organizations', 'Internal communication within an organization about policies, updates, or decisions', 'A legal document', 'A type of business proposal'], 'Internal communication within an organization about policies, updates, or decisions', 'Memos are short internal documents with To, From, Date, and Subject headers. They communicate information, requests, or decisions to colleagues or departments.', 1, 5),
      mc('What is the purpose of an executive summary?', ['A detailed introduction to a long report', 'A concise overview of a longer document\'s key points and recommendations, for busy readers', 'The conclusion of a business proposal', 'A summary written by company executives'], 'A concise overview of a longer document\'s key points and recommendations, for busy readers', 'Executive summaries let decision-makers understand a document\'s main points and recommendations without reading everything. Often the only part read — it must stand alone.', 1, 6),
      mc('What is the "bottom line up front" (BLUF) principle?', ['End with your main point', 'State the most important information first before details and context', 'Use bullet points for all information', 'Keep everything under one page'], 'State the most important information first before details and context', 'BLUF puts the conclusion or recommendation at the top. Busy readers need the key message immediately — supporting details follow for those who want them.', 1, 7),
      mc('When should you follow up after sending a professional email or application?', ['Never — wait for them to respond', 'After an appropriate waiting period (typically 5–7 business days) with a polite, brief follow-up', 'The same day if you haven\'t heard back', 'Only if the deadline has passed'], 'After an appropriate waiting period (typically 5–7 business days) with a polite, brief follow-up', 'Following up shows continued interest and professionalism. Wait long enough to be respectful, be brief, and don\'t be pushy — reference your original message and ask for a status update.', 1, 8),
      oe('Write a professional email declining a meeting request while proposing an alternative.', 'Example: Subject: Re: Meeting Request — Proposed Alternative Time. Thank you for reaching out. Unfortunately, I\'m unavailable on [date] due to a prior commitment. I\'d like to find a time that works for us both — would [alternative date/time options] work for you? Alternatively, if the matter is time-sensitive, I\'m happy to address it via email. Looking forward to connecting. [Name]. Key elements: thank them, briefly explain, offer alternatives, stay positive and action-oriented.', 'A strong answer demonstrates all key elements: gratitude, brief explanation, concrete alternative, professional tone, and brevity.', 2, 9),
      oe('Why is proofreading professional writing so important, and what are effective strategies for catching errors?', 'Professional writing with errors signals carelessness and can undermine trust in your competence. Strategies: read slowly and aloud (your brain reads what you intended, not what\'s there — your ear catches more); read backward word by word for spelling; use spell-check but don\'t rely on it (it misses homophones and grammar); wait before proofreading (fresh eyes catch more); print it out (screen vs. paper engage different brain processes); have someone else review it.', 'A strong answer gives specific, actionable strategies and explains why each one works — not just "read it carefully."', 2, 10),
    ],
  },

  'creative-writing': {
    title: 'Creative Writing Assessment',
    passingScore: 75,
    timeLimitMin: 30,
    questions: [
      mc('What is narrative point of view?', ['The plot of the story', 'The vantage point from which a story is told — who is narrating and how much they know', 'The setting of the story', 'The theme of the narrative'], 'The vantage point from which a story is told — who is narrating and how much they know', 'POV options: first person (I/we — intimate, limited), second person (you — unusual, immersive), third person limited (follows one character\'s perspective), third person omniscient (narrator knows all characters\' thoughts).', 1, 1),
      mc('What is conflict in a story?', ['Violence or fighting', 'The tension or struggle that drives a narrative — can be internal or external', 'The climax of the plot', 'The setting\'s challenges'], 'The tension or struggle that drives a narrative — can be internal or external', 'Conflict creates stakes and drives plot. Types: person vs. person, person vs. nature, person vs. society, person vs. self (internal). Without conflict, there\'s no story.', 1, 2),
      mc('What is the purpose of a story\'s exposition?', ['The rising action', 'The resolution of the conflict', 'Background information establishing setting, characters, and situation at the story\'s beginning', 'The climactic moment'], 'Background information establishing setting, characters, and situation at the story\'s beginning', 'Exposition introduces what readers need to know to follow the story — but it must be woven in naturally, not dumped in boring blocks. "In media res" (starting in action) delays exposition.', 1, 3),
      mc('What is dialogue used for in fiction?', ['To give information the narrator can\'t tell', 'To reveal character, advance plot, create tension, and give the story life and voice', 'To replace narration entirely', 'Only for conversations between main characters'], 'To reveal character, advance plot, create tension, and give the story life and voice', 'Good dialogue does multiple things: it shows who characters are through what they say (and don\'t say), moves the story forward, and creates natural-sounding human interaction.', 1, 4),
      mc('What is a metaphor?', ['A comparison using "like" or "as"', 'A direct comparison between two unlike things without using "like" or "as"', 'An exaggeration for effect', 'A repeated sound pattern'], 'A direct comparison between two unlike things without using "like" or "as"', '"Life is a journey" is a metaphor. "Life is like a journey" is a simile. Metaphors create meaning by equating two things rather than comparing them.', 1, 5),
      mc('What does "pacing" mean in creative writing?', ['The amount of dialogue in a story', 'The speed at which a story unfolds — controlling when to speed up and slow down', 'The number of scenes', 'The length of each chapter'], 'The speed at which a story unfolds — controlling when to speed up and slow down', 'Pacing controls tension and reader experience. Short sentences and scenes with action speed up pacing. Longer, descriptive passages slow it down. Good writers control pacing deliberately.', 1, 6),
      mc('What is characterization?', ['The number of characters in a story', 'The techniques used to develop and reveal a character\'s personality, motives, and traits', 'A character\'s role in the plot', 'Dialogue attributed to a specific character'], 'The techniques used to develop and reveal a character\'s personality, motives, and traits', 'Characterization can be direct (the narrator tells you) or indirect (shown through actions, dialogue, thoughts, and how others react). Round characters are complex; flat characters are one-dimensional.', 1, 7),
      mc('What is the difference between theme and plot?', ['They are the same', 'Plot is what happens; theme is the deeper meaning or universal idea the story explores', 'Theme is the summary; plot is the conflict', 'Plot is theme written explicitly'], 'Plot is what happens; theme is the deeper meaning or universal idea the story explores', 'Plot: "Scrooge is transformed by three ghosts on Christmas Eve." Theme: "It\'s never too late to change; generosity enriches life." Themes are ideas, not events.', 1, 8),
      oe('Write the opening paragraph of a short story. It should establish a character, a setting, and hint at a conflict — without directly stating any of these elements.', 'Example: "The fluorescent light in the hallway had buzzed for three years, and Margaret had learned to count it — a small, reliable irritation in a life that had become defined by them. She stood outside the door with her resignation letter folded into fourths, smooth from handling, the corners going soft. Down the hall, she could hear her manager\'s voice, that same casual ease he had with everyone except her." This paragraph uses details (letter, buzz, voice) to imply conflict without stating it.', 'A strong answer uses concrete details to suggest character, setting, and conflict — without stating "the character was nervous" or "the setting was an office."', 2, 9),
      oe('Why do writing teachers say you should "kill your darlings"? What does this mean for revision?', '"Kill your darlings" means you should cut the passages you\'re most in love with if they don\'t serve the story. Writers often become attached to beautiful sentences, clever jokes, or favorite scenes that don\'t actually advance the plot or deepen character. These become obstacles — the writer protects them when they should delete them. In revision, the question isn\'t "do I love this?" but "does this serve the story?" The attachment itself is a warning sign.', 'A strong answer explains what "darlings" are (beloved but unnecessary passages), why we keep them, and why cutting them makes writing better.', 2, 10),
    ],
  },
}
