import type { ExerciseDef } from '../types'

function mc(
  question: string,
  options: string[],
  correctAnswer: string,
  explanation: string,
  order: number
): ExerciseDef {
  return { question, type: 'MULTIPLE_CHOICE', options, correctAnswer, explanation, order }
}

export const languageExercises6: Record<string, ExerciseDef[]> = {
  'story-structure': [
    mc('What is the three-act structure?', ['A format for three-character stories', 'A narrative framework: Setup (Act 1), Confrontation (Act 2), Resolution (Act 3) — establishing situation, raising stakes, then resolving conflict', 'A rule that all stories must have exactly three chapters', 'A screenplay-specific format not applicable to fiction'], 'A narrative framework: Setup (Act 1), Confrontation (Act 2), Resolution (Act 3) — establishing situation, raising stakes, then resolving conflict', 'Three-act structure is fundamental to most Western storytelling. Act 1: introduce characters and world; Act 2: escalate conflict and obstacles; Act 3: climax and resolution. Even short stories follow this arc.', 1),
    mc('What is a story\'s inciting incident?', ['The story\'s opening scene', 'The event that disrupts the protagonist\'s ordinary world and sets the central conflict in motion', 'The moment of highest tension', 'The story\'s final resolution'], 'The event that disrupts the protagonist\'s ordinary world and sets the central conflict in motion', 'The inciting incident kicks the story into gear — something changes that forces the protagonist to act. In "The Wizard of Oz," Dorothy\'s tornado. In "The Hunger Games," Katniss volunteers for Prim. Without it, nothing would happen.', 2),
    mc('What is the climax of a story?', ['The most interesting scene', 'The moment of highest tension where the central conflict comes to a head — the protagonist faces their greatest challenge', 'The ending of the story', 'The scene where the protagonist succeeds'], 'The moment of highest tension where the central conflict comes to a head — the protagonist faces their greatest challenge', 'The climax is the structural peak — everything before has built toward it. It\'s the decisive confrontation where the story\'s central question is answered. After the climax, the tension releases in the resolution.', 3),
    mc('What is narrative conflict?', ['Arguments between characters', 'The central struggle or opposition that drives the story and creates dramatic tension', 'Any problem a character faces', 'The thematic disagreement between characters'], 'The central struggle or opposition that drives the story and creates dramatic tension', 'Types: character vs. character, character vs. self (internal), character vs. nature, character vs. society, character vs. fate. Conflict drives story forward — without it, nothing is at stake and readers disengage.', 4),
    mc('What is a story\'s resolution?', ['The story\'s happy ending', 'The aftermath of the climax — showing how the conflict was resolved and what changed for the characters', 'A restatement of the story\'s theme', 'The section after the inciting incident'], 'The aftermath of the climax — showing how the conflict was resolved and what changed for the characters', 'The resolution (denouement) shows the new state of the world after the conflict is resolved. It doesn\'t have to be happy — it must be satisfying in terms of emotional logic. It shows what the story meant.', 5),
  ],
  'character': [
    mc('What is the difference between a flat and round character?', ['Round characters are more likeable', 'Flat characters have one or two defining traits; round characters are complex, multidimensional, and capable of surprising us', 'Flat characters appear only once; round characters appear throughout', 'Round characters are protagonists; flat characters are antagonists'], 'Flat characters have one or two defining traits; round characters are complex, multidimensional, and capable of surprising us', 'A villain who is only evil is flat. A villain who loves his daughter, has a coherent worldview, and makes us understand (if not agree) is round. Real people are round — fiction\'s best characters are too.', 1),
    mc('What is character motivation?', ['The character\'s emotional state throughout the story', 'What drives a character to act — their wants, needs, fears, and goals that explain their behavior', 'The reason the author created this character', 'The character\'s backstory and history'], 'What drives a character to act — their wants, needs, fears, and goals that explain their behavior', 'Characters need convincing motivation or their actions feel arbitrary. Surface want (I want to win the competition) should connect to deeper need (I want to prove my worth to myself). Character depth comes from the gap between want and need.', 2),
    mc('What makes character dialogue feel authentic?', ['Making all characters speak grammatically correctly', 'Characters speaking in distinctive voices reflecting their background, education, personality, and emotional state — not all characters sounding the same', 'Having characters explain themselves clearly and explicitly', 'Using formal language for important characters, informal for minor ones'], 'Characters speaking in distinctive voices reflecting their background, education, personality, and emotional state — not all characters sounding the same', 'Cover the character names and read the dialogue — you should know who\'s speaking from the voice alone. Vocabulary, sentence length, what they volunteer vs. hold back, how they argue — all reveal character.', 3),
    mc('What is a character arc?', ['The physical journey a character takes through the story', 'The internal change a character undergoes — how they grow, regress, or transform as a result of the story\'s events', 'The relationship between the protagonist and antagonist', 'The sequence of challenges a character faces'], 'The internal change a character undergoes — how they grow, regress, or transform as a result of the story\'s events', 'Character arcs show internal change driven by external events. The external plot and internal arc should be connected — what happens to characters should force them to change in meaningful ways.', 4),
    mc('What is "show don\'t tell" as applied to character?', ['Never describing how characters look', 'Revealing character through action, dialogue, and decision rather than directly stating personality traits', 'Showing only positive traits of protagonists', 'Using physical description instead of personality description'], 'Revealing character through action, dialogue, and decision rather than directly stating personality traits', '"She was kind" (telling). "She slid her umbrella toward the wet stranger and walked into the rain herself" (showing). Actions reveal character better than labels. What someone does when it costs them something shows who they are.', 5),
  ],
  'setting-and-scene': [
    mc('What role does setting play in fiction?', ['It is merely decorative background', 'Setting establishes atmosphere, creates constraints on action, can reflect characters\' internal states, and grounds readers in a specific place and time', 'Setting only matters in historical fiction', 'Setting is less important than plot and character'], 'Setting establishes atmosphere, creates constraints on action, can reflect characters\' internal states, and grounds readers in a specific place and time', 'Setting does real work. A crumbling house reflects its owner\'s psychology. A locked room limits action in meaningful ways. Rain at a wedding creates ironic atmosphere. Setting and story should be inseparable.', 1),
    mc('What is scene-setting in fiction?', ['Describing the setting in detail at the story\'s beginning', 'Establishing place, time, atmosphere, and relevant context so readers can inhabit the fictional world — without overwhelming them with unnecessary detail', 'Always beginning with description before any action or dialogue', 'Providing a complete geographical description of where the story takes place'], 'Establishing place, time, atmosphere, and relevant context so readers can inhabit the fictional world — without overwhelming them with overwhelming detail', 'Effective scene-setting uses precise, evocative details (not exhaustive catalogs) woven into action and dialogue. One telling detail does more work than three paragraphs of description.', 2),
    mc('What is the difference between summary and scene in narrative?', ['Scenes are fiction; summaries are nonfiction', 'Summary compresses time and covers background quickly; scene expands time and shows a specific moment in real-time detail', 'Summary is always better for reader engagement', 'Scenes always include dialogue; summaries never do'], 'Summary compresses time and covers background quickly; scene expands time and shows a specific moment in real-time detail', 'Master the ratio: slow down for what matters (scenes), speed up through what doesn\'t (summary). "She spent the next three years struggling" = summary. The actual conversation where everything changed = scene.', 3),
    mc('What makes a scene feel grounded and real?', ['Using many adverbs for precise description', 'Specific sensory and physical detail that places readers in a body in a particular place — what they see, hear, smell, feel', 'Describing every element of the setting exhaustively', 'Using formal, elevated prose to signal importance'], 'Specific sensory and physical detail that places readers in a body in a particular place — what they see, hear, smell, feel', '"They had an emotional conversation" is not a scene. "The smell of burned coffee, her chair scraping back three inches when she heard what he said" is grounded in specific sensory experience.', 4),
    mc('What is pathetic fallacy?', ['A fallacy in reasoning committed by a character', 'When the environment reflects or foreshadows a character\'s emotional state — a storm during an argument, sunshine at a resolution', 'Describing nature incorrectly for effect', 'A character who confuses their feelings with the world\'s feelings'], 'When the environment reflects or foreshadows a character\'s emotional state — a storm during an argument, sunshine at a resolution', 'Pathetic fallacy uses setting to externalize internal states. It can be powerful or clichéd depending on execution. Subverting it — bright sunshine during tragedy — can create unsettling irony.', 5),
  ],
  'dialogue': [
    mc('What is dialogue\'s primary function in fiction?', ['To provide information the reader needs to know', 'To reveal character, advance plot, and create immediacy — making readers feel they\'re witnessing rather than being told about events', 'To break up long passages of description', 'To explain characters\' motivations directly'], 'To reveal character, advance plot, and create immediacy — making readers feel they\'re witnessing rather than being told about events', 'Good dialogue does multiple things simultaneously: reveals character (through voice and what\'s chosen to be said), advances plot (things happen and change through conversation), and creates immediacy (readers are in the scene).', 1),
    mc('What is subtext in dialogue?', ['Hidden exposition about the plot', 'The gap between what characters say and what they mean — the real communication happening beneath the surface words', 'Dialogue that references events not yet described', 'Technical jargon used between characters'], 'The gap between what characters say and what they mean — the real communication happening beneath the surface words', '"Fine" can mean devastation. "We need to talk" creates dread before anything is said. Characters often don\'t say what they mean — especially in conflict. Writing subtext well requires knowing what each character truly feels vs. says.', 2),
    mc('When should you use a dialogue tag other than "said"?', ['Always — vary your dialogue tags constantly to avoid repetition', 'Rarely — "said" is invisible; other tags ("exclaimed," "hissed") draw attention to themselves and can become distracting', 'Never — only "said" and "asked" should ever be used', 'Whenever the dialogue is emotionally significant'], 'Rarely — "said" is invisible; other tags ("exclaimed," "hissed") draw attention to themselves and can become distracting', '"Said" and "asked" are invisible — readers skip past them to the dialogue. "She exclaimed" makes readers notice the tag. Use action beats instead: "She slammed the book on the table. \'I can\'t do this anymore.\'" — this shows, not tells.', 3),
    mc('What is an action beat in dialogue?', ['An exciting moment in a conversation', 'A sentence of action attached to dialogue that shows what a character is doing — replacing or supplementing a dialogue tag', 'Dialogue that happens during a fight scene', 'The emotional peak of a conversation'], 'A sentence of action attached to dialogue that shows what a character is doing — replacing or supplementing a dialogue tag', '"I don\'t know what you want from me." She turned to the window. — The action beat (turning to window) creates a visual beat, shows her emotional state, and attributes the dialogue without a tag.', 4),
    mc('What punctuation is used for dialogue?', ['Single quotes for all dialogue', 'Double quotation marks around spoken words, with the dialogue tag set off by a comma inside the closing quotation mark', 'Italics for all spoken dialogue', 'No special punctuation — dialogue is indicated by paragraph breaks only'], 'Double quotation marks around spoken words, with the dialogue tag set off by a comma inside the closing quotation mark', '"I need to talk to you," she said. — Comma inside the closing quote; dialogue tag lowercase. New speaker = new paragraph. British English uses single quotes; American uses double. Punctuation inside quotes (American style).', 5),
  ],
  'short-fiction': [
    mc('What is the central challenge of writing short fiction?', ['Fitting a complete story into a very short word count', 'Every element — character, conflict, setting, theme — must do multiple jobs simultaneously because there\'s no room for anything that doesn\'t earn its place', 'Avoiding complex sentence structures', 'Creating sympathetic characters quickly'], 'Every element — character, conflict, setting, theme — must do multiple jobs simultaneously because there\'s no room for anything that doesn\'t earn its place', 'Short fiction demands economy. A single detail must do the work of a paragraph in a novel. Openings must establish character and conflict immediately. Every word is load-bearing.', 1),
    mc('Where should a short story begin?', ['At the very beginning of the character\'s relevant history', 'As late as possible — in medias res (in the middle of the action), just before the central conflict arrives', 'With a physical description of the main character', 'With background context so readers understand the situation'], 'As late as possible — in medias res (in the middle of the action), just before the central conflict arrives', 'In medias res means starting in the middle of things. Short fiction can\'t afford long setup. Start at the moment things begin to change — readers will pick up context as they go.', 2),
    mc('What is "compression" in short fiction?', ['Cutting the story to a shorter word count', 'Packing maximum meaning into minimum words — each scene, line, and word doing multiple things simultaneously', 'Summarizing background events quickly', 'Reducing dialogue to its essential minimum'], 'Packing maximum meaning into minimum words — each scene, line, and word doing multiple things simultaneously', 'A detail that simultaneously reveals character, establishes setting, and advances theme is "compressed." In short fiction, nothing can be decorative — everything must serve the story\'s engine.', 3),
    mc('What distinguishes flash fiction from a short story?', ['Flash fiction has no dialogue', 'Flash fiction is typically under 1,000 words (sometimes 100-500); short stories are generally 1,000-15,000 words', 'Flash fiction must have a twist ending', 'Flash fiction doesn\'t require a central conflict'], 'Flash fiction is typically under 1,000 words (sometimes 100-500); short stories are generally 1,000-15,000 words', 'Flash fiction\'s extreme compression demands radical economy — often a single scene, moment, or image that implies the larger story around it. Every word must carry unusual weight.', 4),
    mc('What makes a short story\'s ending effective?', ['Resolving every question the story raised', 'Creating a sense of resonance — the feeling that something has shifted or been understood, even if not everything is neatly resolved', 'Providing a moral lesson explicitly stated', 'Ending at the story\'s most exciting moment'], 'Creating a sense of resonance — the feeling that something has shifted or been understood, even if not everything is neatly resolved', 'Great short story endings feel both surprising and inevitable. They give readers something to sit with — an image, a realization, a reversal. Ambiguity is often more powerful than tidy resolution.', 5),
  ],
  'personal-essay': [
    mc('What distinguishes a personal essay from a diary entry?', ['Length — personal essays are longer', 'Personal essays use specific experience to reach universal insight — they have a point beyond "this happened to me"', 'Personal essays are more emotionally restrained', 'Diary entries are fiction; personal essays are nonfiction'], 'Personal essays use specific experience to reach universal insight — they have a point beyond "this happened to me"', 'The personal essay (Montaigne\'s invention) uses the particular to illuminate the general. "I burned the Thanksgiving turkey" becomes an essay when it explores perfectionism, family expectations, or the meaning of failure.', 1),
    mc('What is the "so what?" question in personal essay writing?', ['Why should this essay exist?', 'The question that challenges the writer to articulate why this experience matters beyond the personal — what readers will gain from this story', 'A rhetorical question used in the essay\'s conclusion', 'The central question the essay is trying to answer'], 'The question that challenges the writer to articulate why this experience matters beyond the personal — what readers will gain from this story', 'Every personal essay must answer "so what?" — why should a reader who didn\'t live this experience care? The specific experience must connect to something universal: fear, loss, belonging, identity.', 2),
    mc('What is the lyric essay?', ['An essay written in verse', 'An essay that uses poetic techniques — fragmentation, image, association — rather than linear narrative or argument', 'An essay about music or lyrics', 'A type of academic essay with elevated prose style'], 'An essay that uses poetic techniques — fragmentation, image, association — rather than linear narrative or argument', 'The lyric essay (Seneca, Montaigne, contemporary writers like Annie Dillard) approaches its subject through circling, imagery, and association rather than linear argument or chronological narrative.', 3),
    mc('How specific should personal essays be?', ['General enough that most readers can relate', 'Extremely specific — the paradox of the personal essay is that hyper-specific details create the most universal resonance', 'Only as specific as necessary to tell the story', 'Specific in narrative parts, general in reflective parts'], 'Extremely specific — the paradox of the personal essay is that hyper-specific details create the most universal resonance', '"I was sad" connects with no one. "I kept her voicemail for two years, listening to it on her birthday" connects with everyone who has ever lost someone. Specificity creates universality — not the other way around.', 4),
    mc('What is the relationship between narrating and reflecting in personal essays?', ['All reflection should come at the end after narrating the story', 'Essays weave narration (what happened) with reflection (what it means) throughout — neither sustained purely is as effective as their interplay', 'Reflection should be kept to a minimum in personal essays', 'Reflection and narration are the same thing in essay writing'], 'Essays weave narration (what happened) with reflection (what it means) throughout — neither sustained purely is as effective as their interplay', 'Pure narration is just story. Pure reflection is abstract. The tension between them — the experiencing self in the past, the thinking self in the present — creates the personal essay\'s distinctive double-consciousness.', 5),
  ],
  'poetry-basics': [
    mc('What is the difference between form and free verse poetry?', ['Free verse is easier than formal poetry', 'Form poetry follows established patterns (meter, rhyme); free verse creates its own structure through rhythm, line break, and image', 'Free verse has no rules whatsoever', 'Form poetry is for classical subjects; free verse is for modern subjects'], 'Form poetry follows established patterns (meter, rhyme); free verse creates its own structure through rhythm, line break, and image', 'Sonnets, villanelles, haiku: formal poetry uses defined patterns. Free verse (Whitman, Ginsberg, contemporary poetry) makes its own rules — but still requires attention to rhythm, line, image, and sound.', 1),
    mc('What is a line break in poetry?', ['A stanza break between sections of a poem', 'Where the poet chooses to end a line — a crucial decision that controls pace, emphasis, and meaning', 'A pause in reading indicated by punctuation', 'The meter pattern of a line'], 'Where the poet chooses to end a line — a crucial decision that controls pace, emphasis, and meaning', 'Line breaks are one of poetry\'s distinctive tools. They create emphasis (end-of-line words are stressed), control pace (enjambment creates speed; end-stopped lines create pause), and can create irony or surprise through where the line breaks.', 2),
    mc('What is imagery in poetry?', ['All visual description in a poem', 'Language that appeals to the senses — creating concrete, vivid experience through specific sensory details', 'Metaphors and similes specifically', 'Descriptive adjectives used for effect'], 'Language that appeals to the senses — creating concrete, vivid experience through specific sensory details', 'Imagery is the poem\'s engine — it creates direct experience rather than abstract statement. Good poems work through images, letting readers feel and see rather than just understand. "The apparition of these faces in the crowd" (Pound) — vivid without explanation.', 3),
    mc('What is the difference between a metaphor and a simile?', ['Metaphors are longer than similes', 'A simile compares using "like" or "as"; a metaphor states one thing IS another thing directly', 'Similes are more creative than metaphors', 'Metaphors are only used in formal poetry; similes in free verse'], 'A simile compares using "like" or "as"; a metaphor states one thing IS another thing directly', 'Simile: "Hope is like a thing with feathers" (Dickinson actually wrote "thing with feathers" as metaphor — "like" would make it simile). Metaphor: "Life is a journey." Metaphors create stronger fusion between tenor and vehicle.', 4),
    mc('What is the purpose of sound devices in poetry (rhyme, alliteration, assonance)?', ['To make poems easier to memorize', 'To create music, emphasis, and meaning through the sonic qualities of language — sound reinforcing sense', 'They are decorative additions that don\'t affect meaning', 'To mark the boundaries between poetic lines'], 'To create music, emphasis, and meaning through the sonic qualities of language — sound reinforcing sense', 'Sound is meaning in poetry. Alliteration creates connection; rhyme creates expectation and closure; assonance creates mood. In "the murmuring of innumerable bees" (Tennyson) — the sounds enact the meaning.', 5),
  ],
  'finding-your-voice': [
    mc('What is a writer\'s voice?', ['The character or narrator speaking in a story', 'The distinctive personality that emerges in writing — the combination of diction, rhythm, perspective, and sensibility that makes one writer sound different from another', 'The genre or style of writing a person uses', 'The subject matter a writer typically writes about'], 'The distinctive personality that emerges in writing — the combination of diction, rhythm, perspective, and sensibility that makes one writer sound different from another', 'Voice is the most difficult element of craft to learn and the hardest to define — but unmistakable when present. It\'s why you know a sentence is Hemingway\'s or Didion\'s or Baldwin\'s without seeing the name.', 1),
    mc('How do writers develop their voice?', ['By imitating one favorite author closely', 'Through reading widely, writing consistently, and discovering what only you can say in a way only you can say it', 'By following rules for good style carefully', 'By avoiding all literary influences'], 'Through reading widely, writing consistently, and discovering what only you can say in a way only you can say it', 'Voice develops at the intersection of influence and individuality. Reading widely internalizes what\'s possible; writing consistently reveals your patterns; revision strips away imitation to leave what\'s genuinely yours.', 2),
    mc('What is the relationship between imitation and originality in developing voice?', ['Imitation prevents originality — avoid all literary models', 'Imitation is a stage in the process — all writers begin by imitating writers they admire; originality emerges through that process', 'Originality means writing without reading other writers', 'Only professional writers need to develop original voices'], 'Imitation is a stage in the process — all writers begin by imitating writers they admire; originality emerges through that process', '"Good writers borrow; great writers steal" — T.S. Eliot. Learning from masters is how voice develops. The goal isn\'t to remain an imitator but to absorb influences and synthesize them into something distinctly yours.', 3),
    mc('What does it mean to write with authority?', ['Writing with confidence about any topic', 'Writing from a place of genuine investment — knowing your subject, having a perspective worth expressing, and trusting your own observations', 'Using formal, elevated language', 'Writing about topics where you have professional credentials'], 'Writing from a place of genuine investment — knowing your subject, having a perspective worth expressing, and trusting your own observations', 'Authority comes from genuine engagement, not credential. Write what you actually think, not what you believe you\'re supposed to think. The most powerful writing comes from the specific intersection of your particular experience and perception.', 4),
    mc('What should you do when your writing doesn\'t sound like your voice?', ['Completely rewrite it in a different style', 'Identify where you stopped trusting yourself — where you became cautious or "writerly" — and restore the directness and specificity that is authentically yours', 'Accept that your voice changes for different genres', 'Have someone else read it to tell you what your voice is'], 'Identify where you stopped trusting yourself — where you became cautious or "writerly" — and restore the directness and specificity that is authentically yours', 'Voice gets lost when writers try to sound "like a writer" — using elevated diction, complex syntax, borrowed imagery. Going back to direct, specific, genuine expression usually recovers voice. Trust the impulse that made you want to write this.', 5),
  ],
}
