import type { ExerciseDef } from '../types'

function mc(
  question: string,
  options: string[],
  correctAnswer: string,
  explanation: string,
  order: number
): ExerciseDef {
  return { question, type: 'MULTIPLE_CHOICE', options, correctAnswer, explanation, order }
}

export const languageExercises2: Record<string, ExerciseDef[]> = {
  'parts-of-speech': [
    mc('What is a noun?', ['A word that describes an action', 'A word that names a person, place, thing, or idea', 'A word that modifies a verb', 'A word that connects clauses'], 'A word that names a person, place, thing, or idea', 'Nouns are the subjects and objects of sentences. Common nouns: dog, city, idea. Proper nouns (capitalized): Sarah, Chicago. Abstract nouns: freedom, love. Collective nouns: team, flock.', 1),
    mc('What is a verb?', ['A word that describes a noun', 'A word expressing an action, state, or occurrence', 'A word that replaces a noun', 'A word connecting two sentences'], 'A word expressing an action, state, or occurrence', 'Action verbs: run, think, write. Linking verbs connect subject to description: "She is tired." Helping verbs assist main verbs: "She has been running." Every complete sentence needs a verb.', 2),
    mc('What is an adjective?', ['A word that modifies a verb', 'A word that modifies a noun or pronoun — describing which one, what kind, or how many', 'A word that replaces a noun', 'A word connecting two independent clauses'], 'A word that modifies a noun or pronoun — describing which one, what kind, or how many', 'Adjectives answer: which? (that book), what kind? (red car), how many? (three apples). They come before nouns or after linking verbs: "The sky is blue."', 3),
    mc('What is an adverb?', ['A word that modifies a noun', 'A word that modifies a verb, adjective, or another adverb — often ending in -ly', 'A word that names a place', 'A word that expresses emotion'], 'A word that modifies a verb, adjective, or another adverb — often ending in -ly', 'Adverbs answer: how? (slowly), when? (yesterday), where? (here), to what degree? (very). "She ran quickly." "The movie was incredibly boring." "He came early."', 4),
    mc('What is a conjunction?', ['A word that describes an action', 'A word that connects words, phrases, or clauses', 'A word that modifies verbs', 'A word that expresses a relationship between a noun and the rest of the sentence'], 'A word that connects words, phrases, or clauses', 'Coordinating conjunctions (FANBOYS): for, and, nor, but, or, yet, so — join equal elements. Subordinating conjunctions (because, although, when) join dependent to independent clauses.', 5),
  ],
  'sentence-structure': [
    mc('What is a simple sentence?', ['A sentence with no commas', 'A sentence with one independent clause — one subject and one predicate expressing a complete thought', 'A sentence with fewer than ten words', 'A sentence with only one noun'], 'A sentence with one independent clause — one subject and one predicate expressing a complete thought', '"The dog barked." Simple sentences have one main clause. They can be short or quite long — the key is having just one independent clause.', 1),
    mc('What is a compound sentence?', ['A sentence with a complex subject', 'Two or more independent clauses joined by a coordinating conjunction or semicolon', 'A sentence with a dependent clause', 'A sentence with more than one verb'], 'Two or more independent clauses joined by a coordinating conjunction or semicolon', '"I wanted coffee, but the shop was closed." Two independent clauses joined by "but." Could also use a semicolon: "I wanted coffee; the shop was closed."', 2),
    mc('What is a complex sentence?', ['A sentence that is hard to understand', 'One independent clause + one or more dependent clauses joined by a subordinating conjunction', 'A sentence with more than 20 words', 'Two independent clauses joined by a semicolon'], 'One independent clause + one or more dependent clauses joined by a subordinating conjunction', '"Although I was tired, I finished the report." The dependent clause ("Although I was tired") can\'t stand alone. The independent clause ("I finished the report") can. Subordinating conjunctions: because, although, when, if, since.', 3),
    mc('What is a compound-complex sentence?', ['Any very long sentence', 'Two or more independent clauses AND at least one dependent clause', 'A sentence with both nouns and verbs', 'A sentence that contains a list'], 'Two or more independent clauses AND at least one dependent clause', '"Although I was tired, I finished the report, and my boss praised my work." Dependent clause + two independent clauses = compound-complex. They can be effective or unwieldy — use carefully.', 4),
    mc('What is parallel structure?', ['Using the same grammatical form for elements in a series or pair', 'Writing sentences of equal length', 'Using the same punctuation throughout a paragraph', 'Repeating the same word for emphasis'], 'Using the same grammatical form for elements in a series or pair', '"She likes hiking, swimming, and to run" is not parallel. "She likes hiking, swimming, and running" is parallel — all gerunds. Parallel structure creates clarity and rhythm.', 5),
  ],
  'fragments-and-run-ons': [
    mc('What is a sentence fragment?', ['A sentence that is too short', 'An incomplete sentence that lacks a subject, a verb, or a complete thought', 'A sentence that begins with a conjunction', 'A sentence with more than one clause'], 'An incomplete sentence that lacks a subject, a verb, or a complete thought', '"Running through the park." No subject — who is running? "Because she was late." Subordinating conjunction creates a dependent clause that can\'t stand alone. Fragments leave readers hanging.', 1),
    mc('What is a run-on sentence?', ['A sentence that is too long', 'Two or more independent clauses joined incorrectly — without proper punctuation or a conjunction', 'A sentence with too many adjectives', 'Any sentence longer than 20 words'], 'Two or more independent clauses joined incorrectly — without proper punctuation or a conjunction', '"I was tired I went to bed" is a run-on. "I was tired, I went to bed" is a comma splice (a type of run-on). Fix with: a period, a semicolon, or a conjunction: "I was tired, so I went to bed."', 2),
    mc('What is a comma splice?', ['Any incorrect use of a comma', 'Using a comma alone to join two independent clauses — without a coordinating conjunction', 'Putting a comma before every "and"', 'Using commas in a list incorrectly'], 'Using a comma alone to join two independent clauses — without a coordinating conjunction', '"I love pizza, it is my favorite food." The comma alone can\'t join two independent clauses. Fix: "I love pizza; it is my favorite food." or "I love pizza because it is my favorite food."', 3),
    mc('How can you fix a run-on sentence?', ['Add more words to clarify it', 'Separate it into two sentences, add a semicolon, or join with a coordinating conjunction and comma', 'Remove all punctuation and start over', 'Add a subordinating conjunction to the beginning'], 'Separate it into two sentences, add a semicolon, or join with a coordinating conjunction and comma', 'Fix: "I was tired I went to bed." → "I was tired. I went to bed." or "I was tired; I went to bed." or "I was tired, so I went to bed." Three valid options, different rhythmic effects.', 4),
    mc('What is the easiest way to identify a fragment?', ['Count the words — fragments are short', 'Ask if it has both a subject AND a verb AND expresses a complete thought — fragments fail at least one test', 'Check if it begins with a capital letter', 'See if it could be an answer to a question'], 'Ask if it has both a subject AND a verb AND expresses a complete thought — fragments fail at least one test', '"After finishing dinner" has no independent subject and verb — it\'s a fragment. A sentence must answer: who or what (subject) + did what (predicate) + complete thought (makes sense alone).', 5),
  ],
  'subject-verb-agreement': [
    mc('What is subject-verb agreement?', ['Subjects and verbs must share the same emotional tone', 'The subject and verb must match in number — singular subjects take singular verbs, plural subjects take plural verbs', 'Verbs must follow subjects immediately', 'Subjects and verbs must be from the same part of speech'], 'The subject and verb must match in number — singular subjects take singular verbs, plural subjects take plural verbs', '"The dog runs." (singular) "The dogs run." (plural) Violations: "The team are playing well" (British) vs. "The team is playing well" (American) — collective nouns can be tricky.', 1),
    mc('Which verb form is correct: "Neither the students nor the teacher __ ready"?', ['"are" — "students" is closer and plural', '"is" — "teacher" is closer and singular; with "neither/nor" the verb agrees with the nearest subject', '"are" — when in doubt, use plural', '"were" — use past tense for hypotheticals'], '"is" — "teacher" is closer and singular; with "neither/nor" the verb agrees with the nearest subject', 'The proximity rule: with "neither/nor" and "either/or," the verb agrees with the subject closest to it. "Neither the teacher nor the students are ready" — "students" is nearest, so "are."', 2),
    mc('Which is correct: "Everyone __ responsible for their own work"?', ['"are" — "everyone" refers to many people', '"is" — "everyone" is an indefinite pronoun treated as singular', '"were" — the past tense is always correct here', '"have been" — the present perfect is required'], '"is" — "everyone" is an indefinite pronoun treated as singular', 'Indefinite pronouns (everyone, someone, anyone, nobody, each, either, neither) are singular: "Everyone is here," "Nobody wants to leave," "Each of the students has a book."', 3),
    mc('What is the subject in "The quality of the reports was excellent"?', ['"reports" — it is closest to the verb', '"quality" — it is the actual subject; "of the reports" is a prepositional phrase', '"quality of the reports" — the whole phrase is the subject', '"reports was" — the verb agrees with reports'], '"quality" — it is the actual subject; "of the reports" is a prepositional phrase', 'Prepositional phrases between subject and verb can trick you. Strip "of the reports" away — "The quality was excellent." The subject is "quality" (singular), so the verb is singular.', 4),
    mc('Which sentence demonstrates correct subject-verb agreement?', ['"The data shows a clear trend."', '"The data show a clear trend." — "data" is the plural of "datum"', '"The datas show a clear trend."', '"The data is showing a clear trend."'], '"The data show a clear trend." — "data" is the plural of "datum"', '"Data" is the plural of "datum" — in formal academic writing, "data are." In common usage, "data is" has become acceptable, but in scientific and academic contexts the plural "data show" is preferred.', 5),
  ],
  'commas': [
    mc('When do you use a comma before a coordinating conjunction?', ['Always before "and," "but," "or"', 'When joining two independent clauses: "I was tired, but I stayed." — not needed if one clause is dependent', 'Only in sentences longer than 15 words', 'Never — commas before conjunctions are always incorrect'], 'When joining two independent clauses: "I was tired, but I stayed." — not needed if one clause is dependent', '"I was tired but stayed" — no comma needed (only one independent clause). "I was tired, but I stayed" — comma needed before "but" joining two independent clauses.', 1),
    mc('What is the Oxford (serial) comma?', ['A comma placed before the first item in a list', 'The comma before "and" or "or" in a list of three or more items: "eggs, milk, and butter"', 'A comma used after introductory clauses', 'A comma separating independent clauses'], 'The comma before "and" or "or" in a list of three or more items: "eggs, milk, and butter"', 'Without the Oxford comma: "I dedicate this to my parents, God and Elvis." With it: "my parents, God, and Elvis." The Oxford comma prevents ambiguity. Many style guides recommend it.', 2),
    mc('When do you use a comma after an introductory element?', ['Never — commas after introductory elements are optional', 'After introductory words, phrases, or clauses that come before the main clause: "However, I disagree." / "After the meeting, we ate."', 'Only when the introductory element is more than 5 words', 'Only with subordinating conjunctions'], 'After introductory words, phrases, or clauses that come before the main clause: "However, I disagree." / "After the meeting, we ate."', 'Introductory elements are followed by a comma to signal where the main clause begins. "When I arrived, the party had already started." Without the comma, readers may misread the sentence\'s structure.', 3),
    mc('When do you use commas around a nonrestrictive clause?', ['Always when a clause begins with "which" or "who"', 'When the clause adds non-essential information that could be removed without changing the sentence\'s core meaning', 'When the clause begins with "that"', 'Never — nonrestrictive clauses don\'t need commas'], 'When the clause adds non-essential information that could be removed without changing the sentence\'s core meaning', '"My sister, who lives in Denver, is visiting." The "who" clause adds information but isn\'t needed to identify which sister. Restrictive: "The book that I lent you is rare." — "that I lent you" identifies which book — no commas.', 4),
    mc('Which sentence uses a comma correctly?', ['"I like cats, and dogs."', '"She was, however tired."', '"After graduating, she moved to Chicago."', '"I think, therefore I am incorrect here."'], '"After graduating, she moved to Chicago."', '"After graduating" is an introductory participial phrase — comma correctly follows it. The other examples: "cats, and dogs" (no comma before "and" in a two-item list), "was, however tired" (misplaced comma), and the last example misplaces the comma.', 5),
  ],
  'apostrophes': [
    mc('What are the two main uses of apostrophes?', ['To indicate pauses and to mark quotations', 'To show possession and to form contractions', 'To pluralize nouns and to indicate possession', 'To separate items in a list and to show omitted letters'], 'To show possession and to form contractions', 'Possessive: Sarah\'s book (singular), the dogs\' leashes (plural). Contractions: don\'t (do not), it\'s (it is), they\'re (they are). Apostrophes are NOT used to form regular plurals.', 1),
    mc('How do you form the possessive of a singular noun?', ['Add just an apostrophe after the word', 'Add \'s to the end of the noun: dog → dog\'s, James → James\'s', 'Add s\' to the end of the noun', 'Add \'s only if the noun doesn\'t end in s'], 'Add \'s to the end of the noun: dog → dog\'s, James → James\'s', '"The dog\'s leash." "James\'s book." For singular nouns ending in s, most style guides say add \'s anyway (James\'s), though some allow just the apostrophe (James\'). Consistency matters.', 2),
    mc('How do you form the possessive of a plural noun ending in s?', ['Add \'s after the s: dogs\'s', 'Add just an apostrophe after the s: dogs\'', 'Rewrite the sentence to avoid the possessive', 'Add an apostrophe before the s: do\'gs'], 'Add just an apostrophe after the s: dogs\'', '"The dogs\' leashes." "The teachers\' lounge." For plural nouns already ending in s, just add the apostrophe. For irregular plurals not ending in s: "children\'s books," "men\'s department."', 3),
    mc('What is the difference between "its" and "it\'s"?', ['They are interchangeable', '"It\'s" is the contraction for "it is" or "it has"; "its" is the possessive pronoun — no apostrophe', '"Its" is the contraction; "it\'s" is the possessive', '"It\'s" is the plural; "its" is the singular'], '"It\'s" is the contraction for "it is" or "it has"; "its" is the possessive pronoun — no apostrophe', 'Test: substitute "it is" or "it has." "It\'s raining" = "It is raining" ✓. "The cat licked its paw." Can you say "it is paw"? No — use "its." Possessive pronouns (his, her, its, their) never have apostrophes.', 4),
    mc('Which sentence uses apostrophes correctly?', ['"The student\'s grades improved."', '"The students grades improved."', '"The students\' grade\'s improved."', '"Its a good day to study apostrophe\'s."'], '"The student\'s grades improved."', '"The student\'s grades improved" correctly shows one student\'s grades. The others: "students grades" (missing possessive apostrophe), "grade\'s" (incorrectly uses apostrophe for a plural), "Its" (missing apostrophe for contraction), "apostrophe\'s" (apostrophe incorrectly used for a plural).', 5),
  ],
  'common-errors': [
    mc('What is the difference between "their," "there," and "they\'re"?', ['They are three different spellings of the same word', '"Their" = possessive (their car); "there" = place/existence (over there, there is); "they\'re" = contraction of "they are"', '"There" is possessive; "their" is a place; "they\'re" is an adjective', 'Only "there" is correct in formal writing'], '"Their" = possessive (their car); "there" = place/existence (over there, there is); "they\'re" = contraction of "they are"', 'Test: Substitute "they are." If it works, use "they\'re." For possession (belonging to them) use "their." For everything else — location, existence — use "there."', 1),
    mc('What is the difference between "your" and "you\'re"?', ['They are interchangeable in informal writing', '"Your" = possessive (your opinion); "you\'re" = contraction of "you are"', '"You\'re" = possessive; "your" = contraction', 'Both forms are correct for possession'], '"Your" = possessive (your opinion); "you\'re" = contraction of "you are"', 'Test: substitute "you are." "You\'re welcome" = "You are welcome" ✓. "What is your name?" — can you say "you are name"? No — use "your." The apostrophe always signals a contraction (letters removed).', 2),
    mc('What is the difference between "affect" and "effect"?', ['They mean exactly the same thing', '"Affect" is usually a verb (to influence); "effect" is usually a noun (the result)', '"Effect" is the verb; "affect" is the noun', 'They are only different in formal academic writing'], '"Affect" is usually a verb (to influence); "effect" is usually a noun (the result)', '"The rain affected the game." (verb) "The effect of the rain was visible." (noun) Memory: RAVEN — Remember, Affect is a Verb, Effect is a Noun. Edge cases: "effect" as a verb means "to bring about"; "affect" as a noun is a psychology term.', 3),
    mc('What is the difference between "than" and "then"?', ['They are only different in pronunciation', '"Than" is used in comparisons; "then" refers to time or consequence', '"Then" is used in comparisons; "than" refers to time', 'Both are conjunctions that can be used interchangeably'], '"Than" is used in comparisons; "then" refers to time or consequence', '"She is taller than her brother." (comparison) "First we ate dinner, then we watched a movie." (time sequence) "If you study, then you\'ll do well." (consequence)  "Than" = comparison; "then" = time/consequence.', 4),
    mc('What is the difference between "who" and "whom"?', ['They are interchangeable in modern English', '"Who" is used as a subject (like "he/she"); "whom" is used as an object (like "him/her")', '"Whom" is used as a subject; "who" is used as an object', '"Who" is formal; "whom" is informal'], '"Who" is used as a subject (like "he/she"); "whom" is used as an object (like "him/her")', 'Test: substitute "he" or "him." "Who/whom called?" → "He called" ✓ → use "who." "To who/whom should I address this?" → "To him" ✓ → use "whom." If "he/she" fits: who. If "him/her" fits: whom.', 5),
  ],
}
