import type { ExerciseDef } from '../types'

function mc(
  question: string,
  options: string[],
  correctAnswer: string,
  explanation: string,
  order: number
): ExerciseDef {
  return { question, type: 'MULTIPLE_CHOICE', options, correctAnswer, explanation, order }
}

export const languageExercises5: Record<string, ExerciseDef[]> = {
  'citations': [
    mc('Why do we cite sources?', ['To make essays look more academic', 'To give credit to original authors, allow readers to verify claims, and demonstrate the research behind your argument', 'Because it is required by teachers and professors', 'To protect yourself from being accused of plagiarism only'], 'To give credit to original authors, allow readers to verify claims, and demonstrate the research behind your argument', 'Citations are about intellectual honesty and community. They acknowledge who created ideas, let readers check your sources, show the conversation your work participates in, and credit the scholars whose work you build on.', 1),
    mc('What is the difference between MLA and APA citation styles?', ['MLA is for sciences; APA is for humanities', 'MLA (humanities) emphasizes author and page; APA (social sciences) emphasizes author and year — reflecting different fields\' priorities', 'They are different formatting styles with the same information', 'MLA requires footnotes; APA uses in-text citations only'], 'MLA (humanities) emphasizes author and page; APA (social sciences) emphasizes author and year — reflecting different fields\' priorities', 'MLA in-text: (Smith 45) — page number matters for textual analysis. APA in-text: (Smith, 2021) — publication date matters for scientific currency. Always check which style your field or instructor requires.', 2),
    mc('What is an in-text citation?', ['The full citation at the end of an essay', 'A brief reference within the body of the text pointing to the full citation in the bibliography', 'A footnote at the bottom of the page', 'A citation used within a quotation'], 'A brief reference within the body of the text pointing to the full citation in the bibliography', 'In-text citations are minimal — just enough to link to the full entry in your Works Cited/References list. They tell readers which source you\'re using without interrupting the flow of writing.', 3),
    mc('When must you cite a source?', ['Only for direct quotations', 'For direct quotations, paraphrases, specific facts, statistics, ideas, and arguments that come from a source — everything that isn\'t your own original idea', 'For quotations and statistics only', 'Only when the source is published in the last five years'], 'For direct quotations, paraphrases, specific facts, statistics, ideas, and arguments that come from a source — everything that isn\'t your own original idea', 'Common knowledge (facts everyone knows) doesn\'t need citation. Everything else does — even when you paraphrase or summarize. Failing to cite paraphrased ideas is still plagiarism.', 4),
    mc('What is a Works Cited or References list?', ['A list of sources you read but didn\'t use', 'A formatted list of every source cited in the paper, providing full publication information in a consistent format', 'A summary of all the arguments made in your sources', 'A bibliography of recommended reading on the topic'], 'A formatted list of every source cited in the paper, providing full publication information in a consistent format', 'Works Cited (MLA) / References (APA) / Bibliography (Chicago): all mean a list of sources actually cited in your paper, formatted so readers can locate the original. Include only sources you cited.', 5),
  ],
  'professional-email': [
    mc('What elements make a professional email effective?', ['Casual language and no greeting or sign-off', 'A clear subject line, appropriate greeting, concise organized content, professional tone, and a clear call to action or response request', 'Long, detailed explanation of every issue', 'Using formal vocabulary regardless of the reader'], 'A clear subject line, appropriate greeting, concise organized content, professional tone, and a clear call to action or response request', 'Professional emails should be easy to act on. The subject tells readers what to expect; the body covers one topic clearly; the closing specifies what you need. Busy recipients appreciate brevity and clarity.', 1),
    mc('What makes a good email subject line?', ['A vague description like "Question" or "Hello"', 'A specific, informative summary of the email\'s content and urgency: "Invoice #1234 Due Friday" rather than "Invoice Question"', 'The longest possible description of the email content', 'Your name and date'], 'A specific, informative summary of the email\'s content and urgency: "Invoice #1234 Due Friday" rather than "Invoice Question"', 'Subject lines determine whether emails get opened and found later. Specific subjects help recipients prioritize and search. "Meeting Request — Thursday March 15, 2pm" is vastly more useful than "Meeting."', 2),
    mc('When should you use Reply All?', ['Always, to keep everyone informed', 'Only when all recipients genuinely need your response — not when your reply is only relevant to the original sender', 'Never — always reply only to the sender', 'When you want to show the sender you are responsive'], 'Only when all recipients genuinely need your response — not when your reply is only relevant to the original sender', 'Reply All should be used when your response is relevant to all recipients. "I agree!" or "Thanks!" sent to a mailing list of 50 people is irritating and unprofessional. Think before clicking.', 3),
    mc('What is appropriate email tone in a professional setting?', ['Formal and distant to show professionalism', 'Warm but professional — friendly enough to build relationships, clear and direct enough to communicate efficiently', 'Identical to how you text your friends', 'As formal as a legal document at all times'], 'Warm but professional — friendly enough to build relationships, clear and direct enough to communicate efficiently', 'Tone depends on relationship: more formal with new contacts and executives, warmer with colleagues you know. Either extreme — overly stiff or overly casual — can undermine your professional image.', 4),
    mc('What should you do before sending an important professional email?', ['Send it immediately after writing to show responsiveness', 'Read it once more to check: clear subject, correct recipient, appropriate tone, clear request, any necessary attachments included', 'Have multiple colleagues review it first', 'Add a read receipt request'], 'Read it once more to check: clear subject, correct recipient, appropriate tone, clear request, any necessary attachments included', 'The most common professional email mistakes: wrong recipient, missing attachment, unclear request, or tone that reads harsher than intended. A quick re-read before sending prevents most of these.', 5),
  ],
  'resumes-and-cover-letters': [
    mc('What is the purpose of a resume?', ['To tell your life story', 'To present your qualifications, skills, and experience in a format that shows you\'re a strong match for a specific job', 'To list every job you\'ve ever had', 'To demonstrate your personality and interests'], 'To present your qualifications, skills, and experience in a format that shows you\'re a strong match for a specific job', 'A resume is marketing material — it argues you\'re the right person for this specific job. Tailor it for each application, emphasizing the experience and skills most relevant to that role.', 1),
    mc('What is the most effective format for resume bullet points?', ['Full sentences explaining your responsibilities', 'Action verb + task/accomplishment + result or scope: "Increased customer satisfaction scores by 22% by implementing new onboarding process"', 'Noun phrases describing your job duties', 'Passive voice sentences: "Was responsible for..."'], 'Action verb + task/accomplishment + result or scope: "Increased customer satisfaction scores by 22% by implementing new onboarding process"', 'Strong resume bullets start with strong verbs (led, built, increased, reduced) and quantify results where possible. "Responsible for customer service" is weak. "Resolved 50+ customer complaints weekly, achieving 4.8/5 satisfaction rating" is strong.', 2),
    mc('What is the purpose of a cover letter?', ['To repeat everything on your resume', 'To tell the story of why you want this specific job and how your specific experience makes you the right fit — what the resume can\'t say', 'To list your references', 'A formality required by employers that most don\'t read'], 'To tell the story of why you want this specific job and how your specific experience makes you the right fit — what the resume can\'t say', 'The cover letter adds what the resume can\'t: motivation, personality, and narrative. Use it to explain career changes, connect specific experiences to the role\'s needs, and show you understand the organization.', 3),
    mc('How long should a resume be?', ['At least two pages to show depth of experience', 'One page for most candidates with under 10 years of experience; two pages for experienced professionals — never longer without good reason', 'As long as necessary to include everything relevant', 'Exactly one page for everyone regardless of experience'], 'One page for most candidates with under 10 years of experience; two pages for experienced professionals — never longer without good reason', 'Recruiters typically spend 6-10 seconds on initial resume review. Concise, relevant, easy-to-scan resumes outperform dense, comprehensive ones. If you must cut, cut older and less relevant experience first.', 4),
    mc('What is ATS (Applicant Tracking System) and why does it matter for resumes?', ['A rating system used by interviewers', 'Software that screens resumes for keywords before a human sees them — meaning resumes must match the job description\'s language to pass the initial filter', 'A system that checks resume formatting errors', 'A background check service'], 'Software that screens resumes for keywords before a human sees them — meaning resumes must match the job description\'s language to match the initial filter', 'Many employers use ATS to filter hundreds of applications. If your resume doesn\'t contain keywords from the job description, it may be automatically rejected before a human reads it. Mirror the job description\'s language.', 5),
  ],
  'reports-and-memos': [
    mc('What is the purpose of a business memo?', ['A personal message between colleagues', 'A brief internal document communicating information, decisions, or directives to employees — more formal than email, less formal than a report', 'A legal document recording business decisions', 'An external communication to clients'], 'A brief internal document communicating information, decisions, or directives to employees — more formal than email, less formal than a report', 'Memos (TO/FROM/DATE/SUBJECT) communicate inside an organization: policy updates, meeting summaries, decisions requiring documentation. Formal enough to serve as records; direct enough to be read quickly.', 1),
    mc('What is the inverted pyramid structure in reports?', ['Starting with background information and building to conclusions', 'Leading with the most important information (conclusions/recommendations) and following with supporting detail — most important first', 'A diagram showing organizational hierarchy', 'A method for organizing financial reports'], 'Leading with the most important information (conclusions/recommendations) and following with supporting detail — most important first', 'Busy professionals read the executive summary first and may stop there. Putting key findings first respects readers\' time. Journalists use the same principle — the most important facts in the first paragraph.', 2),
    mc('What should a business report\'s executive summary include?', ['A detailed literature review of prior research', 'The problem, key findings, and main recommendations — a complete standalone overview of the report\'s most important content', 'Only the introduction and conclusion', 'A list of all data sources'], 'The problem, key findings, and main recommendations — a complete standalone overview of the report\'s most important content', 'The executive summary (typically 1-2 pages) should stand alone — senior decision-makers may read only this. It answers: why was this written, what did we find, what should we do?', 3),
    mc('What distinguishes an informational report from an analytical report?', ['Length — analytical reports are always longer', 'Informational reports present data and facts; analytical reports interpret data, draw conclusions, and make recommendations', 'Analytical reports use charts; informational reports don\'t', 'They serve the same purpose with different names'], 'Informational reports present data and facts; analytical reports interpret data, draw conclusions, and make recommendations', 'A sales report listing monthly figures is informational. A market analysis explaining what those figures mean for strategy and recommending action is analytical. Most professional reports are analytical.', 4),
    mc('What makes data visualization effective in business documents?', ['Including as many charts as possible', 'Choosing the right chart type for the data, labeling clearly, and ensuring visuals add insight rather than just decoration', 'Using colorful graphics to make the document look professional', 'Always using pie charts for any percentage data'], 'Choosing the right chart type for the data, labeling clearly, and ensuring visuals add insight rather than just decoration', 'Every visual should answer a question or support a point. Bar charts compare; line charts show trends; pie charts show composition (rarely effective beyond 4-5 segments). Label axes, include units, and caption what the chart shows.', 5),
  ],
  'writing-for-the-web': [
    mc('How does reading on screens differ from reading print?', ['People read screens more carefully than print', 'People scan screens rather than reading word-for-word — they look for relevant information using headings, bullets, and visual cues', 'Screen reading is identical to print reading', 'People read web content more slowly and carefully'], 'People scan screens rather than reading word-for-word — they look for relevant information using headings, bullets, and visual cues', 'Eye-tracking studies show F-shaped reading patterns on screens — people read the first line, scan down the left margin, occasionally move right. Web writing must accommodate scanning rather than assuming linear reading.', 1),
    mc('What is the most important principle of web writing?', ['Using technical vocabulary to establish credibility', 'Front-loading — putting the most important information first on every page and in every paragraph', 'Writing in the longest, most detailed way possible', 'Using the same style as print journalism'], 'Front-loading — putting the most important information first on every page and in every paragraph', 'Web readers decide in seconds whether content is worth their time. If the key information is buried at the end, they\'ve already left. Every element — headline, first sentence, first paragraph — must earn continued attention.', 2),
    mc('What role do headings play in web content?', ['They are decorative elements that improve visual design', 'They allow scanners to navigate to relevant sections — a reader can understand the page\'s structure from headings alone', 'They are only useful in long articles', 'They replace the need for good paragraph structure'], 'They allow scanners to navigate to relevant sections — a reader can understand the page\'s structure from headings alone', 'Web readers use headings as a navigation map. A reader should be able to skim all headings and understand the page\'s main points. Headings must be meaningful, not clever — clarity over wit.', 3),
    mc('What is SEO writing?', ['Writing that is optimized to rank well in search engine results through strategic use of relevant keywords', 'Writing that only appears in email newsletters', 'A style of writing that avoids technical jargon', 'Writing exclusively for academic search engines'], 'Writing that is optimized to rank well in search engine results through strategic use of relevant keywords', 'SEO (Search Engine Optimization) writing uses the words and phrases people actually search for. When done well, it improves discoverability without sacrificing readability. Keyword stuffing — overusing terms artificially — backfires.', 4),
    mc('Why should web writing use shorter sentences and paragraphs than print?', ['Because web readers are less intelligent', 'Because screen reading is more cognitively taxing — shorter units are easier to process and allow more white space that aids comprehension', 'Because search engines penalize long sentences', 'Because web writers are less skilled than print writers'], 'Because screen reading is more cognitively taxing — shorter units are easier to process and allow more white space that aids comprehension', 'Screen reading causes more eye strain and makes it harder to maintain place in long paragraphs. White space between short paragraphs creates visual breathing room. Print norms (4-6 sentence paragraphs) often become 2-3 sentences online.', 5),
  ],
  'persuasive-writing': [
    mc('What is the foundation of effective persuasion?', ['Having the right emotional appeals', 'Understanding your audience — their values, concerns, and objections — so you can frame your argument to connect with what they already care about', 'Having strong evidence regardless of how it\'s presented', 'Using confident, assertive language throughout'], 'Understanding your audience — their values, concerns, and objections — so you can frame your argument to connect with what they already care about', 'Persuasion is audience-centered. The same argument that works for one person fails with another. Effective persuaders research their audience and frame arguments in terms of values the audience already holds.', 1),
    mc('What is the role of ethos in persuasion?', ['Emotional appeals that move the audience', 'Establishing the speaker\'s credibility, expertise, and trustworthiness — audiences are more persuaded by those they trust and respect', 'Logical evidence supporting the argument', 'Visual elements that enhance the presentation'], 'Establishing the speaker\'s credibility, expertise, and trustworthiness — audiences are more persuaded by those they trust and respect', 'Ethos (credibility) is foundational. Before audiences evaluate arguments, they evaluate speakers. Demonstrating expertise, citing credible sources, showing you\'ve considered objections, and being honest all build ethos.', 2),
    mc('What is the most ethical approach to persuasion?', ['Using whatever techniques work, including manipulation', 'Transparent reasoning — presenting genuine evidence, honest acknowledgment of complexity, and genuine respect for the audience\'s ability to decide', 'Emotional appeals are always ethical; logical arguments are always ethical', 'Focusing only on the strongest version of your argument and ignoring all objections'], 'Transparent reasoning — presenting genuine evidence, honest acknowledgment of complexity, and genuine respect for the audience\'s ability to decide', 'Ethical persuasion respects autonomy — it offers genuine reasons and lets people decide. Manipulation bypasses rational evaluation through false urgency, misleading framing, or exploiting cognitive biases.', 3),
    mc('What does it mean to appeal to shared values in persuasion?', ['Pretending to share values you don\'t hold', 'Framing your argument in terms of values your audience already holds, showing how your position aligns with what they care about', 'Only using value statements rather than evidence', 'Avoiding controversial values topics'], 'Framing your argument in terms of values your audience already holds, showing how your position aligns with what they care about', 'People don\'t change values easily — but they can be shown that a new position serves their existing values. Framing a policy as "protecting families" to an audience that values family makes the argument more accessible.', 4),
    mc('What is the most common mistake in persuasive writing?', ['Using too much evidence', 'Leading with your conclusion rather than building up to it — not establishing why the audience should care before making your argument', 'Being too direct about your position', 'Including counterarguments'], 'Leading with your conclusion rather than building up to it — not establishing why the audience should care before making your argument', 'Audiences who feel attacked or don\'t understand why an issue matters to them disengage. Effective persuasion often establishes common ground and shared concern before introducing the controversial argument.', 5),
  ],
  'writing-with-clarity': [
    mc('What is plain language?', ['Simple vocabulary suitable only for children', 'Writing that communicates clearly and directly to the intended audience — using familiar words, short sentences, and active voice', 'Informal slang and conversational language', 'The avoidance of all technical terminology'], 'Writing that communicates clearly and directly to the intended audience — using familiar words, short sentences, and active voice', 'Plain language (also called plain writing or plain English) serves the reader. The goal: the reader can find, understand, and use the information on first reading. It doesn\'t mean dumbing down — it means respecting readers\' time.', 1),
    mc('What is the active voice?', ['Any sentence with an action verb', 'Sentence structure where the subject performs the action: "The team completed the project" rather than "The project was completed by the team"', 'Sentences using present tense only', 'Writing that uses direct commands'], 'Sentence structure where the subject performs the action: "The team completed the project" rather than "The project was completed by the team"', 'Active voice: subject → verb → object. Passive voice: object → passive verb → by whom (often omitted). Active is generally clearer, more direct, and shorter. Use passive when the actor is unknown or unimportant.', 2),
    mc('What is wordiness and how do you fix it?', ['Using too many different words for the same concept', 'Using more words than needed to express an idea — fixed by cutting redundant phrases and expressing ideas more directly', 'Using words that are too long or technical', 'Repetition of the same vocabulary throughout a piece'], 'Using more words than needed to express an idea — fixed by cutting redundant phrases and expressing ideas more directly', '"At this point in time" = "now." "In the event that" = "if." "Due to the fact that" = "because." Clear writing uses the fewest words needed. Cut every word that doesn\'t earn its place.', 3),
    mc('What are nominalizations and why should they be avoided?', ['Capitalized nouns used for emphasis', 'Verbs turned into nouns — which make writing abstract and wordy: "make a decision" instead of "decide," "provide assistance" instead of "help"', 'Proper nouns in academic writing', 'Noun phrases used to define technical terms'], 'Verbs turned into nouns — which make writing abstract and wordy: "make a decision" instead of "decide," "provide assistance" instead of "help"', 'Nominalization (verb → noun): "make a recommendation" → "recommend"; "conduct an investigation" → "investigate"; "reach an agreement" → "agree." Using strong verbs makes writing direct and energetic.', 4),
    mc('What does it mean to write at the "right level" for your audience?', ['Always using simple language for all audiences', 'Matching your vocabulary, assumed knowledge, and detail level to what your specific readers need and know', 'Using the same writing style for every document', 'Writing as formally as possible to appear credible'], 'Matching your vocabulary, assumed knowledge, and detail level to what your specific readers need and know', 'A cardiologist writing for cardiologists can use technical terms. The same doctor writing for patients needs plain language. Misjudging audience level — too complex or too simple — undermines communication.', 5),
  ],
}
