import type { AssessmentDef, AssessmentQuestionDef } from '../types'

const mc = (q: string, opts: string[], ans: string, exp: string, pts: number, ord: number): AssessmentQuestionDef =>
  ({ question: q, type: 'MULTIPLE_CHOICE', options: opts, correctAnswer: ans, explanation: exp, points: pts, order: ord })

const oe = (q: string, ans: string, exp: string, pts: number, ord: number): AssessmentQuestionDef =>
  ({ question: q, type: 'OPEN_ENDED', correctAnswer: ans, explanation: exp, points: pts, order: ord })

export const lawAssessments: Record<string, AssessmentDef> = {
  'know-your-rights': {
    title: 'Know Your Rights Assessment',
    passingScore: 75,
    timeLimitMin: 30,
    questions: [
      mc('What does the First Amendment protect?', ['Only freedom of speech', 'Freedom of speech, religion, press, assembly, and petition', 'The right to bear arms', 'Privacy from government surveillance'], 'Freedom of speech, religion, press, assembly, and petition', 'The First Amendment protects five fundamental freedoms: speech, religion, press, peaceful assembly, and petitioning the government.', 1, 1),
      mc('What does the Fourth Amendment protect against?', ['Self-incrimination', 'Unreasonable searches and seizures by the government', 'Double jeopardy', 'Cruel and unusual punishment'], 'Unreasonable searches and seizures by the government', 'The Fourth Amendment requires police to have probable cause and generally a warrant before searching your person, home, car, or belongings.', 1, 2),
      mc('What is the Fifth Amendment\'s protection against self-incrimination?', ['You don\'t have to testify against yourself in a criminal case', 'You can remain silent in all situations including workplace investigations', 'Police cannot question you at all', 'You have the right to a lawyer in all situations'], 'You don\'t have to testify against yourself in a criminal case', 'The Fifth Amendment\'s self-incrimination clause means you cannot be compelled to be a witness against yourself in a criminal proceeding — you have the right to remain silent.', 1, 3),
      mc('What are Miranda rights?', ['Rights only for citizens', 'Warnings police must give before custodial interrogation about your right to remain silent and to an attorney', 'Your rights at a civil trial', 'The right to a fair trial in any court'], 'Warnings police must give before custodial interrogation about your right to remain silent and to an attorney', 'Miranda warnings inform a suspect in custody of their Fifth and Sixth Amendment rights before interrogation. Failure to give them can make statements inadmissible.', 1, 4),
      mc('What does "due process" mean?', ['The government must follow fair procedures before depriving you of life, liberty, or property', 'All laws must be approved by Congress', 'Every person has the right to a jury trial', 'Government agencies must publish their rules'], 'The government must follow fair procedures before depriving you of life, liberty, or property', 'Due process ensures the government must follow established fair procedures before taking action that affects your fundamental rights.', 1, 5),
      mc('What is the right to equal protection under the law?', ['Everyone must be treated identically by the government', 'The government cannot discriminate arbitrarily based on race, sex, or other protected categories', 'All laws apply equally to all states', 'Every person gets the same tax rate'], 'The government cannot discriminate arbitrarily based on race, sex, or other protected categories', 'Equal protection (14th Amendment) prohibits the government from denying any person equal protection of the laws — it\'s the basis for anti-discrimination law.', 1, 6),
      mc('What is civil forfeiture?', ['Government taking of private property as part of a lawsuit', 'Law enforcement seizing property suspected of being connected to a crime without necessarily convicting the owner', 'A court ordering someone to pay damages', 'The IRS collecting unpaid taxes'], 'Law enforcement seizing property suspected of being connected to a crime without necessarily convicting the owner', 'Civil forfeiture allows police to seize property thought to be connected to criminal activity — often without charging the owner. It\'s controversial because the burden of proof can be low.', 1, 7),
      mc('What is the Eighth Amendment\'s prohibition?', ['Double jeopardy', 'Cruel and unusual punishment and excessive bail', 'Unreasonable searches', 'Self-incrimination'], 'Cruel and unusual punishment and excessive bail', 'The Eighth Amendment prohibits punishments that are grossly disproportionate to crimes and protects against inhumane treatment in the criminal justice system.', 1, 8),
      oe('Describe a situation where knowing your Fourth Amendment rights could matter in everyday life.', 'Example: Police stop your car and ask to search it without a warrant. You have the right to refuse consent to a search. Without probable cause or your consent, any search may be unconstitutional. Evidence found may be suppressed. Knowing this right prevents you from unknowingly waiving it.', 'A strong answer gives a concrete scenario and explains what the right means in practice, not just in theory.', 2, 9),
      oe('Why is it important to understand your constitutional rights even if you\'ve never been in trouble with the law?', 'Rights only protect you if you know them. Without knowledge, people waive rights through ignorance — consenting to searches, speaking when they should be silent, or missing deadlines to assert legal protections. Constitutional rights exist as limits on government power for everyone, not just people who expect to be in trouble.', 'The answer should make a real argument about practical protection, not just "rights are important."', 2, 10),
    ],
  },

  'contracts-and-agreements': {
    title: 'Contracts and Agreements Assessment',
    passingScore: 75,
    timeLimitMin: 30,
    questions: [
      mc('What are the essential elements of a valid contract?', ['Offer, acceptance, signatures, and witnesses', 'Offer, acceptance, consideration, and legal capacity', 'Written terms, notarization, and two parties', 'A written document and payment'], 'Offer, acceptance, consideration, and legal capacity', 'A contract requires: an offer by one party, acceptance by another, consideration (something of value exchanged), and both parties having legal capacity to contract.', 1, 1),
      mc('What is consideration in a contract?', ['The respect both parties must show each other', 'Something of value exchanged between parties — what each side gives and receives', 'The written terms of the agreement', 'The reason for entering the contract'], 'Something of value exchanged between parties — what each side gives and receives', 'Consideration is what makes a contract a bargain — each party must give something (money, services, a promise, giving up a right) for the agreement to be legally binding.', 1, 2),
      mc('What is breach of contract?', ['Negotiating contract terms', 'Failing to fulfill your obligations under a valid contract', 'Terminating a contract legally', 'Disagreeing about contract interpretation'], 'Failing to fulfill your obligations under a valid contract', 'A breach occurs when one party fails to do what the contract requires — not delivering goods, not paying, not completing work on time.', 1, 3),
      mc('What makes a contract voidable?', ['When one party makes more money than the other', 'When formed under duress, fraud, or by someone lacking legal capacity', 'When the contract is not in writing', 'When the terms are unfair'], 'When formed under duress, fraud, or by someone lacking legal capacity', 'A voidable contract is valid but can be canceled by the affected party — for example, contracts signed under coercion, based on misrepresentation, or by a minor.', 1, 4),
      mc('Are oral contracts legally enforceable?', ['No, all contracts must be in writing', 'Generally yes, though some contracts (like real estate) must be in writing under the Statute of Frauds', 'Only in small claims court', 'Yes, but only if there are witnesses'], 'Generally yes, though some contracts (like real estate) must be in writing under the Statute of Frauds', 'Oral contracts are generally enforceable, but they\'re hard to prove. Certain contracts — real estate, agreements lasting over a year — must be written under the Statute of Frauds.', 1, 5),
      mc('What is an independent contractor agreement?', ['An employment contract with extra benefits', 'A contract establishing someone as self-employed rather than an employee', 'A government-required work authorization', 'A union bargaining agreement'], 'A contract establishing someone as self-employed rather than an employee', 'Independent contractor agreements define the work, pay, and terms while establishing the worker is not an employee — important for tax treatment and liability.', 1, 6),
      mc('What does "liquidated damages" mean in a contract?', ['Damages paid in cash only', 'A predetermined amount both parties agree to as damages if a specific breach occurs', 'Damages the court calculates after a breach', 'Payment in installments'], 'A predetermined amount both parties agree to as damages if a specific breach occurs', 'Liquidated damages clauses set the compensation in advance for specific breaches, avoiding litigation over damages when a breach occurs.', 1, 7),
      mc('What is an arbitration clause?', ['A clause requiring both parties to hire lawyers', 'A clause requiring disputes to be resolved through arbitration instead of court', 'A clause limiting the contract term', 'A confidentiality requirement'], 'A clause requiring disputes to be resolved through arbitration instead of court', 'Arbitration clauses require parties to resolve disputes outside of court through an arbitrator — commonly found in employment contracts, credit card agreements, and consumer contracts.', 1, 8),
      oe('You hire a contractor to renovate your bathroom for $5,000, to be completed in 30 days. They finish in 60 days and do substandard work. What are your legal options?', 'You may have a breach of contract claim for both the delay and the substandard work. Options include: demanding they fix the defects (specific performance), deducting repair costs from payment, suing in small claims or civil court for cost of repairs and consequential damages. Document everything. Check the contract for dispute resolution clauses, warranties, or liquidated damages terms.', 'A strong answer identifies it as a breach, names at least two remedies, and mentions the importance of documentation.', 2, 9),
      oe('Why is it important to read every contract before signing, even if it seems routine?', 'Contracts are legally binding. Terms you don\'t read can still bind you — like arbitration clauses that prevent you from suing, auto-renewal clauses, or penalty provisions. Many consumer contracts contain terms that heavily favor the other party. You have no legal excuse for not reading what you signed, so understanding it beforehand is your only protection.', 'A strong answer names specific types of problematic clauses and explains the legal consequence of not reading.', 2, 10),
    ],
  },

  'tenant-and-housing-rights': {
    title: 'Tenant and Housing Rights Assessment',
    passingScore: 75,
    timeLimitMin: 30,
    questions: [
      mc('What is a lease?', ['A real estate purchase agreement', 'A binding contract between a landlord and tenant establishing the terms of a rental', 'A permit to live in a building', 'A rental application'], 'A binding contract between a landlord and tenant establishing the terms of a rental', 'A lease is a legally binding agreement specifying rent, duration, rules, and the rights and responsibilities of both landlord and tenant.', 1, 1),
      mc('What is the implied warranty of habitability?', ['A promise that the landlord will renovate annually', 'The legal requirement that landlords maintain rental units in livable condition', 'A tenant\'s promise to maintain the unit', 'An insurance policy on the property'], 'The legal requirement that landlords maintain rental units in livable condition', 'Landlords are legally required to keep units habitable — functioning heat, plumbing, no infestations, structurally safe. Failure gives tenants legal remedies in most states.', 1, 2),
      mc('Under what circumstances can a landlord legally enter your rental unit?', ['Any time they choose', 'Only when you are home', 'With proper advance notice (usually 24–48 hours), except in genuine emergencies', 'Only for repairs you requested'], 'With proper advance notice (usually 24–48 hours), except in genuine emergencies', 'Most states require landlords to give reasonable notice (typically 24–48 hours) before entering, except for true emergencies like burst pipes or fire.', 1, 3),
      mc('What is a security deposit used for?', ['As extra rent payment', 'To cover unpaid rent or tenant-caused damage at the end of the tenancy', 'The landlord\'s property insurance', 'Moving expenses for the landlord'], 'To cover unpaid rent or tenant-caused damage at the end of the tenancy', 'Security deposits protect landlords from unpaid rent or excessive damage beyond normal wear and tear — and most states regulate how and when they must be returned.', 1, 4),
      mc('What is an eviction?', ['A tenant voluntarily leaving', 'The legal process a landlord uses to remove a tenant from the property', 'A rent increase notice', 'A lease termination by mutual agreement'], 'The legal process a landlord uses to remove a tenant from the property', 'Eviction is a court-supervised process. Landlords cannot lock you out, remove belongings, or shut off utilities — they must follow the legal eviction process.', 1, 5),
      mc('What does the Fair Housing Act prohibit?', ['All tenant background checks', 'Discrimination in housing based on race, color, religion, sex, national origin, disability, or familial status', 'Charging different rents in different neighborhoods', 'Landlords running background checks without consent'], 'Discrimination in housing based on race, color, religion, sex, national origin, disability, or familial status', 'The Fair Housing Act makes it illegal to discriminate in selling, renting, or financing housing based on the listed protected classes.', 1, 6),
      mc('What is normal wear and tear?', ['Any damage to the unit', 'Gradual, expected deterioration from ordinary use that tenants are not responsible for', 'Repairs the landlord must make annually', 'Damage covered by renter\'s insurance'], 'Gradual, expected deterioration from ordinary use that tenants are not responsible for', 'Normal wear and tear — small scuffs, worn carpet, minor nail holes — cannot be deducted from your security deposit. Only damage beyond normal use counts.', 1, 7),
      mc('What should you do before moving into a rental?', ['Sign the lease immediately to hold the unit', 'Do a move-in inspection and document all existing damage in writing with photos', 'Pay the first three months rent upfront', 'Trust the landlord\'s verbal assurances'], 'Do a move-in inspection and document all existing damage in writing with photos', 'Documenting existing damage before move-in — and getting the landlord to sign off — protects you from being charged for damage you didn\'t cause when you move out.', 1, 8),
      oe('Your landlord has refused to fix a broken heater for three weeks in winter. What are your options as a tenant?', 'Options vary by state but typically include: notifying the landlord in writing (creating a paper trail), contacting local housing authority or building inspector, "repair and deduct" (getting it fixed and deducting the cost from rent), rent withholding (paying into an escrow account), or breaking the lease for breach of habitability. Document everything. Retaliation for exercising these rights is illegal.', 'A strong answer mentions documentation, at least two legal remedies, and anti-retaliation protections.', 2, 9),
      oe('What steps should you take when moving out of a rental to maximize getting your security deposit back?', 'Give proper written notice per your lease. Clean thoroughly. Repair any damage beyond normal wear and tear. Do a walk-through with the landlord. Document the unit\'s condition with photos. Request itemized deductions in writing if any are made. Know your state\'s deadline for return (usually 14–30 days). Sue in small claims if the landlord wrongfully withholds.', 'A complete answer addresses notice, cleaning, documentation, and legal recourse if the deposit is unfairly withheld.', 2, 10),
    ],
  },

  'employment-law': {
    title: 'Employment Law Assessment',
    passingScore: 75,
    timeLimitMin: 30,
    questions: [
      mc('What does "at-will employment" mean?', ['The employer must give 30 days notice before firing', 'Either party can end the employment relationship at any time for any legal reason', 'Employees can only be fired for cause', 'Workers have lifetime job guarantees'], 'Either party can end the employment relationship at any time for any legal reason', 'At-will employment (the default in most US states) means employers can fire employees for any legal reason — or no reason — and employees can quit anytime. Exceptions exist for discrimination and retaliation.', 1, 1),
      mc('What is the federal minimum wage?', ['$10.00 per hour', '$7.25 per hour', '$15.00 per hour', 'There is no federal minimum wage'], '$7.25 per hour', 'The federal minimum wage is $7.25/hour, though many states have higher minimums. Employers must pay whichever is higher — state or federal.', 1, 2),
      mc('Which law prohibits workplace discrimination based on race, sex, religion, and national origin?', ['The Fair Labor Standards Act', 'The National Labor Relations Act', 'Title VII of the Civil Rights Act', 'The Americans with Disabilities Act'], 'Title VII of the Civil Rights Act', 'Title VII prohibits employment discrimination in hiring, firing, pay, and conditions based on race, color, religion, sex, and national origin.', 1, 3),
      mc('What is FMLA?', ['A law requiring paid sick leave', 'A federal law providing eligible employees up to 12 weeks of unpaid, job-protected leave for qualifying reasons', 'A minimum wage law', 'A workers\' compensation program'], 'A federal law providing eligible employees up to 12 weeks of unpaid, job-protected leave for qualifying reasons', 'The Family and Medical Leave Act lets eligible employees take unpaid leave for childbirth, serious illness, or family caregiving — with their job protected when they return.', 1, 4),
      mc('What is workplace harassment?', ['Any disagreement with a supervisor', 'Unwelcome conduct based on a protected characteristic that is severe or pervasive enough to create a hostile work environment', 'Criticism of work performance', 'Strict management style'], 'Unwelcome conduct based on a protected characteristic that is severe or pervasive enough to create a hostile work environment', 'Harassment becomes illegal when it\'s based on protected class (race, sex, religion, etc.) and is severe or pervasive — not just rude or unpleasant behavior.', 1, 5),
      mc('What is workers\' compensation?', ['Overtime pay', 'A program providing medical and wage benefits to employees injured on the job', 'Unemployment insurance', 'A bonus for long-term employees'], 'A program providing medical and wage benefits to employees injured on the job', 'Workers\' comp is a no-fault insurance system — injured employees get medical care and partial wage replacement regardless of who caused the accident.', 1, 6),
      mc('What is a non-compete agreement?', ['A contract prohibiting an employee from working for competitors for a period after leaving', 'An agreement not to work overtime', 'A prohibition on working a second job', 'A contract fixing pay for a set term'], 'A contract prohibiting an employee from working for competitors for a period after leaving', 'Non-competes restrict where you can work after leaving a job. Their enforceability varies widely by state — some states (like California) make them largely unenforceable.', 1, 7),
      mc('What is the difference between an employee and an independent contractor?', ['Contractors are paid more', 'Employees have taxes withheld and receive benefits; contractors are self-employed and responsible for their own taxes', 'Contractors have more job security', 'There is no legal difference'], 'Employees have taxes withheld and receive benefits; contractors are self-employed and responsible for their own taxes', 'Classification matters legally — employees get protections (minimum wage, overtime, benefits), while contractors don\'t. Misclassification by employers is illegal.', 1, 8),
      oe('You believe your employer discriminated against you by not promoting you due to your religion. What steps should you take?', 'Document evidence of the discrimination (emails, performance reviews, witness accounts). Report to HR in writing, creating a record. File a charge with the EEOC (required before filing a lawsuit). The EEOC investigates and may mediate or issue a "right to sue" letter. Consult an employment attorney. Time limits matter — EEOC charges must generally be filed within 180–300 days of the discriminatory act.', 'A strong answer names EEOC, mentions documentation, and notes time limits.', 2, 9),
      oe('What protections do whistleblowers have, and why are they important?', 'Whistleblowers are employees who report illegal or unethical activity by their employer. Various federal and state laws protect them from retaliation (firing, demotion, harassment) for reporting violations — including OSHA violations, fraud, safety issues, and securities violations. These protections are essential because without them, employees would fear reporting wrongdoing, allowing illegal activity to continue unchecked.', 'The answer should explain what whistleblowing is, name the protection (anti-retaliation), and explain why it matters.', 2, 10),
    ],
  },

  'criminal-law-basics': {
    title: 'Criminal Law Basics Assessment',
    passingScore: 75,
    timeLimitMin: 30,
    questions: [
      mc('What distinguishes a criminal case from a civil case?', ['Criminal cases involve more money', 'In criminal cases the government prosecutes; in civil cases private parties sue each other', 'Civil cases can result in jail time', 'Criminal cases are settled out of court'], 'In criminal cases the government prosecutes; in civil cases private parties sue each other', 'Criminal law is the government prosecuting violations of laws that affect society. Civil law involves private disputes over rights and compensation.', 1, 1),
      mc('What does "beyond a reasonable doubt" mean?', ['The jury is 50% confident', 'The standard of proof required for criminal conviction — near certainty of guilt', 'Evidence outweighs the defense\'s arguments', 'A reasonable person would probably agree'], 'The standard of proof required for criminal conviction — near certainty of guilt', 'Beyond a reasonable doubt is the highest legal standard — the prosecution must eliminate any reasonable doubt about guilt. Uncertainty requires acquittal.', 1, 2),
      mc('What is the difference between a felony and a misdemeanor?', ['Felonies are federal; misdemeanors are state', 'Felonies are more serious crimes with harsher penalties; misdemeanors are less serious', 'Misdemeanors always result in prison', 'There is no meaningful difference'], 'Felonies are more serious crimes with harsher penalties; misdemeanors are less serious', 'Misdemeanors typically carry up to a year in jail and fines. Felonies carry over a year in prison and have long-term consequences like loss of voting rights and professional licenses.', 1, 3),
      mc('What is probable cause?', ['A feeling an officer has about a suspect', 'Reasonable belief based on facts that a crime was committed or is about to be committed', 'Eyewitness identification', 'A confession by the suspect'], 'Reasonable belief based on facts that a crime was committed or is about to be committed', 'Probable cause is the legal threshold for arrests and searches — officers need specific, articulable facts, not just hunches or generalizations.', 1, 4),
      mc('What is a plea bargain?', ['A defendant\'s request for bail', 'An agreement where the defendant pleads guilty in exchange for a reduced charge or sentence', 'A negotiation over evidence rules', 'The prosecutor dropping all charges'], 'An agreement where the defendant pleads guilty in exchange for a reduced charge or sentence', 'Plea bargains resolve over 90% of criminal cases. Defendants get certainty of a lesser outcome; prosecutors get convictions without the cost and risk of trial.', 1, 5),
      mc('What is the Sixth Amendment\'s guarantee?', ['Freedom from self-incrimination', 'The right to a speedy trial, public trial, impartial jury, and to confront witnesses and have counsel', 'Protection from unreasonable searches', 'Freedom from cruel and unusual punishment'], 'The right to a speedy trial, public trial, impartial jury, and to confront witnesses and have counsel', 'The Sixth Amendment protects criminal defendants\' procedural rights: speedy trial, public trial, jury of peers, confrontation of accusers, and legal representation.', 1, 6),
      mc('What does double jeopardy prohibit?', ['Being charged in two states for the same crime', 'Being tried twice for the same crime after acquittal or conviction in the same jurisdiction', 'Filing civil and criminal charges simultaneously', 'A jury reaching a split verdict'], 'Being tried twice for the same crime after acquittal or conviction in the same jurisdiction', 'The Fifth Amendment\'s double jeopardy clause prevents the government from repeatedly prosecuting someone for the same offense — acquittal is final.', 1, 7),
      mc('What is an arraignment?', ['A private meeting between defendant and prosecutor', 'A court proceeding where charges are read and the defendant enters a plea', 'The initial police questioning', 'A sentencing hearing'], 'A court proceeding where charges are read and the defendant enters a plea', 'At arraignment, the formal charges are presented and the defendant pleads guilty, not guilty, or no contest. Bail is often set at this stage.', 1, 8),
      oe('Why do you have the right to remain silent if arrested, and what are the risks of waiving that right?', 'The Fifth Amendment protects against self-incrimination. Anything you say can be used against you — even innocent-sounding statements can be twisted or taken out of context. Police interrogation techniques are designed to elicit confessions. Exercising silence isn\'t guilt — it\'s protection. The risk of talking: you may say something incriminating or inconsistent that hurts your defense. The risk of silence: minimal — prosecutors can\'t comment on it.', 'A strong answer explains the constitutional basis and the practical dangers of waiving the right.', 2, 9),
      oe('Explain the concept of mens rea and why it matters in criminal law.', 'Mens rea means "guilty mind" — the intent or knowledge required for a crime. Most crimes require both a guilty act (actus reus) and a guilty mind. If someone causes harm by accident without intent, they may not be criminally liable. For example, accidentally killing someone differs from intentional murder. Mens rea distinctions determine whether you\'re charged with murder, manslaughter, or not charged at all.', 'A strong answer defines the term, explains its function, and gives a concrete example showing the difference intent makes.', 2, 10),
    ],
  },

  'family-law-basics': {
    title: 'Family Law Basics Assessment',
    passingScore: 75,
    timeLimitMin: 30,
    questions: [
      mc('What is a prenuptial agreement?', ['A marriage license', 'A contract made before marriage defining how assets will be divided if the marriage ends', 'A divorce settlement', 'A government record of marriage'], 'A contract made before marriage defining how assets will be divided if the marriage ends', 'Prenups are pre-marriage contracts that establish property rights and financial arrangements in the event of divorce or death. They must meet legal requirements to be enforceable.', 1, 1),
      mc('What is the difference between legal separation and divorce?', ['They are identical legally', 'Separated spouses are still legally married but live apart; divorce legally ends the marriage', 'Legal separation is only available in some states', 'Divorce requires both parties to agree; separation does not'], 'Separated spouses are still legally married but live apart; divorce legally ends the marriage', 'Legal separation allows couples to live apart and divide finances/custody while remaining married — useful for insurance reasons or religious beliefs against divorce.', 1, 2),
      mc('What factors do courts consider when determining child custody?', ['Which parent earns more', 'The best interests of the child, including stability, parental involvement, and the child\'s preferences', 'Who filed for divorce first', 'The child\'s gender'], 'The best interests of the child, including stability, parental involvement, and the child\'s preferences', 'Courts use a "best interests of the child" standard, weighing: emotional bonds, each parent\'s ability to provide, stability, history of abuse, and sometimes the child\'s own preferences (depending on age).', 1, 3),
      mc('What is child support?', ['Financial support for a parent during divorce', 'Payments from the non-custodial parent to help cover the child\'s expenses', 'Government assistance for low-income families', 'Educational expenses paid by grandparents'], 'Payments from the non-custodial parent to help cover the child\'s expenses', 'Child support is court-ordered financial support from the non-custodial parent. It\'s calculated based on income, custody arrangement, and the child\'s needs.', 1, 4),
      mc('What is alimony (spousal support)?', ['Child support payments', 'Financial support paid to a lower-earning spouse after divorce', 'Property division', 'A joint account used during separation'], 'Financial support paid to a lower-earning spouse after divorce', 'Alimony compensates a spouse who sacrificed career advancement or earning potential during the marriage. Courts consider length of marriage, standard of living, and each spouse\'s finances.', 1, 5),
      mc('What does "marital property" typically include?', ['Only property purchased in both names', 'Assets and debts acquired during the marriage regardless of whose name is on them', 'Property owned before marriage', 'Inherited assets during the marriage'], 'Assets and debts acquired during the marriage regardless of whose name is on them', 'Marital property generally includes income earned and assets acquired during the marriage — even if titled in one name. Rules vary by state (community property vs. equitable distribution).', 1, 6),
      mc('What is a restraining order?', ['An order freezing bank accounts', 'A court order requiring someone to stay away from another person', 'A court order stopping a divorce', 'A requirement to attend counseling'], 'A court order requiring someone to stay away from another person', 'Restraining orders (protective orders) prohibit contact or proximity to a protected person. Violating them is a criminal offense.', 1, 7),
      mc('At what age can a child typically refuse visitation with a parent?', ['6 years old', '10 years old', 'There is no set age — courts consider maturity, but orders must be followed until modified', '18 years old'], 'There is no set age — courts consider maturity, but orders must be followed until modified', 'Courts may consider an older child\'s preference, but custody orders remain in effect until modified by a court. A child cannot simply refuse court-ordered visitation — the custodial parent must follow the order.', 1, 8),
      oe('Explain the difference between sole custody and joint custody. What are the advantages and disadvantages of each?', 'Sole custody: one parent has primary physical and/or legal custody. Simpler decisions, less conflict, but child has less access to one parent. Joint custody: both parents share physical time and/or legal decision-making. Better for child\'s bond with both parents, but requires communication and cooperation. Works best when parents can co-parent civilly; difficult in high-conflict divorces.', 'A strong answer distinguishes physical vs. legal custody if possible, and gives meaningful trade-offs for each arrangement.', 2, 9),
      oe('Why might someone going through a family law matter benefit from having an attorney even if it seems simple?', 'Family law is emotionally charged and legally complex. Agreements about custody, support, and property have long-term financial and parental consequences. Mistakes (signing something unfair, missing deadlines, failing to disclose assets) can be hard to undo. An attorney protects your rights, ensures agreements are fair and enforceable, and represents you if the other party has one.', 'The answer should name specific risks of proceeding without legal help — not just "lawyers are useful."', 2, 10),
    ],
  },
}
