import type { AssessmentDef, AssessmentQuestionDef } from '../types'

const mc = (q: string, opts: string[], ans: string, exp: string, pts: number, ord: number): AssessmentQuestionDef =>
  ({ question: q, type: 'MULTIPLE_CHOICE', options: opts, correctAnswer: ans, explanation: exp, points: pts, order: ord })

const oe = (q: string, ans: string, exp: string, pts: number, ord: number): AssessmentQuestionDef =>
  ({ question: q, type: 'OPEN_ENDED', correctAnswer: ans, explanation: exp, points: pts, order: ord })

export const mathematicsAssessments: Record<string, AssessmentDef> = {
  'arithmetic': {
    title: 'Arithmetic Assessment',
    passingScore: 75,
    timeLimitMin: 30,
    questions: [
      mc('What is the order of operations?', ['Left to right always', 'PEMDAS — Parentheses, Exponents, Multiplication/Division, Addition/Subtraction', 'Addition before multiplication always', 'Right to left for all operations'], 'PEMDAS — Parentheses, Exponents, Multiplication/Division, Addition/Subtraction', 'PEMDAS defines the sequence for evaluating expressions: Parentheses first, then Exponents, then Multiplication and Division (left to right), then Addition and Subtraction (left to right).', 1, 1),
      mc('What is a prime number?', ['Any odd number', 'A number greater than 1 divisible only by 1 and itself', 'An even number greater than 2', 'A number with no factors'], 'A number greater than 1 divisible only by 1 and itself', 'Prime numbers (2, 3, 5, 7, 11...) have exactly two factors: 1 and themselves. 2 is the only even prime.', 1, 2),
      mc('What is 15% of 80?', ['8', '10', '12', '15'], '12', '15% of 80 = 0.15 × 80 = 12. To find a percentage of a number, convert the percentage to a decimal and multiply.', 1, 3),
      mc('What is the least common multiple (LCM) of 4 and 6?', ['2', '10', '12', '24'], '12', 'The LCM of 4 and 6 is the smallest number both divide evenly into. Multiples of 4: 4, 8, 12... Multiples of 6: 6, 12... LCM = 12.', 1, 4),
      mc('What is the result of 3/4 + 1/6?', ['4/10 = 2/5', '11/12', '4/24', '2/3'], '11/12', 'Find a common denominator: 12. 3/4 = 9/12, 1/6 = 2/12. 9/12 + 2/12 = 11/12.', 1, 5),
      mc('If a car travels 240 miles in 4 hours, what is its average speed?', ['60 miles per hour', '240 miles per hour', '48 miles per hour', '96 miles per hour'], '60 miles per hour', 'Average speed = distance ÷ time = 240 ÷ 4 = 60 mph.', 1, 6),
      mc('What is the absolute value of -7?', ['-7', '7', '0', '1/7'], '7', 'Absolute value is the distance from zero — it\'s always non-negative. |-7| = 7.', 1, 7),
      mc('What is 2³ × 2²?', ['2⁵ = 32', '4⁵ = 1024', '2⁶ = 64', '4⁶'], '2⁵ = 32', 'When multiplying powers with the same base, add the exponents: 2³ × 2² = 2^(3+2) = 2⁵ = 32.', 1, 8),
      oe('A store offers a 30% discount on an item originally priced at $85. What is the final price? Show your work.', 'Discount amount = 30% of $85 = 0.30 × 85 = $25.50. Final price = $85.00 − $25.50 = $59.50.', 'A correct answer should convert percent to decimal, multiply to find discount amount, then subtract from original price. Full credit requires showing the arithmetic steps.', 2, 9),
      oe('Explain in your own words why dividing by a fraction is the same as multiplying by its reciprocal.', 'Dividing by a number means finding how many times it fits. Dividing by 1/2 asks "how many halves fit into this?" — twice as many as the whole number, so you multiply by 2 (the reciprocal of 1/2). For any fraction a/b, dividing by a/b is the same as multiplying by b/a because you\'re reversing the scaling operation.', 'A strong answer gives the conceptual reasoning (not just the rule) using an example to illustrate.', 2, 10),
    ],
  },

  'pre-algebra': {
    title: 'Pre-Algebra Assessment',
    passingScore: 75,
    timeLimitMin: 30,
    questions: [
      mc('What is a variable in algebra?', ['A number that changes randomly', 'A letter representing an unknown or changing quantity', 'Any number greater than zero', 'The result of an equation'], 'A letter representing an unknown or changing quantity', 'Variables (x, y, n) are placeholders for values we don\'t yet know or that can vary — the core concept that connects arithmetic to algebra.', 1, 1),
      mc('What is the solution to 3x + 7 = 22?', ['x = 3', 'x = 5', 'x = 7', 'x = 9'], 'x = 5', '3x + 7 = 22 → 3x = 15 → x = 5. Verify: 3(5) + 7 = 15 + 7 = 22. ✓', 1, 2),
      mc('What does it mean to "combine like terms"?', ['Add all numbers in an expression', 'Add or subtract terms that have the same variable and exponent', 'Factor the expression', 'Distribute multiplication over addition'], 'Add or subtract terms that have the same variable and exponent', 'Like terms share the same variable and exponent: 3x + 5x = 8x. You cannot combine 3x and 5x² because the exponents differ.', 1, 3),
      mc('What is the distributive property?', ['a + (b + c) = (a + b) + c', 'a(b + c) = ab + ac', 'a + b = b + a', '(ab)c = a(bc)'], 'a(b + c) = ab + ac', 'The distributive property lets you multiply a factor across terms inside parentheses: 3(x + 4) = 3x + 12.', 1, 4),
      mc('What is an integer?', ['Any number including decimals', 'A whole number — positive, negative, or zero, with no fractional part', 'A positive whole number only', 'Any rational number'], 'A whole number — positive, negative, or zero, with no fractional part', 'Integers are ..., -3, -2, -1, 0, 1, 2, 3, ... — no decimals or fractions. They include negatives and zero.', 1, 5),
      mc('What is a ratio?', ['The result of division', 'A comparison of two quantities, often written as a:b or a/b', 'A percentage of a total', 'The sum of two quantities'], 'A comparison of two quantities, often written as a:b or a/b', 'Ratios compare quantities: if a class has 12 boys and 8 girls, the ratio is 12:8 = 3:2. Ratios can be simplified like fractions.', 1, 6),
      mc('How do you evaluate -3² ?', ['-9', '9', '-6', '6'], '-9', '-3² means -(3²) = -(9) = -9. Exponentiation applies to 3, then the negative sign is applied. If the entire quantity were squared, it would be (-3)² = 9.', 1, 7),
      mc('What is the solution set for |x| = 5?', ['x = 5 only', 'x = -5 only', 'x = 5 or x = -5', 'No solution'], 'x = 5 or x = -5', 'Absolute value equations have two solutions — both the positive and negative value give the same absolute value: |5| = 5 and |-5| = 5.', 1, 8),
      oe('A recipe uses 2/3 cup of sugar. If you want to make 1.5 times the recipe, how much sugar do you need? Show your work.', '1.5 × 2/3 = 3/2 × 2/3 = 6/6 = 1 cup. Or: 1.5 × 2/3 = 3.0/3 = 1 cup. You need exactly 1 cup of sugar.', 'A correct answer converts 1.5 to a fraction or uses decimal multiplication correctly, showing the computation.', 2, 9),
      oe('Explain what a proportion is and give a real-world example of when you would use one.', 'A proportion states that two ratios are equal: a/b = c/d. Example: If 3 gallons of paint cover 400 square feet, how many gallons do you need for 1,000 square feet? Set up 3/400 = x/1000, cross-multiply: 3000 = 400x, x = 7.5 gallons. Proportions are used in scaling recipes, maps, unit conversion, and any scaling problem.', 'A strong answer defines proportion correctly and solves a specific numeric example showing the setup.', 2, 10),
    ],
  },

  'algebra-i': {
    title: 'Algebra I Assessment',
    passingScore: 75,
    timeLimitMin: 30,
    questions: [
      mc('What is the slope of a line?', ['Its y-intercept', 'The ratio of vertical change to horizontal change (rise/run)', 'The length of the line', 'The x-intercept'], 'The ratio of vertical change to horizontal change (rise/run)', 'Slope (m) measures steepness: m = (y₂ - y₁)/(x₂ - x₁). Positive slopes go up right; negative slopes go down right.', 1, 1),
      mc('What is the slope-intercept form of a linear equation?', ['ax + by = c', 'y = mx + b', 'y - y₁ = m(x - x₁)', 'x/a + y/b = 1'], 'y = mx + b', 'Slope-intercept form y = mx + b directly shows the slope (m) and the y-intercept (b) — where the line crosses the y-axis.', 1, 2),
      mc('What are the solutions of x² - 5x + 6 = 0?', ['x = 2 and x = 3', 'x = -2 and x = -3', 'x = 1 and x = 6', 'x = 5 and x = 1'], 'x = 2 and x = 3', 'Factor: (x - 2)(x - 3) = 0 → x = 2 or x = 3. Verify: 4-10+6=0 ✓ and 9-15+6=0 ✓', 1, 3),
      mc('What is a function?', ['Any equation with two variables', 'A relation where each input (x) has exactly one output (y)', 'An equation with a graph', 'A polynomial with one variable'], 'A relation where each input (x) has exactly one output (y)', 'A function maps each input to exactly one output. The vertical line test: if any vertical line crosses the graph more than once, it\'s not a function.', 1, 4),
      mc('What does it mean when two linear equations have no solution?', ['They are the same line', 'The lines are parallel — same slope, different y-intercepts', 'One equation has no variables', 'The system has infinitely many solutions'], 'The lines are parallel — same slope, different y-intercepts', 'Parallel lines never intersect, so the system has no solution. Equal slopes with different y-intercepts means the lines never meet.', 1, 5),
      mc('How do you solve a system of equations by substitution?', ['Add the equations together', 'Solve one equation for a variable, substitute into the other, solve the result', 'Graph both and find intersection', 'Multiply one equation by a constant'], 'Solve one equation for a variable, substitute into the other, solve the result', 'Substitution: isolate one variable in one equation, plug that expression into the other equation, solve the single-variable equation, then back-substitute.', 1, 6),
      mc('What is the quadratic formula?', ['x = -b ± √(b²-4ac) / 2a', 'x = (-b ± √(b²+4ac)) / 2a', 'x = b/2a', 'x = -b/2a ± √(b²-4ac)'], 'x = -b ± √(b²-4ac) / 2a', 'The quadratic formula solves ax² + bx + c = 0 for any values. The discriminant (b²-4ac) determines if solutions are real: positive → two solutions, zero → one, negative → no real solutions.', 1, 7),
      mc('What is an inequality?', ['An equation with variables', 'A mathematical statement comparing two expressions using <, >, ≤, or ≥', 'An equation with no solution', 'A function with two outputs'], 'A mathematical statement comparing two expressions using <, >, ≤, or ≥', 'Inequalities describe a range of values rather than a single solution. Solving them is similar to equations, but multiplying or dividing by a negative flips the inequality sign.', 1, 8),
      oe('A linear function passes through (0, 3) and (4, 11). Find the equation in slope-intercept form.', 'Slope = (11-3)/(4-0) = 8/4 = 2. The y-intercept is 3 (point (0,3) is on the y-axis). Equation: y = 2x + 3. Verify with (4, 11): y = 2(4) + 3 = 8 + 3 = 11. ✓', 'A correct answer calculates slope, identifies y-intercept from the given point, writes the equation, and verifies.', 2, 9),
      oe('Explain what the discriminant tells you about a quadratic equation, and why this is useful.', 'The discriminant is b² - 4ac from ax² + bx + c = 0. If positive: two real solutions (parabola crosses x-axis twice). If zero: one real solution (parabola just touches x-axis). If negative: no real solutions (parabola doesn\'t cross x-axis). This is useful because you can determine how many solutions exist before solving, and in applications it tells you whether two things actually intersect (e.g., a projectile reaching a certain height).', 'A strong answer covers all three cases with their geometric meaning and gives a practical interpretation.', 2, 10),
    ],
  },

  'geometry': {
    title: 'Geometry Assessment',
    passingScore: 75,
    timeLimitMin: 30,
    questions: [
      mc('What is the sum of interior angles in a triangle?', ['90°', '180°', '270°', '360°'], '180°', 'The interior angles of any triangle always sum to 180°. This is a fundamental theorem of Euclidean geometry.', 1, 1),
      mc('What is the Pythagorean theorem?', ['a + b = c', 'a² + b² = c²', 'a² - b² = c²', '2a + 2b = c'], 'a² + b² = c²', 'In a right triangle, the square of the hypotenuse (c, the longest side opposite the right angle) equals the sum of the squares of the other two sides.', 1, 2),
      mc('What is the area formula for a circle?', ['πr', '2πr', 'πr²', 'πd'], 'πr²', 'Area of a circle = π × radius². The circumference (perimeter) is 2πr.', 1, 3),
      mc('What are supplementary angles?', ['Angles that sum to 90°', 'Angles that sum to 180°', 'Two equal angles', 'Angles that form a straight line and are equal'], 'Angles that sum to 180°', 'Supplementary angles pair to form a straight line (180°). Complementary angles sum to 90°.', 1, 4),
      mc('What is the volume of a rectangular prism (box)?', ['length × width', 'length + width + height', 'length × width × height', '2(lw + lh + wh)'], 'length × width × height', 'Volume of a rectangular prism = l × w × h. The surface area formula is 2(lw + lh + wh).', 1, 5),
      mc('What does it mean for two triangles to be congruent?', ['They are similar in shape', 'They have the same angles', 'They have identical shape and size — all corresponding sides and angles are equal', 'They have the same area'], 'They have identical shape and size — all corresponding sides and angles are equal', 'Congruent triangles are identical — same angles AND same side lengths. Similar triangles have the same angles but may differ in size.', 1, 6),
      mc('What is a transversal?', ['A line that bisects an angle', 'A line that crosses two or more parallel lines', 'The diagonal of a polygon', 'A perpendicular bisector'], 'A line that crosses two or more parallel lines', 'A transversal creates special angle pairs with parallel lines: corresponding angles (equal), alternate interior angles (equal), and co-interior angles (supplementary).', 1, 7),
      mc('What is the measure of each interior angle of a regular hexagon?', ['90°', '108°', '120°', '135°'], '120°', 'Interior angle of regular polygon = (n-2) × 180° / n. For hexagon (n=6): (6-2) × 180 / 6 = 720/6 = 120°.', 1, 8),
      oe('A right triangle has legs of length 5 and 12. Find the hypotenuse and the area of the triangle.', 'Hypotenuse: c² = 5² + 12² = 25 + 144 = 169, c = 13. Area = (1/2) × base × height = (1/2) × 5 × 12 = 30 square units.', 'A correct answer applies the Pythagorean theorem correctly and uses the triangle area formula with the two legs as base and height.', 2, 9),
      oe('A circle has a diameter of 10. Find its circumference and area. Use π ≈ 3.14.', 'Radius = 5. Circumference = 2πr = 2 × 3.14 × 5 = 31.4. Area = πr² = 3.14 × 25 = 78.5 square units.', 'A correct answer identifies radius as half the diameter, applies both formulas correctly, and shows the arithmetic.', 2, 10),
    ],
  },

  'algebra-ii': {
    title: 'Algebra II Assessment',
    passingScore: 75,
    timeLimitMin: 30,
    questions: [
      mc('What is a polynomial?', ['Any equation with variables', 'An expression with one or more terms, each being a constant times a variable raised to a non-negative integer power', 'Any function that forms a curve', 'An equation with at least two variables'], 'An expression with one or more terms, each being a constant times a variable raised to a non-negative integer power', 'Polynomials: 3x² + 2x - 5, x³ - 7, 4. Terms are added/subtracted. Exponents must be non-negative integers.', 1, 1),
      mc('What is a complex number?', ['A very large number', 'A number of the form a + bi where i = √(-1)', 'A fraction with a large denominator', 'Any irrational number'], 'A number of the form a + bi where i = √(-1)', 'Complex numbers extend the real numbers to include the imaginary unit i. They are essential for solving quadratics with negative discriminants.', 1, 2),
      mc('What is a logarithm?', ['The exponent needed to raise a base to get a given value: log_b(x) = y means b^y = x', 'The square root of a number', 'A negative exponent', 'A type of polynomial'], 'The exponent needed to raise a base to get a given value: log_b(x) = y means b^y = x', 'If 2³ = 8, then log₂(8) = 3. Logarithms and exponents are inverse operations — logarithms ask "what exponent produces this value?"', 1, 3),
      mc('What is an arithmetic sequence?', ['A sequence where each term is multiplied by a constant', 'A sequence where each term differs from the previous by a constant amount', 'A random sequence of numbers', 'A sequence of prime numbers'], 'A sequence where each term differs from the previous by a constant amount', 'Arithmetic sequences have a constant difference (d): 2, 5, 8, 11... (d=3). The nth term = a₁ + (n-1)d.', 1, 4),
      mc('What is a geometric sequence?', ['A sequence involving shapes', 'A sequence where each term is multiplied by a constant ratio', 'An arithmetic sequence in reverse', 'A sequence of perfect squares'], 'A sequence where each term is multiplied by a constant ratio', 'Geometric sequences multiply each term by a common ratio (r): 2, 6, 18, 54... (r=3). The nth term = a₁ × r^(n-1).', 1, 5),
      mc('What are the asymptotes of a rational function?', ['The x-intercepts', 'Lines that the function approaches but never crosses (vertical, horizontal, or oblique)', 'The y-intercepts', 'Points where the function equals zero'], 'Lines that the function approaches but never crosses (vertical, horizontal, or oblique)', 'Vertical asymptotes occur where the denominator equals zero. Horizontal asymptotes describe the function\'s behavior as x → ±∞.', 1, 6),
      mc('What is the inverse of a function f(x)?', ['f(-x)', 'f⁻¹(x), which reverses the input-output relationship: if f(a)=b, then f⁻¹(b)=a', '-f(x)', '1/f(x)'], 'f⁻¹(x), which reverses the input-output relationship: if f(a)=b, then f⁻¹(b)=a', 'The inverse function "undoes" f. To find it: swap x and y in y = f(x) and solve for y. The graph of f⁻¹ is a reflection of f across y = x.', 1, 7),
      mc('What does the end behavior of a polynomial describe?', ['The vertex of the parabola', 'What the function approaches as x → +∞ and x → -∞', 'The zeros of the function', 'The y-intercept value'], 'What the function approaches as x → +∞ and x → -∞', 'End behavior depends on the leading term. Even-degree positive leading coefficient: rises both ends. Odd-degree positive leading coefficient: falls left, rises right.', 1, 8),
      oe('Solve: log₂(x) + log₂(x-2) = 3. Show your work.', 'Combine logs: log₂(x(x-2)) = 3 → x(x-2) = 2³ = 8 → x² - 2x - 8 = 0 → (x-4)(x+2) = 0 → x = 4 or x = -2. Since log of negative number is undefined, reject x = -2. Answer: x = 4. Verify: log₂(4) + log₂(2) = 2 + 1 = 3. ✓', 'A correct answer combines the logarithms, converts to exponential form, solves the quadratic, and checks both solutions for domain validity.', 2, 9),
      oe('Explain the relationship between exponential growth and geometric sequences. Give a real-world example.', 'A geometric sequence with ratio r > 1 models exponential growth — each term multiplies by the same factor. For example, bacteria doubling every hour: 1, 2, 4, 8, 16... is a geometric sequence with r=2. The continuous version is the exponential function f(t) = a·rᵗ. Real examples: compound interest, population growth, viral spread. What makes exponential growth powerful (and dangerous) is that the rate of increase itself increases — it accelerates.', 'A strong answer explains the connection, gives a specific example with numbers, and explains why exponential growth is distinctive.', 2, 10),
    ],
  },

  'pre-calculus': {
    title: 'Pre-Calculus Assessment',
    passingScore: 75,
    timeLimitMin: 30,
    questions: [
      mc('What is a radian?', ['A degree of arc', 'An angle where the arc length equals the radius — approximately 57.3°', 'Half a degree', 'A unit of angular velocity'], 'An angle where the arc length equals the radius — approximately 57.3°', 'Radians measure angles as a ratio of arc length to radius. A full circle = 2π radians = 360°. Radians are the natural unit for calculus.', 1, 1),
      mc('What does sin²(θ) + cos²(θ) equal?', ['0', '2', '1', 'sin(2θ)'], '1', 'The Pythagorean identity sin²(θ) + cos²(θ) = 1 holds for all angles and derives from the unit circle definition of sine and cosine.', 1, 2),
      mc('What is the period of f(x) = sin(x)?', ['π', '2π', 'π/2', '4π'], '2π', 'The sine function completes one full cycle every 2π radians. After 2π, the pattern repeats exactly.', 1, 3),
      mc('What is a unit circle?', ['A circle with diameter 1', 'A circle with radius 1 centered at the origin — used to define trigonometric functions', 'A circle with circumference 1', 'Any circle of standard size'], 'A circle with radius 1 centered at the origin — used to define trigonometric functions', 'The unit circle defines sin and cos for all angles: a point at angle θ has coordinates (cos θ, sin θ). It extends trig beyond right triangles to all angles.', 1, 4),
      mc('What is a vector?', ['A point in space', 'A quantity with both magnitude and direction', 'A matrix with one row', 'A scalar that can be negative'], 'A quantity with both magnitude and direction', 'Vectors have both size (magnitude) and direction — like velocity (60 mph northeast) as opposed to speed (60 mph, scalar). Represented as arrows or coordinate pairs.', 1, 5),
      mc('What is the relationship between e^(ln x) and x?', ['They are always different', 'e^(ln x) = x for all x > 0, because e^x and ln are inverse functions', 'e^(ln x) = 1/x', 'e^(ln x) = x²'], 'e^(ln x) = x for all x > 0, because e^x and ln are inverse functions', 'The natural exponential function and natural logarithm are inverses: applying one then the other returns to x. This cancellation is fundamental to solving exponential and log equations.', 1, 6),
      mc('What is the dot product of vectors a and b?', ['The vector perpendicular to both a and b', 'A scalar: |a||b|cos(θ) where θ is the angle between them', 'The sum of corresponding components', 'The product of their magnitudes only'], 'A scalar: |a||b|cos(θ) where θ is the angle between them', 'The dot product a·b = a₁b₁ + a₂b₂ = |a||b|cos(θ). When the dot product is zero, vectors are perpendicular (θ = 90°).', 1, 7),
      mc('What is a limit in mathematics?', ['The maximum value of a function', 'The value a function approaches as the input approaches a given value', 'The highest point on a curve', 'A constraint in an optimization problem'], 'The value a function approaches as the input approaches a given value', 'Limits describe function behavior near a point, not necessarily at the point. lim(x→a) f(x) = L means f(x) gets arbitrarily close to L as x approaches a.', 1, 8),
      oe('Explain what happens to sin(θ) and cos(θ) at θ = 0, π/2, π, and 3π/2 on the unit circle.', 'At θ=0: (cos, sin) = (1, 0). At θ=π/2: (0, 1). At θ=π: (-1, 0). At θ=3π/2: (0, -1). These are the key anchor points on the unit circle. cos starts at 1 and follows the x-coordinate; sin starts at 0 and follows the y-coordinate. Together they trace the circle.', 'A complete answer gives all four coordinate pairs with correct values and explains what they represent on the unit circle.', 2, 9),
      oe('What is the intuitive idea behind a limit, and why is it needed before learning calculus?', 'A limit asks what value a function approaches as the input gets closer and closer to a point — even if the function isn\'t defined there. This is needed for calculus because derivatives require taking the limit of a ratio as the interval shrinks to zero (instantaneous rate of change). Without limits, division by zero makes this undefined. Limits provide the rigorous foundation for differentiation and integration.', 'A strong answer explains the approaching-without-reaching idea and connects limits to the derivative definition.', 2, 10),
    ],
  },

  'calculus': {
    title: 'Calculus Assessment',
    passingScore: 75,
    timeLimitMin: 30,
    questions: [
      mc('What does a derivative represent geometrically?', ['The area under a curve', 'The slope of the tangent line at a point', 'The maximum value of a function', 'The distance a point is from the origin'], 'The slope of the tangent line at a point', 'The derivative f\'(x) gives the instantaneous rate of change — geometrically, the slope of the tangent line to f(x) at that point.', 1, 1),
      mc('What is the power rule for differentiation?', ['d/dx[xⁿ] = xⁿ⁻¹', 'd/dx[xⁿ] = nxⁿ⁻¹', 'd/dx[xⁿ] = n·xⁿ', 'd/dx[xⁿ] = xⁿ/n'], 'd/dx[xⁿ] = nxⁿ⁻¹', 'Power rule: bring down the exponent and reduce it by 1. d/dx[x³] = 3x², d/dx[x⁵] = 5x⁴.', 1, 2),
      mc('What does an integral represent geometrically?', ['The slope of a function', 'The area under the curve between two limits', 'The maximum of a function', 'The rate of change at a point'], 'The area under the curve between two limits', 'The definite integral ∫[a to b] f(x)dx represents the net signed area between the curve and the x-axis from x=a to x=b.', 1, 3),
      mc('What is the Fundamental Theorem of Calculus?', ['Derivatives and integrals have no relationship', 'Differentiation and integration are inverse operations, and the integral of f from a to b equals F(b) - F(a)', 'All continuous functions are differentiable', 'Integration is the limit of a sum only'], 'Differentiation and integration are inverse operations, and the integral of f from a to b equals F(b) - F(a)', 'The FTC connects derivatives and integrals: if F is an antiderivative of f, then ∫[a to b] f(x)dx = F(b) - F(a). Differentiation undoes integration and vice versa.', 1, 4),
      mc('What does f\'(x) > 0 tell you about f(x)?', ['f(x) is concave up', 'f(x) is increasing at x', 'f(x) has a maximum at x', 'f(x) is positive at x'], 'f(x) is increasing at x', 'When the derivative is positive, the function has a positive slope — it\'s increasing. When f\'(x) < 0, f is decreasing. When f\'(x) = 0, f has a critical point (possible max or min).', 1, 5),
      mc('What is the chain rule?', ['d/dx[f(x) + g(x)] = f\'(x) + g\'(x)', 'd/dx[f(g(x))] = f\'(g(x)) · g\'(x)', 'd/dx[f(x)·g(x)] = f\'(x)·g(x) + f(x)·g\'(x)', 'd/dx[f(x)/g(x)] = (f\'g - fg\')/g²'], 'd/dx[f(g(x))] = f\'(g(x)) · g\'(x)', 'The chain rule differentiates composite functions: derivative of the outside (evaluated at the inside) times the derivative of the inside. Example: d/dx[sin(x²)] = cos(x²) · 2x.', 1, 6),
      mc('What is a critical point?', ['Where the function is zero', 'Where f\'(x) = 0 or f\'(x) is undefined — potential max, min, or inflection point', 'The highest point on the function', 'Where the function changes sign'], 'Where f\'(x) = 0 or f\'(x) is undefined — potential max, min, or inflection point', 'Critical points are candidates for local maxima and minima. Use the second derivative test: f\'\'(x) > 0 at a critical point means local min; f\'\'(x) < 0 means local max.', 1, 7),
      mc('What does the integral ∫ 2x dx equal?', ['2x²', 'x² + C', '2 + C', 'x² /2 + C'], 'x² + C', '∫ 2x dx: power rule for integrals — raise power by 1, divide by new power: 2x²/2 = x². Add the constant of integration C.', 1, 8),
      oe('A particle\'s position is given by s(t) = t³ - 6t² + 9t. Find its velocity at t = 2 and determine if the particle is moving forward or backward.', 'Velocity = s\'(t) = 3t² - 12t + 9. At t=2: v(2) = 3(4) - 12(2) + 9 = 12 - 24 + 9 = -3. Since velocity is negative at t=2, the particle is moving backward (in the negative direction).', 'A correct answer takes the derivative using the power rule, evaluates at t=2, and interprets the sign of velocity.', 2, 9),
      oe('Explain in words what the Fundamental Theorem of Calculus tells us about the relationship between derivatives and integrals.', 'The FTC reveals that differentiation and integration are inverse processes. Part 1: the derivative of the integral of f is f itself. Part 2: to evaluate a definite integral, find an antiderivative F and compute F(b) - F(a). This means areas under curves can be computed analytically (not just approximated numerically) using antiderivatives. It unifies two independently developed concepts into one coherent framework.', 'A strong answer explains both parts and emphasizes that the FTC connects two apparently separate concepts into a unified inverse relationship.', 2, 10),
    ],
  },

  'statistics': {
    title: 'Statistics Assessment',
    passingScore: 75,
    timeLimitMin: 30,
    questions: [
      mc('What is the difference between mean, median, and mode?', ['They are all the same', 'Mean is average, median is middle value, mode is most frequent value', 'Median is average, mean is middle', 'Mode is always equal to the mean'], 'Mean is average, median is middle value, mode is most frequent value', 'Mean = sum/count. Median = middle value when sorted. Mode = most frequent value. For skewed data, median is often a better measure of center than mean.', 1, 1),
      mc('What is standard deviation?', ['The range of the data', 'A measure of spread — how much data values deviate from the mean on average', 'The middle value', 'The most common value'], 'A measure of spread — how much data values deviate from the mean on average', 'Standard deviation measures dispersion. Small SD means data clusters near the mean; large SD means data is spread out. Variance is the squared standard deviation.', 1, 2),
      mc('What is a normal distribution?', ['Any symmetric dataset', 'A bell-shaped distribution described by its mean and standard deviation, where ~68% of data falls within 1 SD of the mean', 'A distribution with no outliers', 'A perfectly uniform spread of data'], 'A bell-shaped distribution described by its mean and standard deviation, where ~68% of data falls within 1 SD of the mean', 'The normal (Gaussian) distribution appears throughout nature and statistics. The empirical rule: 68% within 1 SD, 95% within 2 SD, 99.7% within 3 SD of the mean.', 1, 3),
      mc('What does correlation measure?', ['Causation between variables', 'The strength and direction of a linear relationship between two variables', 'The average of two variables', 'Whether one variable predicts the other exactly'], 'The strength and direction of a linear relationship between two variables', 'Correlation (r) ranges from -1 to 1. r = 1: perfect positive linear relationship. r = -1: perfect negative. r = 0: no linear relationship. Correlation does not imply causation.', 1, 4),
      mc('What is a p-value in hypothesis testing?', ['The probability the null hypothesis is true', 'The probability of observing results as extreme as observed, assuming the null hypothesis is true', 'The size of the effect', 'The significance level you set before testing'], 'The probability of observing results as extreme as observed, assuming the null hypothesis is true', 'A small p-value (typically < 0.05) means the observed data would be unlikely if the null hypothesis were true — suggesting the null should be rejected.', 1, 5),
      mc('What is sampling bias?', ['Collecting too small a sample', 'When the sample is not representative of the population, leading to skewed results', 'Using the wrong statistical test', 'When sample size is too large'], 'When the sample is not representative of the population, leading to skewed results', 'Sampling bias occurs when certain population members are more or less likely to be included in the sample — making results that work for the sample misleading for the whole population.', 1, 6),
      mc('What is a confidence interval?', ['The range the true population parameter likely falls within, at a given confidence level', 'A range that definitely contains the true value', 'The standard deviation of the sample', 'A probability that a hypothesis is correct'], 'The range the true population parameter likely falls within, at a given confidence level', 'A 95% confidence interval means: if we repeated the study many times, 95% of the calculated intervals would contain the true parameter. It does NOT mean there\'s a 95% chance the true value is in this specific interval.', 1, 7),
      mc('What is the difference between descriptive and inferential statistics?', ['Descriptive uses more data', 'Descriptive summarizes existing data; inferential draws conclusions about populations from samples', 'Inferential only uses census data', 'They are the same thing'], 'Descriptive summarizes existing data; inferential draws conclusions about populations from samples', 'Descriptive stats (mean, charts) describe the data you have. Inferential stats (hypothesis tests, confidence intervals) use sample data to make claims about a larger population.', 1, 8),
      oe('A researcher claims that a new drug reduces blood pressure. They ran a study and got p = 0.04. What does this mean, and does it prove the drug works?', 'p = 0.04 means there\'s a 4% probability of seeing results this extreme (or more) by chance alone if the drug has no effect. Since p < 0.05, it\'s statistically significant by conventional standards. However: it does NOT prove the drug works. It means the result is unlikely due to chance — but it could be a Type I error (false positive), confounded by other factors, or statistically significant but clinically trivial. Statistical significance ≠ practical importance.', 'A strong answer correctly defines p-value, notes statistical significance, AND points out limitations/caveats.', 2, 9),
      oe('Why is "correlation does not imply causation" one of the most important concepts in statistics?', 'Two variables can correlate perfectly without one causing the other: (1) reverse causation (maybe B causes A, not A causes B), (2) confounding variable (a third variable C causes both A and B), (3) coincidence (ice cream sales and drowning rates both rise in summer — because of heat). Claiming causation from correlation alone can lead to wrong policies, wasted resources, and harmful interventions. Establishing causation requires controlled experiments or careful observational study design.', 'A strong answer gives at least two alternative explanations for correlation (confounding, reverse causation) and explains the practical stakes.', 2, 10),
    ],
  },
}
