import type { AssessmentDef, AssessmentQuestionDef } from '../types'

const mc = (q: string, opts: string[], ans: string, exp: string, pts: number, ord: number): AssessmentQuestionDef =>
  ({ question: q, type: 'MULTIPLE_CHOICE', options: opts, correctAnswer: ans, explanation: exp, points: pts, order: ord })

const oe = (q: string, ans: string, exp: string, pts: number, ord: number): AssessmentQuestionDef =>
  ({ question: q, type: 'OPEN_ENDED', correctAnswer: ans, explanation: exp, points: pts, order: ord })

export const personalFinanceAssessments: Record<string, AssessmentDef> = {
  'budgeting-and-managing-money': {
    title: 'Budgeting and Managing Money Assessment',
    passingScore: 75,
    timeLimitMin: 30,
    questions: [
      mc('What is a budget?', ['A bank account type', 'A plan for how to allocate income across expenses and savings', 'A government tax document', 'A type of investment'], 'A plan for how to allocate income across expenses and savings', 'A budget is a written plan that assigns your income to specific categories — bills, food, savings, entertainment — so you control where your money goes.', 1, 1),
      mc('What does the 50/30/20 rule suggest?', ['50% savings, 30% rent, 20% food', '50% needs, 30% wants, 20% savings/debt', '50% fixed costs, 30% taxes, 20% fun', '50% investing, 30% bills, 20% spending'], '50% needs, 30% wants, 20% savings/debt', 'The 50/30/20 rule is a simple budgeting guideline: half your after-tax income to needs, 30% to wants, 20% to savings and debt repayment.', 1, 2),
      mc('What is a fixed expense?', ['An expense you can choose to skip', 'A cost that stays the same each month', 'An unexpected emergency cost', 'A one-time purchase'], 'A cost that stays the same each month', 'Fixed expenses — like rent, car payments, and insurance — are predictable and the same amount every billing cycle.', 1, 3),
      mc('What is an emergency fund?', ['Money invested in stocks for emergencies', 'Cash set aside for unexpected expenses', 'A line of credit at the bank', 'A government assistance program'], 'Cash set aside for unexpected expenses', 'An emergency fund is liquid savings kept accessible for unexpected events like job loss, car repairs, or medical bills — typically 3–6 months of expenses.', 1, 4),
      mc('What does "living within your means" mean?', ['Only buying things on sale', 'Spending less than or equal to what you earn', 'Having a high income', 'Avoiding credit cards entirely'], 'Spending less than or equal to what you earn', 'Living within your means means your spending doesn\'t exceed your income. It\'s the foundation of financial stability.', 1, 5),
      mc('What is net income?', ['Income before taxes', 'Total sales revenue', 'Take-home pay after taxes and deductions', 'Gross income plus bonuses'], 'Take-home pay after taxes and deductions', 'Net income is what you actually receive after all deductions — taxes, health insurance, retirement contributions — are taken out of your paycheck.', 1, 6),
      mc('Which of the following is a discretionary expense?', ['Rent', 'Electricity bill', 'Streaming service subscription', 'Car insurance'], 'Streaming service subscription', 'Discretionary expenses are non-essential — things you choose to spend on but don\'t need for basic living, like entertainment, dining out, or subscriptions.', 1, 7),
      mc('Why is tracking spending important even if you have a budget?', ['To impress your bank', 'To identify where you overspend and adjust accordingly', 'To avoid paying taxes', 'Tracking is unnecessary if you have a budget'], 'To identify where you overspend and adjust accordingly', 'A budget is a plan, but tracking is reality-checking. It shows where your actual spending diverges from the plan so you can make corrections.', 1, 8),
      oe('Describe what your ideal monthly budget would look like. What categories would you include and roughly what percentage of income would each get?', 'An ideal budget covers needs (housing, utilities, food, transportation), savings, debt repayment, and discretionary spending. The 50/30/20 rule is a common starting point. Priorities vary by situation — someone with debt might allocate more to repayment; someone with no emergency fund prioritizes savings first.', 'A strong answer shows understanding of categories and explains reasoning for allocations — not just listing random percentages.', 2, 9),
      oe('Why do most financial experts say to "pay yourself first"? What does this mean practically?', 'Paying yourself first means automatically transferring money to savings before spending on anything else. It works because humans spend what\'s available — if savings comes out automatically, you adapt your spending to what\'s left instead of saving whatever remains (which is often nothing).', 'The answer should explain the behavioral reason (automatic savings beats relying on willpower) not just define the phrase.', 2, 10),
    ],
  },

  'debt-and-credit': {
    title: 'Debt and Credit Assessment',
    passingScore: 75,
    timeLimitMin: 30,
    questions: [
      mc('What is a credit score?', ['The total amount of debt you owe', 'A numerical rating of your creditworthiness based on your credit history', 'Your bank account balance', 'How much credit you have available'], 'A numerical rating of your creditworthiness based on your credit history', 'Credit scores (like FICO) range 300–850 and tell lenders how likely you are to repay debt. Higher scores mean better loan terms.', 1, 1),
      mc('Which factor has the biggest impact on your credit score?', ['Length of credit history', 'Credit utilization ratio', 'Payment history', 'Number of credit accounts'], 'Payment history', 'Payment history is the largest component of most credit scores — whether you pay bills on time is the strongest signal of creditworthiness.', 1, 2),
      mc('What is APR?', ['Annual Profit Rate', 'The yearly cost of borrowing including interest and fees', 'A type of bank account', 'A credit card reward system'], 'The yearly cost of borrowing including interest and fees', 'APR (Annual Percentage Rate) is the total annual cost of borrowing — it includes the interest rate plus any fees, making it the true cost of a loan or credit card.', 1, 3),
      mc('What is a debt-to-income ratio?', ['How much you earn versus how much you spend', 'Your monthly debt payments divided by your gross monthly income', 'The interest rate on your debts', 'Your credit limit divided by your balance'], 'Your monthly debt payments divided by your gross monthly income', 'DTI ratio compares your debt obligations to your income. Lenders use it to assess whether you can take on more debt — lower is better.', 1, 4),
      mc('What happens if you only pay the minimum balance on a credit card?', ['Your debt is paid off faster', 'You pay more interest over time and stay in debt longer', 'Your credit score improves quickly', 'The interest rate is reduced'], 'You pay more interest over time and stay in debt longer', 'Minimum payments are designed to keep you in debt. Most of the payment covers interest, leaving the principal barely touched — the card company profits while your payoff date stretches out.', 1, 5),
      mc('What is the debt avalanche method?', ['Paying off the smallest debt first', 'Paying off the highest-interest debt first', 'Taking out a new loan to consolidate', 'Ignoring small debts and focusing on large ones'], 'Paying off the highest-interest debt first', 'The avalanche method minimizes total interest paid by tackling the most expensive debt first while paying minimums on the rest.', 1, 6),
      mc('What does it mean when a debt goes to collections?', ['You paid it off successfully', 'A third party has purchased or been assigned the debt to collect it from you', 'The debt is forgiven', 'The bank has lowered your interest rate'], 'A third party has purchased or been assigned the debt to collect it from you', 'When a debt goes to collections, it means the original creditor gave up collecting and sold the debt to a collection agency, which seriously damages your credit score.', 1, 7),
      mc('What is credit utilization?', ['The number of credit cards you have', 'How long you\'ve had your credit accounts', 'The percentage of your available credit you\'re using', 'How many times you\'ve applied for credit'], 'The percentage of your available credit you\'re using', 'Credit utilization is your balance divided by your credit limit. Keeping it below 30% helps your credit score — lower is generally better.', 1, 8),
      oe('Compare the debt snowball and debt avalanche methods. Which would you use and why?', 'Snowball: pay smallest debt first for psychological wins and motivation. Avalanche: pay highest interest debt first to minimize total interest paid. Snowball costs more mathematically but keeps people motivated. Avalanche is optimal financially. The best method is the one you\'ll actually stick with.', 'A complete answer explains both methods, their pros/cons, and gives a reasoned preference.', 2, 9),
      oe('How does interest work on a credit card, and why can a small balance become a large debt over time?', 'Credit cards charge a daily periodic rate (APR divided by 365) on any unpaid balance. Interest compounds — meaning interest is charged on interest. A $1,000 balance at 24% APR costs about $240/year in interest alone. If you only pay minimums, the balance barely drops and you pay interest for years.', 'The answer should explain compounding interest and show why minimum payments are a trap.', 2, 10),
    ],
  },

  'banking-and-accounts': {
    title: 'Banking and Accounts Assessment',
    passingScore: 75,
    timeLimitMin: 30,
    questions: [
      mc('What is the main difference between a checking and savings account?', ['Checking earns more interest', 'Checking is for frequent transactions; savings is for storing money and earning interest', 'Savings accounts have debit cards', 'There is no difference'], 'Checking is for frequent transactions; savings is for storing money and earning interest', 'Checking accounts are designed for day-to-day transactions. Savings accounts are meant to hold money longer-term and typically earn higher interest.', 1, 1),
      mc('What does FDIC insurance protect?', ['Your investments in stocks', 'Bank deposits up to $250,000 per depositor per bank', 'Your home mortgage', 'All money in all accounts regardless of amount'], 'Bank deposits up to $250,000 per depositor per bank', 'The FDIC insures deposits at member banks up to $250,000 per depositor per institution, protecting your money if the bank fails.', 1, 2),
      mc('What is a routing number?', ['Your personal account number', 'A number identifying your specific bank or credit union', 'A transaction confirmation code', 'Your bank\'s customer ID number'], 'A number identifying your specific bank or credit union', 'The routing number (9 digits) identifies the financial institution. It\'s used for direct deposits and wire transfers along with your account number.', 1, 3),
      mc('What is an overdraft?', ['Extra money in your account', 'When you spend more than your account balance', 'A fee for large transfers', 'When a check bounces from another person'], 'When you spend more than your account balance', 'An overdraft occurs when you spend more than your available balance. Banks may cover it (charging a fee) or decline the transaction.', 1, 4),
      mc('What is the main advantage of a credit union over a traditional bank?', ['Credit unions have more locations', 'Credit unions are nonprofit and often offer better rates and lower fees', 'Credit unions are insured by the FDIC', 'Credit unions offer more products'], 'Credit unions are nonprofit and often offer better rates and lower fees', 'Credit unions are member-owned nonprofits that return profits to members in the form of lower fees, better loan rates, and higher savings rates.', 1, 5),
      mc('What is a wire transfer?', ['Sending money via phone', 'An electronic transfer of funds between banks, often used for large or urgent amounts', 'A check sent by mail', 'An ATM deposit'], 'An electronic transfer of funds between banks, often used for large or urgent amounts', 'Wire transfers move money directly between bank accounts electronically and are typically used for large amounts, real estate closings, or international transfers.', 1, 6),
      mc('What does "interest rate" mean on a savings account?', ['The fee charged for holding your money', 'The percentage of your balance the bank pays you annually for keeping money there', 'The minimum balance requirement', 'The penalty for early withdrawal'], 'The percentage of your balance the bank pays you annually for keeping money there', 'A savings account interest rate is what the bank pays you to use your money. Higher rates mean your savings grow faster.', 1, 7),
      mc('What is a monthly statement?', ['A bill from your bank', 'A summary of all account transactions and balances over the month', 'A credit report', 'A tax document'], 'A summary of all account transactions and balances over the month', 'Monthly statements list all deposits, withdrawals, fees, and interest for the period — essential for tracking activity and catching errors or fraud.', 1, 8),
      oe('Why is it important to reconcile (review) your bank statements regularly?', 'Reconciling catches errors, unauthorized charges, and fraud. Banks can make mistakes, and thieves use small charges hoping they go unnoticed. Reviewing statements also helps you understand your spending patterns and ensure no bills were missed or doubled.', 'A strong answer mentions fraud detection and error catching — not just "to know your balance."', 2, 9),
      oe('What factors should you consider when choosing where to keep your money?', 'Key factors: interest rates on savings, fee structures (monthly fees, overdraft fees, ATM fees), FDIC/NCUA insurance, account minimums, online access, branch availability, and customer service. The best bank minimizes fees and maximizes what you earn on your deposits.', 'The answer should list multiple factors with reasoning — not just "go where rates are highest."', 2, 10),
    ],
  },

  'investing-basics': {
    title: 'Investing Basics Assessment',
    passingScore: 75,
    timeLimitMin: 30,
    questions: [
      mc('What is a stock?', ['A loan to a company', 'A share of ownership in a company', 'A government-issued bond', 'A type of savings account'], 'A share of ownership in a company', 'When you buy stock, you become a partial owner (shareholder) of that company and may benefit from its growth and profits.', 1, 1),
      mc('What is a bond?', ['Ownership in a company', 'A loan you make to a government or corporation that pays interest', 'A certificate of deposit', 'A mutual fund with low risk'], 'A loan you make to a government or corporation that pays interest', 'Bonds are debt instruments — the issuer borrows money from investors and promises to pay interest and return the principal at maturity.', 1, 2),
      mc('What is compound interest?', ['Interest paid only on the original principal', 'Interest calculated on both the principal and previously earned interest', 'A fixed interest rate over time', 'Interest paid twice a year'], 'Interest calculated on both the principal and previously earned interest', 'Compounding is when your earnings generate their own earnings. Over time this creates exponential growth — the key to long-term wealth building.', 1, 3),
      mc('What is diversification?', ['Putting all your money in one investment', 'Spreading investments across different assets to reduce risk', 'Investing only in government bonds', 'Choosing high-risk investments only'], 'Spreading investments across different assets to reduce risk', 'Diversification reduces risk by ensuring a loss in one investment doesn\'t destroy your entire portfolio — if one asset falls, others may hold or rise.', 1, 4),
      mc('What is an index fund?', ['A fund managed by an expert picking individual stocks', 'A fund that tracks a market index like the S&P 500', 'A fund only available to wealthy investors', 'A fund that invests only in bonds'], 'A fund that tracks a market index like the S&P 500', 'Index funds passively replicate a market index. They offer broad diversification, low fees, and have historically outperformed most actively managed funds.', 1, 5),
      mc('What is risk tolerance in investing?', ['The maximum amount you can invest', 'Your ability and willingness to endure investment losses in pursuit of gains', 'The minimum return you require', 'How long you plan to invest'], 'Your ability and willingness to endure investment losses in pursuit of gains', 'Risk tolerance shapes your investment strategy. High tolerance means you can weather volatility; low tolerance means you need more stable, lower-return investments.', 1, 6),
      mc('What does "buy low, sell high" mean?', ['Always buy the cheapest stocks', 'Purchase assets when prices are low and sell when they\'ve risen', 'Avoid selling any investments', 'Time the market perfectly'], 'Purchase assets when prices are low and sell when they\'ve risen', 'The core principle of investing for profit — buy when prices are depressed and sell after they\'ve appreciated. Easier said than done in practice.', 1, 7),
      mc('What is a 401(k)?', ['A type of health insurance', 'An employer-sponsored retirement savings account with tax advantages', 'A government pension program', 'A high-yield savings account'], 'An employer-sponsored retirement savings account with tax advantages', 'A 401(k) lets employees save pre-tax income for retirement. Many employers match contributions, making it one of the most valuable employee benefits.', 1, 8),
      oe('Explain why starting to invest early matters so much, using the concept of compounding.', 'Compounding means returns generate more returns. Starting at 22 vs. 32 gives 10 extra years of compounding. Even modest contributions grow dramatically over decades. A 25-year-old investing $200/month at 7% annual return will have far more at 65 than someone who starts at 35 investing $400/month — time matters more than contribution size.', 'The answer must explain the mechanism of compounding, not just say "start early to have more time."', 2, 9),
      oe('What is the difference between saving and investing, and when is each appropriate?', 'Saving means keeping money in low-risk accounts (savings, CDs) for short-term goals or emergencies — it\'s stable but earns little. Investing means putting money into assets that may grow over time but carry risk — appropriate for long-term goals (retirement, college) where you have time to recover from downturns. The rule of thumb: don\'t invest money you need within 3–5 years.', 'A strong answer distinguishes risk level, time horizon, and purpose — not just "saving is safe, investing grows money."', 2, 10),
    ],
  },

  'insurance-fundamentals': {
    title: 'Insurance Fundamentals Assessment',
    passingScore: 75,
    timeLimitMin: 30,
    questions: [
      mc('What is the primary purpose of insurance?', ['To guarantee you profit from accidents', 'To transfer financial risk from an individual to an insurer', 'To save money on medical bills', 'To build wealth over time'], 'To transfer financial risk from an individual to an insurer', 'Insurance pools risk — you pay premiums so that if a covered loss occurs, the insurer covers the financial damage instead of you absorbing it alone.', 1, 1),
      mc('What is a deductible?', ['The monthly fee you pay for insurance', 'The amount you pay out-of-pocket before insurance kicks in', 'The maximum your insurer will pay', 'A discount for safe drivers'], 'The amount you pay out-of-pocket before insurance kicks in', 'The deductible is your share of a covered loss before the insurance company starts paying. Higher deductibles mean lower premiums.', 1, 2),
      mc('What is a premium?', ['The maximum payout from an insurer', 'The regular payment you make to keep insurance active', 'A bonus for filing no claims', 'A one-time fee at signup'], 'The regular payment you make to keep insurance active', 'Premiums are regular payments (monthly, quarterly, annually) that keep your insurance policy in force. Stop paying and your coverage lapses.', 1, 3),
      mc('What does liability insurance cover?', ['Damage to your own property', 'Harm or damage you cause to other people or their property', 'Your medical bills', 'Your vehicle repairs'], 'Harm or damage you cause to other people or their property', 'Liability coverage pays for injury or property damage you cause to others — it\'s required in auto insurance and essential in business coverage.', 1, 4),
      mc('What is a copay in health insurance?', ['The total amount you pay for the year', 'A fixed fee you pay for a specific service, like a doctor visit', 'The amount your employer contributes', 'Your monthly insurance bill'], 'A fixed fee you pay for a specific service, like a doctor visit', 'Copays are set amounts (e.g., $25 per office visit) you pay at the time of service, separate from deductibles and coinsurance.', 1, 5),
      mc('What does term life insurance cover?', ['Your whole life', 'A specific period, paying a death benefit if you die during that term', 'Funeral expenses only', 'Medical bills at end of life'], 'A specific period, paying a death benefit if you die during that term', 'Term life insurance is the simplest life insurance — pure death benefit coverage for a defined number of years. No cash value. Lower cost than whole life.', 1, 6),
      mc('Why is renters insurance recommended even for people who rent?', ['Landlords require it by law', 'It covers your personal belongings and liability, which your landlord\'s insurance doesn\'t', 'It replaces your security deposit', 'It pays your rent if you lose income'], 'It covers your personal belongings and liability, which your landlord\'s insurance doesn\'t', 'Landlord insurance covers the building, not your stuff. Renters insurance covers your belongings against theft, fire, or damage and provides liability protection — often for just $15–30/month.', 1, 7),
      mc('What is an out-of-pocket maximum in health insurance?', ['The highest monthly premium you can pay', 'The most you\'ll pay in a year before insurance covers 100% of covered costs', 'The deductible amount', 'The copay for emergency care'], 'The most you\'ll pay in a year before insurance covers 100% of covered costs', 'Once you hit your out-of-pocket maximum (deductible + copays + coinsurance), the insurer pays 100% of covered services for the rest of the year.', 1, 8),
      oe('Explain the trade-off between high-deductible and low-deductible insurance plans. When might each be better?', 'High deductible = lower premium. Good if you\'re healthy and rarely use insurance — you save on premiums and only pay more if something major happens (and you keep savings to cover the deductible). Low deductible = higher premium. Better if you have chronic conditions, frequent doctor visits, or can\'t afford a surprise large bill.', 'A strong answer explains the premium-deductible trade-off and gives a concrete scenario for each type.', 2, 9),
      oe('Why is it risky to be uninsured, even if you\'re young and healthy?', 'Accidents and sudden illnesses don\'t discriminate by age. An ER visit without insurance can cost tens of thousands of dollars. A car accident where you\'re at fault can result in a lawsuit for damages you can\'t pay. Being uninsured turns any major event into a potential financial catastrophe.', 'The answer should mention specific catastrophic scenarios — not just "you might get sick."', 2, 10),
    ],
  },

  'taxes-for-individuals': {
    title: 'Taxes for Individuals Assessment',
    passingScore: 75,
    timeLimitMin: 30,
    questions: [
      mc('What is a W-2 form?', ['A form you fill out when starting a new job', 'A form showing wages earned and taxes withheld, sent by your employer', 'A form for self-employment income', 'A request for tax refund'], 'A form showing wages earned and taxes withheld, sent by your employer', 'The W-2 is the annual wage statement employers provide by January 31 showing total pay and taxes withheld during the year — required to file your return.', 1, 1),
      mc('What is the difference between a tax deduction and a tax credit?', ['There is no difference', 'Deductions reduce taxable income; credits directly reduce the tax you owe', 'Credits reduce income; deductions reduce tax owed', 'Credits apply only to businesses'], 'Deductions reduce taxable income; credits directly reduce the tax you owe', 'Deductions lower the income that gets taxed. Credits subtract directly from your tax bill. Credits are generally more valuable dollar-for-dollar.', 1, 2),
      mc('What does filing status affect?', ['Only your state taxes', 'Your tax bracket, standard deduction, and eligibility for certain credits', 'Your employer\'s tax obligations', 'Nothing — it\'s only for record-keeping'], 'Your tax bracket, standard deduction, and eligibility for certain credits', 'Filing status (Single, Married Filing Jointly, Head of Household, etc.) determines your tax rate thresholds, deduction amounts, and credit eligibility.', 1, 3),
      mc('What is a progressive tax system?', ['Everyone pays the same tax rate', 'Higher earners pay a higher percentage of income in taxes', 'Taxes increase with inflation automatically', 'A system where only the wealthy are taxed'], 'Higher earners pay a higher percentage of income in taxes', 'In a progressive system, tax rates increase across income brackets. Higher income means a higher marginal rate — but only on income above each threshold.', 1, 4),
      mc('What is a tax refund?', ['Free money from the government', 'The repayment of taxes you overpaid during the year', 'A bonus for filing early', 'Money the government saved for you'], 'The repayment of taxes you overpaid during the year', 'A refund means your withholding or estimated payments exceeded your actual tax bill. It\'s not a gift — it\'s your own money returned.', 1, 5),
      mc('What is the standard deduction?', ['A flat amount subtracted from income before calculating tax', 'A deduction for standard business expenses', 'The government\'s suggested charitable donation', 'A credit for low-income earners'], 'A flat amount subtracted from income before calculating tax', 'The standard deduction is a fixed dollar amount you can subtract from income without itemizing. Most filers take it because it exceeds their itemized deductions.', 1, 6),
      mc('Who must file a federal tax return?', ['Everyone, regardless of income', 'Only people who owe taxes', 'People whose income exceeds IRS minimum thresholds', 'Only employees, not self-employed people'], 'People whose income exceeds IRS minimum thresholds', 'Filing requirements depend on income level, filing status, and age. Most people with income above a threshold must file, even if they don\'t owe taxes (and may be due a refund).', 1, 7),
      mc('What is FICA?', ['A tax on investments', 'Payroll taxes that fund Social Security and Medicare', 'Federal Income Collection Act', 'A state sales tax program'], 'Payroll taxes that fund Social Security and Medicare', 'FICA (Federal Insurance Contributions Act) taxes are automatically withheld from paychecks — 6.2% for Social Security and 1.45% for Medicare, matched by your employer.', 1, 8),
      oe('Explain the difference between your marginal tax rate and your effective tax rate. Why does this distinction matter?', 'Marginal rate is the rate on your last dollar earned — the highest bracket you reach. Effective rate is total taxes paid divided by total income — your actual average rate. Someone in the 22% bracket doesn\'t pay 22% on all income; lower income is taxed at lower rates. The distinction matters because people often overestimate their tax burden.', 'A strong answer explains both terms and clarifies that marginal rate doesn\'t apply to all income.', 2, 9),
      oe('Why might someone choose to have more taxes withheld from each paycheck even though it means a bigger refund instead of that money throughout the year?', 'Some people use overwithholding as forced savings — they\'d otherwise spend the money and end up with nothing saved. The downside is giving the government an interest-free loan. Financially, it\'s better to withhold correctly and invest the difference, but for people who struggle to save, a big refund provides a predictable windfall.', 'The answer should acknowledge the behavioral reasoning without pretending it\'s always the "right" financial choice.', 2, 10),
    ],
  },

  'buying-a-home': {
    title: 'Buying a Home Assessment',
    passingScore: 75,
    timeLimitMin: 30,
    questions: [
      mc('What is a mortgage?', ['A fee paid to a real estate agent', 'A loan used to purchase real estate, secured by the property', 'A home insurance policy', 'A government grant for first-time buyers'], 'A loan used to purchase real estate, secured by the property', 'A mortgage is a long-term loan where the home itself serves as collateral — if you stop paying, the lender can foreclose and take the property.', 1, 1),
      mc('What is a down payment?', ['Monthly mortgage payment', 'The upfront amount paid toward the home\'s purchase price', 'Closing costs and fees', 'The deposit paid to a real estate agent'], 'The upfront amount paid toward the home\'s purchase price', 'The down payment is the cash you put in at closing toward the home\'s price. The mortgage covers the rest. Larger down payments mean smaller loans and often lower interest rates.', 1, 2),
      mc('What does PMI (Private Mortgage Insurance) cover?', ['Your home against fire and theft', 'The lender if you default, required when your down payment is under 20%', 'Your mortgage payment if you lose your job', 'Closing costs at purchase'], 'The lender if you default, required when your down payment is under 20%', 'PMI protects the lender (not you) if you default. It\'s required when you put down less than 20% because the lender takes on more risk.', 1, 3),
      mc('What does "pre-approval" mean in mortgage lending?', ['The seller has accepted your offer', 'A lender has reviewed your financials and committed to a loan amount', 'You have toured the home and like it', 'The home has passed inspection'], 'A lender has reviewed your financials and committed to a loan amount', 'Pre-approval means a lender has verified your income, credit, and assets and issued a conditional commitment to lend up to a specified amount — it strengthens your offer.', 1, 4),
      mc('What are closing costs?', ['The realtor\'s commission only', 'Fees and expenses paid at the time of the home purchase transaction', 'The first month\'s mortgage payment', 'Costs of moving your belongings'], 'Fees and expenses paid at the time of the home purchase transaction', 'Closing costs include loan origination fees, title insurance, appraisal, attorney fees, and more — typically 2–5% of the loan amount, paid at closing.', 1, 5),
      mc('What is home equity?', ['The rent you\'ve paid over the years', 'The portion of your home\'s value that you own, free of the mortgage', 'Your monthly mortgage payment', 'The market value of your home'], 'The portion of your home\'s value that you own, free of the mortgage', 'Equity = Home Value − Mortgage Balance. It grows as you pay down the loan and as the home\'s value increases.', 1, 6),
      mc('What is a fixed-rate mortgage?', ['A mortgage where the interest rate changes with the market', 'A mortgage with an interest rate that stays the same for the entire loan term', 'A loan only for first-time buyers', 'A short-term bridge loan'], 'A mortgage with an interest rate that stays the same for the entire loan term', 'Fixed-rate mortgages keep the same interest rate for 15 or 30 years, giving predictable monthly payments regardless of market rate changes.', 1, 7),
      mc('What is a home inspection?', ['A government appraisal for tax purposes', 'A professional examination of a home\'s condition before purchase', 'A bank\'s review of the property value', 'A neighborhood assessment by the realtor'], 'A professional examination of a home\'s condition before purchase', 'A home inspector evaluates the structure, systems (HVAC, plumbing, electrical), and condition of a home to identify issues before you commit to buying.', 1, 8),
      oe('Why do financial advisors often say renting isn\'t "throwing money away"? When might renting be financially smarter than buying?', 'Renting isn\'t waste — you\'re paying for housing, flexibility, and avoiding maintenance costs. Buying has transaction costs (closing costs, agent fees = 8–10% of value) that take years to recoup. If you move in 2–3 years, you likely lose money buying. Renting also avoids unexpected repair bills and lets you invest the down payment elsewhere. Buying makes sense when you plan to stay long-term and the market is favorable.', 'A strong answer gives specific financial reasons renting can win — not just "sometimes renting is okay."', 2, 9),
      oe('What factors should you consider before deciding how much house you can afford?', 'Key factors: income stability, existing debt (DTI ratio), down payment size, monthly payment vs. income (keep housing under 28–30% of gross), emergency fund after closing, property taxes, insurance, HOA fees, and maintenance costs. The bank\'s max approval is not the same as what you can comfortably afford.', 'The answer should distinguish between what you\'re approved for and what you can sustainably afford, listing specific cost categories.', 2, 10),
    ],
  },

  'retirement-planning': {
    title: 'Retirement Planning Assessment',
    passingScore: 75,
    timeLimitMin: 30,
    questions: [
      mc('What is a 401(k) employer match?', ['A fee the employer charges to manage your account', 'Free money your employer adds to your 401(k) based on your contributions', 'A penalty for withdrawing early', 'Government matching of retirement funds'], 'Free money your employer adds to your 401(k) based on your contributions', 'Employer matching is essentially a 50–100% instant return on contributions — not taking the full match means leaving part of your compensation on the table.', 1, 1),
      mc('What is a traditional IRA?', ['A tax-free retirement account for high earners', 'An individual retirement account with tax-deductible contributions and taxable withdrawals', 'A government pension program', 'An employer-managed retirement fund'], 'An individual retirement account with tax-deductible contributions and taxable withdrawals', 'Traditional IRAs let you deduct contributions from current income (lowering taxes now) but you pay income tax when you withdraw in retirement.', 1, 2),
      mc('How does a Roth IRA differ from a traditional IRA?', ['Roth contributions are tax-deductible; traditional are not', 'Roth withdrawals in retirement are tax-free; traditional withdrawals are taxed', 'Roth accounts have no contribution limits', 'There is no difference'], 'Roth withdrawals in retirement are tax-free; traditional withdrawals are taxed', 'Roth IRAs are funded with after-tax money. The trade-off: no deduction now, but all growth and withdrawals in retirement are completely tax-free.', 1, 3),
      mc('What is Social Security?', ['A private retirement fund', 'A government program providing retirement, disability, and survivor benefits based on work history', 'An employer pension plan', 'A form of health insurance'], 'A government program providing retirement, disability, and survivor benefits based on work history', 'Social Security pays monthly benefits funded by payroll taxes. The amount depends on your earnings history and when you claim (62–70).', 1, 4),
      mc('What happens if you withdraw from a 401(k) before age 59½?', ['Nothing — you can withdraw anytime', 'You pay income tax plus a 10% early withdrawal penalty', 'The account is closed', 'You lose employer matching'], 'You pay income tax plus a 10% early withdrawal penalty', 'Early withdrawals from tax-advantaged retirement accounts trigger income tax on the amount plus a 10% penalty — significantly reducing what you actually receive.', 1, 5),
      mc('What is the "4% rule" in retirement planning?', ['Withdraw 4% of savings every month', 'A guideline suggesting you can withdraw 4% of your portfolio annually without running out for 30 years', 'Invest 4% of income every year', 'Keep 4 months of expenses in cash'], 'A guideline suggesting you can withdraw 4% of your portfolio annually without running out for 30 years', 'The 4% rule is a retirement planning guideline: if you withdraw 4% of your portfolio in year one and adjust for inflation, your money should last 30+ years in most market scenarios.', 1, 6),
      mc('What does "vesting" mean in a 401(k) context?', ['How much you\'ve contributed to your account', 'The schedule under which you gain full ownership of employer contributions', 'When you are eligible to start contributing', 'The process of opening a retirement account'], 'The schedule under which you gain full ownership of employer contributions', 'Vesting schedules determine when employer contributions become truly yours. If you leave before fully vested, you forfeit some or all employer contributions.', 1, 7),
      mc('Why is it important to increase retirement contributions as income grows?', ['To pay more taxes', 'Lifestyle inflation consumes raises; increasing contributions maintains savings rate', 'Employers require it', 'The IRS mandates contribution increases'], 'Lifestyle inflation consumes raises; increasing contributions maintains savings rate', 'When income rises, expenses tend to rise with it. Intentionally routing a portion of raises to retirement prevents lifestyle creep from consuming every dollar of income growth.', 1, 8),
      oe('Explain why someone might choose a Roth IRA over a traditional IRA, or vice versa.', 'Choose Roth if you expect to be in a higher tax bracket in retirement — paying taxes now (at lower rate) beats paying them later (at higher rate). Also great for young people with low current income. Choose traditional if you need the deduction now to lower current tax burden, or if you expect to be in a lower bracket in retirement. Some people use both for tax diversification.', 'A strong answer includes the tax bracket logic and doesn\'t just list features without reasoning.', 2, 9),
      oe('How much should someone save for retirement, and what factors affect that number?', 'Common guidelines: save 10–15% of income for retirement. The right amount depends on: current age (younger = more time, lower required rate), desired retirement age, expected lifestyle expenses in retirement, other income sources (Social Security, pension), and investment returns. Someone starting at 40 needs to save more aggressively than someone starting at 22.', 'A complete answer addresses multiple factors and avoids the oversimplification of one magic number.', 2, 10),
    ],
  },
}
