import type { ExerciseDef } from '../types'

function mc(
  question: string,
  options: string[],
  correctAnswer: string,
  explanation: string,
  order: number
): ExerciseDef {
  return { question, type: 'MULTIPLE_CHOICE', options, correctAnswer, explanation, order }
}

export const psychologyExercises4: Record<string, ExerciseDef[]> = {
  'cognitive-development': [
    mc('What is Piaget\'s core contribution to developmental psychology?', ['He identified four universal personality types in children', 'He showed that children\'s thinking is qualitatively different from adults — not just less knowledge, but a fundamentally different way of understanding the world', 'He proved that development is entirely determined by genetics', 'He developed the first IQ test for children'], 'He showed that children\'s thinking is qualitatively different from adults — not just less knowledge, but a fundamentally different way of understanding the world', 'Piaget proposed that children actively construct understanding through schemas, assimilation, and accommodation — moving through stages with qualitatively different cognitive structures, not just accumulating facts.', 1),
    mc('What is object permanence and when does it develop?', ['The ability to grasp and manipulate objects', 'The understanding that objects continue to exist when out of sight — typically developing around 8-12 months', 'The recognition that objects have permanent names', 'The ability to track moving objects with the eyes'], 'The understanding that objects continue to exist when out of sight — typically developing around 8-12 months', 'Piaget proposed that before 8 months, infants believe objects cease to exist when hidden ("out of sight, out of mind"). Later research suggests earlier, partial understanding — but the classic stage finding identifies when it\'s fully robust.', 2),
    mc('What is conservation in Piaget\'s theory?', ['Children\'s ability to protect valued objects', 'The understanding that quantity remains the same despite changes in appearance — typically mastered in the concrete operational stage (7-11 years)', 'Children\'s tendency to conserve energy through sleep', 'A cognitive strategy for remembering information'], 'The understanding that quantity remains the same despite changes in appearance — typically mastered in the concrete operational stage (7-11 years)', 'Classic test: pour water from a tall thin glass to a short wide one. Preoperational children (2-7) think the tall glass has more. Concrete operational children (7+) understand volume hasn\'t changed despite appearance.', 3),
    mc('What is egocentrism in cognitive development?', ['Selfishness and lack of empathy', 'The preoperational child\'s difficulty understanding that others have different perspectives, knowledge, or experiences than themselves', 'An adult personality disorder involving narcissism', 'Children\'s focus on their own needs before others\''], 'The preoperational child\'s difficulty understanding that others have different perspectives, knowledge, or experiences than themselves', 'The three mountains task: a preoperational child shown a mountain scene from one side chooses the same view for a doll on the opposite side — unable to take the other\'s perspective. This is cognitive limitation, not selfishness.', 4),
    mc('What is Vygotsky\'s Zone of Proximal Development?', ['The space in a classroom optimal for learning', 'The range of tasks a child can\'t do alone but can accomplish with guidance from a more skilled person — where learning is most effective', 'A stage of cognitive development between Piaget\'s stages', 'The optimal level of challenge for adult learners'], 'The range of tasks a child can\'t do alone but can accomplish with guidance from a more skilled person — where learning is most effective', 'Vygotsky: learning happens in the ZPD. Too easy = no growth. Too hard = failure. With scaffolding (support from a more skilled person), children accomplish things just beyond their independent capability — pushing development forward.', 5),
  ],
  'attachment': [
    mc('What is attachment theory?', ['A theory about how children form friendships', 'Bowlby\'s theory that infants are biologically prepared to form close emotional bonds with caregivers — essential for survival and forming a model for future relationships', 'A theory about how adults form romantic relationships only', 'A parenting philosophy emphasizing physical closeness'], 'Bowlby\'s theory that infants are biologically prepared to form close emotional bonds with caregivers — essential for survival and forming a model for future relationships', 'Bowlby proposed that infants come evolutionarily wired to attach — proximity to a caregiver was essential for survival. The quality of that attachment creates an internal working model that shapes future relationships.', 1),
    mc('What is the Strange Situation procedure?', ['A test of infant cognitive development', 'Mary Ainsworth\'s standardized observation measuring infant attachment by watching responses to separation and reunion with a caregiver and a stranger', 'A diagnostic test for childhood anxiety disorders', 'An observation of children in unfamiliar school environments'], 'Mary Ainsworth\'s standardized observation measuring infant attachment by watching responses to separation and reunion with a caregiver and a stranger', 'The Strange Situation revealed different attachment patterns: secure (comfortable exploring, upset at separation, easily comforted by return), anxious-ambivalent, avoidant, and later disorganized.', 2),
    mc('What characterizes a securely attached infant?', ['Never crying when separated from the caregiver', 'Using the caregiver as a secure base to explore, showing distress at separation, and being easily comforted upon the caregiver\'s return', 'Showing indifference to the caregiver\'s presence or absence', 'Being highly anxious and unable to explore when the caregiver is present'], 'Using the caregiver as a secure base to explore, showing distress at separation, and being easily comforted upon the caregiver\'s return', 'Secure attachment (~65% of infants) develops from consistent, sensitive caregiving. These infants grow up to have better social skills, emotional regulation, academic performance, and more satisfying adult relationships.', 3),
    mc('What do Harlow\'s rhesus monkey studies demonstrate?', ['That monkeys attach to whoever feeds them', 'That contact comfort (soft touch) rather than feeding is the primary basis for attachment — comfort is more important than nourishment for bonding', 'That isolation has no long-term effects if nutritional needs are met', 'That infant primates prefer unfamiliar adults to familiar ones'], 'That contact comfort (soft touch) rather than feeding is the primary basis for attachment — comfort is more important than nourishment for bonding', 'Baby monkeys chose the cloth "mother" over the wire "mother" (even though it provided milk) — spending most time with the cloth mother and running to it when frightened. This disproved the "cupboard love" theory of attachment.', 4),
    mc('How does early attachment affect adult relationships?', ['Early attachment has no lasting effect on adult romantic relationships', 'Internal working models from early attachment influence expectations and behaviors in adult relationships — securely attached infants tend to have more stable, trusting adult relationships', 'Adult relationships are entirely shaped by personality, not early attachment', 'Effects of early attachment are completely overwritten by adolescent peer relationships'], 'Internal working models from early attachment influence expectations and behaviors in adult relationships — securely attached infants tend to have more stable, trusting adult relationships', 'Adult attachment theory (Hazan and Shaver): the same secure/anxious/avoidant patterns appear in adult romantic relationships. Securely attached adults are more trusting and comfortable with intimacy; insecurely attached show predictable relationship difficulties.', 5),
  ],
  'childhood-and-adolescence': [
    mc('What is Kohlberg\'s theory of moral development?', ['A theory that morality is entirely culturally determined', 'A stage theory proposing three levels of moral reasoning: preconventional (self-interest), conventional (social rules), and postconventional (abstract principles)', 'A theory that children are naturally moral without teaching', 'A behavioral theory of how children learn right from wrong through punishment'], 'A stage theory proposing three levels of moral reasoning: preconventional (self-interest), conventional (social rules), and postconventional (abstract principles)', 'Kohlberg used moral dilemmas (Heinz dilemma) to assess reasoning. Level 1: avoid punishment/get rewards. Level 2: follow rules, maintain social order. Level 3: universal ethical principles. Most adults operate at Level 2; few reach Level 3.', 1),
    mc('What are the significant cognitive changes of adolescence?', ['Adolescent thinking is essentially the same as childhood thinking', 'Development of formal operational thinking — abstract reasoning, hypothetical thinking, and systematic problem-solving', 'Adolescents think more concretely than children', 'Only emotional, not cognitive, changes occur during adolescence'], 'Development of formal operational thinking — abstract reasoning, hypothetical thinking, and systematic problem-solving', 'Piaget\'s formal operations (12+): adolescents can think about hypotheticals ("what if"), reason about abstractions (justice, freedom), and systematically test possibilities — capabilities largely absent in concrete operational thinking.', 2),
    mc('What is adolescent egocentrism?', ['Adolescents becoming more selfish than children', 'The heightened self-consciousness of adolescence — the imaginary audience (feeling constantly observed) and the personal fable (believing one is special and invulnerable)', 'Adolescents\' cognitive inability to take others\' perspectives', 'A temporary personality disorder common in teenage years'], 'The heightened self-consciousness of adolescence — the imaginary audience (feeling constantly observed) and the personal fable (believing one is special and invulnerable)', 'Elkind\'s concept: imaginary audience = "everyone is watching and judging me" (explains embarrassment sensitivity). Personal fable = "I\'m special and won\'t suffer consequences others do" (explains risk-taking). Both are forms of cognitive distortion.', 3),
    mc('What does neuroscience tell us about the adolescent brain?', ['The adolescent brain is fully developed and adult-like', 'The prefrontal cortex (impulse control, decision-making) is still developing into the mid-20s, while the limbic system (emotion, reward) is already highly active — creating a gap between emotional reactivity and rational control', 'Adolescent risk-taking is purely social, not neurological', 'Brain development is complete by puberty'], 'The prefrontal cortex (impulse control, decision-making) is still developing into the mid-20s, while the limbic system (emotion, reward) is already highly active — creating a gap between emotional reactivity and rational control', 'The adolescent brain has a "powerful accelerator" (limbic system, reward sensitivity) but an "underdeveloped brake" (PFC). This explains risk-taking, impulsivity, emotional intensity, and susceptibility to peer influence.', 4),
    mc('What role do peers play in adolescent development?', ['Peers are less important than parents during adolescence', 'Peer relationships become increasingly central — peers influence identity, values, and behavior; peer acceptance is closely tied to self-esteem', 'Peer influence primarily affects negative behaviors only', 'Peer influence disappears once adolescents begin dating'], 'Peer relationships become increasingly central — peers influence identity, values, and behavior; peer acceptance is closely tied to self-esteem', 'Adolescence involves a shift from family to peer orientation. This is developmentally adaptive — teens are preparing to function independently. Peer influence can be positive (academic motivation, prosocial behavior) as well as negative.', 5),
  ],
  'identity-formation': [
    mc('What is Erikson\'s crisis of adolescence?', ['Industry vs. inferiority — developing competence', 'Identity vs. role confusion — developing a coherent sense of who you are, your values, and your place in the world', 'Intimacy vs. isolation — forming close relationships', 'Generativity vs. stagnation — contributing to the next generation'], 'Identity vs. role confusion — developing a coherent sense of who you are, your values, and your place in the world', 'Erikson\'s fifth stage (adolescence): teenagers must explore and commit to an identity — values, beliefs, career direction, and social roles. Failure = role confusion, an uncertain sense of who you are.', 1),
    mc('What are Marcia\'s four identity statuses?', ['Achieved, confused, diffused, and formed', 'Identity diffusion (no exploration or commitment), foreclosure (commitment without exploration), moratorium (exploring without commitment), and achievement (explored and committed)', 'Early, middle, late, and adult identity', 'Social, personal, political, and vocational identity'], 'Identity diffusion (no exploration or commitment), foreclosure (commitment without exploration), moratorium (exploring without commitment), and achievement (explored and committed)', 'Marcia expanded Erikson: Foreclosure = adopting parents\' identity without question. Moratorium = identity crisis/exploration. Achievement = resolved identity through exploration. Diffusion = no engagement with identity questions.', 2),
    mc('What is the self-concept?', ['The image others have of you', 'Your beliefs about yourself — who you are, your characteristics, abilities, and social roles', 'Your ideal version of yourself', 'Your actual personality traits as measured by tests'], 'Your beliefs about yourself — who you are, your characteristics, abilities, and social roles', 'Self-concept is descriptive (who I am). Self-esteem is evaluative (how I feel about who I am). Self-concept develops through social comparison (how I compare to others), feedback from others, and direct experience of success and failure.', 3),
    mc('What is stereotype threat?', ['The fear of encountering stereotyped people', 'The risk of confirming a negative stereotype about one\'s group — which can impair performance on tasks related to the stereotype', 'The tendency for stereotypes to become self-fulfilling', 'Anxiety about being stereotyped by strangers'], 'The risk of confirming a negative stereotype about one\'s group — which can impair performance on tasks related to the stereotype', 'Steele and Aronson (1995): Black students performed worse on a test when told it measured intelligence (activating the stereotype threat) vs. when told it was a problem-solving task. The threat consumes cognitive resources.', 4),
    mc('What is self-efficacy?', ['General self-confidence in social situations', 'Bandura\'s concept of belief in your ability to accomplish specific tasks — predicting motivation, effort, persistence, and achievement more than general self-esteem', 'The belief that you are morally good', 'Confidence in your overall intelligence and competence'], 'Bandura\'s concept of belief in your ability to accomplish specific tasks — predicting motivation, effort, persistence, and achievement more than general self-esteem', 'High self-efficacy leads to more ambitious goals, more persistence in the face of setbacks, and better performance. It\'s developed through mastery experiences, vicarious observation, social persuasion, and managing physiological states.', 5),
  ],
  'adulthood-and-aging': [
    mc('What did research on adult personality development find?', ['Personality is completely fixed by age 30', 'Most people become more conscientious, agreeable, and emotionally stable across adulthood — the "maturity principle"', 'Personality changes randomly and unpredictably in adulthood', 'Personality only changes through major life events'], 'Most people become more conscientious, agreeable, and emotionally stable across adulthood — the "maturity principle"', 'Cross-sectional and longitudinal studies converge: most adults show increases in conscientiousness, agreeableness, and emotional stability, and decreases in neuroticism and openness, across the lifespan.', 1),
    mc('What is Erikson\'s challenge of middle adulthood?', ['Integrity vs. despair — reflecting on a life well-lived', 'Generativity vs. stagnation — contributing to the next generation through parenting, mentoring, or creative work', 'Identity vs. role confusion — finding one\'s place', 'Intimacy vs. isolation — forming close relationships'], 'Generativity vs. stagnation — contributing to the next generation through parenting, mentoring, or creative work', 'Generativity = concern for establishing and guiding the next generation. Adults who fail to develop generativity experience stagnation — self-absorption and lack of meaningful contribution. Associated with life satisfaction and psychological well-being.', 2),
    mc('What does research on aging and memory show?', ['All types of memory decline equally and dramatically with age', 'Working memory and processing speed decline with age; semantic memory (knowledge) stays relatively stable; wisdom and expertise can improve', 'Memory doesn\'t decline until after 80', 'Memory decline is entirely preventable with the right lifestyle'], 'Working memory and processing speed decline with age; semantic memory (knowledge) stays relatively stable; wisdom and expertise can improve', 'Fluid intelligence (speed, novel problem-solving) declines after 30. Crystallized intelligence (accumulated knowledge, expertise, vocabulary) remains stable or improves into the 60s-70s. Older experts often outperform younger novices.', 3),
    mc('What is the positivity effect in aging?', ['Older adults are generally happier than younger adults', 'The tendency for older adults to remember positive experiences better than negative ones — a shift in emotional goals toward maximizing positive emotional experience', 'The finding that life becomes objectively better in old age', 'The tendency for older adults to have more positive personality traits'], 'The tendency for older adults to remember positive experiences better than negative ones — a shift in emotional goals toward maximizing positive emotional experience', 'Carstensen\'s Socioemotional Selectivity Theory: as perceived time horizon shrinks, people prioritize meaningful, positive emotional experience. Older adults focus on present relationships, attend to positive information, and show better emotional regulation.', 4),
    mc('What does research say about life satisfaction across the lifespan?', ['Life satisfaction steadily decreases with age', 'Life satisfaction follows a U-curve — high in youth, dipping in middle age, and rising again in later life — with many older adults reporting high well-being', 'Life satisfaction is relatively stable across all of adulthood', 'Life satisfaction depends entirely on health status'], 'Life satisfaction follows a U-curve — high in youth, dipping in middle age, and rising again in later life — with many older adults reporting high well-being', 'The "U-curve of happiness": life satisfaction tends to be lower in the 40s-50s (midlife stress, unmet expectations) and rises again after 50. Many people in their 70s-80s report higher well-being than their 30-year-old selves.', 5),
  ],
  'conformity': [
    mc('What did Solomon Asch\'s conformity experiments demonstrate?', ['People rarely conform to group pressure when they know the group is wrong', 'People often conform to obviously wrong group judgments, even when they can clearly see the correct answer themselves', 'Conformity only occurs when people are uncertain about the correct answer', 'People conform only to expert opinion, not peer pressure'], 'People often conform to obviously wrong group judgments, even when they can clearly see the correct answer themselves', 'Asch (1951): participants matched line lengths. With confederates unanimously giving wrong answers, 75% of participants conformed at least once. ~32% of responses were conforming. Even clear perceptual tasks yielded to group pressure.', 1),
    mc('What is normative social influence?', ['Conforming because others know more than you', 'Conforming to be liked and accepted — adjusting behavior to match group norms even when you know the group is wrong', 'Following laws and social rules because they make sense', 'Conforming to expert authority in professional contexts'], 'Conforming to be liked and accepted — adjusting behavior to match group norms even when you know the group is wrong', 'Normative influence = conforming to fit in. Informational influence = conforming because others seem to know more. Asch\'s participants often knew the group was wrong but conformed anyway — normative influence. More powerful when group unanimity is unbroken.', 2),
    mc('What conditions increase conformity rates in Asch\'s experiments?', ['When participants had more expertise than the group', 'Larger groups (up to 3-5 people), group unanimity, and when the participant is insecure or in an unfamiliar situation', 'When the task is more difficult and subjective', 'When the participant is observed by more people outside the group'], 'Larger groups (up to 3-5 people), group unanimity, and when the participant is insecure or in an unfamiliar situation', 'Asch found: conformity increases up to about 3-5 confederates then levels off; a single ally dramatically reduces conformity; public responses show more conformity than private ones. Unanimity is crucial — one dissenter liberates others.', 3),
    mc('What distinguishes compliance from internalization in social influence?', ['They produce the same behavioral outcomes', 'Compliance = changing behavior publicly without changing private beliefs; internalization = genuinely accepting the group\'s view as your own', 'Internalization is less stable than compliance', 'They are the same psychological process with different names'], 'Compliance = changing behavior publicly without changing private beliefs; internalization = genuinely accepting the group\'s view as your own', 'Asch participants often complied (changed their public answer) without internalizing (actually believing the wrong answer). Internalization occurs when influence is informational — you genuinely come to believe the group is right.', 4),
    mc('What real-world behavior does Asch\'s research help explain?', ['Why people buy popular products', 'How ordinary people can commit atrocities, stay silent about wrongdoing, and adopt fashions, beliefs, and behaviors simply because others do', 'Why some people are natural leaders', 'How conformity prevents social conflict'], 'How ordinary people can commit atrocities, stay silent about wrongdoing, and adopt fashions, beliefs, and behaviors simply because others do', 'Asch\'s work illuminates the psychological mechanisms behind mob behavior, peer pressure, fashion, groupthink, and the silence of bystanders. Understanding normative conformity is essential for resisting unjust social pressures.', 5),
  ],
  'obedience': [
    mc('What did Milgram\'s obedience experiments find?', ['Only sadistic people obey authority to harm others', 'Ordinary people delivered what they believed were dangerous electric shocks to others simply because an authority figure told them to', 'Most people refuse to obey unethical authority commands', 'Authority only produces obedience when backed by physical force'], 'Ordinary people delivered what they believed were dangerous electric shocks to others simply because an authority figure told them to', 'Milgram (1963): ~65% of participants delivered all 30 shocks to the maximum 450V level, despite the "learner\'s" screams, despite personal distress — because the experimenter said "please continue."', 1),
    mc('What factors in Milgram\'s research increased obedience?', ['When participants were more aggressive by nature', 'Authority figure\'s presence (vs. phone), victim\'s remoteness (vs. in same room), institutional prestige (Yale), and absence of peer support for defiance', 'When participants were paid more', 'When participants didn\'t know what the experiment was about'], 'Authority figure\'s presence (vs. phone), victim\'s remoteness (vs. in same room), institutional prestige (Yale), and absence of peer support for defiance', 'Proximity matters both ways: obedience dropped when the experimenter gave orders by phone, and when the victim was in the same room (40% vs. 65%). Two rebellious peers dramatically reduced obedience to ~10%.', 2),
    mc('What does Milgram\'s research suggest about human nature?', ['Most people are secretly sadistic and enjoy causing harm', 'The capacity for obedience to authority is a fundamental human characteristic that can lead ordinary people to commit extraordinary harm under institutional pressure', 'People only obey when they personally agree with the authority\'s commands', 'Obedience to authority is culturally specific — not a universal human tendency'], 'The capacity for obedience to authority is a fundamental human characteristic that can lead ordinary people to commit extraordinary harm under institutional pressure', 'Milgram: situational forces are far more powerful than we believe. Participants weren\'t monsters — they were ordinary people responding to situational pressures. This has profound implications for understanding genocide, abuse, and institutional wrongdoing.', 3),
    mc('What is the agentic state?', ['A state of high moral awareness and personal responsibility', 'Milgram\'s concept of shifting from autonomous mode (self-directed) to agentic mode (acting as instrument of authority) — reducing personal responsibility', 'A state of low empathy toward victims', 'The psychological state of someone who enjoys harming others'], 'Milgram\'s concept of shifting from autonomous mode (self-directed) to agentic mode (acting as instrument of authority) — reducing personal responsibility', 'Milgram theorized that participants entered an agentic state — seeing themselves as instruments of legitimate authority rather than autonomous moral agents. This diffusion of responsibility reduced the psychological cost of harming others.', 4),
    mc('What is the ethical legacy of Milgram\'s experiments?', ['They showed ethics in psychological research don\'t matter if the findings are important', 'They directly contributed to the development of ethical guidelines for research involving human subjects, including informed consent and debriefing requirements', 'They had no impact on research ethics', 'They showed that deception in research is always acceptable if the findings are significant'], 'They directly contributed to the development of ethical guidelines for research involving human subjects, including informed consent and debriefing requirements', 'Milgram\'s experiments caused significant participant distress. The controversy led to the Belmont Report (1979) and institutionalization of Institutional Review Boards (IRBs) requiring informed consent, risk minimization, and debriefing.', 5),
  ],
}
