import type { ExerciseDef } from '../types';

const mc = (
  question: string,
  options: string[],
  correctAnswer: string,
  explanation: string,
  order: number
): ExerciseDef => ({ question, type: 'MULTIPLE_CHOICE', options, correctAnswer, explanation, order });

export const psychologyExercises5: Record<string, ExerciseDef[]> = {
  'persuasion': [
    mc('What is the central route to persuasion?', ['Emotional appeals that bypass logic', 'Careful evaluation of the argument\'s logic and evidence', 'Using attractive spokespeople', 'Repeating a message until it feels true'], 'Careful evaluation of the argument\'s logic and evidence', 'The Elaboration Likelihood Model describes two routes: the central route involves careful thinking about message content; the peripheral route uses shortcuts like source attractiveness.', 1),
    mc('Which technique gets a small commitment first, then escalates?', ['Door-in-the-face', 'Foot-in-the-door', 'Scarcity appeal', 'Fear appeal'], 'Foot-in-the-door', 'Foot-in-the-door starts with a small request to create a sense of commitment; the person then feels pressure to stay consistent by agreeing to a larger follow-up request.', 2),
    mc('The mere exposure effect means we like things more when we:', ['Are told they are popular', 'Have seen them repeatedly', 'Associate them with authority figures', 'Are offered them for free'], 'Have seen them repeatedly', 'Repeated exposure increases familiarity, which the brain tends to equate with safety and liking — even without conscious awareness of prior exposure.', 3),
    mc('Which persuasion factor relates to how much the audience believes the speaker?', ['Message length', 'Source credibility', 'Audience size', 'Channel richness'], 'Source credibility', 'Source credibility — encompassing expertise and trustworthiness — strongly determines whether audiences accept the message, independent of its actual logic.', 4),
    mc('Cognitive dissonance can make persuasion work by:', ['Making people forget prior beliefs', 'Creating discomfort that motivates attitude change', 'Distracting attention from weak arguments', 'Triggering the foot-in-the-door reflex'], 'Creating discomfort that motivates attitude change', 'When behavior conflicts with a belief, the resulting discomfort (dissonance) often pushes people to change the belief rather than the behavior, making them receptive to attitude-consistent messages.', 5),
  ],
  'group-dynamics': [
    mc('Social facilitation means people perform better on tasks they know well when:', ['Working alone without distractions', 'In the presence of others', 'Given clear instructions', 'Rewarded financially'], 'In the presence of others', 'Arousal from being observed enhances performance on well-practiced tasks but impairs performance on novel or complex ones — a pattern called social facilitation and inhibition.', 1),
    mc('Social loafing occurs when individuals in a group:', ['Exert more effort than when working alone', 'Compete aggressively with each other', 'Reduce personal effort, assuming others will carry the load', 'Conform to a leader\'s poor decisions'], 'Reduce personal effort, assuming others will carry the load', 'Social loafing is reduced personal accountability in groups; it decreases when individual contributions are identifiable or when people feel personally responsible for the outcome.', 2),
    mc('Groupthink is most likely when a group:', ['Has diverse members with strong dissenting norms', 'Is cohesive and insulated, with a directive leader', 'Uses structured devil\'s advocate roles', 'Votes anonymously on decisions'], 'Is cohesive and insulated, with a directive leader', 'Groupthink emerges from pressure for unanimity in tight, insulated groups, leading to poor decisions because critical evaluation is suppressed.', 3),
    mc('Group polarization means that group discussion tends to:', ['Bring members to moderate, compromise positions', 'Push initial attitudes in a more extreme direction', 'Eliminate individual differences', 'Produce random outcomes'], 'Push initial attitudes in a more extreme direction', 'Discussions expose members to more arguments favoring the dominant view, and social comparison motivates people to adopt even stronger versions of the prevailing position.', 4),
    mc('A person who expresses a minority view consistently over time can:', ['Always be ignored because they lack majority support', 'Influence the majority through informational impact', 'Immediately change the group\'s decision', 'Trigger groupthink'], 'Influence the majority through informational impact', 'Research by Moscovici showed that a consistent, confident minority can plant seeds of doubt and gradually shift majority opinion, though the effect is usually slower and more indirect.', 5),
  ],
  'prejudice-and-discrimination': [
    mc('What is the difference between prejudice and discrimination?', ['They are identical in meaning', 'Prejudice is a behavior; discrimination is an attitude', 'Prejudice is an attitude; discrimination is a behavior', 'Prejudice is conscious; discrimination is unconscious'], 'Prejudice is an attitude; discrimination is a behavior', 'Prejudice refers to the negative attitude (affect + belief) toward a group; discrimination refers to the actual differential treatment of group members.', 1),
    mc('Stereotypes are problematic primarily because they:', ['Are always negative in content', 'Overgeneralize to every individual in the group', 'Come from personal experience only', 'Are biologically programmed'], 'Overgeneralize to every individual in the group', 'Stereotypes may have a statistical grain of truth at the group level but cannot reliably describe any individual, leading to unfair judgments and missed person-level information.', 2),
    mc('In-group favoritism describes the tendency to:', ['Prefer strangers over familiar people', 'Favor members of one\'s own social group', 'Dislike people who are different', 'Compete with other groups for resources'], 'Favor members of one\'s own social group', 'Merely categorizing people into in-group and out-group is enough to trigger preferential treatment for in-group members, even in minimal group experiments with trivial categories.', 3),
    mc('Implicit bias is characterized by:', ['Operating outside conscious awareness and control', 'Being easy to detect via self-report', 'Applying only to racial categories', 'Having no effect on real-world behavior'], 'Operating outside conscious awareness and control', 'Implicit biases are automatically activated associations stored in memory; people often deny holding them while showing measurable effects in reaction-time tasks like the IAT.', 4),
    mc('Which theory explains prejudice as stemming from competition over scarce resources?', ['Social learning theory', 'Realistic conflict theory', 'Social identity theory', 'Cognitive dissonance theory'], 'Realistic conflict theory', 'Realistic conflict theory (Sherif) argues that prejudice and hostility increase when groups compete for the same limited goals — as illustrated in the Robbers Cave experiment.', 5),
  ],
  'reducing-prejudice': [
    mc('The contact hypothesis states that prejudice is reduced when contact between groups is:', ['Superficial and brief', 'Competitive and high-stakes', 'Equal-status and cooperative', 'Led by authority without structure'], 'Equal-status and cooperative', 'Allport\'s conditions for effective contact include equal status, cooperative goals, institutional support, and opportunity to get to know individuals — mere exposure is not enough.', 1),
    mc('Jigsaw classroom technique reduces prejudice mainly by:', ['Separating groups so conflict is impossible', 'Making each student an expert others depend on', 'Assigning grades on a strict curve', 'Removing all group labels'], 'Making each student an expert others depend on', 'In the jigsaw classroom, students from different backgrounds must cooperate because each holds unique information needed to complete the group task, creating positive interdependence.', 2),
    mc('Which approach targets implicit bias most directly?', ['Punishing biased behavior', 'Deliberate counter-stereotypic training', 'Reducing all intergroup contact', 'Increasing in-group size'], 'Deliberate counter-stereotypic training', 'Exposure to vivid counter-stereotypic exemplars and implementation intentions (if-then plans) can weaken automatic associations over time.', 3),
    mc('Superordinate goals help reduce intergroup conflict by:', ['Giving one group clear dominance', 'Requiring both groups to work together toward a shared objective', 'Eliminating the need for cooperation', 'Assigning separate tasks to each group'], 'Requiring both groups to work together toward a shared objective', 'When groups share a goal that neither can achieve alone, competition gives way to cooperation, reshaping how members perceive each other.', 4),
    mc('Perspective-taking interventions reduce prejudice primarily by:', ['Suppressing negative thoughts', 'Increasing empathy and perceived similarity', 'Rewarding tolerance financially', 'Distracting people from their biases'], 'Increasing empathy and perceived similarity', 'Imagining life from an out-group member\'s perspective reduces automatic negative reactions and increases the sense of shared humanity, which softens stereotyped thinking.', 5),
  ],
  'prosocial-behavior': [
    mc('The bystander effect predicts that help is LESS likely when:', ['Only one person witnesses the emergency', 'Many bystanders are present', 'The victim is clearly in danger', 'The helper has first-aid training'], 'Many bystanders are present', 'A larger audience diffuses responsibility — each person assumes someone else will help — and creates pluralistic ignorance where everyone looks calm and concludes there is no emergency.', 1),
    mc('Altruism refers to helping behavior that:', ['Is motivated by personal gain', 'Benefits the helper at the expense of the helped', 'Is motivated by genuine concern for others\' welfare', 'Occurs only under social pressure'], 'Is motivated by genuine concern for others\' welfare', 'True altruism is helping with no expectation of personal benefit; whether pure altruism exists or whether empathy always carries some self-reward is a debated question in psychology.', 2),
    mc('According to the empathy-altruism hypothesis, empathy motivates helping because it:', ['Creates guilt that must be relieved', 'Directly produces other-focused concern', 'Increases fear of social punishment', 'Reduces cognitive load'], 'Directly produces other-focused concern', 'Batson\'s hypothesis argues that feeling genuine empathy for another person motivates truly other-focused helping, not merely personal-distress reduction or social reward.', 3),
    mc('Social exchange theory explains helping as:', ['An automatic, emotion-driven reflex', 'A cost-benefit calculation maximizing net reward', 'A purely genetic survival strategy', 'An outcome of unconscious conditioning'], 'A cost-benefit calculation maximizing net reward', 'Social exchange theory views prosocial behavior as rational: people help when expected benefits (social approval, reduced guilt, reciprocity) outweigh costs (time, risk, money).', 4),
    mc('Reciprocal altruism in evolutionary psychology means:', ['Animals only help close genetic relatives', 'Organisms help others expecting future help in return', 'Helping is always altruistic with no cost', 'Cooperation requires identical genes'], 'Organisms help others expecting future help in return', 'Reciprocal altruism explains cooperation between non-relatives: if the helped individual is likely to return the favor later, the net fitness cost to the helper can be positive over time.', 5),
  ],
  'what-is-abnormal': [
    mc('Which criterion defines behavior as abnormal based on how rarely it occurs?', ['Dysfunction', 'Distress', 'Statistical infrequency', 'Violation of norms'], 'Statistical infrequency', 'Statistical infrequency flags behavior that deviates significantly from the average, though this criterion alone is flawed — extreme intelligence is also statistically rare but not disordered.', 1),
    mc('The "4 Ds" framework for abnormality includes dysfunction, distress, deviance, and:', ['Diagnosis', 'Dangerousness', 'Duration', 'Defense'], 'Dangerousness', 'The four Ds — deviance, distress, dysfunction, and dangerousness — provide a multi-criteria framework; most definitions require several criteria to be met, not just one.', 2),
    mc('A major limitation of cultural context in defining abnormality is that:', ['All cultures define abnormality identically', 'What is abnormal in one culture may be normal in another', 'Culture only affects somatic symptoms', 'DSM criteria are culture-free'], 'What is abnormal in one culture may be normal in another', 'Hearing ancestral voices may be a spiritual gift in one culture and a symptom of psychosis in another, illustrating why cultural context must inform any definition of mental disorder.', 3),
    mc('The medical model of abnormality treats psychological disorders as:', ['Moral failures requiring punishment', 'Illnesses with biological causes that require treatment', 'Social constructs with no objective reality', 'Learned habits that simply need extinction'], 'Illnesses with biological causes that require treatment', 'The medical model imports the disease framework into psychology: disorders have symptoms, etiology, prognosis, and respond to treatments — an approach that shapes the DSM system.', 4),
    mc('Ego-dystonic symptoms are those the person:', ['Accepts as normal parts of their personality', 'Finds consistent with their desired self-image', 'Experiences as unwanted and inconsistent with their self-concept', 'Causes deliberately for attention'], 'Experiences as unwanted and inconsistent with their self-concept', 'Ego-dystonic symptoms (e.g., obsessions, compulsions) feel alien and distressing to the individual, distinguishing them from ego-syntonic traits that feel natural to the self.', 5),
  ],
  'diagnosing-disorders': [
    mc('The DSM-5 is primarily a:', ['Treatment guideline manual', 'Diagnostic classification system describing criteria for mental disorders', 'Biological test battery', 'Psychotherapy protocol handbook'], 'Diagnostic classification system describing criteria for mental disorders', 'The Diagnostic and Statistical Manual of Mental Disorders (DSM-5) provides standardized criteria for diagnosing mental disorders, facilitating consistent communication among clinicians and researchers.', 1),
    mc('Reliability in diagnosis means that:', ['The diagnosis predicts treatment outcome', 'Different clinicians using the same criteria reach the same diagnosis', 'The diagnosis captures all important symptoms', 'Symptoms can be measured biologically'], 'Different clinicians using the same criteria reach the same diagnosis', 'Reliability (inter-rater agreement) ensures that the diagnostic system produces consistent results regardless of who is doing the evaluation — a prerequisite for scientific validity.', 2),
    mc('A major criticism of psychiatric diagnosis is the risk of:', ['Over-identifying truly rare disorders', 'Pathologizing normal variation and labeling effects', 'Missing all serious disorders', 'Ignoring cultural factors in favor of biology'], 'Pathologizing normal variation and labeling effects', 'Critics argue that diagnostic categories can medicalize ordinary human experiences, and that labels carry stigma that can shape how patients see themselves and how others treat them.', 3),
    mc('Comorbidity in mental health means:', ['A disorder caused by medical illness', 'Two or more disorders occurring in the same person simultaneously', 'A disorder with no known treatment', 'Symptoms shared across all disorders'], 'Two or more disorders occurring in the same person simultaneously', 'Comorbidity is the rule rather than the exception in mental health — anxiety and depression, for instance, co-occur at high rates, complicating diagnosis and treatment planning.', 4),
    mc('The biopsychosocial model of mental disorders emphasizes that:', ['Biology alone determines mental illness', 'Only social factors cause psychological problems', 'Biological, psychological, and social factors interact to produce disorders', 'Disorders are entirely learned behaviors'], 'Biological, psychological, and social factors interact to produce disorders', 'The biopsychosocial model replaced single-cause explanations, recognizing that genetic predispositions, cognitive patterns, and social stressors all contribute to the development and course of mental disorders.', 5),
  ],
};
