import type { AssessmentDef, AssessmentQuestionDef } from '../types'

const mc = (q: string, opts: string[], ans: string, exp: string, pts: number, ord: number): AssessmentQuestionDef =>
  ({ question: q, type: 'MULTIPLE_CHOICE', options: opts, correctAnswer: ans, explanation: exp, points: pts, order: ord })
const oe = (q: string, ans: string, exp: string, pts: number, ord: number): AssessmentQuestionDef =>
  ({ question: q, type: 'OPEN_ENDED', correctAnswer: ans, explanation: exp, points: pts, order: ord })

export const psychologyAssessments: Record<string, AssessmentDef> = {
  'intro-to-psychology': {
    title: 'Introduction to Psychology Assessment', passingScore: 75, timeLimitMin: 25,
    questions: [
      mc('Psychology is best defined as:', ['The study of the human brain only', 'The scientific study of behavior and mental processes', 'The practice of treating mental illness', 'The philosophical study of the human soul'], 'The scientific study of behavior and mental processes', 'Psychology uses scientific methods to understand how people think, feel, and behave. It includes both the study of normal functioning and psychological disorders, applying rigorous empirical methods to questions about the mind.', 1, 1),
      mc('Which perspective explains behavior primarily in terms of unconscious conflicts and early childhood experiences?', ['Behavioral', 'Cognitive', 'Psychodynamic', 'Humanistic'], 'Psychodynamic', 'Rooted in Freud\'s work, the psychodynamic perspective holds that behavior is shaped by unconscious drives, unresolved conflicts from childhood, and defense mechanisms. Modern psychodynamic approaches are more flexible than classical Freudian theory.', 1, 2),
      mc('A double-blind experiment controls for:', ['The placebo effect and researcher bias simultaneously', 'Random assignment of participants', 'Sample size requirements', 'Ethical violations in research'], 'The placebo effect and researcher bias simultaneously', 'In a double-blind study, neither participants nor the researchers who interact with them know who is in the treatment vs. control group. This prevents both participant expectation effects (placebo) and researcher confirmation bias.', 1, 3),
      mc('Neurons communicate at synapses using:', ['Electrical sparks across the gap', 'Neurotransmitters released into the synaptic cleft', 'Direct physical contact', 'Blood flow between neurons'], 'Neurotransmitters released into the synaptic cleft', 'When an action potential reaches an axon terminal, vesicles release neurotransmitters into the synapse. These bind to receptors on the receiving neuron, either exciting or inhibiting it. This chemical signaling underlies all thought, emotion, and behavior.', 1, 4),
      mc('The amygdala is most associated with:', ['Language production and comprehension', 'Procedural memory and motor learning', 'Emotion processing, especially fear and threat detection', 'Executive function and planning'], 'Emotion processing, especially fear and threat detection', 'The amygdala is the brain\'s threat-detection center. It processes emotional significance of stimuli and can trigger fear responses before the cortex has consciously processed the situation — the basis of phobias and PTSD.', 1, 5),
      mc('Nature vs. nurture in psychology refers to:', ['The debate between evolutionary and cultural psychology', 'The question of how genetic inheritance and environmental experience interact to shape behavior', 'Whether animals or humans are more appropriate research subjects', 'The choice between laboratory and field research'], 'The question of how genetic inheritance and environmental experience interact to shape behavior', 'Modern psychology recognizes that behavior results from gene-environment interaction, not either factor alone. Genes set ranges of possibilities; environment determines where within that range a trait develops.', 1, 6),
      mc('The behaviorist perspective (Watson, Skinner) focused exclusively on:', ['Observable behavior, rejecting mental states as unscientific', 'Brain chemistry and genetics', 'Unconscious processes and dreams', 'Self-actualization and personal growth'], 'Observable behavior, rejecting mental states as unscientific', 'Behaviorism dominated psychology from the 1920s-1960s, arguing that only observable, measurable behavior was a valid subject for science. It produced powerful insights about learning and conditioning but was eventually displaced by cognitive psychology.', 1, 7),
      mc('A correlation coefficient of -0.85 indicates:', ['A weak positive relationship', 'A strong negative relationship — as one variable increases, the other strongly decreases', 'No meaningful relationship between variables', 'A moderate positive relationship'], 'A strong negative relationship — as one variable increases, the other strongly decreases', 'Correlation ranges from -1.0 to +1.0. The sign indicates direction (positive = both go up/down together; negative = one up, other down). The magnitude indicates strength (0.85 is strong). Neither direction tells us about causation.', 1, 8),
      oe('Explain why psychology uses the scientific method rather than relying on intuition, common sense, or personal experience to understand behavior.', 'Intuition and common sense are often wrong and contain systematic biases — we see patterns that aren\'t there, remember confirming evidence better than disconfirming evidence, and are influenced by cultural assumptions we\'re unaware of. The scientific method — hypothesis, controlled testing, replication, peer review — provides a systematic process for correcting these errors. Personal experience is limited, not representative, and subject to memory distortions. Science\'s self-correcting nature means errors are eventually identified and corrected, unlike intuition which can persist indefinitely.', 'This is why psychology as a science often produces counterintuitive findings. Many things "everyone knows" about human behavior turn out to be wrong or incomplete when tested systematically. The history of psychology is partly a history of debunking folk wisdom.', 2, 9),
      oe('Describe how the biological and cognitive perspectives in psychology complement each other in understanding depression.', 'The biological perspective examines neurochemical factors (serotonin, norepinephrine, dopamine systems), genetic predisposition, brain structure differences (smaller hippocampus, hyperactive amygdala), and hormonal factors (cortisol in stress responses). The cognitive perspective examines how negative automatic thoughts, cognitive distortions (catastrophizing, all-or-nothing thinking), and dysfunctional beliefs maintain depressed mood. The two perspectives complement each other: biological vulnerabilities may make someone prone to developing cognitive patterns that maintain depression; cognitive therapy changes thought patterns that also change brain activity. Effective treatment often combines medication (biological) with psychotherapy (cognitive).', 'Modern psychology understands most complex behaviors and disorders through multiple levels of analysis simultaneously. Neither biological nor cognitive explanations alone are complete — the most powerful understanding combines them with social and developmental factors. This is why the biopsychosocial model has become the standard framework.', 2, 10),
    ],
  },
  'perception-and-cognition': {
    title: 'Perception, Memory & Cognition Assessment', passingScore: 75, timeLimitMin: 25,
    questions: [
      mc('The difference between sensation and perception is:', ['They are the same process described differently', 'Sensation is the detection of stimuli; perception is the brain\'s interpretation of those signals', 'Sensation involves higher brain areas; perception is purely sensory', 'Perception is more accurate than sensation'], 'Sensation is the detection of stimuli; perception is the brain\'s interpretation of those signals', 'Your eyes detect light waves (sensation); your brain constructs a meaningful visual scene from those signals (perception). Perception is active, top-down, and influenced by expectation, context, and prior experience.', 1, 1),
      mc('Working memory is best described as:', ['Long-term storage of factual knowledge', 'A temporary workspace for holding and manipulating information currently in use', 'The process of converting short-term to long-term memory', 'Memory for skills and procedures'], 'A temporary workspace for holding and manipulating information currently in use', 'Working memory holds the information you\'re actively thinking about — Baddeley\'s model includes a central executive, phonological loop, and visuospatial sketchpad. It has limited capacity (~4 chunks) and duration without rehearsal.', 1, 2),
      mc('The serial position effect predicts that in a list of items, you\'ll remember best:', ['Items in the middle of the list', 'Items at the beginning and end of the list', 'Items that are emotionally significant regardless of position', 'Items repeated most frequently'], 'Items at the beginning and end of the list', 'The primacy effect (beginning items enter long-term memory through rehearsal) and recency effect (end items are still in working memory) together create the serial position curve. Middle items suffer from interference.', 1, 3),
      mc('Selective attention explains why:', ['We perceive everything in our environment equally', 'We can focus on some stimuli while filtering out others, like hearing your name in a noisy room', 'Attention is distributed evenly across all sensory modalities', 'Distraction always impairs performance equally'], 'We can focus on some stimuli while filtering out others, like hearing your name in a noisy room', 'The "cocktail party effect" demonstrates selective attention — we can follow one conversation while filtering noise, yet a salient stimulus (our name) breaks through. Attention is a limited resource that the brain must allocate selectively.', 1, 4),
      mc('The misinformation effect (Loftus) shows that memory:', ['Is a perfect recording of events', 'Can be altered by post-event information introduced through leading questions or suggestions', 'Becomes more accurate over time through consolidation', 'Is only distorted in people with memory disorders'], 'Can be altered by post-event information introduced through leading questions or suggestions', 'Loftus\'s research demonstrated that memory is reconstructive — asking "How fast were the cars going when they smashed?" produced higher speed estimates than "when they hit?" Eyewitness memory is malleable, with significant implications for the justice system.', 1, 5),
      mc('Cognitive schemas help us process information by:', ['Ensuring we perceive each situation as entirely new', 'Providing mental frameworks based on prior knowledge that organize and interpret new information', 'Slowing down perception to improve accuracy', 'Storing all information in long-term memory automatically'], 'Providing mental frameworks based on prior knowledge that organize and interpret new information', 'Schemas are mental shortcuts that speed processing — when you see a "restaurant" you immediately know what to expect without relearning each time. The downside is that schemas can distort perception, filling gaps with expectations rather than actual information.', 1, 6),
      mc('The availability heuristic leads to errors in judgment because:', ['We always underestimate risks', 'We judge the likelihood of events by how easily examples come to mind, not by actual frequency', 'We rely too heavily on statistical base rates', 'Emotional events are stored in different memory systems'], 'We judge the likelihood of events by how easily examples come to mind, not by actual frequency', 'After extensive media coverage of plane crashes, people overestimate the danger of flying vs. driving — plane crashes are memorable and vivid; car accident deaths are routine. Availability = mental accessibility, not statistical frequency.', 1, 7),
      mc('Language influences thought according to the Sapir-Whorf hypothesis by suggesting:', ['Language and thought are entirely separate systems', 'The language we speak shapes how we perceive and think about reality', 'All languages produce identical thought patterns', 'Only written language influences cognition'], 'The language we speak shapes how we perceive and think about reality', 'The strong version (linguistic determinism) — language determines thought — is mostly rejected. The weak version (linguistic relativity) has empirical support: languages with more color terms produce finer color discrimination; languages with absolute directions (north/south) rather than relative (left/right) affect spatial cognition.', 1, 8),
      oe('Explain how retrieval cues work and why "tip of the tongue" states occur.', 'Memory retrieval is a reconstructive process triggered by cues — context, related information, sensory details, or emotional state at encoding. The more cues match encoding conditions, the more easily memory is retrieved (encoding specificity principle). "Tip of the tongue" (TOT) states occur when we have a memory stored but can\'t fully retrieve it — we know we know it, can recall partial information (first letter, number of syllables), but the full memory remains inaccessible. TOT states reveal that retrieval is separate from storage and can fail even when information exists in memory.', 'The distinction between storage failure (information is lost) and retrieval failure (information exists but is inaccessible) has practical implications: studying in contexts similar to the test, using retrieval practice (testing yourself), and creating multiple memory cues all improve recall by enhancing retrieval, not just storage.', 2, 9),
      oe('Describe the difference between top-down and bottom-up processing in perception, using a real-world example.', 'Bottom-up processing is data-driven: sensory information from the environment is detected and built up into a perception. Top-down processing is knowledge-driven: prior experience, expectations, and context shape what we perceive. Example: Reading a handwritten note with messy handwriting. Bottom-up processing detects the actual ink marks. Top-down processing uses knowledge of language, context, and the writer\'s typical style to interpret ambiguous shapes as specific letters and words. This is why we read "the cat sat on the mat" even if the "h" and "a" are identically scrawled — context fills in the ambiguity. Both processes operate simultaneously in most real perception.', 'The interaction of top-down and bottom-up processing explains why perception is so efficient (we don\'t have to fully analyze every pixel of a scene) but also why it makes errors (we see what we expect rather than what\'s there). Optical illusions often exploit the conflict between the two processing modes.', 2, 10),
    ],
  },
  'emotion-and-motivation': {
    title: 'Emotion, Motivation & Personality Assessment', passingScore: 75, timeLimitMin: 25,
    questions: [
      mc('Maslow\'s hierarchy of needs proposes that:', ['All needs are equally important and should be addressed simultaneously', 'Lower-level needs (physiological, safety) must generally be satisfied before higher-level needs motivate behavior', 'Self-actualization is the only true human motivation', 'Social needs develop before physiological needs in children'], 'Lower-level needs (physiological, safety) must generally be satisfied before higher-level needs motivate behavior', 'Maslow\'s pyramid places physiological survival at the base (food, water, sleep), then safety, then belonging, then esteem, with self-actualization at the apex. Critics note the hierarchy is not universal and cultures differ in the ordering of social vs. individual needs.', 1, 1),
      mc('The James-Lange theory of emotion proposes that:', ['Emotions cause physiological changes', 'Physiological changes are perceived and interpreted as emotions — we feel afraid because we run, not vice versa', 'Emotion and physiology occur simultaneously and independently', 'Emotions are purely cognitive appraisals with no physiological component'], 'Physiological changes are perceived and interpreted as emotions — we feel afraid because we run, not vice versa', 'James and Lange independently proposed that we experience emotion by perceiving our body\'s response to stimuli. The Cannon-Bard theory challenged this (physiology and emotion occur simultaneously). Schachter-Singer proposed a two-factor model: physiological arousal + cognitive label = emotion.', 1, 2),
      mc('The Big Five personality traits include:', ['Introversion, Sensing, Thinking, Judging, and Perceiving', 'Openness, Conscientiousness, Extraversion, Agreeableness, and Neuroticism (OCEAN)', 'Id, Ego, Superego, Shadow, and Persona', 'Dominance, Influence, Steadiness, Conscientiousness, and Security'], 'Openness, Conscientiousness, Extraversion, Agreeableness, and Neuroticism (OCEAN)', 'The Big Five (OCEAN) emerged from factor analysis of personality descriptors and is the most empirically supported personality model. Unlike Myers-Briggs (MBTI), the Big Five treats traits as continuous dimensions rather than categories, and has strong predictive validity for life outcomes.', 1, 3),
      mc('Intrinsic motivation refers to:', ['Behavior driven by external rewards like money or grades', 'Behavior motivated by internal factors — inherent interest, enjoyment, or personal meaning', 'The motivation to meet basic survival needs', 'Motivation that requires social approval to sustain'], 'Behavior motivated by internal factors — inherent interest, enjoyment, or personal meaning', 'Deci and Ryan\'s Self-Determination Theory shows intrinsic motivation is more durable and produces better performance than extrinsic motivation for complex tasks. Offering external rewards for already intrinsically motivated activities can undermine intrinsic motivation (overjustification effect).', 1, 4),
      mc('The physiological stress response (fight-or-flight) is primarily mediated by:', ['The parasympathetic nervous system and insulin', 'The sympathetic nervous system and stress hormones (cortisol, adrenaline)', 'The prefrontal cortex and dopamine', 'The amygdala and serotonin'], 'The sympathetic nervous system and stress hormones (cortisol, adrenaline)', 'Perceived threat activates the HPA axis (hypothalamus-pituitary-adrenal), releasing cortisol, and the sympathetic nervous system, releasing adrenaline. Heart rate increases, digestion slows, and energy is mobilized — adaptive for acute threats, damaging when chronic.', 1, 5),
      mc('Psychoanalytic theory attributes personality to:', ['Learned patterns of behavior shaped by reinforcement history', 'Conscious rational decisions about how to act', 'The interaction of id (drives), ego (reality), and superego (morality), mostly unconscious', 'Biological temperament and genetic inheritance alone'], 'The interaction of id (drives), ego (reality), and superego (morality), mostly unconscious', 'Freud proposed personality is shaped by unconscious conflict between the id (pleasure-seeking drives), ego (reality-based mediator), and superego (internalized moral standards). Defense mechanisms (repression, projection, rationalization) manage anxiety from these conflicts.', 1, 6),
      mc('Emotional regulation strategies that are generally effective include:', ['Suppression — not expressing or acknowledging emotions', 'Rumination — repeatedly thinking about the cause of negative emotions', 'Cognitive reappraisal — reinterpreting the meaning of an event to change its emotional impact', 'Avoidance — staying away from all emotionally activating situations'], 'Cognitive reappraisal — reinterpreting the meaning of an event to change its emotional impact', 'Research consistently shows cognitive reappraisal (changing how you think about a situation) is more effective than suppression (pushing feelings down). Suppression reduces expression but not internal experience, while cognitive reappraisal changes both.', 1, 7),
      mc('The concept of self-efficacy (Bandura) refers to:', ['A person\'s actual ability level on a specific task', 'A person\'s belief in their ability to succeed in specific situations', 'The tendency to compare oneself favorably to others', 'Self-esteem as a global personality trait'], 'A person\'s belief in their ability to succeed in specific situations', 'Self-efficacy is task-specific and predicts performance better than general self-esteem. High self-efficacy leads to approaching challenges, persisting despite setbacks, and lower anxiety. It is built through mastery experiences, observation, and social encouragement.', 1, 8),
      oe('Explain how chronic stress affects physical health, providing at least two specific mechanisms.', 'Chronic stress maintains elevated cortisol levels, which: (1) suppresses immune function, making the body more vulnerable to illness and slower to heal — explaining why stressed people get sick more often; (2) promotes inflammation, which is linked to cardiovascular disease, type 2 diabetes, and accelerated aging; (3) damages the hippocampus (important for memory) through prolonged cortisol exposure; and (4) disrupts sleep through dysregulated HPA axis activity, creating a cycle that worsens stress. The stress response is adaptive for short-term threats but destructive when chronically activated.', 'The mind-body connection in stress is not metaphorical — it operates through concrete physiological pathways. This is why psychological interventions (mindfulness, therapy, social support) can have measurable physical health effects, and why psychological distress should be taken as seriously as physical symptoms.', 2, 9),
      oe('Compare Freud\'s psychoanalytic approach to personality with the social-cognitive approach (Bandura), identifying a strength and limitation of each.', 'Freud: Strength — emphasizes unconscious processes, early experience, and the complexity of motivation. Limitation — relies heavily on case studies, unfalsifiable concepts (how do you test the id?), and overemphasizes sexuality. Has poor predictive validity and is difficult to test empirically. Bandura\'s social-cognitive approach: Strength — emphasizes observable behavior, learning from others, and self-efficacy — all empirically testable with strong predictive validity. Limitation — may underemphasize unconscious processes, biological factors, and the depth of early developmental experiences. Neither theory fully captures personality\'s complexity.', 'No single personality theory is complete. The major theories each capture something true — psychoanalysis highlights the power of the unconscious; social-cognitive theory highlights learning and context; trait theory captures stable individual differences. Modern personality psychology draws on all of them while remaining empirical.', 2, 10),
    ],
  },
  'developmental-psychology': {
    title: 'Human Development Assessment', passingScore: 75, timeLimitMin: 25,
    questions: [
      mc('Piaget\'s concrete operational stage (ages 7-11) is characterized by:', ['Abstract reasoning and hypothetical thinking', 'Conservation — understanding that quantity stays the same despite changes in appearance', 'Object permanence — understanding objects exist when out of sight', 'Symbolic thinking and rapid language development'], 'Conservation — understanding that quantity stays the same despite changes in appearance', 'In the concrete operational stage, children can understand that a tall thin glass and a short wide glass can hold the same amount of water — quantity is conserved despite perceptual differences. This stage also sees logical thinking about concrete objects, though not yet abstract concepts.', 1, 1),
      mc('Secure attachment in infancy is associated with:', ['Minimal distress during separation from caregiver', 'Distress during separation but comfort and return to exploration upon reunion', 'Avoidance of the caregiver after separation', 'Inconsolable distress that prevents return to play after reunion'], 'Distress during separation but comfort and return to exploration upon reunion', 'Ainsworth\'s Strange Situation identified secure attachment: the infant uses the caregiver as a "safe base," protests separation, but is soothed by reunion and returns to exploration. Secure attachment predicts better social and emotional outcomes throughout childhood and adulthood.', 1, 2),
      mc('Erik Erikson\'s psychosocial theory proposes that development involves:', ['Fixed stages determined entirely by biology', 'A series of conflicts or crises at each life stage, with successful resolution supporting healthy development', 'Continuous gradual change without distinct stages', 'Personality becoming fixed by age five'], 'A series of conflicts or crises at each life stage, with successful resolution supporting healthy development', 'Erikson described eight stages from infancy to old age, each centered on a conflict (e.g., Trust vs. Mistrust, Identity vs. Role Confusion, Integrity vs. Despair). Unlike Freud, Erikson extended development through the entire lifespan and emphasized social context.', 1, 3),
      mc('Adolescent identity development (Erikson\'s Identity vs. Role Confusion) involves:', ['Accepting parents\' values without question', 'Exploring different roles, values, and beliefs before committing to an identity', 'Focusing exclusively on career goals', 'Resolving childhood attachment difficulties'], 'Exploring different roles, values, and beliefs before committing to an identity', 'Identity achievement (James Marcia\'s expansion of Erikson) requires a period of exploration (moratorium) followed by commitment. Those who foreclose (commit without exploring) or remain diffused (neither exploring nor committing) show different outcomes in psychological wellbeing.', 1, 4),
      mc('The concept of critical periods in development refers to:', ['Ages when academic learning is most efficient', 'Time windows when specific experiences have maximum impact on development and the absence of those experiences causes lasting effects', 'Sensitive periods when children are most emotionally vulnerable', 'Ages when cognitive development accelerates most rapidly'], 'Time windows when specific experiences have maximum impact on development and the absence of those experiences causes lasting effects', 'Language acquisition is a classic example: children who aren\'t exposed to language during the critical period (roughly birth to puberty) cannot fully acquire it later. Binocular vision development is another — covering one eye during the critical period causes permanent impairment in that eye.', 1, 5),
      mc('Vygotsky\'s zone of proximal development (ZPD) describes:', ['The gap between a child\'s actual and potential ability with guidance', 'The difference between a child\'s IQ and performance', 'The developmental tasks appropriate for each age group', 'The range of normal cognitive development at a given age'], 'The gap between a child\'s actual and potential ability with guidance', 'The ZPD is the distance between what a child can do independently and what they can do with support from a more skilled partner. Vygotsky argued that learning occurs in this zone — effective teaching operates just above current ability with appropriate scaffolding.', 1, 6),
      mc('Longitudinal research in developmental psychology:', ['Studies different age groups at one point in time', 'Follows the same individuals over an extended time period', 'Compares children from different cultures', 'Uses experimental manipulation to study development'], 'Follows the same individuals over an extended time period', 'Longitudinal studies track the same people over time — more informative than cross-sectional studies but expensive and subject to attrition. They can separate age effects from cohort effects and reveal actual developmental trajectories.', 1, 7),
      mc('According to research on aging, which cognitive abilities tend to remain stable or improve with age?', ['Processing speed and working memory capacity', 'Crystallized intelligence — accumulated knowledge and verbal ability', 'Spatial visualization and reaction time', 'Divided attention and multitasking ability'], 'Crystallized intelligence — accumulated knowledge and verbal ability', 'Fluid intelligence (speed, working memory, novel problem-solving) declines with age. Crystallized intelligence (vocabulary, general knowledge, expertise) remains stable or grows throughout much of adulthood. This is why experienced professionals often outperform younger ones despite slower processing.', 1, 8),
      oe('Explain how Piaget\'s concept of schema, assimilation, and accommodation apply to how a child learns that a dolphin is not a fish.', 'A child who has learned about fish has a "fish schema" — lives in water, has fins, swims. When they first see a dolphin, they assimilate it into the fish schema (it fits well enough). When told dolphins are actually mammals (they breathe air, nurse young with milk, are warm-blooded), the fish schema cannot accommodate this information without modification. Through accommodation, the child restructures the schema — fish breathe through gills and are cold-blooded; mammals breathe air and nurse young. The dolphin now has its own mental category. This cognitive restructuring is what Piaget meant by development.', 'Piaget\'s insight was that children don\'t just know less than adults — they think differently. The process of assimilation and accommodation drives cognitive growth as existing schemas encounter information they cannot fully handle. Disequilibrium (the discomfort of unfit information) motivates the restructuring that produces new understanding.', 2, 9),
      oe('Describe how both nature and nurture contribute to language development in children.', 'Nature: Humans are biologically prepared for language — we have Broca\'s area and Wernicke\'s area dedicated to language, a vocal tract shaped for speech, and a critical period for acquisition. Chomsky argued for a "language acquisition device" — an innate capacity for grammar. All human cultures develop language spontaneously. Nurture: Children must be exposed to language to acquire it — the specific language(s) they learn depend entirely on their environment. The richness of language input (vocabulary, complexity, back-and-forth interaction) predicts later language ability. Children who receive more language input — more words, more varied vocabulary, more conversational turns — develop stronger language skills. Both nature (biological capacity) and nurture (input and interaction) are necessary; neither alone is sufficient.', 'Language acquisition is one of the clearest examples of nature-nurture interaction. The biological foundation is universal; the outcome is specific to the child\'s linguistic environment. The "30-million word gap" research shows that by age 3, children from low-income homes may hear 30 million fewer words than those from high-income homes — with lasting educational consequences.', 2, 10),
    ],
  },
  'social-psychology': {
    title: 'Social Psychology Assessment', passingScore: 75, timeLimitMin: 25,
    questions: [
      mc('Milgram\'s obedience studies demonstrated that:', ['Only people with authoritarian personalities obey harmful commands', 'Ordinary people would administer apparent severe electric shocks to strangers when instructed by an authority figure', 'People always resist unjust authority when given a choice', 'Social pressure is only effective in public settings'], 'Ordinary people would administer apparent severe electric shocks to strangers when instructed by an authority figure', 'Milgram found that ~65% of participants delivered what they believed were maximum shocks (450V, labeled "XXX Danger") when pressured by an authority figure. This shocked the world and fundamentally changed how psychologists think about situational factors in harmful behavior.', 1, 1),
      mc('The fundamental attribution error refers to:', ['Overestimating situational causes of others\' behavior', 'Overestimating dispositional (personality) causes and underestimating situational factors when explaining others\' behavior', 'The tendency to take credit for successes and blame situations for failures', 'Assuming others share our own beliefs and preferences'], 'Overestimating dispositional (personality) causes and underestimating situational factors when explaining others\' behavior', 'We tend to explain others\' behavior as reflecting their character rather than their circumstances. We know our own situational pressures but not others\'. A famous study showed people rated a person who wrote a pro-Castro essay as actually pro-Castro even when told they were assigned to write it.', 1, 2),
      mc('Cognitive dissonance occurs when:', ['Two people disagree about an important issue', 'A person holds two conflicting beliefs or their behavior contradicts their beliefs, creating psychological discomfort', 'A person\'s attitudes are inconsistent with social norms', 'A group reaches an incorrect decision due to conformity pressure'], 'A person holds two conflicting beliefs or their behavior contradicts their beliefs, creating psychological discomfort', 'Festinger showed that when behavior conflicts with belief, people often change the belief rather than the behavior. Smokers who know smoking causes cancer may rationalize that the risk is overstated — changing the belief is easier than stopping smoking.', 1, 3),
      mc('Social loafing is most likely to occur when:', ['Individual contributions are identifiable and evaluated', 'Group tasks have high personal importance to members', 'Individual contributions are unidentifiable and the group is large', 'Group members are interdependent and each holds unique information'], 'Individual contributions are unidentifiable and the group is large', 'When individual effort can\'t be tracked (a group project, a tug-of-war), people exert less effort than when working alone. Accountability is the key moderating factor — identifiable contributions eliminate social loafing.', 1, 4),
      mc('In-group favoritism and out-group derogation appear to require:', ['Real conflict over resources (Realistic Conflict Theory)', 'Long-term contact with out-group members before developing', 'Only minimal categorization into groups — even arbitrary group membership produces bias', 'Personal prejudice developed through negative experiences'], 'Only minimal categorization into groups — even arbitrary group membership produces bias', 'Tajfel\'s minimal group paradigm showed that arbitrarily dividing people into groups (based on coin flips or trivial preferences) immediately produced in-group favoritism. The mere act of categorization triggers bias — resources don\'t need to be at stake.', 1, 5),
      mc('The bystander effect means that in emergencies:', ['People in groups always help faster than individuals alone', 'The more bystanders present, the less likely any individual is to help, due to diffusion of responsibility', 'Trained first responders are the only people likely to help', 'Helping behavior increases with crowd size'], 'The more bystanders present, the less likely any individual is to help, due to diffusion of responsibility', 'Latané and Darley identified two mechanisms: diffusion of responsibility (everyone assumes someone else will act) and pluralistic ignorance (everyone looks calm so everyone concludes it\'s not an emergency). The Kitty Genovese case inspired this research.', 1, 6),
      mc('Persuasion via the peripheral route (ELM) relies on:', ['Careful evaluation of argument quality and evidence', 'Superficial cues like source attractiveness, celebrity endorsement, or message length', 'Strong arguments tailored to the audience\'s existing beliefs', 'Two-sided arguments that address counterarguments'], 'Superficial cues like source attractiveness, celebrity endorsement, or message length', 'Petty and Cacioppo\'s Elaboration Likelihood Model proposes two routes. The central route involves careful thinking and produces durable attitude change. The peripheral route uses cognitive shortcuts and is effective when motivation or ability to think carefully is low.', 1, 7),
      mc('Self-fulfilling prophecy in social psychology means:', ['People always behave consistently with their stated beliefs', 'A belief causes behavior that confirms the original belief, even if the belief was initially false', 'Predictions about social behavior are always accurate', 'Social expectations have no effect on individual behavior'], 'A belief causes behavior that confirms the original belief, even if the belief was initially false', 'Teachers who expect students to be bright interact with them differently — offering more feedback, more challenging material, more patience. These interactions cause the students to perform better, confirming the initial expectation. Rosenthal and Jacobson\'s "Pygmalion effect" study demonstrated this in schools.', 1, 8),
      oe('Explain how the Stanford Prison Experiment (Zimbardo) and the Milgram obedience studies together challenge the dispositional view that "only bad people do bad things."', 'Both studies showed that situational factors can override individual character in producing harmful behavior. In Milgram, 65% of ordinary Americans obeyed authority to the apparent maximum shock level — not sadists, but ordinary people responding to situational pressure. In Zimbardo\'s Stanford Prison Experiment, randomly assigned college students playing "guards" became abusive within days, while "prisoners" became increasingly passive and distressed. Neither study shows that anyone in any situation would behave this way — but both show that situation can be far more powerful than we intuitively assume. The dispositional view (bad acts require bad people) dramatically underestimates the power of social context, institutional pressure, and role expectations.', 'These studies created an ethical revolution in psychology and changed how we think about moral responsibility. They have practical implications for designing institutions — prisons, military units, corporations — to minimize situational pressure toward abuse. They don\'t excuse harmful behavior, but they complicate simple attributions.', 2, 9),
      oe('Describe how contact between groups can reduce prejudice, and what conditions Allport identified as necessary for contact to be effective.', 'Allport\'s Contact Hypothesis (1954) proposed that mere contact is not enough to reduce prejudice — conditions matter. Effective contact requires: (1) equal status between groups in the contact situation; (2) common goals that require cooperation; (3) no competition between groups; and (4) institutional support (authority sanction for the contact). When these conditions are met, contact allows for disconfirmation of stereotypes through personal knowledge, increases empathy, and shifts from category-level (group) to individual-level perception. Evidence from school integration, military desegregation, and intergroup friendship research generally supports the hypothesis when conditions are met.', 'The Contact Hypothesis has been influential in policy: school integration, cooperative classroom structures, and intergroup dialogue programs all draw on it. The conditions are crucial — contact under competitive or unequal conditions can worsen prejudice. This is why simply putting groups together is insufficient without deliberate structural conditions.', 2, 10),
    ],
  },
  'abnormal-psychology': {
    title: 'Psychological Disorders Assessment', passingScore: 75, timeLimitMin: 25,
    questions: [
      mc('The DSM-5 (Diagnostic and Statistical Manual) is primarily used for:', ['Prescribing medication for mental disorders', 'Providing standardized diagnostic criteria for mental disorders to ensure consistent diagnosis', 'Rating the severity of mental illness for legal purposes', 'Training therapists in specific treatment techniques'], 'Providing standardized diagnostic criteria for mental disorders to ensure consistent diagnosis', 'The DSM-5 lists specific symptom criteria, duration requirements, and exclusion criteria for each disorder. It enables clinicians and researchers to use the same language, facilitating communication, research, and insurance billing — though critics note its limitations.', 1, 1),
      mc('Generalized Anxiety Disorder is primarily characterized by:', ['Panic attacks triggered by specific situations', 'Excessive, uncontrollable worry about multiple areas of life for at least 6 months', 'Intrusive thoughts with compulsive rituals', 'Fear of social situations and evaluation'], 'Excessive, uncontrollable worry about multiple areas of life for at least 6 months', 'GAD involves pervasive, hard-to-control worry across multiple domains (health, work, family, finances), causing significant distress and impairment. It\'s distinguished from normal anxiety by its chronicity, uncontrollability, and breadth.', 1, 2),
      mc('The biopsychosocial model of mental disorders emphasizes that:', ['Biological causes alone determine mental illness', 'Mental disorders result from the interaction of biological vulnerability, psychological factors, and social context', 'Social factors are more important than biological ones', 'Psychological disorders are purely learned behaviors'], 'Mental disorders result from the interaction of biological vulnerability, psychological factors, and social context', 'The biopsychosocial model replaced single-cause explanations. Depression, for example, involves genetic predisposition (biological), cognitive patterns of helplessness (psychological), and life stressors or lack of social support (social). Effective treatment often addresses all three levels.', 1, 3),
      mc('SSRIs (selective serotonin reuptake inhibitors) treat depression by:', ['Increasing dopamine production in the reward system', 'Blocking reabsorption of serotonin, increasing its availability in synapses', 'Replacing depleted serotonin stores directly', 'Stimulating the parasympathetic nervous system'], 'Blocking reabsorption of serotonin, increasing its availability in synapses', 'SSRIs prevent the presynaptic neuron from reabsorbing serotonin after release, leaving more serotonin in the synapse to bind with receptors. They are first-line because they\'re safer in overdose than tricyclics and have a more tolerable side effect profile than MAOIs.', 1, 4),
      mc('Major Depressive Disorder requires at least:', ['2 weeks of depressed mood or anhedonia plus at least 4 additional symptoms, causing significant impairment', '6 months of persistent sadness', 'A previous manic episode', 'Psychotic features including hallucinations'], '2 weeks of depressed mood or anhedonia plus at least 4 additional symptoms, causing significant impairment', 'DSM-5 requires 5+ symptoms over at least 2 weeks, with depressed mood OR anhedonia (loss of pleasure) being required. Symptoms include sleep changes, appetite changes, concentration problems, fatigue, worthlessness, and suicidal ideation.', 1, 5),
      mc('Cognitive Behavioral Therapy (CBT) works by:', ['Uncovering unconscious childhood conflicts through free association', 'Identifying and changing maladaptive thought patterns and behaviors that maintain psychological distress', 'Providing a supportive relationship in which clients discover their own solutions', 'Prescribing medication alongside insight-oriented therapy'], 'Identifying and changing maladaptive thought patterns and behaviors that maintain psychological distress', 'CBT is structured, present-focused, and skill-based. It targets the connection between thoughts (cognitions), feelings, and behaviors. Techniques include thought records, behavioral experiments, exposure, and activity scheduling. It is one of the most empirically supported treatments across many disorders.', 1, 6),
      mc('Schizophrenia is characterized by:', ['Alternating periods of depression and mania', 'Multiple distinct personality states', 'Positive symptoms (hallucinations, delusions, disorganized thinking) and negative symptoms (flat affect, avolition, social withdrawal)', 'Chronic anxiety with occasional panic attacks'], 'Positive symptoms (hallucinations, delusions, disorganized thinking) and negative symptoms (flat affect, avolition, social withdrawal)', 'Positive symptoms involve added experiences (perceptions and beliefs not present in healthy functioning). Negative symptoms involve the absence of normal experiences. Both respond differently to treatment and reflect different underlying neurobiological mechanisms.', 1, 7),
      mc('Stigma around mental illness is harmful because:', ['It encourages people to seek help by highlighting severity', 'It deters people from seeking treatment, causes social exclusion, and leads to self-stigma that worsens outcomes', 'It accurately reflects the dangerousness of mental illness', 'It primarily affects clinicians, not patients'], 'It deters people from seeking treatment, causes social exclusion, and leads to self-stigma that worsens outcomes', 'Mental health stigma is a major barrier to care. People avoid seeking help to avoid the label; once labeled, they face discrimination in employment, housing, and relationships; they may internalize negative stereotypes, reducing self-efficacy. Reducing stigma through education and contact with people with mental illness has documented effects on treatment-seeking.', 1, 8),
      oe('Explain why accurate diagnosis of psychological disorders is important, but also why diagnosis alone is not sufficient for effective treatment.', 'Accurate diagnosis is important because it guides treatment selection — effective interventions differ by disorder (exposure therapy for phobias; lithium for bipolar; CBT for depression; antipsychotics for schizophrenia). A missed or wrong diagnosis can lead to ineffective or harmful treatment. However, diagnosis is not sufficient because: the same diagnosis can manifest very differently across individuals; cultural context shapes presentation and what counts as "impairment"; comorbid conditions complicate treatment; and the therapeutic relationship, individual strengths, life context, and patient preferences all affect outcomes. Good treatment is individualized, not just diagnosis-matched.', 'Diagnosis is a starting point, not an endpoint. The DSM categories were designed for research reliability, not necessarily for treatment guidance. Effective clinicians use diagnosis as one input among many — alongside patient history, goals, preferences, strengths, and social context. Person-centered care means treating the person, not just the diagnosis.', 2, 9),
      oe('Compare two evidence-based psychotherapy approaches — CBT and psychodynamic therapy — in terms of their theory of change and what kinds of problems they are best suited to treat.', 'CBT: Theory of change — psychological distress results from distorted thinking and maladaptive behaviors; change cognitions and behaviors and emotions follow. Techniques: thought records, behavioral activation, exposure. Best suited: anxiety disorders, depression, OCD, PTSD, eating disorders. Typical duration: 12-20 sessions. Psychodynamic therapy: Theory of change — symptoms reflect unconscious conflicts, relational patterns, and unresolved developmental issues; bringing these into conscious awareness and working through them in the therapeutic relationship produces change. Techniques: free association, dream analysis, transference interpretation. Best suited: personality disorders, chronic relationship difficulties, complex trauma, when patients want deeper self-understanding. Typical duration: longer term. Both have empirical support; choice depends on the problem, patient preference, and available resources.', 'The "dodo bird verdict" — that all evidence-based therapies produce roughly equivalent outcomes — suggests common factors (therapeutic alliance, hope, coherent rationale) may matter as much as specific techniques. The best therapy is often the one the patient will engage with. Understanding the theoretical basis helps clinicians match approach to problem.', 2, 10),
    ],
  },
}
