import type { ExerciseDef } from '../types';

const mc = (
  question: string,
  options: string[],
  correctAnswer: string,
  explanation: string,
  order: number
): ExerciseDef => ({ question, type: 'MULTIPLE_CHOICE', options, correctAnswer, explanation, order });

export const psychologyExercises6: Record<string, ExerciseDef[]> = {
  'anxiety-disorders': [
    mc('Generalized Anxiety Disorder (GAD) is characterized by:', ['Panic attacks triggered by specific objects', 'Excessive, uncontrollable worry about many areas of life', 'Fear of social evaluation only', 'Intrusive thoughts with compulsive rituals'], 'Excessive, uncontrollable worry about many areas of life', 'GAD involves pervasive, hard-to-control worry lasting at least six months across multiple domains (health, work, relationships) — not focused on one specific trigger.', 1),
    mc('A panic attack reaches peak intensity within:', ['Several hours', 'Ten minutes', 'One to two days', 'Thirty seconds'], 'Ten minutes', 'The DSM-5 defines a panic attack as a sudden surge of intense fear peaking within minutes, involving at least four physical or cognitive symptoms such as racing heart, shortness of breath, and derealization.', 2),
    mc('Social anxiety disorder primarily involves fear of:', ['Open or crowded spaces', 'Negative evaluation in social or performance situations', 'Specific animals or objects', 'Losing control without a safety person present'], 'Negative evaluation in social or performance situations', 'People with social anxiety disorder fear embarrassment or humiliation, leading them to avoid situations like public speaking, eating in public, or meeting new people.', 3),
    mc('The core feature of PTSD that distinguishes it from acute stress reaction is:', ['Presence of nightmares', 'Duration beyond one month after the trauma', 'Avoidance of trauma reminders', 'Hypervigilance to danger'], 'Duration beyond one month after the trauma', 'Both acute stress disorder and PTSD involve re-experiencing, avoidance, and hyperarousal; PTSD is diagnosed when symptoms persist more than one month post-trauma.', 4),
    mc('Exposure therapy for phobias works primarily through:', ['Insight into childhood origins of fear', 'Extinction of fear through repeated non-harmful contact', 'Medication that blocks adrenaline', 'Cognitive restructuring of conscious beliefs only'], 'Extinction of fear through repeated non-harmful contact', 'Graduated exposure allows the fear response to extinguish because the feared stimulus is encountered without the expected harm, updating threat predictions in the brain\'s fear circuits.', 5),
  ],
  'mood-disorders': [
    mc('Major Depressive Disorder requires symptoms lasting at least:', ['Two weeks', 'Six months', 'One year', 'One week'], 'Two weeks', 'MDD requires five or more symptoms (including depressed mood or anhedonia) present for at least two weeks, representing a change from prior functioning and causing significant impairment.', 1),
    mc('Bipolar I disorder requires at least one episode of:', ['Hypomania without depression', 'Major depression without mania', 'Full mania, which may include psychosis', 'Dysthymia lasting two years'], 'Full mania, which may include psychosis', 'A single manic episode lasting at least one week (or any duration if hospitalization is required) is sufficient for a Bipolar I diagnosis; depressive episodes are common but not required by the criteria.', 2),
    mc('Persistent Depressive Disorder (dysthymia) is defined by:', ['Discrete episodes of severe depression', 'Chronic low-grade depression lasting at least two years', 'Rapid cycling between high and low moods', 'Seasonal pattern of depression only in winter'], 'Chronic low-grade depression lasting at least two years', 'Dysthymia involves a depressed mood for most of the day, more days than not, for at least two years, with fewer symptoms than MDD but significant long-term impairment.', 3),
    mc('Which neurotransmitter is most commonly implicated in depression research?', ['Dopamine', 'GABA', 'Serotonin', 'Acetylcholine'], 'Serotonin', 'The monoamine hypothesis links depression to deficits in serotonin (and norepinephrine); while more complex than this simple model, it forms the basis for SSRI antidepressant development.', 4),
    mc('Cognitive therapy for depression targets:', ['Unconscious drives and childhood conflicts', 'Automatic negative thoughts and cognitive distortions', 'Conditioned physiological arousal', 'Social reinforcement patterns only'], 'Automatic negative thoughts and cognitive distortions', 'Beck\'s cognitive therapy identifies and challenges the negative automatic thoughts and underlying dysfunctional beliefs (e.g., "I\'m worthless") that maintain depressive mood.', 5),
  ],
  'psychotherapy': [
    mc('Psychoanalysis and psychodynamic therapy primarily explore:', ['Current behavioral patterns and their reinforcement', 'Unconscious conflicts, early experiences, and defense mechanisms', 'Maladaptive thoughts and beliefs', 'Skills for managing acute crisis'], 'Unconscious conflicts, early experiences, and defense mechanisms', 'Derived from Freud, psychodynamic approaches assume symptoms arise from unconscious conflicts; therapy brings these to consciousness through free association, dream analysis, and transference interpretation.', 1),
    mc('Cognitive-Behavioral Therapy (CBT) is best described as:', ['Insight-oriented and long-term', 'Structured, present-focused, and skills-based', 'Rooted in humanistic philosophy', 'Based on classical conditioning alone'], 'Structured, present-focused, and skills-based', 'CBT is typically time-limited, collaborative, and homework-oriented; it targets the interplay between thoughts, feelings, and behaviors using techniques like thought records and behavioral experiments.', 2),
    mc('Client-centered (humanistic) therapy emphasizes the therapist providing:', ['Expert guidance and direct advice', 'Unconditional positive regard, empathy, and genuineness', 'Systematic desensitization hierarchies', 'Pharmacological support alongside talk therapy'], 'Unconditional positive regard, empathy, and genuineness', 'Rogers\' person-centered approach holds that a growth-promoting therapeutic relationship — characterized by warmth, accurate empathy, and genuineness — is the core change mechanism.', 3),
    mc('Dialectical Behavior Therapy (DBT) was originally developed to treat:', ['Schizophrenia spectrum disorders', 'Borderline personality disorder', 'Specific phobias', 'Attention-deficit/hyperactivity disorder'], 'Borderline personality disorder', 'Linehan developed DBT to address the high suicidality and emotional dysregulation in BPD; it blends acceptance strategies from mindfulness with change strategies from CBT.', 4),
    mc('Research on psychotherapy effectiveness consistently finds:', ['Psychoanalysis is clearly superior to all other approaches', 'There is essentially no difference — therapy never helps', 'Most evidence-based therapies produce similar positive outcomes', 'Therapy helps but only with medication added'], 'Most evidence-based therapies produce similar positive outcomes', 'The "dodo bird verdict" — from comparative outcome studies — is that different bona fide therapies produce roughly equivalent outcomes, suggesting common factors (alliance, hope) are key.', 5),
  ],
  'medication': [
    mc('SSRIs are the first-line medication for depression primarily because:', ['They are more effective than all older drugs', 'They have a safer side-effect profile than tricyclics and MAOIs', 'They work within 24 hours', 'They have no drug interactions'], 'They have a safer side-effect profile than tricyclics and MAOIs', 'SSRIs are not necessarily more effective than older antidepressants, but their reduced risk of overdose and more tolerable side effects make them safer and easier to prescribe.', 1),
    mc('Antipsychotic medications primarily target which neurotransmitter system?', ['Serotonin', 'GABA', 'Dopamine', 'Acetylcholine'], 'Dopamine', 'First-generation antipsychotics block D2 dopamine receptors; the dopamine hypothesis of schizophrenia (excess dopamine in mesolimbic pathways) underpins this approach, though second-generation drugs also affect serotonin.', 2),
    mc('A major concern with long-term use of benzodiazepines is:', ['They cause permanent memory erasure', 'Dependence, tolerance, and rebound anxiety on discontinuation', 'They have no effect without therapy', 'They require genetic testing before use'], 'Dependence, tolerance, and rebound anxiety on discontinuation', 'Benzodiazepines are effective for short-term anxiety relief but carry high dependency risk; abrupt discontinuation can cause severe rebound anxiety and, in some cases, seizures.', 3),
    mc('Mood stabilizers like lithium are most commonly used for:', ['Generalized anxiety disorder', 'Bipolar disorder', 'Specific phobias', 'Obsessive-compulsive disorder'], 'Bipolar disorder', 'Lithium reduces the frequency and severity of both manic and depressive episodes in bipolar disorder; it requires careful monitoring of blood levels due to a narrow therapeutic window.', 4),
    mc('Placebo-controlled trials in psychopharmacology are important because:', ['Placebos have no effect on mental symptoms', 'People often improve from expectation alone, so real drug effects must exceed this baseline', 'Ethical guidelines require no-treatment conditions', 'Medications always outperform placebos by large margins'], 'People often improve from expectation alone, so real drug effects must exceed this baseline', 'Placebo response rates in depression trials can reach 30–40%; only effects significantly above placebo provide evidence that the drug has a specific pharmacological benefit.', 5),
  ],
  'accessing-help': [
    mc('One of the biggest barriers to people seeking mental health treatment is:', ['Lack of awareness that treatments exist', 'Stigma and fear of being judged', 'Excessive availability of providers', 'Required hospitalization for any diagnosis'], 'Stigma and fear of being judged', 'Stigma — both social and self-stigma — remains one of the most consistent predictors of treatment avoidance; people fear being seen as weak, unstable, or dangerous if they seek help.', 1),
    mc('Crisis hotlines and text lines are designed to provide:', ['Long-term therapy relationships', 'Immediate support and safety assessment during acute distress', 'Medication prescriptions over the phone', 'Formal DSM diagnosis'], 'Immediate support and safety assessment during acute distress', 'Crisis services offer real-time connection when someone is overwhelmed or suicidal; trained counselors provide empathy, safety planning, and referrals to appropriate levels of care.', 2),
    mc('Stepped care in mental health means:', ['All patients begin with the most intensive treatment', 'Starting with the least intensive effective intervention and escalating as needed', 'Skipping mild interventions for efficiency', 'Using medication before therapy in every case'], 'Starting with the least intensive effective intervention and escalating as needed', 'Stepped care matches treatment intensity to need — e.g., self-help tools first, then brief therapy, then specialist care — making efficient use of resources and avoiding over-treatment.', 3),
    mc('Peer support specialists in mental health are distinguished by:', ['Having medical degrees in psychiatry', 'Living experience of mental health challenges, used therapeutically', 'Providing medication management only', 'Working exclusively in inpatient settings'], 'Living experience of mental health challenges, used therapeutically', 'Peer support workers use their own recovery journey to build rapport and hope with clients; research supports their effectiveness as a complement to professional services.', 4),
    mc('Psychoeducation as part of treatment primarily involves:', ['Hypnotherapy and suggestion', 'Teaching patients and families about the disorder and its management', 'Electroconvulsive therapy protocols', 'Strict behavioral contracts without explanation'], 'Teaching patients and families about the disorder and its management', 'Psychoeducation improves outcomes by helping people understand their diagnosis, recognize early warning signs, and engage more effectively with treatment — especially in mood and psychotic disorders.', 5),
  ],
};
