import type { ExerciseDef } from '../types'

function mc(
  question: string,
  options: string[],
  correctAnswer: string,
  explanation: string,
  order: number
): ExerciseDef {
  return { question, type: 'MULTIPLE_CHOICE', options, correctAnswer, explanation, order }
}

export const psychologyExercises3: Record<string, ExerciseDef[]> = {
  'what-emotions-are': [
    mc('What are the components of an emotion?', ['Only subjective feelings', 'A physiological response, a behavioral response, and a subjective feeling — all three interact to produce emotional experience', 'Only observable behaviors', 'A cognitive appraisal only'], 'A physiological response, a behavioral response, and a subjective feeling — all three interact to produce emotional experience', 'Emotion involves: body (racing heart, sweating — physiological); behavior (running, smiling — expressive); and feeling (fear, joy — subjective experience). Theories differ on which comes first, but all three are present.', 1),
    mc('What does the James-Lange theory of emotion propose?', ['Emotion is caused by a physiological response: we feel afraid because we tremble, not trembling because we\'re afraid', 'Emotions cause physiological changes', 'Physiological and emotional responses occur simultaneously', 'Emotions are cognitive appraisals of situations'], 'Emotion is caused by a physiological response: we feel afraid because we tremble, not trembling because we\'re afraid', 'James-Lange: stimulus → physiological arousal → cognitive interpretation of arousal = emotion. We don\'t run because we\'re afraid; we\'re afraid because we run. The body\'s response IS the emotion.', 2),
    mc('What did Schachter and Singer\'s two-factor theory propose?', ['Emotion has two components: physiological and behavioral', 'Emotion = physiological arousal + cognitive label for that arousal — the same arousal can become different emotions depending on what we attribute it to', 'Two types of emotion: basic and complex', 'Emotions are either cognitive or physiological, never both'], 'Emotion = physiological arousal + cognitive label for that arousal — the same arousal can become different emotions depending on what we attribute it to', 'Schachter & Singer: arousal without explanation → people look to context for explanation. Fear or excitement produce similar arousal — the label depends on interpretation. Misattribution of arousal: inexplicable arousal gets attributed to whoever is around.', 3),
    mc('What are Paul Ekman\'s basic emotions?', ['Happy, sad, angry, scared, and surprised — five universal emotions', 'Happiness, sadness, anger, fear, surprise, and disgust — six emotions with universally recognized facial expressions', 'Love, hate, fear, and joy — four fundamental emotional states', 'Any emotion that can be named in all human languages'], 'Happiness, sadness, anger, fear, surprise, and disgust — six emotions with universally recognized facial expressions', 'Ekman studied facial expressions across cultures including isolated tribes with no media exposure — finding consistent recognition of the same six expressions. This suggests a biological basis for basic emotional expression.', 4),
    mc('What is emotional regulation?', ['Suppressing all negative emotions', 'The ability to manage, influence, and modify one\'s emotional responses — using strategies like reappraisal, distraction, and acceptance', 'Expressing emotions fully and without restraint', 'A process that only works through therapy'], 'The ability to manage, influence, and modify one\'s emotional responses — using strategies like reappraisal, distraction, and acceptance', 'Emotional regulation includes reappraisal (reinterpreting a situation\'s meaning), suppression (hiding expression, which backfires), distraction, mindfulness, and social sharing. Reappraisal is the healthiest and most effective strategy.', 5),
  ],
  'theories-of-motivation': [
    mc('What is Maslow\'s hierarchy of needs?', ['A theory that all needs are equally important', 'A hierarchical model from basic physiological needs (food, safety) to higher needs (belonging, esteem, self-actualization)', 'A theory that only survival needs motivate behavior', 'A ranking of what most people want from their jobs'], 'A hierarchical model from basic physiological needs (food, safety) to higher needs (belonging, esteem, self-actualization)', 'Maslow\'s pyramid (1943): Physiological → Safety → Belonging → Esteem → Self-actualization. Lower needs must be met before higher ones become motivating. Criticized for Western cultural assumptions and lack of empirical support.', 1),
    mc('What is the difference between intrinsic and extrinsic motivation?', ['Intrinsic is more powerful; extrinsic is less effective', 'Intrinsic motivation comes from internal satisfaction; extrinsic comes from external rewards or pressures', 'Extrinsic motivation is only for material rewards', 'They produce identical results for complex creative tasks'], 'Intrinsic motivation comes from internal satisfaction; extrinsic comes from external rewards or pressures', 'Intrinsic: writing because you love it. Extrinsic: writing for a grade. Overjustification effect: adding external rewards to intrinsic activities can undermine intrinsic motivation — people start doing it "for the reward" rather than for the activity itself.', 2),
    mc('What does Self-Determination Theory propose?', ['People are most motivated by external rewards', 'Three universal psychological needs — autonomy (choice), competence (mastery), and relatedness (connection) — drive intrinsic motivation', 'Motivation is entirely determined by past experiences and habits', 'All people are motivated by the same things regardless of cultural context'], 'Three universal psychological needs — autonomy (choice), competence (mastery), and relatedness (connection) — drive intrinsic motivation', 'Deci and Ryan\'s SDT: when environments support autonomy, competence, and relatedness, people become intrinsically motivated. Controlling environments (micromanagement, threats) undermine intrinsic motivation even for enjoyable activities.', 3),
    mc('What is the overjustification effect?', ['The tendency to over-explain why we are motivated', 'When adding external rewards to an intrinsically motivating activity reduces enjoyment and interest in that activity', 'Over-motivation leading to burnout', 'Excessive use of rewards creating dependency'], 'When adding external rewards to an intrinsically motivating activity reduces enjoyment and interest in that activity', 'Lepper et al. (1973): children who loved drawing drew less after being given expected rewards for drawing. Externally rewarded, they came to see drawing as "work for reward" rather than fun — the reward undermined intrinsic motivation.', 4),
    mc('What is flow?', ['A state of reduced motivation when bored', 'A state of complete absorption in a challenging but manageable task — characterized by effortless concentration and loss of self-consciousness', 'A relaxation technique used to reduce stress', 'The experience of completing a difficult task'], 'A state of complete absorption in a challenging but manageable task — characterized by effortless concentration and loss of self-consciousness', 'Csikszentmihalyi\'s concept: flow occurs when skill level matches challenge level. Too easy = boredom; too hard = anxiety; matched = flow. Athletes, musicians, gamers, and surgeons describe flow as the peak of intrinsic motivation.', 5),
  ],
  'stress-and-coping': [
    mc('What is the General Adaptation Syndrome (GAS)?', ['The tendency for people to adapt to any stressor within a few days', 'Selye\'s three-stage model of stress response: alarm (fight or flight), resistance (adaptation), exhaustion (resources depleted)', 'A general theory of how people cope with stress differently', 'The body\'s immune response to psychological stress'], 'Selye\'s three-stage model of stress response: alarm (fight or flight), resistance (adaptation), exhaustion (resources depleted)', 'Selye (1950s): alarm — the initial stress response; resistance — the body adapts and maintains functioning; exhaustion — prolonged stress depletes resources, leaving the body vulnerable to illness. Chronic stress = exhaustion phase.', 1),
    mc('What is the cognitive appraisal theory of stress?', ['All people respond to the same stressors identically', 'Stress depends on how we appraise (interpret) events — as threatening or manageable — and whether we believe we have the resources to cope', 'Stress is purely physiological with no cognitive component', 'Stressors are only external events, never internal thoughts'], 'Stress depends on how we appraise (interpret) events — as threatening or manageable — and whether we believe we have the resources to cope', 'Lazarus and Folkman: primary appraisal (is this threatening?) + secondary appraisal (can I cope?) = stress level. The same event causes different stress in different people based on their interpretation and perceived coping resources.', 2),
    mc('What is the difference between problem-focused and emotion-focused coping?', ['Problem-focused is more effective in all situations', 'Problem-focused coping targets the stressor itself; emotion-focused coping manages the emotional response to stress', 'Emotion-focused is only for minor stressors', 'They are two names for the same coping strategy'], 'Problem-focused coping targets the stressor itself; emotion-focused coping manages the emotional response to stress', 'Problem-focused: identify and address the source of stress. Best when you have control over the stressor. Emotion-focused: manage your emotional reaction. Better when the stressor is uncontrollable (death, natural disaster). Effective copers match strategy to situation.', 3),
    mc('How does social support affect stress?', ['Social support doesn\'t affect physical health outcomes', 'Social support buffers the effects of stress — socially connected people show lower cortisol responses, better health outcomes, and greater resilience', 'Social support increases stress by creating additional obligations', 'Only professional support from therapists is effective'], 'Social support buffers the effects of stress — socially connected people show lower cortisol responses, better health outcomes, and greater resilience', 'The social buffering hypothesis: social connection dampens the biological stress response. Isolated people have higher cortisol and worse health outcomes. Loneliness is as harmful as smoking 15 cigarettes a day (Holt-Lunstad).', 4),
    mc('What is the relationship between stress and the immune system?', ['Stress always strengthens the immune system', 'Short-term stress can boost immunity; chronic stress suppresses it — making people more vulnerable to illness, slower to heal, and more susceptible to inflammation', 'Stress has no effect on the immune system', 'The immune system is completely independent of psychological states'], 'Short-term stress can boost immunity; chronic stress suppresses it — making people more vulnerable to illness, slower to heal, and more susceptible to inflammation', 'The field of psychoneuroimmunology: chronic stress reduces natural killer cell activity, slows wound healing, and increases inflammatory cytokines. Medical student studies show compromised immune function during exam periods.', 5),
  ],
  'personality-theories': [
    mc('What is the Big Five (OCEAN) personality model?', ['Freud\'s five stages of personality development', 'A research-based model identifying five major personality dimensions: Openness, Conscientiousness, Extraversion, Agreeableness, Neuroticism', 'A five-type personality classification system', 'A therapeutic framework for treating five major personality disorders'], 'A research-based model identifying five major personality dimensions: Openness, Conscientiousness, Extraversion, Agreeableness, Neuroticism', 'The Big Five emerges from factor analysis of personality data across cultures. Each trait is a dimension (high-low), not a category. Highly predictive of life outcomes: conscientiousness predicts academic success, career success, and longevity.', 1),
    mc('What did Freud\'s psychoanalytic theory propose about personality?', ['Personality is entirely shaped by adult experiences', 'Personality develops through childhood stages; unconscious conflicts between id (pleasure), ego (reality), and superego (morality) drive behavior', 'Personality is primarily determined by genetics', 'Personality is shaped by social learning and reinforcement'], 'Personality develops through childhood stages; unconscious conflicts between id (pleasure), ego (reality), and superego (morality) drive behavior', 'Freud\'s id (primitive drives), ego (reality-based mediator), and superego (internalized morality) are in constant conflict. Unresolved conflicts produce defense mechanisms (repression, projection) and neurosis.', 2),
    mc('What is the humanistic view of personality?', ['Personality is determined by unconscious drives', 'People have an innate drive toward growth and self-actualization; personality reflects the degree to which basic needs are met and authentic self-expression is possible', 'Personality is shaped entirely by conditioning', 'Personality consists of stable, inherited traits'], 'People have an innate drive toward growth and self-actualization; personality reflects the degree to which basic needs are met and authentic self-expression is possible', 'Rogers: people have an actualizing tendency (drive to grow). A healthy personality requires congruence between self-concept and experience, and receiving unconditional positive regard rather than conditional love.', 3),
    mc('What is the social-cognitive theory of personality?', ['Personality is determined by social status', 'Personality emerges from the interaction between behavior, personal factors (thoughts, beliefs, expectations), and environment — Bandura\'s reciprocal determinism', 'Social factors determine personality; cognition is irrelevant', 'Personality is entirely a product of cultural socialization'], 'Personality emerges from the interaction between behavior, personal factors (thoughts, beliefs, expectations), and environment — Bandura\'s reciprocal determinism', 'Bandura: behavior, internal factors, and environment mutually influence each other — none is primary. Self-efficacy (belief in your ability to accomplish goals) is a key personality variable predicting performance.', 4),
    mc('What is a personality type vs. a personality trait?', ['Types are more accurate than traits', 'Types place people in discrete categories; traits describe continuous dimensions on which people differ in degree rather than kind', 'Traits are binary; types are continuous', 'They are different words for the same concept'], 'Types place people in discrete categories; traits describe continuous dimensions on which people differ in degree rather than kind', 'MBTI types (introvert vs. extrovert) are discrete categories. Big Five traits are continuous dimensions — you\'re not either extroverted or introverted but somewhere on a spectrum. Research generally supports trait models over type models.', 5),
  ],
  'personality-assessment': [
    mc('What is a self-report personality inventory?', ['A test scored by a psychologist', 'A questionnaire where individuals report their own traits, behaviors, and preferences — like the Big Five personality scales', 'An IQ test measuring personality through cognitive tasks', 'A behavioral observation conducted by a trained observer'], 'A questionnaire where individuals report their own traits, behaviors, and preferences — like the Big Five personality scales', 'Self-report inventories (MMPI, NEO-PI-R, Big Five scales) are widely used. Their validity depends on honest responding — social desirability bias (presenting oneself favorably) is a significant limitation.', 1),
    mc('What is a projective personality test?', ['A test projecting images onto a screen for reaction time measurement', 'An ambiguous stimulus presented to subjects who "project" their unconscious feelings into their interpretations (Rorschach inkblots, TAT)', 'A test measuring how personality projects across different situations', 'A computer simulation of personality development'], 'An ambiguous stimulus presented to subjects who "project" their unconscious feelings into their interpretations (Rorschach inkblots, TAT)', 'Projective tests assume that ambiguous stimuli elicit unconscious material. The Rorschach (inkblots) and TAT (ambiguous pictures) are classic examples. Their reliability and validity are heavily debated.', 2),
    mc('What is the fundamental attribution error in personality assessment?', ['Attributing all behavior to personality when situational factors are often decisive', 'Attributing all behavior to external situations and ignoring personality', 'Overestimating the reliability of personality tests', 'Using personality tests to make employment decisions'], 'Attributing all behavior to personality when situational factors are often decisive', 'The fundamental attribution error: we overestimate dispositional factors and underestimate situational factors. Milgram showed that ordinary people commit extraordinary acts under situational pressure — demonstrating personality\'s limits.', 3),
    mc('What does research on the stability of personality show?', ['Personality is completely fixed by age 5', 'Personality traits are moderately stable across adulthood but do show systematic change — people tend to become more agreeable, conscientious, and emotionally stable with age', 'Personality is entirely unstable and changes constantly', 'Personality can only change through intensive therapy'], 'Personality traits are moderately stable across adulthood but do show systematic change — people tend to become more agreeable, conscientious, and emotionally stable with age', 'Rank-order stability (your relative position vs. others) is high. But mean-level change shows consistent patterns: most people become less neurotic and more conscientious after 30 — suggesting personality development continues throughout adulthood.', 4),
    mc('What is the person-situation debate?', ['Whether personality is biological or learned', 'The debate about how much behavior is determined by stable personality traits vs. situational factors — Mischel vs. trait theorists', 'Whether personality can be measured accurately', 'Whether personality tests are ethical to use in hiring'], 'The debate about how much behavior is determined by stable personality traits vs. situational factors — Mischel vs. trait theorists', 'Mischel (1968): behavior is more situation-specific than trait models suggest. Counter: aggregated behavior across many situations does show trait consistency. Modern view: traits predict behavior in relevant situations, especially with large samples.', 5),
  ],
  'nature-vs-nurture': [
    mc('What does behavioral genetics research tell us about the nature/nurture question?', ['Virtually all traits are entirely genetic', 'Most psychological traits show both genetic and environmental influences — typically with moderate heritability and significant environmental effects', 'Environment determines virtually everything; genes matter little', 'Nature and nurture have completely separate effects that don\'t interact'], 'Most psychological traits show both genetic and environmental influences — typically with moderate heritability and significant environmental effects', 'Meta-analyses of twin studies find heritabilities of ~50% for personality traits, intelligence, and many mental disorders — meaning environment explains the other 50%. No complex psychological trait is 100% genetic or 100% environmental.', 1),
    mc('What is gene-environment interaction?', ['Genes and environment work in opposition to each other', 'The idea that the effects of genes depend on the environment and vice versa — the same gene can have different effects in different environments', 'A statistical method for separating genetic from environmental influences', 'The process by which environmental factors alter genetic sequences'], 'The idea that the effects of genes depend on the environment and vice versa — the same gene can have different effects in different environments', 'The warrior/worrier COMT gene variant: in low-stress environments, the "warrior" variant excels; under high stress, the "worrier" variant does better. Genes don\'t determine traits — they interact with environments to produce them.', 2),
    mc('What is gene-environment correlation?', ['The finding that genes and environment are unrelated', 'The tendency of individuals with certain genetic predispositions to select, evoke, or create environments that match those predispositions', 'Environmental factors causing genetic mutations', 'The statistical correlation between twin pair genetic similarity and personality similarity'], 'The tendency of individuals with certain genetic predispositions to select, evoke, or create environments that match those predispositions', 'Passive: parents who give their musically inclined child music lessons. Evocative: a shy child elicits different responses from others. Active: a musically gifted teenager seeks out music environments. Genes shape environments; environments shape gene expression.', 3),
    mc('What does epigenetics add to the nature/nurture debate?', ['Genes are fixed at conception; epigenetics is irrelevant', 'Environmental experiences can physically alter which genes are expressed without changing DNA sequence — demonstrating that nature and nurture are biologically inseparable', 'Epigenetics shows that environment is more important than genes', 'Only physical (not psychological) traits are affected by epigenetics'], 'Environmental experiences can physically alter which genes are expressed without changing DNA sequence — demonstrating that nature and nurture are biologically inseparable', 'Early trauma methylates stress-response genes; enriched environments affect brain gene expression; even diet affects epigenetic marks. These changes can sometimes pass to offspring — showing how environment gets "under the skin."', 4),
    mc('What is the current scientific consensus on nature vs. nurture?', ['Nature is primary for most traits; nurture affects only minor characteristics', 'The dichotomy is false — genes and environments continuously interact; the real question is how they work together to produce outcomes', 'Nurture is primary; genetic influences are minimal', 'The debate remains unresolved with no scientific consensus'], 'The dichotomy is false — genes and environments continuously interact; the real question is how they work together to produce outcomes', 'Modern behavioral genetics, epigenetics, and developmental psychology all point to the same conclusion: genes and environments are intertwined. Asking "how much is nature vs. nurture?" is like asking how much of a rectangle\'s area is due to its length vs. width.', 5),
  ],
  'prenatal-and-infant': [
    mc('What is a teratogen?', ['A genetic mutation affecting fetal development', 'An environmental agent (alcohol, drugs, radiation, infections) that can damage fetal development during sensitive periods', 'A prenatal hormone affecting personality development', 'A test for genetic abnormalities during pregnancy'], 'An environmental agent (alcohol, drugs, radiation, infections) that can damage fetal development during sensitive periods', 'Teratogens include: alcohol (fetal alcohol syndrome), rubella (heart defects, deafness), tobacco (low birth weight), some medications, radiation. Effects depend on timing — sensitive periods exist for each organ/system.', 1),
    mc('What sensory abilities do newborns have?', ['Newborns are essentially blind and deaf', 'Newborns have all basic senses — they can see (preferring faces and high contrast), hear (preferring mother\'s voice), taste (preferring sweet), smell, and feel pain', 'Newborns can only detect touch and pain', 'Newborns have fully developed adult sensory abilities from birth'], 'Newborns have all basic senses — they can see (preferring faces and high contrast), hear (preferring mother\'s voice), taste (preferring sweet), smell, and feel pain', 'Newborns aren\'t blank slates. They prefer their mother\'s voice (heard in utero) over other voices. They can discriminate their mother\'s smell. They prefer sweet over bitter. They can imitate facial expressions within hours of birth.', 2),
    mc('What is the social smile and when does it appear?', ['A reflexive grimace present from birth', 'A genuine, social smile appearing at approximately 6-8 weeks in response to faces and social interaction', 'The first intentional communication newborns make', 'A smile appearing only when babies are fed'], 'A genuine, social smile appearing at approximately 6-8 weeks in response to faces and social interaction', 'The neonatal smile (first weeks) is reflexive. The social smile (6-8 weeks) is responsive to social stimulation and marks the beginning of intentional social engagement. It has profound effects on caregiver behavior and bonding.', 3),
    mc('What is preferential looking in infant research?', ['The tendency of infants to look longer at their mothers', 'A research method measuring what infants notice and prefer by tracking how long they look at different stimuli', 'A clinical assessment of infant vision problems', 'The tendency of infants to look toward familiar objects'], 'A research method measuring what infants notice and prefer by tracking how long they look at different stimuli', 'Infants look longer at novel, surprising, or preferred stimuli. Habituation-dishabituation paradigm: habituate infant to one stimulus; present a new one. Increased looking to the new stimulus shows discrimination. This reveals sophisticated infant knowledge.', 4),
    mc('What is the competent infant?', ['An infant who is unusually advanced in development', 'The finding that infants are far more cognitively capable than previously believed — they have basic number sense, object permanence, and causal reasoning', 'An infant who has reached all developmental milestones early', 'A theoretical ideal used in developmental research'], 'The finding that infants are far more cognitively capable than previously believed — they have basic number sense, object permanence, and causal reasoning', 'Violation of expectation studies: infants look longer at impossible events (1+1=1 in a magic show). They expect 2. This reveals arithmetic understanding at 5-6 months. Infants are not blank slates — they come equipped with core knowledge systems.', 5),
  ],
}
