import type { ExerciseDef } from '../types'

function mc(
  question: string,
  options: string[],
  correctAnswer: string,
  explanation: string,
  order: number
): ExerciseDef {
  return { question, type: 'MULTIPLE_CHOICE', options, correctAnswer, explanation, order }
}

export const psychologyExercises2: Record<string, ExerciseDef[]> = {
  'how-senses-work': [
    mc('What is the difference between sensation and perception?', ['They are two words for the same process', 'Sensation is the raw detection of physical stimuli; perception is the brain\'s interpretation and organization of that sensory information', 'Sensation is conscious; perception is unconscious', 'Sensation involves thinking; perception is automatic'], 'Sensation is the raw detection of physical stimuli; perception is the brain\'s interpretation and organization of that sensory information', 'Your eye senses light (sensation); your brain sees a face (perception). Same stimulus, very different processes. Perception is active construction — the brain creates what you experience from incomplete sensory data.', 1),
    mc('What is an absolute threshold?', ['The maximum stimulus intensity a sense organ can detect', 'The minimum intensity of a stimulus required for detection 50% of the time', 'The point at which a stimulus becomes painful', 'The threshold at which two stimuli can be distinguished'], 'The minimum intensity of a stimulus required for detection 50% of the time', 'Absolute thresholds vary by individual and context. The human eye can detect a candle flame 30 miles away in darkness. Below threshold = undetectable; above = detectable (in 50% of trials — hence the 50% definition).', 2),
    mc('What is sensory adaptation?', ['Learning to like sensory experiences that were initially unpleasant', 'The decrease in sensitivity to a constant, unchanging stimulus — why you stop noticing a smell after being in a room a while', 'The brain\'s ability to process multiple senses simultaneously', 'Improvement in sensory acuity with practice'], 'The decrease in sensitivity to a constant, unchanging stimulus — why you stop noticing a smell after being in a room a while', 'Sensory adaptation focuses attention on changes in the environment (which are informative) rather than constant stimuli (which provide no new information). You habituate to your glasses, background noise, and familiar smells.', 3),
    mc('What is transduction in sensory processing?', ['Converting perception into conscious experience', 'Converting physical energy (light, sound, pressure) into neural signals the brain can process', 'The transfer of sensory information between brain hemispheres', 'The brain\'s adaptation to constant stimulation'], 'Converting physical energy (light, sound, pressure) into neural signals the brain can process', 'Transduction happens at sensory receptors: rods and cones convert light to electrical signals; hair cells in the ear convert sound waves; skin receptors convert pressure — all into the common language of neural impulses.', 4),
    mc('What is the gate-control theory of pain?', ['Pain signals are controlled by a single brain region', 'A model proposing that neural "gates" in the spinal cord can either open (amplify pain signals) or close (reduce them) based on factors like touch and mental state', 'Pain is entirely psychological — all pain can be stopped by willpower', 'Pain is always proportional to physical tissue damage'], 'A model proposing that neural "gates" in the spinal cord can either open (amplify pain signals) or close (reduce them) based on factors like touch and mental state', 'Gate-control explains why rubbing an injury helps, why distraction reduces pain, and why anxiety amplifies it. The gate can be opened (stress) or closed (endorphins, touch, attention elsewhere).', 5),
  ],
  'perception-vs-reality': [
    mc('What do perceptual illusions demonstrate?', ['That our senses are fundamentally unreliable', 'That perception is an active construction — the brain makes assumptions and fills in gaps that can lead to systematic misperception', 'That only visual perception can be fooled', 'That illusions only affect unintelligent people'], 'That perception is an active construction — the brain makes assumptions and fills in gaps that can lead to systematic misperception', 'Illusions reveal the rules the brain uses to construct reality — assumptions about light direction, object size, color constancy. These shortcuts usually work but can be fooled when conditions are designed to exploit them.', 1),
    mc('What is perceptual set?', ['The complete set of perceptions an individual has', 'A mental predisposition to perceive things in a certain way based on expectations, context, and prior experience', 'The arrangement of visual elements in the field of view', 'The maximum number of stimuli that can be perceived simultaneously'], 'A mental predisposition to perceive things in a certain way based on expectations, context, and prior experience', 'You see what you expect to see. Classic demonstration: the same figure looks like a rabbit or a duck depending on context. "The cat sat on the mat" — you read "the" correctly even when it appears twice ("the the cat").', 2),
    mc('What is figure-ground perception?', ['The brain\'s ability to perceive three-dimensional objects', 'The perceptual tendency to organize visual information into a figure (focal object) against a background', 'The ability to perceive objects at different distances', 'Color perception against differently colored backgrounds'], 'The perceptual tendency to organize visual information into a figure (focal object) against a background', 'Figure-ground: the vase-or-faces illusion shows how the brain alternates which region is figure and which is ground. We can\'t see both simultaneously — the brain constantly organizes perception into objects vs. background.', 3),
    mc('What is depth perception and how is it achieved?', ['The ability to see in darkness', 'The ability to see the world in three dimensions — using monocular cues (perspective, shading) and binocular cues (the slightly different views each eye receives)', 'The ability to track moving objects accurately', 'Perception of the distance of sounds'], 'The ability to see the world in three dimensions — using monocular cues (perspective, shading) and binocular cues (the slightly different views each eye receives)', 'Binocular disparity (retinal disparity) — the slight difference between what each eye sees — is the most powerful depth cue. This is how 3D films work: two slightly different images, one for each eye.', 4),
    mc('What is perceptual constancy?', ['The tendency to see what we expect to see', 'The perception of objects as stable in size, shape, and color despite changing sensory information as viewing conditions change', 'Consistency in sensory thresholds over time', 'The brain\'s consistency in categorizing similar objects'], 'The perception of objects as stable in size, shape, and color despite changing sensory information as viewing conditions change', 'A door is perceived as rectangular even when seen at an angle (shape constancy). A person walking away is perceived as the same size even as their retinal image shrinks (size constancy). The brain compensates for changing inputs.', 5),
  ],
  'attention': [
    mc('What is selective attention?', ['The ability to pay attention to multiple things simultaneously', 'The ability to focus on one stimulus while filtering out competing stimuli — focusing cognitive resources on what\'s most relevant', 'Attention that selectively improves with practice', 'The brain\'s automatic attention to dangerous stimuli'], 'The ability to focus on one stimulus while filtering out competing stimuli — focusing cognitive resources on what\'s most relevant', 'The "cocktail party effect": you can tune out background noise and focus on one conversation — but your name instantly captures attention because the brain continuously monitors even filtered information for self-relevant signals.', 1),
    mc('What is inattentional blindness?', ['Inability to see due to neurological damage', 'Failing to notice visible objects or events when attention is focused elsewhere — the "invisible gorilla" phenomenon', 'Visual impairment caused by focused attention', 'The tendency to miss visual details at the edges of vision'], 'Failing to notice visible objects or events when attention is focused elsewhere — the "invisible gorilla" phenomenon', 'Simons and Chabris\' gorilla study: people watching a ball-passing game were so focused on counting passes that half didn\'t notice a person in a gorilla suit walking through the scene. We don\'t see what we don\'t attend to.', 2),
    mc('What does research on multitasking show?', ['Humans can effectively multitask with practice', 'True simultaneous multitasking for complex tasks is largely a myth — we rapidly switch between tasks rather than doing them simultaneously, with performance costs', 'Only certain people can multitask effectively', 'Multitasking improves with age and experience'], 'True simultaneous multitasking for complex tasks is largely a myth — we rapidly switch between tasks rather than doing them simultaneously, with performance costs', 'The brain switches rather than truly multitasks. Each switch incurs a cost: time, errors, reduced depth of processing. Talking on a phone while driving (even hands-free) impairs driving to the equivalent of legal intoxication.', 3),
    mc('What is the spotlight metaphor for attention?', ['Attention illuminates the entire visual field equally', 'Attention works like a spotlight — whatever is in the spotlight is processed fully; what\'s outside is processed shallowly or not at all', 'Attention shifts to new stimuli automatically and uncontrollably', 'The visual field is processed in order from center to periphery'], 'Attention works like a spotlight — whatever is in the spotlight is processed fully; what\'s outside is processed shallowly or not at all', 'The spotlight can be narrow (focused, intense) or broad (distributed, less intense). We can direct it voluntarily or it can be captured by salient stimuli (sudden movement, loud noise, our name).', 4),
    mc('What is the difference between top-down and bottom-up attention?', ['Top-down attention is more conscious than bottom-up', 'Top-down attention is guided by goals and expectations; bottom-up attention is captured by salient sensory features (sudden movement, bright colors, loud sounds)', 'Top-down is voluntary; bottom-up is always involuntary and cannot be resisted', 'Bottom-up attention is faster and more accurate than top-down'], 'Top-down attention is guided by goals and expectations; bottom-up attention is captured by salient sensory features (sudden movement, bright colors, loud sounds)', 'Looking for your keys (top-down — goal-directed). Your phone suddenly lighting up grabs your attention (bottom-up — stimulus-driven). Both systems work together, with either able to capture attentional resources.', 5),
  ],
  'how-memory-works': [
    mc('What are the three stages of memory processing?', ['Thinking, storing, and remembering', 'Encoding (getting information in), storage (maintaining it), and retrieval (getting it out)', 'Sensory, working, and permanent memory', 'Attention, consolidation, and recall'], 'Encoding (getting information in), storage (maintaining it), and retrieval (getting it out)', 'Memory fails at any stage: poor encoding (not paying attention), storage loss (decay, interference), or retrieval failure (tip-of-tongue — the memory exists but can\'t be accessed). Understanding which stage fails guides improvement.', 1),
    mc('What is the difference between working memory and long-term memory?', ['Working memory stores information permanently', 'Working memory temporarily holds and manipulates information currently in use; long-term memory stores information for extended periods — potentially permanently', 'Long-term memory is less reliable than working memory', 'They are different names for the same type of memory'], 'Working memory temporarily holds and manipulates information currently in use; long-term memory stores information for extended periods — potentially permanently', 'Working memory (formerly "short-term memory") has limited capacity (~4 chunks) and duration (~20 seconds without rehearsal). Long-term memory has essentially unlimited capacity but requires effective encoding to store.', 2),
    mc('What is the difference between explicit and implicit memory?', ['Explicit memory is more accurate', 'Explicit memory involves conscious recall (facts, events); implicit memory involves unconscious influence on behavior (skills, habits, priming)', 'Implicit memory is stored in the hippocampus; explicit is in the amygdala', 'Only explicit memory is affected by brain damage'], 'Explicit memory involves conscious recall (facts, events); implicit memory involves unconscious influence on behavior (skills, habits, priming)', 'Explicit (declarative) memory: knowing what Paris is the capital of France. Implicit (procedural) memory: knowing how to ride a bike. Patient H.M. lost explicit memory but could still learn new motor skills — different systems.', 3),
    mc('What is elaborative encoding?', ['Repeating information many times to memorize it', 'Connecting new information to existing knowledge and meaning — creating rich associations that make memories easier to store and retrieve', 'Breaking long information into smaller chunks', 'Recording information in multiple sensory formats'], 'Connecting new information to existing knowledge and meaning — creating rich associations that make memories easier to store and retrieve', 'Shallow encoding (repeating words) produces weaker memories than deep encoding (thinking about meaning and connections). The more associations, the more retrieval routes — and the harder information is to forget.', 4),
    mc('What is the spacing effect?', ['The tendency to remember information at the beginning and end of a list', 'Learning is more durable when study is spread across sessions over time rather than massed in one sitting (cramming)', 'The gap between encoding and retrieval determines what is remembered', 'Memories fade at a predictable rate over time'], 'Learning is more durable when study is spread across sessions over time rather than massed in one sitting (cramming)', 'Spaced practice dramatically outperforms massed practice (cramming) for long-term retention. Each study session serves as a retrieval practice that strengthens the memory trace. Cramming works for tomorrow\'s exam; spacing works for permanent learning.', 5),
  ],
  'memory-failures': [
    mc('What is the forgetting curve?', ['The rate at which memories deteriorate with age', 'Ebbinghaus\'s finding that memory declines rapidly initially then levels off — most forgetting happens soon after learning', 'A graph of memory errors across the lifespan', 'The gradual improvement in memory with practice'], 'Ebbinghaus\'s finding that memory declines rapidly initially then levels off — most forgetting happens soon after learning', 'Ebbinghaus (1885): without review, we forget ~50% within an hour, ~75% within a day. The curve levels off — what remains after a day tends to be more durable. Spaced review dramatically flattens this curve.', 1),
    mc('What is retroactive interference?', ['Old memories interfering with learning new information', 'New learning interfering with memory for previously learned information', 'The inability to form new memories', 'Memory errors caused by retrieving related information'], 'New learning interfering with memory for previously learned information', 'Retroactive (backward-acting) interference: new learning disrupts old memories. Learning Spanish interferes with French vocabulary you studied earlier. Proactive (forward-acting) interference: old learning disrupts new learning.', 2),
    mc('What are false memories?', ['Memories that are completely fabricated with no basis in reality', 'Vivid, confident memories of events that didn\'t happen or occurred differently — memories constructed and distorted rather than accurately recorded', 'Memories that exist but can\'t be retrieved', 'Memories formed under the influence of drugs or alcohol'], 'Vivid, confident memories of events that didn\'t happen or occurred differently — memories constructed and distorted rather than accurately recorded', 'Elizabeth Loftus\'s research demonstrated that false memories can be implanted through leading questions and suggestions. People vividly "remember" events that never happened — memory is reconstructive, not recording.', 3),
    mc('What is source monitoring error?', ['Forgetting where you put something', 'Misattributing where a memory came from — confusing whether you actually experienced something vs. imagined, heard, or dreamed it', 'Remembering information but forgetting its source citation', 'The tendency to attribute memories to the wrong person'], 'Misattributing where a memory came from — confusing whether you actually experienced something vs. imagined, heard, or dreamed it', 'Cryptomnesia (inadvertent plagiarism) is source monitoring failure — you remember the idea but forget you got it from someone else. Eyewitness errors often involve source confusion: seeing a photo later and "remembering" the face from the crime scene.', 4),
    mc('What is the misinformation effect?', ['The tendency to remember accurate information incorrectly', 'When post-event information (misleading questions, news coverage) alters memory for the original event', 'The tendency to forget incorrect information faster than correct information', 'Memory loss caused by emotional trauma'], 'When post-event information (misleading questions, news coverage) alters memory for the original event', 'Loftus\'s classic study: participants who were asked "How fast were the cars going when they smashed into each other?" remembered the accident as faster and reported seeing broken glass (there was none) compared to those asked "hit."', 5),
  ],
  'thinking-and-problem-solving': [
    mc('What is a mental set?', ['A person\'s natural cognitive style', 'The tendency to keep using solutions that worked in the past — which can blind you to better approaches in new situations', 'A plan for solving a complex problem', 'A fixed way of categorizing information'], 'The tendency to keep using solutions that worked in the past — which can blind you to better approaches in new situations', 'Mental set is useful when old solutions still work but counterproductive when new situations require new approaches. The Einstellung effect: fixating on familiar approaches prevents finding better solutions.', 1),
    mc('What is functional fixedness?', ['The inability to function when a problem has no solution', 'Seeing objects only in their familiar functions — inability to think of using them in novel ways to solve problems', 'The tendency to approach all problems with the same method', 'Emotional fixation on a desired outcome regardless of feasibility'], 'Seeing objects only in their familiar functions — inability to think of using them in novel ways to solve problems', 'Classic demonstration: the candle problem — participants can\'t see that a box of tacks can serve as a candle holder (not just a tack container). Functional fixedness prevents creative problem-solving.', 2),
    mc('What is an algorithm vs. a heuristic?', ['Algorithms are faster; heuristics are more accurate', 'An algorithm is a step-by-step procedure guaranteeing a solution; a heuristic is a mental shortcut that usually works but can lead to errors', 'Heuristics are only used by beginners; algorithms by experts', 'They are different words for the same cognitive strategy'], 'An algorithm is a step-by-step procedure guaranteeing a solution; a heuristic is a mental shortcut that usually works but can lead to errors', 'Algorithms always work but are time-consuming (checking every possible chess move). Heuristics are efficient but fallible (choosing the first available parking spot rather than finding the closest one). Most thinking uses heuristics.', 3),
    mc('What is the availability heuristic?', ['Choosing solutions that are most easily available', 'Judging the probability of events based on how easily examples come to mind — leading to systematic overestimates of dramatic, memorable events', 'Using the most recently learned strategy for new problems', 'Trusting information that is immediately available rather than searching for more'], 'Judging the probability of events based on how easily examples come to mind — leading to systematic overestimates of dramatic, memorable events', 'After a plane crash, people overestimate flight risk. Shark attacks get more fear than car accidents despite car accidents being far more deadly. Dramatic events are more memorable — their memorability inflates perceived probability.', 4),
    mc('What is insight in problem-solving?', ['Gradually working toward a solution through trial and error', 'A sudden "aha!" moment when a problem\'s solution appears all at once — often after a period of incubation', 'A systematic analysis of all possible solutions', 'A feeling of confidence that you\'ve found the right answer'], 'A sudden "aha!" moment when a problem\'s solution appears all at once — often after a period of incubation', 'Insight (the "aha" or "eureka" experience) involves sudden restructuring of the problem representation. The incubation effect suggests that stepping away from a problem allows unconscious processing — often producing sudden insight.', 5),
  ],
  'language-and-thought': [
    mc('What is the Sapir-Whorf hypothesis (linguistic relativity)?', ['Language is universal and doesn\'t affect thought', 'Language shapes thought — the language you speak influences how you perceive and think about the world', 'Thought is only possible with language', 'All languages have identical cognitive effects on their speakers'], 'Language shapes thought — the language you speak influences how you perceive and think about the world', 'Weak version (linguistic relativity): language influences thought. Strong version (linguistic determinism): language determines thought. Research supports the weak version: color vocabulary affects color discrimination; grammatical gender affects object perception.', 1),
    mc('What are the core properties of human language?', ['Fixed signals with predetermined meanings, unlike animal communication', 'Generativity (infinite sentences from finite elements), displacement (discussing things not present), and symbolic representation', 'Only spoken communication — no written component', 'Communication limited to present, observable events'], 'Generativity (infinite sentences from finite elements), displacement (discussing things not present), and symbolic representation', 'Human language is unique in its generativity (we produce and understand sentences we\'ve never heard), displacement (we can discuss yesterday, next year, and imaginary events), and arbitrary symbols (no inherent connection between words and referents).', 2),
    mc('What is the critical period for language acquisition?', ['The first week of life when language imprinting occurs', 'The period in early childhood (birth to roughly puberty) during which language is most easily learned naturally and completely', 'The age of 7-10 when formal education begins', 'There is no critical period — language can be learned equally well at any age'], 'The period in early childhood (birth to roughly puberty) during which language is most easily learned naturally and completely', 'Children exposed to language in the critical period acquire it naturally and completely. Genie (discovered at 13, having been deprived of language) never fully mastered grammar despite years of instruction — evidence for the critical period.', 3),
    mc('How does bilingualism affect cognition?', ['Bilingualism confuses children and slows language development', 'Bilingualism provides cognitive benefits including enhanced executive function, better attention control, and possible delayed onset of dementia', 'There are no cognitive effects of bilingualism', 'Bilingualism benefits are only apparent in languages that are very similar'], 'Bilingualism provides cognitive benefits including enhanced executive function, better attention control, and possible delayed onset of dementia', 'Managing two language systems exercises the executive control system. Bilingual children may show slight delays in each language\'s vocabulary (normal — they\'re learning two) but advantages in tasks requiring attention, task-switching, and inhibiting distracting information.', 4),
    mc('Can thought occur without language?', ['No — all thought requires language', 'Yes — much thinking is non-verbal (spatial reasoning, musical thought, emotional processing), and preverbal infants demonstrate sophisticated cognition', 'Only in primitive, simple forms', 'Only for people who have never learned language'], 'Yes — much thinking is non-verbal (spatial reasoning, musical thought, emotional processing), and preverbal infants demonstrate sophisticated cognition', 'Infants demonstrate object permanence, number sense, and causal reasoning before they have language. Einstein described his thinking as involving visual-spatial images rather than words. Language and thought are related but not identical.', 5),
  ],
}
