import type { ExerciseDef } from '../types'

function mc(
  question: string,
  options: string[],
  correctAnswer: string,
  explanation: string,
  order: number
): ExerciseDef {
  return { question, type: 'MULTIPLE_CHOICE', options, correctAnswer, explanation, order }
}

export const psychologyExercises1: Record<string, ExerciseDef[]> = {
  'what-is-psychology': [
    mc('What is psychology?', ['The study of the brain\'s physical structure', 'The scientific study of behavior and mental processes — thoughts, feelings, perceptions, and actions', 'The study of mental illness exclusively', 'A branch of philosophy with no scientific component'], 'The scientific study of behavior and mental processes — thoughts, feelings, perceptions, and actions', 'Psychology uses scientific methods to understand why people think, feel, and behave as they do — covering everything from sensation and perception to personality, development, and mental health.', 1),
    mc('What distinguishes psychology from common sense?', ['Psychology confirms what most people already know', 'Psychology tests intuitions rigorously — many "obvious" beliefs about human behavior turn out to be wrong when studied carefully', 'Psychology only studies rare, unusual behavior', 'Common sense is more accurate because it\'s based on real experience'], 'Psychology tests intuitions rigorously — many "obvious" beliefs about human behavior turn out to be wrong when studied carefully', 'Hindsight bias makes psychological findings seem obvious after the fact. But research consistently overturns common-sense beliefs: stress doesn\'t always hurt performance, punishment is less effective than reinforcement, and so on.', 2),
    mc('What is the biopsychosocial model?', ['A model treating only biological causes of mental illness', 'A framework understanding behavior and mental health as influenced by biological, psychological, and social factors together', 'A three-stage model of psychological development', 'A model separating psychological from social influences'], 'A framework understanding behavior and mental health as influenced by biological, psychological, and social factors together', 'The biopsychosocial model rejects single-cause explanations. Depression isn\'t only genetic (biological) or only about negative thinking (psychological) or only about life circumstances (social) — it\'s the interaction of all three.', 3),
    mc('What is the nature vs. nurture debate in psychology?', ['Whether people are naturally good or bad', 'The question of how much behavior is determined by genetics and biology (nature) vs. environment and experience (nurture)', 'Whether psychological traits are fixed or changeable', 'Whether intelligence is real or socially constructed'], 'The question of how much behavior is determined by genetics and biology (nature) vs. environment and experience (nurture)', 'Modern psychology recognizes that nature and nurture interact — genes express differently in different environments (epigenetics), and environments shape which genetic predispositions emerge. It\'s not either/or but how they interact.', 4),
    mc('What are some common subfields of psychology?', ['Surgery, therapy, and medication', 'Clinical, developmental, social, cognitive, neuroscience, personality, industrial-organizational, and educational psychology', 'Depression, anxiety, and trauma treatment', 'Only two: experimental and applied psychology'], 'Clinical, developmental, social, cognitive, neuroscience, personality, industrial-organizational, and educational psychology', 'Psychology is vast. Clinical psychologists treat mental illness; developmental psychologists study change across the lifespan; cognitive psychologists study thinking; social psychologists study group behavior. All use scientific methods.', 5),
  ],
  'history-of-psychology': [
    mc('Who is considered the founder of scientific psychology?', ['Sigmund Freud', 'Wilhelm Wundt, who established the first psychology laboratory in Leipzig in 1879', 'William James', 'John Watson'], 'Wilhelm Wundt, who established the first psychology laboratory in Leipzig in 1879', 'Wundt\'s lab marked the beginning of psychology as a separate scientific discipline — distinct from philosophy. He studied consciousness through introspection (systematic self-observation).', 1),
    mc('What was behaviorism?', ['A movement studying consciousness through introspection', 'A school of thought that psychology should only study observable behavior — not unobservable mental states — and that behavior is shaped by environmental conditioning', 'Freud\'s theory of unconscious motivation', 'The study of how social forces shape individual behavior'], 'A school of thought that psychology should only study observable behavior — not unobservable mental states — and that behavior is shaped by environmental conditioning', 'Watson, Pavlov, and Skinner led behaviorism. If it can\'t be observed and measured, it can\'t be studied scientifically. Behaviorism dominated American psychology from ~1920-1960 before the cognitive revolution.', 2),
    mc('What was Freudian psychoanalysis?', ['A behavioral therapy focused on changing actions', 'A theory and therapy focusing on unconscious drives, repressed memories, and childhood experience as the roots of personality and mental illness', 'A cognitive approach to treating anxiety', 'A biological theory of mental illness'], 'A theory and therapy focusing on unconscious drives, repressed memories, and childhood experience as the roots of personality and mental illness', 'Freud proposed that unconscious conflicts (especially sexual and aggressive drives) shape personality and cause mental illness. Psychoanalytic therapy brings unconscious material to conscious awareness through free association and dream analysis.', 3),
    mc('What was the cognitive revolution in psychology?', ['A return to behaviorist principles', 'A shift in the 1950s-60s away from behaviorism, reinstating the scientific study of mental processes like memory, attention, language, and reasoning', 'A movement toward biological explanations of all behavior', 'The introduction of brain scanning technology'], 'A shift in the 1950s-60s away from behaviorism, reinstating the scientific study of mental processes like memory, attention, language, and reasoning', 'Chomsky\'s critique of Skinner, computer science\'s models of information processing, and new research on memory and attention drove the cognitive revolution — making mental processes legitimate scientific subjects again.', 4),
    mc('What is humanistic psychology?', ['A movement studying evolutionary roots of behavior', 'A perspective emphasizing human potential, growth, free will, and the subjective experience of individuals — reacting against behaviorism and psychoanalysis', 'The study of group behavior and social norms', 'A biological approach to understanding personality'], 'A perspective emphasizing human potential, growth, free will, and the subjective experience of individuals — reacting against behaviorism and psychoanalysis', 'Maslow and Rogers led humanism in the 1950s-60s: people are not just conditioned robots (behaviorism) or driven by dark unconscious forces (Freud) — they are meaning-seeking beings capable of growth.', 5),
  ],
  'research-methods': [
    mc('What is the difference between a correlation and an experiment?', ['Correlations are more scientifically valid', 'A correlation shows two variables are related; an experiment manipulates one variable to test if it causes changes in another — only experiments can establish causation', 'Experiments show correlation; correlations show causation', 'They are different names for the same method'], 'A correlation shows two variables are related; an experiment manipulates one variable to test if it causes changes in another — only experiments can establish causation', 'Ice cream sales correlate with drowning — but ice cream doesn\'t cause drowning (summer causes both). Only experiments with random assignment can isolate causation.', 1),
    mc('What is a double-blind study?', ['A study with two experimental conditions', 'A study where neither participants nor researchers know who is in the experimental vs. control group — controlling for placebo effects and experimenter bias', 'A study using two different research methods', 'A study with two independent variables'], 'A study where neither participants nor researchers know who is in the experimental vs. control group — controlling for placebo effects and experimenter bias', 'Single-blind: participants don\'t know. Double-blind: neither participants nor the researchers interacting with them know. This eliminates both placebo effects and researcher expectations from influencing results.', 2),
    mc('What is random sampling?', ['Selecting research participants who volunteer', 'Selecting participants randomly from the population of interest so the sample is representative and findings can generalize', 'Randomly assigning participants to conditions in an experiment', 'Selecting participants based on their characteristics'], 'Selecting participants randomly from the population of interest so the sample is representative and findings can generalize', 'Random sampling (selecting who participates) differs from random assignment (which condition participants are in). Representative samples allow generalization; convenience samples (college students) limit it.', 3),
    mc('What is a survey method?', ['Watching and recording behavior in natural settings', 'Collecting self-reported data through questionnaires — efficient for large samples but limited by social desirability bias and memory errors', 'A structured interview conducted by a researcher', 'A method for studying animals\' behavior patterns'], 'Collecting self-reported data through questionnaires — efficient for large samples but limited by social desirability bias and memory errors', 'Surveys can reach many people cheaply but depend on honest, accurate self-report. People often misremember, misreport what they actually did, and give socially acceptable rather than honest answers.', 4),
    mc('What is a case study?', ['A study with many participants and one variable', 'An in-depth investigation of a single individual, group, or event — providing rich data but difficult to generalize from', 'A laboratory experiment with carefully controlled conditions', 'A study comparing two different populations'], 'An in-depth investigation of a single individual, group, or event — providing rich data but difficult to generalize from', 'Phineas Gage (brain damage and personality change) and H.M. (severe amnesia after hippocampus removal) are famous case studies that generated fundamental neuroscientific insights. Single cases can\'t be generalized but generate important hypotheses.', 5),
  ],
  'major-perspectives': [
    mc('What does the biological perspective in psychology emphasize?', ['Social learning and environmental influences', 'How genetics, brain chemistry, hormones, and the nervous system influence behavior and mental processes', 'The role of unconscious conflicts in behavior', 'How cultural context shapes psychological experience'], 'How genetics, brain chemistry, hormones, and the nervous system influence behavior and mental processes', 'The biological perspective looks to brain structure, neurotransmitters, genetics, and evolution to explain behavior. Depression has a neurochemical basis; schizophrenia has a genetic component; aggression is influenced by testosterone.', 1),
    mc('What does the cognitive perspective study?', ['Observable behavior only', 'How mental processes — thinking, perception, memory, language, reasoning — influence behavior', 'The unconscious drivers of motivation', 'How social context shapes individual thinking'], 'How mental processes — thinking, perception, memory, language, reasoning — influence behavior', 'Cognitive psychology asks how we perceive, attend to, remember, and reason about information. Cognitive therapy focuses on changing distorted thought patterns that contribute to emotional problems.', 2),
    mc('What does the sociocultural perspective examine?', ['How individual biology affects social behavior', 'How cultural context, social norms, and interpersonal relationships shape behavior and mental processes', 'How childhood experiences cause adult problems', 'The evolutionary origins of social behavior'], 'How cultural context, social norms, and interpersonal relationships shape behavior and mental processes', 'What counts as normal behavior, what emotions are appropriate to express, how relationships should work — all vary enormously by culture. The sociocultural perspective corrects for psychology\'s historical overreliance on Western, educated, industrialized, rich, democratic (WEIRD) samples.', 3),
    mc('What does the evolutionary perspective propose?', ['Behavior is entirely determined by genetics', 'Human behavior and mental processes can be understood as adaptations that evolved to help ancestors survive and reproduce', 'Modern humans no longer exhibit evolved behaviors', 'Evolution explains all behavior regardless of cultural context'], 'Human behavior and mental processes can be understood as adaptations that evolved to help ancestors survive and reproduce', 'Fear of snakes, preference for symmetrical faces, in-group favoritism, and sex differences in mate preferences are studied through an evolutionary lens — asking what adaptive function these tendencies may have served.', 4),
    mc('What is eclectic psychology?', ['A theory combining all psychological perspectives into one', 'A practical approach drawing on multiple theoretical perspectives based on what best explains and addresses a particular person\'s situation', 'A rejection of all established psychological theories', 'A perspective focusing only on cultural factors'], 'A practical approach drawing on multiple theoretical perspectives based on what best explains and addresses a particular person\'s situation', 'Most modern practitioners are eclectic — they don\'t rigidly apply one perspective. A depressed client might benefit from cognitive (thought patterns), biological (medication), and social (support systems) approaches together.', 5),
  ],
  'neurons-and-the-brain': [
    mc('What is a neuron?', ['A brain region specialized for specific functions', 'A specialized cell that transmits information through electrical and chemical signals — the basic unit of the nervous system', 'The protective covering of the brain', 'A brain wave pattern measured by EEG'], 'A specialized cell that transmits information through electrical and chemical signals — the basic unit of the nervous system', 'The brain contains ~86 billion neurons. Each neuron has dendrites (receiving signals), a cell body (processing), and an axon (sending signals to other neurons). Communication happens at synapses.', 1),
    mc('What are neurotransmitters?', ['Electrical signals within neurons', 'Chemical messengers that transmit signals across synapses from one neuron to another', 'Proteins that form the structure of neurons', 'Hormones produced by the endocrine system'], 'Chemical messengers that transmit signals across synapses from one neuron to another', 'Neurotransmitters include: serotonin (mood, sleep), dopamine (reward, motivation), norepinephrine (arousal, attention), GABA (inhibition), glutamate (excitation). Many drugs work by altering neurotransmitter systems.', 2),
    mc('What is neuroplasticity?', ['The brain\'s rigid, fixed structure after childhood', 'The brain\'s ability to reorganize itself by forming new neural connections — throughout life, in response to learning and experience', 'A surgical procedure for treating brain injuries', 'The process by which neurons die as we age'], 'The brain\'s ability to reorganize itself by forming new neural connections — throughout life, in response to learning and experience', 'Neuroplasticity means the brain physically changes with learning. London taxi drivers develop larger hippocampi (navigation area). Stroke patients can relearn functions through intensive therapy as other brain areas compensate.', 3),
    mc('What is the difference between the central and peripheral nervous systems?', ['They are two names for the same system', 'The central nervous system (brain and spinal cord) processes information; the peripheral nervous system connects the CNS to the rest of the body', 'The peripheral nervous system controls conscious thought; the central controls automatic functions', 'The central nervous system is voluntary; the peripheral is involuntary'], 'The central nervous system (brain and spinal cord) processes information; the peripheral nervous system connects the CNS to the rest of the body', 'CNS = brain + spinal cord — the command center. PNS = all other nerves — sensory nerves bring information in; motor nerves carry commands out. The autonomic nervous system (a PNS division) controls involuntary functions.', 4),
    mc('What is the action potential?', ['A brain wave measured during activity', 'The electrical signal that travels down an axon when a neuron fires — the "message" being sent from one neuron to the next', 'The threshold of stimulation needed to trigger a response', 'The resting state of a neuron between firings'], 'The electrical signal that travels down an axon when a neuron fires — the "message" being sent from one neuron to the next', 'The action potential is all-or-nothing — either the threshold is reached and the neuron fires fully, or it doesn\'t fire at all. The signal travels down the axon to release neurotransmitters at the synapse.', 5),
  ],
  'brain-structure-and-function': [
    mc('What does the prefrontal cortex do?', ['Control basic survival functions like breathing', 'Handle executive functions — planning, decision-making, impulse control, and personality expression', 'Process visual information from the eyes', 'Coordinate movement and balance'], 'Handle executive functions — planning, decision-making, impulse control, and personality expression', 'The prefrontal cortex (PFC) is the "CEO" of the brain — last to fully develop (mid-20s). Damage causes personality changes and poor impulse control. Phineas Gage\'s PFC damage transformed him from reliable to impulsive and profane.', 1),
    mc('What is the amygdala\'s primary function?', ['Language production and comprehension', 'Processing emotions — especially fear and threat detection; the "alarm system" of the brain', 'Coordinating voluntary muscle movement', 'Consolidating long-term memories'], 'Processing emotions — especially fear and threat detection; the "alarm system" of the brain', 'The amygdala rapidly evaluates stimuli for threat and triggers fear responses. It can hijack rational processing (amygdala hijack) — why people act irrationally when extremely frightened or angry.', 2),
    mc('What role does the hippocampus play?', ['Regulating heart rate and breathing', 'Forming new explicit (declarative) memories — critical for learning and remembering facts and events', 'Processing auditory information from the ears', 'Controlling hormone release throughout the body'], 'Forming new explicit (declarative) memories — critical for learning and remembering facts and events', 'Patient H.M., whose hippocampus was removed to treat epilepsy, could no longer form new long-term memories. He remembered who he was before surgery but couldn\'t remember anything new after — demonstrating the hippocampus\'s role.', 3),
    mc('What does the cerebellum control?', ['Conscious emotional responses', 'Coordination, balance, and fine motor control — the "little brain" under the cortex', 'Language processing and production', 'Long-term memory storage'], 'Coordination, balance, and fine motor control — the "little brain" under the cortex', 'The cerebellum coordinates smooth movement and balance. Alcohol impairs the cerebellum — causing the stumbling, coordination loss of intoxication. It also plays roles in some cognitive functions.', 4),
    mc('What is the corpus callosum?', ['The outer layer of the brain responsible for higher cognition', 'A bundle of nerve fibers connecting the left and right hemispheres, allowing them to communicate', 'The region controlling emotional responses', 'The structure regulating sleep and wakefulness'], 'A bundle of nerve fibers connecting the left and right hemispheres, allowing them to communicate', 'Split-brain patients (corpus callosum severed to treat epilepsy) revealed how the two hemispheres can operate independently. The left hemisphere typically handles language; the right handles spatial tasks.', 5),
  ],
  'genetics-and-behavior': [
    mc('What do twin studies reveal about the influence of genetics on behavior?', ['Identical twins are always psychologically identical', 'By comparing identical twins (100% shared genes) to fraternal twins (50% shared), researchers estimate how much variation in a trait is due to genetics', 'Genetics has no influence on psychological traits', 'All behavioral differences between twins are environmental'], 'By comparing identical twins (100% shared genes) to fraternal twins (50% shared), researchers estimate how much variation in a trait is due to genetics', 'Identical twins raised apart are more similar than fraternal twins raised together for many traits — suggesting genetic influence. But twins raised apart are never 100% identical — environment also shapes traits.', 1),
    mc('What is heritability?', ['The percentage of a trait determined by genetics', 'A statistical estimate of how much of the variation in a trait within a population is attributable to genetic differences — NOT how much of the trait is genetic', 'Whether a trait is passed from parent to child', 'The probability of inheriting a specific gene variant'], 'A statistical estimate of how much of the variation in a trait within a population is attributable to genetic differences — NOT how much of the trait is genetic', 'Heritability is often misunderstood. 50% heritability for intelligence doesn\'t mean 50% of your intelligence is genetic — it means 50% of the variation between people in that population is explained by genetic differences.', 2),
    mc('What is epigenetics?', ['The study of all genes in an organism', 'How environmental experiences can activate or silence genes without changing the DNA sequence itself', 'The genetic basis of personality disorders', 'A method for predicting traits from DNA sequences'], 'How environmental experiences can activate or silence genes without changing the DNA sequence itself', 'Epigenetics shows nature and nurture are intertwined at the molecular level. Childhood trauma can methylate genes affecting stress response. Diet, stress, and exercise can turn genes on or off — affecting even future generations.', 3),
    mc('What does the diathesis-stress model suggest?', ['Mental illness is caused entirely by genetic vulnerability', 'A genetic predisposition (diathesis) + sufficient environmental stress may trigger mental illness — neither alone necessarily causes it', 'Stress causes all mental illness regardless of genetics', 'People without genetic risk cannot develop mental illness'], 'A genetic predisposition (diathesis) + sufficient environmental stress may trigger mental illness — neither alone necessarily causes it', 'Some people have genetic vulnerability (diathesis) to depression or schizophrenia. Whether it develops depends on environmental stress. High stress + high genetic risk = higher likelihood. Low stress + high risk = may never develop.', 4),
    mc('What do adoption studies examine?', ['How adoptive families affect IQ scores', 'Whether adopted children\'s traits more closely resemble their biological or adoptive parents — helping separate genetic from environmental influence', 'The psychological effects of adoption on children', 'Genetic similarities between adoptive and biological children'], 'Whether adopted children\'s traits more closely resemble their biological or adoptive parents — helping separate genetic from environmental influence', 'If a trait is genetic, adopted children should resemble biological parents more than adoptive parents. If environmental, they should resemble adoptive parents. Research shows complex combinations for most traits.', 5),
  ],
}
