import type { AssessmentDef, AssessmentQuestionDef } from '../types'

const mc = (q: string, opts: string[], ans: string, exp: string, pts: number, ord: number): AssessmentQuestionDef =>
  ({ question: q, type: 'MULTIPLE_CHOICE', options: opts, correctAnswer: ans, explanation: exp, points: pts, order: ord })
const oe = (q: string, ans: string, exp: string, pts: number, ord: number): AssessmentQuestionDef =>
  ({ question: q, type: 'OPEN_ENDED', correctAnswer: ans, explanation: exp, points: pts, order: ord })

export const sciencesAssessments: Record<string, AssessmentDef> = {
  'scientific-method': {
    title: 'Scientific Method Assessment', passingScore: 75, timeLimitMin: 25,
    questions: [
      mc('A hypothesis must be:', ['Proven correct before testing', 'Testable and falsifiable', 'Based on at least five prior experiments', 'Approved by a peer review board first'], 'Testable and falsifiable', 'A hypothesis that cannot be proven wrong is not scientific. Falsifiability — the possibility of being disproven — is what separates scientific claims from non-scientific ones.', 1, 1),
      mc('A control group in an experiment:', ['Receives the experimental treatment at double the dose', 'Is exposed to all variables simultaneously', 'Receives no treatment and serves as a baseline for comparison', 'Is the group whose results are discarded'], 'Receives no treatment and serves as a baseline for comparison', 'Without a control group, you cannot determine whether observed changes were caused by the independent variable or something else. Controls isolate the effect being studied.', 1, 2),
      mc('Peer review serves what primary purpose?', ['To make science accessible to the public', 'To allow other experts to scrutinize methodology and findings before publication', 'To assign credit to the original researcher', 'To determine research funding priorities'], 'To allow other experts to scrutinize methodology and findings before publication', 'Peer review is a quality filter. Reviewers check methodology, statistical analysis, and interpretation. It\'s imperfect but essential for maintaining scientific credibility.', 1, 3),
      mc('Correlation between two variables means:', ['One variable causes the other', 'The variables tend to change together', 'The experiment was controlled properly', 'The results are statistically significant'], 'The variables tend to change together', 'Correlation does not imply causation. Ice cream sales and drowning rates both rise in summer — they\'re correlated through a third variable (heat) but neither causes the other.', 1, 4),
      mc('Scientific consensus is best described as:', ['Universal agreement among all scientists globally', 'The position supported by the overwhelming weight of evidence and expert opinion', 'The opinion of the majority of living scientists', 'A democratic vote among researchers in a field'], 'The position supported by the overwhelming weight of evidence and expert opinion', 'Consensus reflects accumulated evidence, not a head count. It can change when new evidence demands it, but it takes more than one contrary study to overturn well-established science.', 1, 5),
      mc('Which type of variable does the researcher deliberately change?', ['Dependent variable', 'Controlled variable', 'Independent variable', 'Confounding variable'], 'Independent variable', 'The independent variable is what you manipulate. The dependent variable is what you measure in response. Controlled variables are held constant to prevent them from affecting the result.', 1, 6),
      mc('Replication in science means:', ['Copying another researcher\'s paper', 'Other researchers independently reproduce the experiment and get similar results', 'Running the same experiment multiple times in one lab', 'Publishing results in more than one journal'], 'Other researchers independently reproduce the experiment and get similar results', 'Replication by independent labs is the gold standard for establishing reliable findings. Results that can\'t be replicated are considered unreliable regardless of the original study\'s quality.', 1, 7),
      mc('An anomaly in data should be:', ['Deleted to improve the results', 'Investigated as a potential source of new understanding', 'Always treated as measurement error', 'Reported only if it supports the hypothesis'], 'Investigated as a potential source of new understanding', 'Many major scientific discoveries began as anomalies. Unexplained results shouldn\'t be hidden — they point to gaps in current understanding that are worth exploring.', 1, 8),
      oe('A student claims that students who eat breakfast score higher on tests. Describe how you would design a controlled experiment to test this claim.', 'You would randomly assign participants to two groups: one that eats breakfast (experimental) and one that does not (control). Both groups would take the same test at the same time under the same conditions. You would control for prior academic performance, sleep, and other variables. Statistical analysis would determine whether any score difference is significant or due to chance.', 'Good experimental design isolates the variable of interest. Random assignment prevents selection bias. Controlling other variables ensures that breakfast, not some other factor, explains any difference. Replication across multiple test sessions strengthens the conclusion.', 2, 9),
      oe('Explain why a single study is rarely sufficient to change scientific consensus, even if the study appears well-designed.', 'A single study may have methodological flaws not caught in peer review, a small sample size, publication bias (null results are underreported), or results specific to a narrow population. Scientific consensus requires multiple independent replications using different methods, all pointing to the same conclusion. One study can raise important questions; many consistent studies build knowledge.', 'Science is a self-correcting process. The more consequential a claim, the more evidence is required. "Extraordinary claims require extraordinary evidence" is a practical expression of this principle.', 2, 10),
    ],
  },
  'biology': {
    title: 'Biology Assessment', passingScore: 75, timeLimitMin: 30,
    questions: [
      mc('The central dogma of molecular biology describes the flow of information as:', ['Protein → RNA → DNA', 'DNA → RNA → Protein', 'RNA → DNA → Protein', 'Protein → DNA → RNA'], 'DNA → RNA → Protein', 'DNA is transcribed into messenger RNA, which is translated into protein. This one-way flow (with rare exceptions like retroviruses) governs how genetic information is expressed in all living cells.', 1, 1),
      mc('Natural selection acts on:', ['Genotype directly', 'Phenotype — observable traits', 'Individual DNA sequences', 'The species as a whole simultaneously'], 'Phenotype — observable traits', 'Natural selection favors traits that improve survival and reproduction in a given environment. It acts on the phenotype (what you can observe), which is influenced by the underlying genotype.', 1, 2),
      mc('A cell\'s powerhouse — the organelle that produces most ATP through cellular respiration — is:', ['The nucleus', 'The ribosome', 'The mitochondrion', 'The Golgi apparatus'], 'The mitochondrion', 'Mitochondria perform aerobic respiration, converting glucose and oxygen into ATP, CO₂, and water. They have their own DNA, evidence of their ancient bacterial origin (endosymbiotic theory).', 1, 3),
      mc('Meiosis differs from mitosis in that meiosis:', ['Produces genetically identical daughter cells', 'Occurs in all body cells', 'Produces four haploid cells for sexual reproduction', 'Does not involve chromosome separation'], 'Produces four haploid cells for sexual reproduction', 'Meiosis produces gametes (eggs and sperm) with half the chromosome number. Fertilization restores the diploid number. Mitosis produces identical diploid cells for growth and repair.', 1, 4),
      mc('Which of the following describes a producer in an ecosystem?', ['An organism that eats only plants', 'An organism that converts sunlight or chemical energy into organic matter', 'An organism that decomposes dead material', 'An organism at the top of the food chain'], 'An organism that converts sunlight or chemical energy into organic matter', 'Producers (plants, algae, some bacteria) form the base of food chains by fixing energy from abiotic sources. All other trophic levels depend on this primary production.', 1, 5),
      mc('A mutation that occurs in a somatic cell (body cell) but not a germline cell:', ['Can be passed to offspring', 'Affects only the individual and is not heritable', 'Changes the organism\'s genotype permanently across all cells', 'Always causes cancer'], 'Affects only the individual and is not heritable', 'Only germline mutations (in eggs and sperm) are inherited. Somatic mutations affect the individual — some are neutral, some cause cancer, and none are passed to offspring.', 1, 6),
      mc('Biodiversity is ecologically important primarily because:', ['It makes ecosystems more visually complex', 'Greater diversity increases ecosystem resilience and stability', 'More species always means more resources for humans', 'Species that look different must fill different roles'], 'Greater diversity increases ecosystem resilience and stability', 'Diverse ecosystems can recover from disturbances more effectively. When one species is lost, others can fill similar roles. Low-diversity ecosystems are more vulnerable to collapse from disease, climate shifts, or invasive species.', 1, 7),
      mc('Convergent evolution occurs when:', ['Two related species develop different traits in different environments', 'Unrelated species independently evolve similar traits due to similar selection pressures', 'A species rapidly diversifies into many new forms', 'Two species interbreed to create a hybrid'], 'Unrelated species independently evolve similar traits due to similar selection pressures', 'Dolphins and sharks have similar streamlined body shapes despite one being a mammal and the other a fish — convergent evolution. Similar environments select for similar solutions regardless of ancestry.', 1, 8),
      oe('Explain how the structure of DNA allows for both accurate replication and the possibility of mutation.', 'DNA\'s double helix uses complementary base pairing (A-T, G-C) to provide a template for accurate replication — each strand guides synthesis of an exact copy. However, errors occasionally occur when the wrong base is incorporated. Most are caught and corrected by proofreading enzymes, but some errors (mutations) persist, providing the raw material for evolution.', 'The accuracy of replication is essential for genetic inheritance, while the rare occurrence of mutations drives genetic diversity. Without accuracy, heredity breaks down. Without mutations, evolution cannot occur. The tension between the two is central to biology.', 2, 9),
      oe('Describe the relationship between photosynthesis and cellular respiration in a forest ecosystem.', 'Plants and algae use photosynthesis to convert CO₂, water, and sunlight into glucose and oxygen. Cellular respiration — in plants, animals, and decomposers — converts glucose and oxygen back into CO₂, water, and ATP energy. The two processes form a carbon and oxygen cycle: photosynthesis builds organic matter and releases O₂; respiration consumes O₂ and returns CO₂. The entire ecosystem\'s energy flows from the sun through photosynthesis.', 'These processes are complementary at the ecosystem level. Forests are net carbon sinks because photosynthesis exceeds respiration, removing CO₂ from the atmosphere. Deforestation disrupts this balance, contributing to climate change.', 2, 10),
    ],
  },
  'chemistry': {
    title: 'Chemistry Assessment', passingScore: 75, timeLimitMin: 30,
    questions: [
      mc('The atomic number of an element equals:', ['The number of neutrons in the nucleus', 'The number of protons in the nucleus', 'The atomic mass rounded to the nearest integer', 'The number of electrons in the outer shell'], 'The number of protons in the nucleus', 'The atomic number uniquely identifies an element. Changing the proton count creates a different element. Neutrons can vary (isotopes) without changing the element\'s identity.', 1, 1),
      mc('Elements in the same group (column) of the periodic table share:', ['The same number of protons', 'Similar chemical properties due to the same number of valence electrons', 'The same atomic mass', 'The same number of electron shells'], 'Similar chemical properties due to the same number of valence electrons', 'Valence electrons determine reactivity. The periodic table\'s genius is that it groups elements with similar bonding behavior — alkali metals all react violently with water, halogens all form salts with metals.', 1, 2),
      mc('An ionic bond forms when:', ['Two nonmetals share electrons equally', 'Electrons are transferred from a metal to a nonmetal, creating charged ions that attract', 'Two atoms share electrons in overlapping orbitals', 'A metal donates electrons to another metal'], 'Electrons are transferred from a metal to a nonmetal, creating charged ions that attract', 'Sodium gives one electron to chlorine: Na⁺ and Cl⁻ attract electrostatically. Ionic compounds have high melting points and conduct electricity when dissolved because the ions separate.', 1, 3),
      mc('Balancing a chemical equation ensures conservation of:', ['Energy only', 'Mass — the same atoms must appear on both sides', 'Volume of reactants and products', 'Temperature across the reaction'], 'Mass — the same atoms must appear on both sides', 'The Law of Conservation of Mass states that matter cannot be created or destroyed. Balancing equations by adjusting coefficients (not subscripts) ensures atom counts match on both sides.', 1, 4),
      mc('A solution with a pH of 3 is:', ['Slightly basic', 'Neutral', 'Strongly acidic', 'Slightly acidic'], 'Strongly acidic', 'pH 7 is neutral. Below 7 is acidic; above 7 is basic. The scale is logarithmic — pH 3 is 10,000 times more acidic than pH 7. Stomach acid is around pH 1-2.', 1, 5),
      mc('In a chemical reaction, activation energy is:', ['The energy released by the reaction', 'The minimum energy needed to initiate the reaction', 'The difference between reactant and product energy', 'The energy stored in chemical bonds'], 'The minimum energy needed to initiate the reaction', 'Even exothermic reactions (which release energy overall) need an initial energy input to break bonds in reactants before new bonds can form. Catalysts lower activation energy without being consumed.', 1, 6),
      mc('Avogadro\'s number (6.022 × 10²³) defines:', ['The number of atoms in one gram of any element', 'The number of particles in one mole of a substance', 'The number of protons in the atomic nucleus', 'The maximum number of electrons in any orbital'], 'The number of particles in one mole of a substance', 'A mole is a counting unit for atoms and molecules. One mole of carbon-12 has a mass of exactly 12 grams. This bridges the atomic and macroscopic scales in stoichiometry.', 1, 7),
      mc('A synthesis reaction is best described as:', ['Two or more substances combining to form a single product', 'A compound breaking into simpler substances', 'Two compounds exchanging ions', 'A reaction that requires heat input'], 'Two or more substances combining to form a single product', 'Synthesis: A + B → AB. Decomposition is the reverse: AB → A + B. Recognizing reaction types helps predict products and understand industrial chemistry processes.', 1, 8),
      oe('Explain why water has unusually high surface tension, boiling point, and specific heat capacity compared to similarly sized molecules.', 'Water molecules form hydrogen bonds — strong intermolecular attractions between the partially positive hydrogen of one molecule and the partially negative oxygen of another. These bonds require significant energy to break, giving water a high boiling point (100°C vs. H₂S at -60°C), high specific heat (resists temperature change), and high surface tension (molecules at the surface are pulled inward). Hydrogen bonding arises from water\'s bent shape and polar covalent bonds.', 'Water\'s unusual properties make life possible: high specific heat stabilizes Earth\'s climate, high boiling point keeps water liquid at biological temperatures, and surface tension allows capillary action in plants. All trace back to hydrogen bonding.', 2, 9),
      oe('Describe what happens at the molecular level during a neutralization reaction between hydrochloric acid (HCl) and sodium hydroxide (NaOH).', 'HCl dissociates in water into H⁺ and Cl⁻ ions. NaOH dissociates into Na⁺ and OH⁻ ions. The H⁺ and OH⁻ ions combine to form water (H₂O). The remaining Na⁺ and Cl⁻ ions form sodium chloride (table salt) when the water evaporates. The net ionic equation is simply H⁺ + OH⁻ → H₂O. The reaction is exothermic and raises solution temperature.', 'Neutralization brings an acid and base to pH 7 (neutral). The products are always water and a salt. This reaction type is fundamental in industrial chemistry, pharmaceuticals, and water treatment.', 2, 10),
    ],
  },
  'physics': {
    title: 'Physics Assessment', passingScore: 75, timeLimitMin: 30,
    questions: [
      mc('Newton\'s First Law (inertia) states that an object:', ['Accelerates in proportion to applied force', 'Will remain at rest or in constant motion unless acted on by a net external force', 'Attracts other objects proportionally to its mass', 'Exerts an equal and opposite reaction force'], 'Will remain at rest or in constant motion unless acted on by a net external force', 'Inertia is the resistance to change in motion. In the absence of friction and other forces (deep space), a moving object continues at constant velocity indefinitely.', 1, 1),
      mc('The unit of energy in the SI system is:', ['Newton (N)', 'Watt (W)', 'Joule (J)', 'Pascal (Pa)'], 'Joule (J)', 'One joule = one newton·meter = one watt·second. Watts measure power (rate of energy use); joules measure energy itself. A 100W bulb uses 100 joules per second.', 1, 2),
      mc('According to the Law of Conservation of Energy:', ['Energy is created during exothermic reactions', 'Energy cannot be created or destroyed, only converted between forms', 'Mechanical energy is always conserved in real systems', 'Energy is destroyed when converted to heat'], 'Energy cannot be created or destroyed, only converted between forms', 'Kinetic energy, potential energy, heat, light, and chemical energy are all interconvertible but the total is constant. A falling ball converts potential to kinetic; friction converts kinetic to heat.', 1, 3),
      mc('An object in free fall near Earth\'s surface accelerates at approximately:', ['5 m/s²', '9.8 m/s²', '12 m/s²', '3.7 m/s²'], '9.8 m/s²', 'Gravitational acceleration at Earth\'s surface (g) is ~9.8 m/s². Every second of free fall adds 9.8 m/s to velocity (ignoring air resistance). This is the same for all masses — Galileo\'s famous insight.', 1, 4),
      mc('Waves transfer:', ['Matter from one place to another', 'Energy through a medium without net movement of the medium itself', 'Sound only — electromagnetic waves transfer matter', 'Heat through direct contact'], 'Energy through a medium without net movement of the medium itself', 'Ocean waves move energy across the surface but water molecules mostly move in circles. Sound waves compress and expand air without carrying air molecules along. Electromagnetic waves transfer energy through empty space.', 1, 5),
      mc('Ohm\'s Law states that voltage equals:', ['Current divided by resistance', 'Current multiplied by resistance', 'Power divided by current', 'Resistance divided by current'], 'Current multiplied by resistance', 'V = IR. Voltage is the driving force (pressure), current is the flow (amps), resistance opposes flow (ohms). Double the resistance at constant voltage and current halves. This is foundational for all circuit analysis.', 1, 6),
      mc('Momentum is conserved in a collision when:', ['No kinetic energy is lost', 'No external forces act on the system', 'The objects stick together', 'The collision is elastic'], 'No external forces act on the system', 'Conservation of momentum holds in all collisions — elastic (kinetic energy conserved) and inelastic (kinetic energy lost to heat/deformation). The total momentum before equals total momentum after when there\'s no external net force.', 1, 7),
      mc('The Doppler effect explains why a siren sounds higher-pitched as it approaches and lower as it moves away. This is because:', ['Sound travels faster toward you', 'Relative motion compresses or stretches wave wavelengths as perceived by the observer', 'The siren produces different frequencies intentionally', 'Sound intensity increases with proximity'], 'Relative motion compresses or stretches wave wavelengths as perceived by the observer', 'As the source approaches, successive wave crests arrive more frequently (shorter apparent wavelength = higher pitch). As it recedes, crests arrive less frequently (lower pitch). The same principle applies to light — redshift in astronomy.', 1, 8),
      oe('A 10 kg box is pushed across a floor with a 50 N force. The frictional force opposing motion is 20 N. Calculate the net force and the resulting acceleration.', 'Net force = Applied force - Friction = 50 N - 20 N = 30 N. Using Newton\'s Second Law: F = ma → a = F/m = 30 N / 10 kg = 3 m/s². The box accelerates at 3 meters per second squared in the direction of applied force.', 'Net force determines acceleration, not applied force alone. Friction must always be subtracted from the driving force. Without friction, all 50 N would accelerate the box at 5 m/s². This is why surfaces and lubrication matter in engineering.', 2, 9),
      oe('Explain the relationship between potential energy and kinetic energy using the example of a roller coaster.', 'At the top of the first hill, the roller coaster has maximum gravitational potential energy (PE = mgh) and minimum kinetic energy. As it descends, PE converts to kinetic energy (KE = ½mv²) — the coaster speeds up. At the bottom, KE is maximum and PE is minimum. On the next uphill, KE converts back to PE. In a frictionless system, total mechanical energy is perfectly conserved. In reality, friction converts some energy to heat, which is why subsequent hills must be shorter.', 'Energy conversion is never perfectly efficient in real systems. Roller coasters must be engineered so subsequent hills are lower than the initial one because friction losses mean the car never fully regains its original PE. This is why perpetual motion machines are impossible.', 2, 10),
    ],
  },
  'earth-science': {
    title: 'Earth & Environmental Science Assessment', passingScore: 75, timeLimitMin: 30,
    questions: [
      mc('The theory of plate tectonics explains:', ['Why seasons change', 'The movement of Earth\'s lithospheric plates and resulting geological phenomena', 'The formation of the atmosphere', 'How erosion shapes landscapes'], 'The movement of Earth\'s lithospheric plates and resulting geological phenomena', 'Plate tectonics unifies geology — explaining earthquakes, volcanoes, mountain building, ocean basin formation, and the distribution of fossils across continents that were once joined.', 1, 1),
      mc('Which type of rock forms from the cooling and solidification of magma or lava?', ['Sedimentary', 'Metamorphic', 'Igneous', 'Carbonate'], 'Igneous', 'Igneous rocks (granite, basalt, obsidian) form from cooling magma (intrusive) or lava (extrusive). Sedimentary rocks form from compressed sediments. Metamorphic rocks form when existing rocks are changed by heat and pressure.', 1, 2),
      mc('The greenhouse effect is a natural process that:', ['Cools the planet by reflecting sunlight', 'Warms the planet by trapping heat radiated from the surface', 'Creates the ozone layer', 'Drives ocean currents'], 'Warms the planet by trapping heat radiated from the surface', 'Greenhouse gases (CO₂, water vapor, methane) absorb outgoing infrared radiation and re-radiate it back to the surface. Without this effect, Earth\'s average temperature would be about -18°C instead of +15°C.', 1, 3),
      mc('Seismic waves from earthquakes are detected and measured using:', ['Barometers', 'Seismographs', 'Doppler radar', 'Magnetometers'], 'Seismographs', 'Seismographs record ground motion as seismic waves pass. Different wave types (P-waves, S-waves, surface waves) travel at different speeds and through different materials, helping scientists locate epicenters and study Earth\'s interior.', 1, 4),
      mc('The rock cycle describes:', ['How rocks are classified by color and hardness', 'The continuous transformation of rocks from one type to another through geological processes', 'The age progression of rocks from young to old', 'The way erosion destroys rock permanently'], 'The continuous transformation of rocks from one type to another through geological processes', 'Rocks continuously transform: magma cools to igneous → erosion creates sediments → sediments compact to sedimentary → heat/pressure creates metamorphic → melting restarts the cycle. No rock type is permanent.', 1, 5),
      mc('Climate differs from weather in that climate describes:', ['Today\'s temperature and precipitation', 'Extreme weather events like hurricanes', 'Long-term atmospheric patterns over decades in a region', 'The conditions at a specific moment'], 'Long-term atmospheric patterns over decades in a region', '"Climate is what you expect; weather is what you get." Climate is the statistical average and variability of atmospheric conditions over 30+ years. Weather is day-to-day or hour-to-hour conditions.', 1, 6),
      mc('Evidence for human-caused climate change includes:', ['The fact that Earth\'s climate has never changed before', 'Rising atmospheric CO₂ concentrations matching fossil fuel combustion patterns, plus rising global temperatures', 'A single decade of temperature records', 'The opinions of most climate scientists but no physical measurements'], 'Rising atmospheric CO₂ concentrations matching fossil fuel combustion patterns, plus rising global temperatures', 'Multiple independent lines of evidence converge: isotopic fingerprints showing fossil fuel origin of added CO₂, ice core records, satellite measurements, ocean heat content, and global temperature datasets — all consistent with human causation.', 1, 7),
      mc('Which layer of Earth is responsible for generating the magnetic field?', ['The crust', 'The mantle', 'The outer core', 'The inner core'], 'The outer core', 'The outer core is liquid iron-nickel. Convection currents in this conducting fluid generate Earth\'s magnetic field through the dynamo effect. The inner core is solid despite high temperatures due to immense pressure.', 1, 8),
      oe('Explain how volcanic eruptions can temporarily lower global temperatures, and why this doesn\'t contradict evidence for human-caused warming.', 'Large volcanic eruptions inject sulfur dioxide into the stratosphere, where it forms aerosols that reflect incoming sunlight, temporarily cooling the planet (e.g., Mount Pinatubo 1991 cooled Earth by ~0.5°C for 1-2 years). This is a short-term, natural forcing that scientists account for in climate models. Human warming is a long-term, persistent trend driven by accumulating CO₂ — the temporary cooling from volcanoes occurs on top of the underlying warming trend and doesn\'t reverse it.', 'Understanding natural climate forcings (volcanoes, solar variation, ocean cycles) is essential for attributing observed warming to human causes. When scientists subtract all known natural forcings from observed temperature rise, the remaining trend matches human emissions. Volcanoes actually provide evidence that scientists understand climate forcing well.', 2, 9),
      oe('Describe the difference between a convergent and divergent plate boundary and give one geological feature associated with each.', 'At convergent boundaries, plates move toward each other. When an oceanic plate meets a continental plate, the denser oceanic plate subducts beneath the continental plate, creating a trench and volcanic mountain range (e.g., the Andes, formed by the Nazca plate subducting under South America). At divergent boundaries, plates move apart and magma rises to fill the gap, creating new oceanic crust — the Mid-Atlantic Ridge is an example, causing Iceland\'s volcanic activity and gradually widening the Atlantic Ocean.', 'Plate boundaries are where most geological action happens. The type of boundary determines whether crust is created or destroyed, and what surface features result. Transform boundaries (plates sliding past each other, like the San Andreas Fault) cause earthquakes without significant volcanism.', 2, 10),
    ],
  },
  'astronomy': {
    title: 'Astronomy & Space Assessment', passingScore: 75, timeLimitMin: 25,
    questions: [
      mc('The Sun\'s energy is produced by:', ['Combustion of hydrogen gas', 'Nuclear fusion of hydrogen into helium in the core', 'Nuclear fission of uranium', 'Gravitational compression alone'], 'Nuclear fusion of hydrogen into helium in the core', 'In the Sun\'s core (15 million °C), hydrogen nuclei fuse into helium, converting a small amount of mass into enormous energy via E = mc². This process has sustained the Sun for 4.6 billion years and will continue for ~5 billion more.', 1, 1),
      mc('A light-year is a unit of:', ['Time', 'Distance — the distance light travels in one year', 'Speed', 'Stellar brightness'], 'Distance — the distance light travels in one year', 'Light travels ~300,000 km/s, so a light-year is ~9.46 trillion km. Proxima Centauri, the nearest star, is 4.24 light-years away — meaning we see it as it was 4.24 years ago.', 1, 2),
      mc('The Big Bang theory describes:', ['An explosion of matter in empty space', 'The rapid expansion of space itself from an extremely hot, dense state ~13.8 billion years ago', 'The death of a massive star', 'The collision of two galaxies'], 'The rapid expansion of space itself from an extremely hot, dense state ~13.8 billion years ago', 'The Big Bang was not an explosion in space — it was the expansion of space itself. Evidence includes the cosmic microwave background radiation, the redshift of distant galaxies, and the abundance of light elements.', 1, 3),
      mc('Stars are classified mainly by:', ['Size and age', 'Surface temperature and luminosity', 'Distance from Earth', 'Chemical composition alone'], 'Surface temperature and luminosity', 'The Hertzsprung-Russell (HR) diagram plots stars by temperature vs. luminosity, revealing that most stars fall on a "main sequence" — including our Sun — with predictable relationships between these properties.', 1, 4),
      mc('What causes the phases of the Moon?', ['Earth\'s shadow falling on the Moon', 'The Moon\'s rotation on its axis', 'The changing angle at which we see the sunlit portion of the Moon', 'Clouds blocking portions of the Moon'], 'The changing angle at which we see the sunlit portion of the Moon', 'The Moon is always half-illuminated by the Sun. As the Moon orbits Earth, we see varying portions of the lit half — from new moon (none visible) to full moon (entirely visible) and back.', 1, 5),
      mc('A solar eclipse occurs when:', ['Earth passes between the Sun and Moon', 'The Moon passes between Earth and the Sun', 'The Moon enters Earth\'s shadow', 'The Sun\'s light is refracted by the atmosphere'], 'The Moon passes between Earth and the Sun', 'A solar eclipse happens at new moon when the Moon aligns with the Sun from Earth\'s perspective. A lunar eclipse happens when Earth\'s shadow falls on the Moon at full moon.', 1, 6),
      mc('The Milky Way galaxy is classified as:', ['An elliptical galaxy', 'An irregular galaxy', 'A barred spiral galaxy', 'A dwarf galaxy'], 'A barred spiral galaxy', 'The Milky Way has a central bar of stars from which spiral arms emerge. Our solar system sits in the Orion Arm, about 26,000 light-years from the galactic center, which harbors a supermassive black hole.', 1, 7),
      mc('Dark matter is inferred from:', ['Direct observation through telescopes', 'Its gravitational effects on visible matter and light', 'Cosmic microwave background patterns alone', 'Theoretical models with no observational support'], 'Its gravitational effects on visible matter and light', 'Galaxies rotate at speeds that cannot be explained by the gravity of visible matter alone. Gravitational lensing bends light more than visible mass predicts. Dark matter — whatever it is — accounts for ~27% of the universe\'s total mass-energy.', 1, 8),
      oe('Describe the life cycle of a star like our Sun, from formation to its ultimate fate.', 'A star forms when a nebula (cloud of gas and dust) collapses under gravity, heating until nuclear fusion ignites in the core — a protostar becomes a main sequence star. For ~10 billion years it fuses hydrogen into helium. When hydrogen is exhausted, the core contracts and outer layers expand into a red giant. Finally, the outer layers are expelled as a planetary nebula, leaving a dense white dwarf that slowly cools over billions of years. Massive stars (8+ solar masses) end more dramatically in a supernova, leaving a neutron star or black hole.', 'A star\'s mass determines its fate. Low-mass stars like the Sun end quietly as white dwarfs; massive stars end violently. The elements forged in stellar cores and distributed by supernovae — carbon, oxygen, iron — are the raw material for planets and life. We are, literally, made of star stuff.', 2, 9),
      oe('Explain two independent pieces of evidence that support the Big Bang theory.', 'First, the cosmic microwave background (CMB): the universe is filled with faint microwave radiation at ~2.7 K — the thermal afterglow predicted if the universe began in an extremely hot state. Its uniformity and small fluctuations match Big Bang predictions. Second, Hubble\'s observation that distant galaxies are moving away from us proportionally to their distance (Hubble\'s Law). Tracing this expansion backward implies all matter was once concentrated in an unimaginably hot, dense state.', 'Multiple independent lines of evidence — CMB, galaxy redshift, and the observed abundance of hydrogen and helium matching Big Bang nucleosynthesis predictions — all converge on the same picture. Like other scientific theories, the Big Bang makes predictions that have repeatedly been confirmed by observation.', 2, 10),
    ],
  },
}
