import type { ExerciseDef } from '../types'

function mc(
  question: string,
  options: string[],
  correctAnswer: string,
  explanation: string,
  order: number
): ExerciseDef {
  return { question, type: 'MULTIPLE_CHOICE', options, correctAnswer, explanation, order }
}

export const sciencesExercises2: Record<string, ExerciseDef[]> = {
  'cell-division': [
    mc('What is mitosis?', ['Cell division producing genetically distinct daughter cells', 'Cell division that produces two genetically identical daughter cells', 'The division of the nucleus only', 'Sexual reproduction in single-celled organisms'], 'Cell division that produces two genetically identical daughter cells', 'Mitosis produces two diploid cells with the same genetic information as the parent — used for growth, repair, and asexual reproduction.', 1),
    mc('What is the difference between mitosis and meiosis?', ['Mitosis produces sex cells; meiosis produces body cells', 'Meiosis produces four genetically unique haploid cells (sex cells); mitosis produces two identical diploid cells', 'They are the same process', 'Mitosis occurs in prokaryotes; meiosis in eukaryotes'], 'Meiosis produces four genetically unique haploid cells (sex cells); mitosis produces two identical diploid cells', 'Meiosis halves chromosome number and introduces genetic variation through crossing over — necessary for sexual reproduction.', 2),
    mc('What is the role of the cell cycle\'s G1 phase?', ['DNA replication', 'Cell growth and preparation for division', 'Chromosome separation', 'Cytokinesis'], 'Cell growth and preparation for division', 'G1 (Gap 1) is when the cell grows, synthesizes proteins, and checks that conditions are right before committing to division.', 3),
    mc('What happens during the S phase of the cell cycle?', ['The cell physically divides', 'DNA is replicated — each chromosome is duplicated', 'Chromosomes align at the cell\'s center', 'The nuclear envelope breaks down'], 'DNA is replicated — each chromosome is duplicated', 'S phase (synthesis) is when the entire genome is copied. Each chromosome becomes two identical sister chromatids held together at the centromere.', 4),
    mc('Cancer is most directly caused by:', ['Viruses infecting healthy cells', 'Uncontrolled cell division due to mutations in genes regulating the cell cycle', 'Cells dying too quickly', 'Failure of meiosis'], 'Uncontrolled cell division due to mutations in genes regulating the cell cycle', 'Mutations in proto-oncogenes or tumor suppressor genes disrupt normal cell cycle checkpoints — cells divide uncontrollably, forming tumors.', 5),
  ],
  'dna-and-genes': [
    mc('What is DNA?', ['A protein that carries energy', 'A double-helix molecule made of nucleotides that stores genetic information', 'A type of lipid found in the nucleus', 'RNA in its inactive form'], 'A double-helix molecule made of nucleotides that stores genetic information', 'DNA (deoxyribonucleic acid) stores hereditary information in base sequences (A, T, C, G). The double helix structure (Watson & Crick, 1953) enables accurate copying.', 1),
    mc('What is a gene?', ['The entire DNA of an organism', 'A segment of DNA that codes for a specific protein or functional RNA', 'A chromosome', 'Any sequence of bases in DNA'], 'A segment of DNA that codes for a specific protein or functional RNA', 'Genes are functional units of heredity — specific sequences that are transcribed into RNA and often translated into proteins that carry out biological functions.', 2),
    mc('What is the central dogma of molecular biology?', ['DNA → RNA → Protein', 'Protein → RNA → DNA', 'RNA → DNA → Protein', 'DNA → Protein directly'], 'DNA → RNA → Protein', 'Information flows from DNA (transcription → mRNA) to protein (translation). This framework explains how genetic information becomes functional molecules.', 3),
    mc('What is transcription?', ['Converting mRNA into a protein', 'Copying DNA into an mRNA strand', 'Replicating the entire genome', 'Reading the amino acid sequence'], 'Copying DNA into an mRNA strand', 'Transcription occurs in the nucleus — RNA polymerase reads a DNA strand and builds a complementary mRNA strand that carries the gene\'s instructions to the ribosome.', 4),
    mc('What is translation?', ['Converting DNA to RNA', 'The ribosome reading mRNA and assembling a protein from amino acids', 'Moving proteins out of the cell', 'Copying the genome before cell division'], 'The ribosome reading mRNA and assembling a protein from amino acids', 'Translation occurs at ribosomes — tRNA molecules bring amino acids matching mRNA codons, and the ribosome links them into a polypeptide chain.', 5),
  ],
  'heredity': [
    mc('What are alleles?', ['Different versions of the same gene', 'Two identical chromosomes', 'The protein products of a gene', 'Sections of non-coding DNA'], 'Different versions of the same gene', 'Alleles are alternate forms of a gene at the same locus on homologous chromosomes — e.g., the allele for brown eyes vs. blue eyes.', 1),
    mc('What does it mean for a trait to be dominant?', ['It is more common in the population', 'It is expressed when at least one dominant allele is present, masking the recessive allele', 'It is always inherited from the mother', 'It skips a generation'], 'It is expressed when at least one dominant allele is present, masking the recessive allele', 'A dominant allele (B) masks the recessive (b). A person with BB or Bb shows the dominant trait; only bb shows the recessive trait.', 2),
    mc('What is a Punnett square used for?', ['Mapping chromosomes to proteins', 'Predicting the probability of offspring inheriting specific genotypes or phenotypes', 'Comparing DNA sequences between species', 'Identifying mutations in a genome'], 'Predicting the probability of offspring inheriting specific genotypes or phenotypes', 'Punnett squares show all possible allele combinations from two parents, giving the probability of each genotype and phenotype in offspring.', 3),
    mc('What is the difference between genotype and phenotype?', ['Genotype is observable; phenotype is genetic', 'Genotype is the genetic makeup; phenotype is the observable trait resulting from genotype + environment', 'They mean the same thing', 'Genotype applies to plants; phenotype to animals'], 'Genotype is the genetic makeup; phenotype is the observable trait resulting from genotype + environment', 'Genotype (AA, Aa, aa) is the actual allele combination. Phenotype (tall, short) is what\'s observed — shaped by genes and environment.', 4),
    mc('What is Mendel\'s law of independent assortment?', ['Genes for different traits are always inherited together', 'Genes for different traits on different chromosomes are inherited independently of each other', 'Dominant traits always appear in every generation', 'Alleles separate before fertilization'], 'Genes for different traits on different chromosomes are inherited independently of each other', 'Independent assortment (Mendel\'s second law) explains why traits on different chromosomes are shuffled randomly, creating variation in offspring.', 5),
  ],
  'mutations-and-variation': [
    mc('What is a genetic mutation?', ['A change in an organism\'s behavior', 'A permanent change in the DNA sequence', 'The process of natural selection', 'A cell dividing incorrectly but keeping correct DNA'], 'A permanent change in the DNA sequence', 'Mutations are changes to DNA — can be a single base change (point mutation), insertion, deletion, or larger chromosomal rearrangement.', 1),
    mc('Are all mutations harmful?', ['Yes — any change to DNA is damaging', 'No — mutations can be harmful, neutral, or occasionally beneficial', 'Only mutations in non-coding DNA are harmful', 'Mutations are always corrected by DNA repair'], 'No — mutations can be harmful, neutral, or occasionally beneficial', 'Most mutations are neutral (in non-coding regions). Some are harmful (cause disease). Rare beneficial mutations can increase survival — the raw material for evolution.', 2),
    mc('What causes genetic variation in sexually reproducing organisms?', ['Only random mutations', 'Crossing over, independent assortment, and random fertilization', 'The environment only', 'Identical replication of parental DNA'], 'Crossing over, independent assortment, and random fertilization', 'Sexual reproduction shuffles alleles three ways: crossing over (recombination during meiosis), independent assortment, and which sperm meets which egg.', 3),
    mc('What is a point mutation?', ['A mutation affecting an entire chromosome', 'A change in a single nucleotide base in the DNA sequence', 'A mutation that skips a generation', 'Deletion of a large chromosome segment'], 'A change in a single nucleotide base in the DNA sequence', 'A point mutation changes one nucleotide — may cause no change (silent), change one amino acid (missense), or introduce a stop codon (nonsense).', 4),
    mc('What is the source of heritable variation in a population?', ['Mutations and sexual recombination passed from parent to offspring', 'Mutations acquired during an organism\'s lifetime through behavior', 'Learned traits passed to offspring', 'Environmental pressure alone'], 'Mutations and sexual recombination passed from parent to offspring', 'Only mutations in germ cells (sperm/egg) are heritable. Somatic mutations affect only the individual. Recombination reshuffles existing variation each generation.', 5),
  ],
  'biotechnology': [
    mc('What is CRISPR-Cas9?', ['A virus that naturally edits genomes', 'A gene-editing tool that can precisely cut and modify DNA at specific locations', 'A technique to clone entire organisms', 'A method for sequencing DNA cheaply'], 'A gene-editing tool that can precisely cut and modify DNA at specific locations', 'CRISPR uses guide RNA to direct the Cas9 enzyme to a specific DNA sequence, where it cuts — allowing deletion, correction, or insertion of genes.', 1),
    mc('What is a GMO?', ['An organism with genes from another species introduced through selective breeding', 'An organism whose DNA has been deliberately altered using genetic engineering techniques', 'Any organism that has undergone natural mutation', 'A cloned organism'], 'An organism whose DNA has been deliberately altered using genetic engineering techniques', 'GMOs (genetically modified organisms) have genes inserted, deleted, or modified in the lab — including Bt corn, golden rice, and insulin-producing bacteria.', 2),
    mc('How is insulin produced using biotechnology?', ['Extracted from pig pancreases only', 'The human insulin gene is inserted into bacteria, which then produce human insulin at scale', 'Synthesized entirely from scratch without biological systems', 'Grown in yeast through selective breeding'], 'The human insulin gene is inserted into bacteria, which then produce human insulin at scale', 'Recombinant DNA technology: the insulin gene is cloned into E. coli plasmids. Bacteria then produce human insulin — safer and more scalable than animal-derived insulin.', 3),
    mc('What is PCR (Polymerase Chain Reaction)?', ['A method to edit genes using CRISPR', 'A technique to rapidly amplify (copy) a specific DNA sequence millions of times', 'A process to sequence all DNA in a genome', 'A method to insert genes into organisms'], 'A technique to rapidly amplify (copy) a specific DNA sequence millions of times', 'PCR uses heat cycling and DNA polymerase to copy a target sequence exponentially — used in COVID tests, forensic DNA analysis, and research.', 4),
    mc('What ethical concern is most associated with human genetic engineering?', ['It is too expensive to be practical', 'Designer babies — selecting or enhancing traits raises questions about inequality, consent, and what makes us human', 'It cannot work in humans yet', 'All genetic changes are unstable and revert'], 'Designer babies — selecting or enhancing traits raises questions about inequality, consent, and what makes us human', 'Germline editing (heritable changes) is especially controversial — edited changes pass to all descendants. Debates around equity, eugenics, and human dignity are unresolved.', 5),
  ],
  'natural-selection': [
    mc('What is natural selection?', ['Random change in allele frequencies over time', 'The process by which individuals with advantageous traits reproduce more, passing traits to offspring', 'Humans selectively breeding animals', 'Mutations that always improve survival'], 'The process by which individuals with advantageous traits reproduce more, passing traits to offspring', 'Natural selection requires: variation in traits, heritability of those traits, and differential reproduction. Favorable traits become more common over generations.', 1),
    mc('What is fitness in evolutionary terms?', ['An organism\'s physical health and strength', 'Reproductive success — how many viable offspring an organism produces', 'The ability to survive any environment', 'Intelligence relative to competitors'], 'Reproductive success — how many viable offspring an organism produces', 'Evolutionary fitness = contribution to the next generation\'s gene pool. A weak organism that reproduces many offspring has higher fitness than a strong one with none.', 2),
    mc('What is adaptation?', ['A behavioral change during an organism\'s lifetime', 'An inherited trait that increases an organism\'s fitness in its environment', 'Any change to an organism\'s body', 'A mutation that occurs in response to the environment'], 'An inherited trait that increases an organism\'s fitness in its environment', 'Adaptations evolve over generations through natural selection — not acquired during life. Camouflage, beaks shaped for food sources, and antibiotic resistance are adaptations.', 3),
    mc('What is the evidence for evolution by natural selection?', ['Only the fossil record', 'The fossil record, comparative anatomy, DNA sequence similarity, observed speciation, and antibiotic resistance', 'Only laboratory experiments', 'Darwin\'s observations alone'], 'The fossil record, comparative anatomy, DNA sequence similarity, observed speciation, and antibiotic resistance', 'Multiple independent lines of evidence converge: fossils show change over time, homologous structures show common ancestry, DNA confirms relatedness, and we observe evolution in real time.', 4),
    mc('What is artificial selection?', ['Natural selection in human-altered environments', 'Humans intentionally breeding organisms with desired traits over generations', 'Genetic engineering to produce traits', 'Evolution that occurs faster than normal'], 'Humans intentionally breeding organisms with desired traits over generations', 'Artificial selection (selective breeding) produced dogs from wolves, corn from teosinte, and every modern livestock breed — Darwin used it to illustrate natural selection\'s power.', 5),
  ],
  'classification-of-life': [
    mc('What are the three domains of life?', ['Plants, Animals, Fungi', 'Bacteria, Archaea, Eukarya', 'Prokaryotes, Eukaryotes, Viruses', 'Kingdom, Phylum, Class'], 'Bacteria, Archaea, Eukarya', 'The three-domain system (Woese) groups all life: Bacteria and Archaea are prokaryotes, Eukarya includes all eukaryotes (plants, animals, fungi, protists).', 1),
    mc('What is the correct order of taxonomic levels from broadest to most specific?', ['Species, Genus, Family, Order, Class, Phylum, Kingdom, Domain', 'Domain, Kingdom, Phylum, Class, Order, Family, Genus, Species', 'Kingdom, Phylum, Order, Class, Family, Genus, Species', 'Domain, Phylum, Kingdom, Class, Family, Order, Genus, Species'], 'Domain, Kingdom, Phylum, Class, Order, Family, Genus, Species', 'Taxonomy: Dear King Philip Came Over For Good Soup. Each level groups organisms by increasing similarity.', 2),
    mc('What does a species\' binomial nomenclature consist of?', ['Kingdom and Phylum', 'Genus and species (e.g., Homo sapiens)', 'Family and Genus', 'Class and Order'], 'Genus and species (e.g., Homo sapiens)', 'Binomial nomenclature (Linnaeus): two-part Latin name — genus (capitalized) + species (lowercase). Written in italics. Universally understood across languages.', 3),
    mc('Why are viruses NOT classified as living organisms by most biologists?', ['They are too small to be alive', 'They lack cells, cannot reproduce independently, and don\'t carry out metabolism on their own', 'They don\'t have DNA', 'They evolved too recently to be classified'], 'They lack cells, cannot reproduce independently, and don\'t carry out metabolism on their own', 'Viruses are acellular and can only replicate inside a host cell using the host\'s machinery. They lack the autonomous characteristics of life.', 4),
    mc('What is a phylogenetic tree?', ['A chart showing an organism\'s taxonomy from domain to species', 'A diagram showing evolutionary relationships and common ancestry among organisms', 'A graph of population sizes over time', 'A map of an ecosystem\'s food web'], 'A diagram showing evolutionary relationships and common ancestry among organisms', 'Phylogenetic trees (cladograms) show branching patterns of ancestry — organisms sharing a recent common ancestor are more closely related, like a family tree for species.', 5),
  ],
}
