import type { ExerciseDef } from '../types'

function mc(
  question: string,
  options: string[],
  correctAnswer: string,
  explanation: string,
  order: number
): ExerciseDef {
  return { question, type: 'MULTIPLE_CHOICE', options, correctAnswer, explanation, order }
}

export const sciencesExercises4: Record<string, ExerciseDef[]> = {
  'covalent-bonds': [
    mc('What is a covalent bond?', ['Transfer of electrons from one atom to another', 'Sharing of one or more pairs of electrons between atoms', 'Attraction between opposite ions', 'A weak force between molecules'], 'Sharing of one or more pairs of electrons between atoms', 'Covalent bonds form between nonmetals — atoms share electrons to achieve full outer shells. H₂O: oxygen shares electrons with two hydrogen atoms.', 1),
    mc('What is a polar covalent bond?', ['A bond where electrons are shared equally', 'A bond where electrons are shared unequally due to different electronegativities', 'A bond between ions', 'A bond involving more than two atoms'], 'A bond where electrons are shared unequally due to different electronegativities', 'When atoms have different electronegativities, the more electronegative atom pulls electrons closer — creating partial charges (δ+ and δ-). Water\'s O-H bonds are polar covalent.', 2),
    mc('What is a nonpolar covalent bond?', ['A bond between two different atoms', 'A bond where electrons are shared equally between atoms with the same electronegativity', 'A bond in ionic compounds', 'A bond that doesn\'t involve valence electrons'], 'A bond where electrons are shared equally between atoms with the same electronegativity', 'Identical atoms (H₂, O₂, N₂) or atoms with very similar electronegativities share electrons symmetrically — no partial charges.', 3),
    mc('How do covalent compounds differ from ionic compounds?', ['Covalent compounds have higher melting points', 'Covalent compounds have lower melting points, don\'t conduct electricity when dissolved, and exist as discrete molecules', 'Ionic compounds form molecules; covalent compounds form crystals', 'There is no meaningful difference in properties'], 'Covalent compounds have lower melting points, don\'t conduct electricity when dissolved, and exist as discrete molecules', 'Covalent bonds form molecules — weaker intermolecular forces mean lower melting/boiling points. No ions → no electrical conductivity in solution.', 4),
    mc('What is a double bond?', ['Two single bonds between different pairs of atoms', 'Sharing of two pairs of electrons between two atoms', 'A bond between two identical elements only', 'A bond formed in ionic compounds'], 'Sharing of two pairs of electrons between two atoms', 'Double bonds (e.g., O=O in O₂, C=C in ethylene) share 4 electrons — stronger and shorter than single bonds. Triple bonds share 6 electrons (N≡N).', 5),
  ],
  'naming-compounds': [
    mc('How are binary ionic compounds named?', ['Name the anion first, then the cation with -ide suffix', 'Name the cation first, then the anion with -ide suffix', 'Use Greek prefixes for both elements', 'Name by molecular formula only'], 'Name the cation first, then the anion with -ide suffix', 'NaCl = sodium chloride. MgO = magnesium oxide. Cation (metal) name unchanged; anion (nonmetal) gets -ide ending.', 1),
    mc('How are binary covalent compounds named?', ['Cation first, anion with -ide', 'Using Greek prefixes (mono-, di-, tri-) to indicate numbers of each atom', 'By the metal\'s name plus the nonmetal with -ide', 'By the compound\'s common name only'], 'Using Greek prefixes (mono-, di-, tri-) to indicate numbers of each atom', 'CO₂ = carbon dioxide; N₂O₄ = dinitrogen tetroxide. Prefixes (mono=1, di=2, tri=3, tetra=4) indicate the number of each atom.', 2),
    mc('What does the Roman numeral in iron(III) chloride indicate?', ['The number of chlorine atoms', 'The charge of the iron ion (+3)', 'The atomic mass of iron', 'The group number of iron on the periodic table'], 'The charge of the iron ion (+3)', 'Transition metals can form multiple ions. Iron(III) means Fe³⁺. Iron(II) would be Fe²⁺. Roman numerals specify which ion is present when multiple options exist.', 3),
    mc('What is the name for H₂SO₄?', ['Hydrogen sulfite', 'Sulfuric acid', 'Hydrosulfuric acid', 'Sulfate acid'], 'Sulfuric acid', 'H₂SO₄ is sulfuric acid — one of the most important industrial chemicals. Acids containing oxygen (oxyacids) are named with -ic or -ous suffix patterns.', 4),
    mc('What does the -ate suffix indicate in a polyatomic ion like sulfate (SO₄²⁻)?', ['The ion has gained extra electrons', 'The ion contains oxygen and has more oxygen than the -ite form', 'The ion is a cation', 'The ion came from an acid with hydrogen'], 'The ion contains oxygen and has more oxygen than the -ite form', 'The -ate/-ite pair: sulfate (SO₄²⁻) has more oxygen than sulfite (SO₃²⁻). Nitrate (NO₃⁻) has more oxygen than nitrite (NO₂⁻).', 5),
  ],
  'balancing-equations': [
    mc('Why must chemical equations be balanced?', ['To make them look symmetrical', 'To satisfy the law of conservation of mass — atoms are neither created nor destroyed in a reaction', 'Because the products must equal the reactants in number', 'Government safety regulations require it'], 'To satisfy the law of conservation of mass — atoms are neither created nor destroyed in a reaction', 'Balancing ensures the same number of each atom appears on both sides. Matter is conserved — reactions rearrange atoms, not create or destroy them.', 1),
    mc('In the equation H₂ + O₂ → H₂O, why is it unbalanced?', ['There are more H atoms than O atoms', 'The left has 2 oxygen atoms but the right has only 1', 'The coefficients are wrong', 'Water should have two oxygens'], 'The left has 2 oxygen atoms but the right has only 1', 'O₂ on the left has 2 oxygens; H₂O on the right has 1. Balanced: 2H₂ + O₂ → 2H₂O gives 4H and 2O on both sides.', 2),
    mc('When balancing equations, what can you change?', ['The subscripts within chemical formulas', 'Only the coefficients (numbers in front of formulas)', 'Both subscripts and coefficients', 'The elements involved in the reaction'], 'Only the coefficients (numbers in front of formulas)', 'Changing subscripts changes the substance. You can only add coefficients — multipliers for whole formulas. 2H₂O means two water molecules.', 3),
    mc('What is a coefficient in a chemical equation?', ['The small number below the element symbol', 'The large number in front of a chemical formula indicating how many molecules are present', 'The charge of an ion', 'The atomic number of an element'], 'The large number in front of a chemical formula indicating how many molecules are present', 'Coefficients multiply the entire formula. 3H₂O means 3 molecules of water = 6 H and 3 O. Subscripts (the small numbers) indicate atoms within a formula.', 4),
    mc('How many oxygen atoms are in 2Ca(NO₃)₂?', ['6', '12', '8', '4'], '12', '2Ca(NO₃)₂: the subscript 2 outside the parentheses multiplies everything inside (NO₃) → N₁O₃. Times 2 for two NO₃ groups = 6 oxygens per formula unit, times 2 molecules = 12.', 5),
  ],
  'types-of-reactions': [
    mc('What is a synthesis reaction?', ['Breaking a compound into simpler substances', 'Two or more reactants combining to form one product (A + B → AB)', 'One element replacing another in a compound', 'Two ionic compounds exchanging ions'], 'Two or more reactants combining to form one product (A + B → AB)', 'Synthesis (combination) reactions: 2H₂ + O₂ → 2H₂O. Elements or compounds combine to form a single, more complex product.', 1),
    mc('What is a decomposition reaction?', ['Two compounds exchanging ions', 'One compound breaking down into two or more simpler substances', 'An element replacing another in a compound', 'A reaction producing heat and light'], 'One compound breaking down into two or more simpler substances', 'Decomposition: AB → A + B. Heat, electricity, or light often drives them. 2H₂O → 2H₂ + O₂ (electrolysis). Opposite of synthesis.', 2),
    mc('What is a single replacement (displacement) reaction?', ['Two compounds exchanging ions', 'One element replaces another element in a compound (A + BC → AC + B)', 'Two elements combining to form one compound', 'A compound breaking into elements'], 'One element replaces another element in a compound (A + BC → AC + B)', 'Zn + 2HCl → ZnCl₂ + H₂: zinc displaces hydrogen. More reactive elements displace less reactive ones — reactivity series determines if reaction occurs.', 3),
    mc('What is a double replacement reaction?', ['Both elements swap between two compounds (AB + CD → AD + CB)', 'One element replacing two in a compound', 'Two compounds forming one product', 'A reaction requiring a catalyst'], 'Both elements swap between two compounds (AB + CD → AD + CB)', 'NaCl + AgNO₃ → AgCl↓ + NaNO₃: sodium and silver exchange partners. Often produces a precipitate, gas, or water.', 4),
    mc('What is a combustion reaction?', ['A reaction that absorbs energy', 'A substance rapidly reacting with oxygen, releasing heat and light (usually CO₂ and H₂O for organic fuels)', 'Any reaction producing fire', 'A reaction between metals and acids'], 'A substance rapidly reacting with oxygen, releasing heat and light (usually CO₂ and H₂O for organic fuels)', 'Complete combustion of hydrocarbons: CH₄ + 2O₂ → CO₂ + 2H₂O. Incomplete combustion produces CO (carbon monoxide). Combustion is exothermic.', 5),
  ],
  'acids-and-bases': [
    mc('What is an acid according to the Arrhenius definition?', ['A substance that accepts protons', 'A substance that produces H⁺ ions when dissolved in water', 'A substance with pH above 7', 'A substance that produces OH⁻ ions'], 'A substance that produces H⁺ ions when dissolved in water', 'Arrhenius acids (HCl, H₂SO₄, HNO₃) release hydrogen ions in water. This lowers pH below 7 and creates the sour taste and corrosive properties of acids.', 1),
    mc('What is a base according to the Arrhenius definition?', ['A substance that produces H⁺ ions', 'A substance that produces OH⁻ (hydroxide) ions when dissolved in water', 'A substance with pH below 7', 'A substance with a sour taste'], 'A substance that produces OH⁻ (hydroxide) ions when dissolved in water', 'Arrhenius bases (NaOH, Ca(OH)₂) release hydroxide ions in water — raising pH above 7, creating slippery feeling and bitter taste.', 2),
    mc('What does the pH scale measure?', ['The concentration of OH⁻ ions', 'The concentration of H⁺ ions — lower pH = more acidic, higher pH = more basic', 'The strength of an ionic compound', 'The boiling point of a solution'], 'The concentration of H⁺ ions — lower pH = more acidic, higher pH = more basic', 'pH = -log[H⁺]. Scale 0-14: pH 7 is neutral (water), below 7 is acidic (lemon juice ~2), above 7 is basic (bleach ~13). Each unit = 10× difference.', 3),
    mc('What is neutralization?', ['An acid becoming neutral by itself', 'The reaction between an acid and a base to produce water and a salt', 'Removing ions from a solution', 'Adding water to dilute an acid'], 'The reaction between an acid and a base to produce water and a salt', 'HCl + NaOH → NaCl + H₂O: acid and base neutralize each other, forming a salt and water. The H⁺ from the acid combines with OH⁻ from the base.', 4),
    mc('What is a buffer solution?', ['A solution with pH = 7', 'A solution that resists changes in pH when small amounts of acid or base are added', 'A highly concentrated acid solution', 'A solution that neutralizes any acid completely'], 'A solution that resists changes in pH when small amounts of acid or base are added', 'Buffers (like blood\'s carbonate/bicarbonate system) maintain stable pH — critical for biological systems. Blood stays ~7.4 despite metabolic acids.', 5),
  ],
  'stoichiometry': [
    mc('What is stoichiometry?', ['The study of atomic structure', 'The calculation of quantities of reactants and products in chemical reactions using molar ratios', 'The naming of chemical compounds', 'The measurement of chemical reaction rates'], 'The calculation of quantities of reactants and products in chemical reactions using molar ratios', 'Stoichiometry uses balanced equations as ratio maps. 2H₂ + O₂ → 2H₂O: 2 moles H₂ react with 1 mole O₂ to produce 2 moles H₂O.', 1),
    mc('What is a mole in chemistry?', ['A small burrowing mammal used as a unit', '6.022 × 10²³ particles (Avogadro\'s number) — the counting unit for atoms and molecules', 'One gram of any substance', 'The smallest unit of a compound'], '6.022 × 10²³ particles (Avogadro\'s number) — the counting unit for atoms and molecules', 'A mole lets chemists count atoms by weighing. 1 mole of carbon = 12 grams = 6.022 × 10²³ atoms. Molar mass = grams per mole.', 2),
    mc('What is molar mass?', ['The mass of one atom in grams', 'The mass in grams of one mole of a substance — numerically equal to the sum of atomic masses', 'The density of a solution', 'The number of moles in a kilogram'], 'The mass in grams of one mole of a substance — numerically equal to the sum of atomic masses', 'H₂O molar mass = 2(1) + 16 = 18 g/mol. This converts between mass and moles, enabling real-world calculations.', 3),
    mc('What is the limiting reactant?', ['The reactant present in the smallest amount by mass', 'The reactant that is completely consumed first, limiting how much product can form', 'The most reactive chemical in a reaction', 'The chemical that determines reaction speed'], 'The reactant that is completely consumed first, limiting how much product can form', 'If you have excess flour but only 2 eggs and a recipe needs 3, eggs are the limiting reactant — you can only make 2/3 of a batch regardless of flour.', 4),
    mc('What is percent yield?', ['The purity of the reactants', '(Actual yield / Theoretical yield) × 100 — how close the actual product was to the predicted amount', 'The percentage of reactants that are limiting', 'The ratio of products to reactants by mass'], '(Actual yield / Theoretical yield) × 100 — how close the actual product was to the predicted amount', 'Theoretical yield is what stoichiometry predicts; actual yield is what you collect. Losses from incomplete reactions, side reactions, or transfer reduce yield below 100%.', 5),
  ],
  'kinematics': [
    mc('What is the difference between distance and displacement?', ['They are the same quantity', 'Distance is total path length (scalar); displacement is straight-line change in position with direction (vector)', 'Displacement is always larger than distance', 'Distance has direction; displacement does not'], 'Distance is total path length (scalar); displacement is straight-line change in position with direction (vector)', 'Run around a 400m track and return to start: distance = 400m, displacement = 0m. Displacement is \"as the crow flies\" with direction.', 1),
    mc('What is the difference between speed and velocity?', ['Speed is faster than velocity', 'Speed is how fast (scalar); velocity is speed with direction (vector)', 'Velocity is always greater than speed', 'Speed involves direction; velocity does not'], 'Speed is how fast (scalar); velocity is speed with direction (vector)', 'Speed = distance/time (no direction). Velocity = displacement/time (includes direction). You can have constant speed but changing velocity (circular motion).', 2),
    mc('What is acceleration?', ['The rate of change of distance', 'The rate of change of velocity — can involve speeding up, slowing down, or changing direction', 'Speed divided by time elapsed', 'Velocity multiplied by mass'], 'The rate of change of velocity — can involve speeding up, slowing down, or changing direction', 'Acceleration = Δv/Δt. A car turning at constant speed is still accelerating because direction changes. Braking is negative acceleration (deceleration).', 3),
    mc('An object in free fall near Earth\'s surface accelerates at approximately:', ['9.8 m/s in the direction of gravity', '9.8 m/s² downward', '10 m/s² upward', '0 m/s² if no air resistance'], '9.8 m/s² downward', 'Near Earth\'s surface, gravity accelerates all objects at g ≈ 9.8 m/s² regardless of mass (ignoring air resistance) — Galileo\'s key insight.', 4),
    mc('What does a velocity-time graph\'s slope represent?', ['Displacement', 'Acceleration', 'Speed', 'Distance'], 'Acceleration', 'Slope = rise/run = Δvelocity/Δtime = acceleration. A flat line = constant velocity (zero acceleration). The area under the v-t graph = displacement.', 5),
  ],
}
