import type { ExerciseDef } from '../types'

function mc(
  question: string,
  options: string[],
  correctAnswer: string,
  explanation: string,
  order: number
): ExerciseDef {
  return { question, type: 'MULTIPLE_CHOICE', options, correctAnswer, explanation, order }
}

export const sciencesExercises3: Record<string, ExerciseDef[]> = {
  'ecosystems': [
    mc('What is an ecosystem?', ['A group of organisms of the same species', 'A community of living organisms interacting with each other and their physical environment', 'The total number of species in a region', 'A single food chain'], 'A community of living organisms interacting with each other and their physical environment', 'Ecosystems include biotic factors (living organisms) and abiotic factors (temperature, water, soil, sunlight) that together form a functioning system.', 1),
    mc('What is a food web?', ['A single chain of who eats whom', 'An interconnected network of food chains showing feeding relationships in an ecosystem', 'The total energy in an ecosystem', 'The decomposition cycle'], 'An interconnected network of food chains showing feeding relationships in an ecosystem', 'Food webs show the complex feeding relationships — most organisms eat multiple species and are eaten by multiple predators, creating a web not a simple chain.', 2),
    mc('What is the role of decomposers in an ecosystem?', ['They are the top predators', 'They break down dead organic matter, returning nutrients to the soil', 'They convert sunlight to energy', 'They regulate predator-prey cycles'], 'They break down dead organic matter, returning nutrients to the soil', 'Bacteria and fungi decompose dead plants and animals, releasing nutrients (nitrogen, phosphorus) back into the soil — essential for nutrient cycling.', 3),
    mc('What happens to energy as it moves up trophic levels?', ['Energy increases at each level', 'About 90% of energy is lost at each transfer, leaving only ~10% for the next level', 'Energy remains constant', 'Energy doubles at each level'], 'About 90% of energy is lost at each transfer, leaving only ~10% for the next level', 'The 10% rule: most energy is lost as heat. This limits food chain length and explains why there are fewer top predators than prey animals.', 4),
    mc('What is a keystone species?', ['The most numerous species in an ecosystem', 'A species with a disproportionately large effect on ecosystem structure relative to its abundance', 'The species at the top of the food chain', 'The first producer in a food web'], 'A species with a disproportionately large effect on ecosystem structure relative to its abundance', 'Sea otters maintain kelp forests by eating sea urchins. Remove otters — urchins explode, kelp disappears, ecosystem collapses. Keystone species have outsized impact.', 5),
  ],
  'biodiversity': [
    mc('What is biodiversity?', ['The number of plants in a habitat', 'The variety of life — species, genetic, and ecosystem diversity — in a given area', 'The geographic range of a species', 'The total biomass of an ecosystem'], 'The variety of life — species, genetic, and ecosystem diversity — in a given area', 'Biodiversity has three levels: species diversity (number of species), genetic diversity (variation within species), and ecosystem diversity (variety of habitats).', 1),
    mc('Why is biodiversity important for ecosystems?', ['It makes ecosystems look attractive', 'Diverse ecosystems are more stable, resilient, and provide more ecosystem services', 'Higher biodiversity always means more food for humans', 'It prevents all natural disasters'], 'Diverse ecosystems are more stable, resilient, and provide more ecosystem services', 'Biodiversity provides resilience — if one species declines, others can fill its role. Monocultures are vulnerable; diverse systems buffer against disturbance.', 2),
    mc('What is a mass extinction?', ['When all organisms in one ecosystem die', 'A period when more than 75% of species disappear in a geologically short time', 'When a single species goes extinct', 'The gradual loss of biodiversity over millions of years'], 'A period when more than 75% of species disappear in a geologically short time', 'Earth has had five mass extinctions. We may be in the sixth — driven by habitat loss, climate change, and overexploitation rather than asteroid impact.', 3),
    mc('What is the leading cause of biodiversity loss today?', ['Natural climate cycles', 'Habitat destruction and fragmentation, primarily from human land use', 'Predation by invasive species only', 'Pollution from heavy metals'], 'Habitat destruction and fragmentation, primarily from human land use', 'Deforestation, agriculture, and urbanization destroy and fragment habitat — the primary driver of extinction. Species need space and connectivity to survive.', 4),
    mc('What is an invasive species?', ['Any non-native organism introduced to a region', 'A non-native species that spreads aggressively and harms native ecosystems', 'A species that preys on endangered species', 'A native species that suddenly increases in number'], 'A non-native species that spreads aggressively and harms native ecosystems', 'Invasive species lack natural predators in their new environment — they outcompete, prey on, or introduce disease to native species. Examples: kudzu, zebra mussels, cane toads.', 5),
  ],
  'atoms-and-elements': [
    mc('What is an atom?', ['The smallest particle of matter that can exist', 'The smallest unit of an element that retains that element\'s chemical properties', 'A molecule made of two elements', 'A charged particle in the nucleus'], 'The smallest unit of an element that retains that element\'s chemical properties', 'Atoms are the building blocks of matter. Each element has atoms with a unique number of protons — that number defines the element.', 1),
    mc('What are the three subatomic particles?', ['Electrons, neutrons, and photons', 'Protons, neutrons, and electrons', 'Protons, quarks, and electrons', 'Neutrons, bosons, and protons'], 'Protons, neutrons, and electrons', 'Protons (+) and neutrons (0) are in the nucleus; electrons (-) orbit in electron shells. Protons determine the element; electrons determine chemical behavior.', 2),
    mc('What is atomic number?', ['The number of neutrons in an atom', 'The number of protons in the nucleus — uniquely identifies the element', 'The total mass of the atom', 'The number of electron shells'], 'The number of protons in the nucleus — uniquely identifies the element', 'Every element has a unique atomic number. Carbon is always 6, oxygen always 8, gold always 79. Same protons = same element.', 3),
    mc('What is atomic mass?', ['The number of protons only', 'The approximate total of protons plus neutrons in the nucleus', 'The number of electrons', 'The weight of the atom in grams'], 'The approximate total of protons plus neutrons in the nucleus', 'Atomic mass ≈ protons + neutrons (electrons have negligible mass). Carbon-12 has 6 protons + 6 neutrons = mass 12.', 4),
    mc('How are elements organized on the periodic table?', ['By alphabetical name', 'By increasing atomic number, grouped by similar chemical properties in columns (groups)', 'By atomic mass only', 'By state of matter at room temperature'], 'By increasing atomic number, grouped by similar chemical properties in columns (groups)', 'The periodic table arranges elements by atomic number horizontally. Vertical groups share electron configurations and chemical behavior.', 5),
  ],
  'atomic-structure': [
    mc('Where is the majority of an atom\'s mass located?', ['In the electron cloud', 'In the nucleus (protons and neutrons)', 'Evenly distributed throughout', 'In the outermost electron shell'], 'In the nucleus (protons and neutrons)', 'The nucleus is tiny but dense — it contains nearly all the atom\'s mass. The electron cloud occupies most of the volume but has negligible mass.', 1),
    mc('What are valence electrons?', ['Electrons in the innermost shell', 'Electrons in the outermost shell that participate in chemical bonding', 'All electrons in an atom', 'Electrons that have been lost or gained'], 'Electrons in the outermost shell that participate in chemical bonding', 'Valence electrons determine how atoms bond. Elements in the same periodic table group have the same number of valence electrons and similar reactivity.', 2),
    mc('Why are noble gases (Group 18) largely unreactive?', ['They have too many protons', 'Their outer electron shells are completely full — they have no tendency to gain or lose electrons', 'They are gases at room temperature', 'They have no neutrons'], 'Their outer electron shells are completely full — they have no tendency to gain or lose electrons', 'Full valence shells (8 electrons — the octet rule) means noble gases are chemically stable. They don\'t readily form bonds with other elements.', 3),
    mc('What is an ion?', ['An atom with a different number of neutrons', 'An atom that has gained or lost electrons, giving it a net electrical charge', 'A radioactive form of an element', 'A molecule made of one element'], 'An atom that has gained or lost electrons, giving it a net electrical charge', 'Cations (+) lost electrons; anions (-) gained electrons. Na loses one electron → Na⁺. Cl gains one → Cl⁻. Oppositely charged ions attract to form ionic bonds.', 4),
    mc('What does the quantum mechanical model of the atom describe?', ['Electrons in fixed circular orbits like planets', 'The probability of finding electrons in specific regions around the nucleus (orbitals)', 'Electrons as solid particles attached to the nucleus', 'A nucleus with electrons evenly embedded (plum pudding)'], 'The probability of finding electrons in specific regions around the nucleus (orbitals)', 'Unlike Bohr\'s simple orbits, quantum mechanics describes electron clouds — orbitals where electrons have a high probability of being found, not fixed paths.', 5),
  ],
  'electron-configuration': [
    mc('What does electron configuration describe?', ['The number of neutrons in an atom', 'How electrons are distributed across an atom\'s energy levels and orbitals', 'The charge of an ion', 'The atom\'s position on the periodic table'], 'How electrons are distributed across an atom\'s energy levels and orbitals', 'Electron configuration specifies which shells and subshells electrons occupy — e.g., carbon is 1s² 2s² 2p². It determines chemical behavior.', 1),
    mc('What is the Aufbau principle?', ['Electrons fill orbitals with the highest energy first', 'Electrons fill orbitals starting with the lowest energy available', 'Two electrons in the same orbital must have opposite spins', 'Electrons spread into empty orbitals before pairing'], 'Electrons fill orbitals starting with the lowest energy available', 'Aufbau (German: "building up") — electrons occupy the lowest energy orbitals first: 1s before 2s before 2p, etc.', 2),
    mc('What does the Pauli Exclusion Principle state?', ['Electrons must fill all orbitals singly before pairing', 'No two electrons in an atom can have the same set of four quantum numbers — each orbital holds at most two electrons with opposite spins', 'Electrons always fill the lowest energy level first', 'Atoms cannot have more than 8 electrons'], 'No two electrons in an atom can have the same set of four quantum numbers — each orbital holds at most two electrons with opposite spins', 'The Pauli Exclusion Principle limits orbitals to two electrons, and they must spin in opposite directions.', 3),
    mc('Why do elements in the same group have similar properties?', ['They have the same atomic mass', 'They have the same number of valence electrons in their outermost shell', 'They were discovered at the same time', 'They have the same number of neutrons'], 'They have the same number of valence electrons in their outermost shell', 'Group 1 elements all have one valence electron — they all readily lose it to form +1 ions and react similarly with water and halogens.', 4),
    mc('How many electrons can the first electron shell hold?', ['8', '2', '18', '4'], '2', 'The first shell (n=1) contains only the 1s orbital, which holds a maximum of 2 electrons. Hydrogen has 1; helium has 2 (full first shell).', 5),
  ],
  'isotopes-and-radioactivity': [
    mc('What are isotopes?', ['Atoms of different elements with the same mass number', 'Atoms of the same element with different numbers of neutrons', 'Ions of the same element with different charges', 'Molecules with the same formula but different structure'], 'Atoms of the same element with different numbers of neutrons', 'Isotopes share the same atomic number (same element) but differ in neutron count — e.g., Carbon-12 (6 neutrons) and Carbon-14 (8 neutrons).', 1),
    mc('What is radioactive decay?', ['An element changing into an ion', 'The spontaneous emission of particles or energy from an unstable atomic nucleus', 'Electrons falling to lower energy levels', 'The breakdown of molecules in a chemical reaction'], 'The spontaneous emission of particles or energy from an unstable atomic nucleus', 'Unstable nuclei decay by emitting alpha particles, beta particles, or gamma rays — transforming into a more stable element or isotope.', 2),
    mc('What is half-life?', ['The time for half the atoms in a sample to undergo radioactive decay', 'Half the mass of a radioactive element', 'The time for radioactivity to become safe', 'The average lifespan of a radioactive particle'], 'The time for half the atoms in a sample to undergo radioactive decay', 'Half-life is constant for each radioisotope. After one half-life, 50% remains; after two, 25%; etc. Used in carbon dating and nuclear medicine.', 3),
    mc('What is carbon-14 dating used for?', ['Dating rocks billions of years old', 'Determining the age of organic materials up to ~50,000 years old', 'Tracking nuclear waste', 'Measuring radiation in hospitals'], 'Determining the age of organic materials up to ~50,000 years old', 'Living organisms have a constant C-14/C-12 ratio. After death, C-14 decays (half-life ~5,730 years). The ratio remaining gives age — used to date fossils, artifacts, and wood.', 4),
    mc('What is the difference between alpha, beta, and gamma radiation?', ['They differ only in energy level', 'Alpha = helium nuclei (low penetration); beta = electrons/positrons (medium); gamma = high-energy photons (most penetrating)', 'Beta is most dangerous; gamma least', 'Alpha is fastest; gamma slowest'], 'Alpha = helium nuclei (low penetration); beta = electrons/positrons (medium); gamma = high-energy photons (most penetrating)', 'Alpha is blocked by paper; beta by aluminum; gamma requires lead or thick concrete. Gamma is most penetrating and ionizing at a distance.', 5),
  ],
  'ionic-bonds': [
    mc('What is an ionic bond?', ['Sharing of electrons between two atoms', 'The electrostatic attraction between oppositely charged ions', 'A bond formed by two nonmetals', 'A weak attraction between molecules'], 'The electrostatic attraction between oppositely charged ions', 'Ionic bonds form when a metal transfers electrons to a nonmetal — metal becomes cation (+), nonmetal becomes anion (-). Opposite charges attract.', 1),
    mc('Which type of elements typically form ionic bonds?', ['Two nonmetals', 'Two metals', 'A metal and a nonmetal', 'Noble gases with nonmetals'], 'A metal and a nonmetal', 'Metals (low electronegativity) donate electrons; nonmetals (high electronegativity) accept them. NaCl: Na gives its electron to Cl.', 2),
    mc('What properties do ionic compounds typically have?', ['Low melting points and poor conductivity in all states', 'High melting points, brittle crystalline solids, conduct electricity when dissolved or melted', 'Gases at room temperature', 'Flexible and malleable like metals'], 'High melting points, brittle crystalline solids, conduct electricity when dissolved or melted', 'Strong electrostatic forces require much heat to break (high mp). The crystal lattice shatters under stress (brittle). Dissolved ions carry current.', 3),
    mc('Why do atoms form ions?', ['To increase their atomic mass', 'To achieve a full outer electron shell (octet), which is a more stable configuration', 'To become neutral', 'Because electrons move randomly'], 'To achieve a full outer electron shell (octet), which is a more stable configuration', 'The octet rule: atoms gain or lose electrons to achieve 8 valence electrons (like noble gases). Na loses 1 → stable 8. Cl gains 1 → stable 8.', 4),
    mc('What is the formula for calcium chloride?', ['CaCl', 'Ca₂Cl', 'CaCl₂', 'Ca₂Cl₃'], 'CaCl₂', 'Ca²⁺ has charge +2; Cl⁻ has charge -1. To balance, you need 2 Cl⁻ for every Ca²⁺. Ionic compounds must be electrically neutral.', 5),
  ],
}
