import type { ExerciseDef } from '../types'

function mc(
  question: string,
  options: string[],
  correctAnswer: string,
  explanation: string,
  order: number
): ExerciseDef {
  return { question, type: 'MULTIPLE_CHOICE', options, correctAnswer, explanation, order }
}

export const sciencesExercises7: Record<string, ExerciseDef[]> = {
  'human-environmental-impact': [
    mc('What is the primary driver of species extinction today?', ['Climate change alone', 'Habitat destruction from human land use — agriculture, deforestation, and urbanization', 'Pollution only', 'Invasive species alone'], 'Habitat destruction from human land use — agriculture, deforestation, and urbanization', 'Habitat loss affects more species than any other threat. 75% of land and 66% of oceans have been significantly altered by humans since pre-industrial times.', 1),
    mc('What is the nitrogen cycle and why does agricultural runoff disrupt it?', ['Nitrogen is just a greenhouse gas; farming adds too much', 'Nitrogen cycles from atmosphere through soil, plants, and animals; fertilizer runoff adds excess nitrogen to waterways causing algal blooms and dead zones', 'Agricultural runoff is actually beneficial to nitrogen cycling', 'Nitrogen cycle is only relevant in oceans'], 'Nitrogen cycles from atmosphere through soil, plants, and animals; fertilizer runoff adds excess nitrogen to waterways causing algal blooms and dead zones', 'Eutrophication: excess N and P from fertilizers cause algal blooms that deplete oxygen when they decompose, creating hypoxic dead zones (Gulf of Mexico, Chesapeake Bay).', 2),
    mc('What is deforestation\'s impact on climate?', ['Forests absorb CO₂, so removing them reduces the carbon sink and releases stored carbon', 'Forests don\'t significantly affect climate', 'Deforestation actually cools the planet by reducing evapotranspiration', 'Deforestation only affects local climate, not global'], 'Forests absorb CO₂, so removing them reduces the carbon sink and releases stored carbon', 'Forests store ~45% of terrestrial carbon. Deforestation (often with burning) releases stored CO₂ and removes ongoing carbon absorption — contributes ~10-15% of global emissions.', 3),
    mc('What is plastic pollution\'s primary environmental harm?', ['It dissolves and poisons soil quickly', 'Plastic persists for centuries, accumulates in food chains (microplastics), entangles wildlife, and concentrates toxins', 'It only harms ocean surface life', 'Plastic breaks down quickly in sunlight'], 'Plastic persists for centuries, accumulates in food chains (microplastics), entangles wildlife, and concentrates toxins', 'Plastic fragments into microplastics ingested by marine life up the food chain. Ocean gyres concentrate plastic into vast patches. ~8 million tons enter oceans annually.', 4),
    mc('What does "sustainability" mean in environmental context?', ['Using resources as fast as possible', 'Meeting present needs without compromising future generations\' ability to meet their needs', 'Stopping all economic development', 'Protecting all species regardless of economic impact'], 'Meeting present needs without compromising future generations\' ability to meet their needs', 'Brundtland Commission definition (1987): sustainable development balances economic, social, and environmental goals so present use doesn\'t deplete resources for the future.', 5),
  ],
  'the-sun': [
    mc('What type of star is our Sun?', ['A red giant', 'A yellow dwarf (G-type main sequence star)', 'A white dwarf', 'A neutron star'], 'A yellow dwarf (G-type main sequence star)', 'The Sun is a G-type main sequence star — average size, temperature, and luminosity. It\'s in the stable "main sequence" phase of hydrogen fusion, with ~5 billion years left.', 1),
    mc('What process powers the Sun?', ['Chemical combustion of hydrogen', 'Nuclear fusion — hydrogen nuclei fuse into helium, releasing enormous energy', 'Nuclear fission splitting heavy atoms', 'Gravitational compression generating heat'], 'Nuclear fusion — hydrogen nuclei fuse into helium, releasing enormous energy', 'The proton-proton chain: 4H → He + energy (E=mc²). The Sun converts ~4 million tons of mass to energy per second. Core temperature: ~15 million°C.', 2),
    mc('What are sunspots?', ['Dark spots caused by solar flares hitting Earth', 'Temporarily cooler, darker regions on the Sun\'s surface caused by concentrated magnetic field activity', 'Areas where the Sun is burning out', 'Shadows cast by passing planets'], 'Temporarily cooler, darker regions on the Sun\'s surface caused by concentrated magnetic field activity', 'Sunspots are ~4,000°C vs surrounding ~5,500°C photosphere — cooler so appear dark. They follow an 11-year cycle and are associated with solar flares and CMEs.', 3),
    mc('How does energy travel from the Sun\'s core to its surface?', ['Only by convection', 'First by radiation (photons absorb/re-emit over ~100,000 years) through the radiative zone, then by convection through the convective zone', 'Directly by conduction through solid layers', 'Only through solar wind channels'], 'First by radiation (photons absorb/re-emit over ~100,000 years) through the radiative zone, then by convection through the convective zone', 'A photon generated in the core takes ~100,000 years to random-walk through the dense radiative zone to the convective zone where hot plasma physically rises.', 4),
    mc('What is the solar wind?', ['Winds on the Sun\'s surface moving gas around', 'A continuous stream of charged particles (mostly protons and electrons) ejected from the Sun\'s corona', 'Radiation from solar flares only', 'The movement of the Sun through the Milky Way'], 'A continuous stream of charged particles (mostly protons and electrons) ejected from the Sun\'s corona', 'Solar wind streams at 400-800 km/s. It shapes planetary magnetospheres, causes auroras, and would strip Earth\'s atmosphere without our magnetic field.', 5),
  ],
  'planets': [
    mc('What distinguishes a planet from a dwarf planet?', ['Planets are larger than dwarf planets', 'A planet orbits the Sun, has enough gravity to be roughly spherical, AND has cleared its orbital neighborhood of other debris', 'A planet must have a moon', 'Only size matters — nothing else'], 'A planet orbits the Sun, has enough gravity to be roughly spherical, AND has cleared its orbital neighborhood of other debris', 'IAU 2006 definition removed Pluto: it hasn\'t cleared its orbital neighborhood (shares space with Kuiper Belt objects). The 8 planets all satisfy all three criteria.', 1),
    mc('What are the terrestrial planets?', ['Jupiter, Saturn, Uranus, Neptune', 'Mercury, Venus, Earth, Mars', 'Earth, Mars, Jupiter, Saturn', 'All planets inside the asteroid belt including Jupiter'], 'Mercury, Venus, Earth, Mars', 'Terrestrial (rocky) planets: small, dense, solid surfaces, few moons, no rings. Gas giants (Jupiter, Saturn) and ice giants (Uranus, Neptune) are much larger and gas/ice dominated.', 2),
    mc('Why is Venus the hottest planet despite Mercury being closer to the Sun?', ['Venus is actually closer to the Sun on average', 'Venus has a thick CO₂ atmosphere creating an extreme greenhouse effect, raising surface temperature to ~462°C', 'Mercury reflects sunlight better', 'Venus rotates faster, generating more internal heat'], 'Venus has a thick CO₂ atmosphere creating an extreme greenhouse effect, raising surface temperature to ~462°C', 'Venus\'s 96% CO₂ atmosphere creates a runaway greenhouse effect — surface temperature exceeds Mercury\'s despite being farther from the Sun. Atmospheric pressure is 90× Earth\'s.', 3),
    mc('What is the asteroid belt?', ['A belt of asteroids between Earth and Mars', 'A region between Mars and Jupiter\'s orbits containing millions of rocky bodies', 'A ring system around Jupiter', 'Debris left from a destroyed planet between Saturn and Uranus'], 'A region between Mars and Jupiter\'s orbits containing millions of rocky bodies', 'The asteroid belt contains remnant planetesimals from the solar system\'s formation — Jupiter\'s gravity prevented them from forming a planet. Ceres is the largest (now a dwarf planet).', 4),
    mc('What makes Jupiter unique among planets?', ['It is the smallest planet', 'It is the largest planet — more massive than all other planets combined — with a powerful magnetic field and dozens of moons', 'It is the only gas planet with rings', 'It is closest to the Sun of the gas giants'], 'It is the largest planet — more massive than all other planets combined — with a powerful magnetic field and dozens of moons', 'Jupiter has 2.5× the mass of all other planets combined. Its Great Red Spot is a storm larger than Earth that has persisted for centuries. It has 95 known moons including volcanic Io and icy Europa.', 5),
  ],
  'moons-and-asteroids': [
    mc('What is the leading theory for how Earth\'s Moon formed?', ['Captured from the asteroid belt', 'A Mars-sized body (Theia) collided with early Earth; the debris coalesced into the Moon', 'Formed at the same time as Earth from the same material', 'Broke off from Earth due to rapid early rotation'], 'A Mars-sized body (Theia) collided with early Earth; the debris coalesced into the Moon', 'The Giant Impact Hypothesis explains the Moon\'s composition (similar to Earth\'s mantle), its large size relative to Earth, and its lack of a substantial iron core.', 1),
    mc('How does Earth\'s Moon affect Earth?', ['Only through causing eclipses', 'It stabilizes Earth\'s axial tilt, drives tides, and gradually slows Earth\'s rotation', 'It reflects enough light to significantly warm nights', 'It shields Earth from all asteroid impacts'], 'It stabilizes Earth\'s axial tilt, drives tides, and gradually slows Earth\'s rotation', 'The Moon\'s gravity stabilizes Earth\'s tilt (~23.5°) preventing chaotic variations. Tides result from differential gravitational pull. Tidal braking slows Earth\'s rotation ~1.4ms per century.', 2),
    mc('What causes tides on Earth?', ['The Sun\'s gravity only', 'The Moon\'s gravitational pull differentially attracting the near side of Earth more than the center more than the far side', 'Earth\'s rotation alone', 'Tidal forces from all planets combined'], 'The Moon\'s gravitational pull differentially attracting the near side of Earth more than the center more than the far side', 'Tidal force = differential gravity. The Moon pulls the near ocean more than Earth\'s center more than the far ocean — creating two tidal bulges on opposite sides. Two high tides per day.', 3),
    mc('What is the difference between a meteor, meteoroid, and meteorite?', ['They are different sizes of the same thing', 'Meteoroid: space rock in space; meteor: the light flash as it burns in atmosphere; meteorite: what lands on Earth\'s surface', 'Meteors are larger than meteoroids', 'Meteorites only come from the asteroid belt'], 'Meteoroid: space rock in space; meteor: the light flash as it burns in atmosphere; meteorite: what lands on Earth\'s surface', 'Simple memory tool: meteoroid = rock in space, meteor = "shooting star" (burning), meteorite = "made it" to Earth\'s surface.', 4),
    mc('What are comets composed of?', ['Pure rock and iron like asteroids', 'Ice, dust, and rocky material — they develop a glowing coma and tail when near the Sun as ice vaporizes', 'Gases compressed into a small body', 'Fragments of destroyed planets'], 'Ice, dust, and rocky material — they develop a glowing coma and tail when near the Sun as ice vaporizes', 'Comets are "dirty snowballs" from the Kuiper Belt or Oort Cloud. Solar wind pushes the tail away from the Sun — so the tail leads when a comet moves away from the Sun.', 5),
  ],
  'stars-and-stellar-evolution': [
    mc('How are stars classified?', ['By their position in the sky', 'By surface temperature and luminosity, from hottest/most luminous (O, B, A) to coolest/dimmest (K, M)', 'By size only', 'By their age'], 'By surface temperature and luminosity, from hottest/most luminous (O, B, A) to coolest/dimmest (K, M)', 'The spectral classification OBAFGKM (mnemonics: "Oh Be A Fine Guy/Girl, Kiss Me"). The Sun is G-type — middle temperature and luminosity. O stars are blue-white; M stars are red dwarfs.', 1),
    mc('What is the main sequence of stellar evolution?', ['The path a star takes across the sky', 'The longest phase of a star\'s life when it fuses hydrogen in its core — a stable equilibrium of gravity and radiation pressure', 'The final stages before a supernova', 'The sequence from nebula to white dwarf'], 'The longest phase of a star\'s life when it fuses hydrogen in its core — a stable equilibrium of gravity and radiation pressure', 'Stars spend most of their lives on the main sequence (the Sun has ~10 billion years total). Mass determines position, temperature, and how long the star lives.', 2),
    mc('What happens to a star like our Sun after the main sequence?', ['It explodes as a supernova', 'It expands into a red giant, then sheds its outer layers as a planetary nebula, leaving a white dwarf', 'It collapses into a neutron star', 'It simply fades and cools in place'], 'It expands into a red giant, then sheds its outer layers as a planetary nebula, leaving a white dwarf', 'When core hydrogen is exhausted, the Sun will swell to ~200× current size (red giant), then gently eject its outer layers. The remnant core — a white dwarf — will slowly cool over billions of years.', 3),
    mc('What is a supernova?', ['Any exploding star regardless of mass', 'The catastrophic explosion of a massive star (≥8 solar masses) at the end of its life, briefly outshining entire galaxies', 'The explosion of a Sun-like star when it becomes a red giant', 'A star collision with another star'], 'The catastrophic explosion of a massive star (≥8 solar masses) at the end of its life, briefly outshining entire galaxies', 'Massive stars fuse elements up to iron (which doesn\'t release energy). The iron core collapses, rebounds, and explodes — seeding space with heavy elements (gold, platinum, uranium).', 4),
    mc('What is a black hole?', ['A dark region of space with no matter', 'An object so massive that its escape velocity exceeds the speed of light — nothing, not even light, can escape', 'A collapsed neutron star of any size', 'A very dense cold star'], 'An object so massive that its escape velocity exceeds the speed of light — nothing, not even light, can escape', 'Black holes form when massive stars (>20 solar masses) collapse. The event horizon is the point of no return. Black holes can be observed by their gravitational effects on nearby matter.', 5),
  ],
  'galaxies': [
    mc('What is the Milky Way?', ['The name for our solar system', 'The spiral galaxy containing our solar system, with ~200-400 billion stars', 'The nearest galaxy to Earth', 'The observable universe'], 'The spiral galaxy containing our solar system, with ~200-400 billion stars', 'The Milky Way is a barred spiral galaxy ~100,000 light-years across. Our solar system is located ~26,000 light-years from the galactic center in one of the spiral arms.', 1),
    mc('What are the main types of galaxies?', ['Circular, oval, and irregular', 'Spiral (including barred spiral), elliptical, and irregular', 'Young, middle-aged, and old', 'Small, medium, and large'], 'Spiral (including barred spiral), elliptical, and irregular', 'Spiral galaxies (like Milky Way, Andromeda) have spiral arms with active star formation. Ellipticals are large, old, star-formation complete. Irregulars lack organized structure.', 2),
    mc('What is dark matter?', ['Matter inside black holes', 'Invisible matter that doesn\'t interact with light but exerts gravitational effects — comprises ~27% of the universe\'s mass-energy', 'Cold, dark regions of space with no stars', 'Matter too far away to observe'], 'Invisible matter that doesn\'t interact with light but exerts gravitational effects — comprises ~27% of the universe\'s mass-energy', 'Galaxies rotate too fast and cluster too strongly for visible matter alone to explain. Dark matter\'s gravitational effects are real and measurable, but its nature is unknown.', 3),
    mc('What is the Local Group?', ['The name for our solar neighborhood', 'The cluster of ~50 galaxies including the Milky Way and Andromeda that are gravitationally bound together', 'All galaxies within 1 billion light-years', 'The inner part of the Milky Way'], 'The cluster of ~50 galaxies including the Milky Way and Andromeda that are gravitationally bound together', 'The Local Group spans ~10 million light-years. The Milky Way and Andromeda (M31) are the two largest members. Andromeda is approaching — will merge with the Milky Way in ~4.5 billion years.', 4),
    mc('What causes galaxies to appear to be moving away from us in all directions?', ['The Milky Way is at the center of the universe pushing things away', 'Space itself is expanding — galaxies are carried apart as the fabric of spacetime grows', 'Galaxies have their own propulsion', 'The Big Bang pushed all matter outward from Earth'], 'Space itself is expanding — galaxies are carried apart as the fabric of spacetime grows', 'Hubble\'s Law: the universe is expanding. Galaxies aren\'t moving through space; space itself is expanding, carrying galaxies apart. This expansion is accelerating due to dark energy.', 5),
  ],
  'the-big-bang': [
    mc('What is the Big Bang theory?', ['A theory that the universe exploded from a single point and has been expanding ever since', 'A theory that the universe has always existed in its current state', 'A theory about how stars explode', 'A model of how planets form from stellar explosions'], 'A theory that the universe exploded from a single point and has been expanding ever since', 'The Big Bang (~13.8 billion years ago) was not an explosion in space but an expansion of space itself from an extremely hot, dense state. All matter, energy, space, and time originated from it.', 1),
    mc('What are the main pieces of evidence for the Big Bang?', ['Only the expansion of galaxies', 'Cosmic Microwave Background radiation, the observed expansion of the universe, and the abundance of light elements (H, He, Li)', 'Telescope observations of the explosion directly', 'Only the age of stars'], 'Cosmic Microwave Background radiation, the observed expansion of the universe, and the abundance of light elements (H, He, Li)', 'Three pillars: Hubble expansion (Hubble, 1929), CMB (Penzias & Wilson, 1965 — the afterglow of the Big Bang), and Big Bang nucleosynthesis predicting the observed H/He ratio.', 2),
    mc('What is the Cosmic Microwave Background (CMB)?', ['Radiation from distant galaxies', 'The faint afterglow of light from the early universe — thermal radiation left over from ~380,000 years after the Big Bang', 'Microwave emissions from the Milky Way center', 'Radiation from the first stars'], 'The faint afterglow of light from the early universe — thermal radiation left over from ~380,000 years after the Big Bang', 'When the universe cooled enough for atoms to form, photons decoupled from matter and have been traveling ever since. The CMB fills all of space uniformly — detected as microwave radiation.', 3),
    mc('What is dark energy?', ['Energy inside black holes', 'A mysterious force driving the accelerating expansion of the universe — constitutes ~68% of total mass-energy', 'Dark matter converted to energy', 'The energy released by supernovae'], 'A mysterious force driving the accelerating expansion of the universe — constitutes ~68% of total mass-energy', 'Discovered 1998: distant supernovae are dimmer than expected — the universe\'s expansion is accelerating. Dark energy (cosmological constant?) drives this but its nature is unknown.', 4),
    mc('How old is the universe?', ['~4.6 billion years', '~13.8 billion years', '~100 billion years', '~1 billion years'], '~13.8 billion years', 'Based on CMB data (Planck satellite), the Big Bang occurred ~13.8 billion years ago. Earth formed 4.6 billion years ago. The universe was ~9 billion years old when our solar system formed.', 5),
  ],
  'space-exploration': [
    mc('What was Sputnik?', ['The first human in space', 'The first artificial satellite, launched by the Soviet Union in 1957', 'The first Moon landing mission', 'The first American satellite'], 'The first artificial satellite, launched by the Soviet Union in 1957', 'Sputnik 1 (October 4, 1957) shocked the world as the first object placed in Earth orbit. It triggered the Space Race and massive investment in science education in the US.', 1),
    mc('What was the significance of Apollo 11?', ['First satellite in orbit', 'First humans to land on the Moon (Neil Armstrong and Buzz Aldrin, July 20, 1969)', 'First space station', 'First Mars rover'], 'First humans to land on the Moon (Neil Armstrong and Buzz Aldrin, July 20, 1969)', 'Apollo 11 fulfilled Kennedy\'s 1961 challenge. Armstrong\'s words: "That\'s one small step for [a] man, one giant leap for mankind." Six Apollo missions landed on the Moon in total.', 2),
    mc('What are space probes used for?', ['Carrying astronauts to distant planets', 'Unmanned spacecraft sent to study planets, moons, comets, and other objects — transmitting data back to Earth', 'Mining asteroids for resources', 'Testing spacecraft systems before crewed missions'], 'Unmanned spacecraft sent to study planets, moons, comets, and other objects — transmitting data back to Earth', 'Probes (Voyager, Cassini, New Horizons) can survive conditions and distances impossible for humans. Voyager 1 (launched 1977) has now left the solar system.', 3),
    mc('What is the James Webb Space Telescope designed to observe?', ['Visible light from nearby stars', 'Infrared light — allowing it to see the earliest galaxies, see through dust clouds, and study exoplanet atmospheres', 'Only the solar system\'s planets', 'Radio waves from black holes'], 'Infrared light — allowing it to see the earliest galaxies, see through dust clouds, and study exoplanet atmospheres', 'JWST (launched 2021) observes in infrared, which penetrates cosmic dust and detects redshifted light from the earliest galaxies (>13 billion years old). 100× more powerful than Hubble.', 4),
    mc('What are exoplanets?', ['Planets outside our solar system orbiting other stars', 'Dwarf planets like Pluto in our solar system', 'Moons of gas giants', 'Rogue planets with no star'], 'Planets outside our solar system orbiting other stars', 'Over 5,500 exoplanets have been confirmed (2024). Detection methods: transit (star dims slightly), radial velocity (star wobbles). Some exoplanets are in habitable zones of their stars.', 5),
  ],
}
