import type { ExerciseDef } from '../types'

function mc(
  question: string,
  options: string[],
  correctAnswer: string,
  explanation: string,
  order: number
): ExerciseDef {
  return { question, type: 'MULTIPLE_CHOICE', options, correctAnswer, explanation, order }
}

export const sciencesExercises6: Record<string, ExerciseDef[]> = {
  'earth-layers': [
    mc('What are the four main layers of Earth from surface to center?', ['Soil, rock, magma, iron', 'Crust, mantle, outer core, inner core', 'Crust, lithosphere, asthenosphere, core', 'Sediment, bedrock, magma, metal'], 'Crust, mantle, outer core, inner core', 'Earth\'s layers: thin crust (continental/oceanic), thick solid mantle (with a partially molten asthenosphere), liquid outer core, and solid inner core of iron and nickel.', 1),
    mc('Why is Earth\'s outer core liquid while the inner core is solid?', ['The inner core is cooler', 'Pressure in the inner core is so extreme that iron solidifies despite the heat; the outer core has less pressure so iron remains liquid', 'The outer core has different composition', 'Temperature is the only factor — the outer core is hotter'], 'Pressure in the inner core is so extreme that iron solidifies despite the heat; the outer core has less pressure so iron remains liquid', 'The inner core is actually hotter than the outer core, but immense pressure (360 GPa) forces iron into solid form. Pressure raises melting point.', 2),
    mc('What is the asthenosphere?', ['The outer layer of Earth where weather occurs', 'A partially molten, ductile layer of the upper mantle on which tectonic plates move', 'The boundary between crust and mantle', 'The liquid outer core'], 'A partially molten, ductile layer of the upper mantle on which tectonic plates move', 'The asthenosphere (100-700 km deep) is semi-molten rock — solid enough to transmit seismic waves but ductile enough for plates to slowly slide over it.', 3),
    mc('How do scientists know what\'s inside Earth\'s interior?', ['By drilling to the core', 'By analyzing seismic waves (P and S waves) that travel through Earth differently based on material', 'By measuring volcanic eruptions', 'By theoretical models only — we can\'t know for certain'], 'By analyzing seismic waves (P and S waves) that travel through Earth differently based on material', 'P-waves (compressional) travel through solids and liquids; S-waves (shear) travel only through solids. S-waves stop at the outer core — revealing it\'s liquid.', 4),
    mc('What generates Earth\'s magnetic field?', ['The solid iron inner core spinning', 'Convection of liquid iron in the outer core creates a dynamo effect', 'The Sun\'s solar wind interacting with Earth', 'Magnetic minerals in the crust'], 'Convection of liquid iron in the outer core creates a dynamo effect', 'Moving liquid iron in the outer core (combined with Earth\'s rotation) generates electric currents that produce Earth\'s magnetic field — the magnetosphere that shields us from solar wind.', 5),
  ],
  'plate-tectonics': [
    mc('What is the theory of plate tectonics?', ['Earth\'s crust is a single continuous shell', 'Earth\'s lithosphere is divided into moving plates whose interactions cause earthquakes, volcanoes, and mountain building', 'Continental positions have never changed', 'Continents drift due to ocean tides'], 'Earth\'s lithosphere is divided into moving plates whose interactions cause earthquakes, volcanoes, and mountain building', 'Plate tectonics (1960s consensus) explains how lithospheric plates move, driven by mantle convection — unifying continental drift, seafloor spreading, and seismic/volcanic activity.', 1),
    mc('What happens at a convergent plate boundary?', ['Plates move apart, creating new crust', 'Plates move toward each other — one subducts beneath the other, or they collide forming mountains', 'Plates slide horizontally past each other', 'Plates create oceanic ridges'], 'Plates move toward each other — one subducts beneath the other, or they collide forming mountains', 'Oceanic-continental convergence: denser oceanic plate subducts, creating trenches and volcanoes. Continental-continental: plates crumple upward forming mountains (Himalayas = India + Asia).', 2),
    mc('What happens at a divergent plate boundary?', ['Plates collide forming mountains', 'Plates move apart; magma rises to create new oceanic crust (seafloor spreading)', 'One plate slides under the other', 'Plates lock together causing major earthquakes'], 'Plates move apart; magma rises to create new oceanic crust (seafloor spreading)', 'At mid-ocean ridges (like the Mid-Atlantic Ridge), plates separate, magma fills the gap, and new seafloor is created. Iceland sits on this ridge.', 3),
    mc('What is subduction?', ['When two plates collide and fold upward', 'When a denser plate slides under a less dense plate and sinks into the mantle', 'When plates slide horizontally', 'The creation of new oceanic crust'], 'When a denser plate slides under a less dense plate and sinks into the mantle', 'Oceanic crust is denser than continental — it subducts under continental plates. The descending slab melts, producing magma that can erupt as volcanoes above the subduction zone.', 4),
    mc('What was the evidence for Alfred Wegener\'s continental drift hypothesis?', ['GPS measurements showing continents moving', 'Matching coastlines, identical fossils on separate continents, and matching rock formations across oceans', 'Volcanic activity patterns only', 'Earthquake locations along ocean ridges'], 'Matching coastlines, identical fossils on separate continents, and matching rock formations across oceans', 'Wegener noted: Africa and South America fit together, Mesosaurus fossils found only on both sides of Atlantic, and matching Appalachian-Caledonian rock formations.', 5),
  ],
  'rocks-and-minerals': [
    mc('What is the difference between a rock and a mineral?', ['Rocks are harder than minerals', 'Minerals are naturally occurring inorganic solids with a defined composition; rocks are aggregates of one or more minerals', 'Minerals are only found underground; rocks are on the surface', 'They are the same thing with different names'], 'Minerals are naturally occurring inorganic solids with a defined composition; rocks are aggregates of one or more minerals', 'Quartz, feldspar, and mica are minerals. Granite is a rock composed of those minerals. Minerals have fixed chemical formulas; rocks are mixtures.', 1),
    mc('What is an igneous rock?', ['Rock formed from compressed sediment', 'Rock formed from the cooling and solidification of magma or lava', 'Rock transformed by heat and pressure', 'Rock formed from organic material'], 'Rock formed from the cooling and solidification of magma or lava', 'Intrusive igneous (granite): magma cools slowly underground — large crystals. Extrusive igneous (basalt, obsidian): lava cools quickly at surface — small crystals or glassy.', 2),
    mc('What is a sedimentary rock?', ['Rock formed from solidified magma', 'Rock formed from compressed and cemented sediment (particles, shells, or minerals)', 'Rock changed by heat and pressure', 'Any rock found near river beds'], 'Rock formed from compressed and cemented sediment (particles, shells, or minerals)', 'Sandstone, limestone, and shale are sedimentary. Sediment accumulates in layers (strata), is buried, compressed, and cemented over time. Fossils are found in sedimentary rock.', 3),
    mc('What is a metamorphic rock?', ['Rock that has been eroded by water', 'Rock that has been transformed by intense heat and/or pressure without melting', 'Rock formed from cooling lava', 'Rock created by volcanic ash'], 'Rock that has been transformed by intense heat and/or pressure without melting', 'Limestone → marble; shale → slate; granite → gneiss under heat and pressure. Metamorphism occurs deep in crust during mountain building or near magma intrusions.', 4),
    mc('What is the rock cycle?', ['The process by which rocks orbit around mountain peaks', 'The continuous transformation of rocks between igneous, sedimentary, and metamorphic forms over geologic time', 'The seasonal weathering of rock surfaces', 'A theory about how minerals form'], 'The continuous transformation of rocks between igneous, sedimentary, and metamorphic forms over geologic time', 'Rocks continuously cycle: magma cools to igneous → erodes to sediment → sedimentary rock → metamorphosed → melts to magma again. No rock type is permanent.', 5),
  ],
  'earthquakes-and-volcanoes': [
    mc('What causes earthquakes?', ['Underground explosions from compressed rock', 'Sudden release of energy from stress built up along faults as tectonic plates move', 'Volcanic eruptions underground', 'Rapid temperature changes in the crust'], 'Sudden release of energy from stress built up along faults as tectonic plates move', 'Plates lock together due to friction; stress builds; when it exceeds friction, they slip suddenly — releasing energy as seismic waves. The focus is the point of rupture.', 1),
    mc('What is the difference between earthquake magnitude and intensity?', ['They are the same measurement', 'Magnitude measures energy released at the source; intensity measures shaking felt at a specific location', 'Intensity is measured by seismographs; magnitude by human observation', 'Magnitude uses the Mercalli scale; intensity uses the Richter scale'], 'Magnitude measures energy released at the source; intensity measures shaking felt at a specific location', 'A magnitude 7 earthquake may be felt lightly far away (low intensity) but violently near the epicenter (high intensity). Richter/moment magnitude = energy; Mercalli = felt effects.', 2),
    mc('What is the "Ring of Fire"?', ['A volcanic region around Africa', 'A zone of intense seismic and volcanic activity encircling the Pacific Ocean, following plate boundaries', 'A single supervolcano under the Pacific', 'The boundary between the crust and mantle'], 'A zone of intense seismic and volcanic activity encircling the Pacific Ocean, following plate boundaries', 'The Ring of Fire follows subduction zones around the Pacific — ~75% of Earth\'s volcanoes and ~90% of earthquakes occur here. Japan, Indonesia, and the Pacific coast Americas sit on it.', 3),
    mc('What causes a volcano to erupt?', ['Water seeping into magma chambers', 'Pressure from rising magma — buoyant magma ascends through the crust and erupts when pressure exceeds rock strength', 'Earthquakes alone always trigger eruptions', 'Tectonic plates colliding at the surface'], 'Pressure from rising magma — buoyant magma ascends through the crust and erupts when pressure exceeds rock strength', 'Magma rises because it\'s less dense than surrounding rock. Dissolved gases expand as pressure decreases — explosiveness depends on magma viscosity and gas content.', 4),
    mc('What is a tsunami?', ['An extremely large ocean storm wave', 'A series of ocean waves triggered by a large underwater disturbance (earthquake, landslide, or volcanic eruption)', 'A tidal wave caused by the Moon\'s gravity', 'Any wave over 10 meters tall'], 'A series of ocean waves triggered by a large underwater disturbance (earthquake, landslide, or volcanic eruption)', 'Tsunamis are seismically generated, not weather-related. In deep ocean they\'re barely detectable; near shore the wave slows and piles up to devastating heights.', 5),
  ],
  'the-atmosphere': [
    mc('What is the composition of Earth\'s atmosphere?', ['Mostly oxygen with some nitrogen', 'Approximately 78% nitrogen, 21% oxygen, and 1% other gases including CO₂ and argon', 'Mostly CO₂ like Venus', '50% nitrogen, 50% oxygen'], 'Approximately 78% nitrogen, 21% oxygen, and 1% other gases including CO₂ and argon', 'Earth\'s atmosphere is mostly nitrogen (N₂). Oxygen (21%) supports life. CO₂ is only ~0.04% but critical for the greenhouse effect. Venus\'s CO₂-rich atmosphere = 462°C surface.', 1),
    mc('What is the greenhouse effect?', ['Farming in enclosed glass structures', 'Atmospheric gases absorbing outgoing infrared radiation and re-emitting it, warming Earth\'s surface', 'Ozone trapping solar radiation', 'Clouds blocking incoming sunlight'], 'Atmospheric gases absorbing outgoing infrared radiation and re-emitting it, warming Earth\'s surface', 'Greenhouse gases (CO₂, water vapor, methane) are transparent to incoming solar radiation but absorb and re-radiate outgoing infrared — warming the surface. Without it, Earth would be -18°C.', 2),
    mc('What does the ozone layer do?', ['Traps heat near Earth\'s surface', 'Absorbs most of the Sun\'s ultraviolet (UV) radiation, protecting life on Earth', 'Filters out visible light', 'Prevents clouds from forming too high'], 'Absorbs most of the Sun\'s ultraviolet (UV) radiation, protecting life on Earth', 'Stratospheric ozone (O₃) at 15-35 km altitude absorbs UV-B and UV-C radiation. UV-B causes skin cancer and DNA damage. CFCs depleted the ozone layer (Antarctic ozone hole).', 3),
    mc('What are the main layers of the atmosphere in order from surface upward?', ['Stratosphere, troposphere, mesosphere, thermosphere', 'Troposphere, stratosphere, mesosphere, thermosphere, exosphere', 'Ozone layer, cloud layer, vacuum layer, space', 'Lower, middle, upper, and outer atmosphere'], 'Troposphere, stratosphere, mesosphere, thermosphere, exosphere', 'Weather occurs in the troposphere (0-12 km). Ozone is in the stratosphere. Meteors burn in the mesosphere. Auroras occur in the thermosphere. The exosphere gradually fades to space.', 4),
    mc('Why is the sky blue?', ['The ocean reflects blue light upward', 'The atmosphere scatters shorter (blue) wavelengths of sunlight more than longer wavelengths (red)', 'Blue light penetrates the atmosphere more deeply', 'Water vapor in the air absorbs red light'], 'The atmosphere scatters shorter (blue) wavelengths of sunlight more than longer wavelengths (red)', 'Rayleigh scattering: gas molecules scatter blue light in all directions — you see blue sky everywhere. At sunset, light travels farther through atmosphere, scattering away all blue, leaving red/orange.', 5),
  ],
  'weather-systems': [
    mc('What drives weather patterns on Earth?', ['The Moon\'s gravitational pull', 'Differential heating of Earth\'s surface by the Sun, creating pressure differences that drive air movement', 'Earth\'s rotation only', 'Ocean currents alone'], 'Differential heating of Earth\'s surface by the Sun, creating pressure differences that drive air movement', 'Uneven solar heating creates warm, rising air (low pressure) and cool, sinking air (high pressure). This drives wind, which moves heat and moisture — creating weather.', 1),
    mc('What is the Coriolis effect?', ['The warming effect of the ocean on coastal weather', 'The deflection of moving air masses by Earth\'s rotation — right in Northern Hemisphere, left in Southern', 'The tendency of low pressure to draw in high pressure air', 'How mountains create rain shadows'], 'The deflection of moving air masses by Earth\'s rotation — right in Northern Hemisphere, left in Southern', 'Earth\'s rotation deflects large-scale air movement. It creates clockwise winds around high pressure in the NH and counterclockwise around low pressure (hurricanes spin counterclockwise in NH).', 2),
    mc('What is a weather front?', ['The leading edge of a storm system', 'The boundary between two air masses of different temperature and humidity', 'The area of highest pressure in a weather system', 'A line on a weather map showing wind direction'], 'The boundary between two air masses of different temperature and humidity', 'Cold fronts bring cold air replacing warm — typically storms and rapid temperature drops. Warm fronts bring warm air advancing over cold — gradual cloudiness and rain.', 3),
    mc('What causes thunderstorms?', ['Only cold fronts', 'Rapid upward movement of warm, moist air — creating towering cumulonimbus clouds with lightning and heavy rain', 'Low pressure systems alone', 'Wind shear at high altitude'], 'Rapid upward movement of warm, moist air — creating towering cumulonimbus clouds with lightning and heavy rain', 'Thunderstorms need: moisture, instability (warm air over cool), and a lifting mechanism (front, sea breeze, terrain). Rising air cools, water condenses, releasing latent heat that fuels the storm.', 4),
    mc('What is the difference between weather and climate?', ['Weather is long-term; climate is short-term', 'Weather is short-term atmospheric conditions; climate is the long-term pattern of weather over decades in a region', 'They are the same thing measured differently', 'Climate refers to global conditions; weather to local only'], 'Weather is short-term atmospheric conditions; climate is the long-term pattern of weather over decades in a region', '"Climate is what you expect; weather is what you get." Climate describes 30-year average patterns — temperature range, precipitation, seasonal patterns — for a location.', 5),
  ],
  'climate-and-climate-change': [
    mc('What is the scientific consensus on current climate change?', ['Scientists are equally divided on whether it is happening', 'Earth\'s climate is warming primarily due to human emissions of greenhouse gases, with over 97% of climate scientists in agreement', 'Natural cycles fully explain recent warming', 'The climate is cooling overall'], 'Earth\'s climate is warming primarily due to human emissions of greenhouse gases, with over 97% of climate scientists in agreement', 'Multiple independent lines of evidence (rising temperatures, melting ice, rising seas, ocean acidification, attribution studies) confirm human-caused warming. The IPCC represents consensus of thousands of scientists.', 1),
    mc('What is the primary human cause of current climate change?', ['Deforestation alone', 'Burning fossil fuels (coal, oil, natural gas) releasing CO₂ and other greenhouse gases', 'Nuclear power plant emissions', 'Agricultural methane only'], 'Burning fossil fuels (coal, oil, natural gas) releasing CO₂ and other greenhouse gases', 'CO₂ from fossil fuel combustion (plus methane from agriculture/landfills and deforestation) has raised atmospheric CO₂ from 280 ppm pre-industrial to over 420 ppm today.', 2),
    mc('What is ocean acidification?', ['Oceans becoming more basic as they warm', 'The lowering of ocean pH as oceans absorb CO₂, forming carbonic acid', 'Pollution making coastal waters toxic', 'Volcanic activity releasing acid into the ocean'], 'The lowering of ocean pH as oceans absorb CO₂, forming carbonic acid', 'Oceans absorb ~30% of CO₂ emissions: CO₂ + H₂O → H₂CO₃ → H⁺ + HCO₃⁻. Ocean pH has dropped 0.1 units (30% more acidic) since industrialization. Harms shell-forming organisms.', 3),
    mc('Which of the following is NOT a projected effect of climate change?', ['More frequent and intense heat waves', 'Rising sea levels from thermal expansion and ice melt', 'Decreased intensity of hurricanes globally', 'Shifts in species ranges and increased extinction risk'], 'Decreased intensity of hurricanes globally', 'Climate change is projected to intensify the strongest hurricanes (more water vapor/energy) even if total numbers don\'t rise. All other options are well-supported projections.', 4),
    mc('What is the difference between climate mitigation and adaptation?', ['Mitigation is short-term; adaptation is long-term', 'Mitigation reduces greenhouse gas emissions to slow change; adaptation adjusts to changes that are already unavoidable', 'Adaptation prevents climate change; mitigation responds to it', 'They are the same strategy with different names'], 'Mitigation reduces greenhouse gas emissions to slow change; adaptation adjusts to changes that are already unavoidable', 'Mitigation: renewable energy, efficiency, stopping deforestation. Adaptation: seawalls, drought-resistant crops, heat warning systems. Both are needed simultaneously.', 5),
  ],
}
