import type { ExerciseDef } from '../types'

function mc(
  question: string,
  options: string[],
  correctAnswer: string,
  explanation: string,
  order: number
): ExerciseDef {
  return { question, type: 'MULTIPLE_CHOICE', options, correctAnswer, explanation, order }
}

export const sciencesExercises1: Record<string, ExerciseDef[]> = {
  'observation-and-hypothesis': [
    mc('What is a scientific hypothesis?', ['A proven scientific fact', 'A testable, falsifiable explanation for an observation', 'An educated guess that can never be tested', 'The conclusion of an experiment'], 'A testable, falsifiable explanation for an observation', 'A hypothesis is a proposed explanation that can be tested through experiment or observation. If it can\'t be falsified in principle, it\'s not scientific.', 1),
    mc('What does it mean for a hypothesis to be "falsifiable"?', ['It has already been shown to be false', 'It is possible to design an experiment that could prove it wrong', 'It is likely to be false', 'Scientists have voted to reject it'], 'It is possible to design an experiment that could prove it wrong', 'Falsifiability (Karl Popper) is the hallmark of science. "God exists" can\'t be falsified; "this drug reduces fever" can be tested and potentially disproven.', 2),
    mc('Which is the best example of a scientific observation?', ['Sunsets are beautiful', '"I think the plant is unhealthy"', 'The plant\'s leaves turned yellow and began wilting after 5 days without water', '"Plants don\'t like the dark"'], 'The plant\'s leaves turned yellow and began wilting after 5 days without water', 'Scientific observations are specific, objective, and measurable — not vague impressions or interpretations. Precise description enables testable hypotheses.', 3),
    mc('What is inductive reasoning in science?', ['Starting with a theory and testing specific predictions', 'Drawing general conclusions from specific observations', 'Proving a hypothesis true through one experiment', 'Deducing what must be true based on logic alone'], 'Drawing general conclusions from specific observations', 'Induction moves from specific data to general conclusions. Observe many ravens are black → hypothesis: all ravens are black. One white raven falsifies it.', 4),
    mc('Why should a hypothesis be as specific and precise as possible?', ['Vague hypotheses are easier to test', 'Specific hypotheses generate clear predictions that can be definitively tested and falsified', 'General hypotheses cover more situations', 'Specificity makes hypotheses more likely to be true'], 'Specific hypotheses generate clear predictions that can be definitively tested and falsified', 'A precise hypothesis ("X will increase by 10% when Y doubles") produces testable predictions. Vague hypotheses ("X might affect Y") can survive any result.', 5),
  ],
  'experiments-and-controls': [
    mc('What is the purpose of a control group in an experiment?', ['To serve as extra subjects in case others drop out', 'To provide a baseline comparison — everything is the same except the experimental variable', 'To control the experimenter\'s behavior', 'To represent the most common outcome'], 'To provide a baseline comparison — everything is the same except the experimental variable', 'The control group experiences everything except the variable being tested. It shows what happens without the intervention, making differences meaningful.', 1),
    mc('What is an independent variable?', ['A variable that changes on its own', 'The variable the experimenter deliberately manipulates', 'The outcome being measured', 'A variable held constant throughout'], 'The variable the experimenter deliberately manipulates', 'The independent variable is what you change. The dependent variable is what you measure. All other variables should be controlled (held constant).', 2),
    mc('What is a dependent variable?', ['A variable that depends on the experimenter\'s preference', 'The outcome or response that is measured in an experiment', 'A variable that is controlled and kept constant', 'The variable you manipulate'], 'The outcome or response that is measured in an experiment', 'The dependent variable is what you measure to see if the independent variable had an effect. It "depends" on the independent variable.', 3),
    mc('Why do scientists use random assignment in experiments?', ['To make the experiment more exciting', 'To ensure that pre-existing differences between subjects are distributed by chance, not bias', 'Random assignment is actually not useful', 'To reduce the number of subjects needed'], 'To ensure that pre-existing differences between subjects are distributed by chance, not bias', 'Random assignment controls for confounding variables — people are randomly put in experimental or control groups so differences in outcomes can be attributed to the intervention.', 4),
    mc('What is a placebo and why is it used?', ['A very small dose of the real treatment', 'An inert treatment that looks like the real treatment, used to separate true treatment effects from expectation effects', 'The name for the control group treatment', 'A failed experimental drug'], 'An inert treatment that looks like the real treatment, used to separate true treatment effects from expectation effects', 'The placebo effect is real — believing you\'re being treated can cause measurable improvements. Placebos separate genuine drug effects from this psychological response.', 5),
  ],
  'data-and-conclusions': [
    mc('What is the difference between qualitative and quantitative data?', ['Qualitative is better; quantitative is worse', 'Qualitative describes qualities (color, texture); quantitative involves measurements and numbers', 'Quantitative is used in biology; qualitative in physics', 'There is no meaningful difference'], 'Qualitative describes qualities (color, texture); quantitative involves measurements and numbers', 'Qualitative data: categories, descriptions, observations. Quantitative data: measurements, counts, ratios. Science often uses both.', 1),
    mc('What does statistical significance mean?', ['The result is practically important', 'The result is unlikely to be due to random chance (p < 0.05)', 'The sample size was large enough', 'The experiment was conducted correctly'], 'The result is unlikely to be due to random chance (p < 0.05)', 'Statistical significance (p-value) tells you how likely the result is by chance. It doesn\'t tell you whether the result is large, important, or replicable.', 2),
    mc('Why must conclusions be limited to what the data actually show?', ['Scientists are too cautious by nature', 'Overgeneralizing beyond the data is scientifically invalid — conclusions must be supported by evidence', 'All scientific conclusions should be tentative and never stated with confidence', 'Data can support any conclusion if interpreted creatively'], 'Overgeneralizing beyond the data is scientifically invalid — conclusions must be supported by evidence', 'Scientific integrity requires that conclusions match what was actually measured. Extrapolating far beyond the study population or conditions is a form of error.', 3),
    mc('What is a confounding variable?', ['A variable the scientist intentionally manipulates', 'An unmeasured variable that influences both the independent and dependent variables, distorting results', 'A measurement error in the data', 'A variable that can be ignored'], 'An unmeasured variable that influences both the independent and dependent variables, distorting results', 'Confounders create false associations. Coffee drinkers may have higher cancer rates — but if they also smoke more, smoking (the confounder) causes the cancer, not coffee.', 4),
    mc('What is the difference between correlation and causation?', ['They are the same thing if the sample is large enough', 'Correlation means two variables move together; causation means one actually causes the other to change', 'Causation is impossible to establish scientifically', 'Correlation is more important than causation'], 'Correlation means two variables move together; causation means one actually causes the other to change', '"Ice cream sales correlate with drowning rates" — summer causes both, not ice cream. Causation requires ruling out confounders and showing mechanism.', 5),
  ],
  'peer-review-and-replication': [
    mc('What is peer review in science?', ['Scientists reviewing each other\'s salaries', 'Evaluation of research by other qualified scientists before publication, checking methods, logic, and conclusions', 'A government review of research funding', 'Students grading each other\'s lab reports'], 'Evaluation of research by other qualified scientists before publication, checking methods, logic, and conclusions', 'Peer review catches errors, fraud, and weak methodology before publication. It\'s imperfect but the best filter science has for quality control.', 1),
    mc('Why is replication important in science?', ['One experiment is never enough to believe a result', 'It gives other scientists jobs', 'A result replicated by independent labs is much more reliable than a single study', 'Replication proves a hypothesis permanently true'], 'A result replicated by independent labs is much more reliable than a single study', 'Any single study might have errors, fraud, or statistical flukes. If independent researchers replicate the result in different conditions, confidence grows dramatically.', 2),
    mc('What is the "replication crisis"?', ['Too many scientists trying to replicate the same findings', 'The finding that many published scientific results, especially in psychology, cannot be replicated', 'Peer reviewers requesting too many revisions', 'The decline in scientific publication volume'], 'The finding that many published scientific results, especially in psychology, cannot be replicated', 'Studies found that ~50-60% of landmark psychology findings couldn\'t be reproduced. This exposed problems with small samples, p-hacking, and publication bias.', 3),
    mc('What is scientific consensus?', ['Whatever the majority of scientists personally believe', 'The collective judgment of scientists based on accumulated, replicated evidence across many studies', 'The result of a single landmark study', 'Agreement among all scientists on all topics'], 'The collective judgment of scientists based on accumulated, replicated evidence across many studies', 'Consensus emerges from many independent studies converging on the same conclusion. It\'s not a vote — it reflects the weight of evidence (e.g., climate change, evolution, vaccine safety).', 4),
    mc('How should you evaluate a single scientific study in the news?', ['Treat it as established fact if it was peer-reviewed', 'With skepticism — consider sample size, who funded it, whether it was replicated, and whether it contradicts a broad consensus', 'Trust it completely if a university conducted it', 'Only trust studies with very large sample sizes'], 'With skepticism — consider sample size, who funded it, whether it was replicated, and whether it contradicts a broad consensus', 'One study is a data point, not a conclusion. The best science is replicated, peer-reviewed, conducted without conflicts of interest, and consistent with a larger body of evidence.', 5),
  ],
  'cell-theory': [
    mc('What are the three principles of cell theory?', ['Cells grow, divide, and die', 'All living things are made of cells; the cell is the basic unit of life; all cells come from pre-existing cells', 'Cells contain DNA, proteins, and water', 'Cells have a nucleus, membrane, and cytoplasm'], 'All living things are made of cells; the cell is the basic unit of life; all cells come from pre-existing cells', 'Cell theory (developed by Schleiden, Schwann, and Virchow) is a foundational principle of biology — cells are life\'s basic structural and functional unit.', 1),
    mc('What is the difference between prokaryotic and eukaryotic cells?', ['Prokaryotes are plant cells; eukaryotes are animal cells', 'Prokaryotes lack a membrane-bound nucleus; eukaryotes have a true nucleus and membrane-bound organelles', 'Prokaryotes are larger than eukaryotes', 'Eukaryotes lack DNA; prokaryotes have DNA in a nucleus'], 'Prokaryotes lack a membrane-bound nucleus; eukaryotes have a true nucleus and membrane-bound organelles', 'Bacteria are prokaryotes — their DNA floats in the cytoplasm. All plants, animals, fungi, and protists are eukaryotes with a nucleus and organelles.', 2),
    mc('Which organisms are prokaryotes?', ['Humans and other mammals', 'Bacteria and archaea', 'Fungi and plants', 'Viruses and prions'], 'Bacteria and archaea', 'Bacteria and archaea are the only prokaryotes — single-celled organisms without a membrane-bound nucleus. All other life is eukaryotic.', 3),
    mc('What is the smallest unit of life?', ['The atom', 'The molecule', 'The cell', 'The organelle'], 'The cell', 'Cells are the smallest units that can perform all functions of life: metabolism, growth, response to stimuli, and reproduction. Organelles alone cannot.', 4),
    mc('How do cells arise, according to cell theory?', ['Cells spontaneously generate from non-living matter', 'Cells arise only from pre-existing cells through division', 'Cells are created by the organism\'s DNA', 'New cells form from organelles combining'], 'Cells arise only from pre-existing cells through division', '"Omnis cellula e cellula" (Virchow) — all cells come from cells. This disproved spontaneous generation and established cellular reproduction as the basis of life.', 5),
  ],
  'cell-structure': [
    mc('What is the function of the cell membrane?', ['It stores genetic information', 'It controls what enters and exits the cell, providing selective permeability', 'It produces energy for the cell', 'It provides the cell\'s rigid structure'], 'It controls what enters and exits the cell, providing selective permeability', 'The phospholipid bilayer membrane regulates transport — letting some molecules through freely, others by protein channels, and blocking others. It defines the cell\'s boundary.', 1),
    mc('What is the function of the nucleus?', ['Energy production', 'Protein synthesis directly', 'Containing DNA and directing cell activity — the cell\'s control center', 'Breaking down waste materials'], 'Containing DNA and directing cell activity — the cell\'s control center', 'The nucleus houses the cell\'s genetic material and directs activities by controlling which genes are expressed (transcription).', 2),
    mc('What do mitochondria do?', ['Produce proteins', 'Synthesize lipids', 'Generate ATP through cellular respiration — the cell\'s energy currency', 'Store genetic information'], 'Generate ATP through cellular respiration — the cell\'s energy currency', 'Mitochondria convert glucose and oxygen into ATP through cellular respiration. They have their own DNA — evidence they were once free-living bacteria.', 3),
    mc('What do ribosomes do?', ['Generate energy', 'Synthesize proteins by reading mRNA instructions', 'Package materials for secretion', 'Digest cellular waste'], 'Synthesize proteins by reading mRNA instructions', 'Ribosomes are the cell\'s protein factories — they translate mRNA sequences into amino acid chains (proteins) in both prokaryotes and eukaryotes.', 4),
    mc('What structure is found in plant cells but NOT animal cells?', ['Cell membrane', 'Mitochondria', 'Nucleus', 'Cell wall and chloroplasts'], 'Cell wall and chloroplasts', 'Plant cells have cell walls (rigidity and support) and chloroplasts (photosynthesis) that animal cells lack. Animal cells have centrioles not found in plants.', 5),
  ],
  'cell-processes': [
    mc('What is photosynthesis?', ['How cells produce ATP from sugar', 'The process by which plants use sunlight, CO₂, and water to produce glucose and oxygen', 'How plants absorb nutrients from soil', 'The breakdown of organic molecules for energy'], 'The process by which plants use sunlight, CO₂, and water to produce glucose and oxygen', 'Photosynthesis: 6CO₂ + 6H₂O + light → C₆H₁₂O₆ + 6O₂. It occurs in chloroplasts and captures solar energy into chemical form.', 1),
    mc('What is cellular respiration?', ['Breathing through lungs', 'The process by which cells break down glucose to release energy (ATP), producing CO₂ and water', 'The transport of oxygen in blood', 'The exchange of gases between plants and the atmosphere'], 'The process by which cells break down glucose to release energy (ATP), producing CO₂ and water', 'Cellular respiration: C₆H₁₂O₆ + 6O₂ → 6CO₂ + 6H₂O + ATP. Occurs in mitochondria. It\'s the reverse of photosynthesis.', 2),
    mc('What is ATP?', ['A type of DNA', 'Adenosine triphosphate — the cell\'s primary energy currency used to power cellular processes', 'A protein that catalyzes reactions', 'The sugar produced by photosynthesis'], 'Adenosine triphosphate — the cell\'s primary energy currency used to power cellular processes', 'ATP stores and transfers energy within cells. When ATP is broken down to ADP, energy is released to power muscle contraction, biosynthesis, and transport.', 3),
    mc('Which organelle conducts photosynthesis?', ['Mitochondria', 'Ribosome', 'Chloroplast', 'Vacuole'], 'Chloroplast', 'Chloroplasts in plant cells contain chlorophyll, which absorbs light energy used in photosynthesis. They also have their own DNA — like mitochondria.', 4),
    mc('Fermentation allows cells to produce ATP without:', ['Glucose', 'Ribosomes', 'Oxygen (anaerobic conditions)', 'ADP'], 'Oxygen (anaerobic conditions)', 'Fermentation is anaerobic respiration — producing ATP without oxygen. Yeast ferment sugars to alcohol; muscle cells produce lactic acid during intense exercise.', 5),
  ],
}
