import type { ExerciseDef } from '../types'

function mc(
  question: string,
  options: string[],
  correctAnswer: string,
  explanation: string,
  order: number
): ExerciseDef {
  return { question, type: 'MULTIPLE_CHOICE', options, correctAnswer, explanation, order }
}

export const sciencesExercises5: Record<string, ExerciseDef[]> = {
  'newtons-laws': [
    mc('What does Newton\'s First Law state?', ['Force equals mass times acceleration', 'An object at rest or in uniform motion stays that way unless acted on by a net external force', 'Every action has an equal and opposite reaction', 'Gravity pulls all objects equally'], 'An object at rest or in uniform motion stays that way unless acted on by a net external force', 'The Law of Inertia: objects resist changes to their state of motion. A hockey puck slides forever on a frictionless surface; friction stops it on ice.', 1),
    mc('What does Newton\'s Second Law state?', ['Objects at rest stay at rest', 'Net force equals mass times acceleration (F = ma)', 'For every action there is an equal and opposite reaction', 'Gravity depends on mass and distance'], 'Net force equals mass times acceleration (F = ma)', 'F = ma: larger force → more acceleration; larger mass → less acceleration for the same force. Units: 1 Newton = 1 kg·m/s².', 2),
    mc('What does Newton\'s Third Law state?', ['F = ma', 'For every action force, there is an equal and opposite reaction force', 'Objects fall at the same rate regardless of mass', 'Inertia resists changes in motion'], 'For every action force, there is an equal and opposite reaction force', 'Forces always come in pairs. Earth pulls you down (gravity); you pull Earth up with equal force. A rocket expels gas backward; the gas pushes the rocket forward.', 3),
    mc('If a 2 kg object accelerates at 5 m/s², what is the net force?', ['2.5 N', '7 N', '10 N', '0.4 N'], '10 N', 'F = ma = 2 kg × 5 m/s² = 10 N. Newton\'s Second Law directly applied.', 4),
    mc('What is inertia?', ['The force of gravity on an object', 'An object\'s tendency to resist changes in its state of motion — proportional to mass', 'The acceleration due to gravity', 'The reaction force to applied force'], 'An object\'s tendency to resist changes in its state of motion — proportional to mass', 'Inertia is the \"resistance\" to acceleration. A large truck is harder to start moving or stop than a bicycle — more mass = more inertia.', 5),
  ],
  'gravity': [
    mc('What determines the gravitational force between two objects?', ['Their size and color', 'Their masses and the distance between them (F = Gm₁m₂/r²)', 'Only their masses', 'Only the distance between them'], 'Their masses and the distance between them (F = Gm₁m₂/r²)', 'Newton\'s Law of Universal Gravitation: gravity is proportional to the product of masses and inversely proportional to distance squared. Double distance → gravity decreases to 1/4.', 1),
    mc('Why do astronauts feel weightless in orbit?', ['Gravity is zero in space', 'They are in continuous free fall toward Earth — orbit is falling and missing the ground', 'The space station shields them from gravity', 'Their mass disappears in vacuum'], 'They are in continuous free fall toward Earth — orbit is falling and missing the ground', 'Orbital weightlessness = continuous free fall. The space station falls toward Earth but moves horizontally fast enough that Earth curves away beneath it.', 2),
    mc('What is the difference between mass and weight?', ['They are the same thing', 'Mass is the amount of matter (kg, constant everywhere); weight is the gravitational force on that mass (N, varies by location)', 'Weight is measured in kg; mass in Newtons', 'Mass changes on the Moon; weight does not'], 'Mass is the amount of matter (kg, constant everywhere); weight is the gravitational force on that mass (N, varies by location)', 'Your mass is the same on the Moon and Earth. Your weight on the Moon is 1/6 of Earth weight because lunar gravity is 1/6 as strong.', 3),
    mc('According to Newton\'s Third Law, when Earth pulls you down with gravity, what happens?', ['Nothing — gravity is one-directional', 'You pull Earth toward you with an equal and opposite force', 'You push Earth away', 'The ground pushes you up instead'], 'You pull Earth toward you with an equal and opposite force', 'Gravity is mutual — Earth pulls you down, you pull Earth up with the same force. Earth\'s enormous mass means it barely accelerates; you accelerate noticeably.', 4),
    mc('If you drop a feather and a bowling ball on the Moon (no atmosphere), what happens?', ['The bowling ball falls faster', 'Both fall at the same rate and hit the ground simultaneously', 'The feather falls faster due to its shape', 'Neither falls — no gravity on Moon'], 'Both fall at the same rate and hit the ground simultaneously', 'Without air resistance, all objects fall with the same acceleration due to gravity regardless of mass — Galileo\'s principle, famously demonstrated on the Moon in 1971.', 5),
  ],
  'friction-and-momentum': [
    mc('What is friction?', ['A force that accelerates moving objects', 'A force that opposes relative motion between surfaces in contact', 'A measure of an object\'s velocity', 'The force of gravity between surfaces'], 'A force that opposes relative motion between surfaces in contact', 'Friction arises from microscopic interactions between surfaces. Static friction prevents motion from starting; kinetic friction opposes ongoing motion.', 1),
    mc('What factors affect the force of kinetic friction?', ['The speed of the object and its shape', 'The coefficient of kinetic friction and the normal force between surfaces', 'The area of contact and the object\'s temperature', 'The velocity and direction of motion'], 'The coefficient of kinetic friction and the normal force between surfaces', 'f = μN: friction force = coefficient of friction × normal force. Heavier objects have more normal force → more friction. The friction coefficient depends on the surfaces.', 2),
    mc('What is momentum?', ['Force times acceleration', 'Mass times velocity (p = mv)', 'The energy of a moving object', 'The rate of change of velocity'], 'Mass times velocity (p = mv)', 'Momentum (p = mv) is a vector quantity. A heavy, slow truck and a light, fast car can have the same momentum. It\'s the "quantity of motion."', 3),
    mc('What does the law of conservation of momentum state?', ['Momentum increases during collisions', 'The total momentum of a closed system remains constant if no external forces act on it', 'Momentum is always lost in collisions', 'Momentum equals force times time'], 'The total momentum of a closed system remains constant if no external forces act on it', 'In a collision, momentum transfers between objects but the total stays the same. This explains billiard ball physics, rocket propulsion, and car crash dynamics.', 4),
    mc('What is impulse?', ['The change in an object\'s speed only', 'Force multiplied by time — equals the change in momentum', 'Momentum divided by mass', 'The force required to stop an object'], 'Force multiplied by time — equals the change in momentum', 'Impulse = F×t = Δp. Airbags increase collision time, reducing force. A baseball\'s follow-through applies force longer, increasing ball momentum.', 5),
  ],
  'work-and-energy': [
    mc('In physics, what is work?', ['Any physical activity that makes you tired', 'Force applied in the direction of displacement: W = F × d × cos(θ)', 'Energy consumed by the body', 'Power multiplied by time'], 'Force applied in the direction of displacement: W = F × d × cos(θ)', 'Physics work requires force with a displacement component in the force\'s direction. Holding a weight stationary = no work despite the effort felt.', 1),
    mc('What is kinetic energy?', ['Energy stored in position or configuration', 'Energy of motion: KE = ½mv²', 'Energy stored in chemical bonds', 'Energy released by nuclear reactions'], 'Energy of motion: KE = ½mv²', 'KE depends on mass and especially velocity (squared). Doubling speed quadruples kinetic energy — why high speeds dramatically increase crash severity.', 2),
    mc('What is potential energy?', ['Energy of motion', 'Stored energy due to position, configuration, or chemical state', 'Energy dissipated as heat', 'The work done against friction'], 'Stored energy due to position, configuration, or chemical state', 'Gravitational PE = mgh. A book on a shelf has more PE than on the floor. Chemical PE is stored in bonds (gasoline). Elastic PE in a stretched spring.', 3),
    mc('What does the law of conservation of energy state?', ['Energy is created during chemical reactions', 'Energy cannot be created or destroyed — only converted between forms', 'Energy decreases over time in any system', 'Mechanical energy is always conserved'], 'Energy cannot be created or destroyed — only converted between forms', 'Total energy in a closed system is constant. A falling ball converts PE to KE. Burning fuel converts chemical energy to heat and light. Energy changes form, never disappears.', 4),
    mc('What is power in physics?', ['Force times distance', 'The rate at which work is done or energy is transferred: P = W/t', 'Mass times acceleration', 'Energy times velocity'], 'The rate at which work is done or energy is transferred: P = W/t', 'Power (watts = joules/second) measures how fast work is done. A powerful engine can do the same work faster. 1 watt = 1 joule per second.', 5),
  ],
  'heat-and-thermodynamics': [
    mc('What is temperature?', ['The total thermal energy of an object', 'A measure of the average kinetic energy of particles in a substance', 'The amount of heat transferred', 'The energy contained in chemical bonds'], 'A measure of the average kinetic energy of particles in a substance', 'Temperature measures how fast particles are moving on average — not the total energy. A hot cup of water and a hot lake have the same temperature but different total thermal energy.', 1),
    mc('What is heat?', ['The same as temperature', 'Thermal energy transferred from a warmer object to a cooler one', 'The total energy of a system', 'Radiation emitted by hot objects'], 'Thermal energy transferred from a warmer object to a cooler one', 'Heat (Q) is energy in transit — it flows from high temperature to low. Heat and temperature are different: adding heat to water raises temperature; melting ice absorbs heat without temperature change.', 2),
    mc('What does the First Law of Thermodynamics state?', ['Heat always flows from cold to hot', 'The total energy of a system plus its surroundings is conserved — energy can\'t be created or destroyed', 'Entropy always increases', 'You can\'t get more work out of a system than heat you put in'], 'The total energy of a system plus its surroundings is conserved — energy can\'t be created or destroyed', 'The First Law is conservation of energy applied to thermodynamic systems: ΔU = Q - W. Internal energy changes equal heat added minus work done by the system.', 3),
    mc('What does the Second Law of Thermodynamics state?', ['Energy is conserved in all processes', 'Heat naturally flows from hot to cold; entropy (disorder) in a closed system tends to increase', 'Work can be completely converted to heat', 'Temperature always decreases in a closed system'], 'Heat naturally flows from hot to cold; entropy (disorder) in a closed system tends to increase', 'The Second Law explains why heat flows one way, why engines waste energy, and why your room becomes messier — entropy is nature\'s direction of spontaneous change.', 4),
    mc('What is specific heat capacity?', ['The temperature at which a substance melts', 'The amount of heat energy needed to raise 1 kg of a substance by 1°C', 'The rate at which heat flows through a material', 'The maximum temperature a substance can reach'], 'The amount of heat energy needed to raise 1 kg of a substance by 1°C', 'Water has high specific heat (4,186 J/kg·°C) — it takes a lot of energy to change its temperature, which is why coastlines have moderate climates.', 5),
  ],
  'waves': [
    mc('What is a wave?', ['A moving particle of matter', 'A disturbance that transfers energy through a medium without transferring matter', 'The flow of electrons through a conductor', 'A type of particle emitted by radioactive elements'], 'A disturbance that transfers energy through a medium without transferring matter', 'Waves transfer energy, not matter. A water wave moves energy across the ocean — the water itself moves up and down, not horizontally.', 1),
    mc('What is the difference between transverse and longitudinal waves?', ['Transverse waves need a medium; longitudinal do not', 'Transverse waves oscillate perpendicular to propagation; longitudinal oscillate parallel to propagation', 'Longitudinal waves are faster', 'There is no meaningful physical difference'], 'Transverse waves oscillate perpendicular to propagation; longitudinal oscillate parallel to propagation', 'Light and water waves are transverse (up-down oscillation, sideways travel). Sound is longitudinal — air molecules compress and expand in the direction of travel.', 2),
    mc('What is the relationship between frequency and wavelength for a wave?', ['They are directly proportional at constant speed', 'They are inversely proportional: v = fλ, so higher frequency = shorter wavelength', 'They are not related', 'Higher frequency always means longer wavelength'], 'They are inversely proportional: v = fλ, so higher frequency = shorter wavelength', 'Wave speed = frequency × wavelength (v = fλ). At constant speed, doubling frequency halves wavelength. Blue light has shorter wavelength and higher frequency than red.', 3),
    mc('What is the Doppler effect?', ['Waves slowing down as they travel farther', 'The change in perceived frequency of a wave when the source and observer are moving relative to each other', 'Wave reflection off hard surfaces', 'The interference of two waves of similar frequency'], 'The change in perceived frequency of a wave when the source and observer are moving relative to each other', 'Approaching sirens sound higher pitched (compressed wavelength = higher frequency); receding sirens lower. The same effect works for light — redshift from receding stars.', 4),
    mc('What part of the electromagnetic spectrum is visible light?', ['The lowest frequency electromagnetic waves', 'A narrow band of electromagnetic radiation between ultraviolet and infrared, detectable by human eyes', 'Any radiation that produces heat', 'The highest energy electromagnetic waves'], 'A narrow band of electromagnetic radiation between ultraviolet and infrared, detectable by human eyes', 'Visible light is ~400-700nm wavelength. The EM spectrum spans radio waves (low frequency/energy) to gamma rays (highest). All EM waves travel at c in vacuum.', 5),
  ],
  'electricity-and-magnetism': [
    mc('What is electric current?', ['The force that pushes electrons', 'The flow of electric charge (usually electrons) through a conductor', 'The energy stored in a battery', 'The resistance of a material to electron flow'], 'The flow of electric charge (usually electrons) through a conductor', 'Current (I) is measured in amperes (amps = coulombs/second). Conventional current flows from + to -; electrons actually flow - to +.', 1),
    mc('What is voltage (electric potential difference)?', ['The amount of current flowing', 'The energy per unit charge — the \"pressure\" that drives current through a circuit', 'The resistance of a conductor', 'The power dissipated by a resistor'], 'The energy per unit charge — the \"pressure\" that drives current through a circuit', 'Voltage (V) is measured in volts. Higher voltage = more energy per charge = more force driving electrons. A 9V battery provides more \"push\" than a 1.5V battery.', 2),
    mc('What does Ohm\'s Law state?', ['Power equals current times resistance', 'V = IR: voltage equals current times resistance', 'Resistance increases with temperature always', 'Current equals voltage squared divided by resistance'], 'V = IR: voltage equals current times resistance', 'Ohm\'s Law: V = IR. At constant voltage, doubling resistance halves current. At constant resistance, doubling voltage doubles current.', 3),
    mc('What is the relationship between electricity and magnetism?', ['They are completely separate phenomena', 'They are two aspects of the same fundamental force — moving charges create magnetic fields; changing magnetic fields induce current', 'Magnetism causes electricity but not vice versa', 'Electricity causes magnetism only in iron'], 'They are two aspects of the same fundamental force — moving charges create magnetic fields; changing magnetic fields induce current', 'Electromagnetism (Maxwell): electric currents create magnetic fields (motor principle); changing magnetic fields create electric current (generator principle). Unified theory explains light.', 4),
    mc('What is electromagnetic induction?', ['Charging an object by contact', 'The generation of electric current by a changing magnetic field', 'The attraction between opposite charges', 'The flow of electrons through a semiconductor'], 'The generation of electric current by a changing magnetic field', 'Faraday\'s Law: a changing magnetic field through a conductor induces an EMF (voltage). This is how generators, transformers, and induction cooktops work.', 5),
  ],
}
