import type { ExerciseDef } from '../types'

function mc(
  question: string,
  options: string[],
  correctAnswer: string,
  explanation: string,
  order: number
): ExerciseDef {
  return { question, type: 'MULTIPLE_CHOICE', options, correctAnswer, explanation, order }
}

export const techExercises8: Record<string, ExerciseDef[]> = {
  'what-ai-actually-is': [
    mc('Which best describes what AI (artificial intelligence) is?', ['A robot that thinks exactly like a human', 'Software that performs tasks that typically require human-like intelligence', 'A supercomputer that knows everything', 'A program that always produces correct answers'], 'Software that performs tasks that typically require human-like intelligence', 'AI is software that can do things like recognize images, translate language, or generate text — not a mind, but a powerful pattern-matching system.', 1),
    mc('What is "narrow AI"?', ['AI that only works on small datasets', 'AI designed for one specific task or domain', 'A less powerful version of general AI', 'AI that runs on low-power devices'], 'AI designed for one specific task or domain', 'Virtually all AI today is narrow — excellent at one thing (chess, image recognition, translation) but can\'t generalize outside its domain.', 2),
    mc('What does "training" an AI model mean?', ['Teaching a robot to walk', 'Exposing a model to data so it learns patterns', 'Writing the rules an AI follows manually', 'Testing an AI for bugs'], 'Exposing a model to data so it learns patterns', 'Training is the process of feeding a model data and adjusting its internal parameters until it gets good at the task.', 3),
    mc('AI systems today are best described as:', ['Sentient and self-aware', 'Pattern-recognition systems trained on data', 'Logical reasoning engines', 'Deterministic rule-following programs'], 'Pattern-recognition systems trained on data', 'Modern AI learns statistical patterns from massive datasets — it doesn\'t reason, understand, or know things the way humans do.', 4),
    mc('What is a common misconception about AI?', ['That AI can learn from data', 'That AI has human-level understanding and common sense', 'That AI can generate text', 'That AI needs training data'], 'That AI has human-level understanding and common sense', 'AI systems are often confidently wrong. They lack understanding — they predict likely outputs, not correct ones.', 5),
  ],
  'how-machine-learning-works': [
    mc('What is machine learning?', ['Programming a computer with explicit rules for every situation', 'Training a system to learn patterns from data instead of writing rules by hand', 'A type of database query language', 'Using computers to monitor machine performance'], 'Training a system to learn patterns from data instead of writing rules by hand', 'ML lets computers figure out rules from examples — you show it thousands of cat photos and it learns what cats look like.', 1),
    mc('In supervised learning, what does "labeled data" mean?', ['Data stored in neat folders on a server', 'Training examples that include the correct answer', 'Data that has been cleaned and validated', 'Data tagged with timestamps'], 'Training examples that include the correct answer', 'Labeled data has inputs paired with correct outputs (e.g., photos labeled "cat" or "dog") so the model learns from feedback.', 2),
    mc('What happens during the training process?', ['The model memorizes every example', 'The model adjusts internal parameters to minimize prediction errors', 'Engineers write new rules based on test results', 'The data is compressed and stored'], 'The model adjusts internal parameters to minimize prediction errors', 'Training iterates over data, comparing predictions to correct answers and adjusting weights to reduce error over time.', 3),
    mc('What is overfitting in machine learning?', ['When a model is too slow to process data', 'When a model memorizes training data but performs poorly on new data', 'When the training dataset is too small', 'When the model uses too much computing power'], 'When a model memorizes training data but performs poorly on new data', 'An overfit model "memorized" the training examples instead of learning generalizable patterns — it fails on anything new.', 4),
    mc('What is a neural network?', ['A physical network connecting AI servers', 'A computing architecture loosely inspired by brain neurons', 'A database of connected facts', 'A type of encrypted communication protocol'], 'A computing architecture loosely inspired by brain neurons', 'Neural networks are layers of mathematical functions that transform inputs into outputs — loosely analogous to neurons firing.', 5),
  ],
  'large-language-models': [
    mc('What is a large language model (LLM)?', ['A dictionary stored in a computer', 'An AI model trained on massive text data to predict and generate language', 'A search engine with natural language queries', 'A chatbot that follows scripted responses'], 'An AI model trained on massive text data to predict and generate language', 'LLMs like GPT and Claude are trained on huge text corpora to learn language patterns, then generate coherent text responses.', 1),
    mc('How do LLMs generate responses?', ['By looking up answers in a database', 'By predicting the most likely next word or token based on context', 'By reasoning through logic rules', 'By searching the internet in real time'], 'By predicting the most likely next word or token based on context', 'LLMs generate text token by token, each time predicting what comes next given everything before it.', 2),
    mc('What is "hallucination" in the context of LLMs?', ['The model refusing to answer sensitive questions', 'The model confidently stating false or made-up information', 'Slow response time due to server load', 'When the model repeats itself in a loop'], 'The model confidently stating false or made-up information', 'LLMs generate plausible-sounding text — but plausible isn\'t the same as true. They can fabricate facts, citations, and quotes.', 3),
    mc('What does "context window" refer to in LLMs?', ['The size of the user\'s screen', 'The amount of text an LLM can process at once', 'The time limit for generating a response', 'The number of languages the model supports'], 'The amount of text an LLM can process at once', 'The context window is the maximum text (conversation history, instructions, documents) an LLM can "see" at one time.', 4),
    mc('What does it mean that LLMs have a knowledge cutoff date?', ['They stop working after a certain date', 'They were trained on data only up to a point in time and don\'t know about events after', 'They become less accurate over time', 'They require internet access after a certain date'], 'They were trained on data only up to a point in time and don\'t know about events after', 'Training data has a cutoff date — the model has no knowledge of events, publications, or changes after that point.', 5),
  ],
  'using-ai-tools': [
    mc('What is prompt engineering?', ['Programming AI systems from scratch', 'Crafting inputs to get better outputs from an AI', 'Debugging AI code', 'Training an AI on custom data'], 'Crafting inputs to get better outputs from an AI', 'The way you phrase a prompt significantly affects output quality — specificity, context, and format all matter.', 1),
    mc('When should you fact-check AI-generated content?', ['Only for technical topics', 'Always, before using it for anything important', 'Never — AI is usually accurate', 'Only when the topic is controversial'], 'Always, before using it for anything important', 'LLMs hallucinate confidently. Any important claim from an AI should be verified against reliable sources.', 2),
    mc('Which is a good use case for current AI tools?', ['Making high-stakes medical diagnoses alone', 'Drafting first versions of text, summarizing content, brainstorming ideas', 'Replacing legal counsel for contracts', 'Getting real-time news updates'], 'Drafting first versions of text, summarizing content, brainstorming ideas', 'AI excels at generating drafts, summaries, and ideas quickly — but always needs human review for anything important.', 3),
    mc('What does it mean to give an AI "context"?', ['Paying for a premium subscription', 'Providing background information relevant to your request', 'Giving the AI internet access', 'Using the AI in the correct language'], 'Providing background information relevant to your request', 'More relevant context (your role, the goal, constraints, examples) helps AI produce more targeted, useful responses.', 4),
    mc('What is the biggest risk of uncritically trusting AI-generated information?', ['Wasting computing resources', 'Making decisions based on confident but incorrect information', 'Slowing down your workflow', 'Exposing your data to the AI company'], 'Making decisions based on confident but incorrect information', 'AI sounds authoritative even when wrong. Acting on hallucinated facts can cause real harm in medicine, law, finance, and more.', 5),
  ],
  'ai-and-work': [
    mc('What best describes how AI is changing most jobs?', ['AI is replacing all human jobs immediately', 'AI is automating certain tasks within jobs, changing how work is done', 'AI only affects technology-sector jobs', 'AI has had no real impact on employment yet'], 'AI is automating certain tasks within jobs, changing how work is done', 'AI mostly automates specific tasks (drafting emails, summarizing data) rather than entire jobs — but roles are shifting.', 1),
    mc('Which type of work is currently most at risk from AI automation?', ['Creative and interpersonal roles', 'Highly physical, unpredictable outdoor work', 'Routine, structured information processing tasks', 'Emergency medical response'], 'Routine, structured information processing tasks', 'Predictable, rule-based tasks (data entry, basic writing, template-based design) are easiest for AI to automate.', 2),
    mc('What skill will make workers more valuable alongside AI, not replaced by it?', ['Typing faster than AI can generate text', 'Judgment, creativity, and knowing when to question AI output', 'Memorizing more facts than AI knows', 'Using every AI tool available'], 'Judgment, creativity, and knowing when to question AI output', 'AI can produce output, but humans who can evaluate, refine, and apply it wisely are more valuable than those who just use it.', 3),
    mc('Which industry has AI had the most transformative impact on so far?', ['Coal mining', 'Information work — writing, coding, analysis, customer service', 'Agriculture', 'Construction'], 'Information work — writing, coding, analysis, customer service', 'Knowledge work that produces text, code, or decisions has been most immediately affected by language model capabilities.', 4),
    mc('What is "AI augmentation"?', ['Replacing workers with AI entirely', 'Using AI to enhance human capability rather than replace it', 'Uploading human memories to AI', 'Training humans to think like AI'], 'Using AI to enhance human capability rather than replace it', 'Augmentation means AI handles the tedious parts while humans focus on judgment, relationships, and creativity — a powerful combination.', 5),
  ],
  'ai-ethics-and-bias': [
    mc('What is AI bias?', ['AI making calculations that are slightly off', 'Systematic errors in AI outputs that reflect or amplify unfair patterns in training data', 'AI preferring certain programming languages', 'When AI takes too long to generate a response'], 'Systematic errors in AI outputs that reflect or amplify unfair patterns in training data', 'AI learns from human-generated data — which contains historical biases in hiring, lending, policing, and more. The AI can amplify these.', 1),
    mc('Which real-world harm has AI bias caused?', ['AI refusing to write poetry', 'Facial recognition systems being less accurate for darker-skinned faces', 'AI being unable to process large files', 'Chatbots using informal language'], 'Facial recognition systems being less accurate for darker-skinned faces', 'Studies found major facial recognition systems had dramatically higher error rates for Black women vs white men — real bias with real consequences.', 2),
    mc('What does "explainability" mean in AI ethics?', ['How quickly an AI can explain its setup process', 'Being able to understand and explain why an AI made a specific decision', 'How well an AI explains technical topics to users', 'The ability to export an AI model\'s weights'], 'Being able to understand and explain why an AI made a specific decision', 'When AI makes consequential decisions (loan denial, parole), people deserve to understand why — but many AI systems are black boxes.', 3),
    mc('What is a key concern about AI and privacy?', ['AI uses too much battery power', 'AI systems require massive data collection and may reveal sensitive patterns', 'AI models take up too much storage space', 'AI slows down internet connections'], 'AI systems require massive data collection and may reveal sensitive patterns', 'Training and using AI often requires vast personal data. Models can also inadvertently reveal private information from their training set.', 4),
    mc('Who is responsible when an AI system makes a harmful mistake?', ['The AI itself, since it made the decision', 'No one — AI mistakes are unpredictable', 'The developers, deployers, and organizations using the AI', 'Only the end user who prompted the AI'], 'The developers, deployers, and organizations using the AI', 'AI systems are built and deployed by humans and organizations — accountability for harms lies with those who created and deployed the system.', 5),
  ],
}
