import type { ExerciseDef } from '../types'

function mc(question: string, options: string[], correctAnswer: string, explanation: string, order: number): ExerciseDef {
  return { question, type: 'MULTIPLE_CHOICE', options, correctAnswer, explanation, order }
}

export const techExercises6: Record<string, ExerciseDef[]> = {
  'spreadsheet-basics': [
    mc('In a spreadsheet, a cell address like "B3" refers to:', ['Row B, Column 3', 'Column B, Row 3', 'The third cell in the entire spreadsheet', 'Sheet B, Position 3'], 'Column B, Row 3', 'Spreadsheet addresses use column letter first (A, B, C...) then row number (1, 2, 3...). B3 is at the intersection of column B and row 3. Understanding addressing is fundamental for writing formulas that reference other cells.', 1),
    mc('A formula in a spreadsheet must begin with:', ['A cell reference', 'An equals sign (=)', 'A function name like SUM', 'A number'], 'An equals sign (=)', 'Any cell entry starting with = is treated as a formula. =B2+C2 adds two cells. Without =, the entry is treated as literal text. This is the fundamental rule of spreadsheet formulas.', 2),
    mc('What is the difference between absolute and relative cell references?', ['Absolute references use numbers; relative use letters', 'Relative references (A1) change when copied; absolute references ($A$1) stay fixed', 'Absolute references point to values on other sheets; relative references stay on the same sheet', 'There is no difference in modern spreadsheet applications'], 'Relative references (A1) change when copied; absolute references ($A$1) stay fixed', 'Copy a formula with A1 down one row and it becomes A2. Copy $A$1 anywhere and it always refers to A1. Mix them: A$1 fixes the row; $A1 fixes the column. Essential for building formulas that copy correctly across a table.', 3),
    mc('Which formula correctly sums all values in cells A1 through A10?', ['=ADD(A1:A10)', '=SUM(A1:A10)', '=TOTAL(A1,A10)', '=A1+A2+A3+A4+A5+A6+A7+A8+A9+A10'], '=SUM(A1:A10)', 'SUM is the most used spreadsheet function. A1:A10 is a range reference — all cells from A1 to A10. Writing out every addition is error-prone and breaks if rows are inserted. Always use range functions for efficiency.', 4),
    mc('When you sort a data table, which of the following is essential to avoid corrupting the data?', ['Selecting only the column you want to sort before sorting', 'Selecting the entire table (all columns) so all rows stay together during sorting', 'Converting the data to text format before sorting', 'Removing any formulas before sorting'], 'Selecting the entire table (all columns) so all rows stay together during sorting', 'Sorting only one column while leaving others in place detaches names from their data, prices from their products, etc. Always select the full dataset (or let the application detect the full range) so each row moves as a unit.', 5),
  ],
  'common-functions': [
    mc('The VLOOKUP function is used to:', ['Calculate the average of a vertical column', 'Search for a value in the first column of a range and return a corresponding value from another column in that row', 'Count all non-empty cells in a column', 'Find the maximum value in a vertical range'], 'Search for a value in the first column of a range and return a corresponding value from another column in that row', 'VLOOKUP(lookup_value, table_range, column_index, exact_match). Classic use: look up a product ID in column A and return its price from column C. INDEX/MATCH is more flexible but VLOOKUP remains widely used.', 1),
    mc('The IF function syntax is IF(condition, value_if_true, value_if_false). What does =IF(A1>100,"High","Low") return if A1=85?', ['High', 'Low', 'ERROR', '85'], 'Low', '85 > 100 is FALSE, so the function returns the value_if_false argument: "Low". If A1 were 150, it would return "High". IFs can be nested — IF(cond1, val1, IF(cond2, val2, val3)) — though this gets complex.', 2),
    mc('COUNTIF counts cells that meet a condition. =COUNTIF(B2:B20,"Yes") does what?', ['Sums all values in B2:B20 where another column says "Yes"', 'Counts how many cells in B2:B20 contain exactly the text "Yes"', 'Checks if "Yes" appears at least once in B2:B20', 'Returns the row number of the first "Yes" in B2:B20'], 'Counts how many cells in B2:B20 contain exactly the text "Yes"', 'COUNTIF(range, criteria) counts cells matching the criteria. SUMIF(range, criteria, sum_range) sums values where a condition is met. AVERAGEIF does the same for averages. These are essential for conditional analysis without pivot tables.', 3),
    mc('CONCATENATE (or the & operator) is used to:', ['Find the longest text string in a column', 'Join two or more text strings or cell values into one', 'Split a text cell into multiple columns', 'Count the number of characters in a cell'], 'Join two or more text strings or cell values into one', '=A1&" "&B1 joins first name, a space, and last name from two cells. =CONCATENATE(A1," ",B1) does the same. In modern Excel/Sheets, TEXTJOIN is more powerful. & is often more readable than the function form.', 4),
    mc('What does the TODAY() function return in a spreadsheet?', ['A static date that was entered when the function was first typed', 'The current date, which updates automatically each time the file is opened or recalculated', 'The date the file was last saved', 'The deadline date stored in a separate settings cell'], 'The current date, which updates automatically each time the file is opened or recalculated', 'TODAY() is a volatile function — it recalculates automatically. Useful for calculating how many days have elapsed since an event (=TODAY()-StartDate) or highlighting overdue items. NOW() returns the current date and time.', 5),
  ],
  'sorting-and-filtering': [
    mc('Filtering a spreadsheet data table does what?', ['Permanently removes rows that don\'t match the filter criteria', 'Temporarily hides rows that don\'t match the filter, without deleting data', 'Sorts the visible data according to the filter criteria', 'Creates a separate filtered copy on a new sheet'], 'Temporarily hides rows that don\'t match the filter, without deleting data', 'Filters hide non-matching rows — the data still exists and reappears when the filter is cleared or changed. Row numbers in filtered views are non-sequential (you might see rows 1, 5, 12, 23) because the others are hidden.', 1),
    mc('A multi-level sort (sorting by multiple columns) is used when:', ['You want to sort by one column and ignore all others', 'The primary sort column has many tied values and you want to apply a secondary sort to break ties', 'You need to sort numbers and text separately', 'Your data has more than 1,000 rows and single-column sort is too slow'], 'The primary sort column has many tied values and you want to apply a secondary sort to break ties', 'Example: sort by Department first, then by Last Name within each department. Multi-level sorting ensures a meaningful order when the primary key has repeated values.', 2),
    mc('To quickly find all transactions over $500 in a large dataset, the most efficient method is:', ['Manually scrolling through all rows', 'Sorting the amount column descending and reading the top rows', 'Using a column filter with a "greater than 500" criterion', 'Using VLOOKUP to find matching rows'], 'Using a column filter with a "greater than 500" criterion', 'Number filters in spreadsheets support conditions like "greater than," "between," "equals," and "top 10." Applying a filter shows only matching rows instantly, regardless of dataset size.', 3),
    mc('When using Text-to-Columns to split data (like "Last, First" into two columns), you need to specify:', ['The number of characters in the longest entry', 'The delimiter (comma, space, tab, etc.) or fixed-width positions where the split should occur', 'The destination format (text vs. number) for the resulting columns', 'The sort order for the resulting columns after splitting'], 'The delimiter (comma, space, tab, etc.) or fixed-width positions where the split should occur', 'Text-to-Columns splits a single cell\'s content across multiple columns. Delimiter mode splits on a character (comma, tab, space). Fixed-width mode splits at specific character positions. Used frequently for cleaning imported data.', 4),
    mc('The "Remove Duplicates" feature in a spreadsheet should be used carefully because:', ['It permanently deletes matching rows without moving them to a recycle bin', 'It always removes all matching rows including the original', 'It can only remove exact duplicates, not similar entries', 'It only works on columns, not entire rows'], 'It permanently deletes matching rows without moving them to a recycle bin', 'Remove Duplicates immediately and permanently deletes rows. Always work on a copy or use Undo immediately if the result is wrong. Define which columns to check for duplication — matching on ALL columns vs. just a key column gives very different results.', 5),
  ],
  'pivot-tables': [
    mc('A pivot table is used to:', ['Create a chart from existing data', 'Quickly summarize, group, and analyze large datasets without writing formulas', 'Validate data entry against a list of allowed values', 'Link data between two separate spreadsheet files'], 'Quickly summarize, group, and analyze large datasets without writing formulas', 'Pivot tables transform raw transactional data (thousands of rows) into summaries: total sales by region, count of orders per product, average rating by month. They recalculate instantly when the source data changes or you rearrange fields.', 1),
    mc('In a pivot table, "Row Labels" determine:', ['Which columns display numerical values', 'How data is grouped along the left side of the table — each unique value becomes a row', 'The sort order of the entire dataset', 'Which fields appear in chart legends'], 'How data is grouped along the left side of the table — each unique value becomes a row', 'If you put "Department" in Row Labels, each department gets its own row. Values (like sum of sales) are then calculated for each group. Nesting row labels creates drill-down hierarchies: Region > Department > Employee.', 2),
    mc('To refresh a pivot table after the source data has been updated, you must:', ['Delete and recreate the pivot table', 'Right-click the pivot table and choose Refresh, or manually trigger recalculation', 'The pivot table updates automatically without any action required', 'Re-import the source data from its original location'], 'Right-click the pivot table and choose Refresh, or manually trigger recalculation', 'Pivot tables don\'t update automatically when source data changes (in most applications). Right-click > Refresh recalculates all values. Some applications allow automatic refresh on file open. This is a common oversight when reporting on frequently updated data.', 3),
    mc('A calculated field in a pivot table allows you to:', ['Apply conditional formatting to cells based on their values', 'Create a new field based on a formula using other pivot table fields', 'Import additional data into the pivot cache from another source', 'Filter which source rows are included in the pivot analysis'], 'Create a new field based on a formula using other pivot table fields', 'Calculated fields create derived metrics: Profit = Revenue - Cost, or Margin = Revenue / Cost - 1. These calculated fields appear as if they were columns in the source data and can be added to the Values area.', 4),
    mc('Slicers in a pivot table are:', ['Tools to cut large datasets into smaller files', 'Visual filter controls that let you click to filter the pivot table by specific categories', 'Formulas that extract specific rows from the source data', 'Charts connected to pivot table data for visual analysis'], 'Visual filter controls that let you click to filter the pivot table by specific categories', 'Slicers are buttons representing each unique value in a field. Clicking a slicer button filters the pivot table to show only that category. Multiple slicers can work together. They make interactive dashboards accessible to non-technical users.', 5),
  ],
  'charts-and-visualization': [
    mc('A bar chart is most appropriate for:', ['Showing how a value changes continuously over time', 'Comparing discrete categories or groups to each other', 'Displaying the relationship between two continuous variables', 'Showing how parts relate to a whole as percentages'], 'Comparing discrete categories or groups to each other', 'Bar charts (vertical = column chart, horizontal = bar chart) excel at comparing amounts across categories: sales by region, students by grade, votes by candidate. They are the workhorse of data visualization.', 1),
    mc('A line chart is best suited for:', ['Comparing parts of a whole at one point in time', 'Showing trends in data over a continuous time period', 'Displaying correlations between two unrelated variables', 'Showing the distribution of values within a dataset'], 'Showing trends in data over a continuous time period', 'Line charts show how values change over time (monthly sales, daily temperature, stock prices). The connected line implies continuity — that values between measured points exist. Don\'t use line charts for unrelated categories.', 2),
    mc('Misleading charts often use which tactic to exaggerate differences?', ['Using colors that are difficult to distinguish', 'Truncating the y-axis (starting at a non-zero value) to make small differences look dramatic', 'Displaying too many data points on a single chart', 'Using 3D effects that distort relative sizes'], 'Truncating the y-axis (starting at a non-zero value) to make small differences look dramatic', 'A chart showing values between 99% and 100% looks dramatic if the y-axis starts at 99%. Starting at 0 would show a barely perceptible difference. Truncated axes are used deliberately (and accidentally) to manipulate interpretation.', 3),
    mc('A scatter plot is best used for:', ['Comparing sales across multiple product categories', 'Exploring the relationship or correlation between two numerical variables', 'Showing how a market is divided among competitors', 'Displaying data that changes over a time period'], 'Exploring the relationship or correlation between two numerical variables', 'Each point in a scatter plot represents an observation with both an X and a Y value. Patterns reveal correlation: points trending up-right show positive correlation; trending down-right show negative correlation; random scatter shows no correlation.', 4),
    mc('Pie charts are appropriate when:', ['You have many categories to compare', 'You want to show data changes over time', 'You have a few categories (ideally 5 or fewer) that together make up 100% of something', 'Your audience needs to read precise values from the chart'], 'You have a few categories (ideally 5 or fewer) that together make up 100% of something', 'Pie charts show part-to-whole relationships. With many slices, they become hard to read — humans struggle to compare small angle differences. For more than 5-6 categories, a bar chart with sorted values is almost always clearer.', 5),
  ],
  'data-cleaning': [
    mc('Data cleaning is necessary before analysis because:', ['Raw data must be converted to binary format before statistical functions can process it', 'Real-world data contains inconsistencies, errors, missing values, and formatting issues that produce incorrect analysis if not addressed', 'Spreadsheet functions refuse to operate on uncleaned data', 'Dirty data slows down spreadsheet performance by overloading memory'], 'Real-world data contains inconsistencies, errors, missing values, and formatting issues that produce incorrect analysis if not addressed', '"Garbage in, garbage out." Inconsistent spellings ("NY", "New York", "new york"), extra spaces, wrong data types, and duplicate entries produce wrong counts, failed lookups, and misleading charts if not corrected first.', 1),
    mc('The TRIM function in a spreadsheet:', ['Cuts text longer than a specified length', 'Removes leading and trailing spaces from text, and normalizes multiple spaces within text to single spaces', 'Trims a column to a specified width in the view', 'Removes numbers from a text string'], 'Removes leading and trailing spaces from text, and normalizes multiple spaces within text to single spaces', 'Invisible spaces are a common data quality issue. " New York" and "New York" look identical but don\'t match in lookups or comparisons. TRIM fixes this. Apply it to all text columns before analysis.', 2),
    mc('When you import a column of dates that appears as text (not recognized by date functions), the best approach is:', ['Manually re-enter all dates in the correct format', 'Use Text-to-Columns or DATEVALUE() to convert the text to actual date values the application recognizes', 'Apply a date format to the cells and the values will convert automatically', 'Use the IF function to check if each value is a date'], 'Use Text-to-Columns or DATEVALUE() to convert the text to actual date values the application recognizes', 'Text dates (like "01/15/2024" stored as text) won\'t work with date functions or sort correctly. Text-to-Columns with Date delimiter parsing or DATEVALUE() converts them to numeric date serial values that the spreadsheet recognizes.', 3),
    mc('Identifying duplicate entries in a dataset can be done quickly by:', ['Manually scrolling through sorted data looking for repeated values', 'Using Conditional Formatting to highlight duplicates, or COUNTIF to flag values appearing more than once', 'Importing the data into a database which automatically prevents duplicates', 'Sorting alphabetically and trusting that duplicates will be adjacent'], 'Using Conditional Formatting to highlight duplicates, or COUNTIF to flag values appearing more than once', 'Conditional Formatting > Highlight Cells > Duplicate Values instantly colors repeated values. A helper column with =COUNTIF($A$1:$A$1000,A1)>1 flags each duplicate. Both approaches work for identifying before using Remove Duplicates.', 4),
    mc('Data validation in a spreadsheet prevents bad data entry by:', ['Automatically correcting typos in cells', 'Restricting what can be entered in a cell — numbers only, from a dropdown list, within a date range, etc.', 'Alerting the data entry person after they submit an incorrect form', 'Running spell-check on all text columns automatically'], 'Restricting what can be entered in a cell — numbers only, from a dropdown list, within a date range, etc.', 'Data Validation (Data > Validation) rules are applied to cells before entry. A dropdown list prevents free-form text that creates inconsistent categories. A number range (1-100) rejects invalid scores. Prevention is better than cleaning after the fact.', 5),
  ],
  'introduction-to-sql': [
    mc('SQL (Structured Query Language) is used to:', ['Style and format the visual output of database results', 'Create, read, update, and delete data in a relational database', 'Define the physical storage structure of database files on disk', 'Connect applications to network services'], 'Create, read, update, and delete data in a relational database', 'SQL is the language for talking to relational databases (MySQL, PostgreSQL, SQLite, SQL Server). SELECT retrieves data. INSERT adds data. UPDATE modifies data. DELETE removes data. CREATE and ALTER manage table structure.', 1),
    mc('A basic SQL SELECT statement "SELECT name, age FROM users WHERE age > 25" does what?', ['Creates a new table with name and age columns', 'Returns name and age from every row in the users table where age is greater than 25', 'Counts how many users are over 25', 'Deletes users over 25 from the database'], 'Returns name and age from every row in the users table where age is greater than 25', 'SELECT specifies which columns to return. FROM specifies the table. WHERE filters which rows to include. Only rows meeting the condition (age > 25) are returned. SELECT * returns all columns.', 2),
    mc('What does the ORDER BY clause do in SQL?', ['Filters rows based on a condition', 'Sorts the result rows by a specified column in ascending or descending order', 'Groups rows with matching values for aggregate functions', 'Limits the number of rows returned'], 'Sorts the result rows by a specified column in ascending or descending order', 'ORDER BY column_name ASC (ascending, default) or DESC (descending) sorts results. SELECT * FROM products ORDER BY price DESC returns products from most to least expensive. Without ORDER BY, result order is not guaranteed.', 3),
    mc('SQL JOINs are used to:', ['Merge two tables into one permanent table', 'Combine rows from multiple tables based on a related column (like a shared ID)', 'Append new rows to an existing table from another table', 'Create a backup copy of a table with an alternate name'], 'Combine rows from multiple tables based on a related column (like a shared ID)', 'INNER JOIN returns rows where both tables have a matching value in the join column. SELECT orders.id, customers.name FROM orders INNER JOIN customers ON orders.customer_id = customers.id links orders to customer names.', 4),
    mc('GROUP BY in SQL is used with aggregate functions (SUM, COUNT, AVG) to:', ['Sort results into groups for display purposes only', 'Calculate aggregate values for each unique value in a column', 'Filter groups based on conditions using the WHERE clause', 'Join tables based on matching values in a group of columns'], 'Calculate aggregate values for each unique value in a column', 'SELECT department, COUNT(*) FROM employees GROUP BY department counts employees per department. Each unique department becomes a row in the result with its count. HAVING (not WHERE) filters groups after aggregation.', 5),
  ],
}
