import type { ExerciseDef } from '../types'

function mc(question: string, options: string[], correctAnswer: string, explanation: string, order: number): ExerciseDef {
  return { question, type: 'MULTIPLE_CHOICE', options, correctAnswer, explanation, order }
}

export const techExercises2: Record<string, ExerciseDef[]> = {
  'ip-addresses-and-dns': [
    mc('An IP address serves what purpose on the internet?', ['It encrypts data during transmission', 'It uniquely identifies a device on a network, allowing data to be sent to the correct destination', 'It measures the speed of a network connection', 'It stores website content so pages load faster'], 'It uniquely identifies a device on a network, allowing data to be sent to the correct destination', 'Every device on the internet has an IP address — a unique numerical label (like 192.168.1.1 for IPv4). Routers use IP addresses to determine where to send each packet, just like a postal address directs mail.', 1),
    mc('DNS (Domain Name System) translates:', ['Website content into the language of the browser', 'Human-readable domain names (like google.com) into IP addresses', 'IP addresses into physical locations for tracking purposes', 'Encrypted data into readable form for browsers'], 'Human-readable domain names (like google.com) into IP addresses', 'DNS is the internet\'s "phone book." When you type google.com, your device asks a DNS server for the corresponding IP address (142.250.80.46, for example), then connects to that IP. Without DNS, you\'d have to memorize IP addresses.', 2),
    mc('IPv6 was developed to replace IPv4 primarily because:', ['IPv6 is faster due to a simpler header format', 'IPv4\'s roughly 4.3 billion addresses are nearly exhausted; IPv6 provides approximately 340 undecillion addresses', 'IPv6 is more secure by default than IPv4', 'IPv6 eliminates the need for DNS by encoding domain names in the address'], 'IPv4\'s roughly 4.3 billion addresses are nearly exhausted; IPv6 provides approximately 340 undecillion addresses', 'IPv4 uses 32-bit addresses (2^32 ≈ 4.3 billion). With smartphones, IoT devices, and global growth, we\'ve run out. IPv6 uses 128-bit addresses (2^128 ≈ 340 undecillion) — enough for every atom on Earth to have multiple addresses.', 3),
    mc('What is a "private" IP address range (like 192.168.x.x)?', ['IP addresses reserved for government and military use', 'Address ranges reserved for internal use within networks — not routable on the public internet', 'Addresses assigned to the most secure servers that hide their identity', 'IPv6 addresses that have been shortened for readability'], 'Address ranges reserved for internal use within networks — not routable on the public internet', 'RFC 1918 defines private ranges (10.x.x.x, 172.16-31.x.x, 192.168.x.x) for internal networks. Your home router assigns these. NAT (Network Address Translation) maps these private IPs to your single public IP for internet access.', 4),
    mc('When you type a URL in your browser, the order of events begins with:', ['The browser downloading the webpage immediately from cache', 'A DNS query to resolve the domain name to an IP address', 'An HTTPS handshake to encrypt the connection', 'The browser sending your request to your ISP for approval'], 'A DNS query to resolve the domain name to an IP address', 'The browser must know where to connect before it can request the page. Step 1: DNS query (what is the IP for this domain?). Step 2: TCP connection to that IP. Step 3: TLS handshake (for HTTPS). Step 4: HTTP request for the page content.', 5),
  ],
  'http-and-https': [
    mc('HTTP (Hypertext Transfer Protocol) is the foundation of web communication. What does it define?', ['How data is physically transmitted over cables and wireless connections', 'The format and rules for requests and responses between web browsers and servers', 'The encryption standard used to secure web traffic', 'The structure of HTML documents that browsers display'], 'The format and rules for requests and responses between web browsers and servers', 'HTTP is an application-layer protocol defining how clients (browsers) request resources and how servers respond. It is a request-response protocol: client sends a GET request for a URL; server responds with the content and a status code.', 1),
    mc('HTTPS differs from HTTP in that HTTPS:', ['Uses a different port and faster routing through the internet', 'Encrypts all communication between browser and server using TLS, preventing eavesdropping and tampering', 'Only works on websites that have been verified by the government', 'Compresses data to deliver pages faster'], 'Encrypts all communication between browser and server using TLS, preventing eavesdropping and tampering', 'HTTPS wraps HTTP in TLS (Transport Layer Security). Without it, anyone on the same network can read your traffic. With it, data is encrypted end-to-end. Browsers show a padlock icon for HTTPS connections.', 2),
    mc('An HTTP status code of 404 means:', ['The server refused the connection for security reasons', 'The requested resource was not found on the server', 'The request was successfully completed', 'The server is temporarily unavailable'], 'The requested resource was not found on the server', '404 Not Found is returned when the server can\'t find the requested URL. 200 = OK (success). 301 = redirect. 403 = forbidden. 500 = internal server error. Status codes tell clients what happened with each request.', 3),
    mc('HTTP cookies are used for what purpose?', ['To store website files locally for faster loading (that is caching)', 'To maintain session state — remembering login status, preferences, and shopping cart items across requests', 'To track user location for compliance with local laws', 'To share data between different websites the user visits'], 'To maintain session state — remembering login status, preferences, and shopping cart items across requests', 'HTTP is stateless — each request is independent. Cookies allow servers to identify returning users by storing a small token on the browser. When you log in, the server sets a cookie; subsequent requests send that cookie to prove identity.', 4),
    mc('What does an HTTP GET request do vs. a POST request?', ['GET requests data from the server; POST sends data to the server', 'GET is encrypted; POST is not', 'GET works for HTML only; POST works for all file types', 'GET is used by search engines; POST is used by authenticated users'], 'GET requests data from the server; POST sends data to the server', 'GET retrieves resources (loading a webpage). POST submits data to be processed (submitting a form, logging in). GET parameters appear in the URL; POST data is in the request body and is not stored in browser history.', 5),
  ],
  'packets-and-routing': [
    mc('Why is internet data divided into packets rather than sent as one continuous stream?', ['Packets allow data to be compressed more efficiently during transmission', 'Packets allow different parts of data to take different network paths and be reassembled at the destination, enabling efficient use of network capacity', 'Packets prevent encryption from being applied to the entire data stream at once', 'Packets reduce the processing burden on the sender by allowing intermittent transmission'], 'Packets allow different parts of data to take different network paths and be reassembled at the destination, enabling efficient use of network capacity', 'Breaking data into packets allows them to be routed independently, distributed across available paths, and prioritized. If one packet is lost, only that packet needs to be retransmitted. This is the foundation of packet-switched networking.', 1),
    mc('A router\'s primary function is to:', ['Convert between wired and wireless network signals', 'Forward packets between networks based on IP addresses, directing them toward their destination', 'Assign IP addresses to devices on the local network', 'Encrypt data before it leaves the local network'], 'Forward packets between networks based on IP addresses, directing them toward their destination', 'Routers examine each packet\'s destination IP address and consult routing tables to determine the best next hop toward the destination. They connect different networks — your home network to the internet, or two ISP networks to each other.', 2),
    mc('TCP (Transmission Control Protocol) guarantees reliable delivery by:', ['Sending data through multiple paths simultaneously', 'Requiring the receiver to acknowledge received packets and retransmitting any that are lost', 'Encrypting packets so they cannot be modified in transit', 'Reducing packet size to minimize the chance of errors during transmission'], 'Requiring the receiver to acknowledge received packets and retransmitting any that are lost', 'TCP establishes a connection, numbers each packet, requires acknowledgment (ACK) for each, and retransmits unacknowledged packets. This ensures data arrives complete and in order — essential for web pages, email, and file downloads.', 3),
    mc('UDP (User Datagram Protocol) is preferred over TCP for live video and gaming because:', ['UDP provides stronger encryption for real-time content', 'UDP has no acknowledgment or retransmission — it is faster at the cost of reliability, and lost packets are preferable to delayed ones in real-time applications', 'UDP was specifically designed for multimedia and automatically adjusts bitrate', 'UDP routes packets more efficiently through congested networks'], 'UDP has no acknowledgment or retransmission — it is faster at the cost of reliability, and lost packets are preferable to delayed ones in real-time applications', 'In live video, a late packet is worse than a missing one — a one-second delay for retransmission breaks the real-time experience. UDP drops lost packets and keeps moving. The application (not the protocol) handles any needed error correction.', 4),
    mc('TTL (Time to Live) in a network packet prevents:', ['Data from being transmitted unencrypted on public networks', 'Packets from circling indefinitely in routing loops by limiting the number of hops a packet can traverse', 'Users from accessing content after a set time for digital rights management', 'Connections from staying open longer than the server allows'], 'Packets from circling indefinitely in routing loops by limiting the number of hops a packet can traverse', 'TTL is decremented by 1 at each router. When it reaches 0, the packet is discarded and the sender is notified. Without TTL, a routing error could cause a packet to bounce between routers forever, consuming network bandwidth.', 5),
  ],
  'routers-and-wifi': [
    mc('The difference between a router and a switch in a home network is:', ['A router connects to the internet; a switch connects multiple wired devices within the same local network', 'A router handles Wi-Fi; a switch handles wired connections only', 'Routers are faster but more expensive; switches are slower and cheaper', 'There is no practical difference for home use — both perform the same function'], 'A router connects to the internet; a switch connects multiple wired devices within the same local network', 'A router connects different networks (your LAN to the internet) and handles NAT/DHCP. A switch expands the number of wired ports on your local network, forwarding traffic between connected devices using MAC addresses.', 1),
    mc('Wi-Fi 6 (802.11ax) improves over Wi-Fi 5 (802.11ac) primarily by:', ['Using a completely new frequency band that previous devices cannot detect', 'Handling more devices simultaneously more efficiently — especially in dense environments like apartments and offices', 'Doubling the maximum transmission range in open areas', 'Eliminating the need for a router by allowing devices to connect peer-to-peer'], 'Handling more devices simultaneously more efficiently — especially in dense environments like apartments and offices', 'Wi-Fi 6 introduces OFDMA (Orthogonal Frequency Division Multiple Access) that allows a single transmission to serve multiple clients simultaneously. This dramatically improves performance in dense environments with many connected devices.', 2),
    mc('The 2.4 GHz vs 5 GHz Wi-Fi bands differ in that:', ['2.4 GHz is faster but has shorter range; 5 GHz is slower with longer range', '2.4 GHz has longer range but slower speeds and more congestion; 5 GHz has faster speeds but shorter range', '2.4 GHz is for older devices only; new devices use 5 GHz exclusively', 'There is no performance difference — the numbers refer only to router pricing tiers'], '2.4 GHz has longer range but slower speeds and more congestion; 5 GHz has faster speeds but shorter range', '2.4 GHz penetrates walls better and covers more distance but tops out at lower speeds and is crowded (shared with microwaves, Bluetooth, baby monitors). 5 GHz offers much faster speeds but drops off more quickly through walls and over distance.', 3),
    mc('WPA3 is the current Wi-Fi security standard. It improves over WPA2 by:', ['Using a longer password requirement to prevent brute-force attacks', 'Using a more secure key exchange (SAE) that prevents offline dictionary attacks even if a weak password is used', 'Requiring devices to register with the router before connecting', 'Encrypting only sensitive traffic automatically, leaving casual browsing unencrypted for speed'], 'Using a more secure key exchange (SAE) that prevents offline dictionary attacks even if a weak password is used', 'WPA2\'s 4-way handshake can be captured and cracked offline against password dictionaries. WPA3\'s SAE (Simultaneous Authentication of Equals) makes each handshake unique, so capturing traffic doesn\'t enable offline guessing.', 4),
    mc('DHCP (Dynamic Host Configuration Protocol) automatically assigns to devices on a network:', ['A MAC address unique to each network interface', 'An IP address, subnet mask, default gateway, and DNS server — without manual configuration', 'A username and password for network access', 'A unique hostname visible to other devices on the network'], 'An IP address, subnet mask, default gateway, and DNS server — without manual configuration', 'Without DHCP, every device on every network would need manual IP configuration. DHCP servers (usually the router in home networks) automatically provide all required network settings when a device connects.', 5),
  ],
  'ports-and-protocols': [
    mc('Network ports are used to:', ['Physically connect devices to the router using cables', 'Distinguish between different services or applications running on the same IP address', 'Measure network throughput in megabits per second', 'Encrypt specific types of traffic while leaving others unencrypted'], 'Distinguish between different services or applications running on the same IP address', 'A port is a number (0-65535) that identifies which application on a server should receive a packet. A single server IP may run a web server (port 80/443), email (port 25/587), and SSH (port 22) simultaneously. Ports separate the traffic.', 1),
    mc('Port 443 is associated with which protocol?', ['FTP (File Transfer Protocol)', 'SMTP (email)', 'HTTPS (secure web traffic)', 'DNS (domain name resolution)'], 'HTTPS (secure web traffic)', 'Well-known port assignments: 80 = HTTP, 443 = HTTPS, 22 = SSH, 25 = SMTP (email), 53 = DNS, 21 = FTP. Knowing these helps with network troubleshooting and understanding firewall rules.', 2),
    mc('SSH (Secure Shell) is used for:', ['Securely sharing files between desktop computers on a local network', 'Encrypted remote access to a command-line interface on another computer, typically a server', 'Sending encrypted email between servers', 'Streaming encrypted audio and video over a local network'], 'Encrypted remote access to a command-line interface on another computer, typically a server', 'SSH allows you to control a remote computer\'s command line over an encrypted connection. System administrators use SSH to manage servers. It replaced unencrypted Telnet. SSH key authentication is more secure than passwords.', 3),
    mc('A firewall controls network traffic by:', ['Encrypting all data passing through the network interface', 'Examining packets and allowing or blocking them based on rules (port, IP, protocol, etc.)', 'Caching frequently visited websites to speed up internet access', 'Compressing outbound traffic to reduce bandwidth usage'], 'Examining packets and allowing or blocking them based on rules (port, IP, protocol, etc.)', 'A firewall is a security boundary. Rules define what traffic is permitted: allow port 443 from anywhere, block all inbound port 22, allow only internal traffic on port 3306. Firewalls can be hardware (router) or software (OS firewall).', 4),
    mc('The protocol layer model (like the OSI model) is useful because:', ['It guarantees all network implementations will be compatible', 'It separates network communication into distinct functional layers so each layer can be designed independently', 'It defines exact hardware specifications that all network equipment must follow', 'It provides a legal framework for network communication standards'], 'It separates network communication into distinct functional layers so each layer can be designed independently', 'The layered model (Physical, Data Link, Network, Transport, Session, Presentation, Application) means Ethernet can be replaced by Wi-Fi without changing IP. HTTP can be added above TCP. Each layer communicates only with the layers immediately above and below it.', 5),
  ],
  'vpns-and-privacy': [
    mc('A VPN (Virtual Private Network) works by:', ['Providing a separate physical internet connection isolated from other users', 'Encrypting your traffic and routing it through a server in another location, masking your IP and protecting data from local eavesdropping', 'Blocking all tracking cookies and scripts automatically', 'Speeding up your connection by routing around congestion'], 'Encrypting your traffic and routing it through a server in another location, masking your IP and protecting data from local eavesdropping', 'A VPN creates an encrypted tunnel from your device to the VPN server. Your ISP and local network see only encrypted traffic to the VPN. Websites see the VPN server\'s IP, not yours. Useful on public Wi-Fi and for bypassing geographic restrictions.', 1),
    mc('Using a VPN makes you completely anonymous online. This statement is:', ['True — a VPN hides your identity entirely', 'False — the VPN provider knows your identity, and your behavior patterns, browser fingerprint, and logged-in accounts can still identify you', 'True only if you use a no-log VPN provider', 'Depends entirely on which country the VPN server is in'], 'False — the VPN provider knows your identity, and your behavior patterns, browser fingerprint, and logged-in accounts can still identify you', 'VPNs hide your IP from websites and your traffic from your ISP. But the VPN provider itself can see your traffic. You\'re still identifiable by cookies, browser fingerprinting, and login sessions. VPNs shift trust, not eliminate the need for it.', 2),
    mc('Incognito/private browsing mode in a browser prevents:', ['Your ISP and network from seeing your browsing activity', 'Websites from tracking you with cookies and fingerprinting', 'The browser from saving history, cookies, and form data locally on your device', 'Advertisers from collecting any data about your session'], 'The browser from saving history, cookies, and form data locally on your device', 'Incognito mode only prevents local storage — no browsing history, cookies, or saved passwords remain after the session. Your ISP, employer network, and the websites you visit can still see and log your activity.', 3),
    mc('Browser fingerprinting is a tracking technique that:', ['Uses cookies stored on your device to identify you', 'Builds a unique identifier from your browser configuration, screen resolution, installed fonts, and other attributes', 'Requires you to accept tracking when you visit a website', 'Only works when you are logged into a website'], 'Builds a unique identifier from your browser configuration, screen resolution, installed fonts, and other attributes', 'Your combination of browser version, OS, screen size, timezone, installed plugins, and other attributes is often unique enough to identify you across sessions and websites — even without cookies or a login. Blocking cookies alone doesn\'t prevent this.', 4),
    mc('End-to-end encryption (E2EE) in messaging apps means:', ['Messages are encrypted only between your device and the app\'s server', 'Only the sender and recipient can decrypt messages — not the app provider, their servers, or anyone in between', 'Messages are encrypted during transmission but decrypted for moderation before delivery', 'The app uses government-approved encryption standards on both ends'], 'Only the sender and recipient can decrypt messages — not the app provider, their servers, or anyone in between', 'E2EE means encryption keys exist only on the communicating devices. Signal, WhatsApp (when E2EE is active), and iMessage use E2EE. The company\'s servers relay encrypted data they cannot decrypt. Contrast with most email which is not E2EE.', 5),
  ],
  'what-is-programming': [
    mc('A computer program is fundamentally:', ['A collection of hardware components that perform a task', 'A set of instructions written in a programming language that a computer can execute', 'A graphical interface that allows users to interact with a computer', 'A mathematical formula that a calculator evaluates'], 'A set of instructions written in a programming language that a computer can execute', 'A program is a sequence of precise instructions. The computer follows them exactly, one at a time. Programming is the act of writing those instructions in a language the computer can understand and execute.', 1),
    mc('Source code written by a programmer must be converted to machine code because:', ['The programming language is proprietary and must be licensed before execution', 'CPUs execute only binary machine code (0s and 1s) — human-readable source code must be translated', 'Source code contains comments and formatting that would slow execution', 'Operating systems require a compiled format for security verification before running programs'], 'CPUs execute only binary machine code (0s and 1s) — human-readable source code must be translated', 'Humans write in high-level languages (Python, Java, C++). CPUs execute binary instructions specific to their architecture. A compiler or interpreter bridges this gap — translating human-readable code to executable machine instructions.', 2),
    mc('The difference between a compiled language and an interpreted language is:', ['Compiled languages are faster to write; interpreted languages are faster to run', 'Compiled languages are translated to machine code before execution; interpreted languages are translated line-by-line at runtime', 'Compiled languages work only on one OS; interpreted languages work on all platforms', 'There is no practical difference for most programming tasks'], 'Compiled languages are translated to machine code before execution; interpreted languages are translated line-by-line at runtime', 'Compilers (C, C++, Go) translate the entire program ahead of time, producing a fast executable. Interpreters (Python, JavaScript, Ruby) read and execute each line at runtime — more flexible but generally slower. Python\'s simplicity usually outweighs the speed difference.', 3),
    mc('An algorithm is:', ['The programming language used to write a solution', 'A step-by-step procedure for solving a problem or accomplishing a task', 'The compiled output of a program ready for execution', 'A data structure that organizes information efficiently'], 'A step-by-step procedure for solving a problem or accomplishing a task', 'An algorithm is a precisely defined sequence of steps that solves a problem. Sorting a list, finding the shortest path, and searching a database all have well-defined algorithms. Programming is translating algorithms into code.', 4),
    mc('Why is learning to debug (find and fix errors) as important as learning to write code?', ['Debuggers are the main productivity tool in professional programming', 'All real programs contain bugs, and the ability to diagnose and fix them determines how quickly you can build working software', 'Debugging is the only way to learn what code actually does', 'Professional programmers spend more time debugging than writing new code'], 'All real programs contain bugs, and the ability to diagnose and fix them determines how quickly you can build working software', 'Writing code and debugging are inseparable. Even experienced engineers spend substantial time diagnosing why code doesn\'t behave as expected. Systematic debugging — reading errors, using print statements, using a debugger — is a skill that compounds over a career.', 5),
  ],
}
