import type { ExerciseDef } from '../types'

function mc(question: string, options: string[], correctAnswer: string, explanation: string, order: number): ExerciseDef {
  return { question, type: 'MULTIPLE_CHOICE', options, correctAnswer, explanation, order }
}

export const techExercises1: Record<string, ExerciseDef[]> = {
  'cpu-memory-storage': [
    mc('What is the primary function of the CPU (Central Processing Unit)?', ['Storing programs and data permanently', 'Executing instructions — performing calculations and logic operations', 'Managing communication between the computer and external devices', 'Holding data temporarily while the CPU processes it'], 'Executing instructions — performing calculations and logic operations', 'The CPU is the "brain" — it fetches instructions from memory, decodes them, executes operations (arithmetic, logic, control), and stores results. Everything the computer does flows through the CPU.', 1),
    mc('What is the key difference between RAM and a hard drive?', ['RAM is faster but volatile (loses data when powered off); storage is slower but persistent', 'RAM holds more data but is slower; storage is fast and holds less', 'They perform the same function but at different price points', 'RAM stores the operating system; storage stores user files only'], 'RAM is faster but volatile (loses data when powered off); storage is slower but persistent', 'RAM (random access memory) is extremely fast but loses all data when power is removed. Hard drives and SSDs are much slower but retain data permanently. The OS loads from storage into RAM for fast access during use.', 2),
    mc('What does "64-bit processor" mean compared to 32-bit?', ['It runs at exactly twice the clock speed', 'It can process 64 bits of data at once and address vastly more RAM (up to 16 exabytes vs. 4 GB for 32-bit)', 'It has 64 cores, enabling 64 simultaneous tasks', 'It uses 64-bit encryption for all data it processes'], 'It can process 64 bits of data at once and address vastly more RAM (up to 16 exabytes vs. 4 GB for 32-bit)', 'A 64-bit processor handles data in 64-bit chunks and can address up to 2^64 bytes of memory. 32-bit processors were limited to 4 GB of RAM. This is why modern software and operating systems are 64-bit.', 3),
    mc('An SSD (Solid State Drive) is faster than an HDD (Hard Disk Drive) primarily because:', ['SSDs use a more efficient file system', 'SSDs have no moving parts — they use flash memory chips that can be accessed electronically', 'SSDs run at higher voltage, enabling faster data transfer', 'SSDs are connected to the CPU directly, bypassing the motherboard'], 'SSDs have no moving parts — they use flash memory chips that can be accessed electronically', 'HDDs have spinning platters and moving read/write heads — mechanical action limits speed and adds latency. SSDs access flash memory cells electronically with no mechanical delay, delivering 5-10x or more faster read/write speeds.', 4),
    mc('CPU clock speed (GHz) measures:', ['The number of cores available for parallel processing', 'How many instruction cycles the CPU can perform per second', 'The speed of data transfer between the CPU and RAM', 'How quickly the CPU heats up under load'], 'How many instruction cycles the CPU can perform per second', 'A 3.5 GHz CPU can perform 3.5 billion clock cycles per second. Each cycle may complete one or more instructions. Clock speed is one factor in performance — core count, architecture, and cache size also matter significantly.', 5),
  ],
  'how-data-is-stored': [
    mc('A bit is the smallest unit of digital information and can represent:', ['0 to 255', 'One of two states: 0 or 1', 'One character of text', 'A single pixel on a display'], 'One of two states: 0 or 1', 'Computers use binary — every piece of data is ultimately represented as sequences of 0s and 1s (bits). Physically, a bit represents a high or low voltage, a magnetic orientation, or a presence or absence of a charge.', 1),
    mc('How many bits are in one byte?', ['4', '8', '16', '32'], '8', 'One byte = 8 bits. A byte can represent 256 values (2^8). Bytes are the standard unit for measuring file sizes, memory, and storage. A single ASCII character (like the letter "A") is stored in one byte.', 2),
    mc('If a file is 1 megabyte (MB), how many bytes is that?', ['1,000 bytes', '1,024 bytes', 'Approximately 1,000,000 bytes (or exactly 1,048,576 in binary)', '1,000,000,000 bytes'], 'Approximately 1,000,000 bytes (or exactly 1,048,576 in binary)', 'In binary (base-2) computing, 1 MB = 2^20 = 1,048,576 bytes. In the decimal (SI) system used by storage manufacturers, 1 MB = 1,000,000 bytes. This discrepancy is why a "1 TB" drive shows less than 1 TB in your OS.', 3),
    mc('Binary uses base 2, meaning it only uses the digits 0 and 1. The binary number 1011 equals what in decimal?', ['5', '8', '11', '13'], '11', '1011 in binary: (1×8) + (0×4) + (1×2) + (1×1) = 8 + 0 + 2 + 1 = 11. Each position in binary represents a power of 2 (1, 2, 4, 8, 16...).', 4),
    mc('Hexadecimal (base 16) is commonly used in computing because:', ['It is easier for CPUs to process than binary', 'Each hex digit represents exactly 4 bits, making binary data more compact and readable for humans', 'It was the first number system used in early computers', 'It allows representing numbers larger than 32 bits'], 'Each hex digit represents exactly 4 bits, making binary data more compact and readable for humans', 'Hex uses 0-9 and A-F (16 values). One hex digit = 4 bits; two hex digits = one byte. A 32-bit value takes 32 binary digits but only 8 hex digits. Memory addresses, colors (#FF5733), and many technical values are expressed in hex.', 5),
  ],
  'input-output-devices': [
    mc('The distinction between input and output devices is:', ['Input devices receive data from the computer; output devices send data to the computer', 'Input devices send data to the computer for processing; output devices present results to the user', 'Input devices are wired; output devices are wireless', 'Input devices are used for data entry only; output devices can also send data to other computers'], 'Input devices send data to the computer for processing; output devices present results to the user', 'A keyboard, mouse, microphone, and camera are input devices — they send data into the computer. Monitors, speakers, and printers are output devices — they present processed information to the user. Some devices (touchscreens, network cards) are both.', 1),
    mc('A GPU (Graphics Processing Unit) is particularly useful for tasks beyond graphics because:', ['It has a faster clock speed than the CPU', 'It contains thousands of smaller cores optimized for parallel processing of identical operations simultaneously', 'It has direct access to long-term storage, bypassing RAM', 'It handles all floating-point arithmetic that the CPU cannot perform'], 'It contains thousands of smaller cores optimized for parallel processing of identical operations simultaneously', 'GPUs have thousands of smaller, simpler cores vs. a CPU\'s few powerful cores. This makes them ideal for massively parallel tasks like rendering pixels, training AI models, scientific simulation, and cryptocurrency mining.', 2),
    mc('USB (Universal Serial Bus) replaced many older interfaces because:', ['It is faster than all other connection types', 'It provides a single standardized connector for many device types and allows hot-swapping without rebooting', 'It delivers more power than other interfaces, eliminating the need for separate power adapters', 'It is wireless by design'], 'It provides a single standardized connector for many device types and allows hot-swapping without rebooting', 'Before USB, keyboards, mice, printers, and scanners all used different proprietary connectors. USB standardized connections and allowed devices to be added/removed without restarting the computer.', 3),
    mc('The main difference between a mechanical keyboard switch and a membrane keyboard is:', ['Mechanical keyboards use Bluetooth; membrane keyboards use wired connections', 'Mechanical keyboards use individual physical switches per key with tactile/audible feedback; membranes use a single sheet beneath all keys', 'Mechanical keyboards require special drivers; membrane keyboards are plug-and-play', 'Membrane keyboards are faster; mechanical are more accurate'], 'Mechanical keyboards use individual physical switches per key with tactile/audible feedback; membranes use a single sheet beneath all keys', 'Mechanical switches actuate at a defined travel point, providing tactile or clicky feedback. Membrane keyboards are cheaper to produce — pressing any key depresses a rubber dome against a membrane sheet. They feel "mushy" by comparison.', 4),
    mc('HDMI, DisplayPort, and USB-C are all standards that can carry:', ['Power only, not data or video', 'Audio and video signals (and in some cases data and power)', 'Only video signals at 4K or higher resolutions', 'Data only between computers, not display signals'], 'Audio and video signals (and in some cases data and power)', 'Modern video interfaces carry both audio and video. USB-C with DisplayPort Alt Mode can additionally carry data and power on the same cable. These multi-purpose standards reduce cable clutter compared to older single-function connections.', 5),
  ],
  'what-is-an-operating-system': [
    mc('An operating system\'s primary role is to:', ['Run application software directly without any intermediate layer', 'Manage hardware resources and provide a consistent interface for applications to use them', 'Provide internet access and security updates', 'Store user files in an organized structure'], 'Manage hardware resources and provide a consistent interface for applications to use them', 'The OS sits between hardware and applications. It manages CPU time, memory allocation, storage access, and device communication. Without the OS, every application would need to know how to control every piece of hardware directly.', 1),
    mc('The kernel of an operating system is:', ['The graphical user interface (desktop environment)', 'The core component that manages hardware directly and handles the most privileged system operations', 'The file manager that organizes user data', 'The application that controls system updates and security patches'], 'The core component that manages hardware directly and handles the most privileged system operations', 'The kernel runs at the highest privilege level and directly controls hardware. Everything else — the GUI, file explorer, even the login screen — runs on top of the kernel. A kernel crash results in a system crash (BSOD, kernel panic).', 2),
    mc('Which of the following is NOT an example of an operating system?', ['Windows 11', 'Ubuntu Linux', 'iOS', 'Microsoft Word'], 'Microsoft Word', 'Windows, Ubuntu, and iOS are operating systems. Microsoft Word is an application that runs on top of an operating system — it uses OS services but doesn\'t manage hardware or provide the foundational services other software relies on.', 3),
    mc('Virtual memory allows a computer to:', ['Run multiple operating systems simultaneously', 'Use storage space as an extension of RAM when physical RAM is full', 'Encrypt RAM contents for security', 'Separate RAM between different user accounts on the same machine'], 'Use storage space as an extension of RAM when physical RAM is full', 'When RAM fills up, the OS moves less-used memory pages to a swap file or paging file on disk. This allows more applications to run than RAM alone would support, at the cost of performance (disk access is much slower than RAM).', 4),
    mc('Process isolation in a modern OS means:', ['Only one process can run at a time, preventing conflicts', 'Each process runs in its own protected memory space and cannot directly access another process\'s memory', 'Processes on different user accounts cannot communicate', 'The OS prevents applications from accessing the internet without permission'], 'Each process runs in its own protected memory space and cannot directly access another process\'s memory', 'Process isolation prevents one crashed or malicious application from reading or corrupting another\'s memory. If a browser tab crashes, others continue. Without isolation, any buggy program could corrupt the entire system.', 5),
  ],
  'files-and-directories': [
    mc('In a file system hierarchy, the "root" directory is:', ['The first folder a user sees when they log in', 'The top-level directory from which all other directories branch', 'The directory where the operating system is installed', 'The directory where user account files are stored'], 'The top-level directory from which all other directories branch', 'The root is the top of the directory tree. On Unix/Linux it is /. On Windows each drive has its own root (C:\\). All other directories and files are descendants of the root in a hierarchical tree structure.', 1),
    mc('A file path like /home/user/documents/report.pdf tells you:', ['The file was created by the "user" account in the documents folder', 'The location of the file within the directory hierarchy: starting from root (/), then home, user, documents, and finally the file', 'The file is stored on a remote server (the / indicates a network path)', 'The file\'s content type based on the folder structure'], 'The location of the file within the directory hierarchy: starting from root (/), then home, user, documents, and finally the file', 'A file path describes exactly where a file is located. Each / separates a directory level. Starting with / means the path starts at the root. This precise addressing is how the OS locates any specific file on the system.', 2),
    mc('File extensions (like .jpg, .docx, .exe) indicate:', ['The size and creation date of the file', 'The file format, which tells the OS and applications how to interpret the file\'s contents', 'The level of encryption applied to the file', 'Who created the file and with what application'], 'The file format, which tells the OS and applications how to interpret the file\'s contents', 'Extensions are conventions that associate files with applications and formats. .jpg = JPEG image, .docx = Word document, .exe = Windows executable. The OS uses extensions to determine what program should open a file.', 3),
    mc('The difference between a hard link and a symbolic link (symlink) in a file system is:', ['Hard links work across drives; symlinks only work on the same drive', 'A hard link creates a second reference to the same data; a symlink is a pointer to a path (like a shortcut)', 'Symlinks can link to directories; hard links can only link to files', 'There is no practical difference for regular users'], 'A hard link creates a second reference to the same data; a symlink is a pointer to a path (like a shortcut)', 'A hard link is another name for the same underlying data — deleting one doesn\'t affect the other. A symlink is a path pointer — if the target is deleted or moved, the symlink breaks. Hard links can\'t span filesystems; symlinks can.', 4),
    mc('File permissions (read, write, execute) on a Unix/Linux system control:', ['Which file types can be stored in each directory', 'Who (owner, group, others) can view, modify, or run each file', 'How large a file can grow before it is automatically archived', 'When files are automatically backed up by the system'], 'Who (owner, group, others) can view, modify, or run each file', 'Unix permissions define three levels of access (read/write/execute) for three groups (owner, group members, all others). This prevents unauthorized modification of system files and separates user data between accounts on shared systems.', 5),
  ],
  'processes-and-memory': [
    mc('When you open an application, the operating system:', ['Reads the application from storage and executes it directly on disk', 'Loads the application\'s code and data from storage into RAM for the CPU to execute', 'Copies the application to RAM permanently until you manually remove it', 'Runs the application in a virtualized storage environment to protect the main disk'], 'Loads the application\'s code and data from storage into RAM for the CPU to execute', 'The CPU cannot execute code directly from a hard drive or SSD — the code must be in RAM first. The OS loads the program, allocates memory, creates a process, and the CPU begins executing instructions from RAM.', 1),
    mc('A process is "blocked" or "waiting" when:', ['It has exceeded its CPU time allocation for that scheduling interval', 'It is waiting for an event to occur (like I/O completion or user input) and cannot use the CPU productively', 'The OS has detected it consuming too much memory and suspended it', 'It is running in background mode with reduced priority'], 'It is waiting for an event to occur (like I/O completion or user input) and cannot use the CPU productively', 'A process waiting for a file read, network response, or keypress cannot productively run. The OS puts it in a blocked state and schedules other processes. When the event occurs, the OS moves it back to "ready" status.', 2),
    mc('Why does a computer slow down when many applications are open simultaneously?', ['The CPU slows its clock speed to prevent overheating', 'RAM fills up, causing the OS to use slower virtual memory (swapping to disk), and the CPU must share time among more processes', 'Opening applications fragments the hard drive, slowing all disk access', 'Network bandwidth is shared between more applications, reducing download speeds for all'], 'RAM fills up, causing the OS to use slower virtual memory (swapping to disk), and the CPU must share time among more processes', 'More processes compete for CPU time (requiring more context switching) and RAM. When RAM is exhausted, swapping to disk (which is much slower) causes dramatic slowdowns. Adding RAM often has more impact than a faster CPU for this reason.', 3),
    mc('A memory leak in an application occurs when:', ['The application reads data from unauthorized memory locations', 'The application allocates memory but never releases it, gradually consuming all available RAM', 'The application stores sensitive data in unencrypted memory', 'Memory contents are lost when the application is closed'], 'The application allocates memory but never releases it, gradually consuming all available RAM', 'Applications should release memory they no longer need. When they don\'t (a programming bug), that memory remains allocated and unavailable to other processes. Over time, a leaking app consumes more and more RAM until the system slows or crashes.', 4),
    mc('The Task Manager (Windows) or Activity Monitor (macOS) is useful for:', ['Scheduling tasks to run at specific times', 'Viewing running processes, their CPU/memory usage, and killing unresponsive ones', 'Managing which applications start when the computer boots', 'All of the above capabilities are present in these tools'], 'All of the above capabilities are present in these tools', 'Task Manager and Activity Monitor show running processes and their resource use, allow killing unresponsive programs, and often include startup management and resource history. They are the primary diagnostic tools for performance and unresponsive programs.', 5),
  ],
  'command-line-basics': [
    mc('The command line (terminal) differs from a graphical interface primarily in that:', ['The command line is faster for most users because no mouse is needed', 'The command line accepts text instructions directly, enabling automation, remote access, and operations not exposed in GUI', 'The command line is only available on Linux and macOS, not Windows', 'The command line bypasses the operating system and talks directly to hardware'], 'The command line accepts text instructions directly, enabling automation, remote access, and operations not exposed in GUI', 'The command line (CLI) allows precise control, scripting/automation, remote server management via SSH, and access to system features without a GUI. Many advanced operations are faster and more powerful via CLI than any graphical tool.', 1),
    mc('The command "cd documents" in a terminal does what?', ['Creates a new directory named "documents"', 'Changes the current working directory to the "documents" folder', 'Copies a file named "documents" to the current location', 'Displays the contents of the "documents" directory'], 'Changes the current working directory to the "documents" folder', 'cd = "change directory." It moves your terminal\'s working context into the specified directory. Subsequent commands operate from that location. cd .. moves up one level; cd ~ returns to the home directory.', 2),
    mc('What does the command "ls" (or "dir" on Windows) do?', ['Loads the system configuration', 'Lists the files and directories in the current directory', 'Displays the last system log entries', 'Locks the screen for security'], 'Lists the files and directories in the current directory', 'ls (list) on Unix/Linux/macOS and dir on Windows display the contents of the current directory. ls -la shows hidden files and detailed permissions. These are among the most frequently used commands.', 3),
    mc('In a command like "cat file.txt | grep error", what does the pipe (|) do?', ['Runs both commands simultaneously in separate windows', 'Sends the output of the first command as the input to the second command', 'Saves the output to a file named "error"', 'Separates two commands that run one after the other, regardless of success'], 'Sends the output of the first command as the input to the second command', 'The pipe is a fundamental Unix concept. cat file.txt outputs file contents; | sends that output to grep, which filters it. The result shows only lines containing "error." Chaining commands with pipes is the foundation of shell scripting.', 4),
    mc('What does adding "--help" or "-h" to most command-line commands do?', ['Connects to online help documentation via the internet', 'Displays usage instructions and available flags/options for that command', 'Enables a safe "help mode" that prevents the command from making changes', 'Asks the system administrator for remote assistance'], 'Displays usage instructions and available flags/options for that command', 'Most CLI tools support --help or -h to print usage information inline. The "man" command (manual) provides more comprehensive documentation. These are the first places to look when learning a new tool or forgetting an option.', 5),
  ],
}
