import type { ExerciseDef } from '../types'

function mc(question: string, options: string[], correctAnswer: string, explanation: string, order: number): ExerciseDef {
  return { question, type: 'MULTIPLE_CHOICE', options, correctAnswer, explanation, order }
}

export const techExercises4: Record<string, ExerciseDef[]> = {
  'dictionaries': [
    mc('A Python dictionary stores data as:', ['Ordered sequences indexed by integers', 'Key-value pairs where keys are unique identifiers for their associated values', 'Sets of unique values with no associated data', 'Sorted lists of tuples'], 'Key-value pairs where keys are unique identifiers for their associated values', 'Dictionaries (dicts) map unique keys to values: {"name": "Alice", "age": 30}. Keys can be strings, numbers, or other immutable types. Values can be anything. Fast key-based lookup is their primary advantage.', 1),
    mc('To access the value for a key in a Python dictionary, you use:', ['my_dict.get_value("key")', 'my_dict["key"] or my_dict.get("key")', 'my_dict.find("key")', 'my_dict[0]["key"]'], 'my_dict["key"] or my_dict.get("key")', 'my_dict["key"] returns the value or raises a KeyError if the key doesn\'t exist. my_dict.get("key") returns None (or a default) if the key is missing — safer for uncertain keys. Both are common patterns.', 2),
    mc('What happens when you assign a value to a key that already exists in a Python dictionary?', ['A new key-value pair is added alongside the existing one', 'The existing value is replaced with the new value', 'A KeyError is raised because duplicate keys are not allowed', 'The dictionary stores both values as a list under that key'], 'The existing value is replaced with the new value', 'Dictionary keys are unique. d["age"] = 25 followed by d["age"] = 30 results in d["age"] being 30 — the second assignment overwrites the first. This is useful for updating records.', 3),
    mc('Iterating over a dictionary with "for key in my_dict" gives you:', ['Both keys and values simultaneously', 'Only the keys', 'Only the values', 'Key-value pairs as tuples'], 'Only the keys', '"for key in my_dict" iterates over keys. "for value in my_dict.values()" iterates over values. "for key, value in my_dict.items()" iterates over (key, value) tuples. .items() is the most useful for cases where you need both.', 4),
    mc('When would you use a dictionary instead of a list?', ['When items need to be stored in a specific order', 'When you need fast lookup by a meaningful name/key rather than by position', 'When you need to store only one of each value (no duplicates)', 'When you need to perform mathematical operations on the stored values'], 'When you need fast lookup by a meaningful name/key rather than by position', 'Use a list when order matters and you access by position. Use a dict when you access by a meaningful identifier (like a name, ID, or word). Dict lookup by key is O(1) — extremely fast even for millions of items.', 5),
  ],
  'reading-and-writing-files': [
    mc('To open a file for reading in Python, the correct approach is:', ['file = open("data.txt")', 'with open("data.txt", "r") as f: — the "with" statement is preferred', 'file = file.open("data.txt", read=True)', 'import file; file.read("data.txt")'], 'with open("data.txt", "r") as f: — the "with" statement is preferred', 'The "with" statement (context manager) automatically closes the file when the block exits, even if an error occurs. This prevents file handle leaks. open("file", "r") for read, "w" for write (overwrites), "a" for append.', 1),
    mc('f.readlines() on an open file returns:', ['The first line of the file as a string', 'A single string containing the entire file contents', 'A list of strings, one per line, including the newline character', 'The total number of lines in the file'], 'A list of strings, one per line, including the newline character', 'f.read() returns the entire file as one string. f.readline() returns the next single line. f.readlines() returns all lines as a list. To remove trailing newlines when iterating: for line in f: line.strip().', 2),
    mc('Opening a file in "w" mode and writing to it when the file already exists will:', ['Raise a FileExistsError and abort the operation', 'Append the new content after the existing content', 'Overwrite the file, destroying all previous content', 'Create a backup of the original before writing'], 'Overwrite the file, destroying all previous content', '"w" (write) mode truncates the file to zero length before writing. Always intentional. Use "a" (append) to add to existing content. Use "x" to create a new file and fail if it already exists. Back up important data before writing.', 3),
    mc('CSV files are commonly used for data because:', ['They are compressed and therefore smaller than other formats', 'They are plain text using commas to separate values — readable by humans and importable into any spreadsheet or data tool', 'They encrypt data automatically during save operations', 'They preserve formatting like bold, color, and font size between applications'], 'They are plain text using commas to separate values — readable by humans and importable into any spreadsheet or data tool', 'CSV is the universal data exchange format. Every spreadsheet application, database, and data tool can import and export CSV. The simplicity (just text with commas) ensures compatibility, though it lacks support for complex types.', 4),
    mc('The json module in Python is useful for files because:', ['JSON is the fastest file format for reading large datasets', 'JSON preserves Python data structures (dicts, lists, strings, numbers) in a text format that other applications can also read', 'JSON files are automatically compressed when saved', 'JSON is required for all web application data storage'], 'JSON preserves Python data structures (dicts, lists, strings, numbers) in a text format that other applications can also read', 'json.dump() converts Python objects to JSON format for storage. json.load() reads them back. JSON is human-readable and supported by virtually every programming language and web API — making it ideal for data interchange.', 5),
  ],
  'debugging': [
    mc('A syntax error in Python occurs when:', ['The program runs but produces incorrect results', 'The code violates the language\'s grammatical rules and cannot be parsed', 'The program attempts to divide by zero at runtime', 'A referenced variable has not been defined yet'], 'The code violates the language\'s grammatical rules and cannot be parsed', 'Syntax errors prevent the program from running at all. Missing colons, mismatched parentheses, and misspelled keywords cause syntax errors. Python points to the approximate location in the error message.', 1),
    mc('A runtime error (exception) differs from a syntax error in that:', ['Runtime errors can be prevented by careful planning; syntax errors cannot', 'Runtime errors occur while the program is executing — the syntax is valid but something goes wrong during operation', 'Runtime errors only occur in production environments, not during development', 'Syntax errors crash the program; runtime errors produce incorrect output silently'], 'Runtime errors occur while the program is executing — the syntax is valid but something goes wrong during operation', 'Division by zero (ZeroDivisionError), accessing a missing key (KeyError), and type mismatches (TypeError) are runtime errors. The syntax is correct but the execution encounters an invalid state. Try/except handles these.', 2),
    mc('The most useful first step when encountering an error in Python is:', ['Rewriting the entire function from scratch', 'Reading the traceback carefully — it shows the exact file, line number, and error type', 'Adding print() statements throughout the code randomly', 'Searching the internet immediately for the error message'], 'Reading the traceback carefully — it shows the exact file, line number, and error type', 'The traceback is Python\'s error report. It shows the call stack (which function called which), the exact line where the error occurred, and the exception type with a message. Start by reading the LAST few lines — that\'s where the actual error is.', 3),
    mc('Using print() statements for debugging is:', ['Unprofessional and should never be used — use a debugger instead', 'A valid and common technique, especially for quick checks — though debuggers offer more power', 'Only effective for syntax errors, not logical errors', 'Appropriate only in development, never in code that others will run'], 'A valid and common technique, especially for quick checks — though debuggers offer more power', 'print debugging is fast and requires no setup. Insert print("value:", x) before a suspected problem. Even professional engineers use print debugging for quick diagnosis. Step-through debuggers are more powerful for complex logic tracing.', 4),
    mc('A logical error (bug) in a program is the hardest type to find because:', ['Logical errors always produce no output, making them difficult to detect', 'The program runs without crashing but produces incorrect results — there is no error message to guide you', 'Logical errors only manifest on specific hardware configurations', 'Python cannot detect logical errors even with strict mode enabled'], 'The program runs without crashing but produces incorrect results — there is no error message to guide you', 'A logical error means the code is syntactically correct and runs, but the algorithm is wrong. For example, using + instead of - produces wrong math with no error. You must trace the logic, compare expected vs. actual output, and reason about what the code does vs. what it should do.', 5),
  ],
  'what-is-html': [
    mc('HTML stands for:', ['Hyperlink and Text Management Language', 'HyperText Markup Language', 'High-Text Modeling Language', 'Hyperlink Transfer Markup Language'], 'HyperText Markup Language', 'HTML is the standard markup language for creating web pages. "HyperText" refers to text containing links to other documents. "Markup" refers to the use of tags to annotate content with meaning and structure.', 1),
    mc('HTML describes the structure of a web page by:', ['Defining the visual appearance using color and font specifications', 'Wrapping content in tags that define its meaning and role (heading, paragraph, link, image)', 'Writing program logic that runs in the browser', 'Specifying the network protocol used to deliver the page'], 'Wrapping content in tags that define its meaning and role (heading, paragraph, link, image)', 'HTML tags like <h1>, <p>, <a>, and <img> give semantic meaning to content. CSS handles visual presentation. JavaScript handles behavior. HTML is the foundation — the content layer that everything else builds on.', 2),
    mc('A browser\'s job when it receives HTML is to:', ['Execute the HTML as a program', 'Parse the HTML, build a DOM (Document Object Model) tree, and render it visually', 'Compress the HTML and display the raw code', 'Validate the HTML against the W3C standard before displaying anything'], 'Parse the HTML, build a DOM (Document Object Model) tree, and render it visually', 'The browser parses HTML into a tree structure (DOM), combines it with CSS styles and JavaScript behavior, and renders the final visual result. Different browsers may render the same HTML slightly differently depending on their engines.', 3),
    mc('The difference between block-level elements (like <p>, <div>) and inline elements (like <span>, <a>) is:', ['Block elements support styling; inline elements do not', 'Block elements start on a new line and take full width; inline elements flow within text', 'Block elements require closing tags; inline elements are self-closing', 'Block elements are for structural content; inline elements are for images only'], 'Block elements start on a new line and take full width; inline elements flow within text', 'Block elements create a "block" — they force a line break before and after and stretch to full container width. Inline elements flow within surrounding text without creating line breaks. CSS can override default display behavior.', 4),
    mc('HTML5 introduced semantic elements like <article>, <section>, <nav>, and <footer> to:', ['Replace div elements which are deprecated in HTML5', 'Give structural elements meaningful names that describe their role, improving accessibility and SEO', 'Enable new CSS styling capabilities not possible with generic elements', 'Allow JavaScript to target elements without using class or id attributes'], 'Give structural elements meaningful names that describe their role, improving accessibility and SEO', 'Before HTML5, layouts used countless <div> elements with class names. Semantic elements communicate purpose: <nav> is navigation, <article> is standalone content. Screen readers and search engines understand the page structure better.', 5),
  ],
  'html-elements': [
    mc('An HTML attribute provides:', ['Content displayed inside the element', 'Additional information about an element, specified inside the opening tag', 'Styling instructions for the element\'s appearance', 'Instructions for browser behavior on any element type'], 'Additional information about an element, specified inside the opening tag', 'Attributes appear in the opening tag: <a href="url">. href is an attribute specifying the link destination. Other attributes: src (image source), alt (image description), class (CSS targeting), id (unique identifier), style (inline CSS).', 1),
    mc('The alt attribute on an <img> tag is important because:', ['It provides a tooltip when hovering over the image', 'It describes the image for screen readers and displays if the image fails to load', 'It is required for browsers to display the image at all', 'It specifies the image file format'], 'It describes the image for screen readers and displays if the image fails to load', 'alt text is an accessibility requirement. Screen readers read it aloud to visually impaired users. It also appears when the image can\'t load. Meaningful alt text (not just "image") helps users who can\'t see the image understand its content.', 2),
    mc('An <a> tag with href="#section-id" creates:', ['A link that navigates to an external website named "section-id"', 'An anchor link that jumps to an element with id="section-id" on the same page', 'A link that downloads a file named "section-id"', 'A broken link that goes nowhere until the section-id page is created'], 'An anchor link that jumps to an element with id="section-id" on the same page', 'The # prefix creates an internal page link that scrolls to the element with that id. Common for "back to top" links, table of contents navigation, and single-page navigation menus.', 3),
    mc('The <head> section of an HTML document contains:', ['The visible content of the webpage displayed to users', 'Metadata, links to stylesheets, scripts, and the page title — not rendered as visible content', 'The navigation menu and header of the page', 'Comments and documentation for other developers'], 'Metadata, links to stylesheets, scripts, and the page title — not rendered as visible content', '<head> contains <title> (browser tab text), <meta> tags (description, viewport, character set), <link> (CSS stylesheets), and <script> tags. None of this is visible on the page itself — it configures how the browser handles the document.', 4),
    mc('What does the "id" attribute uniquely identify on a web page?', ['The database record corresponding to this element', 'A single specific element — no two elements on the same page should share an id', 'The element\'s CSS class for group styling', 'The order in which elements were added to the DOM'], 'A single specific element — no two elements on the same page should share an id', 'IDs must be unique within a page. They are used for CSS targeting (#my-id), JavaScript selection (getElementById), and anchor links (#my-id). The "class" attribute (which can be shared) is more commonly used for styling multiple elements.', 5),
  ],
  'building-a-page': [
    mc('The correct basic structure for any HTML document is:', ['<html> with <title> and <body> at the same level', '<!DOCTYPE html>, then <html> containing <head> and <body>', '<head> containing <body> containing <html>', 'Only <body> is required — all other tags are optional'], '<!DOCTYPE html>, then <html> containing <head> and <body>', '<!DOCTYPE html> tells the browser it\'s HTML5. <html> is the root element. <head> contains metadata. <body> contains all visible content. Without this structure, browsers apply quirks mode and behavior becomes unpredictable.', 1),
    mc('When nesting HTML elements, the correct rule is:', ['Child elements must always be inline, never block', 'Elements must be properly nested — an element opened inside another must be closed before the outer element closes', 'Any element can be placed inside any other element', 'Self-closing tags like <br> must always be paired with </br>'], 'Elements must be properly nested — an element opened inside another must be closed before the outer element closes', 'Proper nesting: <div><p>text</p></div>. Improper: <div><p>text</div></p>. Browsers often fix improper nesting silently, but the resulting DOM may not match what you intended, causing layout and JavaScript bugs.', 2),
    mc('The <div> element is best described as:', ['A semantic element that describes navigation content', 'A generic block-level container with no inherent semantic meaning, used for layout grouping', 'An element for displaying tabular data in rows and columns', 'A required wrapper for all content that uses CSS flexbox'], 'A generic block-level container with no inherent semantic meaning, used for layout grouping', '<div> just groups elements for styling or layout purposes — it carries no meaning of its own. Use semantic elements (<article>, <section>, <nav>) when they accurately describe the content. Use <div> when no semantic element fits.', 3),
    mc('Adding a comment in HTML uses what syntax?', ['// This is a comment', '/* This is a comment */', '<!-- This is a comment -->', '## This is a comment'], '<!-- This is a comment -->', 'HTML comments are <!-- text here -->. They are not rendered in the browser but are visible in the page source. Use them to explain complex sections, leave notes for collaborators, or temporarily disable code during development.', 4),
    mc('The purpose of the <meta name="viewport" content="width=device-width, initial-scale=1"> tag is:', ['To set the maximum resolution for images on the page', 'To tell mobile browsers to set the viewport width to the device width, enabling responsive design', 'To specify the page\'s geographic location for search engines', 'To prevent the browser from caching the page for privacy'], 'To tell mobile browsers to set the viewport width to the device width, enabling responsive design', 'Without this meta tag, mobile browsers display pages at desktop width (usually ~980px) and scale down, making text tiny. This tag enables responsive CSS media queries to work correctly on mobile devices.', 5),
  ],
  'forms-and-links': [
    mc('An HTML form\'s "action" attribute specifies:', ['The validation rules applied to form inputs', 'The URL where form data is sent when the form is submitted', 'The method used to encode the form data', 'The styling of the form container'], 'The URL where form data is sent when the form is submitted', 'action="/submit" means form data goes to the /submit endpoint on the same server. The method attribute (GET or POST) determines how data is transmitted. Without action, some browsers submit to the current page URL.', 1),
    mc('The difference between form method="GET" and method="POST" is:', ['GET is encrypted; POST is not', 'GET appends form data to the URL; POST sends it in the request body (not visible in the URL)', 'GET is for forms with file uploads; POST is for text-only forms', 'POST refreshes the page; GET navigates to a new page'], 'GET appends form data to the URL; POST sends it in the request body (not visible in the URL)', 'GET: ?name=Alice&age=30 appears in the URL. Suitable for search forms (shareable, bookmarkable). POST: data in request body, not visible in URL. Use POST for passwords, sensitive data, file uploads, and data-modifying operations.', 2),
    mc('The "required" attribute on an input field causes the browser to:', ['Prevent the page from loading until the field is filled', 'Display an error message and prevent form submission if the field is empty', 'Automatically fill the field with the user\'s previously entered data', 'Make the field read-only after the first entry'], 'Display an error message and prevent form submission if the field is empty', '"required" is HTML5 client-side validation. The browser checks the field before submitting — if empty (or invalid), submission is blocked and an error message appears. Never rely on client-side validation alone; always validate on the server too.', 3),
    mc('A target="_blank" attribute on an <a> link causes:', ['The link to download the file instead of opening it', 'The linked page to open in a new browser tab or window', 'The link to apply no styling when clicked', 'The link to verify the destination URL before navigating'], 'The linked page to open in a new browser tab or window', 'target="_blank" opens the link in a new tab. For security, add rel="noopener noreferrer" — without it, the opened page can access the opener window via JavaScript. This is a common security oversight.', 4),
    mc('The <label> element associated with a form input improves:', ['The visual layout of the form by positioning labels automatically', 'Accessibility — clicking the label focuses the input, and screen readers associate the label text with the input', 'Form security by encrypting the label text from view-source inspection', 'Form performance by grouping inputs for batch validation'], 'Accessibility — clicking the label focuses the input, and screen readers associate the label text with the input', 'A label associated via for="input-id" or by wrapping the input creates an accessible connection. Screen readers announce the label when focusing the input. Clicking the label focuses/activates the input — especially important for checkboxes.', 5),
  ],
}
