import type { ExerciseDef } from '../types'

function mc(question: string, options: string[], correctAnswer: string, explanation: string, order: number): ExerciseDef {
  return { question, type: 'MULTIPLE_CHOICE', options, correctAnswer, explanation, order }
}

export const techExercises5: Record<string, ExerciseDef[]> = {
  'how-css-works': [
    mc('CSS (Cascading Style Sheets) is used to:', ['Define the structure and content of a web page', 'Control the visual presentation — colors, fonts, layout, and spacing', 'Add interactive behavior to web pages', 'Communicate with web servers to fetch data'], 'Control the visual presentation — colors, fonts, layout, and spacing', 'CSS separates style from content. HTML defines what content is (a heading, a paragraph). CSS defines how it looks (red, 24px, centered). This separation allows redesigning the entire visual appearance without touching the HTML structure.', 1),
    mc('In CSS, a selector followed by a declaration block ({color: red;}) targets:', ['Only elements that were created by JavaScript', 'All HTML elements matching the selector, applying the specified styles', 'Elements that the user has already interacted with', 'Only the first matching element on the page'], 'All HTML elements matching the selector, applying the specified styles', 'A CSS rule: .header { color: blue; font-size: 24px; } applies to every element with class="header". Element selectors (p, h1), class selectors (.name), and ID selectors (#id) select different sets of elements.', 2),
    mc('CSS specificity determines what happens when multiple rules target the same element. Which has the highest specificity?', ['A class selector (.btn)', 'An element selector (button)', 'An inline style (style="color:red")', 'A CSS rule with !important'], 'A CSS rule with !important', 'Specificity order (lowest to highest): elements/pseudoelements, classes/pseudoclasses/attributes, IDs, inline styles, !important. !important overrides everything and is a last resort — overusing it creates unmaintainable code.', 3),
    mc('The CSS box model defines that every element is composed of:', ['Content, borders, and backgrounds', 'Content area, padding, border, and margin from inside out', 'Content width and height only — everything else is separate', 'Typography metrics: baseline, cap height, and line height'], 'Content area, padding, border, and margin from inside out', 'Understanding the box model is fundamental. Content is the actual text/image. Padding is transparent space inside the border. Border wraps the padding. Margin is transparent space outside the border separating elements.', 4),
    mc('What does "cascading" in CSS mean?', ['CSS files are loaded one after another to override previous styles', 'When multiple rules apply to an element, the browser resolves conflicts based on specificity, source order, and importance', 'Styles are inherited from parent elements and cascade down to children', 'Both conflict resolution and inheritance contribute to the "cascading" behavior'], 'Both conflict resolution and inheritance contribute to the "cascading" behavior', 'Cascading has two aspects: 1) Style inheritance — children inherit font, color, and other text properties from parents unless overridden. 2) Conflict resolution — when multiple rules target the same element, specificity and order determine which wins.', 5),
  ],
  'layout-with-css': [
    mc('CSS Flexbox is best used for:', ['Creating two-dimensional grid layouts with rows and columns simultaneously', 'Laying out items along a single axis (row or column) and distributing space between them', 'Fixed, pixel-perfect layouts where elements don\'t need to adapt to screen size', 'Only centering elements vertically on a page'], 'Laying out items along a single axis (row or column) and distributing space between them', 'Flexbox is a one-dimensional layout model. It excels at navigation bars, card rows, centering elements, and distributing space in one direction. For two-dimensional layouts (rows AND columns simultaneously), CSS Grid is more powerful.', 1),
    mc('To center a div both horizontally and vertically using Flexbox, the parent needs:', ['margin: auto on the child element', 'display: flex; justify-content: center; align-items: center on the parent', 'position: absolute; top: 50%; left: 50% on the child', 'display: flex; text-align: center on the parent'], 'display: flex; justify-content: center; align-items: center on the parent', 'justify-content controls the main axis (horizontal by default); align-items controls the cross axis (vertical by default). Setting both to center with the parent as a flex container is the modern standard for centering.', 2),
    mc('CSS Grid differs from Flexbox in that Grid:', ['Only works in modern browsers, while Flexbox works in all browsers', 'Lays out items in two dimensions simultaneously — defining rows AND columns', 'Is faster to render because it uses native browser layout algorithms', 'Can only create equal-width columns, unlike Flexbox\'s flexible sizing'], 'Lays out items in two dimensions simultaneously — defining rows AND columns', 'Grid defines rows and columns together: grid-template-columns: 1fr 2fr 1fr creates three columns. Items can span multiple rows and columns. Grid is ideal for page-level layouts; Flexbox for component-level alignment.', 3),
    mc('The CSS property "position: absolute" causes an element to:', ['Stay fixed in the viewport even when scrolling', 'Be positioned relative to its nearest positioned ancestor, removed from normal document flow', 'Snap to the nearest edge of the screen', 'Stack on top of all other elements regardless of z-index'], 'Be positioned relative to its nearest positioned ancestor, removed from normal document flow', 'Absolute positioning removes the element from normal flow (other elements ignore it). It positions relative to the nearest ancestor with position: relative (or the <body> if none). top: 0; right: 0 places it at the top-right of its container.', 4),
    mc('The CSS unit "rem" is based on:', ['The root element\'s (html) font size', 'The parent element\'s current font size', 'The viewport width', 'A fixed measurement equal to 16 pixels regardless of settings'], 'The root element\'s (html) font size', 'rem (root em) is relative to the HTML element\'s font size (default 16px). 1.5rem = 24px if root is 16px. If the user changes their browser font size for accessibility, rem units scale appropriately. This is a key accessibility advantage over px.', 5),
  ],
  'responsive-design': [
    mc('Responsive web design means:', ['Designing websites that respond to user input faster', 'Creating web pages that adapt their layout to fit different screen sizes and devices', 'Building websites that work without JavaScript', 'Ensuring websites load in under 3 seconds on all connections'], 'Creating web pages that adapt their layout to fit different screen sizes and devices', 'Responsive design uses fluid grids, flexible images, and CSS media queries to ensure a good experience on everything from a small phone to a large desktop monitor — using a single HTML file with adaptive CSS.', 1),
    mc('A CSS media query allows you to:', ['Query a database from within a CSS file', 'Apply different styles based on device characteristics like screen width, height, or orientation', 'Load different HTML files for mobile and desktop users', 'Test CSS in a mobile browser simulator'], 'Apply different styles based on device characteristics like screen width, height, or orientation', '@media (max-width: 768px) { .menu { display: none; } } applies those styles only when viewport is 768px or narrower. Media queries are the core mechanism enabling responsive layouts to change at specific breakpoints.', 2),
    mc('A "mobile-first" CSS approach means:', ['Designing only for mobile and ignoring desktop users', 'Writing base styles for mobile screens, then adding larger-screen overrides using min-width media queries', 'Loading a separate mobile website for phone users', 'Using max-width media queries to progressively add styles for smaller screens'], 'Writing base styles for mobile screens, then adding larger-screen overrides using min-width media queries', 'Mobile-first starts with the simplest layout (mobile) as the default, then enhances for larger screens with @media (min-width: ...) queries. This approach is often cleaner and ensures good mobile performance as the baseline.', 3),
    mc('Using max-width: 100% on images in CSS ensures:', ['Images always display at their maximum resolution', 'Images scale down to fit their container but never scale up beyond their natural size', 'Images maintain their aspect ratio when the window is resized', 'Both scaling constraints and aspect ratio preservation are achieved'], 'Both scaling constraints and aspect ratio preservation are achieved', 'max-width: 100% prevents images from overflowing their container (preventing horizontal scroll) while not stretching them beyond their natural size. Browsers maintain aspect ratio by default. This is a fundamental responsive image technique.', 4),
    mc('What is the purpose of CSS Grid\'s "fr" unit?', ['Fixed pixel-based column widths', 'A fractional unit that distributes available space proportionally among columns or rows', 'Font-relative sizing for column widths', 'The frequency (in Hz) at which the layout recalculates'], 'A fractional unit that distributes available space proportionally among columns or rows', 'grid-template-columns: 1fr 2fr means the second column gets twice the free space as the first. fr units fill available space fluidly, adjusting when the viewport changes. Combined with repeat() and auto-fill, fr enables responsive grids without media queries.', 5),
  ],
  'javascript-basics': [
    mc('JavaScript in a browser environment can:', ['Directly access the user\'s file system and read any file', 'Manipulate the HTML/CSS, respond to user events, and communicate with servers', 'Run only in the <head> section of an HTML document', 'Execute in parallel threads to speed up animations'], 'Manipulate the HTML/CSS, respond to user events, and communicate with servers', 'Browser JavaScript runs in a sandbox — it can modify the DOM, respond to clicks/keys, fetch data from APIs, and store data locally. It cannot access the file system (outside of explicit user actions) or other browser tabs due to security restrictions.', 1),
    mc('The difference between let, const, and var in JavaScript is:', ['var and let are identical; const is for constants', 'const cannot be reassigned, let is block-scoped and reassignable, var is function-scoped and can cause bugs', 'const and let are for arrays; var is for all other types', 'Only const exists in modern JavaScript — var and let are deprecated'], 'const cannot be reassigned, let is block-scoped and reassignable, var is function-scoped and can cause bugs', 'Use const by default (signals intent not to reassign). Use let when reassignment is needed. Avoid var — its function-scoping and hoisting behavior causes subtle bugs. const/let were introduced in ES6 (2015).', 2),
    mc('In JavaScript, console.log() is primarily used for:', ['Displaying output to the user on the web page', 'Printing debug information to the browser\'s developer console', 'Logging errors to the server for monitoring', 'Storing values that need to persist between page loads'], 'Printing debug information to the browser\'s developer console', 'console.log() outputs to the developer tools console (F12 in most browsers). This is the primary debugging tool for JavaScript — print values, trace execution, and check variable states without displaying anything to page visitors.', 3),
    mc('JavaScript functions can be written as arrow functions (const add = (a, b) => a + b). Arrow functions differ from regular functions primarily in:', ['Arrow functions cannot accept parameters', 'Arrow functions have no "this" binding of their own — they inherit "this" from the surrounding scope', 'Arrow functions run faster than regular functions', 'Arrow functions are only for callbacks and cannot be called directly'], 'Arrow functions have no "this" binding of their own — they inherit "this" from the surrounding scope', 'Arrow functions are concise and avoid "this" confusion common with regular functions in callbacks. They are the modern standard for function expressions. They cannot be used as constructors with "new".', 4),
    mc('What does the === operator check in JavaScript vs ==?', ['=== checks type and value; == checks only value, performing type coercion', '=== is slower but more precise; == is faster but less reliable', '=== is used for objects; == is used for primitives', 'They are identical in modern JavaScript engines'], '=== checks type and value; == checks only value, performing type coercion', '== with type coercion: 0 == false is true, "" == 0 is true. These surprises cause bugs. === (strict equality) requires both type and value to match: 0 === false is false. Always use === in modern JavaScript.', 5),
  ],
  'dom-manipulation': [
    mc('The DOM (Document Object Model) is:', ['The protocol used to transfer HTML from server to browser', 'A tree-structured representation of the HTML document that JavaScript can read and modify', 'The CSS stylesheet attached to the current HTML document', 'A browser security model preventing cross-site scripting'], 'A tree-structured representation of the HTML document that JavaScript can read and modify', 'The DOM is an in-memory tree of all elements on the page. JavaScript can traverse this tree, read or change element content and attributes, add/remove elements, and modify styles — causing the visible page to update in real time.', 1),
    mc('document.getElementById("myId") returns:', ['A string containing the element\'s HTML', 'The DOM element with id="myId", or null if not found', 'An array of all elements with the specified class', 'The parent element of the element with that id'], 'The DOM element with id="myId", or null if not found', 'getElementById returns the single element with that id (or null). querySelector("#myId") does the same with CSS selector syntax. querySelectorAll(".className") returns all matching elements as a NodeList.', 2),
    mc('To change the visible text content of a DOM element in JavaScript:', ['element.text = "new text"', 'element.innerText = "new text" or element.textContent = "new text"', 'element.content("new text")', 'element.html = "new text"'], 'element.innerText = "new text" or element.textContent = "new text"', 'innerText sets/gets rendered text (respects CSS visibility). textContent sets/gets all text including hidden. innerHTML sets/gets HTML — powerful but dangerous if setting user input (XSS vulnerability). Use textContent for plain text.', 3),
    mc('The best reason to manipulate the DOM via JavaScript rather than reloading the page is:', ['DOM manipulation is the only way to change page content after it loads', 'Updating specific elements without a full page reload provides a faster, smoother user experience', 'DOM manipulation is required for all forms of user interaction', 'Reloading the page doesn\'t work in modern single-page applications'], 'Updating specific elements without a full page reload provides a faster, smoother user experience', 'DOM manipulation powers dynamic UIs: showing/hiding menus, updating counters, loading new content, validating forms. Without it, every interaction would require a round trip to the server and a full page reload — the old way of the web.', 4),
    mc('When you call element.classList.add("active"), you are:', ['Replacing all existing classes on the element with "active"', 'Adding "active" to the element\'s class list without removing other classes', 'Creating a new CSS rule called "active" for that element', 'Adding the element to a group called "active" for batch operations'], 'Adding "active" to the element\'s class list without removing other classes', 'classList.add() adds a class. classList.remove() removes one. classList.toggle() adds if absent, removes if present. classList.contains() checks if a class is applied. These are the standard way to dynamically change styles via JavaScript.', 5),
  ],
  'events': [
    mc('An event listener in JavaScript responds to:', ['Network requests made by the browser', 'User actions (clicks, keypresses, form submissions) or browser events (page load, scroll)', 'Changes to the CSS stylesheet', 'Server-sent messages only'], 'User actions (clicks, keypresses, form submissions) or browser events (page load, scroll)', 'Event listeners are functions that run when a specified event occurs on an element. The web is event-driven — user interactions trigger events, and JavaScript responds. Without events, web pages would be static.', 1),
    mc('The correct way to add a click event listener in modern JavaScript is:', ['element.onclick = function() {}', 'element.addEventListener("click", function() {})', 'element.click(function() {})', 'on(element, "click", function() {})'], 'element.addEventListener("click", function() {})', 'addEventListener is preferred over onclick because it allows multiple listeners on the same element without overwriting. onclick can only hold one function. addEventListener also allows easy removal with removeEventListener.', 2),
    mc('The event object passed to an event handler contains:', ['Only the type of event that occurred', 'Information about the event including the target element, cursor position, key pressed, and other context', 'The HTML source code of the target element', 'A reference to the previous event that occurred'], 'Information about the event including the target element, cursor position, key pressed, and other context', 'The event object (often named "e" or "event") provides event.target (the element that triggered it), event.type ("click"), event.clientX/clientY (mouse position), event.key (for keyboard events), and many more properties.', 3),
    mc('event.preventDefault() is used to:', ['Stop the event from bubbling up to parent elements', 'Prevent the browser\'s default behavior for that event (like form submission or link navigation)', 'Remove the event listener after the first trigger', 'Cancel all pending events in the queue'], 'Prevent the browser\'s default behavior for that event (like form submission or link navigation)', 'Clicking a link navigates. Submitting a form sends data and reloads. These are browser defaults. event.preventDefault() stops them — allowing JavaScript to handle the action instead (validate a form, use fetch() instead of a full POST).', 4),
    mc('Event bubbling means:', ['The browser queues events and processes them one at a time to prevent conflicts', 'An event on a child element propagates up through all parent elements, triggering their handlers for the same event type', 'Multiple events of the same type merge into a single handler call', 'Events automatically repeat (bubble) every 500ms until handled'], 'An event on a child element propagates up through all parent elements, triggering their handlers for the same event type', 'A click on a <button> inside a <div> inside <body> triggers click handlers on button, then div, then body (unless stopped). This allows "event delegation" — attaching one handler to a parent to handle events from many children.', 5),
  ],
  'fetch-and-apis': [
    mc('An API (Application Programming Interface) in the context of web development is:', ['The browser\'s built-in set of JavaScript functions', 'An endpoint that allows your JavaScript code to request data from a remote server', 'A design pattern for organizing front-end code', 'The protocol used to encrypt HTTPS traffic'], 'An endpoint that allows your JavaScript code to request data from a remote server', 'Web APIs expose server-side data or functionality via HTTP endpoints. Your JavaScript calls the API URL (e.g., /api/weather), the server returns data (usually JSON), and your code uses that data to update the page without a full reload.', 1),
    mc('The Fetch API in JavaScript is used to:', ['Pre-load all resources before the page displays', 'Make HTTP requests to servers and work with the responses asynchronously', 'Fetch CSS stylesheets separately from HTML', 'Cache API responses in localStorage automatically'], 'Make HTTP requests to servers and work with the responses asynchronously', 'fetch(url) sends an HTTP request and returns a Promise. On resolution, you call .json() to parse the response body as JSON. This is the modern replacement for XMLHttpRequest (XHR) and powers dynamic content loading without page reloads.', 2),
    mc('Promises in JavaScript handle:', ['Synchronous operations that need guaranteed completion', 'Asynchronous operations that will complete in the future, providing .then() and .catch() for success/error handling', 'Memory allocation for large objects', 'Type conversions between JavaScript data types'], 'Asynchronous operations that will complete in the future, providing .then() and .catch() for success/error handling', 'A Promise represents a value that will be available eventually. fetch() returns a Promise. .then(response => ...) handles success. .catch(error => ...) handles failure. async/await is syntactic sugar that makes Promises look synchronous.', 3),
    mc('JSON (JavaScript Object Notation) is the standard format for API data because:', ['Browsers can only process JSON, not other data formats', 'It is lightweight, human-readable, and natively supported in JavaScript and virtually every other language', 'JSON is automatically encrypted when transmitted over HTTP', 'JSON files are smaller than all other data formats due to built-in compression'], 'It is lightweight, human-readable, and natively supported in JavaScript and virtually every other language', 'JSON uses JavaScript syntax (objects, arrays, strings, numbers) making it natural for JS developers. JSON.parse() converts JSON text to JavaScript objects. JSON.stringify() converts objects to JSON text. Every language has JSON libraries.', 4),
    mc('async/await in JavaScript simplifies working with Promises by:', ['Making asynchronous code execute synchronously on a separate thread', 'Allowing you to write asynchronous code in a sequential, synchronous-looking style', 'Automatically retrying failed requests up to three times', 'Combining multiple fetch calls into a single request'], 'Allowing you to write asynchronous code in a sequential, synchronous-looking style', 'async functions return Promises. await pauses execution inside an async function until the Promise resolves. const data = await fetch(url).then(r => r.json()) reads top-to-bottom like synchronous code while remaining non-blocking.', 5),
  ],
}
