import type { ExerciseDef } from '../types'

function mc(question: string, options: string[], correctAnswer: string, explanation: string, order: number): ExerciseDef {
  return { question, type: 'MULTIPLE_CHOICE', options, correctAnswer, explanation, order }
}

export const techExercises3: Record<string, ExerciseDef[]> = {
  'variables-and-data-types': [
    mc('A variable in programming is:', ['A value that never changes throughout program execution', 'A named storage location that holds a value which can change during execution', 'A mathematical symbol representing an unknown quantity', 'A type of loop that repeats a block of code'], 'A named storage location that holds a value which can change during execution', 'Variables are containers with names. x = 5 stores the value 5 in a variable named x. Later, x = 10 changes its value. The name allows you to refer to the stored value without knowing it in advance.', 1),
    mc('In Python, what data type would the value 3.14 be?', ['int (integer)', 'str (string)', 'float (floating-point number)', 'bool (boolean)'], 'float (floating-point number)', 'Floats are decimal numbers. Integers (int) are whole numbers like 3. Strings (str) are text like "hello". Booleans (bool) are True or False. Python determines type automatically from the literal value assigned.', 2),
    mc('What is the difference between an integer (int) and a float in most programming languages?', ['Integers can be negative; floats cannot', 'Integers represent whole numbers; floats represent numbers with decimal points', 'Floats are more precise; integers are approximate', 'Integers are stored in RAM; floats are stored on disk during computation'], 'Integers represent whole numbers; floats represent numbers with decimal points', 'int stores whole numbers (5, -12, 1000). float stores decimal numbers (3.14, -0.001, 2.0). Mathematical operations may return floats even with integer inputs — dividing 5 by 2 gives 2.5 in Python 3.', 3),
    mc('In Python, what does type("hello") return?', ["int", "str", "bool", "char"], 'str', 'The type() function returns the data type of a value. "hello" is a string (str). Knowing and checking types is important because operations behave differently on different types — "2" + "3" = "23" (string concatenation), not 5.', 4),
    mc('Dynamic typing (like Python) means:', ['Variables can only hold one type of value throughout the program', 'The type of a variable is determined by the value assigned to it and can change', 'The program\'s speed adapts dynamically based on system load', 'Data types are checked at compile time rather than at runtime'], 'The type of a variable is determined by the value assigned to it and can change', 'Python is dynamically typed: x = 5 makes x an int; x = "hello" makes it a str — no explicit type declaration needed. Statically typed languages (Java, C++) require declaring a variable\'s type upfront and enforce it throughout.', 5),
  ],
  'operators-and-expressions': [
    mc('In Python, the expression 17 % 5 evaluates to:', ['3.4', '12', '2', '85'], '2', '% is the modulo operator — it returns the remainder of integer division. 17 divided by 5 = 3 remainder 2. So 17 % 5 = 2. Modulo is useful for checking divisibility (n % 2 == 0 checks if n is even).', 1),
    mc('What is the difference between = and == in most programming languages?', ['= assigns a value; == compares two values for equality', '== is more precise; = is used for approximate comparisons', '= is for numbers; == is for strings and objects', 'They are interchangeable; the choice depends on style preference'], '= assigns a value; == compares two values for equality', 'x = 5 stores 5 in x (assignment). x == 5 evaluates to True or False (comparison). Using = when you mean == is a common bug — in an if statement, it may cause unexpected behavior or a syntax error depending on the language.', 2),
    mc('The expression (5 > 3) and (2 < 1) evaluates to:', ['True', 'False', 'Error — mixed comparisons are not allowed', 'None'], 'False', '(5 > 3) is True. (2 < 1) is False. True AND False = False. The "and" operator requires both conditions to be True. "or" requires at least one True. "not" inverts the boolean.', 3),
    mc('Integer division in Python 3 using // returns:', ['A float with two decimal places', 'The quotient rounded to the nearest integer', 'The floor of the division (rounded down) as an integer', 'The same result as regular division /'], 'The floor of the division (rounded down) as an integer', '7 // 2 = 3 (not 3.5). // discards the remainder and rounds down (toward negative infinity). Regular / always returns a float in Python 3 (7 / 2 = 3.5). Use // when you need whole-number division.', 4),
    mc('What does the ** operator do in Python?', ['Multiply two numbers', 'Raise a number to a power (exponentiation)', 'Compare two values and return the larger one', 'Perform floor division'], 'Raise a number to a power (exponentiation)', '2 ** 8 = 256 (2 to the 8th power). 3 ** 3 = 27. This is Python\'s exponentiation operator — equivalent to pow(base, exponent). Many other languages use ^ (though in Python ^ is bitwise XOR).', 5),
  ],
  'input-and-output': [
    mc('The input() function in Python:', ['Reads a value from a file and returns it', 'Pauses execution, displays an optional prompt, and returns the user\'s typed input as a string', 'Accepts input from any source — keyboard, file, or network', 'Reads the next command-line argument passed to the script'], 'Pauses execution, displays an optional prompt, and returns the user\'s typed input as a string', 'input("Enter your name: ") displays the prompt, waits for keyboard input, and returns everything typed (up to Enter) as a string. Even if the user types a number, input() returns a string — you must convert with int() or float() if needed.', 1),
    mc('In Python, print("Hello" + " " + "World") outputs:', ['Hello + + World', 'Hello World', '"Hello" " " "World"', 'An error because you cannot add strings'], 'Hello World', 'The + operator concatenates (joins) strings. "Hello" + " " + "World" produces the single string "Hello World". print() then outputs that string followed by a newline. String concatenation requires all operands to be strings.', 2),
    mc('To convert a string "42" to an integer in Python, you use:', ['str(42)', 'int("42")', 'float("42")', 'convert("42", int)'], 'int("42")', 'int("42") returns the integer 42. Without this conversion, "42" + 1 would cause a TypeError. This is necessary whenever you read numeric input from input() and want to do math with it.', 3),
    mc('The f-string in Python (f"Hello {name}!") does what?', ['Creates a fixed string that cannot be changed', 'Inserts the value of variables directly into the string at the curly brace positions', 'Formats the string as a file path', 'Converts the name variable to a float for numerical output'], 'Inserts the value of variables directly into the string at the curly brace positions', 'f-strings (formatted string literals) evaluate expressions inside {} at runtime. If name = "Alice", f"Hello {name}!" produces "Hello Alice!" You can also include expressions: f"Result: {2 + 2}" outputs "Result: 4".', 4),
    mc('print() in Python adds what to the end of its output by default?', ['A space character', 'A newline character (\\n) that moves the cursor to the next line', 'A period followed by a newline', 'Nothing — the output continues on the same line'], 'A newline character (\\n) that moves the cursor to the next line', 'print() automatically appends a newline after output, so each call starts on a new line. To suppress this, use print("text", end=""). To use a different separator, use print("a", "b", sep="-") which outputs "a-b".', 5),
  ],
  'conditionals': [
    mc('An if/elif/else structure in Python executes:', ['All blocks where the condition is True', 'Only the first block whose condition is True, then skips the rest', 'The else block always, and conditionally the if blocks as well', 'Each block exactly once, in order, regardless of conditions'], 'Only the first block whose condition is True, then skips the rest', 'Python evaluates conditions top to bottom. When it finds the first True condition, it runs that block and skips all remaining elif/else blocks. If no condition is True, the else block (if present) runs.', 1),
    mc('What does the following Python code print if x = 7?\nif x > 10:\n    print("big")\nelif x > 5:\n    print("medium")\nelse:\n    print("small")', ['big', 'medium', 'small', 'medium\nsmall'], 'medium', '7 > 10 is False. 7 > 5 is True, so "medium" is printed and the else is skipped. Only the first True branch executes.', 2),
    mc('A nested if statement is:', ['An if statement with more than two conditions', 'An if statement inside another if statement\'s block', 'An if statement that checks multiple variables simultaneously', 'An if statement with both elif and else clauses'], 'An if statement inside another if statement\'s block', 'Nesting allows checking additional conditions only when a parent condition is true. For example, check if a number is positive (outer if), then check if it is even (inner if). Deep nesting can reduce readability — functions or "and" operators often simplify this.', 3),
    mc('The condition "not (a and b)" is equivalent to:', ['(not a) and (not b)', '(not a) or (not b)', 'not a and b', 'a or not b'], '(not a) or (not b)', 'De Morgan\'s Law: NOT (A AND B) = (NOT A) OR (NOT B). Also: NOT (A OR B) = (NOT A) AND (NOT B). Understanding boolean algebra is fundamental for writing correct conditional logic.', 4),
    mc('What is a common use case for the ternary operator (or conditional expression) in Python: x = "yes" if condition else "no"?', ['Replacing all multi-line if/else blocks', 'Providing a compact one-line way to choose between two values based on a condition', 'Running code only when a module is imported as main', 'Checking if a variable has been defined before using it'], 'Providing a compact one-line way to choose between two values based on a condition', 'Python\'s conditional expression: value_if_true if condition else value_if_false. It\'s useful for simple assignments: status = "adult" if age >= 18 else "minor". For complex logic, a multi-line if/else is more readable.', 5),
  ],
  'loops': [
    mc('A "for" loop in Python is used to:', ['Repeat code an indefinite number of times based on a condition', 'Iterate over each item in a sequence (list, string, range, etc.) a fixed number of times', 'Define a function that runs repeatedly in the background', 'Loop only when a boolean condition evaluates to True'], 'Iterate over each item in a sequence (list, string, range, etc.) a fixed number of times', 'for item in sequence: executes the body once per item. The number of iterations equals the length of the sequence. range(5) produces [0,1,2,3,4] — a common way to loop a specific number of times.', 1),
    mc('What does "break" do inside a loop?', ['Skips the current iteration and continues to the next', 'Immediately exits the loop entirely', 'Restarts the loop from the beginning', 'Pauses execution until a condition becomes True'], 'Immediately exits the loop entirely', 'break stops the loop and jumps to the first line after the loop. continue skips the rest of the current iteration and moves to the next one. These control flow statements allow fine-grained loop control.', 2),
    mc('A while loop continues executing as long as:', ['The loop variable increments within a range', 'Its condition remains True', 'There are items remaining in a list', 'The function it is in has not returned a value'], 'Its condition remains True', 'while condition: repeats its body. Each iteration re-evaluates the condition. If it starts False, the body never runs. If it never becomes False (infinite loop), the program runs forever — a common bug when the loop variable isn\'t updated.', 3),
    mc('The range(2, 10, 3) function in Python generates:', ['Numbers from 2 to 10 in steps of 3: [2, 5, 8]', 'Numbers from 3 to 10 starting at 2: [3, 5, 7, 9]', 'A list of 10 numbers starting at 2: [2, 3, 4, ..., 11]', 'A random number between 2 and 10, repeated 3 times'], 'Numbers from 2 to 10 in steps of 3: [2, 5, 8]', 'range(start, stop, step) generates numbers starting at start, stepping by step, stopping before stop. range(2, 10, 3) produces 2, 5, 8 (the next would be 11, which exceeds 9, so it stops at 8).', 4),
    mc('List comprehension in Python ( [x*2 for x in range(5)] ) is a compact way to:', ['Loop through a list and check conditions only', 'Create a new list by applying an expression to each element of an iterable', 'Sort a list using a custom key function', 'Filter None values from a list'], 'Create a new list by applying an expression to each element of an iterable', '[x*2 for x in range(5)] produces [0, 2, 4, 6, 8]. It is equivalent to a for loop that appends to a list but is more concise and often faster. Optional conditions can be added: [x for x in nums if x > 0].', 5),
  ],
  'functions': [
    mc('What is the purpose of defining a function?', ['To make code run faster by pre-compiling it', 'To encapsulate a reusable block of code that can be called multiple times with different inputs', 'To prevent variables inside from affecting the rest of the program only', 'To allow Python to detect and fix errors in the code block automatically'], 'To encapsulate a reusable block of code that can be called multiple times with different inputs', 'Functions let you write code once and call it many times. This reduces repetition (DRY: Don\'t Repeat Yourself), makes code easier to test, and organizes complex programs into manageable pieces.', 1),
    mc('In Python, a function "returns" a value by:', ['Printing it with print()', 'Using the return statement, which sends the value back to wherever the function was called', 'Storing it in a global variable accessible everywhere', 'Saving it to a file that the calling code reads back'], 'Using the return statement, which sends the value back to wherever the function was called', 'return value ends the function and passes value back to the caller. Without a return statement, Python returns None. The caller can use the returned value: result = add(3, 4). print() outputs to the screen but doesn\'t return a value to the caller.', 2),
    mc('What is the scope of a variable defined inside a function?', ['Global — it is accessible from anywhere in the program', 'Local — it only exists within the function and is destroyed when the function returns', 'It depends on whether you declare it with "var" or "let"', 'Module-level — accessible within the same file but not other files'], 'Local — it only exists within the function and is destroyed when the function returns', 'Local scope means variables inside a function cannot be accessed outside it. This prevents functions from accidentally modifying each other\'s data. Passing values as arguments and using return values is the proper way to share data between functions.', 3),
    mc('Default parameter values in Python functions (def greet(name="World")) allow:', ['The function to accept any number of arguments', 'Calling the function without providing that argument — it uses the default if omitted', 'Making the parameter required in all calls', 'The function to validate inputs automatically'], 'Calling the function without providing that argument — it uses the default if omitted', 'greet() prints "Hello, World!" and greet("Alice") prints "Hello, Alice!" Default values make parameters optional. Parameters with defaults must come after required parameters in the function definition.', 4),
    mc('What does *args in a Python function definition allow?', ['Passing keyword arguments as a dictionary', 'Accepting any number of positional arguments as a tuple', 'Multiplying arguments together automatically', 'Accepting only string arguments'], 'Accepting any number of positional arguments as a tuple', 'def f(*args) allows calling f(1, 2, 3, 4) — all extra positional arguments are collected into a tuple called args. **kwargs collects keyword arguments into a dictionary. These allow writing functions that accept variable numbers of arguments.', 5),
  ],
  'lists-and-arrays': [
    mc('A Python list can contain:', ['Only items of the same data type', 'Items of any data types, including other lists', 'A maximum of 255 items', 'Only immutable (unchangeable) items'], 'Items of any data types, including other lists', 'Python lists are heterogeneous and dynamic: [1, "hello", True, [2, 3]] is valid. Lists can grow and shrink, and elements can be of any type. This flexibility distinguishes Python from statically typed languages where arrays typically hold one type.', 1),
    mc('List indexing in Python starts at 0, so for my_list = [10, 20, 30, 40], my_list[2] returns:', ['10', '20', '30', '40'], '30', 'Index 0 = 10, index 1 = 20, index 2 = 30, index 3 = 40. Zero-based indexing is standard in most programming languages. my_list[-1] = 40 (last element). my_list[-2] = 30 (second from last).', 2),
    mc('The .append() method on a Python list:', ['Adds an element to the beginning of the list', 'Inserts an element at a specified index position', 'Adds an element to the end of the list', 'Returns the list sorted in alphabetical order'], 'Adds an element to the end of the list', 'my_list.append(5) adds 5 to the end. .insert(i, val) adds at index i. .extend([4, 5]) adds multiple items. .remove(val) removes the first occurrence of val. .pop() removes and returns the last item.', 3),
    mc('Slicing a list with my_list[1:4] returns:', ['Elements at indexes 1, 2, 3, and 4', 'Elements at indexes 1, 2, and 3 (stop index is exclusive)', 'Elements at indexes 0, 1, 2, and 3', 'A single element at index 2 (the average of 1 and 4)'], 'Elements at indexes 1, 2, and 3 (stop index is exclusive)', 'Slice notation: list[start:stop] returns elements from start up to (but not including) stop. my_list[1:4] returns items at indexes 1, 2, 3. my_list[:3] = first 3. my_list[2:] = from index 2 to end. my_list[::-1] reverses the list.', 4),
    mc('The "in" operator with a list (5 in my_list) does what?', ['Returns the index position of 5 in the list', 'Adds 5 to the list if it is not already present', 'Returns True if 5 is in the list, False otherwise', 'Checks if 5 is a valid index for the list'], 'Returns True if 5 is in the list, False otherwise', '"in" tests membership. 5 in [1, 5, 10] returns True. "hello" in my_string checks if "hello" is a substring. "key" in my_dict checks if a key exists. "not in" is the inverse. These are fundamental for conditional checks.', 5),
  ],
}
