import type { AssessmentDef, AssessmentQuestionDef } from '../types'

const mc = (q: string, opts: string[], ans: string, exp: string, pts: number, ord: number): AssessmentQuestionDef =>
  ({ question: q, type: 'MULTIPLE_CHOICE', options: opts, correctAnswer: ans, explanation: exp, points: pts, order: ord })

const oe = (q: string, ans: string, exp: string, pts: number, ord: number): AssessmentQuestionDef =>
  ({ question: q, type: 'OPEN_ENDED', correctAnswer: ans, explanation: exp, points: pts, order: ord })

export const technologyAssessments: Record<string, AssessmentDef> = {
  'how-computers-work': {
    title: 'How Computers Work Assessment',
    passingScore: 75,
    timeLimitMin: 30,
    questions: [
      mc('What does the CPU do?', ['Stores long-term data', 'Executes instructions and performs calculations', 'Manages internet connections', 'Converts power to electricity'], 'Executes instructions and performs calculations', 'The CPU (Central Processing Unit) is the brain of a computer — it fetches, decodes, and executes instructions from programs.', 1, 1),
      mc('What is the difference between RAM and storage?', ['RAM is permanent; storage is temporary', 'RAM is fast, temporary working memory; storage is slow, permanent data retention', 'They are the same thing', 'Storage is faster than RAM'], 'RAM is fast, temporary working memory; storage is slow, permanent data retention', 'RAM holds data actively in use (lost when powered off). Storage (SSD/HDD) retains data permanently — your files, programs, OS.', 1, 2),
      mc('What does an operating system do?', ['Run a single application', 'Manage hardware resources and provide services to programs', 'Connect to the internet', 'Store user files'], 'Manage hardware resources and provide services to programs', 'The OS (Windows, macOS, Linux) manages CPU, memory, storage, and I/O — it\'s the software layer between hardware and applications.', 1, 3),
      mc('What is a bit?', ['A unit of storage equal to 8 bytes', 'The smallest unit of digital data, representing 0 or 1', 'A type of processor speed', 'A file format'], 'The smallest unit of digital data, representing 0 or 1', 'Computers represent all data in binary — bits (0s and 1s). Eight bits make a byte; larger units are kilobytes, megabytes, gigabytes, etc.', 1, 4),
      mc('What does a GPU do?', ['Handle audio processing', 'Store files', 'Process graphics and parallel computations', 'Control input devices'], 'Process graphics and parallel computations', 'The GPU (Graphics Processing Unit) handles rendering visuals and is optimized for parallel processing — also used in AI/ML workloads.', 1, 5),
      mc('What is an input device?', ['A screen or speakers', 'Hardware that sends data to the computer — like keyboard, mouse, microphone', 'A printer or monitor', 'The CPU'], 'Hardware that sends data to the computer — like keyboard, mouse, microphone', 'Input devices allow users to communicate with the computer. Output devices (monitors, printers, speakers) send information from the computer to the user.', 1, 6),
      mc('What does booting a computer mean?', ['Shutting it down safely', 'Starting up — loading the operating system into memory', 'Installing new software', 'Connecting to a network'], 'Starting up — loading the operating system into memory', 'Booting is the startup process: the computer\'s firmware (BIOS/UEFI) runs, loads the OS from storage into RAM, and hands control to the OS.', 1, 7),
      mc('What is a file system?', ['A collection of all files on a computer', 'The method an OS uses to organize, store, and retrieve data on storage devices', 'A type of database software', 'A folder structure you create'], 'The method an OS uses to organize, store, and retrieve data on storage devices', 'File systems (NTFS, ext4, APFS) define how data is stored, named, and retrieved on disks — they handle directories, permissions, and file metadata.', 1, 8),
      oe('Explain in your own words what happens when you double-click to open a program.', 'The OS receives the click event. It finds the program file on storage, loads it into RAM, creates a process, and the CPU begins executing the program\'s instructions. The program draws its interface to the screen via the GPU. The OS manages memory and other resources while the program runs.', 'A strong answer traces the path from user action through OS, storage, RAM, CPU — not just "the program opens."', 2, 9),
      oe('Why does adding more RAM often make a computer faster, and when does it stop helping?', 'When RAM is full, the OS uses virtual memory (swapping data to disk), which is much slower. More RAM lets the OS keep more active data in fast memory, reducing swapping. It stops helping when RAM is no longer the bottleneck — if the CPU or storage is the limiting factor, more RAM won\'t speed things up.', 'The answer should explain virtual memory/swapping and the concept of bottlenecks.', 2, 10),
    ],
  },

  'internet-and-networking': {
    title: 'Internet and Networking Assessment',
    passingScore: 75,
    timeLimitMin: 30,
    questions: [
      mc('What is an IP address?', ['A website\'s password', 'A unique numerical identifier assigned to each device on a network', 'A type of internet connection', 'Your internet provider\'s name'], 'A unique numerical identifier assigned to each device on a network', 'IP addresses are how devices find each other on networks. Like a mailing address for data packets — every device needs one to communicate.', 1, 1),
      mc('What does DNS do?', ['Encrypt your internet traffic', 'Translate human-readable domain names into IP addresses', 'Assign IP addresses to devices', 'Block malicious websites'], 'Translate human-readable domain names into IP addresses', 'DNS (Domain Name System) is like the internet\'s phone book — it converts "google.com" into the IP address that routers need to deliver your request.', 1, 2),
      mc('What is the difference between HTTP and HTTPS?', ['HTTPS is faster', 'HTTPS encrypts data in transit; HTTP does not', 'They are identical', 'HTTP is more secure'], 'HTTPS encrypts data in transit; HTTP does not', 'HTTPS uses TLS/SSL to encrypt the connection between your browser and the server — protecting against eavesdropping and tampering. Always look for HTTPS for sensitive activities.', 1, 3),
      mc('What does a router do?', ['Store website data', 'Direct data packets between networks', 'Connect devices to power', 'Filter email spam'], 'Direct data packets between networks', 'Routers receive data packets and forward them toward their destination — connecting your home network to the internet and directing traffic within the network.', 1, 4),
      mc('What is bandwidth?', ['The speed of a single file download', 'The maximum rate of data transfer through a network connection', 'The number of devices connected', 'The cost of internet service'], 'The maximum rate of data transfer through a network connection', 'Bandwidth is the capacity of a network connection — how much data can flow through per second. More bandwidth means more data can be transferred simultaneously.', 1, 5),
      mc('What is a VPN?', ['A faster internet connection', 'A service that encrypts your traffic and masks your IP address by routing through a server', 'A type of firewall', 'A private browser mode'], 'A service that encrypts your traffic and masks your IP address by routing through a server', 'A VPN (Virtual Private Network) creates an encrypted tunnel for your internet traffic and hides your real IP — used for privacy, security on public Wi-Fi, and bypassing geographic restrictions.', 1, 6),
      mc('What is Wi-Fi?', ['A type of Ethernet cable', 'Wireless networking using radio waves to connect devices to a local network', 'A mobile data standard', 'A brand name for internet service'], 'Wireless networking using radio waves to connect devices to a local network', 'Wi-Fi uses radio frequencies (2.4 GHz, 5 GHz) to wirelessly connect devices to a router/network access point, providing internet access without physical cables.', 1, 7),
      mc('What does a firewall do?', ['Speed up your internet connection', 'Monitor and filter incoming and outgoing network traffic based on security rules', 'Encrypt your files', 'Block all pop-up ads'], 'Monitor and filter incoming and outgoing network traffic based on security rules', 'Firewalls are the first line of network defense — they inspect traffic and block connections that violate security policies, protecting against unauthorized access.', 1, 8),
      oe('Explain what happens technically when you type a URL into a browser and press Enter.', 'Your browser sends a DNS query to resolve the domain to an IP. It establishes a TCP connection to that IP (and TLS handshake for HTTPS). It sends an HTTP GET request. The server responds with HTML. Your browser parses the HTML, requests additional resources (CSS, JS, images), and renders the page. All of this typically happens in under a second.', 'A strong answer hits the key steps: DNS → TCP → TLS → HTTP request → response → render. It doesn\'t need to be perfectly technical but should show understanding.', 2, 9),
      oe('Why is using public Wi-Fi (at a coffee shop or airport) risky, and what can you do to protect yourself?', 'Public Wi-Fi may be unencrypted or on a shared network where others can intercept traffic. Attackers can run "man-in-the-middle" attacks or set up fake hotspots. Protection: use a VPN to encrypt all traffic, only visit HTTPS sites, avoid banking or sensitive logins on public Wi-Fi, use mobile data for sensitive tasks instead.', 'The answer should explain the threat (interception, fake hotspots) and name specific mitigations.', 2, 10),
    ],
  },

  'introduction-to-programming': {
    title: 'Introduction to Programming Assessment',
    passingScore: 75,
    timeLimitMin: 30,
    questions: [
      mc('What is a variable in programming?', ['A fixed value that never changes', 'A named storage location for a value that can change', 'A type of error in code', 'A function that returns a number'], 'A named storage location for a value that can change', 'Variables give names to data so programs can store, reference, and modify values during execution.', 1, 1),
      mc('What does a conditional statement do?', ['Repeat a block of code', 'Execute different code depending on whether a condition is true or false', 'Define a function', 'Store a list of values'], 'Execute different code depending on whether a condition is true or false', 'Conditionals (if/else) allow programs to make decisions — running different code paths based on whether conditions are met.', 1, 2),
      mc('What is a loop in programming?', ['A bug that causes infinite repetition', 'A structure that repeats code until a condition is met', 'A function that calls itself', 'A type of variable'], 'A structure that repeats code until a condition is met', 'Loops (for, while) let you execute the same block of code multiple times — essential for processing lists, repeating actions, and avoiding code duplication.', 1, 3),
      mc('What is a function?', ['A stored set of values', 'A named, reusable block of code that performs a specific task', 'A variable that holds numbers', 'A database query'], 'A named, reusable block of code that performs a specific task', 'Functions let you define logic once and call it multiple times with different inputs — they make code modular, reusable, and easier to understand.', 1, 4),
      mc('What is a data type?', ['A programming language', 'A classification that specifies what kind of value a variable holds', 'A type of coding error', 'A method for storing files'], 'A classification that specifies what kind of value a variable holds', 'Data types (integer, string, boolean, float, etc.) tell the program what kind of data something is and what operations can be performed on it.', 1, 5),
      mc('What does debugging mean?', ['Writing new code features', 'Finding and fixing errors in code', 'Testing code in production', 'Deleting old code'], 'Finding and fixing errors in code', 'Debugging is the process of identifying, analyzing, and fixing bugs (errors) in code — a core skill for any programmer.', 1, 6),
      mc('What is pseudocode?', ['Broken code that doesn\'t run', 'An informal, plain-language description of an algorithm\'s logic', 'A programming language for beginners', 'Code that runs on any system'], 'An informal, plain-language description of an algorithm\'s logic', 'Pseudocode is a way to plan out logic in plain language before writing real code — it helps think through algorithms without worrying about syntax.', 1, 7),
      mc('What is the difference between compiled and interpreted languages?', ['Compiled languages are newer', 'Compiled languages are translated to machine code before running; interpreted languages run line by line', 'Interpreted languages are faster', 'They are functionally identical'], 'Compiled languages are translated to machine code before running; interpreted languages run line by line', 'Compiled languages (C, C++) are converted to machine code once, then run fast. Interpreted languages (Python, JavaScript) are translated at runtime, offering flexibility at some speed cost.', 1, 8),
      oe('Write pseudocode for a program that takes a list of numbers and prints only the even ones.', 'For each number in the list: check if number divided by 2 has no remainder (number mod 2 equals 0). If true, print the number. End loop. Example: list = [1,2,3,4,5,6] → prints 2, 4, 6.', 'A strong answer uses a loop and a conditional correctly. Exact syntax doesn\'t matter — the logic flow should be clear.', 2, 9),
      oe('Why is it important to write readable code, not just code that works?', 'Code is read far more often than it\'s written — by teammates, future you, or anyone maintaining the project. Readable code reduces bugs (clearer logic is easier to reason about), speeds up collaboration, and makes debugging faster. Clever code that no one understands is a liability. Good naming, comments, and structure are as important as correctness.', 'The answer should give practical reasons (maintenance, collaboration, debugging) not just abstract principles.', 2, 10),
    ],
  },

  'web-development-basics': {
    title: 'Web Development Basics Assessment',
    passingScore: 75,
    timeLimitMin: 30,
    questions: [
      mc('What does HTML stand for and what is it used for?', ['HyperText Markup Language — defining the structure and content of web pages', 'Hyperlink and Text Management Language — managing links', 'HyperText Modern Language — styling websites', 'Home Transfer Markup Language — building mobile apps'], 'HyperText Markup Language — defining the structure and content of web pages', 'HTML is the backbone of web pages — it uses tags to define the structure and meaning of content: headings, paragraphs, images, links, etc.', 1, 1),
      mc('What role does CSS play in web development?', ['Adding interactivity and logic', 'Controlling the visual presentation and layout of HTML elements', 'Storing data in databases', 'Handling server-side processing'], 'Controlling the visual presentation and layout of HTML elements', 'CSS (Cascading Style Sheets) controls how HTML elements look — colors, fonts, sizes, layout, spacing, responsive design.', 1, 2),
      mc('What does JavaScript do in a web page?', ['Defines structure', 'Controls styling', 'Adds interactivity and dynamic behavior', 'Manages databases'], 'Adds interactivity and dynamic behavior', 'JavaScript runs in the browser and makes pages interactive — responding to clicks, updating content without page reloads, validating forms, animations, and more.', 1, 3),
      mc('What is the difference between front-end and back-end development?', ['Front-end is mobile; back-end is web', 'Front-end is what users see; back-end handles server logic, databases, and APIs', 'They are the same', 'Back-end runs in the browser; front-end runs on the server'], 'Front-end is what users see; back-end handles server logic, databases, and APIs', 'Front-end (HTML, CSS, JavaScript) is the user interface. Back-end (servers, databases, APIs) handles data processing, storage, and business logic.', 1, 4),
      mc('What is an API?', ['A programming language for beginners', 'An interface that allows different software systems to communicate', 'A type of database', 'A web design framework'], 'An interface that allows different software systems to communicate', 'APIs (Application Programming Interfaces) define how software components talk to each other — how your app requests data from a server or third-party service.', 1, 5),
      mc('What is a responsive website?', ['A website that loads quickly', 'A site that adapts its layout to different screen sizes', 'A site with a lot of animations', 'A website that responds to voice commands'], 'A site that adapts its layout to different screen sizes', 'Responsive design ensures websites look and function well on phones, tablets, and desktops — using flexible layouts, media queries, and relative units.', 1, 6),
      mc('What does it mean to "inspect element" in a browser?', ['View the server\'s source code', 'Use developer tools to examine and modify a page\'s HTML, CSS, and JavaScript live', 'Check the page for errors', 'View the site\'s database'], 'Use developer tools to examine and modify a page\'s HTML, CSS, and JavaScript live', 'Browser dev tools allow you to inspect, debug, and experiment with a page\'s code in real time — invaluable for development and learning.', 1, 7),
      mc('What is a domain name?', ['An IP address for a website', 'The human-readable address used to access a website (e.g., example.com)', 'A type of web hosting', 'The file structure of a website'], 'The human-readable address used to access a website (e.g., example.com)', 'Domain names are registered through registrars and mapped to IP addresses via DNS, making websites accessible without memorizing numbers.', 1, 8),
      oe('Describe the roles of HTML, CSS, and JavaScript using a house as an analogy.', 'HTML is the structure — walls, floors, rooms. CSS is the interior design — paint, furniture arrangement, aesthetic choices. JavaScript is the electricity and plumbing — the dynamic systems that make things functional and interactive. All three work together to create a complete, livable, interactive space.', 'A strong answer clearly maps each technology to a distinct, accurate role in the analogy.', 2, 9),
      oe('What is the difference between a static website and a dynamic website? Give an example of each.', 'Static: every visitor sees the same pre-built HTML files. Fast, simple, no database needed. Example: a simple personal portfolio or landing page. Dynamic: content is generated on the fly based on user data, a database, or logic. Example: Facebook (your feed is unique), Amazon (product pages are generated from data). Dynamic sites require a back-end server and database.', 'A strong answer explains the generation mechanism (pre-built vs. generated) and gives examples that make sense.', 2, 10),
    ],
  },

  'data-and-spreadsheets': {
    title: 'Data and Spreadsheets Assessment',
    passingScore: 75,
    timeLimitMin: 30,
    questions: [
      mc('What is a cell in a spreadsheet?', ['A tab or worksheet', 'The intersection of a row and column where data is entered', 'A formula bar', 'A chart type'], 'The intersection of a row and column where data is entered', 'Cells are the basic units of a spreadsheet, identified by column letter and row number (e.g., A1, B3). Each cell holds a value, formula, or text.', 1, 1),
      mc('What does the SUM function do?', ['Counts the number of cells with data', 'Adds together all values in a specified range', 'Averages a range of numbers', 'Finds the largest value'], 'Adds together all values in a specified range', 'SUM is the most common spreadsheet function — =SUM(A1:A10) adds up all values in cells A1 through A10.', 1, 2),
      mc('What does VLOOKUP do?', ['Validates data entry', 'Looks up a value in a column and returns a corresponding value from another column', 'Sorts a list vertically', 'Counts values meeting a condition'], 'Looks up a value in a column and returns a corresponding value from another column', 'VLOOKUP (Vertical Lookup) searches for a value in the first column of a range and returns the value from a specified column in the same row — essential for joining data from different tables.', 1, 3),
      mc('What is a pivot table?', ['A table that automatically sorts data', 'A tool for summarizing, grouping, and analyzing data without writing formulas', 'A type of chart', 'A locked table that can\'t be edited'], 'A tool for summarizing, grouping, and analyzing data without writing formulas', 'Pivot tables let you drag and drop fields to summarize large datasets — calculating totals, averages, and counts by different categories interactively.', 1, 4),
      mc('What is a relative vs. absolute cell reference?', ['Absolute references use dollar signs; relative references adjust when copied to new cells', 'They are identical', 'Relative references never change; absolute ones do', 'Absolute references are for text; relative for numbers'], 'Absolute references use dollar signs; relative references adjust when copied to new cells', 'Relative (A1) — shifts when you copy the formula. Absolute ($A$1) — always refers to the same cell regardless of where the formula is copied.', 1, 5),
      mc('What does the AVERAGE function calculate?', ['The most frequent value in a range', 'The middle value in a sorted range', 'The arithmetic mean of a range of numbers', 'The sum divided by 100'], 'The arithmetic mean of a range of numbers', '=AVERAGE(A1:A10) sums all values in the range and divides by the count — giving you the arithmetic mean.', 1, 6),
      mc('What is data validation in a spreadsheet?', ['Checking that formulas are correct', 'Restricting what type or range of data can be entered in a cell', 'Formatting cells with colors', 'Sorting data alphabetically'], 'Restricting what type or range of data can be entered in a cell', 'Data validation sets rules for cell input — like only allowing numbers between 1–100, a dropdown list, or dates — preventing errors and ensuring consistency.', 1, 7),
      mc('What does conditional formatting do?', ['Applies formulas based on conditions', 'Automatically changes cell appearance (color, font) based on cell values', 'Filters data by condition', 'Sorts cells by color'], 'Automatically changes cell appearance (color, font) based on cell values', 'Conditional formatting highlights cells visually based on rules — like turning cells red when values fall below a threshold — making patterns and outliers immediately visible.', 1, 8),
      oe('You have a spreadsheet with 500 rows of sales data including salesperson name, region, product, and amount. How would you use a pivot table to find total sales by region?', 'Insert a pivot table from the data range. Drag "Region" to the Rows area. Drag "Amount" to the Values area (set to Sum). The pivot table will show one row per unique region with the total sales for each. You can then add filters, sort by amount, or drill down further by adding more fields.', 'A strong answer correctly describes placing Region in rows and Amount as a summed value — not just "use a pivot table."', 2, 9),
      oe('Why is it important to keep raw data separate from calculations and summaries in a spreadsheet?', 'Raw data should be untouched — it\'s the source of truth. If you mix calculations into the raw data sheet, you risk overwriting original values, making errors hard to trace. Separate sheets for raw data vs. analysis make it clear what\'s input vs. output, allow you to redo analysis without re-entering data, and make sharing and auditing easier.', 'The answer should explain the data integrity argument — not just "it keeps things organized."', 2, 10),
    ],
  },

  'cybersecurity-basics': {
    title: 'Cybersecurity Basics Assessment',
    passingScore: 75,
    timeLimitMin: 30,
    questions: [
      mc('What is phishing?', ['A type of firewall attack', 'A social engineering attack using fake communications to steal credentials or data', 'Malware that encrypts your files', 'A network intrusion technique'], 'A social engineering attack using fake communications to steal credentials or data', 'Phishing uses deceptive emails, texts, or fake websites to trick users into revealing passwords, credit cards, or other sensitive information.', 1, 1),
      mc('What is two-factor authentication (2FA)?', ['Using two passwords', 'Requiring a second verification step (like a code) in addition to a password', 'Logging in from two devices simultaneously', 'Having two separate accounts'], 'Requiring a second verification step (like a code) in addition to a password', '2FA adds a second layer — even if someone steals your password, they can\'t log in without the second factor (SMS code, authenticator app, hardware key).', 1, 2),
      mc('What is malware?', ['Outdated software', 'Malicious software designed to damage, steal, or gain unauthorized access', 'A broken website', 'Slow internet connection'], 'Malicious software designed to damage, steal, or gain unauthorized access', 'Malware (malicious software) includes viruses, trojans, spyware, ransomware, and more — all designed to harm systems or extract data without authorization.', 1, 3),
      mc('What is a strong password?', ['Any password you can remember', 'A long, random combination of letters, numbers, and symbols not used elsewhere', 'Your name and birthday', 'A word from the dictionary with a number at the end'], 'A long, random combination of letters, numbers, and symbols not used elsewhere', 'Strong passwords are long (12+ characters), complex, unique per site, and not based on guessable personal information. Password managers make this practical.', 1, 4),
      mc('What is ransomware?', ['Software that holds your data hostage by encrypting it and demanding payment', 'A virus that steals passwords', 'Advertising software', 'A fake antivirus program'], 'Software that holds your data hostage by encrypting it and demanding payment', 'Ransomware encrypts your files and demands payment (often cryptocurrency) for the decryption key. Paying doesn\'t guarantee recovery.', 1, 5),
      mc('What does "end-to-end encryption" mean?', ['Encryption from your device to the server', 'Messages are encrypted so only the sender and recipient can read them — not even the service provider', 'Encryption of files on your hard drive', 'A firewall protecting both ends of a connection'], 'Messages are encrypted so only the sender and recipient can read them — not even the service provider', 'End-to-end encryption (used in Signal, WhatsApp) ensures no third party — including the app company — can read your messages in transit.', 1, 6),
      mc('What is a data breach?', ['Accidental deletion of data', 'Unauthorized access to or exposure of private data', 'A database backup failure', 'Deleting a user account'], 'Unauthorized access to or exposure of private data', 'Data breaches occur when attackers (or sometimes insiders) access data they shouldn\'t — exposing personal information, credentials, or sensitive business data.', 1, 7),
      mc('What is the principle of least privilege?', ['Only admins can access the internet', 'Users and systems should have only the minimum access necessary to perform their function', 'Employees should use simple passwords', 'Privileged users have fewer security rules'], 'Users and systems should have only the minimum access necessary to perform their function', 'Least privilege limits damage from breaches — if an account is compromised, attackers only get what that account could access, not everything.', 1, 8),
      oe('You receive an email from your "bank" saying your account is locked and you must click a link immediately. Describe the red flags and what you should do.', 'Red flags: urgency and pressure, generic greeting, link URL doesn\'t match official bank domain, asking for credentials via email. What to do: don\'t click any links, don\'t call numbers in the email, open a new browser and go directly to the bank\'s real website or call the number on the back of your card. Report the phishing email to your bank and email provider.', 'A strong answer names specific red flags (urgency, fake URL) and gives concrete steps that avoid the attack.', 2, 9),
      oe('Why is reusing the same password across multiple sites dangerous?', 'If one site is breached, attackers use "credential stuffing" — trying the stolen username/password combination on other sites. Since most people reuse passwords, attackers gain access to email, banking, and other accounts with one breach. A unique password per site limits breach damage to that single account. Use a password manager to make this practical.', 'The answer must explain credential stuffing specifically — not just "passwords can be stolen."', 2, 10),
    ],
  },

  'ai-and-automation-literacy': {
    title: 'AI and Automation Literacy Assessment',
    passingScore: 75,
    timeLimitMin: 30,
    questions: [
      mc('What is machine learning?', ['Programming a computer with explicit rules', 'A type of database management', 'Training a model to find patterns in data and make predictions without explicit programming', 'Automated software testing'], 'Training a model to find patterns in data and make predictions without explicit programming', 'Machine learning lets computers learn from examples — the system finds patterns in training data and applies them to new data without being explicitly programmed for each case.', 1, 1),
      mc('What is a large language model (LLM)?', ['A very large dictionary', 'An AI system trained on massive text data to generate and understand language', 'A translation tool', 'A database of books'], 'An AI system trained on massive text data to generate and understand language', 'LLMs (like GPT, Claude) are trained on huge amounts of text and learn statistical patterns in language — enabling them to write, answer questions, summarize, and reason.', 1, 2),
      mc('What does "AI hallucination" mean?', ['AI becoming self-aware', 'When an AI generates confident, plausible-sounding but false information', 'AI producing unusual visual art', 'When AI systems crash'], 'When an AI generates confident, plausible-sounding but false information', 'AI hallucinations are factual errors presented convincingly. LLMs don\'t look things up — they predict text. Sometimes that produces incorrect "facts."', 1, 3),
      mc('What is automation in a business context?', ['Replacing all employees with robots', 'Using technology to perform repetitive tasks without human intervention', 'A scheduling software', 'Outsourcing work to another country'], 'Using technology to perform repetitive tasks without human intervention', 'Business automation uses software, scripts, or machines to handle repetitive, rule-based tasks — freeing humans for higher-value work.', 1, 4),
      mc('What is a training dataset?', ['A practice test for programmers', 'The data used to teach a machine learning model', 'A dataset kept for testing after training', 'A government data repository'], 'The data used to teach a machine learning model', 'Training data is what the model learns from — it\'s examples with known inputs and outputs that the algorithm studies to find patterns.', 1, 5),
      mc('What is algorithmic bias?', ['When computer algorithms are faster than humans', 'When AI systems produce systematically unfair results due to biased training data or design', 'When algorithms make mathematical errors', 'Preferring algorithmic over manual decisions'], 'When AI systems produce systematically unfair results due to biased training data or design', 'If training data reflects historical discrimination or over-represents certain groups, AI learns those biases and may perpetuate or amplify unfair outcomes.', 1, 6),
      mc('What is a prompt in the context of AI?', ['A software update command', 'The input text or instruction given to an AI model to guide its response', 'A type of training data', 'An AI error message'], 'The input text or instruction given to an AI model to guide its response', 'Prompts are how users communicate tasks to AI systems. The quality and specificity of the prompt strongly influences the quality of the output.', 1, 7),
      mc('What is robotic process automation (RPA)?', ['Physical robots replacing warehouse workers', 'Software that automates repetitive digital tasks by mimicking human computer interactions', 'AI that controls factory machines', 'A type of cybersecurity tool'], 'Software that automates repetitive digital tasks by mimicking human computer interactions', 'RPA software bots can log into systems, copy/paste data, fill forms, and run reports — automating work that previously required human clicks and keystrokes.', 1, 8),
      oe('What are the potential benefits and risks of increasing automation in the workplace?', 'Benefits: increased productivity, reduced errors on repetitive tasks, lower costs, freeing workers for creative/interpersonal work. Risks: job displacement (especially routine jobs), widening inequality if benefits go only to owners, skills gaps as jobs change, over-reliance on automation creating fragility. The key is managing transitions — retraining workers and ensuring the gains are broadly shared.', 'A strong answer gives substantive points on both sides — not just "some jobs are lost but new ones are created."', 2, 9),
      oe('How should you verify information you get from an AI chatbot?', 'AI can be confidently wrong. Verification steps: check the claim against authoritative sources (official websites, peer-reviewed research, reputable news). Ask the AI to cite sources, then verify those sources exist and say what the AI claims. Be especially skeptical of specific statistics, quotes, dates, and names — these are common hallucination points. AI is a starting point, not a final source.', 'A strong answer explains why AI is unreliable for facts and gives concrete verification steps.', 2, 10),
    ],
  },
}
