import type { ExerciseDef } from '../types'

function mc(
  question: string,
  options: string[],
  correctAnswer: string,
  explanation: string,
  order: number
): ExerciseDef {
  return { question, type: 'MULTIPLE_CHOICE', options, correctAnswer, explanation, order }
}

export const techExercises7: Record<string, ExerciseDef[]> = {
  'common-attacks': [
    mc('What is phishing?', ['Scanning a network for open ports', 'Tricking someone into revealing credentials via fake emails or sites', 'Installing software without permission', 'Overloading a server with requests'], 'Tricking someone into revealing credentials via fake emails or sites', 'Phishing uses deceptive emails or fake websites to trick victims into entering passwords or other sensitive information.', 1),
    mc('What distinguishes spear phishing from regular phishing?', ['It uses malware instead of emails', 'It targets a specific individual using personalized details', 'It attacks network hardware directly', 'It only works on mobile devices'], 'It targets a specific individual using personalized details', 'Spear phishing is highly targeted — attackers research the victim and craft convincing, personalized messages.', 2),
    mc('What is ransomware?', ['Software that monitors your keystrokes', 'Malware that encrypts your files and demands payment', 'A fake antivirus program', 'Software that steals your browser history'], 'Malware that encrypts your files and demands payment', 'Ransomware locks or encrypts your files and demands payment (usually cryptocurrency) for the decryption key.', 3),
    mc('Social engineering attacks primarily exploit:', ['Software vulnerabilities', 'Hardware weaknesses', 'Human psychology and trust', 'Network misconfigurations'], 'Human psychology and trust', 'Social engineering bypasses technical defenses by manipulating people — exploiting trust, authority, urgency, or fear.', 4),
    mc('Which is the best defense against most phishing attacks?', ['Faster antivirus software', 'Skepticism and verification before clicking or entering credentials', 'A more expensive firewall', 'Using a VPN at all times'], 'Skepticism and verification before clicking or entering credentials', 'Pausing to verify the sender and URL — before clicking links or entering passwords — stops most phishing attempts.', 5),
  ],
  'passwords-and-authentication': [
    mc('What makes a password strong?', ['It contains your birthday and name', 'It is long, random, and unique to each site', 'It uses only numbers for easy recall', 'It is short but complex'], 'It is long, random, and unique to each site', 'Length and uniqueness matter most. A long random password that is never reused is far harder to crack than a short complex one.', 1),
    mc('What does MFA (multi-factor authentication) add?', ['A second password requirement', 'A second form of verification beyond just a password', 'Biometric login replacing passwords', 'A VPN layer for all logins'], 'A second form of verification beyond just a password', 'MFA requires something you know (password) plus something you have (phone/app) or something you are (fingerprint).', 2),
    mc('Why is reusing passwords across sites dangerous?', ['It slows down your computer', 'A breach at one site exposes all accounts using that password', 'It violates most terms of service', 'It makes passwords easier to guess'], 'A breach at one site exposes all accounts using that password', 'Credential stuffing attacks use leaked passwords from one breach to try logging in everywhere else — reuse makes this devastating.', 3),
    mc('What is a password manager?', ['A browser that saves passwords in plain text', 'Software that securely generates and stores unique passwords for each site', 'A tool that resets forgotten passwords automatically', 'A government service for password recovery'], 'Software that securely generates and stores unique passwords for each site', 'Password managers create and remember strong unique passwords for every site, so you only need to remember one master password.', 4),
    mc('Which MFA method is generally most secure?', ['SMS text message codes', 'Email verification codes', 'An authenticator app or hardware security key', 'Security questions'], 'An authenticator app or hardware security key', 'SMS can be intercepted via SIM swapping. Authenticator apps and hardware keys are much harder to compromise.', 5),
  ],
  'how-breaches-happen': [
    mc('What is a data breach?', ['When a company accidentally deletes customer records', 'Unauthorized access and exposure of protected information', 'A server going offline unexpectedly', 'A software update that corrupts data'], 'Unauthorized access and exposure of protected information', 'A breach occurs when attackers (or insiders) gain unauthorized access to sensitive data — passwords, financial info, personal records.', 1),
    mc('What is credential stuffing?', ['Using stolen username/password pairs to try logging into other services', 'Guessing passwords using common words', 'Installing keyloggers on victim computers', 'Creating fake login pages'], 'Using stolen username/password pairs to try logging into other services', 'Attackers buy leaked credentials from one breach and automatically test them across hundreds of other websites.', 2),
    mc('What percentage of breaches involve a human element (phishing, stolen creds, error)?', ['About 10%', 'About 30%', 'Over 60%', 'Almost none'], 'Over 60%', 'Verizon\'s DBIR consistently finds that over 60-80% of breaches involve people — phishing, weak passwords, or human error.', 3),
    mc('What is an insider threat?', ['A hacker who exploits insider knowledge of software', 'A current or former employee who misuses access to harm the organization', 'Malware that hides inside legitimate programs', 'An attack that originates from within a country'], 'A current or former employee who misuses access to harm the organization', 'Insiders have legitimate access — breaches caused by employees (malicious or negligent) are especially hard to prevent.', 4),
    mc('Why do companies store hashed passwords instead of plain text?', ['Hashing speeds up the login process', 'If the database is stolen, attackers can\'t immediately use the passwords', 'Plain text storage is illegal everywhere', 'Hashing compresses data to save space'], 'If the database is stolen, attackers can\'t immediately use the passwords', 'Hashing is one-way — even if attackers steal the database, they still have to crack the hashes to recover usable passwords.', 5),
  ],
  'personal-security-practices': [
    mc('What should you do if you receive a suspicious email asking you to verify your account?', ['Click the link but don\'t enter your password', 'Go directly to the company\'s website by typing the address yourself', 'Reply asking if it\'s real', 'Forward it to your contacts as a warning'], 'Go directly to the company\'s website by typing the address yourself', 'Never click links in suspicious emails. Go directly to the site by typing the URL — this bypasses any fake pages.', 1),
    mc('Which of these is a warning sign of a scam?', ['The message uses your full name', 'Urgent pressure to act immediately or face consequences', 'The email came from a company you use', 'The message has a company logo'], 'Urgent pressure to act immediately or face consequences', 'Scammers create artificial urgency to prevent you from thinking carefully or verifying the request.', 2),
    mc('How often should you update your software and operating system?', ['Only when something breaks', 'Once a year during scheduled maintenance', 'As soon as updates are available', 'Never — updates can break things'], 'As soon as updates are available', 'Updates patch security vulnerabilities. Delayed updates are one of the most common ways systems get compromised.', 3),
    mc('What is the safest approach to public Wi-Fi?', ['Use it freely — encryption protects everything', 'Avoid sensitive accounts or use a VPN when on public Wi-Fi', 'Only use it for email, not banking', 'It is safe as long as the network has a password'], 'Avoid sensitive accounts or use a VPN when on public Wi-Fi', 'Public Wi-Fi can be monitored. Use a VPN or avoid logging into sensitive accounts (banking, email) on public networks.', 4),
    mc('What is two-factor authentication primarily designed to protect against?', ['Malware on your device', 'Someone who has stolen your password', 'Physical theft of your phone', 'Network monitoring attacks'], 'Someone who has stolen your password', 'Even if an attacker has your password, 2FA blocks them because they don\'t have your second factor (phone, app, key).', 5),
  ],
  'securing-devices': [
    mc('Why should you use a PIN or password on your phone?', ['It makes the phone faster', 'It protects data if the phone is lost or stolen', 'It is required by law', 'It prevents apps from using data'], 'It protects data if the phone is lost or stolen', 'Without a lock screen, anyone who finds your phone has access to email, banking, photos, and all accounts.', 1),
    mc('What does full-disk encryption do?', ['Compresses files to save storage space', 'Makes files unreadable without the correct credentials', 'Automatically backs up your data', 'Prevents software from being installed'], 'Makes files unreadable without the correct credentials', 'Encryption scrambles data so it\'s useless to anyone who doesn\'t have the key — critical if a device is stolen.', 2),
    mc('Why should you be cautious about apps you install?', ['Apps use battery life', 'Apps request permissions and may access your camera, microphone, or data', 'Too many apps slow app store browsing', 'App stores charge for storage'], 'Apps request permissions and may access your camera, microphone, or data', 'Apps request access to sensitive device features. Malicious or careless apps can harvest data or track you.', 3),
    mc('What is the purpose of a firewall?', ['To speed up internet connections', 'To monitor and control incoming and outgoing network traffic', 'To encrypt your hard drive', 'To scan for viruses in real time'], 'To monitor and control incoming and outgoing network traffic', 'A firewall filters network traffic based on rules, blocking unauthorized connections to or from your device.', 4),
    mc('What should you do before selling or disposing of an old device?', ['Delete your photos and texts', 'Factory reset and/or wipe the drive completely', 'Remove the SIM card only', 'Log out of all apps'], 'Factory reset and/or wipe the drive completely', 'Simply deleting files or logging out doesn\'t remove data. A full wipe ensures the next owner can\'t recover your information.', 5),
  ],
  'network-security': [
    mc('What is a default router password, and why is it a security risk?', ['A password set by your ISP that changes monthly', 'The factory-set password on the router — it\'s public knowledge and should be changed immediately', 'An auto-generated strong password unique to each device', 'The WPA2 key printed on the router label'], 'The factory-set password on the router — it\'s public knowledge and should be changed immediately', 'Default passwords are published online. Attackers scan for routers still using defaults to take control of the network.', 1),
    mc('What does WPA3 refer to?', ['A type of firewall', 'A Wi-Fi encryption standard', 'A VPN protocol', 'A network speed rating'], 'A Wi-Fi encryption standard', 'WPA3 (Wi-Fi Protected Access 3) is the current standard for encrypting wireless traffic on home and enterprise networks.', 2),
    mc('What is a network intrusion detection system (IDS)?', ['Software that automatically fixes network problems', 'A system that monitors network traffic for suspicious activity', 'A tool that encrypts all network packets', 'A backup internet connection'], 'A system that monitors network traffic for suspicious activity', 'An IDS watches network traffic for patterns matching known attacks or anomalies, and alerts administrators.', 3),
    mc('Why should IoT devices (smart TVs, thermostats) be on a separate network segment?', ['They use too much bandwidth on the main network', 'If compromised, they can\'t be used to attack computers on the main network', 'They require different DNS settings', 'Smart devices need lower latency'], 'If compromised, they can\'t be used to attack computers on the main network', 'Network segmentation contains breaches — a compromised smart bulb shouldn\'t be able to reach your banking computer.', 4),
    mc('What is the primary purpose of a DMZ in network security?', ['To block all foreign network traffic', 'To host public-facing servers separate from the internal network', 'To duplicate data for redundancy', 'To increase network speed for gaming'], 'To host public-facing servers separate from the internal network', 'A DMZ puts internet-facing servers (web, email) in a separate zone so attacks on them don\'t directly reach internal systems.', 5),
  ],
  'encryption-basics': [
    mc('What is encryption?', ['Compressing data to reduce file size', 'Converting data into an unreadable format that requires a key to decode', 'Backing up data to a secure server', 'Removing sensitive fields from a database'], 'Converting data into an unreadable format that requires a key to decode', 'Encryption scrambles data so only someone with the correct key can read it — protecting confidentiality in transit and at rest.', 1),
    mc('What is the difference between symmetric and asymmetric encryption?', ['Symmetric is for files; asymmetric is for networks', 'Symmetric uses one key for both encryption and decryption; asymmetric uses a public/private key pair', 'Symmetric is stronger; asymmetric is faster', 'Symmetric is old; asymmetric is modern'], 'Symmetric uses one key for both encryption and decryption; asymmetric uses a public/private key pair', 'Symmetric is fast but requires sharing a secret key. Asymmetric solves this — you can share your public key openly.', 2),
    mc('What does the padlock icon in a browser\'s address bar indicate?', ['The website is safe and trustworthy', 'The connection between your browser and the server is encrypted (HTTPS)', 'The site has been verified by the government', 'Your data is stored securely on the server'], 'The connection between your browser and the server is encrypted (HTTPS)', 'HTTPS means the connection is encrypted — it doesn\'t guarantee the site itself is safe, just that data in transit is protected.', 3),
    mc('What is end-to-end encryption?', ['Encryption applied only to stored data', 'Encryption where only the sender and recipient can read the message', 'Encryption handled by the service provider', 'A protocol for encrypting emails in transit'], 'Encryption where only the sender and recipient can read the message', 'End-to-end encryption means even the service provider can\'t read your messages — only the two endpoints hold the keys.', 4),
    mc('Why is it important to use HTTPS on websites that collect form data?', ['HTTPS makes pages load faster', 'Data entered in forms is encrypted so it can\'t be read by network eavesdroppers', 'HTTP forms don\'t work on mobile devices', 'HTTPS prevents phishing attacks'], 'Data entered in forms is encrypted so it can\'t be read by network eavesdroppers', 'Without HTTPS, form data (passwords, credit cards) is sent in plain text and can be intercepted on the network.', 5),
  ],
}
