import type { ExerciseDef } from '../types'

function mc(question: string, options: string[], correctAnswer: string, explanation: string, order: number): ExerciseDef {
  return { question, type: 'MULTIPLE_CHOICE', options, correctAnswer, explanation, order }
}

export const tradesExercises4: Record<string, ExerciseDef[]> = {
  'thermostats-and-controls': [
    mc('A two-wire thermostat circuit (R and W terminals) controls what type of system?', ['A heat pump with auxiliary heat', 'A basic single-stage heating system only', 'A dual-fuel system with gas and electric backup', 'A multi-zone hydronic heating system'], 'A basic single-stage heating system only', 'R (power) and W (heat call) is the simplest thermostat wiring — it controls one stage of heating. Adding cooling requires a Y terminal; fan control adds G; second stages add W2/Y2; C is the common wire for smart thermostats.', 1),
    mc('A "C wire" (common wire) on a thermostat is required for:', ['All thermostats in forced-air systems', 'Smart and programmable thermostats that need continuous low-voltage power', 'Two-wire heating-only systems', 'Any thermostat controlling a heat pump'], 'Smart and programmable thermostats that need continuous low-voltage power', 'Smart thermostats have WiFi radios, displays, and processors that need constant power. The C wire completes the 24V circuit back to the transformer, providing steady power instead of harvesting power from control signals.', 2),
    mc('The "anticipator" setting on an older mechanical thermostat prevents:', ['The system from short-cycling too frequently', 'The room from overshooting the set temperature by shutting off heating slightly early', 'The thermostat from reading the temperature of the air handler instead of the room', 'The compressor from running in sub-freezing temperatures'], 'The room from overshooting the set temperature by shutting off heating slightly early', 'The heat anticipator adds a tiny bit of heat inside the thermostat, causing it to call for heat slightly less often. This compensates for residual heat in the system after the burner shuts off, preventing temperature overshoot.', 3),
    mc('A programmable thermostat set to 62°F at night and 70°F at 6 AM will:', ['Begin heating at 6 AM and reach 70°F sometime after that', 'Attempt to reach 70°F BY 6 AM using the schedule', 'Only adjust the temperature when the occupant presses the override button', 'Depend entirely on the HVAC system capacity; the thermostat has no knowledge of when to start'], 'Begin heating at 6 AM and reach 70°F sometime after that', 'Basic programmable thermostats start at the scheduled time. "Smart" thermostats with adaptive recovery learn how long the system needs and start early to achieve the setpoint by the scheduled time.', 4),
    mc('What does "emergency heat" mode do on a heat pump thermostat?', ['Activates the heat pump at maximum capacity during extreme cold', 'Bypasses the heat pump and runs only the backup electric resistance heat', 'Activates both the heat pump and backup heat simultaneously for faster warming', 'Prevents the outdoor unit from running to protect it during an ice storm'], 'Bypasses the heat pump and runs only the backup electric resistance heat', 'Emergency heat should only be used when the heat pump is broken. It runs the backup strips only, which is far less efficient than the heat pump. Running in emergency heat mode continuously will dramatically increase electric bills.', 5),
  ],
  'preventive-maintenance': [
    mc('How often should standard 1-inch HVAC air filters be replaced?', ['Once a year', 'Every 1-3 months, depending on usage and household conditions', 'Every 6 months for most homes', 'Only when the system seems to be working harder than normal'], 'Every 1-3 months, depending on usage and household conditions', 'A dirty filter restricts airflow, reducing efficiency, stressing the blower, and causing the coil to ice. Homes with pets or allergy sufferers may need monthly changes. Thicker media filters (4-5 inch) can last 6-12 months.', 1),
    mc('What should be done with the condensate drain line on an AC system each cooling season?', ['Replaced entirely to prevent mold buildup', 'Flushed with a diluted bleach solution to prevent algae clogs', 'Sealed tightly to prevent outdoor insects from entering', 'Inspected only when water overflows the drain pan'], 'Flushed with a diluted bleach solution to prevent algae clogs', 'The condensate drain line removes water from the evaporator coil. Algae and mold grow in this dark, damp line and eventually clog it, causing the drain pan to overflow and potentially damaging ceilings. Annual bleach flush prevents this.', 2),
    mc('Cleaning the outdoor condenser coil fins annually is important because:', ['Dirty fins reduce the refrigerant charge in the system', 'Debris on the coil reduces heat rejection, decreasing efficiency and increasing compressor wear', 'Dirty fins cause refrigerant leaks at the coil connections', 'The fins must be straight for the warranty to remain valid'], 'Debris on the coil reduces heat rejection, decreasing efficiency and increasing compressor wear', 'The condenser rejects heat from the refrigerant to the outdoor air. Clogged fins trap heat, forcing the compressor to work harder against higher head pressure — reducing efficiency and shortening compressor life.', 3),
    mc('What is the purpose of lubricating blower motor bearings during preventive maintenance?', ['To reduce electrical consumption of the motor', 'To prevent premature bearing failure and extend motor life', 'To reduce vibration noise from the air handler cabinet', 'To prevent ice from forming on the motor shaft'], 'To prevent premature bearing failure and extend motor life', 'Many older blower motors have oil ports that require annual lubrication. Dry bearings overheat and fail prematurely. Modern PSC and ECM motors are typically sealed and maintenance-free.', 4),
    mc('When should an HVAC technician check refrigerant charge?', ['At every annual service as a standard procedure', 'Only when symptoms suggest a problem (inadequate cooling, icing, long run times)', 'Every spring before cooling season starts regardless of symptoms', 'Only when the system is more than 10 years old'], 'Only when symptoms suggest a problem (inadequate cooling, icing, long run times)', 'Refrigerant doesn\'t deplete in a properly sealed system. Checking charge every year is unnecessary and adds cost. Check charge when there are symptoms of low charge. Finding low charge should always prompt a leak search.', 5),
  ],
  'refrigerants': [
    mc('Why was R-22 (Freon) phased out under the Montreal Protocol?', ['It was too expensive to manufacture at scale', 'It is an ozone-depleting substance that damages the stratospheric ozone layer', 'It was found to cause cancer in HVAC technicians', 'It reacted with newer compressor oils and caused system failures'], 'It is an ozone-depleting substance that damages the stratospheric ozone layer', 'R-22 is a hydrochlorofluorocarbon (HCFC). When released into the atmosphere, chlorine atoms destroy ozone molecules. The Montreal Protocol phased out production globally; R-22 is no longer manufactured in the US.', 1),
    mc('Section 608 of the Clean Air Act requires technicians working with refrigerants to:', ['Use only EPA-approved refrigerants in all systems', 'Hold an EPA 608 certification and use certified recovery equipment — not venting refrigerant', 'Report all refrigerant purchases to the EPA annually', 'Replace refrigerant entirely each time a system is opened'], 'Hold an EPA 608 certification and use certified recovery equipment — not venting refrigerant', 'Intentional venting of refrigerants is illegal. Technicians must be EPA 608 certified, recover refrigerant into approved cylinders before opening systems, and properly reclaim or recycle refrigerant.', 2),
    mc('R-410A operates at significantly higher pressures than R-22. What does this mean for technicians?', ['R-410A systems require lower-capacity compressors', 'R-410A requires different (higher-rated) gauges and hoses designed for its operating pressures', 'R-410A can be mixed with R-22 in an emergency', 'Higher pressure means less refrigerant is needed per system'], 'R-410A requires different (higher-rated) gauges and hoses designed for its operating pressures', 'R-410A operates at approximately 70% higher pressure than R-22. Standard R-22 gauge sets are not rated for R-410A pressures. Using the wrong equipment is dangerous and can result in blown hose assemblies.', 3),
    mc('A refrigerant blend (like R-410A) differs from a pure refrigerant because blends:', ['Can be topped off by adding refrigerant in liquid or vapor phase without concern', 'Must be charged as a liquid since the components can fractionate (separate) if charged as vapor', 'Have lower efficiency than pure refrigerants like R-22', 'Cannot be recovered and must be vented during service'], 'Must be charged as a liquid since the components can fractionate (separate) if charged as vapor', 'Zeotropic blends like R-410A can fractionate — the different components have different boiling points and may separate if charged as vapor. Always charge R-410A as liquid from an inverted cylinder.', 4),
    mc('Global warming potential (GWP) has become important in refrigerant selection because:', ['High-GWP refrigerants damage the ozone layer more severely', 'Refrigerants released during service or at end-of-life contribute to greenhouse gas emissions based on their GWP', 'GWP determines the flammability classification of a refrigerant', 'Low-GWP refrigerants are more efficient at the same operating pressures'], 'Refrigerants released during service or at end-of-life contribute to greenhouse gas emissions based on their GWP', 'GWP measures how much heat a gas traps compared to CO2 over 100 years. R-410A has a GWP of 2,088 — meaning a pound released is equivalent to over a ton of CO2. Newer refrigerants like R-32 and R-454B have lower GWPs.', 5),
  ],
  'troubleshooting-basics': [
    mc('The first step in diagnosing any HVAC problem should be:', ['Checking the refrigerant charge', 'Gathering information: what symptoms are present, when did it start, what changed recently', 'Replacing the most commonly failed component for that symptom', 'Calling the equipment manufacturer\'s technical support line'], 'Gathering information: what symptoms are present, when did it start, what changed recently', 'Systematic diagnostics starts with information gathering. Understanding the complaint, when it started, and any recent events (filter change, storm, thermostat adjustment) often points directly to the cause.', 1),
    mc('An air conditioner is running constantly but not cooling adequately. Which is the LEAST likely cause?', ['A dirty air filter restricting airflow', 'Low refrigerant charge reducing heat absorption capacity', 'The thermostat setpoint being higher than the actual room temperature', 'Excessive heat load from open windows or doors in the space'], 'The thermostat setpoint being higher than the actual room temperature', 'If the setpoint is higher than room temp, the system wouldn\'t call for cooling at all. The other three are all common causes of a system that runs without adequately cooling.', 2),
    mc('A furnace ignites but then shuts off after a few seconds (short cycling). The most likely cause is:', ['Low gas pressure at the meter', 'A dirty flame sensor that cannot confirm the burner is lit', 'A failed inducer motor preventing combustion gas exhaust', 'A cracked heat exchanger that must be replaced immediately'], 'A dirty flame sensor that cannot confirm the burner is lit', 'The flame sensor verifies ignition. A coating of oxidation on the sensor prevents it from passing enough current to prove flame to the control board, which shuts down as a safety measure. Cleaning with steel wool is usually a $0 fix.', 3),
    mc('Airflow measurement is an important diagnostic step because:', ['Airflow readings allow you to calculate refrigerant charge without gauges', 'Many HVAC problems — from icing to inadequate heating/cooling — are caused by insufficient or unbalanced airflow', 'Airflow measurement identifies refrigerant leaks at the evaporator coil', 'Only airflow measurements can determine if a heat exchanger is cracked'], 'Many HVAC problems — from icing to inadequate heating/cooling — are caused by insufficient or unbalanced airflow', 'Low airflow causes coil icing, inadequate heat transfer, and uneven comfort. It can be caused by dirty filters, collapsed ducts, closed vents, or undersized ductwork — all of which must be ruled out before blaming refrigerant.', 4),
    mc('When comparing measured supply air temperature to return air temperature, a standard AC system should produce a temperature difference (delta-T) of approximately:', ['5-8°F', '10-15°F', '16-22°F', '25-35°F'], '16-22°F', 'A properly charged and airflow-balanced AC system typically produces a 16-22°F temperature drop across the evaporator coil. Below this range suggests low charge or high load; above it often indicates restricted airflow.', 5),
  ],
  'hvac-tools': [
    mc('A manifold gauge set is used to:', ['Measure airflow through the duct system', 'Measure and manipulate refrigerant pressures on the high and low sides of the system', 'Test thermostat wiring for voltage and continuity', 'Measure the static pressure of the duct system'], 'Measure and manipulate refrigerant pressures on the high and low sides of the system', 'The manifold gauge set connects to the service valves on the suction and discharge lines. Pressure readings combined with temperature measurements allow technicians to evaluate refrigerant charge and system operation.', 1),
    mc('A digital psychrometer (or sling psychrometer) measures:', ['Refrigerant pressure and temperature simultaneously', 'Dry bulb temperature and wet bulb temperature, used to calculate relative humidity', 'Airflow velocity in feet per minute', 'Combustion efficiency of a gas furnace'], 'Dry bulb temperature and wet bulb temperature, used to calculate relative humidity', 'Dry bulb is the regular air temperature. Wet bulb is measured with a moistened sensor — the evaporative cooling effect indicates humidity. Together they determine relative humidity, dew point, and enthalpy.', 2),
    mc('A combustion analyzer is used on gas appliances to measure:', ['The static pressure of the heat exchanger', 'Flue gas components including CO, CO2, O2, and efficiency to verify safe and efficient combustion', 'Refrigerant charge in heat pump systems', 'Duct leakage in the distribution system'], 'Flue gas components including CO, CO2, O2, and efficiency to verify safe and efficient combustion', 'A combustion analyzer samples flue gases and calculates efficiency. It detects dangerous CO levels that may indicate a cracked heat exchanger or incomplete combustion, and verifies the system is burning fuel properly.', 3),
    mc('An anemometer or flow hood is used to measure:', ['Refrigerant flow rate in the system', 'Airflow velocity or volume at registers and grilles', 'Duct static pressure to size equipment properly', 'Blower motor RPM and current draw'], 'Airflow velocity or volume at registers and grilles', 'An anemometer measures air velocity in feet per minute. A flow hood is placed over a register to measure total airflow in CFM. Both are essential for balancing air distribution and diagnosing comfort complaints.', 4),
    mc('Nitrogen is used in HVAC work to:', ['Replace refrigerant temporarily while making repairs', 'Pressure-test and leak-check systems after brazing, before charging with refrigerant', 'Purge moisture from the refrigerant circuit before adding new refrigerant', 'Clean evaporator and condenser coils without corrosive chemicals'], 'Pressure-test and leak-check systems after brazing, before charging with refrigerant', 'Dry nitrogen (oxygen-free) is used to pressure-test repaired systems for leaks before pulling a vacuum and charging. It also prevents oxidation inside copper tubing during brazing when used as a flowing purge gas.', 5),
  ],
  'types-of-wood': [
    mc('What is the difference between hardwood and softwood?', ['Hardwood is always harder than softwood; softwood is always softer', 'Hardwood comes from deciduous trees; softwood comes from coniferous trees — though some softwoods are physically harder than some hardwoods', 'Softwood is only used for furniture; hardwood is only used for framing', 'Hardwood requires special tools; softwood can be cut with any saw'], 'Hardwood comes from deciduous trees; softwood comes from coniferous trees — though some softwoods are physically harder than some hardwoods', 'The terms are botanical, not physical. Oak, maple, and walnut are hardwoods (deciduous). Pine, fir, and cedar are softwoods (coniferous). Balsa is a hardwood but is physically very soft; longleaf pine is a softwood but is physically quite hard.', 1),
    mc('Dimensional lumber sold as "2x4" actually measures:', ['2 inches by 4 inches', '1.5 inches by 3.5 inches', '1.75 inches by 3.75 inches', '2 inches by 3.5 inches'], '1.5 inches by 3.5 inches', 'Dimensional lumber is surfaced (planed) after rough-cutting, reducing it from nominal to actual dimensions. A 2x4 is 1.5" × 3.5". A 2x6 is 1.5" × 5.5". Knowing this is essential for layout and planning.', 2),
    mc('Plywood is stronger than solid wood of the same thickness because:', ['It contains synthetic resins that add tensile strength', 'Alternating grain directions in adjacent plies resist splitting and distribute stress', 'It is made from the densest hardwood species available', 'The manufacturing process compresses the wood fibers for greater density'], 'Alternating grain directions in adjacent plies resist splitting and distribute stress', 'Plywood is built with each layer\'s grain perpendicular to adjacent layers. This cross-grain construction eliminates the weak directional nature of solid wood, making plywood stable and resistant to splitting.', 3),
    mc('OSB (Oriented Strand Board) vs. plywood: which is typically used for wall and roof sheathing today and why?', ['Plywood, because it is stronger in all applications', 'OSB, because it is less expensive than plywood for equivalent structural performance', 'Neither — solid lumber boards are still standard for sheathing', 'OSB for roofs only; plywood for walls, because of moisture differences'], 'OSB, because it is less expensive than plywood for equivalent structural performance', 'OSB has largely replaced plywood for structural sheathing because it costs 15-30% less for the same structural rating. The tradeoff is that OSB is more susceptible to moisture damage at exposed edges.', 4),
    mc('The moisture content of lumber used for interior framing should ideally be:', ['Below 19% to prevent shrinkage, warping, and nail pops after installation', 'Above 25% so the wood is easy to nail without splitting', 'Exactly 12% regardless of geographic location or application', 'Any moisture content is acceptable since drywall conceals the framing'], 'Below 19% to prevent shrinkage, warping, and nail pops after installation', 'Lumber above 19% moisture content is considered "green" and will shrink, twist, and warp as it dries in service. Shrinkage causes nail pops, drywall cracks, squeaky floors, and sticking doors.', 5),
  ],
}
