import type { ExerciseDef } from '../types'

function mc(question: string, options: string[], correctAnswer: string, explanation: string, order: number): ExerciseDef {
  return { question, type: 'MULTIPLE_CHOICE', options, correctAnswer, explanation, order }
}

export const tradesExercises5: Record<string, ExerciseDef[]> = {
  'reading-a-tape-measure': [
    mc('On a standard tape measure, what does the large diamond or black triangle symbol at 19.2 inches indicate?', ['The halfway point between 16-inch stud spacing', 'The spacing for I-joists and engineered lumber at 5 studs over 8 feet (19.2" on center)', 'A manufacturer quality control mark', 'The point where the tape begins to curve upward when extended'], 'The spacing for I-joists and engineered lumber at 5 studs over 8 feet (19.2" on center)', '19.2" OC divides 8 feet into 5 equal spaces. This is a common spacing for I-joist floor systems. The black diamonds mark every 19.2" so layout is quick. Red marks every 16" are for standard stud spacing.', 1),
    mc('To measure inside a cabinet or closet using a tape, you would add the length of the tape\'s body because:', ['The hook at the end is not accurate for inside measurements', 'The tape cannot bend at the corner and must account for the body length to read inside dimensions', 'Inside measurements require deducting rather than adding the body length', 'The hook slides to compensate, but inside corners require adding the case length'], 'The tape cannot bend at the corner and must account for the body length to read inside dimensions', 'For an inside measurement, extend the tape until the case hits the opposite wall. Read the tape at the case\'s edge, then add the case length (printed on the back, typically 3"). The sum is the inside dimension.', 2),
    mc('The term "on center" (OC) in layout work means:', ['Measuring to the center of each stud or joist from the previous center', 'Measuring from the outside edge of one framing member to the outside edge of the next', 'Placing framing members with no gaps between them', 'Centering framing members precisely in the middle of the wall or floor span'], 'Measuring to the center of each stud or joist from the previous center', '16" OC means each stud\'s center is 16" from the previous stud\'s center. This keeps standard 4×8 sheet goods aligning on stud edges. Layout begins from a corner with the first stud at 15.25" (to land sheet edges on stud centers).', 3),
    mc('When reading a tape measure, the smallest graduation between inch marks on a standard tape is:', ['1/16 inch', '1/8 inch', '1/32 inch', '1/4 inch'], '1/16 inch', 'Most tape measures show 1/16" as the smallest graduation. High-precision tapes may show 1/32". For rough framing, 1/8" is sufficient; for finish work, reading to 1/16" is important.', 4),
    mc('A board measures 5 feet 7 and 3/8 inches. Written as a decimal for a saw setting, this is:', ['5.73 feet', '5.614 feet', 'It cannot be expressed as a simple decimal', '67.375 inches'], '67.375 inches', '5×12=60 inches + 7 inches = 67 inches + 3/8 = 67.375 inches. Converting to inches first avoids the confusion of feet-inch-fraction mixed notation when setting tools or calculating.', 5),
  ],
  'hand-tools': [
    mc('A combination square is used for which of the following tasks?', ['Checking that a corner is square only', 'Marking 45° and 90° angles, checking depth, and scribing lines parallel to an edge', 'Measuring board width only', 'Setting bevel angles other than 45° and 90°'], 'Marking 45° and 90° angles, checking depth, and scribing lines parallel to an edge', 'The combination square has a sliding blade that locks at any position. With the head against the edge, it scribes a consistent line. The head has 90° and 45° faces and often a spirit level.', 1),
    mc('What is a marking gauge used for?', ['Checking that boards are parallel', 'Scribing a line parallel to an edge at a consistent distance for joinery', 'Measuring the moisture content of lumber', 'Laying out angles for miter cuts'], 'Scribing a line parallel to an edge at a consistent distance for joinery', 'A marking gauge has an adjustable fence and a pin or blade. Set the distance, run the fence along the edge, and the pin scribes a consistent line — used to mark tenon shoulders, mortise depths, and rabbet lines.', 2),
    mc('A claw hammer\'s nail puller (the V-notch on the head) is most effective when:', ['Pulling nails that are flush with the wood surface', 'Placing a scrap of wood under the head to increase leverage and protect the surface', 'Pulling ring-shank nails from concrete', 'Used only with the hammer face, not the claw end'], 'Placing a scrap of wood under the head to increase leverage and protect the surface', 'The scrap block does two things: it gives you a fulcrum closer to the nail for better mechanical advantage, and it distributes the force over a larger area, preventing the hammer head from crushing the wood surface.', 3),
    mc('Which chisel technique is correct when paring wood to a layout line?', ['Drive with a mallet, working from the layout line toward the waste', 'Work by hand pressure only when paring, keeping the flat face down and cutting from the waste toward the line', 'Always cut across the grain for cleaner results', 'Drive the chisel vertically into the grain to sever fibers'], 'Work by hand pressure only when paring, keeping the flat face down and cutting from the waste toward the line', 'Paring is controlled hand-pressure cutting for fine fitting. The flat back rides against the reference surface. Cut from waste to line — never the other way, or you risk splitting into the good side.', 4),
    mc('The "set" on a hand saw refers to:', ['The angle of the teeth relative to the blade', 'The alternating outward bend of teeth that creates a kerf wider than the blade to prevent binding', 'The tension of the blade in a frame saw', 'The number of teeth per inch, determining cut speed vs. smoothness'], 'The alternating outward bend of teeth that creates a kerf wider than the blade to prevent binding', 'Saw teeth are bent alternately left and right (set). This creates a kerf just wide enough for the blade to pass without friction. A saw with insufficient set will bind in the cut.', 5),
  ],
  'power-tools': [
    mc('The most important safety rule when using any power saw is:', ['Always cut away from your body', 'Never remove blade guards and keep your hands out of the blade path', 'Only use carbide-tipped blades', 'Clamp the workpiece with both hands before cutting'], 'Never remove blade guards and keep your hands out of the blade path', 'Guards exist for this exact reason. Keeping hands out of the cutting path prevents the most common and catastrophic power saw injuries. Let the tool complete the cut — never pull your hand back through a spinning blade.', 1),
    mc('A circular saw blade should be set to cut how deep relative to the workpiece?', ['As deep as possible for maximum stability', 'Just enough that one full tooth plus the gullet extends below the material', 'Exactly half the blade diameter for optimal speed', 'Flush with the bottom of the material'], 'Just enough that one full tooth plus the gullet extends below the material', 'Setting blade depth to expose about 1/4" to 3/8" below the material reduces the amount of blade exposed, making binding and kickback less likely, and produces a cleaner cut with less tear-out.', 2),
    mc('Kickback on a circular saw or table saw is caused by:', ['Cutting too slowly through dense material', 'The blade pinching in the kerf or contacting the off-cut, which throws the workpiece or saw back violently', 'A dull blade that requires extra pressure to advance', 'Using a blade with too many teeth for the material being cut'], 'The blade pinching in the kerf or contacting the off-cut, which throws the workpiece or saw back violently', 'Kickback happens when wood closes on the blade (from internal stress or unsupported off-cut) or the off-cut contacts the back of the blade. A riving knife/splitter and proper workpiece support prevent kickback.', 3),
    mc('What does a drill\'s clutch (the numbered ring behind the chuck) do?', ['Controls the direction of rotation', 'Limits torque output, disengaging before stripping screws or damaging materials', 'Adjusts the drill\'s speed based on material hardness', 'Locks the bit during hammer drilling operations'], 'Limits torque output, disengaging before stripping screws or damaging materials', 'The clutch slips at a preset torque, producing a ratcheting sound. Higher numbers = more torque. For driving screws into wood without stripping, set a low number. For drilling, set to the drill bit symbol (maximum torque).', 4),
    mc('When using a jigsaw to cut a curve, the best technique is:', ['Pushing the saw quickly to prevent blade wander', 'Moving the saw slowly and letting the blade do the work, following the layout line without forcing', 'Using the widest blade available for most curves', 'Starting the cut from the middle of the workpiece using a plunge cut'], 'Moving the saw slowly and letting the blade do the work, following the layout line without forcing', 'Jigsaws cut on the upstroke. Pushing too fast causes blade flex, rough cuts, and wandering. Let the blade advance at its own pace — force causes deflection, especially in thick or dense material.', 5),
  ],
  'cutting-techniques': [
    mc('When making a cross cut (across the grain) on a table saw, you should use:', ['The fence as a stop and push the workpiece with your hand', 'The miter gauge or a crosscut sled to guide the workpiece perpendicular to the blade', 'The fence only, positioned to the right of the blade', 'A circular saw instead — table saws are only for rip cuts'], 'The miter gauge or a crosscut sled to guide the workpiece perpendicular to the blade', 'Never use the fence as a length stop for crosscuts — the off-cut can bind between the fence and blade and kick back. Use the miter gauge or a sled. A stop block clamped to the fence upstream of the blade is the safe way to set a repeated length.', 1),
    mc('A rip cut follows the grain of the wood. The proper tool to guide this cut on a table saw is:', ['The miter gauge set to 0 degrees', 'The rip fence, set parallel to the blade', 'A crosscut sled with adjustable angles', 'A framing square clamped to the table'], 'The rip fence, set parallel to the blade', 'The rip fence runs parallel to the blade for ripping boards to width. Always use a push stick when the fence is within 6 inches of the blade. Never use the miter gauge for rip cuts.', 2),
    mc('What type of saw blade is best for cutting sheet goods like plywood with minimal tear-out?', ['A 24-tooth framing blade for fast cuts', 'A 40-60 tooth ATB (alternating top bevel) blade', 'A 10-tooth ripping blade', 'A dado stack set at full width'], 'A 40-60 tooth ATB (alternating top bevel) blade', 'High tooth count ATB blades make clean, splinter-free cuts in plywood and melamine. Fewer teeth = faster, rougher cuts. For face-down cuts (circular saw), the good face goes down since most tear-out occurs on the upstroke exit side.', 3),
    mc('A compound miter saw differs from a standard miter saw in that it can:', ['Cut wider boards than a standard saw', 'Tilt the blade to cut both miter and bevel angles simultaneously for crown molding and angled trim', 'Make dado cuts in addition to crosscuts', 'Rip narrow boards along their length'], 'Tilt the blade to cut both miter and bevel angles simultaneously for crown molding and angled trim', 'A standard miter saw pivots left/right (miter). A compound saw also tilts (bevel). A sliding compound miter saw adds horizontal travel for wider boards. Crown molding installation typically requires compound angles.', 4),
    mc('When hand-sawing, the correct technique to start a cut without the saw jumping is:', ['Press hard and make several fast strokes to establish the kerf immediately', 'Notch the starting point with a chisel, then begin sawing', 'Use your thumb or finger as a guide for the first few pull strokes at a low angle', 'Mark with a pencil and begin cutting on the waste side with full strokes immediately'], 'Use your thumb or finger as a guide for the first few pull strokes at a low angle', 'Guide the blade with your thumb knuckle against the side of the blade for the first few light pull strokes to establish the kerf. Once the saw is seated, lower the angle and begin full strokes. Never push on the first stroke.', 5),
  ],
  'joinery-basics': [
    mc('What is the strongest woodworking joint for connecting two pieces at a corner?', ['Butt joint with glue', 'Mortise and tenon or dovetail joint', 'Pocket screw joint', 'Biscuit joint'], 'Mortise and tenon or dovetail joint', 'Mortise-and-tenon and dovetail joints provide mechanical interlocking in addition to glue surface area. Butt joints rely entirely on fasteners or glue with minimal mechanical strength.', 1),
    mc('Wood glue joint strength depends primarily on:', ['The brand of glue used', 'Adequate clamping pressure, proper surface preparation, and mating surfaces that fit without gaps', 'Applying glue to only one surface', 'Using the maximum amount of glue possible for full coverage'], 'Adequate clamping pressure, proper surface preparation, and mating surfaces that fit without gaps', 'A gap-free, properly clamped joint with clean mating surfaces can be stronger than the wood itself. Gaps, contaminated surfaces (oil, finish), insufficient clamping, or glue that has started to set before assembly all create weak joints.', 2),
    mc('What is the purpose of using a dado cut in cabinetry?', ['To join two boards at 90 degrees at a corner', 'To create a channel in one board that another panel slides into, such as for drawer bottoms or cabinet backs', 'To rough up a surface for better glue adhesion', 'To cut boards to uniform width on a table saw'], 'To create a channel in one board that another panel slides into, such as for drawer bottoms or cabinet backs', 'A dado is a rectangular groove cut across the grain. Shelves in bookcase sides, drawer bottoms, and cabinet backs all use dadoes for a strong, recessed fit. A rabbet is a similar groove at the edge of a board.', 3),
    mc('Pocket screws joined with glue are appropriate for which applications?', ['Structural load-bearing connections in furniture', 'Face frame construction, drawer assembly, and cabinet carcasses where strength requirements are moderate', 'Outdoor furniture exposed to weather', 'Joints that will be taken apart seasonally'], 'Face frame construction, drawer assembly, and cabinet carcasses where strength requirements are moderate', 'Pocket screw joints are fast and reasonably strong for face frames and cabinet assembly. They aren\'t suited to high-stress structural applications, outdoor exposure (without exterior-rated glue/screws), or joints that need to be disassembled.', 4),
    mc('When gluing up a panel from multiple boards, why is grain direction important?', ['Grain direction affects how much glue penetrates the surface', 'Alternating or aligning growth ring orientation controls seasonal wood movement to prevent cupping', 'Grain direction determines which boards should go at the edges of the panel', 'Grain must all run the same direction for hand planing to be possible afterward'], 'Alternating or aligning growth ring orientation controls seasonal wood movement to prevent cupping', 'Wood expands and contracts across the grain with humidity changes. Alternating ring orientation in adjacent boards distributes movement and prevents the whole panel from cupping in one direction.', 5),
  ],
  'framing-basics': [
    mc('Standard stud spacing in residential wall framing is:', ['12 inches on center', '16 inches on center (or 24" OC for some applications)', '24 inches on center universally', '18 inches on center'], '16 inches on center (or 24" OC for some applications)', '16" OC is standard. It aligns with the edges of 4×8 sheet goods (16, 32, 48, 64, 80, 96"). 24" OC is used in some energy-efficient framing and where code allows for reduced loads.', 1),
    mc('A king stud, trimmer stud, and header work together in a wall to:', ['Provide backing for drywall at inside corners', 'Frame an opening for a window or door and transfer loads around it to the foundation', 'Connect the top and bottom plates at a wall intersection', 'Provide nailing for exterior sheathing at building corners'], 'Frame an opening for a window or door and transfer loads around it to the foundation', 'Headers span across openings carrying loads from above. Trimmer studs (jack studs) support the header at each end. King studs run full height beside the trimmers and transfer loads down to the bottom plate.', 2),
    mc('What is the purpose of a double top plate in wall framing?', ['To provide a nailing surface for ceiling drywall', 'To lap over intersecting walls and tie the framing together, and to distribute loads from above', 'To add height to accommodate standard door heights', 'To provide backing for attic insulation at the top of the wall'], 'To lap over intersecting walls and tie the framing together, and to distribute loads from above', 'The second top plate laps over intersecting wall top plates, tying the walls together structurally. It also helps distribute point loads from above (beams, joists) across multiple studs.', 3),
    mc('Fire blocking in wall framing is required to:', ['Strengthen the wall against wind loads', 'Interrupt concealed wall cavities at defined intervals to slow the spread of fire', 'Provide additional nailing for exterior sheathing', 'Prevent insulation from settling to the bottom of wall cavities'], 'Interrupt concealed wall cavities at defined intervals to slow the spread of fire', 'Open wall cavities act as chimneys in a fire. Fire blocking (horizontal pieces of framing in the cavity) limits the open vertical air space to 10 feet maximum, slowing fire travel within the wall assembly.', 4),
    mc('Load-bearing walls differ from partition walls in that load-bearing walls:', ['Are always exterior walls', 'Transfer structural loads (roof, floor, or upper wall loads) to the foundation', 'Must be framed with 2x6 studs instead of 2x4', 'Require permits to build but partition walls do not'], 'Transfer structural loads (roof, floor, or upper wall loads) to the foundation', 'Load-bearing walls carry gravity loads from above and must be properly supported down to the foundation. Partition walls only support themselves. Removing a load-bearing wall without properly transferring its loads causes structural failure.', 5),
  ],
}
