import type { AssessmentDef, AssessmentQuestionDef } from '../types'

const mc = (q: string, opts: string[], ans: string, exp: string, pts: number, ord: number): AssessmentQuestionDef =>
  ({ question: q, type: 'MULTIPLE_CHOICE', options: opts, correctAnswer: ans, explanation: exp, points: pts, order: ord })

const oe = (q: string, ans: string, exp: string, pts: number, ord: number): AssessmentQuestionDef =>
  ({ question: q, type: 'OPEN_ENDED', correctAnswer: ans, explanation: exp, points: pts, order: ord })

export const tradesAssessments: Record<string, AssessmentDef> = {
  'electrical-fundamentals': {
    title: 'Electrical Fundamentals Assessment',
    passingScore: 75,
    timeLimitMin: 30,
    questions: [
      mc('What is voltage?', ['The flow of electric current', 'The electrical pressure that drives current through a circuit', 'The resistance in a wire', 'The power consumed by a device'], 'The electrical pressure that drives current through a circuit', 'Voltage (measured in volts) is the difference in electrical potential that pushes electrons through a circuit — like water pressure in a pipe.', 1, 1),
      mc('What is Ohm\'s Law?', ['Power = Voltage × Current', 'Voltage = Current × Resistance (V = IR)', 'Current = Power ÷ Voltage', 'Resistance = Voltage + Current'], 'Voltage = Current × Resistance (V = IR)', 'Ohm\'s Law defines the relationship between voltage, current, and resistance. If you know any two values, you can calculate the third.', 1, 2),
      mc('What is the purpose of a circuit breaker?', ['To step up voltage', 'To protect circuits from overload by automatically shutting off current', 'To convert AC to DC', 'To measure current flow'], 'To protect circuits from overload by automatically shutting off current', 'Circuit breakers detect excessive current and trip (open the circuit) automatically — protecting wiring from overheating and preventing fires.', 1, 3),
      mc('What does it mean when wiring is described as "grounded"?', ['The wire runs underground', 'A safety path exists to carry fault current to earth, preventing shock', 'The wire is insulated', 'The circuit has no resistance'], 'A safety path exists to carry fault current to earth, preventing shock', 'Grounding provides a low-resistance path for fault current to flow safely to earth, triggering breakers and protecting people from electrocution.', 1, 4),
      mc('What is the difference between series and parallel circuits?', ['Series uses AC; parallel uses DC', 'In series, components share current; in parallel, they share voltage', 'They are interchangeable', 'Parallel circuits have only one path; series have multiple'], 'In series, components share current; in parallel, they share voltage', 'Series circuits: one path for current — if one component fails, all fail. Parallel circuits: multiple paths — failure of one doesn\'t affect others. Homes use parallel wiring.', 1, 5),
      mc('What is AWG in electrical wire sizing?', ['American Wire Gauge — larger numbers mean thinner wire', 'Amperage Wire Grounding — a safety standard', 'Approved Wire Gauge — a certification mark', 'A type of conduit'], 'American Wire Gauge — larger numbers mean thinner wire', 'AWG measures wire diameter. Counter-intuitively, higher AWG numbers mean thinner wire. 12 AWG is thicker (higher ampacity) than 14 AWG.', 1, 6),
      mc('What does GFCI stand for and where is it required?', ['General Fault Circuit Indicator — all circuits', 'Ground Fault Circuit Interrupter — required in wet areas like bathrooms and kitchens', 'Ground Fuse Circuit Interrupter — outdoor only', 'General Fault Current Indicator — basements only'], 'Ground Fault Circuit Interrupter — required in wet areas like bathrooms and kitchens', 'GFCIs detect small current imbalances indicating a fault (like current flowing through a person) and cut power in milliseconds — required by code in kitchens, bathrooms, garages, and outdoor outlets.', 1, 7),
      mc('What is the first step before working on any electrical circuit?', ['Test the outlet with a multimeter', 'Verify the circuit is de-energized using a non-contact voltage tester', 'Remove the wall plate', 'Turn off the light switch'], 'Verify the circuit is de-energized using a non-contact voltage tester', 'Always verify power is off with a non-contact voltage tester — even after turning off a breaker. Mislabeled panels can result in live circuits when you expect dead ones.', 1, 8),
      oe('Explain why you should never replace a 15-amp breaker with a 20-amp breaker just because it keeps tripping.', 'Breakers are sized to protect the wiring, not the devices. 15A breakers protect 14 AWG wire. Installing a 20A breaker allows more current than the wire can safely handle — the wire overheats and can start a fire before the breaker trips. The correct fix is to identify why the circuit is overloaded (too many devices) or upgrade the wiring to match the larger breaker.', 'A strong answer explains that breakers protect wires, not devices, and that wire ampacity is the limiting factor.', 2, 9),
      oe('A homeowner reports their kitchen outlets stopped working but the breaker isn\'t tripped. What is the most likely cause and how would you troubleshoot?', 'Most likely cause: a tripped GFCI outlet. Kitchen circuits often share a GFCI that protects multiple downstream outlets. Check for a tripped GFCI outlet anywhere on the circuit (including an outlet in the garage or bathroom that feeds the kitchen) and press the reset button. If it immediately trips again, there\'s a wiring fault or a plugged-in device causing the ground fault.', 'A strong answer identifies the GFCI as the probable culprit and explains the reset process and follow-up.', 2, 10),
    ],
  },

  'plumbing-basics': {
    title: 'Plumbing Basics Assessment',
    passingScore: 75,
    timeLimitMin: 30,
    questions: [
      mc('What is the difference between supply lines and drain lines?', ['They are the same', 'Supply lines bring fresh water in; drain lines remove wastewater out', 'Supply lines are larger', 'Drain lines are pressurized'], 'Supply lines bring fresh water in; drain lines remove wastewater out', 'Supply lines carry pressurized clean water to fixtures. Drain-waste-vent (DWV) lines carry wastewater away by gravity.', 1, 1),
      mc('What is the purpose of a P-trap?', ['To increase water pressure', 'To hold water that blocks sewer gases from entering the home', 'To filter water', 'To regulate flow rate'], 'To hold water that blocks sewer gases from entering the home', 'The P-trap is the curved pipe under sinks that stays filled with water, creating a seal that prevents sewer gases (including methane and hydrogen sulfide) from backing up into the home.', 1, 2),
      mc('What is water pressure measured in?', ['GPM (gallons per minute)', 'PSI (pounds per square inch)', 'CFM (cubic feet per minute)', 'BTU (British thermal units)'], 'PSI (pounds per square inch)', 'Residential water pressure typically runs 40–80 PSI. Too low and fixtures don\'t perform well; too high can damage pipes, fittings, and appliances.', 1, 3),
      mc('What is a shutoff valve?', ['A valve that increases water flow', 'A valve that stops water flow to a fixture or section of pipe', 'A pressure regulator', 'A drain cleanout access point'], 'A valve that stops water flow to a fixture or section of pipe', 'Shutoff valves let you cut water to a specific fixture (under sink, behind toilet) without shutting off the whole house — essential for repairs.', 1, 4),
      mc('What causes a water hammer?', ['Sediment in pipes', 'The sudden stop of fast-moving water causing pressure shock and banging noises', 'Low water pressure', 'A failing water heater'], 'The sudden stop of fast-moving water causing pressure shock and banging noises', 'Water hammer happens when a valve closes quickly and the momentum of moving water creates a pressure spike that bangs against pipe walls.', 1, 5),
      mc('What is the purpose of a vent pipe in a plumbing system?', ['To supply fresh water', 'To allow air into the drain system so water flows freely and prevents siphoning of traps', 'To vent hot water heater exhaust', 'To provide a cleanout for blockages'], 'To allow air into the drain system so water flows freely and prevents siphoning of traps', 'Vent pipes (running up through the roof) prevent negative pressure in drain lines. Without venting, drains gurgle and traps siphon dry — letting sewer gas in.', 1, 6),
      mc('What does "pipe pitch" or "slope" mean in drain plumbing?', ['The diameter of the pipe', 'The downward angle of drain pipes that allows gravity to move water', 'The pipe material type', 'The pressure rating of the pipe'], 'The downward angle of drain pipes that allows gravity to move water', 'Drain lines must slope toward the sewer/septic — typically 1/4 inch per foot. Too little and solids settle; too much and water outruns solids, causing clogs.', 1, 7),
      mc('What is PEX pipe?', ['A type of copper fitting', 'A flexible plastic tubing widely used for supply lines due to freeze resistance and ease of installation', 'A drain pipe material', 'A type of pipe joint'], 'A flexible plastic tubing widely used for supply lines due to freeze resistance and ease of installation', 'PEX (cross-linked polyethylene) is flexible, resistant to freezing, easy to install without soldering, and cheaper than copper — now the most common residential supply pipe.', 1, 8),
      oe('A toilet keeps running after flushing. What are the most likely causes and how would you diagnose them?', 'Most likely causes: (1) Flapper not sealing — add food coloring to tank; if it appears in bowl without flushing, the flapper is leaking. Replace it. (2) Float set too high — water fills past the overflow tube. Adjust float arm or float ball so water stops below the overflow tube. (3) Fill valve worn — if adjusting the float doesn\'t help, replace the fill valve assembly. All parts are inexpensive and available at hardware stores.', 'A strong answer names at least two causes and describes a diagnostic step for each.', 2, 9),
      oe('Why is it important to know where your main water shutoff is, and when would you need it?', 'The main shutoff cuts water to the entire house — essential for burst pipes, major leaks, or plumbing emergencies where you can\'t reach a fixture shutoff. Every homeowner and tenant should know its location (typically near the water meter, in a basement, or crawl space) and verify it works before an emergency. A slow-acting or stuck shutoff during a flood causes massive damage.', 'A strong answer explains what the shutoff does, when you need it, and emphasizes knowing its location proactively.', 2, 10),
    ],
  },

  'hvac-fundamentals': {
    title: 'HVAC Fundamentals Assessment',
    passingScore: 75,
    timeLimitMin: 30,
    questions: [
      mc('What does HVAC stand for?', ['High Voltage Air Cooling', 'Heating, Ventilation, and Air Conditioning', 'Home Ventilation and Cooling', 'Heating, Vapor, Air, and Condensation'], 'Heating, Ventilation, and Air Conditioning', 'HVAC systems handle the full range of indoor climate control: heating in winter, cooling in summer, and ventilation to maintain air quality.', 1, 1),
      mc('How does a refrigeration cycle cool air?', ['By generating cold air directly', 'By absorbing heat from indoor air using a refrigerant that evaporates and compresses', 'By blowing air over ice', 'By filtering warm particles from the air'], 'By absorbing heat from indoor air using a refrigerant that evaporates and compresses', 'Air conditioners don\'t create cold — they move heat. Refrigerant absorbs heat as it evaporates indoors, then releases that heat outside as it condenses.', 1, 2),
      mc('What is a MERV rating?', ['A measure of furnace efficiency', 'Minimum Efficiency Reporting Value — a standard for air filter effectiveness', 'A certification for HVAC technicians', 'A refrigerant pressure rating'], 'Minimum Efficiency Reporting Value — a standard for air filter effectiveness', 'MERV ratings (1–16 for residential) measure how well a filter captures particles. Higher MERV = finer filtration, but also more airflow resistance.', 1, 3),
      mc('What is a heat pump?', ['A furnace that runs on electricity', 'A system that moves heat between indoors and outdoors, providing both heating and cooling', 'A water heater', 'An air purifier with heating capability'], 'A system that moves heat between indoors and outdoors, providing both heating and cooling', 'Heat pumps are highly efficient — they move existing heat rather than generating it. In winter, they extract heat from outdoor air; in summer, they run in reverse like an AC.', 1, 4),
      mc('What is the purpose of the evaporator coil in an AC system?', ['To cool refrigerant before it enters the compressor', 'To absorb heat from indoor air as refrigerant evaporates inside it', 'To dissipate heat outside', 'To filter indoor air'], 'To absorb heat from indoor air as refrigerant evaporates inside it', 'The evaporator coil sits in the air handler inside your home. As refrigerant evaporates at low pressure inside the coil, it absorbs heat from passing air — cooling your home.', 1, 5),
      mc('What does SEER measure?', ['The filter efficiency rating', 'The Seasonal Energy Efficiency Ratio — how efficiently an AC uses energy over a season', 'The airflow in cubic feet per minute', 'The noise level of a unit'], 'The Seasonal Energy Efficiency Ratio — how efficiently an AC uses energy over a season', 'Higher SEER ratings mean more cooling output per unit of energy consumed — lower operating costs. Modern standards require at least 14 SEER.', 1, 6),
      mc('Why is regular air filter replacement important?', ['It reduces refrigerant pressure', 'Dirty filters restrict airflow, reducing efficiency, straining components, and degrading air quality', 'Filters only need replacement when HVAC is serviced', 'It has no effect on system performance'], 'Dirty filters restrict airflow, reducing efficiency, straining components, and degrading air quality', 'A clogged filter makes the system work harder, reduces airflow to rooms, can cause the evaporator coil to freeze, shortens equipment life, and worsens indoor air quality.', 1, 7),
      mc('What is refrigerant?', ['The oil that lubricates HVAC compressors', 'A chemical compound that absorbs and releases heat as it changes between liquid and gas states', 'The coolant in radiant floor systems', 'A type of insulation in ductwork'], 'A chemical compound that absorbs and releases heat as it changes between liquid and gas states', 'Refrigerant is the working fluid of the refrigeration cycle. Common types include R-22 (being phased out) and R-410A. Only licensed technicians can handle refrigerant legally.', 1, 8),
      oe('A homeowner says their AC is running constantly but the house won\'t cool down. What are the possible causes?', 'Possible causes: dirty/clogged air filter restricting airflow; dirty evaporator or condenser coils; low refrigerant (leak); undersized system for the load; ductwork leaks losing conditioned air; home not well insulated/sealed; extreme outdoor heat. Diagnosis: check and replace filter first, inspect coils, check refrigerant charge (requires a tech), inspect duct insulation and sealing.', 'A strong answer lists at least three causes and notes which require a professional vs. DIY.', 2, 9),
      oe('What routine maintenance should a homeowner perform on their HVAC system to extend its life?', 'Change air filters every 1–3 months (check monthly). Keep outdoor condenser unit clear of debris and vegetation. Clean return air vents. Schedule annual professional tune-ups (inspect refrigerant, coils, electrical connections, belts, drain pan). Flush condensate drain line. Replace thermostat batteries. These steps catch problems early, maintain efficiency, and prevent costly breakdowns.', 'A complete answer covers DIY tasks AND the importance of professional annual service — not just one or the other.', 2, 10),
    ],
  },

  'carpentry-and-woodworking': {
    title: 'Carpentry and Woodworking Assessment',
    passingScore: 75,
    timeLimitMin: 30,
    questions: [
      mc('What is the difference between hardwood and softwood?', ['Hardwood is harder; softwood is softer (always)', 'Hardwood comes from deciduous trees; softwood comes from conifers', 'Softwood is used for furniture; hardwood for framing', 'They differ only in price'], 'Hardwood comes from deciduous trees; softwood comes from conifers', 'The classification is botanical, not physical — hardwoods (oak, maple, cherry) come from broadleaf trees; softwoods (pine, fir, cedar) from needle-bearing trees. Some "softwoods" are physically harder than some "hardwoods."', 1, 1),
      mc('What does "grain" mean in woodworking?', ['The color pattern of wood', 'The direction and pattern of wood fibers', 'The wood\'s moisture content', 'The number of growth rings'], 'The direction and pattern of wood fibers', 'Grain refers to the alignment of wood fibers. Cutting with the grain is easier; cross-grain cuts require more care. Grain direction affects how wood splits, planes, and finishes.', 1, 2),
      mc('What is a rabbet joint?', ['A type of wood glue', 'A stepped recess cut along the edge of a board to accept another piece', 'A joint using wooden dowels', 'A type of wood finish'], 'A stepped recess cut along the edge of a board to accept another piece', 'A rabbet is an L-shaped channel cut into the edge or end of a board, typically used for cabinet backs, drawer bottoms, and panel joints.', 1, 3),
      mc('What does "plumb" mean in carpentry?', ['Level (perfectly horizontal)', 'Perfectly vertical', 'Square (90-degree angle)', 'Smoothly finished'], 'Perfectly vertical', 'Plumb means straight up and down — true vertical. A plumb line hangs freely and indicates true vertical by gravity.', 1, 4),
      mc('What is the purpose of wood glue in joinery?', ['To fill gaps between boards', 'To create a chemical bond that strengthens wood joints', 'To lubricate saw blades', 'To seal wood against moisture'], 'To create a chemical bond that strengthens wood joints', 'Properly applied wood glue creates a joint stronger than the surrounding wood. It bonds wood fibers chemically when the joint is clamped during curing.', 1, 5),
      mc('What is the correct way to measure and cut for accuracy?', ['Measure once, cut once', 'Measure twice, cut once', 'Cut then measure to fit', 'Use a template every time'], 'Measure twice, cut once', 'The classic carpentry rule: verify your measurement before cutting. Wood can\'t be uncut — a moment of verification prevents wasted material and time.', 1, 6),
      mc('What is moisture content and why does it matter?', ['How wet the finish is when applied', 'The percentage of water in wood — affects stability, workability, and final dimensions', 'The humidity of the shop environment', 'The water resistance of finished wood'], 'The percentage of water in wood — affects stability, workability, and final dimensions', 'Wood expands when it absorbs moisture and shrinks when it dries. Using wood with improper moisture content for the environment leads to warping, cracking, and joint failure.', 1, 7),
      mc('What is a pilot hole?', ['A test hole to check depth', 'A small hole drilled before a screw or bolt to prevent wood splitting', 'The first hole in a series', 'A hole for electrical conduit'], 'A small hole drilled before a screw or bolt to prevent wood splitting', 'Pilot holes are slightly smaller than the fastener diameter — they prevent wood from splitting when driving screws near edges or in hardwoods.', 1, 8),
      oe('Explain why wood movement matters in furniture building and how you account for it.', 'Wood expands and contracts across the grain with seasonal humidity changes. A glued solid wood panel that\'s restricted from moving will crack or warp. Accommodations: allow expansion gaps around panels, use elongated screw slots in tabletops so wood can slide, avoid gluing cross-grain joints that restrict movement. Understanding movement direction (mostly across the grain, not along it) is essential for durable work.', 'A strong answer explains that movement is cross-grain, why it causes failure if restricted, and names at least one design technique.', 2, 9),
      oe('What safety rules should you always follow when using a table saw?', 'Key rules: use the blade guard and riving knife unless impossible for the cut. Never reach over or behind a spinning blade. Keep hands at least 6 inches from the blade — use push sticks for narrow rips. Stand to the side, not directly behind the blade (kickback zone). Keep the fence parallel to the blade. Don\'t use dull blades. Wear eye protection. Never start a cut with the stock touching the blade.', 'A strong answer names multiple specific rules — not just "be careful."', 2, 10),
    ],
  },

  'automotive-basics': {
    title: 'Automotive Basics Assessment',
    passingScore: 75,
    timeLimitMin: 30,
    questions: [
      mc('What does engine oil do?', ['Cool the engine only', 'Lubricate moving parts, reduce friction, clean, and help cool internal components', 'Fuel the engine', 'Pressurize the fuel system'], 'Lubricate moving parts, reduce friction, clean, and help cool internal components', 'Engine oil forms a film between metal parts to prevent friction and wear. It also carries heat, cleans contaminants, and protects against corrosion.', 1, 1),
      mc('What does the check engine light indicate?', ['Your oil needs changing', 'The engine is overheating', 'The vehicle\'s OBD system has detected a fault and stored a diagnostic trouble code', 'Time for a tune-up'], 'The vehicle\'s OBD system has detected a fault and stored a diagnostic trouble code', 'The check engine light (CEL) means the onboard diagnostics system detected something out of spec. A scan tool reads the trouble code — it can be minor (loose gas cap) or serious (misfires, catalytic converter failure).', 1, 2),
      mc('What is brake fade?', ['Brakes wearing out over time', 'Temporary loss of braking effectiveness due to heat buildup', 'A brake fluid leak', 'When brakes apply unevenly'], 'Temporary loss of braking effectiveness due to heat buildup', 'Brake fade occurs during sustained heavy braking (like descending a mountain) when heat builds up and reduces friction efficiency — a serious safety concern.', 1, 3),
      mc('What does a serpentine belt drive?', ['The transmission', 'Multiple accessories including the alternator, power steering pump, and AC compressor', 'The camshaft', 'Only the alternator'], 'Multiple accessories including the alternator, power steering pump, and AC compressor', 'The serpentine belt is a single continuous belt that drives multiple engine accessories. When it fails, all those systems fail simultaneously.', 1, 4),
      mc('What is the purpose of coolant (antifreeze)?', ['Lubricate the engine', 'Regulate engine temperature and prevent freezing or boiling in extreme conditions', 'Clean the fuel system', 'Improve fuel economy'], 'Regulate engine temperature and prevent freezing or boiling in extreme conditions', 'Coolant transfers heat from the engine to the radiator. It also raises the boiling point and lowers the freezing point of the cooling system fluid.', 1, 5),
      mc('What does tire tread depth affect?', ['Only fuel economy', 'Wet-weather traction and stopping distance', 'Tire pressure only', 'Ride comfort only'], 'Wet-weather traction and stopping distance', 'Tire tread channels water away from the contact patch. Worn tread reduces grip especially on wet roads and dramatically increases stopping distance.', 1, 6),
      mc('What is an OBD-II scanner?', ['An oil drain tool', 'A tool that reads diagnostic trouble codes from a vehicle\'s computer', 'A fuel pressure gauge', 'A battery tester'], 'A tool that reads diagnostic trouble codes from a vehicle\'s computer', 'OBD-II (On-Board Diagnostics) is the standard port (under the dash) where scan tools connect to read fault codes, live sensor data, and clear check engine lights.', 1, 7),
      mc('What causes a battery to fail prematurely?', ['Driving too fast', 'Deep discharge cycles, heat, age, and a failing charging system', 'Using the wrong oil', 'Low tire pressure'], 'Deep discharge cycles, heat, age, and a failing charging system', 'Car batteries degrade from repeated deep discharge (leaving lights on), heat exposure, sulfation from undercharging, and natural aging. A failing alternator also destroys batteries by undercharging.', 1, 8),
      oe('What checks should you perform when buying a used car, before taking it to a mechanic?', 'Visual inspection: look for rust under the car and in wheel wells, uneven panel gaps (signs of collision repair), mismatched paint. Check tires for uneven wear (suspension issues). Start it cold: listen for knocking or smoking on startup. Check all fluids (oil color, coolant, brake fluid). Test all lights, windows, locks, and HVAC. Take it on a test drive — listen for clunks, brake pulsation, steering pull. Then get a pre-purchase inspection from a trusted mechanic.', 'A strong answer covers visual, fluid, operational, and drive checks — and recommends a professional inspection.', 2, 9),
      oe('Explain why tire rotation and alignment matter for vehicle safety and longevity.', 'Rotation: front and rear tires wear at different rates (front tires steer and often bear more braking load). Rotating them evenly distributes wear, extending tire life and maintaining balanced handling. Alignment: wheels that aren\'t aligned cause uneven tire wear, steering pull, and reduced fuel economy. Misalignment from hitting potholes or curbs can compromise handling at highway speeds. Both are low-cost preventive measures that avoid expensive tire replacement and improve safety.', 'A strong answer gives the "why" behind each — different wear rates for rotation, safety and wear effects for alignment.', 2, 10),
    ],
  },

  'welding-fundamentals': {
    title: 'Welding Fundamentals Assessment',
    passingScore: 75,
    timeLimitMin: 30,
    questions: [
      mc('What is the basic principle of welding?', ['Bonding metals with adhesive', 'Joining metals by melting them together, with or without filler material', 'Bending metal into shape', 'Cutting metal with heat'], 'Joining metals by melting them together, with or without filler material', 'Welding melts the base metals at the joint and often adds filler metal — when the weld pool solidifies, it creates a metallurgical bond stronger than mechanical fasteners.', 1, 1),
      mc('What does MIG stand for in MIG welding?', ['Metal Inert Gas', 'Metal Integrated Grinder', 'Multiple Input Gun', 'Molten Inert Gas'], 'Metal Inert Gas', 'MIG (Metal Inert Gas) welding uses a continuously fed wire electrode and shielding gas. It\'s the most beginner-friendly process — often called "hot glue gun for metal."', 1, 2),
      mc('What is the purpose of shielding gas in MIG welding?', ['To cool the weld quickly', 'To protect the weld pool from atmospheric contamination', 'To increase welding speed', 'To reduce the heat input'], 'To protect the weld pool from atmospheric contamination', 'Oxygen and nitrogen in the atmosphere cause porosity and brittleness in welds. Shielding gas (argon, CO2, or mix) displaces air around the arc to protect the molten pool.', 1, 3),
      mc('What is the difference between a fillet weld and a butt weld?', ['Fillet welds are stronger', 'A butt weld joins two pieces end-to-end on the same plane; a fillet weld joins two pieces at an angle (usually 90°)', 'Butt welds are cosmetic; fillet welds are structural', 'They use different equipment'], 'A butt weld joins two pieces end-to-end on the same plane; a fillet weld joins two pieces at an angle (usually 90°)', 'Butt welds join plate edges face-to-face. Fillet welds (the most common type) join pieces in T, lap, or corner joints where the surfaces meet at an angle.', 1, 4),
      mc('What is porosity in a weld?', ['A design feature for lighter welds', 'Gas pockets trapped in the solidified weld — a defect that weakens the joint', 'A textured surface finish', 'Controlled penetration depth'], 'Gas pockets trapped in the solidified weld — a defect that weakens the joint', 'Porosity forms when gas (from contamination, moisture, or improper shielding) gets trapped as the weld solidifies. It creates voids that reduce strength and may cause cracking.', 1, 5),
      mc('What PPE is required for welding?', ['Safety glasses and gloves', 'Auto-darkening welding helmet, fire-resistant clothing, leather gloves, and steel-toed boots', 'Only a welding helmet', 'Hard hat and safety glasses'], 'Auto-darkening welding helmet, fire-resistant clothing, leather gloves, and steel-toed boots', 'Welding produces UV/IR radiation (arc eye), spatter, fumes, and extreme heat. Full PPE is non-negotiable — arc eye can cause permanent vision damage.', 1, 6),
      mc('What causes warping in welded metal?', ['Using too much filler wire', 'Uneven heating and cooling causing differential thermal expansion and contraction', 'Welding too slowly', 'Using the wrong shielding gas'], 'Uneven heating and cooling causing differential thermal expansion and contraction', 'Metal expands when heated and contracts when cooling. Uneven heating from welding causes differential contraction that bends and distorts the workpiece — a key challenge in structural welding.', 1, 7),
      mc('What is a good weld bead supposed to look like?', ['Flat and shiny', 'Consistent width and height, with a smooth rippled pattern and good fusion at the edges', 'Raised and irregular for maximum material', 'Any appearance is acceptable if it holds'], 'Consistent width and height, with a smooth rippled pattern and good fusion at the edges', 'A quality weld bead has consistent width (steady travel speed), uniform ripples (consistent arc length), and fuses into the base metal at both toes without undercut or overlap.', 1, 8),
      oe('Explain the safety hazards of welding and how to mitigate each one.', 'Key hazards: (1) UV/IR radiation — wear proper auto-darkening helmet, never look at arc unprotected. (2) Fumes — weld in ventilated area or use fume extraction; especially critical with galvanized or coated metals. (3) Fire/explosion — clear flammables, use fire-resistant blankets, have extinguisher ready. (4) Electrical shock — inspect equipment, don\'t weld in wet conditions. (5) Spatter — fire-resistant clothing and leather gloves.', 'A strong answer lists multiple specific hazards with specific mitigations — not just "be careful."', 2, 9),
      oe('Why is metal preparation (cleaning and fit-up) so critical before welding?', 'Contaminants like rust, mill scale, paint, oil, and moisture cause porosity, inclusion defects, and poor fusion — weakening the weld. Poor fit-up (gaps, misalignment) makes it impossible to fill evenly and creates stress concentration points. The strongest welds start with clean, properly fit metal. Grinding and prepping takes time but determines weld quality — no amount of skill compensates for bad preparation.', 'A strong answer names specific contaminants, explains what defects they cause, and connects fit-up to structural integrity.', 2, 10),
    ],
  },

  'masonry-and-concrete': {
    title: 'Masonry and Concrete Assessment',
    passingScore: 75,
    timeLimitMin: 30,
    questions: [
      mc('What are the components of concrete?', ['Sand, gravel, and water', 'Portland cement, sand, aggregate (gravel), and water', 'Concrete is a single mined material', 'Lime, water, and sand only'], 'Portland cement, sand, aggregate (gravel), and water', 'Concrete is a composite: Portland cement binds everything, sand fills small voids, aggregate (stone) provides bulk strength, and water triggers the chemical curing reaction.', 1, 1),
      mc('What is the water-cement ratio and why does it matter?', ['How much water to use for mixing only', 'The ratio of water to cement by weight — lower ratios produce stronger, less permeable concrete', 'A ratio for mixing mortar only', 'How long to wet-cure the concrete'], 'The ratio of water to cement by weight — lower ratios produce stronger, less permeable concrete', 'Too much water weakens concrete by creating excessive porosity when water evaporates. The w/c ratio directly determines strength and durability — it\'s the most critical variable in mix design.', 1, 2),
      mc('What is rebar used for in concrete?', ['Decoration', 'Reinforcement — steel in tension compensates for concrete\'s weakness in tension', 'To speed up curing', 'To reduce the amount of aggregate needed'], 'Reinforcement — steel in tension compensates for concrete\'s weakness in tension', 'Concrete is strong in compression but weak in tension. Steel rebar carries tensile forces, allowing reinforced concrete to resist bending and cracking under load.', 1, 3),
      mc('What is curing in concrete work?', ['Allowing concrete to dry out as fast as possible', 'Maintaining moisture and temperature so the cement hydration reaction can complete properly', 'Mixing the concrete batch', 'Removing formwork after pouring'], 'Maintaining moisture and temperature so the cement hydration reaction can complete properly', 'Curing isn\'t drying — it\'s the opposite. Keeping concrete moist for at least 7 days allows the cement to hydrate fully and reach maximum strength. Premature drying causes weakness and cracking.', 1, 4),
      mc('What is the difference between mortar and concrete?', ['They are the same material', 'Concrete has coarse aggregate (gravel); mortar does not — mortar is used to bond masonry units', 'Mortar is stronger', 'Concrete is used outdoors; mortar indoors'], 'Concrete has coarse aggregate (gravel); mortar does not — mortar is used to bond masonry units', 'Mortar is a paste of cement, sand, and water used to bond bricks, blocks, and stone. Concrete adds coarse aggregate for structural applications.', 1, 5),
      mc('What causes concrete to crack?', ['Using too much cement', 'Shrinkage during curing, thermal expansion/contraction, overloading, and inadequate control joints', 'Not enough aggregate', 'Adding rebar incorrectly'], 'Shrinkage during curing, thermal expansion/contraction, overloading, and inadequate control joints', 'All concrete eventually cracks — the goal is controlling where and how. Shrinkage cracks from moisture loss, thermal cracks from temperature cycles, structural cracks from overloading.', 1, 6),
      mc('What are control joints?', ['Joints between rebar sections', 'Planned weak points cut or formed in concrete to direct where cracks occur', 'Expansion material between slabs', 'Steel connectors between concrete panels'], 'Planned weak points cut or formed in concrete to direct where cracks occur', 'Control joints are saw-cut or tooled grooves that create weak planes — concrete cracks along these joints instead of randomly, keeping the slab looking neat and functioning properly.', 1, 7),
      mc('What is the standard compressive strength of residential concrete, measured in PSI?', ['1,000 PSI', '4,000 PSI', '10,000 PSI', '500 PSI'], '4,000 PSI', 'Residential concrete (slabs, footings, driveways) typically specifies 3,000–4,000 PSI compressive strength at 28 days. High-performance applications can exceed 10,000 PSI.', 1, 8),
      oe('Why must concrete be placed and finished quickly after mixing, and what happens if it sits too long?', 'Cement begins hydrating immediately after water contact — the mix stiffens progressively. Once past the initial set, the concrete can\'t be reworked without destroying its structure. Adding water to re-temper a stiff mix weakens it by raising the w/c ratio. In hot weather, set time accelerates further. Crews must plan placements, staging, and finishing sequence so the entire pour is workable from start to finish.', 'A strong answer explains the hydration timeline and why adding water to a stiffening mix is harmful.', 2, 9),
      oe('What steps should you take to prevent frost damage to freshly poured concrete in cold weather?', 'Fresh concrete must stay above 50°F (ideally 55°F+) for at least 7 days to cure properly. Cold weather steps: use warm mixing water, use accelerating admixtures, avoid placing on frozen ground (thaw first or insulate forms), use heated enclosures or insulating blankets over the pour, monitor temperature. Water expands when it freezes — if fresh concrete freezes before it gains strength, the ice crystals destroy the internal structure permanently.', 'A strong answer explains the mechanism of frost damage and gives at least three protective measures.', 2, 10),
    ],
  },
}
