import type { ExerciseDef } from '../types'

function mc(question: string, options: string[], correctAnswer: string, explanation: string, order: number): ExerciseDef {
  return { question, type: 'MULTIPLE_CHOICE', options, correctAnswer, explanation, order }
}

export const tradesExercises8: Record<string, ExerciseDef[]> = {
  'reading-a-weld': [
    mc('Porosity in a weld bead appears as and is caused by:', ['Surface cracking caused by rapid cooling', 'Small holes or pits caused by gas trapped in the solidifying weld metal', 'A rough, uneven surface caused by insufficient amperage', 'Lack of fusion between weld passes caused by contamination'], 'Small holes or pits caused by gas trapped in the solidifying weld metal', 'Porosity indicates contamination (oil, rust, moisture, inadequate shielding) that generated gas during welding. Gas was trapped as the metal solidified. In structural applications, porosity weakens the weld and is a rejectable defect.', 1),
    mc('Undercut in a weld is:', ['Insufficient weld metal that leaves a groove or depression at the toe of the weld along the base metal', 'Weld metal that extends beyond the toe into the base metal', 'An incomplete fusion between two weld passes', 'Excessive concavity in a fillet weld face'], 'Insufficient weld metal that leaves a groove or depression at the toe of the weld along the base metal', 'Undercut is a groove melted into the base metal at the weld toe that is not filled with weld metal. It reduces the effective cross-section of the base metal and creates a stress concentration that can initiate fatigue cracks.', 2),
    mc('A properly sized fillet weld should have a face that is:', ['Highly convex (crowned) for maximum throat size and strength', 'Flat to slightly concave — a convex face reduces effective throat and creates stress concentration', 'Deeply concave to maximize the weld\'s flexibility', 'Any profile — fillet weld geometry doesn\'t affect strength if the legs are sized correctly'], 'Flat to slightly concave — a convex face reduces effective throat and creates stress concentration', 'Effective throat (the relevant dimension for fillet weld strength) is shortest in a convex bead. A flat or slightly concave face maximizes the throat-to-leg ratio. Excessive convexity is a stress concentrator and wastes weld metal.', 3),
    mc('Incomplete fusion in a weld means:', ['The weld bead did not reach full width in the joint', 'The weld metal did not properly bond to the base metal or previous weld pass', 'The joint was not cleaned before welding, resulting in porosity', 'The welder stopped the bead before reaching the end of the joint'], 'The weld metal did not properly bond to the base metal or previous weld pass', 'Incomplete fusion (lack of fusion) occurs when the base metal or previous pass did not reach melting temperature — the new weld metal sits on top without truly bonding. It creates a plane of weakness invisible from the surface.', 4),
    mc('What does a weld that is too narrow and highly crowned (convex) indicate about the welding parameters?', ['Voltage too high and amperage too low', 'Travel speed too fast and/or amperage too low relative to the joint requirements', 'Shielding gas flow too high, cooling the puddle prematurely', 'Electrode angle too steep, forcing the puddle backward'], 'Travel speed too fast and/or amperage too low relative to the joint requirements', 'A narrow, convex (high crown) bead indicates insufficient heat input — either too little amperage or too fast travel speed. The puddle chilled before it could flatten and wet out properly. Slow down and/or increase amperage.', 5),
  ],
  'metals-and-prep': [
    mc('The most important step before welding any metal is:', ['Pre-heating the base metal to at least 300°F', 'Cleaning the weld zone to bare, shiny metal — removing rust, paint, oil, and mill scale', 'Tacking the joint at 12-inch intervals to control distortion', 'Selecting the correct filler metal grade for the base material'], 'Cleaning the weld zone to bare, shiny metal — removing rust, paint, oil, and mill scale', 'Contamination causes the most common weld defects: porosity, lack of fusion, and cracking. Paint releases toxic fumes and creates porosity. Mill scale prevents proper fusion on steel. Grind, wire-brush, and degrease all surfaces before welding.', 1),
    mc('Mild steel (A36/A572) and stainless steel can both be welded, but they require different filler metals primarily because:', ['They have different melting points that require different heat inputs', 'Mixing carbon and chromium-nickel alloys creates a weld with poor corrosion resistance and potential cracking', 'Stainless requires a flux-core process; mild steel requires solid wire', 'The arc characteristics are incompatible between the two base metals'], 'Mixing carbon and chromium-nickel alloys creates a weld with poor corrosion resistance and potential cracking', 'Using mild steel filler on stainless dilutes the chromium and nickel content, destroying corrosion resistance in the weld zone. Using stainless filler on mild steel wastes money and may cause cracking. Use appropriate matched filler.', 2),
    mc('When welding cast iron, the most common challenge is:', ['Cast iron melts at too high a temperature for standard welding equipment', 'Its high carbon content makes it prone to cracking from thermal shock — requiring pre-heat, controlled interpass temperature, and slow cooling', 'Cast iron cannot be welded and must always be brazed or bolted', 'Cast iron absorbs shielding gas and requires flux-coated electrodes exclusively'], 'Its high carbon content makes it prone to cracking from thermal shock — requiring pre-heat, controlled interpass temperature, and slow cooling', 'Cast iron is brittle and cracks easily when heated and cooled rapidly. Pre-heating to 500-1200°F, maintaining interpass temperature, using nickel or high-nickel electrodes, and slow cooling (in an insulated blanket or sand) prevent cracking.', 3),
    mc('Aluminum requires more amperage than steel of the same thickness because:', ['Aluminum has lower electrical resistance, so more current is needed to maintain the arc', 'Aluminum conducts heat extremely well, drawing heat away from the weld zone rapidly', 'Aluminum requires a longer arc length, which demands more amperage to maintain', 'Aluminum\'s oxide layer requires more heat energy to break down before welding can begin'], 'Aluminum conducts heat extremely well, drawing heat away from the weld zone rapidly', 'Aluminum\'s thermal conductivity is about 6x higher than steel. Heat spreads out rapidly, making it harder to achieve fusion at the joint. Higher amperage compensates for heat loss. For thick sections, pre-heating (250-400°F) further helps.', 4),
    mc('Joint fit-up (how closely mating surfaces align before welding) affects weld quality because:', ['Poor fit-up makes it impossible to maintain consistent arc length', 'Gaps require additional filler passes that dilute the base metal composition', 'Tight, consistent fit-up minimizes the volume of weld metal needed, reducing distortion and ensuring complete fusion', 'Joint fit-up only matters for aesthetic appearance, not structural integrity'], 'Tight, consistent fit-up minimizes the volume of weld metal needed, reducing distortion and ensuring complete fusion', 'Gaps require more weld metal (more passes, more heat, more distortion) and risk incomplete fusion at the root. Tight fit-up allows a predictable root pass with full fusion. Consistent fit-up also allows consistent travel speed and parameters.', 5),
  ],
  'welding-safety': [
    mc('What is the correct way to move a compressed gas cylinder (argon, CO2, oxygen)?', ['Carry it horizontally on your shoulder to avoid dropping it', 'Roll it on its bottom edge — never drag, drop, or let it fall', 'Use the valve protection cap as a handle to guide it', 'Only move cylinders with the regulator attached so it is ready to use'], 'Roll it on its bottom edge — never drag, drop, or let it fall', 'A dropped cylinder can shear the valve, turning it into a missile. Always keep the protective cap on when not in use, chain cylinders to a wall or cart, and use a hand truck. Never lift by the valve or drag horizontally.', 1),
    mc('Cutting stainless steel generates hexavalent chromium (Cr-VI) fumes, which are hazardous because:', ['They cause an immediate burning sensation that acts as a warning to leave the area', 'Cr-VI is a confirmed human carcinogen that causes lung cancer with long-term inhalation exposure', 'Cr-VI reacts with moisture in the respiratory tract to form corrosive chromic acid', 'They reduce oxygen levels in the welding zone, creating an asphyxiation risk'], 'Cr-VI is a confirmed human carcinogen that causes lung cancer with long-term inhalation exposure', 'OSHA has a very low permissible exposure limit for Cr-VI. Welding stainless requires local exhaust ventilation, and in many cases a supplied-air respirator. Grinding stainless also generates Cr-VI dust that must be controlled.', 2),
    mc('The minimum safe distance between a welding area and combustible materials is:', ['3 feet in all directions', '10 feet in all directions, or combustibles must be covered with fire-resistant blankets', '25 feet for gas welding; 10 feet for electric arc processes', '50 feet or the combustibles must be relocated completely'], '10 feet in all directions, or combustibles must be covered with fire-resistant blankets', 'OSHA/NFPA guidelines require 35 feet of clearance from combustibles, or use of fire-resistant blankets. Common practice accepts 10 feet with appropriate fire watch and blankets. Spatter can travel farther than most people expect.', 3),
    mc('Ear protection is required for welding and grinding because:', ['The arc noise can permanently damage hearing over a career', 'Grinding noise exceeds 85 dB — the OSHA threshold for required hearing protection', 'Both arc flash and grinding create low-frequency vibrations that damage the inner ear', 'Both welding and grinding produce ultrasonic frequencies that bypass normal hearing but damage the cochlea'], 'Grinding noise exceeds 85 dB — the OSHA threshold for required hearing protection', 'Angle grinders typically produce 95-100 dB at operator distance. OSHA requires hearing protection above 85 dB with 8-hour exposure. Even short exposure to 100 dB causes cumulative hearing loss without protection.', 4),
    mc('What type of respirator provides adequate protection from welding fumes in a well-ventilated shop?', ['A dust mask (N95 filtering facepiece)', 'A half-face respirator with P100 particulate + OV/AG combination cartridges', 'No respirator is needed in a ventilated shop — fume levels stay below OSHA limits', 'A full-face respirator with supplied air is always required for any welding fumes'], 'A half-face respirator with P100 particulate + OV/AG combination cartridges', 'P100 filters capture 99.97% of particles including metal fumes. OV/AG (organic vapor/acid gas) cartridges handle gaseous contaminants. In a well-ventilated shop this typically provides adequate protection. Stainless, galvanized, or confined space welding requires additional protection.', 5),
  ],
  'forming-and-pouring': [
    mc('Concrete forms must be designed to withstand what primary force during the pour?', ['The weight of workers walking on the concrete', 'The lateral pressure (hydrostatic pressure) of wet concrete acting like a fluid against form walls', 'The downward weight of concrete from above in multi-story pours', 'The thermal expansion of concrete as it heats during hydration'], 'The lateral pressure (hydrostatic pressure) of wet concrete acting like a fluid against form walls', 'Wet concrete behaves like a dense liquid. Forms must resist the outward hydrostatic pressure, which increases with pour depth and pour rate. Fast pours on deep forms can exceed the pressure of water at the same depth.', 1),
    mc('Form release agent (form oil) is applied to concrete forms before pouring to:', ['Prevent moisture absorption from the concrete into the form material', 'Prevent the concrete from bonding to the form so it can be stripped cleanly', 'Seal the form against leaks at joints and seams', 'Prevent the concrete surface from drying too fast against the form face'], 'Prevent the concrete from bonding to the form so it can be stripped cleanly', 'Without release agent, concrete chemically bonds to plywood and many other form materials. Stripping becomes difficult or impossible, damaging both the forms and the concrete surface. Apply a thin, even coat before every pour.', 2),
    mc('Consolidation of freshly placed concrete (vibrating it) is done to:', ['Speed up the curing process by generating heat', 'Eliminate air voids and honeycomb by allowing concrete to flow around reinforcement and form surfaces', 'Increase the water content in dense sections of the pour', 'Align aggregate particles parallel to the form surface for a smoother finish'], 'Eliminate air voids and honeycomb by allowing concrete to flow around reinforcement and form surfaces', 'Internal vibrators liquefy the concrete temporarily, allowing it to flow into tight spaces around rebar and against forms. Insufficient consolidation results in honeycomb (voids) that reduce strength and appearance.', 3),
    mc('Cold weather concreting (below 40°F) requires precautions because:', ['Cold air reduces the alkalinity of fresh concrete, preventing proper hydration', 'Low temperatures dramatically slow or stop the hydration reaction — and freezing fresh concrete destroys its strength permanently', 'Cold concrete slumps (flows) too easily and is difficult to finish', 'Cold weather increases the water demand, requiring mix adjustments to add more cement'], 'Low temperatures dramatically slow or stop the hydration reaction — and freezing fresh concrete destroys its strength permanently', 'Below 50°F, hydration slows significantly. Below 32°F, water freezes before hydration can occur. Ice crystal formation expands the mix, destroying the forming cement paste. Cold weather concrete requires heated materials, enclosures, and insulating blankets.', 4),
    mc('The correct time to begin floating and finishing a concrete slab is:', ['Immediately after screeding while the surface is still very wet', 'After the bleed water has evaporated and the surface can support your weight without sinking more than 1/4 inch', 'After 4 hours regardless of surface conditions or weather', 'Only after the concrete has reached initial set (no longer flows when disturbed)'], 'After the bleed water has evaporated and the surface can support your weight without sinking more than 1/4 inch', 'Working too early seals the surface over bleed water that must escape, causing surface scaling. Too late and the concrete has hardened beyond the ability to finish. The sheen from bleed water disappearing, combined with footprint depth testing, indicates proper timing.', 5),
  ],
  'concrete-finishing': [
    mc('Bull floating after screeding a concrete slab serves what purpose?', ['Creating the final smooth finish surface', 'Leveling high spots and filling low spots, and pushing large aggregate below the surface while closing the surface', 'Compacting the concrete below the surface for strength', 'Creating a non-slip broom finish on the surface'], 'Leveling high spots and filling low spots, and pushing large aggregate below the surface while closing the surface', 'The bull float (a large, flat float on a long handle) refines the screed surface, embeds aggregate, and closes the surface to retain moisture for the bleed water phase. It sets up the surface for hand floating and finishing later.', 1),
    mc('A broom finish on an exterior concrete slab serves what purpose?', ['To create a decorative appearance that looks better than a smooth finish', 'To provide a non-slip texture by creating fine ridges that improve traction in wet conditions', 'To hide imperfections in the floating work', 'To speed up moisture evaporation from the surface for faster curing'], 'To provide a non-slip texture by creating fine ridges that improve traction in wet conditions', 'Broom finishing is standard on sidewalks, driveways, and any exterior surface where water could pool. A smooth-troweled finish becomes dangerously slick when wet. The direction of broom strokes should be perpendicular to foot traffic.', 2),
    mc('When should a concrete sealer be applied to a new exterior slab?', ['Immediately after finishing while the surface is still damp', 'After the concrete has cured for 28 days and is fully dry', 'At 24-48 hours as part of the curing process to retain moisture', 'Sealers are optional and provide only cosmetic benefit to exterior concrete'], 'After the concrete has cured for 28 days and is fully dry', 'Applying sealer to uncured or damp concrete traps moisture and can cause problems. Wait for full 28-day cure and ensure the surface is dry. Penetrating sealers protect against freeze-thaw damage and deicing salts.', 3),
    mc('Concrete slab "pop-outs" (small conical chunks that break from the surface) are caused by:', ['Insufficient floating pressure that leaves air pockets near the surface', 'Reactive aggregate particles that expand due to freeze-thaw cycles or alkali-silica reaction', 'Overworking the surface during finishing', 'Using too much water during curing'], 'Reactive aggregate particles that expand due to freeze-thaw cycles or alkali-silica reaction', 'Certain aggregate types absorb water and expand during freeze-thaw cycling, popping out of the concrete surface. Alkali-silica reaction (ASR) between cement alkalis and reactive silica in some aggregates also causes this.', 4),
    mc('Stamped concrete gets its decorative pattern from:', ['Pre-formed concrete poured into molds and then assembled', 'Textured mats pressed into the surface while the concrete is in a semi-plastic state during finishing', 'Grinding the surface after curing and applying colored stains in patterns', 'Casting the slab with colored aggregate layers at different depths'], 'Textured mats pressed into the surface while the concrete is in a semi-plastic state during finishing', 'Stamped concrete uses rigid or semi-rigid polyurethane or aluminum mats pressed into the concrete after color hardener and release agent are applied. The mats imprint patterns mimicking stone, brick, or wood. Timing is critical — too early or too late and the impressions don\'t hold.', 5),
  ],
  'mortar-and-mixing': [
    mc('The difference between mortar and concrete is:', ['Mortar contains coarse aggregate; concrete uses fine sand only', 'Concrete contains coarse aggregate (gravel); mortar uses only fine aggregate (sand) and is used for bonding masonry units', 'Mortar is a stronger material than concrete for equivalent cement content', 'Concrete is used above grade; mortar is used only below grade'], 'Concrete contains coarse aggregate (gravel); mortar uses only fine aggregate (sand) and is used for bonding masonry units', 'Mortar is cement, sand, and water — no gravel. This keeps it smooth and workable for troweling into thin joints between bricks or blocks. Concrete includes coarse aggregate for structural mass.', 1),
    mc('Type S mortar is specified for which applications?', ['Interior non-load-bearing walls only', 'Exterior and below-grade applications, structural masonry, and areas with lateral loads like retaining walls', 'Above-grade decorative applications only', 'Any application where Type N is too soft but Type M is too hard'], 'Exterior and below-grade applications, structural masonry, and areas with lateral loads like retaining walls', 'ASTM mortar types by compressive strength: M (highest), S, N (most common exterior), O (low-strength interior). Type S provides high bond strength and durability for exterior structural work, below grade, and where freeze-thaw resistance matters.', 2),
    mc('The correct consistency for brick mortar is commonly described as:', ['Wet enough to pour from the bucket without scooping', 'The consistency of peanut butter — stiff enough to hold a shape but workable with a trowel', 'Dry enough that it crumbles slightly when mixed — add water as you work', 'Fluid enough that bricks can slide easily for alignment after placement'], 'The consistency of peanut butter — stiff enough to hold a shape but workable with a trowel', 'Mortar should hold a clean edge when cut with a trowel but spread smoothly without crumbling. Too wet means low strength, poor bond, and staining. Too dry won\'t key into masonry pores or develop proper bond.', 3),
    mc('Why must masonry units be dampened before applying mortar in hot, dry weather?', ['Wet bricks provide a better key for mortar adhesion', 'Dry masonry absorbs water from the mortar too quickly, preventing proper hydration of the cement and reducing bond strength', 'The water prevents the mortar from sticking to the brick surface', 'Dampening prevents thermal expansion of the masonry unit during curing'], 'Dry masonry absorbs water from the mortar too quickly, preventing proper hydration of the cement and reducing bond strength', 'A kiln-dried or sun-heated brick will wick water from the mortar before the cement can hydrate and bond. Pre-dampening the brick slows suction. However, don\'t saturate — standing water prevents proper bond as well.', 4),
    mc('Retempered mortar (adding water to stiffened mortar and remixing) should be done:', ['Never — retempering is not permitted in any professional masonry work', 'Only within 2.5 hours of initial mix and only enough to restore workability — never after initial set begins', 'Whenever mortar becomes too stiff to work, regardless of elapsed time', 'Only with a machine mixer — hand retempering is not acceptable'], 'Only within 2.5 hours of initial mix and only enough to restore workability — never after initial set begins', 'ASTM C270 allows retempering within 2.5 hours of initial mixing to restore workability lost to evaporation. Once initial set begins, retempering breaks the forming cement bonds and the mortar must be discarded.', 5),
  ],
  'laying-brick': [
    mc('The term "running bond" in brick laying describes:', ['The pattern where each course offsets joints by half a brick from the course above and below', 'A bond pattern with bricks laid perpendicular to the wall face (headers) every sixth course', 'A decorative pattern used only for patio paving, not structural walls', 'Laying bricks at a 45-degree angle to the wall face for a herringbone pattern'], 'The pattern where each course offsets joints by half a brick from the course above and below', 'Running bond is the most common pattern. Each brick is centered over the joint below, staggering joints by half a unit. This distributes loads across the wall and ties courses together without the use of headers.', 1),
    mc('When laying the first course of brick, the most important step is:', ['Using the stiffest mortar possible for maximum compression strength in the bed joint', 'Establishing a perfectly level and properly positioned first course, as it controls the alignment of every course above', 'Laying the corners first and then filling between them with a story pole', 'Buttering the full face of each brick before placement'], 'Establishing a perfectly level and properly positioned first course, as it controls the alignment of every course above', 'The first course is the foundation of all the work above. If it\'s out of level, plumb, or improperly spaced, every subsequent course inherits that error. Corners are built first and used as guides for the courses between them.', 2),
    mc('Bed joints and head joints in masonry refer to:', ['Bed joints run horizontally (under each course); head joints are the vertical joints between bricks in a course', 'Bed joints are at the base of the wall; head joints are at the top', 'Both are horizontal joints — bed joints are at the corners; head joints are in the field', 'Head joints are at the back of the wall (wythe to wythe); bed joints are at the face'], 'Bed joints run horizontally (under each course); head joints are the vertical joints between bricks in a course', 'Bed joints receive the mortar layer on which the next course is laid. Head joints are buttered on the end of each brick as it is placed, creating the vertical joint between adjacent bricks in the same course.', 3),
    mc('A mason\'s story pole (or course rod) is used to:', ['Support bricks at the correct height during placement', 'Mark the heights of each course so all courses maintain consistent joint thickness throughout the wall', 'Verify that the wall is plumb at regular intervals during construction', 'Measure the horizontal spacing of bricks within each course'], 'Mark the heights of each course so all courses maintain consistent joint thickness throughout the wall', 'A story pole (or gauge rod) is a straight board marked at each course height. By checking the wall face against the pole, the mason ensures consistent joint thickness throughout the structure — critical for aligning openings and for appearance.', 4),
    mc('Weep holes in a brick veneer wall are provided to:', ['Allow inspection of the wall cavity without removing bricks', 'Drain water that enters the wall cavity and prevent moisture from building up behind the veneer', 'Provide ventilation to the wall cavity to prevent moisture condensation', 'Allow for thermal expansion of the brick veneer during temperature extremes'], 'Drain water that enters the wall cavity and prevent moisture from building up behind the veneer', 'Rain penetrates brick veneer. Flashing at the base of the cavity directs water to weep holes (typically open vertical head joints every 24-32 inches) where it drains out. Without weeps, trapped water damages the structure and causes efflorescence.', 5),
  ],
  'masonry-repair': [
    mc('Tuckpointing is the process of:', ['Applying a decorative colored mortar over old mortar joints for aesthetics', 'Removing deteriorated mortar to a minimum depth and filling with new mortar to restore the joint', 'Sealing all mortar joints with a clear waterproofing compound', 'Replacing damaged bricks while leaving the surrounding mortar intact'], 'Removing deteriorated mortar to a minimum depth and filling with new mortar to restore the joint', 'Tuckpointing (repointing) removes old, crumbling, or cracked mortar to a depth of at least 3/4 inch using an angle grinder or cold chisel, then packs in fresh mortar. It extends the life of brick walls by decades.', 1),
    mc('The new mortar used for tuckpointing should be:', ['Stronger (higher cement content) than the original mortar for better durability', 'Similar or slightly weaker than the original mortar so joints remain the sacrificial element and don\'t damage the brick', 'Type M mortar for all repointing applications regardless of the original mortar type', 'The same brand as the original mortar, mixed to twice the normal water content for better penetration'], 'Similar or slightly weaker than the original mortar so joints remain the sacrificial element and don\'t damage the brick', 'In historic and older masonry, using mortar stronger than the brick causes brick faces to spall as the mortar doesn\'t yield. Mortar joints should be the sacrificial element, not the irreplaceable brick units. Match original mortar strength as closely as possible.', 2),
    mc('Efflorescence (white staining) on brick surfaces is caused by:', ['Calcium from the brick dissolving in rain and staining the surface', 'Water-soluble salts being drawn to the surface by evaporating moisture and crystallizing on the face', 'Excess cement in the mortar mix leaching to the brick surface', 'A biological growth (mold or lichen) that attaches to porous brick surfaces'], 'Water-soluble salts being drawn to the surface by evaporating moisture and crystallizing on the face', 'Water moves through masonry, picking up soluble salts. When it evaporates at the surface, salts crystallize as a white powder or crust. Efflorescence itself is generally harmless but indicates water movement through the wall — the underlying source should be addressed.', 3),
    mc('When replacing a damaged brick in an existing wall, the replacement brick should be:', ['Any brick of the same nominal size regardless of age, texture, or color', 'Selected to match the size, texture, color, and absorption characteristics of the surrounding brick as closely as possible', 'A modern brick of higher strength than the originals for improved durability at the repair location', 'Installed with a stiffer mortar than surrounding joints to compensate for the single-brick repair'], 'Selected to match the size, texture, color, and absorption characteristics of the surrounding brick as closely as possible', 'A mismatched replacement brick stands out permanently. For historic work, salvaged bricks from the same period or careful color-matching is essential. Absorption rate (IRA) also matters — a very different absorption rate changes the bond with the mortar.', 4),
    mc('Lintel inspection and repair is critical because lintels:', ['Provide backing for the mortar joint at the top of an opening', 'Carry the masonry load above an opening (window, door) and transfer it to the wall on each side', 'Anchor the masonry veneer to the structural backup wall or frame', 'Create the thermal break between interior and exterior in a masonry wall'], 'Carry the masonry load above an opening (window, door) and transfer it to the wall on each side', 'Lintels span openings and carry the weight of masonry above. Corroded steel lintels expand and push out surrounding masonry, causing visible cracking. Failed lintels allow masonry above openings to settle or collapse.', 5),
  ],
}
