import type { ExerciseDef } from '../types'

function mc(question: string, options: string[], correctAnswer: string, explanation: string, order: number): ExerciseDef {
  return { question, type: 'MULTIPLE_CHOICE', options, correctAnswer, explanation, order }
}

export const tradesExercises1: Record<string, ExerciseDef[]> = {
  'voltage-current-resistance': [
    mc('What does Ohm\'s Law state?', ['Voltage equals current plus resistance', 'Voltage equals current multiplied by resistance', 'Current equals voltage multiplied by resistance', 'Resistance equals voltage plus current'], 'Voltage equals current multiplied by resistance', 'Ohm\'s Law: V = I × R. Voltage (V) equals current (I) times resistance (R). This relationship governs all basic electrical circuits.', 1),
    mc('A circuit has 12 volts and 4 ohms of resistance. What is the current?', ['3 amps', '48 amps', '8 amps', '0.33 amps'], '3 amps', 'Using I = V/R: 12 ÷ 4 = 3 amps. Current equals voltage divided by resistance.', 2),
    mc('What unit measures electrical resistance?', ['Ampere', 'Volt', 'Watt', 'Ohm'], 'Ohm', 'Resistance is measured in ohms (Ω), named after Georg Ohm. Current is measured in amps, voltage in volts, and power in watts.', 3),
    mc('If resistance in a circuit increases while voltage stays the same, what happens to current?', ['It increases', 'It decreases', 'It stays the same', 'It doubles'], 'It decreases', 'From I = V/R: if R goes up and V is fixed, I must go down. More resistance means less current for the same voltage.', 4),
    mc('What does voltage represent in an electrical circuit?', ['The flow of electrons through a conductor', 'The opposition to electron flow', 'The electrical pressure that drives current', 'The rate at which energy is consumed'], 'The electrical pressure that drives current', 'Voltage is the potential difference — the "pressure" that pushes electrons through a circuit. No voltage means no current flow.', 5),
  ],
  'ac-vs-dc': [
    mc('What is the key difference between AC and DC power?', ['AC uses higher voltage than DC', 'AC reverses direction periodically; DC flows in one direction', 'DC is more dangerous than AC', 'AC cannot be stored in batteries'], 'AC reverses direction periodically; DC flows in one direction', 'Alternating current (AC) cycles back and forth — in the US, 60 times per second. Direct current (DC) flows in a single constant direction.', 1),
    mc('Which type of power comes from a standard wall outlet in the US?', ['DC at 120 volts', 'AC at 120 volts', 'DC at 240 volts', 'AC at 240 volts'], 'AC at 120 volts', 'Standard US wall outlets deliver 120V AC at 60 Hz. Large appliances like dryers and ranges use 240V AC.', 2),
    mc('Why is AC used for power transmission over long distances instead of DC?', ['AC travels faster than DC', 'AC voltage can be easily stepped up and down with transformers', 'AC loses no energy during transmission', 'DC cannot travel more than one mile'], 'AC voltage can be easily stepped up and down with transformers', 'Transformers only work with AC. High-voltage AC transmission loses less energy over distance, then transformers step it back down for home use.', 3),
    mc('Which type of power do batteries produce?', ['AC', 'DC', 'Both AC and DC', 'Neither — batteries produce static electricity'], 'DC', 'Batteries produce DC — a steady, unidirectional flow of current. Devices that plug into walls often convert AC to DC internally using a rectifier.', 4),
    mc('What is the frequency of AC power in the United States?', ['50 Hz', '60 Hz', '120 Hz', '240 Hz'], '60 Hz', 'US AC power runs at 60 Hz — meaning the current changes direction 60 times per second. Most of Europe uses 50 Hz.', 5),
  ],
  'electrical-safety': [
    mc('What should you ALWAYS do before working on any electrical circuit?', ['Wear rubber-soled shoes', 'Turn off the breaker and verify power is off with a tester', 'Work quickly to minimize exposure time', 'Wear leather gloves'], 'Turn off the breaker and verify power is off with a tester', 'Never assume a breaker is labeled correctly. Always turn off the breaker AND confirm with a non-contact voltage tester that the circuit is truly de-energized.', 1),
    mc('Which is the most dangerous electrical hazard in wet locations?', ['High voltage shocking you directly', 'Current traveling through water to ground through your body', 'Overloaded circuits causing heat', 'Corroded wiring creating resistance'], 'Current traveling through water to ground through your body', 'Water dramatically lowers the resistance of the path to ground. Even low voltages can be lethal when current passes through a wet body to ground.', 2),
    mc('What does lockout/tagout (LOTO) protect against?', ['Accidental re-energizing of a circuit while someone is working on it', 'Water damage to electrical panels', 'Overloaded circuits', 'Improper wire gauge selection'], 'Accidental re-energizing of a circuit while someone is working on it', 'LOTO physically locks a breaker in the off position and tags it, preventing anyone from accidentally restoring power while a worker is in the circuit.', 3),
    mc('Electrical current of what amperage can be lethal to humans?', ['Above 50 amps', 'Above 1 amp', 'As little as 0.1 amps (100 milliamps)', 'Only above 240 volts'], 'As little as 0.1 amps (100 milliamps)', 'Current, not voltage, kills. As little as 100 mA (0.1 amp) through the heart can cause ventricular fibrillation. Even 10 mA causes painful muscle contractions.', 4),
    mc('Why should you never work on electrical systems alone?', ['It is illegal without a partner present', 'Someone must be present to shut off power and call for help if you are incapacitated', 'Two people are required to hold wires correctly', 'Insurance requires a witness'], 'Someone must be present to shut off power and call for help if you are incapacitated', 'If you are shocked and cannot release the circuit or call for help, a second person can cut power and call 911. Electrical injuries can cause muscle lock that prevents self-rescue.', 5),
  ],
  'reading-an-electrical-panel': [
    mc('What is the purpose of a circuit breaker in a service panel?', ['To increase voltage for high-demand appliances', 'To automatically interrupt current when it exceeds a safe level', 'To convert AC to DC power', 'To measure the amperage of each circuit'], 'To automatically interrupt current when it exceeds a safe level', 'A breaker trips — opening the circuit — when current exceeds its rated amperage, protecting wiring from overheating and potential fire.', 1),
    mc('What does a double-pole breaker in a panel indicate?', ['It protects two separate 120V circuits', 'It feeds a 240V circuit using both hot legs of the service', 'It provides extra protection for a standard 120V circuit', 'It is used only for GFCI-protected circuits'], 'It feeds a 240V circuit using both hot legs of the service', 'Double-pole breakers connect to both hot legs of the 120/240V service, providing 240V for appliances like dryers, water heaters, and HVAC equipment.', 2),
    mc('The main breaker in a panel controls what?', ['Only the largest circuit in the panel', 'All power entering the panel from the utility', 'The grounding system for the house', 'The neutral and ground bus bars only'], 'All power entering the panel from the utility', 'The main breaker is a double-pole breaker that can disconnect all power to the panel at once. It is the first point of control after the utility meter.', 3),
    mc('What does a tripped breaker look like in most panels?', ['It is pushed fully to the off position', 'It sits in a middle position between on and off', 'It has a red light illuminated', 'It appears identical to breakers that are on'], 'It sits in a middle position between on and off', 'When a breaker trips, the handle moves to a middle position — not fully on or fully off. To reset it, push it fully to off, then back to on.', 4),
    mc('What is the neutral bus bar in a service panel used for?', ['Connecting the hot wires from each circuit', 'Providing a return path for current on neutral (white) wires', 'Grounding all metal enclosures in the home', 'Connecting the main breaker to the utility lines'], 'Providing a return path for current on neutral (white) wires', 'The neutral bus bar collects the return path (white wires) from all circuits. In the main panel, neutral and ground are bonded together at this bar.', 5),
  ],
  'wiring-basics': [
    mc('In standard US residential wiring, what does a black wire indicate?', ['Neutral — the return path', 'Hot — carries voltage from the panel', 'Ground — safety path to earth', 'Traveler wire in a three-way switch circuit'], 'Hot — carries voltage from the panel', 'Black is hot in residential wiring. White is neutral, green or bare copper is ground. Red is sometimes used as a second hot wire in 240V or three-way switch wiring.', 1),
    mc('What does wire gauge indicate and which number is thicker: 12 AWG or 14 AWG?', ['Higher gauge numbers mean thicker wire; 14 AWG is thicker', 'Lower gauge numbers mean thicker wire; 12 AWG is thicker', 'Gauge and thickness are unrelated; check the label', 'Both are the same thickness but different materials'], 'Lower gauge numbers mean thicker wire; 12 AWG is thicker', 'In the AWG system, smaller numbers = larger wire. 12 AWG is thicker than 14 AWG and can carry more current (20A vs 15A).', 2),
    mc('Which wire gauge is required for a standard 20-amp circuit?', ['14 AWG', '12 AWG', '10 AWG', '16 AWG'], '12 AWG', '12 AWG wire is rated for 20-amp circuits. Using 14 AWG (rated for 15 amps) on a 20-amp breaker is a fire hazard — the breaker won\'t trip before the wire overheats.', 3),
    mc('What is the purpose of the ground wire in a circuit?', ['To carry return current back to the panel under normal operation', 'To provide a safe path for fault current and trip the breaker', 'To reduce electrical interference in audio and video systems', 'To balance the load between the two hot legs'], 'To provide a safe path for fault current and trip the breaker', 'Under normal conditions, no current flows through the ground wire. If a hot wire touches a metal enclosure, ground provides a low-resistance path that causes the breaker to trip.', 4),
    mc('NM-B cable (Romex) is appropriate for which installation?', ['Wet or damp locations', 'Indoor dry locations only', 'Exterior conduit runs', 'Underground burial'], 'Indoor dry locations only', 'NM-B (non-metallic sheathed cable, brand name Romex) is only listed for dry, indoor use. Outdoor, wet, and underground installations require appropriate cables like UF-B or conduit with THWN wire.', 5),
  ],
  'outlets-and-switches': [
    mc('What does a standard 15-amp duplex outlet consist of?', ['One receptacle with a 15-amp and a 20-amp slot', 'Two receptacles each capable of providing power independently', 'A single receptacle with GFCI protection built in', 'Two receptacles wired in series'], 'Two receptacles each capable of providing power independently', 'A duplex outlet has two receptacles (plug-in points) wired in parallel. Each can independently power a device up to the circuit\'s rating.', 1),
    mc('When wiring an outlet, the hot wire connects to which terminal?', ['The silver (neutral) screw', 'The green (ground) screw', 'The brass (hot) screw', 'Either silver or brass — polarity doesn\'t matter'], 'The brass (hot) screw', 'Hot (black) wire goes to the brass screw. Neutral (white) goes to the silver screw. Ground (green/bare) goes to the green screw. Reversed polarity can cause dangerous conditions.', 2),
    mc('A switch controls a circuit by doing what?', ['Reducing voltage to the connected device', 'Interrupting the hot wire to open and close the circuit', 'Interrupting the neutral wire to open and close the circuit', 'Changing the direction of current flow'], 'Interrupting the hot wire to open and close the circuit', 'Switches are always wired in the hot leg — never the neutral. Switching the neutral would leave the fixture at voltage even when "off," creating a shock hazard.', 3),
    mc('What is a three-way switch used for?', ['Controlling three separate fixtures from one location', 'Controlling one fixture from two different locations', 'Providing three levels of dimming', 'Switching 240V circuits safely'], 'Controlling one fixture from two different locations', 'Three-way switches come in pairs. They allow you to control one light (or outlet) from two locations — common at the top and bottom of stairs.', 4),
    mc('The T-shaped slot on a 20-amp outlet (vs the straight slot on a 15-amp) exists to:', ['Accommodate older two-prong plugs', 'Prevent 20-amp plugs from being inserted into 15-amp circuits', 'Allow 15-amp and 20-amp plugs to be used on the same circuit', 'Provide better contact for high-current devices'], 'Prevent 20-amp plugs from being inserted into 15-amp circuits', 'The T-shaped neutral slot on a 20-amp receptacle only accepts 20-amp plugs. A 20-amp circuit can have 15-amp receptacles on it, but a 15-amp circuit cannot have 20-amp receptacles.', 5),
  ],
  'gfci-and-afci': [
    mc('What does a GFCI outlet protect against?', ['Overloaded circuits causing heat damage', 'Current imbalance between hot and neutral that indicates a ground fault', 'Arc faults in deteriorated wiring', 'Voltage surges from lightning'], 'Current imbalance between hot and neutral that indicates a ground fault', 'A GFCI monitors the difference between current on the hot and neutral. If more than 5 milliamps is "missing" (going to ground through something — like a person), it trips in milliseconds.', 1),
    mc('Where are GFCI outlets required by the NEC?', ['Only in commercial buildings', 'In all new construction regardless of location', 'In areas near water: bathrooms, kitchens, garages, outdoors, and unfinished basements', 'Only in bathrooms and outdoor locations'], 'In areas near water: bathrooms, kitchens, garages, outdoors, and unfinished basements', 'The NEC requires GFCI protection wherever water and electricity may interact: bathrooms, kitchen counters within 6 feet of a sink, garages, outdoors, crawlspaces, and unfinished basements.', 2),
    mc('What does an AFCI breaker protect against?', ['Ground faults that could electrocute a person', 'Arc faults in damaged or deteriorated wiring that can cause fires', 'Overloads from too many devices on one circuit', 'Power surges from the utility'], 'Arc faults in damaged or deteriorated wiring that can cause fires', 'Arc fault circuit interrupters detect the electrical signature of arcing — which occurs in damaged wire insulation, loose connections, or pinched cords — and trip before a fire starts.', 3),
    mc('A GFCI outlet has "TEST" and "RESET" buttons. What should you do monthly?', ['Press RESET to ensure it has power', 'Press TEST to trip it, then RESET to restore it, verifying it works', 'Press both simultaneously to check for faults', 'Nothing — GFCIs are maintenance-free'], 'Press TEST to trip it, then RESET to restore it, verifying it works', 'The TEST button simulates a ground fault. A working GFCI will trip and cut power. Press RESET to restore. If it doesn\'t trip or won\'t reset, the GFCI is faulty and must be replaced.', 4),
    mc('A GFCI outlet installed at the first outlet in a circuit can protect:', ['Only that single outlet', 'All outlets downstream on the same circuit', 'All outlets in the entire panel', 'Only outlets on the same wall'], 'All outlets downstream on the same circuit', 'A single GFCI outlet can be wired to protect all outlets "downstream" of it on the same circuit. The downstream outlets are connected to the LOAD terminals, not the LINE terminals.', 5),
  ],
}
