import type { ExerciseDef } from '../types'

function mc(question: string, options: string[], correctAnswer: string, explanation: string, order: number): ExerciseDef {
  return { question, type: 'MULTIPLE_CHOICE', options, correctAnswer, explanation, order }
}

export const tradesExercises2: Record<string, ExerciseDef[]> = {
  'electrical-tools': [
    mc('What is a non-contact voltage tester used for?', ['Measuring the exact voltage of a circuit', 'Detecting whether a wire or outlet is live without touching it', 'Testing the continuity of a wire', 'Measuring resistance in a circuit'], 'Detecting whether a wire or outlet is live without touching it', 'A non-contact voltage tester beeps or lights up when held near a live wire or outlet. It is the first tool to use before touching any wiring — it doesn\'t require contact with the conductor.', 1),
    mc('A multimeter can measure which of the following?', ['Voltage only', 'Current only', 'Voltage, current, and resistance', 'Only AC voltage'], 'Voltage, current, and resistance', 'A multimeter (or VOM) measures volts, ohms, and milliamps. It can test voltage on live circuits, check continuity, measure resistance of components, and test batteries.', 2),
    mc('Wire strippers are designed to remove insulation without damaging:', ['The outer jacket of NM cable', 'The copper conductor inside the wire', 'The ground wire from a cable', 'Electrical tape wrapped around a splice'], 'The copper conductor inside the wire', 'Wire strippers have sized notches that cut through insulation at the correct depth for each wire gauge without nicking the copper. Nicked conductors create weak points and heat.', 3),
    mc('What is a fish tape used for?', ['Measuring wire lengths in a panel', 'Pulling wire through walls, conduit, and tight spaces', 'Detecting hidden wires inside walls', 'Splicing wires inside junction boxes'], 'Pulling wire through walls, conduit, and tight spaces', 'A fish tape is a stiff but flexible steel or fiberglass tape that is fed through a wall cavity or conduit. Wire is attached to the end and the tape is retracted, pulling the wire through.', 4),
    mc('Which tool is required to install wire connectors (wire nuts) correctly?', ['Needle-nose pliers only', 'No tool is required — they are twisted on by hand', 'A crimping tool', 'Linesman pliers'], 'No tool is required — they are twisted on by hand', 'Wire nuts are twisted onto stripped wire ends by hand. The internal spring threads grip the wires as you twist clockwise. Linesman pliers can help with difficult connections but aren\'t required.', 5),
  ],
  'nec-basics': [
    mc('What is the National Electrical Code (NEC)?', ['A federal law mandating electrical safety', 'A model code adopted by states and localities setting minimum electrical safety standards', 'A manufacturer\'s specification guide for electrical products', 'A training curriculum for licensed electricians'], 'A model code adopted by states and localities setting minimum electrical safety standards', 'The NEC is published by the NFPA and is a model code — not federal law. States and municipalities adopt it (often with amendments) to establish local electrical safety requirements.', 1),
    mc('How often is the NEC updated?', ['Every year', 'Every 3 years', 'Every 5 years', 'Only when a major accident prompts revision'], 'Every 3 years', 'The NEC is revised on a 3-year cycle. The most recent editions are 2020 and 2023. Your local jurisdiction may be on an older adopted edition.', 2),
    mc('The NEC establishes requirements for which of the following?', ['The price of electrical materials', 'Installation methods, wire sizing, breaker sizing, and protection requirements', 'Licensing requirements for electricians', 'The efficiency ratings of electrical appliances'], 'Installation methods, wire sizing, breaker sizing, and protection requirements', 'The NEC covers how electrical systems must be installed — conductor sizing, protection, conduit fill, clearances, grounding, and more. Licensing is handled separately by states and localities.', 3),
    mc('Which organization publishes the NEC?', ['OSHA', 'UL (Underwriters Laboratories)', 'NFPA (National Fire Protection Association)', 'IEEE (Institute of Electrical and Electronics Engineers)'], 'NFPA (National Fire Protection Association)', 'The NEC is NFPA 70, published by the National Fire Protection Association. UL tests and certifies equipment. OSHA sets workplace safety standards. IEEE sets engineering standards.', 4),
    mc('If your local jurisdiction has adopted the 2017 NEC but you installed to the 2020 NEC standard, is the installation compliant?', ['No — you must always use the most current NEC', 'Yes — meeting a newer code always satisfies an older adopted code', 'Only if you get a variance from the local authority', 'It depends on whether the inspector approves the newer standard'], 'Yes — meeting a newer code always satisfies an older adopted code', 'Codes set minimums. Exceeding the locally adopted standard is always acceptable. You cannot install to a standard below what the local jurisdiction has adopted.', 5),
  ],
  'permits-and-inspections': [
    mc('Why are electrical permits required for significant work?', ['To generate revenue for the local government', 'To ensure work is inspected by a qualified authority and meets code for safety', 'To protect licensed electricians from competition', 'To create a record for insurance purposes only'], 'To ensure work is inspected by a qualified authority and meets code for safety', 'Permits require inspections. Inspections catch dangerous work before walls close up. Unpermitted work can void homeowner\'s insurance, cause problems at sale, and create liability.', 1),
    mc('What typically happens during a rough-in electrical inspection?', ['The inspector tests all outlets and switches for proper operation', 'The inspector verifies wiring methods, box fill, and conductor installation before walls are closed', 'The inspector checks the panel labeling and breaker sizing only', 'The inspector issues an occupancy permit'], 'The inspector verifies wiring methods, box fill, and conductor installation before walls are closed', 'A rough-in inspection happens after wiring is run but before drywall. The inspector checks wire routing, box placement, stapling intervals, conductor sizing, and protection requirements.', 2),
    mc('What work typically does NOT require an electrical permit?', ['Adding a new circuit', 'Replacing a circuit breaker', 'Replacing a like-for-like outlet or switch in the same location', 'Installing a new subpanel'], 'Replacing a like-for-like outlet or switch in the same location', 'Minor repairs and replacements — swapping an outlet or switch in the same location for the same type — are typically exempt. Adding circuits, panels, or service changes require permits.', 3),
    mc('What is a "certificate of occupancy" in the context of electrical work?', ['A permit to begin electrical work on a new building', 'A document issued after all inspections pass confirming the building is safe to occupy', 'A license confirming an electrician is qualified to work', 'An insurance certificate required before starting work'], 'A document issued after all inspections pass confirming the building is safe to occupy', 'A CO is issued by the authority having jurisdiction after all final inspections — electrical, plumbing, structural — have passed. It confirms the building meets code for occupancy.', 4),
    mc('If an inspector fails your electrical work, what is the correct next step?', ['Proceed anyway since the inspection is advisory only', 'Correct the identified deficiencies and call for a re-inspection', 'Appeal immediately to the state licensing board', 'Cover the work and hope the next inspector approves it'], 'Correct the identified deficiencies and call for a re-inspection', 'A failed inspection means specific items don\'t meet code. Fix the issues listed on the correction notice, then schedule a re-inspection. Covering failed work is a code violation.', 5),
  ],
  'supply-and-drain': [
    mc('What are the two distinct systems in a residential plumbing installation?', ['Hot water and cold water systems', 'The supply system and the drain-waste-vent (DWV) system', 'The pressure system and the gravity system', 'The indoor system and the outdoor irrigation system'], 'The supply system and the drain-waste-vent (DWV) system', 'Supply lines bring pressurized fresh water in. The DWV system removes wastewater by gravity and uses vent pipes to maintain proper air pressure so drains flow freely.', 1),
    mc('What is the purpose of a P-trap in a drain line?', ['To filter debris from the drainwater', 'To hold a small amount of water that blocks sewer gases from entering the home', 'To regulate the flow rate of the drain', 'To connect the drain to the vent stack'], 'To hold a small amount of water that blocks sewer gases from entering the home', 'The curved P-trap retains water after each use. That water plug prevents methane, hydrogen sulfide, and other sewer gases from traveling back up through the drain into living spaces.', 2),
    mc('Vent pipes in a DWV system serve what purpose?', ['They supply fresh air to combustion appliances', 'They allow air into drain lines so water flows freely without siphoning', 'They exhaust hot water vapor from the water heater', 'They equalize water pressure throughout the supply system'], 'They allow air into drain lines so water flows freely without siphoning', 'Without venting, draining water creates a vacuum that siphons the water from P-traps. Vent pipes (typically exiting through the roof) allow air in, maintaining atmospheric pressure so drains flow.', 3),
    mc('The main shutoff valve for a house is most commonly located:', ['At the water meter near the street', 'At the water heater', 'Where the main water line enters the house', 'At the first fixture on the cold water line'], 'Where the main water line enters the house', 'The main shutoff is typically on the supply line just inside where it enters the foundation or crawlspace. Knowing its location is critical in a plumbing emergency.', 4),
    mc('What is the difference between drain pipe slope requirements and supply line installation?', ['Supply lines must slope; drain lines can be level', 'Drain lines require a downward slope (typically 1/4" per foot) to drain by gravity; supply lines are pressurized and can run in any direction', 'Both supply and drain lines must maintain exactly 1/4" per foot slope', 'There is no difference — both are gravity-fed systems'], 'Drain lines require a downward slope (typically 1/4" per foot) to drain by gravity; supply lines are pressurized and can run in any direction', 'Supply water is under pressure from the municipal main or well pump — it can go up, down, or horizontal. Drain lines rely on gravity, requiring a minimum 1/4" drop per foot of run.', 5),
  ],
  'water-pressure': [
    mc('What is the normal residential water pressure range?', ['10-30 PSI', '40-80 PSI', '100-120 PSI', '15-25 PSI'], '40-80 PSI', 'Residential water pressure should be between 40 and 80 PSI. Below 40 PSI causes poor flow at fixtures. Above 80 PSI stresses pipes, fixtures, and appliances and can cause leaks.', 1),
    mc('What tool measures water pressure at a fixture or hose bib?', ['A flow meter', 'A pressure gauge with a hose fitting', 'A manometer', 'A multimeter set to pressure mode'], 'A pressure gauge with a hose fitting', 'A simple pressure gauge with a hose thread fitting screws onto a hose bib (outdoor spigot). Turn on the water with all other fixtures off for a static pressure reading.', 2),
    mc('A pressure reducing valve (PRV) is installed to:', ['Increase water pressure when it is too low from the street', 'Reduce high incoming street pressure to a safe level for home plumbing', 'Prevent backflow from the house into the municipal supply', 'Filter sediment from the incoming water supply'], 'Reduce high incoming street pressure to a safe level for home plumbing', 'Many municipal supplies deliver water at 100+ PSI. A PRV reduces this to the 50-70 PSI range, protecting fixtures, water heaters, washing machines, and pipes from premature wear.', 3),
    mc('Water hammer is the banging sound in pipes caused by:', ['Loose pipes vibrating against framing members', 'A sudden pressure wave when fast-closing valves (like solenoids in dishwashers) stop flow abruptly', 'Air trapped in the supply lines', 'Sediment buildup in the water heater tank'], 'A sudden pressure wave when fast-closing valves (like solenoids in dishwashers) stop flow abruptly', 'When water moving at speed is suddenly stopped, kinetic energy creates a pressure spike that causes pipes to bang. Air chambers or water hammer arrestors absorb this shock.', 4),
    mc('Low water pressure at a single fixture but normal pressure at others most likely indicates:', ['A failing PRV affecting only that fixture', 'A clogged aerator or partially closed supply stop valve at that fixture', 'Municipal pressure drop in that section of street', 'A leak in the main supply line near the house'], 'A clogged aerator or partially closed supply stop valve at that fixture', 'Isolated low pressure at one fixture points to a local cause: a clogged aerator screen (especially in older homes with mineral buildup), a partially closed stop valve, or a faulty cartridge.', 5),
  ],
  'pipe-materials': [
    mc('What is the main advantage of PEX (cross-linked polyethylene) pipe over copper?', ['PEX is more resistant to freeze damage and easier to install around obstacles', 'PEX lasts longer than copper in all conditions', 'PEX can be used for gas lines as well as water', 'PEX has no expansion or contraction with temperature changes'], 'PEX is more resistant to freeze damage and easier to install around obstacles', 'PEX is flexible, resists freezing better than rigid pipe (it expands instead of splitting), and can snake around obstacles without fittings. It has largely replaced copper in new residential construction.', 1),
    mc('CPVC differs from standard PVC in that CPVC is rated for:', ['Underground burial use', 'Hot water supply lines (up to 180°F)', 'Gas distribution systems', 'Higher pressure than copper'], 'Hot water supply lines (up to 180°F)', 'Standard PVC is only rated for cold water and drain/waste/vent. CPVC (chlorinated PVC) is rated for hot water supply up to 180°F and is used in some hot water distribution systems.', 2),
    mc('What is copper pipe Type M, L, and K distinguished by?', ['Material purity — K is the purest copper', 'Wall thickness — K is thickest, M is thinnest', 'Application — M for drain, L for supply, K for gas', 'Connection method — M is soldered, L uses compression, K uses flare fittings'], 'Wall thickness — K is thickest, M is thinnest', 'All three are the same copper alloy. The letters indicate wall thickness. Type K (green) is thickest for underground. Type L (blue) is standard for supply. Type M (red) is thinnest, for indoor supply.', 3),
    mc('Black iron pipe is used in residential construction primarily for:', ['Cold water supply', 'Natural gas and propane distribution', 'Hot water recirculation systems', 'Drain lines where PVC is not allowed'], 'Natural gas and propane distribution', 'Black iron (steel) pipe is the traditional material for gas distribution inside buildings. It is strong, threaded, and gas-compatible. It is not used for water because it corrodes.', 4),
    mc('What is the key disadvantage of galvanized steel pipe in older homes?', ['It is too rigid to connect to modern flexible supply lines', 'It corrodes from the inside over time, reducing flow and eventually leaking', 'It reacts with chlorine in municipal water and becomes toxic', 'It cannot be joined with standard fittings or tools'], 'It corrodes from the inside over time, reducing flow and eventually leaking', 'Galvanized pipe has a zinc coating that eventually corrodes from the inside in contact with water. The rust buildup reduces flow and the pipe eventually develops pinhole leaks — a common repiping situation.', 5),
  ],
}
