import type { ExerciseDef } from '../types'

function mc(question: string, options: string[], correctAnswer: string, explanation: string, order: number): ExerciseDef {
  return { question, type: 'MULTIPLE_CHOICE', options, correctAnswer, explanation, order }
}

export const tradesExercises3: Record<string, ExerciseDef[]> = {
  'fixing-a-leak': [
    mc('Before attempting any plumbing repair, the first step is always:', ['Applying plumber\'s tape to the leaking joint', 'Turning off the water supply to that fixture or the whole house', 'Draining the hot water tank', 'Calling a licensed plumber to assess the situation'], 'Turning off the water supply to that fixture or the whole house', 'Water must be shut off before opening any plumbing connection. Use the stop valve under the fixture for small repairs, or the main shutoff for larger work or if no stop valve exists.', 1),
    mc('A slow drip from a compression faucet is most often caused by:', ['A cracked supply line', 'A worn rubber washer or O-ring that no longer seals properly', 'Excess water pressure', 'A clogged aerator'], 'A worn rubber washer or O-ring that no longer seals properly', 'Compression faucets use a rubber washer pressed against a seat to stop flow. The washer degrades over time and no longer seals. Replacing the washer is usually a $1-2 fix.', 2),
    mc('A pinhole leak in a copper pipe is best repaired permanently by:', ['Wrapping it tightly with plumber\'s tape and hose clamps', 'Cutting out the damaged section and replacing it with new pipe and fittings', 'Applying epoxy pipe repair compound as a permanent solution', 'Increasing water pressure to force the leak closed'], 'Cutting out the damaged section and replacing it with new pipe and fittings', 'Pinhole leaks indicate corrosion. Patches and tape are temporary emergency measures only. The corroded section must be cut out and replaced. Multiple pinholes may mean the whole pipe run needs replacing.', 3),
    mc('How can you locate a water leak inside a wall without cutting into it?', ['Listen with a stethoscope pressed against the wall', 'Use a moisture meter, thermal camera, or acoustic leak detector', 'Shut off the main and watch the meter for movement', 'All of the above methods can help locate leaks'], 'All of the above methods can help locate leaks', 'Multiple diagnostic tools are used together: a moisture meter finds wet areas, a thermal camera shows temperature differences, an acoustic detector picks up flow sounds, and meter monitoring confirms active leaks.', 4),
    mc('After completing a plumbing repair, what should you always do before considering the job done?', ['Apply pipe dope to all connections as a precaution', 'Restore water pressure slowly and watch the repair for leaks for several minutes', 'Test all other fixtures in the house to check for pressure changes', 'Document the repair with photos for permit purposes'], 'Restore water pressure slowly and watch the repair for leaks for several minutes', 'Gradually restore water, then inspect all connections for drips or seeping. Check again after 30 minutes. A repair that looks dry initially may weep once pipe threads fully pressurize.', 5),
  ],
  'toilets-and-faucets': [
    mc('A toilet that runs continuously after flushing is most likely caused by:', ['A cracked toilet tank', 'A faulty fill valve or a flapper that doesn\'t seat properly', 'Excess water pressure in the supply line', 'A clogged jet hole under the rim'], 'A faulty fill valve or a flapper that doesn\'t seat properly', 'Most running toilets have one of two causes: a flapper (rubber seal at the tank bottom) that doesn\'t close completely, or a fill valve that doesn\'t shut off. Both are inexpensive DIY repairs.', 1),
    mc('A faucet handle is hard to turn or stiff. The most likely cause in a cartridge faucet is:', ['Low water pressure from the supply line', 'A worn or damaged cartridge that needs replacement', 'Mineral buildup in the aerator', 'A bad supply shut-off valve below the sink'], 'A worn or damaged cartridge that needs replacement', 'Cartridge faucets use a plastic or brass cartridge to control flow and temperature. Worn cartridges become stiff or start leaking. Replacement cartridges are brand-specific and typically cost $15-40.', 2),
    mc('When a toilet rocks side to side, the likely cause is:', ['An improper water pressure setting', 'A failed wax ring requiring immediate replacement', 'Loose or rotted floor flanges or bolts', 'A cracked toilet base that needs replacement'], 'Loose or rotted floor flanges or bolts', 'A rocking toilet usually has loose closet bolts or a deteriorated flange. This must be addressed promptly — rocking breaks the wax ring seal, allowing sewer gas and water to escape under the floor.', 3),
    mc('Ball faucets (common in kitchen sinks) use what to control water flow and temperature?', ['Rubber washers on a stem', 'A rotating ceramic disc', 'A ball with inlet holes that align with ports as it rotates', 'An electronic solenoid valve'], 'A ball with inlet holes that align with ports as it rotates', 'Ball faucets have a ball-shaped cap with holes that align with hot/cold ports as the handle moves. Worn springs, seats, and O-rings are the most common failure points in ball faucets.', 4),
    mc('What is the wax ring on a toilet for?', ['Securing the toilet to the floor bolts', 'Creating a watertight seal between the toilet horn and the floor flange', 'Absorbing vibration between the toilet and tile floor', 'Sealing the water supply connection to the tank'], 'Creating a watertight seal between the toilet horn and the floor flange', 'The wax ring fills the gap between the toilet\'s horn (outlet) and the floor flange, creating an airtight and watertight seal. It must be replaced any time the toilet is removed and reset.', 5),
  ],
  'water-heaters': [
    mc('What is the recommended water heater temperature setting to prevent scalding while inhibiting Legionella bacteria growth?', ['100°F', '120°F', '140°F', '160°F'], '120°F', '120°F is the standard recommendation — hot enough to inhibit Legionella bacteria growth but low enough to reduce scalding risk. Above 130°F, the risk of third-degree burns in seconds increases significantly.', 1),
    mc('The anode rod in a water heater serves what purpose?', ['Heating the water by electrical resistance', 'Sacrificially corroding to protect the tank from rust', 'Regulating water temperature at the element', 'Filtering sediment before it enters the tank'], 'Sacrificially corroding to protect the tank from rust', 'The anode rod is made of magnesium or aluminum. It corrodes in place of the steel tank. When the anode is consumed, the tank itself begins to corrode. Anode rods should be inspected every 3-5 years.', 2),
    mc('Sediment buildup at the bottom of a water heater tank causes what problems?', ['Only reduced efficiency — sediment has no safety implications', 'Reduced efficiency, longer recovery time, rumbling noises, and accelerated tank corrosion', 'Higher water pressure in the supply lines', 'Contaminated water that is unsafe to use'], 'Reduced efficiency, longer recovery time, rumbling noises, and accelerated tank corrosion', 'Sediment insulates the burner from the water (gas) or covers the element (electric), reducing efficiency. It also traps water against the steel tank, accelerating corrosion. Flushing annually extends tank life.', 3),
    mc('A temperature and pressure (T&P) relief valve on a water heater is designed to:', ['Maintain steady water temperature during high demand', 'Open and release pressure if temperature or pressure exceeds safe limits, preventing an explosion', 'Reduce water pressure before it enters the tank', 'Balance hot and cold water pressure throughout the house'], 'Open and release pressure if temperature or pressure exceeds safe limits, preventing an explosion', 'The T&P valve is a critical safety device. If the thermostat fails and water overheats, pressure builds. The valve opens automatically to vent steam and water, preventing a catastrophic tank failure.', 4),
    mc('What is the main advantage of a tankless (on-demand) water heater over a storage tank heater?', ['It costs less to purchase and install', 'It heats water only when needed, eliminating standby heat loss from a constantly maintained tank', 'It can supply unlimited hot water to multiple fixtures simultaneously without any limit', 'It uses no electricity and relies entirely on gravity flow'], 'It heats water only when needed, eliminating standby heat loss from a constantly maintained tank', 'Storage tank heaters maintain hot water 24/7, losing heat continuously (standby loss). Tankless heaters fire only when flow is detected, saving 20-35% in energy costs for typical households.', 5),
  ],
  'drain-clogs': [
    mc('Which method should you try FIRST for a clogged drain?', ['Chemical drain cleaner', 'A cup plunger', 'A drain snake (auger)', 'Dismantling the P-trap'], 'A cup plunger', 'Start with the least invasive method. A plunger creates pressure/vacuum that often dislodges soft clogs. If that fails, try a drain snake. Chemical cleaners should be used cautiously and as a last resort.', 1),
    mc('Why should chemical drain cleaners (like Drano) be used sparingly?', ['They are only effective on hair clogs, not grease', 'They generate heat that can damage PVC pipes and are hazardous if mixed with other chemicals or splashed', 'They are too expensive for regular use', 'They require a permit to use in residential plumbing'], 'They generate heat that can damage PVC pipes and are hazardous if mixed with other chemicals or splashed', 'Caustic drain cleaners generate heat that can warp PVC, damage older pipes, and corrode metal. They are dangerous if splashed on skin or mixed with other cleaners. Overuse harms pipes over time.', 2),
    mc('A bathroom sink drains slowly but isn\'t completely blocked. The most likely cause is:', ['A clogged main sewer line', 'Hair and soap buildup on the pop-up drain stopper mechanism', 'A collapsed drain pipe under the floor', 'Incorrect pipe slope in the wall'], 'Hair and soap buildup on the pop-up drain stopper mechanism', 'Bathroom sinks almost always clog at the pop-up stopper assembly. Removing and cleaning the stopper (and the pivot rod it connects to) clears most slow bathroom sink drains in minutes.', 3),
    mc('When using a drain snake (hand auger), what indicates you\'ve reached the clog?', ['The snake stops advancing and meets resistance', 'The snake returns to you automatically', 'The water in the fixture starts draining', 'The snake makes a grinding sound'], 'The snake stops advancing and meets resistance', 'When the snake tip meets resistance, you\'ve hit the clog. Rotate the handle to break it up or hook it. If the snake passes through without resistance and the drain still doesn\'t clear, the blockage may be farther down.', 4),
    mc('A main sewer line clog (affecting multiple fixtures throughout the house) is best cleared by:', ['Plunging every affected fixture simultaneously', 'Using a motorized drain auger or calling a professional with a sewer camera', 'Pouring boiling water down the lowest floor drain', 'Increasing water pressure at the main shutoff'], 'Using a motorized drain auger or calling a professional with a sewer camera', 'Main line clogs require a heavy-duty motorized auger (drum machine) to reach the distance and break through root intrusion or solid buildup. A sewer camera identifies the exact cause and location.', 5),
  ],
  'heating-systems': [
    mc('What is the difference between a forced-air furnace and a boiler heating system?', ['Furnaces heat water; boilers heat air', 'Furnaces heat and distribute air through ducts; boilers heat water distributed through radiators or radiant floors', 'Boilers are only used in commercial buildings', 'Furnaces are electric only; boilers are gas only'], 'Furnaces heat and distribute air through ducts; boilers heat water distributed through radiators or radiant floors', 'Forced-air furnaces heat air and move it through ductwork. Boilers heat water that circulates through radiators, baseboard heaters, or in-floor tubing. Both can use gas, oil, or electric as a fuel source.', 1),
    mc('A heat pump provides heating by:', ['Burning fuel to generate heat directly', 'Extracting heat from outdoor air (even in cold weather) and moving it inside', 'Converting electrical energy to radiant heat through resistance elements', 'Circulating heated water from a central boiler'], 'Extracting heat from outdoor air (even in cold weather) and moving it inside', 'Heat pumps move heat rather than generate it. Even at 20°F, outdoor air contains heat energy that a heat pump can extract and concentrate inside — typically delivering 2-3x more heat energy than the electricity consumed.', 2),
    mc('AFUE (Annual Fuel Utilization Efficiency) measures what in a heating system?', ['The speed at which a furnace can heat a space', 'The percentage of fuel energy that is converted to usable heat over the heating season', 'The amount of carbon monoxide produced per BTU of heat', 'The operating cost compared to a baseline system'], 'The percentage of fuel energy that is converted to usable heat over the heating season', 'An 80% AFUE furnace converts 80% of fuel to heat; 20% is lost up the flue. A 96% AFUE condensing furnace loses only 4%. Higher AFUE means lower operating costs but higher equipment cost.', 3),
    mc('A condensing furnace (95%+ AFUE) differs from a standard furnace because it:', ['Burns fuel at a higher temperature for more output', 'Extracts so much heat from combustion gases that the flue gases condense and the unit can vent through PVC pipe', 'Requires natural gas rather than propane to achieve high efficiency', 'Uses two heat exchangers in series with an electric backup'], 'Extracts so much heat from combustion gases that the flue gases condense and the unit can vent through PVC pipe', 'Condensing furnaces extract so much heat that exhaust gases cool below the dew point and condense to liquid. The cool, non-corrosive exhaust can vent through inexpensive PVC instead of a metal flue.', 4),
    mc('What is the purpose of a heat exchanger in a gas furnace?', ['To transfer heat from the burner flame to the air stream without mixing combustion gases with house air', 'To exchange heat between supply and return air to pre-warm incoming cold air', 'To regulate burner temperature to prevent overheating', 'To recover heat from the flue gases before they exit the building'], 'To transfer heat from the burner flame to the air stream without mixing combustion gases with house air', 'The heat exchanger is a sealed metal chamber. Combustion products stay inside it. House air passes over the outside, absorbing heat. A cracked heat exchanger is a serious CO hazard — it allows combustion gases into the air supply.', 5),
  ],
  'cooling-systems': [
    mc('How does a central air conditioner remove heat from a home?', ['It generates cold air and pumps it into the home', 'It absorbs heat from indoor air using refrigerant and rejects that heat outside', 'It circulates outdoor cold air through the duct system during cool nights', 'It uses a chemical reaction to lower the temperature of indoor air'], 'It absorbs heat from indoor air using refrigerant and rejects that heat outside', 'Air conditioning moves heat — it doesn\'t create cold. Refrigerant absorbs heat at the indoor evaporator coil, travels to the outdoor condenser where it rejects the heat, then returns to repeat the cycle.', 1),
    mc('The SEER rating (Seasonal Energy Efficiency Ratio) of an air conditioner measures:', ['The cooling capacity in BTUs per hour', 'The cooling output divided by the electrical energy used over a cooling season — higher is more efficient', 'The decibel level of the outdoor unit during operation', 'The percentage of humidity removed from indoor air'], 'The cooling output divided by the electrical energy used over a cooling season — higher is more efficient', 'SEER = cooling BTUs / watt-hours of energy used. A 16 SEER unit uses about 60% of the electricity a 10 SEER unit uses for the same cooling. Minimum SEER for new units is 14-15 depending on region.', 2),
    mc('What is the purpose of the expansion valve in a refrigeration system?', ['To compress the refrigerant gas into a high-pressure liquid', 'To rapidly drop refrigerant pressure, causing it to cool dramatically before entering the evaporator', 'To measure refrigerant flow and alert technicians to low charge', 'To separate liquid and gaseous refrigerant before the compressor'], 'To rapidly drop refrigerant pressure, causing it to cool dramatically before entering the evaporator', 'The expansion valve (or TXV) creates a pressure drop. As high-pressure liquid refrigerant passes through, it expands and rapidly cools — dropping to temperatures well below the air passing over the evaporator coil.', 3),
    mc('Ice forming on an air conditioner\'s indoor evaporator coil during operation usually indicates:', ['The system is working correctly and very efficiently', 'Restricted airflow (dirty filter/coil) or low refrigerant charge causing the coil to drop below freezing', 'The thermostat is set too low', 'Excessive humidity in the home'], 'Restricted airflow (dirty filter/coil) or low refrigerant charge causing the coil to drop below freezing', 'When airflow is restricted or refrigerant is low, the coil gets colder than normal. Moisture in the air freezes on it. Ice formation further blocks airflow — a worsening cycle. The system should be shut off until the ice melts and the cause corrected.', 4),
    mc('What refrigerant replaced R-22 (Freon) in new residential AC systems?', ['R-134a', 'R-410A', 'R-404A', 'R-717 (ammonia)'], 'R-410A', 'R-410A (brand names Puron, Genetron) replaced R-22, which was phased out under the Montreal Protocol for its ozone-depleting properties. R-22 is no longer manufactured; supplies are limited and prices are high.', 5),
  ],
  'ventilation-and-air-quality': [
    mc('What is the purpose of ventilation in a building?', ['To cool the building using outdoor air exclusively', 'To dilute and remove indoor air pollutants and provide fresh oxygen for occupants', 'To pressurize the building to prevent outside air infiltration', 'To circulate heated or cooled air through the duct system'], 'To dilute and remove indoor air pollutants and provide fresh oxygen for occupants', 'Ventilation dilutes CO2, VOCs, moisture, odors, and combustion byproducts. Modern tight-construction homes trap pollutants, making mechanical ventilation essential for indoor air quality.', 1),
    mc('An HRV (Heat Recovery Ventilator) improves on simple exhaust ventilation by:', ['Heating the incoming outdoor air with a gas burner', 'Transferring heat from outgoing stale air to incoming fresh air, reducing heating/cooling losses', 'Filtering outdoor air with a HEPA filter before distributing it', 'Recirculating indoor air through a UV sterilization chamber'], 'Transferring heat from outgoing stale air to incoming fresh air, reducing heating/cooling losses', 'An HRV uses a heat exchanger to transfer 70-85% of the heat in exhaust air to the incoming fresh air stream. This provides fresh air without the energy penalty of heating or cooling raw outdoor air.', 2),
    mc('MERV ratings for air filters measure:', ['The filter\'s ability to control static electricity in ductwork', 'The minimum efficiency for reporting particulate capture — higher MERV catches smaller particles', 'The maximum airflow restriction the filter adds to the system', 'The months of service life before replacement is required'], 'The minimum efficiency for reporting particulate capture — higher MERV catches smaller particles', 'MERV 1-4 filters capture large dust. MERV 8-11 captures mold spores and pet dander. MERV 13-16 captures bacteria and some viruses. Very high MERV filters require stronger fans due to increased resistance.', 3),
    mc('Carbon monoxide (CO) in a home most commonly comes from:', ['Off-gassing from new furniture and carpets', 'Incomplete combustion from gas appliances, furnaces, fireplaces, or attached garages', 'Radon gas entering from the soil', 'Mold growing in damp areas'], 'Incomplete combustion from gas appliances, furnaces, fireplaces, or attached garages', 'CO is produced when fuel burns without sufficient oxygen. Cracked heat exchangers, blocked flues, back-drafting, and running vehicles in attached garages are the top residential CO sources.', 4),
    mc('The best location for a CO detector in a home is:', ['At floor level, since CO is heavier than air', 'At ceiling level, since CO is lighter than air', 'At breathing height (5-6 feet off the floor) near sleeping areas', 'Adjacent to gas appliances where CO is generated'], 'At breathing height (5-6 feet off the floor) near sleeping areas', 'CO is nearly the same density as air and mixes throughout a room. Detectors belong near sleeping areas (hallways outside bedrooms) at breathing height where they can wake occupants during nighttime CO events.', 5),
  ],
}
