import type { ExerciseDef } from '../types'

function mc(question: string, options: string[], correctAnswer: string, explanation: string, order: number): ExerciseDef {
  return { question, type: 'MULTIPLE_CHOICE', options, correctAnswer, explanation, order }
}

export const tradesExercises7: Record<string, ExerciseDef[]> = {
  'routine-maintenance': [
    mc('How often should engine oil and filter be changed in a modern vehicle using conventional oil?', ['Every 1,000-2,000 miles', 'Every 3,000 miles — the traditional standard', 'Every 5,000-7,500 miles or per the manufacturer\'s oil life monitor', 'Only when the oil appears black on the dipstick'], 'Every 5,000-7,500 miles or per the manufacturer\'s oil life monitor', 'Modern engines and oil formulations have extended drain intervals well beyond the old 3,000-mile myth. Most manufacturers specify 5,000-7,500 miles with conventional oil or 7,500-10,000+ with synthetic. Follow the owner\'s manual.', 1),
    mc('Tire rotation extends tire life by:', ['Ensuring all tires wear down at the same rate, maximizing the life of the full set', 'Moving the best tires to the drive axle for safety', 'Checking and correcting tire pressure at each rotation', 'Rebalancing tires as part of the rotation service'], 'Ensuring all tires wear down at the same rate, maximizing the life of the full set', 'Drive tires, front (steering) tires, and rear tires all wear differently based on their position. Rotating them every 5,000-7,500 miles evens out wear so the whole set can be replaced together.', 2),
    mc('Checking and maintaining proper tire pressure is important because:', ['Low pressure improves ride quality without affecting safety', 'Underinflated tires cause excessive heat buildup, accelerated shoulder wear, and reduced fuel economy', 'Overinflated tires provide better traction in wet conditions', 'Tire pressure only matters for highway driving'], 'Underinflated tires cause excessive heat buildup, accelerated shoulder wear, and reduced fuel economy', 'Low pressure causes the tire to flex excessively, generating heat (a leading cause of blowouts) and wearing the outer edges faster. Overinflation causes center wear and reduced contact patch, decreasing traction.', 3),
    mc('The serpentine belt in modern vehicles drives what systems?', ['Only the alternator', 'The alternator, power steering pump, A/C compressor, and water pump — all from one belt', 'The timing system connecting the crankshaft to the camshafts', 'The transmission\'s torque converter'], 'The alternator, power steering pump, A/C compressor, and water pump — all from one belt', 'A single serpentine belt (guided by an automatic tensioner) runs all engine accessories. When it fails, all these systems fail simultaneously. Replacement every 60,000-100,000 miles is typical preventive maintenance.', 4),
    mc('Coolant (antifreeze) needs periodic replacement because:', ['It evaporates from the overflow reservoir and must be topped off regularly', 'The corrosion inhibitors degrade over time, causing the coolant to become acidic and attack metal components', 'The 50/50 mixture ratio changes and it becomes too concentrated over time', 'Coolant absorbs oil from a leaking head gasket and must be flushed when contaminated'], 'The corrosion inhibitors degrade over time, causing the coolant to become acidic and attack metal components', 'Coolant additives neutralize acids and protect aluminum, steel, and copper from corrosion. Over time (typically 2-5 years depending on type), inhibitors are depleted and the coolant becomes corrosive. Flushing replaces the inhibitor package.', 5),
  ],
  'reading-error-codes': [
    mc('OBD-II (On-Board Diagnostics II) became standard on all US vehicles sold after:', ['1988', '1996', '2000', '2005'], '1996', 'OBD-II was mandated for all cars and light trucks sold in the US from model year 1996 onward. It standardized diagnostic connectors, protocols, and trouble code definitions across all manufacturers.', 1),
    mc('What does a P0300 diagnostic trouble code indicate?', ['A problem with the vehicle\'s powertrain control module', 'Random or multiple cylinder misfires detected', 'An oxygen sensor reading outside normal parameters', 'A problem with the idle air control valve'], 'Random or multiple cylinder misfires detected', 'P-codes are powertrain codes. P0300 = random/multiple cylinder misfire. P0301-P0308 indicate specific cylinder misfires (P0302 = cylinder 2). Misfires can damage catalytic converters rapidly if driven for extended periods.', 2),
    mc('The difference between a "hard code" and a "pending code" in OBD-II is:', ['Hard codes require dealer service; pending codes can be cleared at home', 'A pending code has tripped once but not enough times to illuminate the check engine light; a hard code has met the threshold to turn on the light', 'Hard codes affect emissions; pending codes are performance-related only', 'There is no difference — all codes illuminate the check engine light'], 'A pending code has tripped once but not enough times to illuminate the check engine light; a hard code has met the threshold to turn on the light', 'Most emission-related faults must be detected on consecutive drive cycles before the MIL (check engine light) illuminates. Pending codes let technicians catch developing problems before the light comes on.', 3),
    mc('After clearing a check engine light with a scan tool, why might an emissions inspection fail?', ['The scan tool may have corrupted the ECU\'s programming', 'Drive cycle "readiness monitors" are reset and may not be complete — emissions tests check that all monitors have run', 'The code is stored in a separate memory that the scan tool cannot clear', 'Inspections require the MIL to be off AND the code to remain stored'], 'Drive cycle "readiness monitors" are reset and may not be complete — emissions tests check that all monitors have run', 'Clearing codes resets all OBD-II readiness monitors to "incomplete." Inspections check that these monitors (O2 sensor, catalyst, EVAP, etc.) have run and passed. The vehicle needs specific driving patterns to complete each monitor.', 4),
    mc('A scan tool and a code reader differ in that a scan tool can:', ['Read codes from all vehicle manufacturers; a code reader only works on domestic vehicles', 'Display live sensor data, perform bidirectional tests, and access manufacturer-specific codes; a code reader only reads generic P-codes', 'Clear codes without requiring a drive cycle to turn off the MIL', 'Read codes without connecting to the OBDII port, using wireless technology'], 'Display live sensor data, perform bidirectional tests, and access manufacturer-specific codes; a code reader only reads generic P-codes', 'Basic code readers retrieve and clear generic OBD-II codes. A full scan tool shows live PIDs (parameter IDs) like O2 sensor voltage and MAP pressure, performs component activation tests, and accesses manufacturer-enhanced codes.', 5),
  ],
  'common-repairs': [
    mc('Replacing brake pads is a job most DIYers can do because it primarily requires:', ['Bleeding the brake system after compression', 'Compressing the caliper piston back into its bore, removing old pads, and inserting new ones with the caliper reassembled', 'Special brake bleeding equipment and a second person', 'Removing the rotor to access the caliper mounting bolts'], 'Compressing the caliper piston back into its bore, removing old pads, and inserting new ones with the caliper reassembled', 'Basic pad replacement requires a C-clamp or piston tool to push the piston back, removing two caliper bolts, swapping pads, and reassembling. Brake fluid in the reservoir may overflow when the piston is compressed — have a turkey baster ready.', 1),
    mc('An air filter replacement is straightforward because:', ['It requires no tools and takes less than 5 minutes on most vehicles', 'It must be installed at the dealer to avoid voiding the warranty', 'It requires a specialized filter wrench for the housing', 'It needs to be broken in with two quarts of oil run through it first'], 'It requires no tools and takes less than 5 minutes on most vehicles', 'Most engine air filters are accessible by opening a plastic airbox — usually no tools required, or just a screwdriver. The owner\'s manual shows the location. Replacing the filter at the recommended interval is simple and saves fuel.', 2),
    mc('Replacing a car battery safely requires:', ['Disconnecting the negative terminal first (to prevent sparks), then the positive', 'Disconnecting the positive terminal first, then the negative', 'Disconnecting both terminals simultaneously', 'Using the vehicle\'s jump-start mode before disconnecting'], 'Disconnecting the negative terminal first (to prevent sparks), then the positive', 'Always remove negative (ground) first. If your wrench touches any grounded metal while disconnecting the positive terminal, no current flows. Disconnect positive first, and any ground contact causes a spark and potential battery explosion.', 3),
    mc('Replacing wiper blades when they streak or skip is important for:', ['Preventing damage to the windshield glass from blade framework contact', 'Maintaining visibility in rain, snow, and after headlight glare in wet conditions', 'Preventing the wiper motor from burning out from excessive friction', 'All of the above reasons'], 'All of the above reasons', 'Worn blades streak, reducing visibility — a safety issue. The metal frame can contact and scratch glass. Friction from a blade not gliding smoothly can strain the wiper motor over time. Blade replacement is cheap insurance.', 4),
    mc('When replacing spark plugs, the correct torque matters because:', ['Over-tightening strips the threads in the aluminum head or cracks the ceramic insulator; under-tightening allows gas blowby', 'Plug torque determines the gap and therefore the spark intensity', 'Manufacturers specify torque to avoid warranty issues, though any tight installation works equally well', 'Over-tightening improves sealing but under-tightening reduces fuel consumption'], 'Over-tightening strips the threads in the aluminum head or cracks the ceramic insulator; under-tightening allows gas blowby', 'Aluminum heads are soft — a stripped spark plug thread requires a helicoil or head removal to repair. Under-tightened plugs can work loose and blow out with combustion pressure. Use a torque wrench and manufacturer spec.', 5),
  ],
  'when-to-take-it-in': [
    mc('Which repair should a DIYer typically leave to a professional?', ['Replacing an air filter', 'Replacing wiper blades', 'Replacing a timing belt or timing chain', 'Replacing an engine\'s cabin air filter'], 'Replacing a timing belt or timing chain', 'Timing belt replacement requires precise alignment of crankshaft and camshafts and often requires special tools. On interference engines, a misaligned timing belt can cause pistons to collide with valves, resulting in catastrophic engine damage.', 1),
    mc('Signs that brake rotors need replacement rather than just pad replacement include:', ['Rotors that appear shiny and smooth after driving', 'Deep grooves, thickness below minimum specification, or severe pulsation indicating warping', 'Squealing during initial brake application in the morning', 'Brake dust on the wheels after normal driving'], 'Deep grooves, thickness below minimum specification, or severe pulsation indicating warping', 'Rotors have a minimum thickness specification stamped on them. Rotors worn below this thickness cannot dissipate heat properly. Deep grooves grip pads unevenly. Warped rotors cause pedal pulsation and inconsistent braking.', 2),
    mc('When getting a quote from a repair shop, the best approach is:', ['Always choose the lowest quote since the same repair is the same quality everywhere', 'Get two or three written quotes for the same described repair, ask what parts brand will be used, and check reviews', 'Trust only dealerships for accurate repair quotes', 'Agree to the first shop that can take your car immediately'], 'Get two or three written quotes for the same described repair, ask what parts brand will be used, and check reviews', 'Prices vary significantly between shops. Multiple quotes reveal outliers. Asking about parts quality (OEM vs. aftermarket) reveals whether cost differences reflect quality differences. Reviews reflect consistency of work.', 3),
    mc('A car is safe to drive with which of the following warning lights on?', ['Oil pressure warning (red oil can)', 'Temperature warning (high coolant temp)', 'Low tire pressure warning (TPMS)', 'Battery warning (battery symbol)'], 'Low tire pressure warning (TPMS)', 'Low tire pressure reduces handling and can lead to a blowout but doesn\'t create immediate mechanical danger if pressure is only slightly low. Pull over and check pressure soon. The other three warnings indicate imminent mechanical damage — stop immediately.', 4),
    mc('What does it mean when a shop says a repair requires "dealer-only" programming?', ['The part is not available from aftermarket suppliers', 'After installation, the vehicle\'s computer (ECU) must be calibrated or programmed to recognize the new component, which requires manufacturer software', 'The part has a warranty only honored at dealerships', 'The repair requires a factory-trained technician by law'], 'After installation, the vehicle\'s computer (ECU) must be calibrated or programmed to recognize the new component, which requires manufacturer software', 'Many modern components — control modules, throttle bodies, key fobs, TPMS sensors — require ECU programming after installation. This used to require a dealer, but aftermarket programmers and expanded scan tools handle many of these now.', 5),
  ],
  'stick-welding': [
    mc('Stick welding (SMAW) uses a consumable electrode covered in flux. What does the flux do?', ['Provides filler metal to the weld puddle only', 'Burns to create shielding gas and slag that protects the molten weld from atmospheric contamination', 'Pre-heats the base metal before the arc is struck', 'Provides the electrical current that maintains the arc'], 'Burns to create shielding gas and slag that protects the molten weld from atmospheric contamination', 'The flux coating on a stick electrode burns in the arc, creating a shielding gas cloud and a slag layer that floats on top of the molten puddle, protecting it from oxygen and nitrogen until it solidifies. The slag is chipped off after cooling.', 1),
    mc('E6013 and E7018 are common electrode designations. What does the "70" in E7018 indicate?', ['The electrode diameter in thousandths of an inch', 'The minimum tensile strength of the deposited weld metal in thousands of PSI (70,000 PSI)', 'The amperage range the electrode is designed for', 'The percent iron powder content in the flux coating'], 'The minimum tensile strength of the deposited weld metal in thousands of PSI (70,000 PSI)', 'The AWS designation: E = electrode, 70 = 70,000 PSI tensile strength, 1 = usable in all positions, 8 = flux type (low hydrogen, DC+). E6013 = 60,000 PSI tensile, all position, AC-capable.', 2),
    mc('Low-hydrogen electrodes (7018) must be stored in:', ['A sealed original package at room temperature', 'A heated rod oven at 250-300°F to prevent moisture absorption', 'A sealed plastic bag with desiccant packets', 'Normal shop conditions — humidity only affects flux-cored wire, not stick electrodes'], 'A heated rod oven at 250-300°F to prevent moisture absorption', '7018 is classified low-hydrogen — it is specially formulated to minimize hydrogen in the weld (which causes hydrogen-induced cracking in high-strength steel). Moisture exposure defeats this. Rods left out of the oven must be re-dried or discarded.', 3),
    mc('The correct arc length for stick welding is approximately:', ['Equal to the diameter of the electrode core wire', '3-4 times the electrode diameter for maximum penetration', 'As long as possible to allow slag to float away from the puddle', 'Touching the electrode to the workpiece and backing off slowly'], 'Equal to the diameter of the electrode core wire', 'The arc gap should equal the diameter of the electrode\'s bare metal core — typically 1/8" for a 1/8" (3.2mm) electrode. Too long = wide, flat, porous bead with undercut. Too short = stubbing out and a narrow, convex bead.', 4),
    mc('An advantage of stick welding over MIG in field applications is:', ['Stick produces cleaner welds with less spatter', 'Stick equipment is simpler, doesn\'t require a gas cylinder, and works outdoors in wind', 'Stick is faster and requires less operator skill than MIG', 'Stick can be used on thinner materials than MIG without burn-through'], 'Stick equipment is simpler, doesn\'t require a gas cylinder, and works outdoors in wind', 'MIG shielding gas is blown away by wind, causing porosity and contamination. Stick\'s flux creates its own shielding, working in wind, outdoors, and in difficult access areas. Stick is the foundation of structural and pipeline welding.', 5),
  ],
  'tig-welding': [
    mc('TIG welding (GTAW) uses a non-consumable tungsten electrode. Filler is added by:', ['Automatically feeding wire through the TIG torch', 'Dipping a separate filler rod held in the non-torch hand into the leading edge of the puddle', 'Melting the base metal together without filler for autogenous welds only', 'Using the tungsten itself as both electrode and filler'], 'Dipping a separate filler rod held in the non-torch hand into the leading edge of the puddle', 'TIG is a two-handed process. The torch hand maintains the arc; the filler hand repeatedly dips the rod into the front of the puddle. On thin material, autogenous (filler-free) fusion welding is possible.', 1),
    mc('TIG welding produces the highest quality welds because:', ['It uses the highest amperage of any welding process', 'Precise current control, separate filler addition, and inert gas shielding allow exact control over heat input and weld chemistry', 'The tungsten electrode creates a hotter arc than consumable electrodes', 'TIG can weld faster than MIG, reducing distortion from extended heat input'], 'Precise current control, separate filler addition, and inert gas shielding allow exact control over heat input and weld chemistry', 'TIG allows the welder to control arc independently of filler addition. Foot pedal amperage control adjusts heat on the fly. Pure argon shielding produces clean, spatter-free welds on aluminum, stainless, titanium, and thin materials.', 2),
    mc('What causes tungsten contamination during TIG welding?', ['Using AC current on steel instead of DC', 'The tungsten electrode touching the molten weld puddle or filler rod', 'Using pure argon instead of argon/helium mix', 'Welding at too low an amperage for the tungsten diameter'], 'The tungsten electrode touching the molten weld puddle or filler rod', 'Contact with the puddle or filler rod contaminates the tungsten tip — inclusions from tungsten in the weld are a defect. The tungsten must be re-ground or broken back to a clean point before resuming. Good technique maintains arc gap without contact.', 3),
    mc('Welding aluminum with TIG requires AC (alternating current) rather than DC because:', ['Aluminum conducts heat away too rapidly for DC to maintain an arc', 'The AC electrode-positive half-cycle breaks up the aluminum oxide layer that would otherwise prevent fusion', 'DC causes excessive spatter on aluminum at welding temperatures', 'Aluminum requires lower amperage than DC machines can provide at fine-tuned levels'], 'The AC electrode-positive half-cycle breaks up the aluminum oxide layer that would otherwise prevent fusion', 'Aluminum forms a tough, high-melting-point oxide layer (2037°C vs. aluminum\'s 660°C melting point). The electrode-positive portion of the AC cycle has a "cleaning action" that blasts away this oxide, allowing the aluminum underneath to fuse.', 4),
    mc('TIG welding is most suited to which applications?', ['Heavy structural steel fabrication where speed is critical', 'Thin, exotic, or precision materials like stainless, titanium, aluminum, and chromoly where appearance and quality matter', 'Outdoor repairs and field welding in variable conditions', 'High-production manufacturing where automated equipment reduces operator influence'], 'Thin, exotic, or precision materials like stainless, titanium, aluminum, and chromoly where appearance and quality matter', 'TIG\'s slow speed and two-hand technique make it impractical for heavy fabrication. Its precision, cleanliness, and control make it standard for aerospace, food equipment, custom motorcycles, and medical device fabrication.', 5),
  ],
  'choosing-a-process': [
    mc('For a beginner learning to weld mild steel in a shop setting, which process is typically recommended first?', ['TIG, because it teaches the most skill fundamentals', 'MIG (solid wire GMAW), because the machine manages wire feeding and it produces results faster', 'Stick (SMAW), because it works on any power source and in any conditions', 'Flux-core, because it doesn\'t require shielding gas'], 'MIG (solid wire GMAW), because the machine manages wire feeding and it produces results faster', 'MIG is the easiest process to learn basic technique on — the machine feeds wire automatically and settings can be adjusted until results look right. TIG and stick require more manual coordination and patience for beginners.', 1),
    mc('Flux-core arc welding (FCAW) has an advantage over solid-wire MIG when:', ['Welding thin sheet metal where burn-through is a concern', 'Welding outdoors or in drafty conditions where shielding gas would be blown away', 'Welding titanium or other exotic alloys', 'Welding in overhead positions exclusively'], 'Welding outdoors or in drafty conditions where shielding gas would be blown away', 'Self-shielded FCAW uses a flux-filled hollow wire that generates its own shielding, similar to stick electrodes. No external gas is needed, so wind is less of a factor. Common in structural steel, construction, and shipyard work.', 2),
    mc('A job requiring welding 1/4" stainless steel for a food-service counter would most logically use:', ['Stick welding for speed and penetration', 'TIG welding for clean, corrosion-resistant welds with no spatter', 'MIG with stainless wire and tri-mix gas', 'Either TIG or MIG with stainless wire — both are appropriate for this application'], 'Either TIG or MIG with stainless wire — both are appropriate for this application', 'Both are used for stainless. TIG produces cleaner cosmetic welds; MIG with tri-mix (90% He/7.5% Ar/2.5% CO2) or 98% Ar/2% O2 is faster. The choice depends on production rate, appearance requirements, and available equipment.', 3),
    mc('Why is stick welding preferred for structural steel and pipeline work over MIG?', ['Stick deposits metal faster than MIG on heavy structural sections', 'Stick works outdoors in wind, on rusty or coated steel, with portable equipment and no gas cylinder', 'Stick produces less distortion in thick sections than MIG', 'Stick is more cost-effective for thin materials used in structural framing'], 'Stick works outdoors in wind, on rusty or coated steel, with portable equipment and no gas cylinder', 'Structural work is done outdoors on steel that may have mill scale, rust, or primer. Stick handles contaminated base metal better and requires only a welding machine and electrodes — no gas, no wire feeder — ideal for remote locations.', 4),
    mc('The process "best" for a given weld is determined by:', ['Whatever the welder learned first and is most comfortable with', 'The combination of base material, thickness, position, quality requirements, production rate, and conditions', 'The most expensive process, which always produces the best results', 'Standard industry tables that assign a process to each material type regardless of application'], 'The combination of base material, thickness, position, quality requirements, production rate, and conditions', 'No single process is best for everything. TIG excels at precision on thin exotics; MIG at production speed on clean steel; stick at portability and outdoor use; plasma at cutting. Good welders know when each is appropriate.', 5),
  ],
  'welding-safety': [
    mc('Arc flash from welding can cause what eye injury even with indirect exposure?', ['Temporary blindness lasting a few minutes', 'Arc eye (photokeratitis) — a painful UV burn to the cornea that may not appear until hours after exposure', 'Permanent color blindness from repetitive exposure', 'Only cosmetic redness — UV radiation at welding distances is not strong enough to damage the cornea'], 'Arc eye (photokeratitis) — a painful UV burn to the cornea that may not appear until hours after exposure', 'Arc flash produces intense UV radiation. Even a few seconds of exposure without eye protection causes a painful condition similar to a sunburned eyeball. Symptoms often appear 6-12 hours later. Welding curtains protect bystanders.', 1),
    mc('The minimum lens shade for MIG welding at typical amperages (100-300A) is approximately:', ['Shade 3-4', 'Shade 7-8', 'Shade 10-12', 'Shade 15-16'], 'Shade 10-12', 'ANSI recommends shade 10 for MIG welding under 150A, shade 12 for 150-500A. TIG at lower amperages can use shade 8-10. Auto-darkening helmets set to the appropriate shade provide protection instantly without manually lowering the hood.', 2),
    mc('What hazard does welding galvanized steel create that solid steel does not?', ['Extreme spatter that is more likely to ignite combustibles', 'Zinc fume fever from zinc oxide fumes released when the galvanized coating burns', 'A harder-than-normal weld bead that is brittle and prone to cracking', 'Electrical conductivity issues that prevent a stable arc from forming'], 'Zinc fume fever from zinc oxide fumes released when the galvanized coating burns', 'Welding galvanized steel releases zinc oxide fumes. Inhaling them causes metal fume fever — flu-like symptoms (chills, fever, nausea) that appear 4-8 hours after exposure. Weld galvanized steel outdoors or with forced-air extraction whenever possible.', 3),
    mc('A fire watch is required after welding operations in an area with combustibles because:', ['Insurance policies mandate a fire watch regardless of conditions', 'Welding spatter can smolder in hidden areas and ignite fires minutes to hours after welding ends', 'OSHA regulations require one hour of observation after any hot work regardless of conditions', 'Combustibles near the welding area must be documented before and after welding'], 'Welding spatter can smolder in hidden areas and ignite fires minutes to hours after welding ends', 'Welding spatter travels up to 35 feet and can smolder in insulation, wood framing, or debris for hours before igniting. OSHA requires a 30-minute minimum fire watch after hot work in areas with combustibles.', 4),
    mc('When welding in a confined space, what is the primary hazard beyond fumes?', ['Excessive noise from the arc in an enclosed space', 'Oxygen depletion from shielding gas (argon) or fuel combustion, creating an asphyxiation risk', 'The inability to maintain proper joint fit-up in tight quarters', 'Increased electrical shock risk from higher humidity in enclosed spaces'], 'Oxygen depletion from shielding gas (argon) or fuel combustion, creating an asphyxiation risk', 'Argon is heavier than air and can displace oxygen in a confined space, creating a deadly oxygen-deficient atmosphere with no warning odor. Atmospheric monitoring, forced ventilation, and a standby person outside are mandatory for confined space hot work.', 5),
  ],
  'how-concrete-works': [
    mc('Concrete gains strength through which process?', ['Drying out as water evaporates from the mix', 'A chemical reaction (hydration) between Portland cement and water that does not require drying', 'Freezing of the water within the mix after placement', 'Compression from form pressure as it sets'], 'A chemical reaction (hydration) between Portland cement and water that does not require drying', 'Concrete gains strength through hydration — cement reacts with water to form calcium silicate hydrate crystals. This is why concrete submerged in water still gains strength, and why keeping it moist (curing) improves strength development.', 1),
    mc('The water-to-cement ratio in a concrete mix affects:', ['Only the workability (how easy it is to place and finish)', 'Both workability and final strength — more water makes it easier to work but produces weaker concrete', 'Only final strength — workability is controlled by aggregate size', 'Neither — strength depends only on the cement content, not water content'], 'Both workability and final strength — more water makes it easier to work but produces weaker concrete', 'A lower w/c ratio produces stronger, more durable concrete with less shrinkage. Excess water weakens the cement paste, increases porosity, and causes more cracking. Admixtures (plasticizers) can improve workability without adding water.', 2),
    mc('Why should concrete be cured (kept moist) for at least 7 days after placement?', ['To prevent the surface from getting dirty before it hardens', 'To allow the hydration reaction to continue — it stops if the mix dries out before gaining full strength', 'To prevent thermal shock from temperature changes during hardening', 'To allow the aggregate to settle uniformly throughout the pour'], 'To allow the hydration reaction to continue — it stops if the mix dries out before gaining full strength', 'Hydration requires water. If fresh concrete dries out too quickly, the reaction stops prematurely and the concrete reaches only a fraction of its potential strength. Moist curing (water, wet burlap, or curing compound) retains moisture.', 3),
    mc('Concrete achieves approximately what percentage of its design strength after 28 days?', ['50%', '75%', '95-99%', '100% exactly'], '95-99%', '28 days is the standard testing age because concrete achieves approximately 95-99% of its design strength by then. It continues to gain strength slowly for years — 90-day strength may be 15-20% higher than 28-day.', 4),
    mc('Control joints are placed in concrete flatwork to:', ['Provide visual interest and break the monotony of a plain slab', 'Create planned weak points where the inevitable shrinkage cracks will occur in a controlled, straight line', 'Connect the concrete slab to adjacent sections for structural continuity', 'Allow water to drain through the slab surface'], 'Create planned weak points where the inevitable shrinkage cracks will occur in a controlled, straight line', 'Concrete always cracks as it shrinks during curing. Control joints (typically 1/4 of slab depth, spaced 10-15 feet apart) are weakened sections that direct cracks to a straight, controlled location rather than a random visible crack.', 5),
  ],
}
