import type { ExerciseDef } from '../types'

function mc(question: string, options: string[], correctAnswer: string, explanation: string, order: number): ExerciseDef {
  return { question, type: 'MULTIPLE_CHOICE', options, correctAnswer, explanation, order }
}

export const tradesExercises6: Record<string, ExerciseDef[]> = {
  'finish-carpentry': [
    mc('When installing base molding at an inside corner, the correct joint is:', ['A 45-degree miter on both pieces', 'A butt joint on one piece and a coped cut on the other', 'Two square butt joints meeting in the corner', 'A scarf joint at 22.5 degrees'], 'A butt joint on one piece and a coped cut on the other', 'Coping produces a tighter joint than mitering at inside corners because walls are rarely perfectly square. One piece butts to the wall. The second is cut to the profile of the first using a coping saw, then lapped over it.', 1),
    mc('The purpose of a "reveal" on door casing (the small offset from the edge of the door jamb) is:', ['To prevent the casing from interfering with the door swing', 'To provide a consistent visual reference line and compensate for slight imperfections in the jamb', 'To allow for seasonal wood movement of the jamb', 'Required by code to maintain a minimum clearance'], 'To provide a consistent visual reference line and compensate for slight imperfections in the jamb', 'A 3/16" to 1/4" reveal is marked around the jamb with a combination square. Casing is nailed to this line, giving a clean, consistent look even if the jamb isn\'t perfectly plumb or the door opening is slightly out of square.', 2),
    mc('When nailing trim with a finish nailer, nails should be driven at a slight angle so that:', ['They sink deeper for a stronger hold', 'If they miss a stud, they don\'t protrude through the wall surface', 'They can be hidden more easily with filler', 'The trim cannot be removed without damaging the wall'], 'If they miss a stud, they don\'t protrude through the wall surface', 'A nail fired straight into a wall will protrude through the drywall if it misses the stud. Angling 5-10 degrees ensures that even a miss stays within the wall cavity, and angling inward can help lock trim to the surface.', 3),
    mc('Cabinet installation requires what critical first step before any cabinets are hung?', ['Locating the highest point of the floor and establishing a level reference line from it', 'Attaching all base cabinets to each other before mounting to the wall', 'Installing the upper cabinets first while the floor area is unobstructed', 'Shimming the wall to be perfectly plumb'], 'Locating the highest point of the floor and establishing a level reference line from it', 'Floors are rarely level. Find the highest point, then use a level (or laser) to establish a consistent layout line. All base cabinet heights and upper cabinet positions reference from this line — not the floor itself.', 4),
    mc('Scarf joints in long runs of base or crown molding should be located:', ['At a wall stud so both pieces can be nailed', 'At the midpoint of the longest wall', 'At an outside corner where they are most visible and easily inspected', 'Anywhere convenient as long as they are glued'], 'At a wall stud so both pieces can be nailed', 'Both ends of a scarf joint (cut at 45° to lap each other) need to be nailed to solid backing. Locating the joint over a stud gives nailing for both pieces, and cutting the angle so it laps away from the viewer makes the joint nearly invisible.', 5),
  ],
  'the-engine': [
    mc('In a four-stroke internal combustion engine, what is the correct order of the four strokes?', ['Compression, intake, power, exhaust', 'Intake, compression, power, exhaust', 'Power, intake, compression, exhaust', 'Intake, power, compression, exhaust'], 'Intake, compression, power, exhaust', 'Each cylinder goes through: intake (air/fuel mixture drawn in), compression (piston compresses the mixture), power (spark ignites mixture, expanding gases push the piston down), exhaust (burned gases pushed out).', 1),
    mc('Engine displacement refers to:', ['The maximum RPM the engine can sustain', 'The total volume swept by all pistons during one complete cycle', 'The ratio of compressed to uncompressed gas in each cylinder', 'The amount of fuel the engine consumes per mile'], 'The total volume swept by all pistons during one complete cycle', 'Displacement (measured in liters or cubic inches) is the total volume the pistons displace. A 2.0L engine has 2,000cc of displacement. Larger displacement generally means more power, but efficiency, turbocharging, and design matter more in modern engines.', 2),
    mc('What is the purpose of engine oil?', ['To cool the engine by circulating through the cooling system', 'To lubricate moving parts, reduce friction and heat, and remove contaminants from engine surfaces', 'To provide a hydraulic medium for variable valve timing systems only', 'To seal the rings against the cylinder walls and prevent compression loss'], 'To lubricate moving parts, reduce friction and heat, and remove contaminants from engine surfaces', 'Oil lubricates journals, bearings, and cylinder walls; cushions impacts; transfers heat away from hot components; and carries contaminants to the filter. Old oil loses viscosity and becomes acidic, causing accelerated wear.', 3),
    mc('A car\'s cooling system maintains engine temperature by:', ['Circulating air through fins on the engine block', 'Circulating coolant (antifreeze/water mixture) through the engine block and a radiator where heat is dissipated to outside air', 'Using the exhaust system to remove heat as combustion gases exit', 'Running the air conditioning compressor to cool the engine bay'], 'Circulating coolant (antifreeze/water mixture) through the engine block and a radiator where heat is dissipated to outside air', 'Coolant absorbs heat from the block and heads, then flows to the radiator where airflow (from driving or the cooling fan) dissipates the heat. The thermostat regulates coolant temperature.', 4),
    mc('Compression ratio in an engine refers to:', ['The ratio of engine RPM to wheel RPM through the drivetrain', 'The ratio of cylinder volume at the bottom of the stroke to volume at the top of the stroke (combustion chamber volume)', 'The maximum pressure the fuel injection system generates', 'The ratio of engine output to fuel consumed'], 'The ratio of cylinder volume at the bottom of the stroke to volume at the top of the stroke (combustion chamber volume)', 'A 10:1 compression ratio means the air/fuel mixture is compressed to 1/10th its original volume. Higher compression = more power and efficiency, but requires higher octane fuel to prevent pre-ignition (knock).', 5),
  ],
  'drivetrain': [
    mc('What is the primary function of a vehicle\'s transmission?', ['To convert engine torque to wheel torque and allow the engine to operate in its efficient RPM range at various vehicle speeds', 'To transfer power from the engine to all four wheels equally', 'To reduce engine speed for city driving and increase it for highway driving', 'To engage and disengage the engine from the drivetrain'], 'To convert engine torque to wheel torque and allow the engine to operate in its efficient RPM range at various vehicle speeds', 'The transmission uses gear ratios to match engine output to load requirements. Low gears multiply torque for acceleration; high gears reduce engine RPM for efficient highway cruising.', 1),
    mc('A front-wheel drive (FWD) vehicle differs from rear-wheel drive (RWD) in that FWD:', ['Provides better traction for towing and high-performance driving', 'Combines the drive and steering functions in the front wheels, improving fuel efficiency but reducing performance handling', 'Always has a center differential to distribute power', 'Requires a driveshaft running the length of the vehicle'], 'Combines the drive and steering functions in the front wheels, improving fuel efficiency but reducing performance handling', 'FWD eliminates the driveshaft and rear differential, saving weight and allowing lower floor height. The front wheels both steer and drive — CV joints allow power delivery through steering angles. FWD understeers; RWD oversteers.', 2),
    mc('A CV (constant velocity) joint in a front-wheel drive axle serves what purpose?', ['To provide variable gear ratios within the axle for smooth power delivery', 'To transmit power at a constant rotational speed through the range of angles required by suspension movement and steering', 'To act as a flexible coupling that absorbs drivetrain vibration', 'To lock the differential during cornering for better traction'], 'To transmit power at a constant rotational speed through the range of angles required by suspension movement and steering', 'CV joints allow the drive axle to flex through its suspension travel range and steering angles while delivering power at a constant speed — critical for FWD where the front wheels must both steer and be driven simultaneously.', 3),
    mc('The differential in a drive axle allows:', ['The engine to disconnect from the drivetrain at idle', 'The inside and outside wheels to rotate at different speeds while cornering', 'Power to be split equally between front and rear axles', 'The transmission to shift gears without operator input'], 'The inside and outside wheels to rotate at different speeds while cornering', 'When a vehicle turns, the outside wheel travels a longer arc than the inside wheel and must rotate faster. The differential allows this speed difference while maintaining power delivery to both wheels.', 4),
    mc('All-wheel drive (AWD) differs from four-wheel drive (4WD) primarily in that AWD:', ['Uses separate gear ranges (hi/lo) for off-road use', 'Operates continuously and automatically, distributing power variably to all four wheels based on traction conditions', 'Requires driver engagement and is intended for off-road use', 'Only drives two wheels at a time to improve fuel economy'], 'Operates continuously and automatically, distributing power variably to all four wheels based on traction conditions', 'AWD systems are always active, using electronics to detect slipping and redistribute torque automatically. Traditional 4WD requires driver engagement and is designed for off-road conditions — it shouldn\'t be used on dry pavement in low range.', 5),
  ],
  'electrical-systems': [
    mc('What is the purpose of a vehicle\'s alternator?', ['To store electrical energy for starting the engine', 'To generate electricity while the engine runs, charging the battery and powering electrical loads', 'To regulate voltage to prevent damage to sensitive electronics', 'To convert AC power from the engine to DC power for the battery'], 'To generate electricity while the engine runs, charging the battery and powering electrical loads', 'The alternator is driven by the engine via a belt and generates AC electricity, which an internal rectifier converts to DC. It maintains battery charge and powers all vehicle electrical systems while the engine runs.', 1),
    mc('A vehicle\'s battery\'s primary function is to:', ['Power all electrical systems while the engine is running', 'Start the engine by delivering high current to the starter motor, and provide backup power when demand exceeds alternator output', 'Regulate charging voltage from the alternator', 'Store energy from regenerative braking for later use'], 'Start the engine by delivering high current to the starter motor, and provide backup power when demand exceeds alternator output', 'The battery delivers 200-600+ amps to crank the starter. Once running, the alternator takes over and recharges the battery. A battery doesn\'t power the car during operation — the alternator does.', 2),
    mc('CAN bus (Controller Area Network) in modern vehicles is:', ['A physical cable connecting the battery to all electrical loads', 'A communication network allowing vehicle computers (ECUs) to share data without direct wiring between every module', 'A power distribution box that replaces the fuse block', 'A diagnostic port for connecting scan tools'], 'A communication network allowing vehicle computers (ECUs) to share data without direct wiring between every module', 'Modern cars have dozens of ECUs controlling engine, transmission, ABS, airbags, and more. CAN bus lets them share data on a two-wire network. This eliminates thousands of feet of direct wiring and allows modules to coordinate.', 3),
    mc('A fuse in a vehicle\'s electrical system protects:', ['The battery from being overcharged by the alternator', 'The wiring in a circuit from overheating if a fault draws excessive current', 'Individual electrical components from voltage spikes', 'The ECU from receiving incorrect sensor signals'], 'The wiring in a circuit from overheating if a fault draws excessive current', 'Fuses are the weak link in a circuit by design. When a fault (short to ground) causes current to exceed the fuse rating, the fuse element melts and opens the circuit — protecting the wiring from overheating and starting a fire.', 4),
    mc('When diagnosing an electrical fault using a multimeter, voltage drop testing is used to find:', ['The total resistance of the circuit', 'Excessive resistance in conductors or connections that is causing voltage loss and current restriction', 'Whether a fuse is blown or intact', 'The amperage being drawn by a specific component'], 'Excessive resistance in conductors or connections that is causing voltage loss and current restriction', 'Voltage drop testing measures voltage lost across a section of circuit under load. More than 0.1-0.2V drop across a connection or wire indicates excess resistance from corrosion, loose terminals, or undersized conductors.', 5),
  ],
  'brakes-and-suspension': [
    mc('Disc brakes convert kinetic energy to heat by:', ['Pressing brake pads against a rotating rotor using hydraulic pressure', 'Expanding brake shoes against the inside of a drum', 'Using electromagnetic resistance to slow the wheel', 'Applying friction to the outer surface of the tire'], 'Pressing brake pads against a rotating rotor using hydraulic pressure', 'Hydraulic pressure from the master cylinder actuates calipers that squeeze pads against the rotor. Friction converts vehicle kinetic energy to heat. The rotor and pads must dissipate this heat.', 1),
    mc('ABS (Anti-lock Braking System) prevents skidding by:', ['Increasing braking force beyond the driver\'s pedal input', 'Rapidly modulating brake pressure to keep wheels rotating at the threshold of slipping rather than locking completely', 'Automatically steering the vehicle in the braking direction', 'Distributing brake force evenly to all four wheels regardless of load'], 'Rapidly modulating brake pressure to keep wheels rotating at the threshold of slipping rather than locking completely', 'ABS sensors detect wheel lockup and release/reapply brake pressure up to 15 times per second. Rotating wheels provide steering control. Locked wheels produce the worst stopping distance and eliminate steering.', 2),
    mc('A strut-type suspension (MacPherson strut) combines the functions of:', ['The wheel bearing and steering knuckle', 'A shock absorber and a structural suspension component in one unit', 'The coil spring and anti-roll bar', 'The control arm and steering tie rod'], 'A shock absorber and a structural suspension component in one unit', 'A MacPherson strut is a telescoping shock absorber that also acts as the upper suspension pivot point. The coil spring usually surrounds the strut. It is compact and cost-effective — common in front suspensions.', 3),
    mc('Brake fluid absorbs moisture over time. This is a problem because:', ['Moisture increases brake fluid viscosity, making pedal feel spongy', 'Water in the fluid dramatically lowers its boiling point, causing vapor lock and brake fade under heavy use', 'Moisture causes the ABS system to report false sensor errors', 'Water in brake fluid expands and prevents the pistons from retracting after braking'], 'Water in the fluid dramatically lowers its boiling point, causing vapor lock and brake fade under heavy use', 'Fresh DOT3 fluid boils above 400°F. Fluid with 3% water boils at ~300°F. Under hard braking, fluid in the caliper can boil, creating compressible vapor bubbles — causing a spongy pedal or complete brake fade. Flush every 2-3 years.', 4),
    mc('Wheel alignment (camber, toe, caster) primarily affects:', ['The engine\'s ability to maintain proper air/fuel ratio at various speeds', 'Tire wear, vehicle handling, and straight-line tracking', 'Suspension ride height and spring rate', 'Brake bias between front and rear wheels'], 'Tire wear, vehicle handling, and straight-line tracking', 'Misalignment causes rapid, uneven tire wear. Incorrect toe (tires pointed in or out) causes tire scrubbing. Incorrect camber (tilt) causes edge wear. Caster affects straight-line stability and steering returnability.', 5),
  ],
  'mig-welding': [
    mc('MIG (GMAW) welding uses a continuously fed wire electrode and what type of shielding?', ['Flux coating on the wire that burns to create shielding gas', 'A flow of shielding gas (argon, CO2, or a mix) from a separate gas cylinder', 'A flux core built into the hollow wire electrode', 'No shielding — MIG is used only on stainless steel that is self-shielding'], 'A flow of shielding gas (argon, CO2, or a mix) from a separate gas cylinder', 'Standard MIG (solid wire GMAW) uses external gas — typically 75% Argon/25% CO2 (C25) for mild steel. The gas shields the molten puddle from atmospheric oxygen and nitrogen, preventing porosity and contamination.', 1),
    mc('Wire feed speed in MIG welding primarily controls:', ['The depth of penetration into the base metal', 'The welding current (amperage), since the machine is voltage-preset and adjusts current to maintain it', 'The shielding gas flow rate', 'The travel speed required to maintain a consistent bead'], 'The welding current (amperage), since the machine is voltage-preset and adjusts current to maintain it', 'MIG machines are constant-voltage. The machine varies current to maintain set voltage. Wire feed speed determines how much wire enters the arc — more wire requires more current to melt it. Wire speed = amperage control.', 2),
    mc('The correct angle to hold a MIG gun during a weld pass is approximately:', ['Perfectly perpendicular to the work surface', '10-15 degrees in the direction of travel (push or drag) and 90 degrees to the joint sides', '45 degrees to the work surface for maximum penetration', '30-45 degrees dragging away from the weld for deep penetration'], '10-15 degrees in the direction of travel (push or drag) and 90 degrees to the joint sides', 'Gun angle affects bead shape and penetration. Pushing (gun angled 10-15° in travel direction) gives a flatter, wider bead with less penetration. Dragging gives a narrower bead with more penetration. Extreme angles cause porosity and poor fusion.', 3),
    mc('What does a "proper MIG weld" sound like during the welding process?', ['A loud popping and crackling sound indicating deep penetration', 'A steady, consistent crackling like bacon frying — no large pops or sputtering', 'Complete silence — noise indicates incorrect settings', 'A high-pitched hissing from the shielding gas overriding arc noise'], 'A steady, consistent crackling like bacon frying — no large pops or sputtering', 'The "frying bacon" sound indicates stable arc and proper wire speed. Loud irregular popping indicates wire speed too high or voltage too low. A hissing sound may indicate insufficient wire speed or voltage too high.', 4),
    mc('Before welding on any metal, proper preparation includes:', ['Preheating all metal to the same temperature to prevent warping', 'Cleaning the weld area of rust, paint, oil, and mill scale to bare metal', 'Tacking the pieces together with standard hardware store fasteners', 'Sandblasting only — other methods leave surface contaminants'], 'Cleaning the weld area of rust, paint, oil, and mill scale to bare metal', 'Contamination causes porosity, incomplete fusion, and weak welds. Grind or wire-brush the area to bare metal. Paint releases toxic gases when burned. Mill scale on new steel requires grinding for proper fusion.', 5),
  ],
}
