import { Pool } from 'pg'
import { PrismaPg } from '@prisma/adapter-pg'
import { PrismaClient } from '@prisma/client'

const pool = new Pool({ connectionString: process.env.DATABASE_URL })
const adapter = new PrismaPg(pool)
const db = new PrismaClient({ adapter })

type L = [string, string] // [slug, name]
type CourseDef = { slug: string; name: string; desc: string; hours: number; lessons: L[] }
type SubjectDef = { slug: string; name: string; desc: string; icon: string; order: number; courses: CourseDef[] }

const CATALOG: SubjectDef[] = [
  {
    slug: 'arts-and-creative-skills', name: 'Arts & Creative Skills',
    desc: 'Drawing, design, photography, music, and the creative process — practical skills for making things that matter.',
    icon: '🎨', order: 1,
    courses: [
      { slug: 'creative-process', name: 'The Creative Process', desc: 'Where ideas come from, how to develop them, and how to keep making things when inspiration runs out.', hours: 2, lessons: [
        ['what-is-creativity', 'What Is Creativity?'],
        ['idea-generation', 'Idea Generation'],
        ['habit-and-routine', 'Habit and Routine'],
        ['creative-blocks', 'Creative Blocks'],
        ['feedback-and-critique', 'Feedback and Critique'],
        ['sharing-your-work', 'Sharing Your Work'],
      ]},
      { slug: 'drawing', name: 'Drawing Fundamentals', desc: 'Learn to see and draw — from basic shapes through light, shadow, and perspective.', hours: 3, lessons: [
        ['learning-to-see', 'Learning to See'],
        ['basic-forms', 'Basic Forms'],
        ['contour-drawing', 'Contour Drawing'],
        ['gesture-drawing', 'Gesture Drawing'],
        ['perspective', 'Perspective'],
        ['shading-and-light', 'Shading and Light'],
        ['drawing-from-observation', 'Drawing from Observation'],
      ]},
      { slug: 'graphic-design', name: 'Graphic Design', desc: 'Typography, color, layout, and the principles behind design that communicates.', hours: 3, lessons: [
        ['typography', 'Typography'],
        ['color-in-design', 'Color in Design'],
        ['layout-and-grid', 'Layout and Grid'],
        ['logo-design', 'Logo Design'],
        ['design-tools-overview', 'Design Tools Overview'],
        ['print-vs-digital', 'Print vs. Digital'],
        ['social-media-graphics', 'Social Media Graphics'],
      ]},
      { slug: 'music-fundamentals', name: 'Music Fundamentals', desc: 'Pitch, rhythm, scales, chords, and how to read and understand music.', hours: 3, lessons: [
        ['sound-and-pitch', 'Sound and Pitch'],
        ['rhythm-and-meter', 'Rhythm and Meter'],
        ['time-signatures', 'Time Signatures'],
        ['scales-and-keys', 'Scales and Keys'],
        ['chords-and-harmony', 'Chords and Harmony'],
        ['reading-notation', 'Reading Notation'],
        ['ear-training', 'Ear Training'],
      ]},
      { slug: 'photography', name: 'Photography', desc: 'How cameras work, how to use light, and how to compose a shot that says something.', hours: 3, lessons: [
        ['how-cameras-work', 'How Cameras Work'],
        ['exposure-triangle', 'The Exposure Triangle'],
        ['light-in-photography', 'Light in Photography'],
        ['photo-composition', 'Photo Composition'],
        ['focus-and-depth', 'Focus and Depth of Field'],
        ['editing-basics', 'Editing Basics'],
        ['finding-your-eye', 'Finding Your Eye'],
      ]},
      { slug: 'visual-art-fundamentals', name: 'Visual Art Fundamentals', desc: 'The principles of design that underlie all visual art — color, composition, contrast, and more.', hours: 3, lessons: [
        ['line-and-shape', 'Line and Shape'],
        ['value-and-contrast', 'Value and Contrast'],
        ['color-theory', 'Color Theory'],
        ['texture-and-space', 'Texture and Space'],
        ['composition', 'Composition'],
        ['balance-and-rhythm', 'Balance and Rhythm'],
        ['unity-and-variety', 'Unity and Variety'],
      ]},
    ],
  },
  {
    slug: 'business', name: 'Business & Entrepreneurship',
    desc: 'Everything you need to start, run, and grow a business — from legal structures to cash flow to your first customer.',
    icon: '🏢', order: 2,
    courses: [
      { slug: 'business-foundations', name: 'Business Foundations', desc: 'What a business is, how to structure it legally, and how to get started without the mistakes that kill most new ventures.', hours: 3, lessons: [
        ['defining-a-business', 'Defining a Business'],
        ['business-structures', 'Business Structures: LLC, Sole Prop, and More'],
        ['what-a-business-plan-actually-is', 'What a Business Plan Actually Is'],
        ['defining-your-customer', 'Defining Your Customer'],
        ['revenue-models', 'Revenue Models'],
        ['separating-finances', 'Separating Your Finances'],
      ]},
      { slug: 'hiring-and-people', name: 'Hiring & People', desc: 'When and how to hire, onboard, pay, and part ways with employees and contractors.', hours: 2, lessons: [
        ['when-to-hire', 'When to Hire'],
        ['contractor-vs-employee', 'Contractor vs. Employee'],
        ['finding-good-people', 'Finding Good People'],
        ['onboarding', 'Onboarding'],
        ['payroll-basics', 'Payroll Basics'],
        ['letting-someone-go', 'Letting Someone Go'],
      ]},
      { slug: 'legal-basics', name: 'Legal Basics for Business', desc: 'Contracts, intellectual property, and knowing when you need a lawyer.', hours: 2, lessons: [
        ['what-makes-a-contract', 'What Makes a Contract'],
        ['reading-contracts', 'Reading Contracts'],
        ['common-contract-mistakes', 'Common Contract Mistakes'],
        ['copyright-basics', 'Copyright Basics'],
        ['trademarks', 'Trademarks'],
        ['when-to-get-a-lawyer', 'When to Get a Lawyer'],
      ]},
      { slug: 'operations-and-finance', name: 'Operations & Finance', desc: 'Cash flow, pricing, bookkeeping, and the numbers that actually run a business.', hours: 4, lessons: [
        ['what-cash-flow-is', 'What Cash Flow Is'],
        ['reading-a-pl', 'Reading a P&L'],
        ['what-to-track', 'What to Track'],
        ['bookkeeping-tools', 'Bookkeeping Tools'],
        ['working-with-accountant', 'Working with an Accountant'],
        ['cost-based-pricing', 'Cost-Based Pricing'],
        ['value-based-pricing', 'Value-Based Pricing'],
        ['pricing-mistakes', 'Pricing Mistakes'],
        ['invoicing-and-getting-paid', 'Invoicing and Getting Paid'],
      ]},
      { slug: 'sales-and-marketing', name: 'Sales & Marketing', desc: 'Finding customers, making the ask, and building word-of-mouth that scales.', hours: 3, lessons: [
        ['your-first-customer', 'Your First Customer'],
        ['ideal-customer-profile', 'Ideal Customer Profile'],
        ['where-customers-are', 'Where Customers Are'],
        ['word-of-mouth', 'Word of Mouth'],
        ['online-presence', 'Online Presence'],
        ['social-media-basics', 'Social Media Basics'],
        ['making-the-ask', 'Making the Ask'],
        ['handling-objections', 'Handling Objections'],
        ['follow-up', 'Follow-Up'],
      ]},
      { slug: 'taxes-for-business', name: 'Taxes for Business', desc: 'Self-employment taxes, quarterly estimates, deductions, and when to get help.', hours: 2, lessons: [
        ['self-employment-tax', 'Self-Employment Tax'],
        ['quarterly-estimates', 'Quarterly Estimates'],
        ['business-deductions', 'Business Deductions'],
        ['tax-planning-basics', 'Tax Planning Basics'],
        ['retirement-accounts', 'Retirement Accounts for Business Owners'],
        ['hiring-tax-help', 'When to Hire Tax Help'],
      ]},
    ],
  },
  {
    slug: 'economics', name: 'Economics',
    desc: 'How economies work — from individual decisions to global trade, markets, and government policy.',
    icon: '📊', order: 3,
    courses: [
      { slug: 'behavioral-economics', name: 'Behavioral Economics', desc: "Why people don't behave rationally, and what that means for markets and policy.", hours: 3, lessons: [
        ['rationality-and-its-limits', 'Rationality and Its Limits'],
        ['loss-aversion', 'Loss Aversion'],
        ['heuristics', 'Heuristics'],
        ['anchoring-and-adjustment', 'Anchoring and Adjustment'],
        ['overconfidence-bias', 'Overconfidence Bias'],
        ['sunk-cost-fallacy', 'The Sunk Cost Fallacy'],
        ['nudges', 'Nudges'],
      ]},
      { slug: 'business-economics', name: 'Business Economics', desc: 'Cost structures, market power, competition, and how firms make decisions.', hours: 3, lessons: [
        ['types-of-costs', 'Types of Costs'],
        ['production-decisions', 'Production Decisions'],
        ['perfect-competition', 'Perfect Competition'],
        ['monopoly', 'Monopoly'],
        ['oligopoly-and-monopolistic', 'Oligopoly and Monopolistic Competition'],
        ['economies-of-scale', 'Economies of Scale'],
        ['antitrust', 'Antitrust'],
      ]},
      { slug: 'economic-thinking', name: 'Economic Thinking', desc: 'The core concepts economists use to understand the world — scarcity, incentives, supply and demand.', hours: 3, lessons: [
        ['scarcity-and-choice', 'Scarcity and Choice'],
        ['marginal-thinking', 'Marginal Thinking'],
        ['supply-and-demand', 'Supply and Demand'],
        ['price-mechanism', 'The Price Mechanism'],
        ['elasticity', 'Elasticity'],
        ['market-failures', 'Market Failures'],
        ['economic-systems', 'Economic Systems'],
      ]},
      { slug: 'global-economics', name: 'Global Economics', desc: 'Trade, exchange rates, development, and how the world economy fits together.', hours: 3, lessons: [
        ['why-countries-trade', 'Why Countries Trade'],
        ['tariffs-and-trade-barriers', 'Tariffs and Trade Barriers'],
        ['trade-deficits', 'Trade Deficits'],
        ['exchange-rates', 'Exchange Rates'],
        ['globalization-tradeoffs', 'Globalization: Tradeoffs'],
        ['imf-and-world-bank', 'The IMF and World Bank'],
        ['economic-development', 'Economic Development'],
      ]},
      { slug: 'macroeconomics', name: 'Macroeconomics', desc: 'GDP, inflation, unemployment, business cycles, and the tools governments use to manage them.', hours: 4, lessons: [
        ['gdp', 'GDP'],
        ['inflation', 'Inflation'],
        ['unemployment', 'Unemployment'],
        ['business-cycles', 'Business Cycles'],
        ['fiscal-policy', 'Fiscal Policy'],
        ['monetary-policy', 'Monetary Policy'],
        ['national-debt', 'The National Debt'],
        ['economic-schools', 'Schools of Economic Thought'],
      ]},
    ],
  },
  {
    slug: 'health-and-wellness', name: 'Health & Wellness',
    desc: 'The human body, nutrition, fitness, mental health, and how to navigate the healthcare system.',
    icon: '💊', order: 4,
    courses: [
      { slug: 'first-aid-and-emergency-response', name: 'First Aid & Emergency Response', desc: 'CPR, bleeding, choking, burns, and what to do in a medical emergency.', hours: 3, lessons: [
        ['calling-for-help', 'Calling for Help'],
        ['assessing-an-emergency', 'Assessing an Emergency'],
        ['cpr-basics', 'CPR Basics'],
        ['aed-use', 'AED Use'],
        ['choking', 'Choking'],
        ['bleeding-and-wounds', 'Bleeding and Wounds'],
        ['burns-and-injuries', 'Burns and Injuries'],
        ['overdose-and-poisoning', 'Overdose and Poisoning'],
      ]},
      { slug: 'fitness-and-exercise', name: 'Fitness & Exercise', desc: 'How to build a workout routine that works — with or without a gym.', hours: 2, lessons: [
        ['why-exercise-matters', 'Why Exercise Matters'],
        ['cardio-vs-strength', 'Cardio vs. Strength Training'],
        ['progressive-overload', 'Progressive Overload'],
        ['designing-a-workout-plan', 'Designing a Workout Plan'],
        ['recovery-and-rest', 'Recovery and Rest'],
        ['exercise-without-a-gym', 'Exercise Without a Gym'],
      ]},
      { slug: 'human-body', name: 'The Human Body', desc: 'How your major body systems work, from cells to organs to homeostasis.', hours: 4, lessons: [
        ['cell-basics', 'Cell Basics'],
        ['cell-processes', 'Cell Processes'],
        ['tissues-and-organs', 'Tissues and Organs'],
        ['homeostasis', 'Homeostasis'],
        ['musculoskeletal-system', 'The Musculoskeletal System'],
        ['cardiovascular-system', 'The Cardiovascular System'],
        ['respiratory-system', 'The Respiratory System'],
        ['digestive-system', 'The Digestive System'],
        ['nervous-system', 'The Nervous System'],
        ['immune-system', 'The Immune System'],
      ]},
      { slug: 'mental-health-fundamentals', name: 'Mental Health Fundamentals', desc: 'Understanding mental health, common conditions, stigma, and how to get support.', hours: 3, lessons: [
        ['what-is-mental-health', 'What Is Mental Health?'],
        ['anxiety-and-depression', 'Anxiety and Depression'],
        ['trauma-and-stress', 'Trauma and Stress'],
        ['sleep-and-mental-health', 'Sleep and Mental Health'],
        ['self-care-that-works', 'Self-Care That Works'],
        ['mental-health-stigma', 'Mental Health Stigma'],
        ['helping-someone-else', 'Helping Someone Else'],
        ['getting-professional-help', 'Getting Professional Help'],
      ]},
      { slug: 'navigating-healthcare', name: 'Navigating Healthcare', desc: 'Understanding insurance, medical records, prescriptions, and how to be your own advocate.', hours: 2, lessons: [
        ['understanding-your-insurance', 'Understanding Your Insurance'],
        ['primary-care-and-specialists', 'Primary Care and Specialists'],
        ['medical-billing', 'Medical Billing'],
        ['medical-records', 'Medical Records'],
        ['prescriptions-and-medications', 'Prescriptions and Medications'],
        ['second-opinions', 'Second Opinions'],
      ]},
      { slug: 'nutrition-and-diet', name: 'Nutrition & Diet', desc: 'Macros, micros, food labels, and what a healthy diet actually looks like.', hours: 3, lessons: [
        ['what-a-healthy-diet-looks-like', 'What a Healthy Diet Looks Like'],
        ['macronutrients', 'Macronutrients'],
        ['micronutrients', 'Micronutrients'],
        ['calories-and-energy', 'Calories and Energy'],
        ['reading-food-labels', 'Reading Food Labels'],
        ['common-diet-myths', 'Common Diet Myths'],
        ['eating-on-a-budget', 'Eating on a Budget'],
        ['special-dietary-needs', 'Special Dietary Needs'],
      ]},
    ],
  },
  {
    slug: 'history-and-civics', name: 'History & Civics',
    desc: 'How governments work, how we got here, and how to think critically about media and information.',
    icon: '🏛️', order: 5,
    courses: [
      { slug: 'how-government-works', name: 'How Government Works', desc: 'The Constitution, three branches, checks and balances, and how laws get made.', hours: 3, lessons: [
        ['the-constitution', 'The Constitution'],
        ['three-branches', 'The Three Branches'],
        ['checks-and-balances', 'Checks and Balances'],
        ['federalism', 'Federalism'],
        ['congress-and-legislation', 'Congress and Legislation'],
        ['the-courts', 'The Courts'],
        ['voting-and-elections', 'Voting and Elections'],
      ]},
      { slug: 'media-literacy', name: 'Media Literacy', desc: 'How to evaluate sources, spot misinformation, and form your own views.', hours: 2, lessons: [
        ['how-media-works', 'How Media Works'],
        ['identifying-bias', 'Identifying Bias'],
        ['spotting-misinformation', 'Spotting Misinformation'],
        ['evaluating-sources', 'Evaluating Sources'],
        ['logical-fallacies', 'Logical Fallacies'],
        ['forming-your-own-views', 'Forming Your Own Views'],
      ]},
      { slug: 'us-history-foundations', name: 'U.S. History: Foundations', desc: 'Colonization through Reconstruction — the founding and early struggles of the United States.', hours: 4, lessons: [
        ['colonization', 'Colonization'],
        ['causes-of-revolution', 'Causes of Revolution'],
        ['revolution-and-founding', 'Revolution and Founding'],
        ['early-republic', 'The Early Republic'],
        ['westward-expansion', 'Westward Expansion'],
        ['slavery-and-sectional-crisis', 'Slavery and Sectional Crisis'],
        ['civil-war', 'The Civil War'],
        ['reconstruction', 'Reconstruction'],
      ]},
      { slug: 'us-history-modern', name: 'U.S. History: Modern', desc: 'The Gilded Age through the 21st century — industrialization, war, civil rights, and change.', hours: 4, lessons: [
        ['gilded-age-and-progressive-era', 'The Gilded Age and Progressive Era'],
        ['world-war-one', 'World War I'],
        ['great-depression', 'The Great Depression'],
        ['world-war-two', 'World War II'],
        ['cold-war', 'The Cold War'],
        ['civil-rights-movement', 'The Civil Rights Movement'],
        ['social-change-in-the-sixties', 'Social Change in the Sixties'],
        ['america-in-the-21st-century', 'America in the 21st Century'],
      ]},
      { slug: 'world-history-ancient', name: 'World History: Ancient', desc: 'From the first civilizations through the Mongol Empire — the ancient and medieval world.', hours: 4, lessons: [
        ['first-civilizations', 'First Civilizations'],
        ['ancient-greece', 'Ancient Greece'],
        ['ancient-rome', 'Ancient Rome'],
        ['ancient-asia', 'Ancient Asia'],
        ['fall-of-rome-and-middle-ages', 'The Fall of Rome and the Middle Ages'],
        ['feudalism-and-crusades', 'Feudalism and the Crusades'],
        ['islam-and-the-caliphates', 'Islam and the Caliphates'],
        ['mongol-empire', 'The Mongol Empire'],
      ]},
      { slug: 'world-history-modern', name: 'World History: Modern', desc: 'The Renaissance through globalization — how the modern world was made.', hours: 4, lessons: [
        ['renaissance-and-reformation', 'The Renaissance and Reformation'],
        ['age-of-exploration', 'The Age of Exploration'],
        ['scientific-revolution', 'The Scientific Revolution'],
        ['atlantic-revolutions', 'The Atlantic Revolutions'],
        ['industrialization-and-imperialism', 'Industrialization and Imperialism'],
        ['world-wars', 'The World Wars'],
        ['decolonization', 'Decolonization'],
        ['globalization', 'Globalization'],
      ]},
    ],
  },
  {
    slug: 'language-and-writing', name: 'Language & Writing',
    desc: 'Grammar, essay writing, creative writing, and the practical communication skills that matter in every area of life.',
    icon: '✍️', order: 6,
    courses: [
      { slug: 'creative-writing', name: 'Creative Writing', desc: 'Story structure, character, dialogue, and the fundamentals of fiction and personal essay.', hours: 4, lessons: [
        ['story-structure', 'Story Structure'],
        ['character', 'Character'],
        ['setting-and-scene', 'Setting and Scene'],
        ['dialogue', 'Dialogue'],
        ['short-fiction', 'Short Fiction'],
        ['poetry-basics', 'Poetry Basics'],
        ['personal-essay', 'Personal Essay'],
        ['finding-your-voice', 'Finding Your Voice'],
      ]},
      { slug: 'essay-writing', name: 'Essay Writing', desc: 'Argumentative, expository, narrative, and descriptive essays — from thesis to final draft.', hours: 4, lessons: [
        ['argumentative-essays', 'Argumentative Essays'],
        ['expository-essays', 'Expository Essays'],
        ['narrative-essays', 'Narrative Essays'],
        ['descriptive-essays', 'Descriptive Essays'],
        ['finding-sources', 'Finding Sources'],
        ['using-evidence', 'Using Evidence'],
        ['citations', 'Citations'],
      ]},
      { slug: 'grammar-and-mechanics', name: 'Grammar & Mechanics', desc: 'Parts of speech, sentence structure, punctuation, and the most common errors in writing.', hours: 3, lessons: [
        ['parts-of-speech', 'Parts of Speech'],
        ['sentence-structure', 'Sentence Structure'],
        ['subject-verb-agreement', 'Subject-Verb Agreement'],
        ['commas', 'Commas'],
        ['apostrophes', 'Apostrophes'],
        ['capitalization', 'Capitalization'],
        ['fragments-and-run-ons', 'Fragments and Run-Ons'],
        ['common-errors', 'Common Errors'],
      ]},
      { slug: 'practical-writing', name: 'Practical Writing', desc: 'Email, resumes, reports, persuasive writing, and clear communication for real-world contexts.', hours: 3, lessons: [
        ['writing-with-clarity', 'Writing with Clarity'],
        ['professional-email', 'Professional Email'],
        ['persuasive-writing', 'Persuasive Writing'],
        ['reports-and-memos', 'Reports and Memos'],
        ['resumes-and-cover-letters', 'Résumés and Cover Letters'],
        ['writing-for-the-web', 'Writing for the Web'],
      ]},
      { slug: 'reading-comprehension', name: 'Reading Comprehension', desc: 'Active reading, main ideas, inference, author\'s purpose, and evaluating arguments.', hours: 3, lessons: [
        ['before-you-read', 'Before You Read'],
        ['reading-actively', 'Reading Actively'],
        ['main-idea-and-detail', 'Main Idea and Detail'],
        ['inference-and-implication', 'Inference and Implication'],
        ['authors-purpose', "Author's Purpose"],
        ['tone-and-voice', 'Tone and Voice'],
        ['evaluating-arguments', 'Evaluating Arguments'],
      ]},
      { slug: 'writing-fundamentals', name: 'Writing Fundamentals', desc: 'The paragraph, brainstorming, drafting, revising, and editing — the full writing process.', hours: 3, lessons: [
        ['brainstorming', 'Brainstorming'],
        ['the-paragraph', 'The Paragraph'],
        ['drafting', 'Drafting'],
        ['revising', 'Revising'],
        ['editing-and-proofreading', 'Editing and Proofreading'],
        ['introductions-and-conclusions', 'Introductions and Conclusions'],
        ['transitions', 'Transitions'],
      ]},
    ],
  },
  {
    slug: 'law-and-legal-rights', name: 'Law & Legal Rights',
    desc: 'Contracts, tenant rights, employment law, criminal law, and the rights every person should know.',
    icon: '⚖️', order: 7,
    courses: [
      { slug: 'contracts-and-agreements', name: 'Contracts & Agreements', desc: 'What makes a contract, how to read one, and how to protect yourself.', hours: 3, lessons: [
        ['what-makes-a-contract', 'What Makes a Contract'],
        ['verbal-vs-written', 'Verbal vs. Written Contracts'],
        ['key-clauses-to-find', 'Key Clauses to Find'],
        ['fine-print-tactics', 'Fine Print Tactics'],
        ['terms-of-service', 'Terms of Service'],
        ['service-agreements', 'Service Agreements'],
        ['employment-contracts', 'Employment Contracts'],
        ['negotiating-terms', 'Negotiating Terms'],
        ['when-contracts-are-void', 'When Contracts Are Void'],
      ]},
      { slug: 'criminal-law-basics', name: 'Criminal Law Basics', desc: 'The criminal justice process from arrest to trial, your rights, and how it all works.', hours: 2, lessons: [
        ['crimes-and-classifications', 'Crimes and Classifications'],
        ['from-arrest-to-trial', 'From Arrest to Trial'],
        ['right-to-counsel', 'Right to Counsel'],
        ['bail-and-pretrial', 'Bail and Pretrial'],
        ['plea-deals', 'Plea Deals'],
        ['criminal-records', 'Criminal Records'],
      ]},
      { slug: 'employment-law', name: 'Employment Law', desc: 'Your rights as a worker — wages, safety, discrimination, and what to do when they are violated.', hours: 4, lessons: [
        ['at-will-employment', 'At-Will Employment'],
        ['employee-vs-contractor', 'Employee vs. Contractor'],
        ['minimum-wage-and-overtime', 'Minimum Wage and Overtime'],
        ['workplace-harassment', 'Workplace Harassment'],
        ['protected-classes', 'Protected Classes'],
        ['osha-basics', 'OSHA Basics'],
        ['workers-compensation', "Workers' Compensation"],
        ['fmla', 'FMLA'],
        ['unemployment-insurance', 'Unemployment Insurance'],
        ['filing-a-complaint', 'Filing a Complaint'],
      ]},
      { slug: 'family-law-basics', name: 'Family Law Basics', desc: 'Marriage, divorce, custody, child support, wills, and the legal side of family life.', hours: 3, lessons: [
        ['legal-aspects-of-marriage', 'Legal Aspects of Marriage'],
        ['prenuptial-agreements', 'Prenuptial Agreements'],
        ['divorce-process', 'The Divorce Process'],
        ['property-division', 'Property Division'],
        ['child-custody', 'Child Custody'],
        ['child-support', 'Child Support'],
        ['wills-basics', 'Wills Basics'],
        ['dying-without-a-will', 'Dying Without a Will'],
      ]},
      { slug: 'know-your-rights', name: 'Know Your Rights', desc: 'The Bill of Rights and the constitutional protections every person has against government power.', hours: 4, lessons: [
        ['bill-of-rights', 'The Bill of Rights'],
        ['first-amendment', 'The First Amendment'],
        ['fourth-amendment', 'The Fourth Amendment'],
        ['fifth-amendment', 'The Fifth Amendment'],
        ['due-process', 'Due Process'],
        ['equal-protection', 'Equal Protection'],
        ['civil-vs-criminal', 'Civil vs. Criminal Law'],
        ['being-stopped-by-police', 'Being Stopped by Police'],
        ['consent-to-search', 'Consent to Search'],
        ['if-you-are-arrested', 'If You Are Arrested'],
      ]},
      { slug: 'tenant-and-housing-rights', name: 'Tenant & Housing Rights', desc: 'Leases, security deposits, habitability, eviction, and the rights every renter should know.', hours: 3, lessons: [
        ['lease-agreements', 'Lease Agreements'],
        ['security-deposits', 'Security Deposits'],
        ['habitability-standards', 'Habitability Standards'],
        ['repairs-and-maintenance', 'Repairs and Maintenance'],
        ['landlord-entry', 'Landlord Entry'],
        ['retaliation-protections', 'Retaliation Protections'],
        ['eviction-process', 'The Eviction Process'],
      ]},
    ],
  },
  {
    slug: 'mathematics', name: 'Mathematics',
    desc: 'Arithmetic through calculus — the math that underpins science, finance, engineering, and everyday problem-solving.',
    icon: '📐', order: 8,
    courses: [
      { slug: 'arithmetic', name: 'Arithmetic', desc: 'Numbers, operations, fractions, decimals, percentages, and the foundation of all math.', hours: 4, lessons: [
        ['whole-numbers', 'Whole Numbers'],
        ['addition-and-subtraction', 'Addition and Subtraction'],
        ['multiplication-and-division', 'Multiplication and Division'],
        ['factors-and-multiples', 'Factors and Multiples'],
        ['fractions', 'Fractions'],
        ['decimals', 'Decimals'],
        ['percentages', 'Percentages'],
        ['ratios-and-proportions', 'Ratios and Proportions'],
        ['negative-numbers', 'Negative Numbers'],
        ['order-of-operations', 'Order of Operations'],
        ['estimation', 'Estimation'],
      ]},
      { slug: 'pre-algebra', name: 'Pre-Algebra', desc: 'Variables, expressions, equations, inequalities, and the bridge from arithmetic to algebra.', hours: 3, lessons: [
        ['what-is-a-variable', 'What Is a Variable?'],
        ['writing-expressions', 'Writing Expressions'],
        ['solving-one-step-equations', 'Solving One-Step Equations'],
        ['solving-two-step-equations', 'Solving Two-Step Equations'],
        ['inequalities', 'Inequalities'],
        ['the-coordinate-plane', 'The Coordinate Plane'],
        ['perimeter-and-area', 'Perimeter and Area'],
        ['pythagorean-theorem', 'The Pythagorean Theorem'],
        ['angles-and-triangles', 'Angles and Triangles'],
      ]},
      { slug: 'algebra-i', name: 'Algebra I', desc: 'Linear equations, functions, graphing, systems of equations, and quadratics.', hours: 5, lessons: [
        ['linear-equations', 'Linear Equations'],
        ['linear-inequalities', 'Linear Inequalities'],
        ['slope-and-lines', 'Slope and Lines'],
        ['graphing-linear-functions', 'Graphing Linear Functions'],
        ['systems-of-equations', 'Systems of Equations'],
        ['solving-systems', 'Solving Systems'],
        ['exponents', 'Exponents'],
        ['polynomials', 'Polynomials'],
        ['factoring', 'Factoring'],
        ['quadratic-equations', 'Quadratic Equations'],
        ['functions', 'Functions'],
      ]},
      { slug: 'algebra-ii', name: 'Algebra II', desc: 'Polynomial functions, exponentials, logarithms, rational functions, and trigonometry.', hours: 5, lessons: [
        ['polynomial-functions', 'Polynomial Functions'],
        ['rational-functions', 'Rational Functions'],
        ['radical-functions', 'Radical Functions'],
        ['exponential-and-log', 'Exponential and Logarithmic Functions'],
        ['unit-circle', 'The Unit Circle'],
        ['right-triangle-trig', 'Right Triangle Trigonometry'],
        ['trig-functions-and-graphs', 'Trig Functions and Graphs'],
        ['trig-identities', 'Trig Identities'],
      ]},
      { slug: 'geometry', name: 'Geometry', desc: 'Points, lines, angles, polygons, circles, triangles, and 3D solids.', hours: 4, lessons: [
        ['points-lines-planes', 'Points, Lines, and Planes'],
        ['angles', 'Angles'],
        ['parallel-lines', 'Parallel Lines'],
        ['triangle-properties', 'Triangle Properties'],
        ['similar-triangles', 'Similar Triangles'],
        ['polygons-and-area', 'Polygons and Area'],
        ['circles', 'Circles'],
        ['coordinate-geometry', 'Coordinate Geometry'],
        ['3d-solids', '3D Solids'],
      ]},
      { slug: 'pre-calculus', name: 'Pre-Calculus', desc: 'Limits, sequences, series, and the bridge between algebra and calculus.', hours: 4, lessons: [
        ['sequences', 'Sequences'],
        ['series-and-summation', 'Series and Summation'],
        ['combinatorics', 'Combinatorics'],
        ['what-is-a-limit', 'What Is a Limit?'],
        ['evaluating-limits', 'Evaluating Limits'],
        ['continuity', 'Continuity'],
      ]},
      { slug: 'calculus', name: 'Calculus', desc: 'Derivatives, integrals, the fundamental theorem, and their applications.', hours: 6, lessons: [
        ['the-derivative', 'The Derivative'],
        ['differentiation-rules', 'Differentiation Rules'],
        ['chain-product-quotient', 'Chain, Product, and Quotient Rules'],
        ['applications-of-derivatives', 'Applications of Derivatives'],
        ['the-integral', 'The Integral'],
        ['integration-techniques', 'Integration Techniques'],
        ['fundamental-theorem', 'The Fundamental Theorem of Calculus'],
        ['applications-of-integrals', 'Applications of Integrals'],
      ]},
      { slug: 'statistics', name: 'Statistics', desc: 'Data, distributions, probability, hypothesis testing, and how to reason with numbers.', hours: 4, lessons: [
        ['collecting-data', 'Collecting Data'],
        ['measures-of-center', 'Measures of Center'],
        ['distributions-and-spread', 'Distributions and Spread'],
        ['data-visualization', 'Data Visualization'],
        ['probability-basics', 'Probability Basics'],
        ['probability-rules', 'Probability Rules'],
        ['sampling-and-inference', 'Sampling and Inference'],
        ['hypothesis-testing', 'Hypothesis Testing'],
      ]},
    ],
  },
  {
    slug: 'personal-finance', name: 'Personal Finance',
    desc: 'Budgeting, banking, credit, investing, insurance, taxes, and buying a home — the money skills that actually matter.',
    icon: '💰', order: 9,
    courses: [
      { slug: 'banking-and-accounts', name: 'Banking & Accounts', desc: 'Checking, savings, interest rates, FDIC insurance, and how banks make money.', hours: 2, lessons: [
        ['choosing-a-bank', 'Choosing a Bank'],
        ['checking-vs-savings', 'Checking vs. Savings'],
        ['interest-rates', 'Interest Rates'],
        ['how-banks-make-money', 'How Banks Make Money'],
        ['fdic-insurance', 'FDIC Insurance'],
        ['cds-and-money-market', 'CDs and Money Market Accounts'],
      ]},
      { slug: 'budgeting-and-managing-money', name: 'Budgeting & Managing Money', desc: 'How to track spending, build an emergency fund, and take control of your money.', hours: 4, lessons: [
        ['where-does-money-come-from', 'Where Does Money Come From?'],
        ['tracking-spending', 'Tracking Spending'],
        ['fixed-vs-variable-expenses', 'Fixed vs. Variable Expenses'],
        ['the-fifty-thirty-twenty-rule', 'The 50/30/20 Rule'],
        ['zero-based-budgeting', 'Zero-Based Budgeting'],
        ['budgeting-methods', 'Budgeting Methods'],
        ['budgeting-tools', 'Budgeting Tools'],
        ['why-emergency-funds-matter', 'Why Emergency Funds Matter'],
        ['building-the-fund', 'Building the Fund'],
        ['how-much-to-save', 'How Much to Save'],
      ]},
      { slug: 'buying-a-home', name: 'Buying a Home', desc: 'Mortgages, down payments, the buying process, and whether homeownership is right for you.', hours: 4, lessons: [
        ['are-you-ready-to-buy', 'Are You Ready to Buy?'],
        ['when-renting-wins', 'When Renting Wins'],
        ['how-mortgages-work', 'How Mortgages Work'],
        ['mortgage-types', 'Mortgage Types'],
        ['down-payments-and-pmi', 'Down Payments and PMI'],
        ['getting-approved', 'Getting Approved'],
        ['finding-a-home', 'Finding a Home'],
        ['making-an-offer', 'Making an Offer'],
        ['closing-costs', 'Closing Costs'],
        ['the-real-cost-of-homeownership', 'The Real Cost of Homeownership'],
      ]},
      { slug: 'debt-and-credit', name: 'Debt & Credit', desc: 'Credit scores, credit cards, student loans, debt payoff strategies, and predatory lending.', hours: 5, lessons: [
        ['what-is-credit', 'What Is Credit?'],
        ['how-credit-scores-work', 'How Credit Scores Work'],
        ['credit-reports', 'Credit Reports'],
        ['building-credit-from-zero', 'Building Credit from Zero'],
        ['credit-cards', 'Credit Cards'],
        ['good-debt-vs-bad-debt', 'Good Debt vs. Bad Debt'],
        ['student-loans', 'Student Loans'],
        ['predatory-lending', 'Predatory Lending'],
        ['debt-avalanche-vs-snowball', 'Debt Avalanche vs. Snowball'],
        ['debt-consolidation', 'Debt Consolidation'],
        ['negotiating-with-creditors', 'Negotiating with Creditors'],
      ]},
      { slug: 'insurance-fundamentals', name: 'Insurance Fundamentals', desc: 'How insurance works, the types you need, and how to avoid being underinsured.', hours: 3, lessons: [
        ['why-insurance-matters', 'Why Insurance Matters'],
        ['insurance-basics', 'Insurance Basics'],
        ['health-insurance', 'Health Insurance'],
        ['auto-insurance', 'Auto Insurance'],
        ['renters-and-homeowners', 'Renters and Homeowners Insurance'],
        ['life-insurance', 'Life Insurance'],
        ['disability-insurance', 'Disability Insurance'],
      ]},
      { slug: 'investing-basics', name: 'Investing Basics', desc: 'Compound interest, stocks, bonds, index funds, risk, and how to start investing.', hours: 4, lessons: [
        ['compound-interest', 'Compound Interest'],
        ['inflation-and-purchasing-power', 'Inflation and Purchasing Power'],
        ['risk-and-return', 'Risk and Return'],
        ['stocks-basics', 'Stocks Basics'],
        ['bonds-basics', 'Bonds Basics'],
        ['mutual-funds', 'Mutual Funds'],
        ['index-funds-and-etfs', 'Index Funds and ETFs'],
        ['diversification', 'Diversification'],
        ['asset-allocation', 'Asset Allocation'],
        ['starting-with-little', 'Starting with Little'],
        ['what-to-avoid', 'What to Avoid'],
      ]},
      { slug: 'retirement-planning', name: 'Retirement Planning', desc: '401(k), IRA, Social Security, and how to build a retirement that actually works.', hours: 3, lessons: [
        ['the-time-value-of-starting-early', 'The Time Value of Starting Early'],
        ['401k-basics', '401(k) Basics'],
        ['ira-basics', 'IRA Basics'],
        ['self-employed-retirement', 'Retirement for the Self-Employed'],
        ['how-much-do-you-need', 'How Much Do You Need?'],
        ['social-security-reality', 'Social Security Reality'],
        ['withdrawal-rules', 'Withdrawal Rules'],
      ]},
      { slug: 'taxes-for-individuals', name: 'Taxes for Individuals', desc: 'Tax brackets, deductions, W-2 vs. 1099, filing, and getting the most from your return.', hours: 3, lessons: [
        ['tax-brackets', 'Tax Brackets'],
        ['w2-vs-1099', 'W-2 vs. 1099'],
        ['withholding', 'Withholding'],
        ['tax-forms', 'Tax Forms'],
        ['standard-vs-itemized', 'Standard vs. Itemized Deductions'],
        ['tax-deductions', 'Tax Deductions'],
        ['tax-advantaged-accounts', 'Tax-Advantaged Accounts'],
        ['free-filing-options', 'Free Filing Options'],
        ['when-to-get-help', 'When to Get Help'],
      ]},
    ],
  },
  {
    slug: 'psychology', name: 'Psychology',
    desc: 'How the mind works — from neurons and perception to development, personality, and social behavior.',
    icon: '🧠', order: 10,
    courses: [
      { slug: 'abnormal-psychology', name: 'Abnormal Psychology', desc: 'Mental disorders, diagnosis, treatment, and how to access help.', hours: 4, lessons: [
        ['what-is-abnormal', 'What Is Abnormal?'],
        ['diagnosing-disorders', 'Diagnosing Disorders'],
        ['anxiety-disorders', 'Anxiety Disorders'],
        ['mood-disorders', 'Mood Disorders'],
        ['psychotherapy', 'Psychotherapy'],
        ['medication', 'Medication'],
        ['accessing-help', 'Accessing Help'],
      ]},
      { slug: 'developmental-psychology', name: 'Developmental Psychology', desc: 'How people grow and change from birth through old age — cognitively, emotionally, and socially.', hours: 3, lessons: [
        ['prenatal-and-infant', 'Prenatal Development and Infancy'],
        ['attachment', 'Attachment'],
        ['childhood-and-adolescence', 'Childhood and Adolescence'],
        ['cognitive-development', 'Cognitive Development'],
        ['identity-formation', 'Identity Formation'],
        ['adulthood-and-aging', 'Adulthood and Aging'],
      ]},
      { slug: 'emotion-and-motivation', name: 'Emotion & Motivation', desc: 'What emotions are, what drives behavior, personality, and how people cope with stress.', hours: 3, lessons: [
        ['what-emotions-are', 'What Emotions Are'],
        ['theories-of-motivation', 'Theories of Motivation'],
        ['stress-and-coping', 'Stress and Coping'],
        ['personality-theories', 'Personality Theories'],
        ['personality-assessment', 'Personality Assessment'],
        ['nature-vs-nurture', 'Nature vs. Nurture'],
      ]},
      { slug: 'intro-to-psychology', name: 'Introduction to Psychology', desc: 'The history, methods, perspectives, and biology of psychology.', hours: 3, lessons: [
        ['what-is-psychology', 'What Is Psychology?'],
        ['history-of-psychology', 'History of Psychology'],
        ['major-perspectives', 'Major Perspectives'],
        ['research-methods', 'Research Methods'],
        ['neurons-and-the-brain', 'Neurons and the Brain'],
        ['brain-structure-and-function', 'Brain Structure and Function'],
        ['genetics-and-behavior', 'Genetics and Behavior'],
      ]},
      { slug: 'perception-and-cognition', name: 'Perception & Cognition', desc: 'How we sense the world, pay attention, form memories, and think.', hours: 3, lessons: [
        ['how-senses-work', 'How Senses Work'],
        ['perception-vs-reality', 'Perception vs. Reality'],
        ['attention', 'Attention'],
        ['how-memory-works', 'How Memory Works'],
        ['memory-failures', 'Memory Failures'],
        ['thinking-and-problem-solving', 'Thinking and Problem-Solving'],
        ['language-and-thought', 'Language and Thought'],
      ]},
      { slug: 'social-psychology', name: 'Social Psychology', desc: 'How people think, feel, and behave in social situations — conformity, obedience, prejudice, and more.', hours: 3, lessons: [
        ['conformity', 'Conformity'],
        ['obedience', 'Obedience'],
        ['persuasion', 'Persuasion'],
        ['prejudice-and-discrimination', 'Prejudice and Discrimination'],
        ['reducing-prejudice', 'Reducing Prejudice'],
        ['prosocial-behavior', 'Prosocial Behavior'],
        ['group-dynamics', 'Group Dynamics'],
      ]},
    ],
  },
  {
    slug: 'sciences', name: 'Sciences',
    desc: 'Biology, chemistry, physics, earth science, astronomy, and the scientific method — the foundations of natural knowledge.',
    icon: '🔬', order: 11,
    courses: [
      { slug: 'astronomy', name: 'Astronomy', desc: 'The solar system, stars, galaxies, and the history and future of the universe.', hours: 3, lessons: [
        ['the-big-bang', 'The Big Bang'],
        ['the-sun', 'The Sun'],
        ['planets', 'Planets'],
        ['moons-and-asteroids', 'Moons and Asteroids'],
        ['stars-and-stellar-evolution', 'Stars and Stellar Evolution'],
        ['galaxies', 'Galaxies'],
        ['space-exploration', 'Space Exploration'],
      ]},
      { slug: 'biology', name: 'Biology', desc: 'Cells, genetics, evolution, ecosystems, and the science of life.', hours: 5, lessons: [
        ['cell-theory', 'Cell Theory'],
        ['cell-structure', 'Cell Structure'],
        ['cell-processes', 'Cell Processes'],
        ['cell-division', 'Cell Division'],
        ['dna-and-genes', 'DNA and Genes'],
        ['heredity', 'Heredity'],
        ['mutations-and-variation', 'Mutations and Variation'],
        ['natural-selection', 'Natural Selection'],
        ['classification-of-life', 'Classification of Life'],
        ['biodiversity', 'Biodiversity'],
        ['ecosystems', 'Ecosystems'],
        ['biotechnology', 'Biotechnology'],
      ]},
      { slug: 'chemistry', name: 'Chemistry', desc: 'Atoms, elements, bonding, reactions, acids and bases, and the periodic table.', hours: 5, lessons: [
        ['atoms-and-elements', 'Atoms and Elements'],
        ['atomic-structure', 'Atomic Structure'],
        ['isotopes-and-radioactivity', 'Isotopes and Radioactivity'],
        ['electron-configuration', 'Electron Configuration'],
        ['ionic-bonds', 'Ionic Bonds'],
        ['covalent-bonds', 'Covalent Bonds'],
        ['naming-compounds', 'Naming Compounds'],
        ['types-of-reactions', 'Types of Reactions'],
        ['balancing-equations', 'Balancing Equations'],
        ['stoichiometry', 'Stoichiometry'],
        ['acids-and-bases', 'Acids and Bases'],
      ]},
      { slug: 'earth-science', name: 'Earth Science', desc: 'Plate tectonics, rocks, the atmosphere, weather, climate change, and our planet.', hours: 4, lessons: [
        ['earth-layers', 'Earth Layers'],
        ['plate-tectonics', 'Plate Tectonics'],
        ['earthquakes-and-volcanoes', 'Earthquakes and Volcanoes'],
        ['rocks-and-minerals', 'Rocks and Minerals'],
        ['the-atmosphere', 'The Atmosphere'],
        ['weather-systems', 'Weather Systems'],
        ['climate-and-climate-change', 'Climate and Climate Change'],
        ['human-environmental-impact', 'Human Environmental Impact'],
      ]},
      { slug: 'physics', name: 'Physics', desc: 'Motion, forces, energy, waves, electricity, and the laws that govern the physical world.', hours: 5, lessons: [
        ['kinematics', 'Kinematics'],
        ['newtons-laws', "Newton's Laws"],
        ['gravity', 'Gravity'],
        ['friction-and-momentum', 'Friction and Momentum'],
        ['work-and-energy', 'Work and Energy'],
        ['heat-and-thermodynamics', 'Heat and Thermodynamics'],
        ['waves', 'Waves'],
        ['electricity-and-magnetism', 'Electricity and Magnetism'],
      ]},
      { slug: 'scientific-method', name: 'The Scientific Method', desc: 'Observation, hypothesis, experiment, data, and how science actually works.', hours: 2, lessons: [
        ['observation-and-hypothesis', 'Observation and Hypothesis'],
        ['experiments-and-controls', 'Experiments and Controls'],
        ['data-and-conclusions', 'Data and Conclusions'],
        ['peer-review-and-replication', 'Peer Review and Replication'],
      ]},
    ],
  },
  {
    slug: 'technology-and-computing', name: 'Technology & Computing',
    desc: 'How computers work, programming, the web, data, cybersecurity, and AI literacy.',
    icon: '💻', order: 12,
    courses: [
      { slug: 'ai-and-automation-literacy', name: 'AI & Automation Literacy', desc: 'What AI is, how it works, what it can and cannot do, and how to use it responsibly.', hours: 3, lessons: [
        ['what-ai-actually-is', 'What AI Actually Is'],
        ['how-machine-learning-works', 'How Machine Learning Works'],
        ['large-language-models', 'Large Language Models'],
        ['using-ai-tools', 'Using AI Tools'],
        ['ai-ethics-and-bias', 'AI Ethics and Bias'],
        ['ai-and-work', 'AI and Work'],
      ]},
      { slug: 'cybersecurity-basics', name: 'Cybersecurity Basics', desc: 'Passwords, encryption, common attacks, and how to protect yourself online.', hours: 3, lessons: [
        ['passwords-and-authentication', 'Passwords and Authentication'],
        ['encryption-basics', 'Encryption Basics'],
        ['common-attacks', 'Common Attacks'],
        ['how-breaches-happen', 'How Breaches Happen'],
        ['personal-security-practices', 'Personal Security Practices'],
        ['securing-devices', 'Securing Devices'],
        ['network-security', 'Network Security'],
      ]},
      { slug: 'data-and-spreadsheets', name: 'Data & Spreadsheets', desc: 'Spreadsheet fundamentals, formulas, pivot tables, charts, and a taste of SQL.', hours: 3, lessons: [
        ['spreadsheet-basics', 'Spreadsheet Basics'],
        ['common-functions', 'Common Functions'],
        ['sorting-and-filtering', 'Sorting and Filtering'],
        ['data-cleaning', 'Data Cleaning'],
        ['pivot-tables', 'Pivot Tables'],
        ['charts-and-visualization', 'Charts and Visualization'],
        ['introduction-to-sql', 'Introduction to SQL'],
      ]},
      { slug: 'how-computers-work', name: 'How Computers Work', desc: 'Hardware, operating systems, files, the command line, and what happens when you run a program.', hours: 3, lessons: [
        ['cpu-memory-storage', 'CPU, Memory, and Storage'],
        ['input-output-devices', 'Input and Output Devices'],
        ['how-data-is-stored', 'How Data Is Stored'],
        ['what-is-an-operating-system', 'What Is an Operating System?'],
        ['files-and-directories', 'Files and Directories'],
        ['processes-and-memory', 'Processes and Memory'],
        ['command-line-basics', 'Command Line Basics'],
      ]},
      { slug: 'internet-and-networking', name: 'Internet & Networking', desc: 'How the internet works — IP addresses, DNS, HTTP, routers, and VPNs.', hours: 3, lessons: [
        ['routers-and-wifi', 'Routers and Wi-Fi'],
        ['ip-addresses-and-dns', 'IP Addresses and DNS'],
        ['packets-and-routing', 'Packets and Routing'],
        ['http-and-https', 'HTTP and HTTPS'],
        ['ports-and-protocols', 'Ports and Protocols'],
        ['vpns-and-privacy', 'VPNs and Privacy'],
      ]},
      { slug: 'introduction-to-programming', name: 'Introduction to Programming', desc: 'Variables, logic, loops, functions, and the fundamentals of writing code.', hours: 5, lessons: [
        ['what-is-programming', 'What Is Programming?'],
        ['variables-and-data-types', 'Variables and Data Types'],
        ['operators-and-expressions', 'Operators and Expressions'],
        ['input-and-output', 'Input and Output'],
        ['conditionals', 'Conditionals'],
        ['loops', 'Loops'],
        ['functions', 'Functions'],
        ['lists-and-arrays', 'Lists and Arrays'],
        ['dictionaries', 'Dictionaries'],
        ['reading-and-writing-files', 'Reading and Writing Files'],
        ['debugging', 'Debugging'],
      ]},
      { slug: 'web-development-basics', name: 'Web Development Basics', desc: 'HTML, CSS, JavaScript, the DOM, and how to build and style a web page.', hours: 5, lessons: [
        ['what-is-html', 'What Is HTML?'],
        ['html-elements', 'HTML Elements'],
        ['forms-and-links', 'Forms and Links'],
        ['how-css-works', 'How CSS Works'],
        ['layout-with-css', 'Layout with CSS'],
        ['responsive-design', 'Responsive Design'],
        ['javascript-basics', 'JavaScript Basics'],
        ['dom-manipulation', 'DOM Manipulation'],
        ['events', 'Events'],
        ['fetch-and-apis', 'Fetch and APIs'],
        ['building-a-page', 'Building a Page'],
      ]},
    ],
  },
  {
    slug: 'trades-and-skilled-work', name: 'Trades & Skilled Work',
    desc: 'Electrical, plumbing, HVAC, welding, carpentry, automotive, and masonry — hands-on skills for real jobs.',
    icon: '🔧', order: 13,
    courses: [
      { slug: 'automotive-basics', name: 'Automotive Basics', desc: 'How cars work, routine maintenance, common repairs, and when to take it to a shop.', hours: 4, lessons: [
        ['the-engine', 'The Engine'],
        ['drivetrain', 'The Drivetrain'],
        ['electrical-systems', 'Automotive Electrical Systems'],
        ['routine-maintenance', 'Routine Maintenance'],
        ['brakes-and-suspension', 'Brakes and Suspension'],
        ['reading-error-codes', 'Reading Error Codes'],
        ['common-repairs', 'Common Repairs'],
        ['when-to-take-it-in', 'When to Take It In'],
      ]},
      { slug: 'carpentry-and-woodworking', name: 'Carpentry & Woodworking', desc: 'Hand tools, power tools, measuring, cutting, joinery, and framing basics.', hours: 4, lessons: [
        ['types-of-wood', 'Types of Wood'],
        ['reading-a-tape-measure', 'Reading a Tape Measure'],
        ['hand-tools', 'Hand Tools'],
        ['power-tools', 'Power Tools'],
        ['cutting-techniques', 'Cutting Techniques'],
        ['joinery-basics', 'Joinery Basics'],
        ['framing-basics', 'Framing Basics'],
        ['finish-carpentry', 'Finish Carpentry'],
      ]},
      { slug: 'electrical-fundamentals', name: 'Electrical Fundamentals', desc: 'Voltage, current, resistance, wiring, panels, safety, and the NEC basics.', hours: 5, lessons: [
        ['voltage-current-resistance', 'Voltage, Current, and Resistance'],
        ['ac-vs-dc', 'AC vs. DC'],
        ['electrical-safety', 'Electrical Safety'],
        ['electrical-tools', 'Electrical Tools'],
        ['wiring-basics', 'Wiring Basics'],
        ['reading-an-electrical-panel', 'Reading an Electrical Panel'],
        ['outlets-and-switches', 'Outlets and Switches'],
        ['gfci-and-afci', 'GFCI and AFCI'],
        ['nec-basics', 'NEC Basics'],
        ['permits-and-inspections', 'Permits and Inspections'],
      ]},
      { slug: 'hvac-fundamentals', name: 'HVAC Fundamentals', desc: 'Heating, cooling, ventilation, refrigerants, thermostats, and preventive maintenance.', hours: 4, lessons: [
        ['heating-systems', 'Heating Systems'],
        ['cooling-systems', 'Cooling Systems'],
        ['ventilation-and-air-quality', 'Ventilation and Air Quality'],
        ['refrigerants', 'Refrigerants'],
        ['thermostats-and-controls', 'Thermostats and Controls'],
        ['hvac-tools', 'HVAC Tools'],
        ['preventive-maintenance', 'Preventive Maintenance'],
        ['troubleshooting-basics', 'Troubleshooting Basics'],
      ]},
      { slug: 'masonry-and-concrete', name: 'Masonry & Concrete', desc: 'How concrete works, mixing, forming, pouring, finishing, and laying brick.', hours: 3, lessons: [
        ['how-concrete-works', 'How Concrete Works'],
        ['mortar-and-mixing', 'Mortar and Mixing'],
        ['forming-and-pouring', 'Forming and Pouring'],
        ['concrete-finishing', 'Concrete Finishing'],
        ['laying-brick', 'Laying Brick'],
        ['masonry-repair', 'Masonry Repair'],
      ]},
      { slug: 'plumbing-basics', name: 'Plumbing Basics', desc: 'Supply and drain systems, pipe materials, common repairs, and water heaters.', hours: 3, lessons: [
        ['supply-and-drain', 'Supply and Drain Systems'],
        ['pipe-materials', 'Pipe Materials'],
        ['fixing-a-leak', 'Fixing a Leak'],
        ['drain-clogs', 'Drain Clogs'],
        ['toilets-and-faucets', 'Toilets and Faucets'],
        ['water-heaters', 'Water Heaters'],
        ['water-pressure', 'Water Pressure'],
      ]},
      { slug: 'welding-fundamentals', name: 'Welding Fundamentals', desc: 'Safety, metal prep, MIG, TIG, stick welding, and reading a weld.', hours: 4, lessons: [
        ['welding-safety', 'Welding Safety'],
        ['metals-and-prep', 'Metals and Prep'],
        ['choosing-a-process', 'Choosing a Process'],
        ['mig-welding', 'MIG Welding'],
        ['stick-welding', 'Stick Welding'],
        ['tig-welding', 'TIG Welding'],
        ['reading-a-weld', 'Reading a Weld'],
      ]},
    ],
  },
]

async function main() {
  console.log('Seeding catalog...')

  for (let si = 0; si < CATALOG.length; si++) {
    const sd = CATALOG[si]
    console.log(`  ${sd.slug}`)

    const subject = await db.subject.upsert({
      where: { slug: sd.slug },
      update: { name: sd.name, description: sd.desc, icon: sd.icon, order: sd.order, publishedAt: new Date() },
      create: { slug: sd.slug, name: sd.name, description: sd.desc, icon: sd.icon, order: sd.order, publishedAt: new Date() },
    })

    for (let ci = 0; ci < sd.courses.length; ci++) {
      const cd = sd.courses[ci]

      const course = await db.course.upsert({
        where: { slug: cd.slug },
        update: { name: cd.name, description: cd.desc, estimatedHours: cd.hours, order: ci + 1, publishedAt: new Date() },
        create: { subjectId: subject.id, slug: cd.slug, name: cd.name, description: cd.desc, estimatedHours: cd.hours, order: ci + 1, publishedAt: new Date() },
      })

      const mod = await db.module.upsert({
        where: { courseId_slug: { courseId: course.id, slug: cd.slug } },
        update: { name: cd.name, order: 1 },
        create: { courseId: course.id, slug: cd.slug, name: cd.name, order: 1 },
      })

      for (let li = 0; li < cd.lessons.length; li++) {
        const [lslug, lname] = cd.lessons[li]
        const contentPath = `${sd.slug}/${cd.slug}/${lslug}.md`

        await db.lesson.upsert({
          where: { moduleId_slug: { moduleId: mod.id, slug: lslug } },
          update: { name: lname, contentPath, order: li + 1 },
          create: { moduleId: mod.id, slug: lslug, name: lname, contentPath, order: li + 1 },
        })
      }
    }
  }

  console.log('Done.')
}

main()
  .catch((e) => { console.error(e); process.exit(1) })
  .finally(async () => { await db.$disconnect(); await pool.end() })
